### ISSUE TITLE
Worker failed to close block reader due to Premature end of Content-Length delimited message body on cold read

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10062]
**Alluxio Version:**
What version of Alluxio are you using?
2.1.0-snaphost

**Describe the bug**
Running Distributed TensorFlow (4 workers) training on alluxio fuse, and the data is stored in OSS, no data in alluxio at the first.

1. The tensorflow training is failed due to failed to read the data: /data/imagenet/train-00464-of-01024

```
10	images/sec: 189.4 +/- 14.3 (jitter = 20.6)	10.731
10	images/sec: 195.6 +/- 13.2 (jitter = 20.9)	9.219
10	images/sec: 195.6 +/- 13.2 (jitter = 20.8)	13.262
10	images/sec: 189.5 +/- 14.3 (jitter = 20.4)	10.236
I1008 09:37:22.397283 139885269550848 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, /data/imagenet/train-00464-of-01024; Input/output error
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[{{node RemoteCall}}]]
	 [[node input_processing/IteratorGetNext (defined at /perseus-demo/tensorflow-demo/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2697) ]]
	 [[{{node cluster_56_1/merge_oidx_273}}]]
```

2. Check the alluxio fuse logs in node 192.168.0.117, looks like it failed to get block id 

```
2019-10-08 09:37:18,488 WARN  GrpcBlockingStream - Received error io.grpc.StatusRuntimeException: UNKNOWN: Premature end of Content-Length delimited message body (expected: 151474249; received: 26878828 for stream (GrpcDataReader{request=block_id: 7801405440
offset: 0
length: 151474249
promote: true
chunk_size: 1048576
open_ufs_block_options {
  ufs_path: "oss://imagenet-huabei5/images/train-00464-of-01024"
  offset_in_file: 0
  block_size: 151474249
  maxUfsReadConcurrency: 2147483647
  mountId: 228572097505313622
  no_cache: false
}
, address=WorkerNetAddress{host=192.168.0.117, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=192.168.0.117, rack=null)}})
2019-10-08 09:37:18,910 ERROR AlluxioFuseFileSystem - Failed to read file /training-data/images/train-00464-of-01024
alluxio.exception.status.UnknownException: Premature end of Content-Length delimited message body (expected: 151474249; received: 26878828 (GrpcDataReader{request=block_id: 7801405440
offset: 0
length: 151474249
promote: true
chunk_size: 1048576
open_ufs_block_options {
  ufs_path: "oss://imagenet-huabei5/images/train-00464-of-01024"
  offset_in_file: 0
  block_size: 151474249
  maxUfsReadConcurrency: 2147483647
  mountId: 228572097505313622
  no_cache: false
}
, address=WorkerNetAddress{host=192.168.0.117, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=192.168.0.117, rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:263)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:244)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:162)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receiveDataMessage(GrpcDataMessageBlockingStream.java:84)
	at alluxio.client.block.stream.GrpcDataReader.readChunk(GrpcDataReader.java:120)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:375)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:253)
	at alluxio.client.file.FileInStream.read(FileInStream.java:183)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:589)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Premature end of Content-Length delimited message body (expected: 151474249; received: 26878828
	at io.grpc.Status.asRuntimeException(Status.java:530)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:168)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
alluxio.exception.status.UnknownException: Premature end of Content-Length delimited message body (expected: 151474249; received: 26878828 (GrpcDataReader{request=block_id: 7801405440
```
The details log
[alluxio-fuse-7m2gc-alluxio-fuse.log](https://github.com/Alluxio/alluxio/files/3702233/alluxio-fuse-7m2gc-alluxio-fuse.log)

3.  I see a lot of the errors in worker logs( 192.168.0.117)

```
2019-10-08 09:37:42,724 WARN  BlockReadHandler - Failed to close block reader for block 3607101440 with error Premature end of Content-Length delimited message body (expected: 148811335; received: 36211319.
2019-10-08 09:37:42,754 WARN  BlockReadHandler - Failed to close block reader for block 12197036032 with error Premature end of Content-Length delimited message body (expected: 152391087; received: 35165166.
2019-10-08 09:37:42,779 WARN  BlockReadHandler - Failed to close block reader for block 6660554752 with error Premature end of Content-Length delimited message body (expected: 141589159; received: 36231221.
2019-10-08 09:37:42,800 WARN  BlockReadHandler - Failed to close block reader for block 4966055936 with error Premature end of Content-Length delimited message body (expected: 140042540; received: 36096377.
```

See the details in the logs:
[alluxio-worker-9nhmp-alluxio-worker.log](https://github.com/Alluxio/alluxio/files/3702329/alluxio-worker-9nhmp-alluxio-worker.log)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
@cheyang  I did some simple investigation. It seems a HTTP response to Alluxio worker from the UFS service (OSS in this case), that the server claimed that the content contained X bytes but only sent Y (<X) bytes. If this is the case, the root cause is below Alluxio layer but either in the UFS connector or the UFS service

https://stackoverflow.com/questions/23152816/premature-end-of-content-length-delimited-message-body-expected

**Comment by cheyang** [comment]
Here is the logs:

[diagnose_alluxio_1570701411.tar.gz](https://github.com/Alluxio/alluxio/files/3711882/diagnose_alluxio_1570701411.tar.gz)

**Comment by cheyang** [comment]
I'm able to reproduce the issue even setting the block size to 32MB:

1. I can see the problem block id is 7801405440 (expected: 33554432; received: 27767820)

```
ed: 27767820 for stream (GrpcDataReader{request=block_id: 7801405440
offset: 0
length: 33554432
promote: true
chunk_size: 1048576
open_ufs_block_options {
  ufs_path: "oss://imagenet-huabei5/images/train-00464-of-01024"
  offset_in_file: 0
  block_size: 33554432
  maxUfsReadConcurrency: 2147483647
  mountId: 4770954595713637123
  no_cache: false
}
, address=WorkerNetAddress{host=192.168.0.117, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=192.168.0.117, rack=null)}})
2019-10-10 16:58:42,487 ERROR AlluxioFuseFileSystem - Failed to read file /training-data/images/train-00464-of-01024
alluxio.exception.status.UnknownException: Premature end of Content-Length delimited message body (expected: 33554432; received: 27767820 (GrpcDataReader{request=block_id: 7801405440
offset: 0
length: 33554432
promote: true
chunk_size: 1048576
open_ufs_block_options {
  ufs_path: "oss://imagenet-huabei5/images/train-00464-of-01024"
  offset_in_file: 0
  block_size: 33554432
  maxUfsReadConcurrency: 2147483647
  mountId: 4770954595713637123
  no_cache: false
}
```

2. I went to the machine 192.168.0.117, check the length of the block 7801405440, its size is 33554432 which is the same as expected.

```
[root@iZhp3b4qysu7phen3sah9sZ ~]# cd /dev/shm/alluxioworker/
[root@iZhp3b4qysu7phen3sah9sZ alluxioworker]# ls -ltr |grep 7801405440
-rwxrwxrwx 1 root root 33554432 Oct 11 00:58 7801405440
```

**Comment by cheyang** [comment]
I'm able to see such error:
```
2019-10-12 07:50:17,413 WARN  BlockReadHandler - Failed to close block reader for block 12062818304 with error.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 33554432; received: 27506068
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
        at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
        at org.apache.http.conn.BasicManagedEntity.streamClosed(BasicManagedEntity.java:166)
        at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
        at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
        at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
        at alluxio.underfs.MultiRangeObjectInputStream.closeStream(MultiRangeObjectInputStream.java:115)
        at alluxio.underfs.MultiRangeObjectInputStream.close(MultiRangeObjectInputStream.java:53)
        at alluxio.worker.block.UfsInputStreamManager.release(UfsInputStreamManager.java:137)
        at alluxio.worker.block.UnderFileSystemBlockReader.close(UnderFileSystemBlockReader.java:263)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.completeRequest(BlockReadHandler.java:88)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.completeRequest(BlockReadHandler.java:70)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:385)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:293)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by cheyang** [comment]
All the logs: [diagnose_alluxio_1570866636.tar.gz](https://github.com/Alluxio/alluxio/files/3720346/diagnose_alluxio_1570866636.tar.gz)

**Comment by cheyang** [comment]
But I think the real Error which causes the read failed is

```
2019-10-12 07:50:13,695 ERROR AlluxioFuseFileSystem - Failed to read file /images/train-00233-of-01024
alluxio.exception.status.UnknownException: Premature end of Content-Length delimited message body (expected: 33554432; received: 27393063 (GrpcDataReader{request=block_id: 3925868544
offset: 0
length: 33554432
promote: true
chunk_size: 1048576
open_ufs_block_options {
  ufs_path: "oss://imagenet-huabei5/images/train-00233-of-01024"
  offset_in_file: 0
  block_size: 33554432
  maxUfsReadConcurrency: 2147483647
  mountId: 1
  no_cache: false
}
, address=WorkerNetAddress{host=192.168.0.195, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=192.168.0.195, rack=null)}})
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
        at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:263)
        at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:244)
        at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:162)
```

And the related error is in alluxio-worker-4zm6r-alluxio-worker.log.


```
2019-10-12 07:50:11,160 WARN  AbstractReadHandler - Exception occurred while reading data for read request alluxio.worker.grpc.BlockReadRequest@cba1b70.: Premature end of Content-Length delimited message body (expected: 33554432; received: 27393063
```

**Comment by cheyang** [comment]
I'm trying to upgrade aliyun OSS to 3.6.0, and test again.

```
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 33554432; received: 26980384
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:118)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at alluxio.underfs.MultiRangeObjectInputStream.read(MultiRangeObjectInputStream.java:80)
        at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:454)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:278)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1118)
        at alluxio.worker.block.UnderFileSystemBlockReader.transferTo(UnderFileSystemBlockReader.java:223)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:110)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:70)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:325)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:293)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
And also see similar issue: https://discuss.hail.is/t/i-am-trying-to-import-vcf-but-i-receive-an-error-connectionclosedexception-premature-end-of-content-length-delimited-message-body/1051/2

Any hints? @apc999

**Comment by cheyang** [comment]
The build I tested is https://github.com/Alluxio/alluxio/pull/10049

```
[INFO] +- com.aliyun.oss:aliyun-sdk-oss:jar:3.6.0:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- org.jdom:jdom:jar:1.1:compile
[INFO] |  +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO] |  |  \- stax:stax-api:jar:1.0.1:compile
[INFO] |  +- com.aliyun:aliyun-java-sdk-core:jar:3.4.0:compile
[INFO] |  +- com.aliyun:aliyun-java-sdk-ram:jar:3.0.0:compile
[INFO] |  +- com.aliyun:aliyun-java-sdk-sts:jar:3.0.0:compile
[INFO] |  \- com.aliyun:aliyun-java-sdk-ecs:jar:4.2.0:compile

```

**Comment by cheyang** [comment]
I tried to add some debug info like: https://github.com/cheyang/alluxio/commit/14e72173e567a966095af0cfb00060d1f27376f9

And I found it seems not took too much time:

```
2019-10-14 02:08:26,265 WARN  AbstractReadHandler - Exception occurred while reading data for read request alluxio.worker.grpc.BlockReadRequest@6a30091f, and it took 15 ms
2019-10-14 02:08:26,266 WARN  AbstractReadHandler - Exception occurred while reading data for read request alluxio.worker.grpc.BlockReadRequest@6a30091f.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 33554432; received: 31451830
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:118)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
```

**Comment by apc999** [comment]
taken over by https://github.com/Alluxio/alluxio/issues/10109
