### ISSUE TITLE
Worker registers timeout when starting

### ISSUE THREAD

**Issue by liuhongtong** [Alluxio/alluxio#10061]
**Alluxio Version:**
2.0.1
**Describe the bug**
Worker registers timeout when starting

There is no new log in master. worker log:
```
2019-10-08 17:22:55,654 ERROR ProcessUtils - Uncaught exception while running Alluxio worker, stopping it and exiting. Exception "alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.CancelledException: HTTP/2 error code: CANCEL
Received Rst Stream", Root Cause "io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream"
alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.CancelledException: HTTP/2 error code: CANCEL
Received Rst Stream
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:376)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:321)
	at alluxio.worker.block.BlockMasterClient.register(BlockMasterClient.java:222)
	at alluxio.worker.block.BlockMasterSync.registerWithMaster(BlockMasterSync.java:106)
	at alluxio.worker.block.BlockMasterSync.<init>(BlockMasterSync.java:93)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:214)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:77)
	at alluxio.Registry.start(Registry.java:131)
	at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:283)
	at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:235)
	at alluxio.ProcessUtils.run(ProcessUtils.java:35)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:70)
Caused by: alluxio.exception.status.CancelledException: HTTP/2 error code: CANCEL
Received Rst Stream
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:124)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:209)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:361)
	... 11 more
Caused by: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at alluxio.grpc.BlockMasterWorkerServiceGrpc$BlockMasterWorkerServiceBlockingStub.registerWorker(BlockMasterWorkerServiceGrpc.java:477)
	at alluxio.worker.block.BlockMasterClient.lambda$register$6(BlockMasterClient.java:223)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:359)
	... 11 more
2019-10-08 17:22:55,671 INFO  GrpcDataServer - Shutting down RPC Server at 0.0.0.0/0.0.0.0:29999.
```

**To Reproduce**
N/A

**Expected behavior**
N/A

**Urgency**
N/A

**Additional context**
N/A

**Comment by ZacBlanco** [comment]
@liuhongtong can you share your `alluxio-site.properties` for your master+worker?

**Comment by ns1123** [comment]
@liuhongtong I've seen this occur when the worker has a master address with "master-host:19999" instead of "master-host:19998". As @ZacBlanco mentioned, posting your configuration settings will help identify the issue.

**Comment by liuhongtong** [comment]
Master and worker has the same configuration. `alluxio.master.hostname` is an IP address.
```
alluxio.master.hostname=x.x.x.x
alluxio.security.authorization.permission.enabled=false
alluxio.security.authentication.type=NOSASL
alluxio.worker.tieredstore.levels=3
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk/alluxio/alluxio-blockpool
alluxio.worker.tieredstore.level0.dirs.quota=200GB
alluxio.worker.tieredstore.level1.alias=SSD
alluxio.worker.tieredstore.level1.dirs.path=/data12/alluxio/alluxio-blockpool,/data13/alluxio/alluxio-blockpool
alluxio.worker.tieredstore.level1.dirs.quota=1700GB
alluxio.worker.tieredstore.level2.alias=HDD
alluxio.worker.tieredstore.level2.dirs.path=/data0/alluxio/alluxio-blockpool,/data1/alluxio/alluxio-blockpool,/data2/alluxio/alluxio-blockpool,/data3/alluxio/alluxio-blockpool,/data4/alluxio/alluxio-blockpool,/data5/alluxio/alluxio-blockpool,/data6/alluxio/alluxio-blockpool,/data7/alluxio/alluxio-blockpool,/data8/alluxio/alluxio-blockpool,/data9/alluxio/alluxio-blockpool,/data10/alluxio/alluxio-blockpool,/data11/alluxio/alluxio-blockpool
alluxio.worker.tieredstore.level2.dirs.quota=8700GB
alluxio.job.master.job.capacity=1000000
alluxio.user.network.writer.flush.timeout=3min
```

**Comment by ZacBlanco** [comment]
@liuhongtong thanks for providing your config.

I don't see anything that stands out here. Have you confirmed that your master configuration and worker configuration are identical aside from the configured storage?

If possible, can you provide a reliable set of steps to reproduce this? Without the ability to reproduce we can't fix the issue (if there is one)

**Comment by rastogiasr** [comment]
If this issue is still valid, re-open the issue with steps to reproduce.

**Comment by shenghui361** [comment]
Alluxio Version:
2.5.0-3

`2021-05-25 16:11:59,428 INFO  ProcessUtils - Running under Java 1.8.0_92
2021-05-25 16:15:50,424 WARN  BlockMasterClient - Register(workerId=2402720825125147223) exits with exception [alluxio.exception.status.UnavailableException: Failed after 1 attempts: alluxio.exception.status.CancelledException: RST_STREAM closed stream. HTTP/2 error code: CANCEL] in 225523 ms (>=10000ms)
2021-05-25 16:15:50,425 ERROR ProcessUtils - Uncaught exception while running Alluxio worker @cnsz22plivyf:29999, stopping it and exiting. Exception "alluxio.exception.status.UnavailableException: Failed after 1 attempts: alluxio.exception.status.CancelledException: RST_STREAM closed stream. HTTP/2 error code: CANCEL", Root Cause "io.grpc.StatusRuntimeException: CANCELLED: RST_STREAM closed stream. HTTP/2 error code: CANCEL"
alluxio.exception.status.UnavailableException: Failed after 1 attempts: alluxio.exception.status.CancelledException: RST_STREAM closed stream. HTTP/2 error code: CANCEL
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:422)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.worker.block.BlockMasterClient.register(BlockMasterClient.java:232)
        at alluxio.worker.block.BlockMasterSync.registerWithMaster(BlockMasterSync.java:109)
        at alluxio.worker.block.BlockMasterSync.<init>(BlockMasterSync.java:96)
        at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:238)
        at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:88)
        at alluxio.Registry.start(Registry.java:131)
        at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:283)
        at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:235)
        at alluxio.ProcessUtils.run(ProcessUtils.java:36)
        at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:80)
Caused by: alluxio.exception.status.CancelledException: RST_STREAM closed stream. HTTP/2 error code: CANCEL
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:129)
        at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:407)
        ... 12 more
Caused by: io.grpc.StatusRuntimeException: CANCELLED: RST_STREAM closed stream. HTTP/2 error code: CANCEL
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at alluxio.grpc.BlockMasterWorkerServiceGrpc$BlockMasterWorkerServiceBlockingStub.registerWorker(BlockMasterWorkerServiceGrpc.java:472)
        at alluxio.worker.block.BlockMasterClient.lambda$register$6(BlockMasterClient.java:233)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:405)
        ... 12 more
2021-05-25 16:15:50,428 INFO  GrpcDataServer - Shutting down Alluxio worker gRPC server at 0.0.0.0/0.0.0.0:29999.`
