### ISSUE TITLE
Worker failed to close block reader due to Premature end of Content-Length delimited message body on cold read

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10109]
**Alluxio Version:**
2.1.0-snaphost

**Describe the bug**

Running Distributed TensorFlow training on alluxio fuse, and the data is stored in Aliyun OSS, no data in alluxio at the first.

<a name="4962a6c3"></a>
### Problem Analysis

1. The tensorflow training is crashed due to failed to reading the data: `/data/imagenet/train-00368-of-01024`

```
2019-10-15T08:26:36.096784982Z I1015 08:26:36.095052 139990391076608 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, /data/imagenet/train-00368-of-01024; Input/output error
2019-10-15T08:26:36.09680675Z 	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
2019-10-15T08:26:36.096811939Z 	 [[{{node RemoteCall}}]]
2019-10-15T08:26:36.09681583Z 	 [[node input_processing/IteratorGetNext (defined at /perseus-demo/tensorflow-demo/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2697) ]]
2019-10-15T08:26:36.096819897Z 	 [[{{node cluster_56_1/merge_oidx_273}}]]
2019-10-15T08:26:36.649951311Z [iZhp3bku0ru8vuxq08lorwZ:7347] *** An error occurred in MPI_Allreduce
2019-10-15T08:26:36.649969165Z [iZhp3bku0ru8vuxq08lorwZ:7347] *** reported by process [3067871233,6]
2019-10-15T08:26:36.649973593Z [iZhp3bku0ru8vuxq08lorwZ:7347] *** on communicator MPI COMMUNICATOR 7 DUP FROM 0
2019-10-15T08:26:36.649976871Z [iZhp3bku0ru8vuxq08lorwZ:7347] *** MPI_ERR_OTHER: known error not in list
2019-10-15T08:26:36.649991302Z [iZhp3bku0ru8vuxq08lorwZ:7347] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
2019-10-15T08:26:36.64999497Z [iZhp3bku0ru8vuxq08lorwZ:7347] ***    and potentially your MPI job)
2019-10-15T08:26:37.668226187Z [iZhp3bku0ru8vuxq08lorxZ:09154] 2 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
2019-10-15T08:26:37.668245459Z [iZhp3bku0ru8vuxq08lorxZ:09154] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

2. Check the logs of the fuse, it shows that :Failed to read file /images/train-00368-of-01024<br />
alluxio.exception.status.UnknownException: Premature end of Content-Length delimited message body (expected: 33554432; received: 27661128 (GrpcDataReader{request=block_id: 6190792704

And Block id which has problem is `6190792704`

```
2019-10-15 08:26:31,827 ERROR AlluxioFuseFileSystem - Failed to read file /images/train-00368-of-01024
alluxio.exception.status.UnknownException: Premature end of Content-Length delimited message body (expected: 33554432; received: 27661128 (GrpcDataReader{request=block_id: 6190792704
offset: 0
length: 33554432
promote: true
chunk_size: 1048576
open_ufs_block_options {
  ufs_path: "oss://imagenet-huabei5/images/train-00368-of-01024"
  offset_in_file: 0
  block_size: 33554432
  maxUfsReadConcurrency: 2147483647
  mountId: 1
  no_cache: false
}
, address=WorkerNetAddress{host=192.168.0.120, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=192.168.0.120, rack=null)}})
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
        at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:261)
        at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:242)
        at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:162)
        at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receiveDataMessage(GrpcDataMessageBlockingStream.java:84)
        at alluxio.client.block.stream.GrpcDataReader.readChunk(GrpcDataReader.java:120)
        at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:375)
        at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:253)
        at alluxio.client.file.FileInStream.read(FileInStream.java:183)
        at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:589)
        at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
        at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Premature end of Content-Length delimited message body (expected: 33554432; received: 27661128
```

3. And at the same time, looking into the log of the worker. the data reading of block **6190792704** began at **1571127990358(08:26:30,358)**, then failed at **1571127990372(08:26:30,372)**. It is about **14 ms**. (worker.log)

```
2019-10-15 08:26:30,358 INFO  AbstractReadHandler - Begin read data for read request 1090519040 begin at 1571127990358
2019-10-15 08:26:30,372 WARN  AbstractReadHandler - Exception occurred while reading data for read request 6190792704 begin at 1571127990358, and fail at 1571127990372
2019-10-15 08:26:30,373 WARN  AbstractReadHandler - Exception occurred while reading data for read request alluxio.worker.grpc.BlockReadRequest@6f15dc2c, and it took 14 ms
2019-10-15 08:26:30,374 WARN  AbstractReadHandler - Exception occurred while reading data for read request alluxio.worker.grpc.BlockReadRequest@6f15dc2c.
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 33554432; received: 27661128
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:118)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at alluxio.underfs.MultiRangeObjectInputStream.read(MultiRangeObjectInputStream.java:80)
        at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:454)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:278)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1118)
        at alluxio.worker.block.UnderFileSystemBlockReader.transferTo(UnderFileSystemBlockReader.java:223)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:110)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:70)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:328)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:293)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

4. Now check the offset of the block id **6190792704**, we can find the offset of the block id is 0. (worker.log)

```
alluxio fs stat /images/train-00368-of-01024
/images/train-00368-of-01024 is a file path.
FileInfo{fileId=6207569919, name=train-00368-of-01024, path=/images/train-00368-of-01024, ufsPath=oss://imagenet-huabei5/images/train-00368-of-01024, length=149248038, blockSizeBytes=33554432, creationTimeMs=1571126855056, completed=true, folder=false, pinned=false, pinnedlocation=[], cacheable=true, persisted=true, blockIds=[6190792704, 6190792705, 6190792706, 6190792707, 6190792708], inMemoryPercentage=22, lastModificationTimesMs=1570713748000, ttl=-1, lastAccessTimesMs=1571127894576, ttlAction=DELETE, owner=, group=, mode=511, persistenceState=PERSISTED, mountPoint=false, replicationMax=-1, replicationMin=0, fileBlockInfos=[FileBlockInfo{blockInfo=BlockInfo{id=6190792704, length=33554432, locations=[BlockLocation{workerId=7833376687220055784, address=WorkerNetAddress{host=192.168.0.120, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=192.168.0.120, rack=null)}, tierAlias=MEM, mediumType=MEM}]}, offset=0, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=6190792705, length=33554432, locations=[]}, offset=33554432, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=6190792706, length=33554432, locations=[]}, offset=67108864, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=6190792707, length=33554432, locations=[]}, offset=100663296, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=6190792708, length=15030310, locations=[]}, offset=134217728, ufsLocations=[]}], mountId=1, inAlluxioPercentage=22, ufsFingerprint=TYPE|FILE UFS|oss OWNER|_ GROUP|_ MODE|511 CONTENT_HASH|12C3B3BCE7601CD0210F8948B608C2F7-59 , acl=user::rwx,group::rwx,other::rwx, defaultAcl=}
Containing the following blocks:
BlockInfo{id=6190792704, length=33554432, locations=[BlockLocation{workerId=7833376687220055784, address=WorkerNetAddress{host=192.168.0.120, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=192.168.0.120, rack=null)}, tierAlias=MEM, mediumType=MEM}]}
BlockInfo{id=6190792705, length=33554432, locations=[]}
BlockInfo{id=6190792706, length=33554432, locations=[]}
BlockInfo{id=6190792707, length=33554432, locations=[]}
BlockInfo{id=6190792708, length=15030310, locations=[]}
```

And we also find that the block looks good in block size, it's 33554432

```
# ls -ltr /dev/shm/alluxioworker/6190792704
-rwxrwxrwx 1 root root 33554432 Oct 15 16:26 /dev/shm/alluxioworker/6190792704
```

5. And we can find the function `mOssClient.getObject(req);` started at **1571127894663 (08:24:54,663)**, and the `getObject` returned at **1571127894719(08:24:54,719)**, it took **56ms**. (worker.log)

```
2019-10-15 08:24:54,663 INFO  OSSInputStream - Open OSS Key images/train-00368-of-01024 with startPos 0 at 1571127894663
2019-10-15 08:24:54,719 INFO  OSSInputStream - Open OSS Key images/train-00368-of-01024 and get stream with startPos 0 at 1571127894719
2019-10-15 08:24:54,719 INFO  OSSInputStream - Calling createStream took: 56 ms
2019-10-15 08:26:36,074 INFO  OSSInputStream - Open OSS Key images/train-00368-of-01024 with startPos 10423649 at 1571127996074
2019-10-15 08:26:36,077 INFO  OSSInputStream - Open OSS Key images/train-00368-of-01024 and get stream with startPos 10423649 at 1571127996077
2019-10-15 08:26:36,740 INFO  OSSInputStream - Open OSS Key images/train-00368-of-01024 with startPos 0 at 1571127996740
2019-10-15 08:26:36,744 INFO  OSSInputStream - Open OSS Key images/train-00368-of-01024 and get stream with startPos 0 at 1571127996744
```

6. In conclusion, we find it started from connection established(getObject returned) at **1571127894719(08:24:54,719)**, and read data at **1571127990358(08:26:30,358)**. It took (1571127990358 - 1571127894719) =  95639 ms = **95.639 seconds** from connection established to read data. and due to `alluxio.underfs.oss.socket.timeout=50sec`, I think the connection is closed by client side.
6. Other interesting findings: I find the block 6190792704 is called many times before the failed one. It means `AbstractReadHandler:run` are called many times, does it indicates the `alluxio fuse(client)` requests this block many times?

```
grep 6190792704 *worker.log
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:54,620 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127894620
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:55,099 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127895099
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:55,245 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127895245
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:55,516 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127895516
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:55,722 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127895722
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:55,956 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127895956
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:56,124 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127896124
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:56,247 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127896247
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:56,395 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127896395
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:24:56,641 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127896641
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:26:28,826 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127988826
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:26:29,665 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127989665
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:26:30,358 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127990358
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:26:30,372 WARN  AbstractReadHandler - Exception occurred while reading data for read request 6190792704 begin at 1571127990358, and fail at 1571127990372
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:26:31,867 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127991867
alluxio-worker-q9p7l-alluxio-worker.log:2019-10-15 08:26:36,738 INFO  AbstractReadHandler - Begin read data for read request 6190792704 begin at 1571127996738
```

So questions:

1. Why it took nearly 1 minutes between getting objects
1. The block looks good, what makes this happen
1. How alluxio makes sure it's robust when AWS, OSS is not so stable.
1. Can we add some debug infos so that we can determine such issue in future?

**Comment by cheyang** [comment]
See the attach file:


[readme.txt](https://github.com/Alluxio/alluxio/files/3729106/readme.txt)

**Comment by cheyang** [comment]
Here are all the logs:

[diagnose_alluxio_1571129675.tar.gz](https://github.com/Alluxio/alluxio/files/3729116/diagnose_alluxio_1571129675.tar.gz)

**Comment by cheyang** [comment]
I've uploaded the log file: 
[diagnose_alluxio_1571369553.tar.gz](https://github.com/Alluxio/alluxio/files/3742203/diagnose_alluxio_1571369553.tar.gz)

The file is train-00039-of-01024, and the block id is 14143193088.

The fuse log: alluxio-fuse-wnvl2-alluxio-fuse.log
the worker log: alluxio-worker-6qmsk-alluxio-worker.log

**Comment by apc999** [comment]
discussed with @cheyang , a workaround is to set properties like the following to avoid the error messages on "premature end"

```
alluxio.user.block.size.bytes.default=32MB 
 alluxio.user.network.reader.chunk.size.bytes=32MB # DEFAULT 1MB
```

@calvinjia FYI

**Comment by yuzhu** [comment]
@apc999 has this issue been resolved? or do we need a better solution than this workaround?
