### ISSUE TITLE
Job ID not persistent in job service

### ISSUE THREAD

**Issue by chcn** [Alluxio/alluxio#10133]
**Summary**
When restarting job master and worker, the previous job IDs are lost, and any request to get the old job ID will return exception like 

```alluxio.exception.status.UnknownException: The job of id 1,571,284,390,130 does not exist
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:209)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:374)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:334)
	at alluxio.client.job.RetryHandlingJobMasterClient.getStatus(RetryHandlingJobMasterClient.java:85)
	at alluxio.master.table.transform.TransformManager$JobMonitor.heartbeat(TransformManager.java:205)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: The job of id 1,571,284,390,130 does not exist
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at alluxio.grpc.JobMasterClientServiceGrpc$JobMasterClientServiceBlockingStub.getJobStatus(JobMasterClientServiceGrpc.java:444)
	at alluxio.client.job.RetryHandlingJobMasterClient$1.call(RetryHandlingJobMasterClient.java:87)
	at alluxio.client.job.RetryHandlingJobMasterClient$1.call(RetryHandlingJobMasterClient.java:85)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:372)
```

instead of a more descriptive exception or job status.

**Urgency**
`TableManager` needs a way to find out that a job ID no longer exists.

**Comment by chcn** [comment]
But `JobMaster` gives an explicit exception `2019-10-16 21:19:14,772 WARN  JobMasterClientServiceHandler - Exit (Error): getJobStatus: request=jobId: 1571284390130
, Error=alluxio.exception.JobDoesNotExistException: The job of id 1,571,284,390,130 does not exist`, the `JobMasterClient` should propagate this exception.

**Comment by chcn** [comment]
Fixed: https://github.com/Alluxio/alluxio/pull/10119/files#diff-798f3e7b3cbeb0746a98fd91e4145322L226
