### ISSUE TITLE
Stabilize tests

### ISSUE THREAD

**Issue by ghost** [Alluxio/alluxio#10252]
**Summary**
Some tests, especially integration tests, are flaky. They fail repeatedly on jenkins, but hard to reproduce the failure on our macbook. This ticket keeps track of all the flaky tests we encountered. Add a comment once a test is no longer flaky, in the comment, describe the root cause for the flakiness, or add a link to the PR you make to stabilize the test.

List of flaky tests:

```
Failed tests: 
alluxio.collections.LockPoolTest.parallelInsertTest(alluxio.collections.LockPoolTest)
  Run 1: LockPoolTest.parallelInsertTest:117 expected:<16> but was:<15>
  Run 2: LockPoolTest.parallelInsertTest:117 expected:<16> but was:<15>
```

```
alluxio.server.ft.journal.MultiMasterJournalTest
testTtl(alluxio.server.ft.journal.MultiMasterJournalTest)  Time elapsed: 4.756 sec  <<< ERROR!
java.io.IOException: java.lang.RuntimeException: alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ 0647feca8eb3:34358 after 6 attempts
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)
Caused by: java.lang.RuntimeException: alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ 0647feca8eb3:34358 after 6 attempts
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)
Caused by: alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ 0647feca8eb3:34358 after 6 attempts
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)
Caused by: alluxio.exception.status.UnavailableException: Failed to handshake with master 0647feca8eb3:34358 to load cluster default configuration values: UNAVAILABLE: Network closed for unknown reason
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at alluxio.server.ft.journal.MultiMasterJournalTest.before(MultiMasterJournalTest.java:53)
```

```
alluxio.client.cli.fs.JobServiceFaultToleranceShellTest
distributedMv(alluxio.client.cli.fs.JobServiceFaultToleranceShellTest)  Time elapsed: 7.883 sec  <<< ERROR!
java.io.IOException: java.lang.RuntimeException: alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ 0647feca8eb3:34176 after 1 attempts
	at alluxio.client.cli.fs.JobServiceFaultToleranceShellTest.before(JobServiceFaultToleranceShellTest.java:52)
Caused by: java.lang.RuntimeException: alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ 0647feca8eb3:34176 after 1 attempts
	at alluxio.client.cli.fs.JobServiceFaultToleranceShellTest.before(JobServiceFaultToleranceShellTest.java:52)
Caused by: alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ 0647feca8eb3:34176 after 1 attempts
	at alluxio.client.cli.fs.JobServiceFaultToleranceShellTest.before(JobServiceFaultToleranceShellTest.java:52)
Caused by: alluxio.exception.status.UnavailableException: Failed to handshake with master 0647feca8eb3:34176 to load cluster default configuration values: UNAVAILABLE: Network closed for unknown reason
	at alluxio.client.cli.fs.JobServiceFaultToleranceShellTest.before(JobServiceFaultToleranceShellTest.java:52)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at alluxio.client.cli.fs.JobServiceFaultToleranceShellTest.before(JobServiceFaultToleranceShellTest.java:52)
```

```
alluxio.client.cli.fs.command.CpCommandIntegrationTest
copyFromLocalLarge(alluxio.client.cli.fs.command.CpCommandIntegrationTest)  Time elapsed: 9.39 sec  <<< ERROR!
alluxio.exception.status.InternalException: 
http2 exception (GrpcDataReader{request=block_id: 16777216
offset: 0
length: 16777216
promote: false
chunk_size: 64
open_ufs_block_options {
  ufs_path: "/tmp/alluxio-tests/CpCommandIntegrationTest-copyFromLocalLarge-d5c6f0ad-6980-4660-8aae-fa661e78e4f5/underFSStorage/testFile"
  offset_in_file: 0
  block_size: 16777216
  maxUfsReadConcurrency: 2147483647
  mountId: 1
  no_cache: true
}
, address=WorkerNetAddress{host=0647feca8eb3, rpcPort=37614, dataPort=37614, webPort=46392, domainSocketPath=, tieredIdentity=TieredIdentity(node=0647feca8eb3, rack=null)}})
	at alluxio.client.cli.fs.command.CpCommandIntegrationTest.copyFromLocalLarge(CpCommandIntegrationTest.java:418)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: http2 exception
Caused by: io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
```

**Urgency**
Slows down engineering efficiency A LOT.

**Comment by yuzhu** [comment]
```alluxio.collections.LockPoolTest.parallelInsertTest(alluxio.collections.LockPoolTest)
  Run 1: LockPoolTest.parallelInsertTest:117 expected:<16> but was:<15>
  Run 2: LockPoolTest.parallelInsertTest:117 expected:<16> but was:<15>```

**Comment by calvinjia** [comment]
@gpang have the recent changes been able to address these test stability issues?
