### ISSUE TITLE
This exception occurred when I was creating the master,Ask for help

### ISSUE THREAD

**Issue by SeeMyWorld** [Alluxio/alluxio#10257]
Alluxio Version: master
Describe : This was added to the configuration:-Dalluxio.master.mount.table.root.ufs=10.142.167.220:/
exception:
```
Caused by: java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in scheme name at index 0: 10.142.167.220:/
	at alluxio.uri.StandardURI.<init>(StandardURI.java:65)
	at alluxio.uri.URI$Factory.create(URI.java:128)
	at alluxio.uri.URI$Factory.create(URI.java:107)
	at alluxio.AlluxioURI.<init>(AlluxioURI.java:79)
	at alluxio.underfs.AbstractUfsManager.getRoot(AbstractUfsManager.java:196)
	at alluxio.master.file.DefaultFileSystemMaster.getRootMountInfo(DefaultFileSystemMaster.java:456)
	at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:414)
	at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:395)
	at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:51)
	at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:28)
	at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ZacBlanco** [comment]
@SeeMyWorld you need to specify a scheme for your root UFS.

How else does the Alluxio master know what type of under storage system it is communicating with?

Your UFS scheme will typically be `hdfs://`, `s3a://`, `swift://`, etc. Please refer to the respective under storage documentation at https://docs.alluxio.io for your specific UFS.

**Comment by SeeMyWorld** [comment]
@ZacBlanco We are now using NFS, the NFS in (- Dalluxio. Master. Mount. Table. Root. It = < under_storage_address > )how to configure.     thank

**Comment by ZacBlanco** [comment]
You can't just point to the IP of some NFS. You'll need to set up the NFS mount on that local machine first, and then point to the NFS mount in `alluxio.master.mount.table.root.ufs`. See the documentation: https://docs.alluxio.io/os/user/stable/en/ufs/NFS.html

This would need to be done on every master/worker.

- Configure and mount the NFS filesystem at `/mnt/nfs`
- Set `alluxio.master.mount.table.root.ufs=/mnt/nfs` in `alluxio-site.properties`
- Restart alluxio masters and workers

**Comment by yuzhu** [comment]
@SeeMyWorld you need to mount the nfs on the machine running alluxio, and then specify the mount point as `alluxio.master.mount.table.root.ufs`  

See https://docs.alluxio.io/ee/user/stable/en/ufs/NFS.html?q=nfs for more instructions

**Comment by SeeMyWorld** [comment]
I have done according to this, but this problem still appears. My understanding is that if I configure this in alluxio-site.properties, I don't need to configure this (-dalluxio.mast.mount.table.root.it = < under_storage_address >).

**Comment by ZacBlanco** [comment]
I recommend against using JVM parameters (`-D<property_name>=<value>`) unless you're trying to deploy with docker. `alluxio-site.properties` is recommended way to set properties.

Can you paste your entire `alluxio-site.properties` configuration here? We'll need more context to figure out the issue. From the looks of your previous response. The journal may be misconfigured or the user launching the Alluxio process doesn't have the proper permissions.

**Comment by SeeMyWorld** [comment]
@ZacBlanco Hello, I think it is also the problem of my permission, but now I am using a cloud service deployed k8s, we have not actively set this permission, how should this permission be modified?
`[root@10-10-61-162 conf]# cat alluxio-site.properties
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

# Site specific configuration properties for Alluxio
# Details about all configuration properties https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html

# Common properties
  alluxio.master.hostname=localhost
  alluxio.master.mount.table.root.ufs=/nfs

# Security properties
# alluxio.security.authorization.permission.enabled=true
# alluxio.security.authentication.type=SIMPLE

# Worker properties
# alluxio.worker.memory.size=1GB
# alluxio.worker.tieredstore.levels=1
# alluxio.worker.tieredstore.level0.alias=MEM
# alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk

# User properties
# alluxio.user.file.readtype.default=CACHE_PROMOTE
# alluxio.user.file.writetype.default=MUST_CACHE
`

**Comment by SeeMyWorld** [comment]
@ZacBlanco Hello, I think it is also the problem of my permission, but now I am using a cloud service deployed k8s, we have not actively set this permission, how should this permission be modified?
`[root@10-10-61-162 conf]# cat alluxio-site.properties
\#
\# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
\# (the "License"). You may not use this work except in compliance with the License, which is
\# available at www.apache.org/licenses/LICENSE-2.0
\#
\# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
\# either express or implied, as more fully set forth in the License.
\#
\# See the NOTICE file distributed with this work for information regarding copyright ownership.
\#

\# Site specific configuration properties for Alluxio
\# Details about all configuration properties https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html

\# Common properties
  alluxio.master.hostname=localhost
  alluxio.master.mount.table.root.ufs=/nfs

\# Security properties
\# alluxio.security.authorization.permission.enabled=true
\# alluxio.security.authentication.type=SIMPLE

\# Worker properties
\# alluxio.worker.memory.size=1GB
\# alluxio.worker.tieredstore.levels=1
\# alluxio.worker.tieredstore.level0.alias=MEM
\# alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk

\# User properties
\# alluxio.user.file.readtype.default=CACHE_PROMOTE
\# alluxio.user.file.writetype.default=MUST_CACHE`

**Comment by ZacBlanco** [comment]
Sorry for the delay.

It's possible that the user doesn't have permission at the `/journal` path. You can try configuring the journal path to be something other than `/journal`, but for the containers I think it is slightly more difficult due to k8s volume management if you want the journal to persist between restarts.

Can you outline the steps which you followed to deploy Alluxio in the cloud k8s environment you mentioned? It will affect the steps required to correctly configure the permissions and/or journal volume

**Comment by calvinjia** [comment]
Closing this issue due to inactivity. @SeeMyWorld Feel free to reopen or create another ticket if you run into other issues.

**Comment by np-ftrwei** [comment]
Same issue with v2.8.1.
Setting alluxio.master.mount.table.root.ufs=/mnt/foo etc doesn't work.
Still getting 
ERROR ClientMasterSync - Failed to get master address during initialization alluxio.exception.status.UnavailableException: Failed to handshake with master 10.244.1.34:19998 to load cluster default configuration values: UNAVAILABLE: io exception
