### ISSUE TITLE
Backup command return null if mounted s3 bucket is empty

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#10264]
**Alluxio Version:**
Alluxio master
**Describe the bug**
When an empty S3 bucket is mounted to Alluxio, before any files are written into the bucket, backing up will throw NPE

2019-10-24 12:48:13,514 INFO  DefaultMetaMaster - Backing up to root UFS in directory /alluxio_backups
2019-10-24 12:48:14,998 ERROR MetaMasterClientServiceHandler - Exit (Error): backup: options=localFileSystem: false

java.lang.NullPointerException
        at alluxio.underfs.s3a.S3AUnderFileSystem.getObjectStatus(S3AUnderFileSystem.java:516)
        at alluxio.underfs.ObjectUnderFileSystem.isFile(ObjectUnderFileSystem.java:589)
        at alluxio.underfs.ObjectUnderFileSystem.mkdirs(ObjectUnderFileSystem.java:616)
        at alluxio.underfs.BaseUnderFileSystem.mkdirs(BaseUnderFileSystem.java:184)
        at alluxio.underfs.ObjectUnderFileSystem.mkdirs(ObjectUnderFileSystem.java:636)

**To Reproduce**
Create an empty S3 bucket
Use the empty S3 bucket as a root mount, change the write type to be MUST_CACHE
do some operations (what kind of operation does not matter)
run `fsadmin backup`

**Expected behavior**
Alluxio backup command should not return NPE in whatever cases

**Comment by LuQQiu** [comment]
The details of the workflow that cause the issue is 
```
Backup -> try to create /alluxio_backups folder
(1) call mkdirs(/)  because `/alluxio_backups` is not a directory or a file and parent not exist
(2) call mkdirs("") because `/` is not a directory or file and parent not exists
(3) empty string is not an folder 
When checking if it's a file, getObjectStatus of empty string throws NPE
```

**Comment by LuQQiu** [comment]
Our ObjectUFS root key is full url like s3://<bucket>/
but in nearly all ufs operation, we strip the prefix which is stripping the rootkey.
The fix is to check "/" in isRoot

**Comment by LuQQiu** [comment]
Fixed in https://github.com/Alluxio/alluxio/pull/10276
