### ISSUE TITLE
ProcessUtils reports Root Cause null when a property fails to resolve to a certain type

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#10338]
**Alluxio Version:**
2.1.0-SNAPSHOT

**Describe the bug**
For different wrong value for a key that should be a double, the error message may not be clear. Below are 2 examples. Root Cause is both `null`, which can be misleading.

```
2019-10-28 17:52:36,496 ERROR ProcessUtils - Uncaught exception while running Alluxio worker, stopping it and exiting. Exception "java.lang.RuntimeException: Configuration cannot evaluate key alluxio.worker.tieredstore.level0.watermark.low.ratio as double", Root Cause "null"
java.lang.RuntimeException: Configuration cannot evaluate key alluxio.worker.tieredstore.level0.watermark.low.ratio as double
    at alluxio.conf.InstancedConfiguration.getDouble(InstancedConfiguration.java:271)
    at alluxio.conf.ServerConfiguration.getDouble(ServerConfiguration.java:212)
    at alluxio.worker.block.SpaceReserver.updateStorageInfo(SpaceReserver.java:93)
...
```

```
2019-10-29 00:28:01,972 ERROR ProcessUtils - Uncaught exception while running Alluxio worker @172.31.20.213:29999, stopping it and exiting. Exception "java.lang.RuntimeException: Configuration cannot evaluate value 0.7-Dalluxio.master.metastore.dir=/metastore as double for key alluxio.worker.tieredstore.level0.watermark.low.ratio", Root Cause "null"
java.lang.RuntimeException: Configuration cannot evaluate value 0.7-Dalluxio.master.metastore.dir=/metastore as double for key alluxio.worker.tieredstore.level0.watermark.low.ratio
```

**To Reproduce**
Define a numerical property to be a string, in this case `alluxio.worker.tieredstore.level0.watermark.low.ratio`.

**Expected behavior**
Maybe remove the Root Cause when it is null? 

**Urgency**
Low.

**Additional context**

**Comment by jiacheliu3** [comment]
After the refactor on configuration and addition of type safety, this issue is no longer applicable
