### ISSUE TITLE
alluxio-2.1.0 (build from source) start job worker failed

### ISSUE THREAD

**Issue by pangzhenzhou** [Alluxio/alluxio#10421]
**Alluxio Version:**
alluxio-2.1.0

hadoop verison
Hadoop 2.7.3.2.6.4.0-91
Subversion git@github.com:hortonworks/hadoop.git -r a4b6e1c0e98b4488d38bcc0a241dcbe3538b1c4d
Compiled by jenkins on 2018-01-04T10:41Z
Compiled with protoc 2.5.0
From source with checksum 9c28f884302610b59b221c7fbaeac3e
This command was run using /usr/hdp/2.6.4.0-91/hadoop/hadoop-common-2.7.3.2.6.4.0-91.jar

**Describe the bug**

job worker start failed .
>>> BEGIN
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:380)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:344)
	at alluxio.worker.job.RetryHandlingJobMasterClient.registerWorker(RetryHandlingJobMasterClient.java:70)
	at alluxio.worker.JobWorkerIdRegistry.registerWorker(JobWorkerIdRegistry.java:50)
	at alluxio.worker.JobWorker.start(JobWorker.java:102)
	at alluxio.worker.AlluxioJobWorkerProcess.startWorkers(AlluxioJobWorkerProcess.java:252)
	at alluxio.worker.AlluxioJobWorkerProcess.start(AlluxioJobWorkerProcess.java:181)
	at alluxio.ProcessUtils.run(ProcessUtils.java:35)
	at alluxio.worker.AlluxioJobWorker.main(AlluxioJobWorker.java:79)
Caused by: alluxio.exception.ServiceNotFoundException: Service JOB_MASTER_WORKER_SERVICE is not found.
	... 10 more
Caused by: alluxio.exception.status.NotFoundException: Service JOB_MASTER_WORKER_SERVICE is not found.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:131)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:210)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:384)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:344)
	at alluxio.AbstractClient.getRemoteServiceVersion(AbstractClient.java:120)
	at alluxio.AbstractClient.checkVersion(AbstractClient.java:146)
	at alluxio.AbstractClient.connect(AbstractClient.java:232)
	... 9 more
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Service JOB_MASTER_WORKER_SERVICE is not found.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at alluxio.grpc.ServiceVersionClientServiceGrpc$ServiceVersionClientServiceBlockingStub.getServiceVersion(ServiceVersionClientServiceGrpc.java:172)
	at alluxio.AbstractClient$1.call(AbstractClient.java:122)
	at alluxio.AbstractClient$1.call(AbstractClient.java:120)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:382)
	... 13 more
2019-11-06 11:21:47,965 INFO  worker.AlluxioJobWorkerProcess (AlluxioJobWorkerProcess.java:stop) - Stopping RPC server on Alluxio job worker

**Comment by pangzhenzhou** [comment]
runTests  success

**Comment by ZacBlanco** [comment]
@pangzhenzhou there isn't enough information here to determine your issue.

- What command did you use to compile Alluxio?
- What java version are you using?
- What maven version are you using?

All the other information provided about your hadoop distribution seems irrelevant.
