### ISSUE TITLE
Dataproc initialization action create directory under user "kafka:google-sudoers"

### ISSUE THREAD

**Issue by roderickyao** [Alluxio/alluxio#10439]
Alluxio 2.1.0

Dataproc initialization actions create Alluxio directory /opt/alluxio using user name "kafka" and group "google-sudoers" by default. Users will have permission denied error when they run "alluxio format".
`og4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /opt/alluxio/logs/master_audit.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at alluxio.conf.InstancedConfiguration.<clinit>(InstancedConfiguration.java:44)
	at alluxio.cli.GetConf.main(GetConf.java:274)
`

**Comment by madanadit** [comment]
Hi @yhqs540 can you please post the `gcloud dataproc clusters create` command you used to launch the cluster?

**Comment by yhqs540** [comment]
gcloud dataproc clusters create roderickyao-alluxio --initialization-actions gs://alluxio-public/enterprise-dataproc/2.0.1-1.0/alluxio-dataproc.sh --single-node --master-boot-disk-size=50G --worker-boot-disk-size=50G --metadata alluxio_root_ufs_uri=gs://<bucket>/alluxio-test/,alluxio_site_properties="alluxio.master.mount.table.root.option.fs.gcs.accessKeyId=<KEY>;alluxio.master.mount.table.root.option.fs.gcs.secretAccessKey=<SECRET>",alluxio_license_base64=$(cat alluxio-enterprise-license.json | base64 |  tr -d "\n"),alluxio_download_path=gs://<bucket>/alluxio-enterprise-2.1.0-1.0.tar.gz
