### ISSUE TITLE
fuse在alpine下运行无法创建文件夹

### ISSUE THREAD

**Issue by we7team** [Alluxio/alluxio#10553]
**Alluxio Version:**
alluxio/alluxio-fuse:2.2.0-SNAPSHOT

**Describe the bug**
官方的fuse镜像太大了，想基于alpine做个小点的镜像，运行中发现创建文件夹报错

**错误日志：**
```
2019-12-03T16:03:54.912964624Z 2019-12-03 16:03:54,910 ERROR AlluxioFuseFileSystem - Failed to create directory /11
2019-12-03T16:03:54.91298944Z ExitCodeException exitCode=1: id: unknown user 0
2019-12-03T16:03:54.912993947Z 
2019-12-03T16:03:54.912997399Z 	at alluxio.util.ShellUtils$Command.run(ShellUtils.java:170)
2019-12-03T16:03:54.913001161Z 	at alluxio.util.ShellUtils$Command.access$200(ShellUtils.java:138)
2019-12-03T16:03:54.913004681Z 	at alluxio.util.ShellUtils.execCommand(ShellUtils.java:243)
2019-12-03T16:03:54.913008072Z 	at alluxio.fuse.AlluxioFuseUtils.getUserName(AlluxioFuseUtils.java:94)
2019-12-03T16:03:54.913011408Z 	at alluxio.fuse.AlluxioFuseFileSystem.mkdir(AlluxioFuseFileSystem.java:466)
2019-12-03T16:03:54.913014824Z 	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$1.invoke(Unknown Source)
```

**dockerfile：**
```
FROM alluxio/alluxio-fuse:2.2.0-SNAPSHOT AS alluxio-extractor
FROM adoptopenjdk/openjdk8:x86_64-alpine-jdk8u-nightly-slim
RUN set -ex \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
    && apk update \
    && apk upgrade \
    && apk add --no-cache shadow fuse-dev

# alluxio-fuse
ARG ALLUXIO_USERNAME=alluxio
ARG ALLUXIO_GROUP=alluxio
ARG ALLUXIO_UID=1000
ARG ALLUXIO_GID=1000

# if Alluxio user, group, gid, and uid aren't root|0
# then create the alluxio user and set file permissions accordingly
RUN if [ ${ALLUXIO_USERNAME} != "root" ] \
    && [ ${ALLUXIO_GROUP} != "root" ] \
    && [ ${ALLUXIO_UID} -ne 0 ] \
    && [ ${ALLUXIO_GID} -ne 0 ]; then \
      addgroup -g ${ALLUXIO_GID} ${ALLUXIO_GROUP} && \
      adduser --system -u ${ALLUXIO_UID} -g ${ALLUXIO_GID} ${ALLUXIO_USERNAME} && \
      usermod -a -G root ${ALLUXIO_USERNAME} && \
      mkdir -p /journal && \
      chown -R ${ALLUXIO_UID}:${ALLUXIO_GID} /journal && \
      chmod -R g=u /journal && \
      mkdir /alluxio-fuse && \
      chown -R ${ALLUXIO_UID}:${ALLUXIO_GID} /alluxio-fuse; \
    fi

COPY --from=alluxio-extractor /opt/alluxio/integration/fuse  /opt/alluxio/integration/fuse
COPY --from=alluxio-extractor /opt/alluxio/conf  /opt/alluxio/conf
COPY --from=alluxio-extractor /opt/alluxio/libexec /opt/alluxio/libexec
COPY --from=alluxio-extractor /entrypoint.sh /

RUN chown -R ${ALLUXIO_USERNAME}:${ALLUXIO_GROUP} /opt/ /entrypoint.sh

# end
RUN apk add --no-cache --update bash bash-doc bash-completion \
    && cd /bin && rm -f sh && ln -s /bin/bash sh \
    && rm -rf /var/cache/apk/* /tmp/*

USER ${ALLUXIO_UID}
ENTRYPOINT ["/entrypoint.sh"]
```

用户也没问题
![image](https://user-images.githubusercontent.com/4837122/70068137-665c8b80-162a-11ea-80fa-183ce08cf34d.png)

**Comment by jja725** [comment]
@ssz1997 is this till valid? otherwise please help me close this thanks

**Comment by ssz1997** [comment]
@we7team This is a permission issue of the alluxio fuse. I believe this has been fixed. Close this issue now but feel free to reopen if you still experience such error.
