### ISSUE TITLE
NPE in alluxio fuse log

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10592]
**Alluxio Version:**
What version of Alluxio are you using?
2.2.0

**Describe the bug**
Check the fuse log:

```
019-12-08 23:51:14,478 ERROR AlluxioFuseFileSystem - Failed to get info of /
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at alluxio.client.file.MetadataCache.getStatus(MetadataCache.java:56)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:323)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:313)
	at alluxio.fuse.AlluxioFuseFileSystem.getattr(AlluxioFuseFileSystem.java:374)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$1(AbstractFuseFS.java:95)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$0.invoke(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
	at alluxio.collections.ConcurrentHashSet.addIfAbsent(ConcurrentHashSet.java:72)
	at alluxio.client.file.MetadataCache.lambda$getStatus$0(MetadataCache.java:59)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 8 more
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by chcn** [comment]
@cheyang based on the stacktrace, it's not the latest master branch I think.

**Comment by ns1123** [comment]
@apc999 please link fix if this is addressed.

**Comment by cheyang** [comment]
I'm not able to reproduce it, so close it. Will reopen it if I can reproduce.
