### ISSUE TITLE
UnavailableException will test spark with alluxio

### ISSUE THREAD

**Issue by XiaochenCui** [Alluxio/alluxio#10683]
**Alluxio Version:**
2.1.1

**Describe the bug**
I have followed the docs https://docs.alluxio.io/os/user/stable/en/compute/Spark.html to run spark on alluxio, but when I run `double.saveAsTextFile("alluxio://localhost:19998/Output_HDFS")`
It failed with UnavailableException

**To Reproduce**
It can be reproduce in my company's cluster, I will be there if you need any extra information.

**Expected behavior**
Execution success

**Urgency**
We are going to build alluxio before the 2020 comes.

**Additional context**
Here is the all log:
```
scala> double.saveAsTextFile("alluxio://localhost:19998/Output_HDFS")
[Stage 0:>                                                          (0 + 2) / 2]19/12/30 17:00:25 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, cdh2, executor 1): alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMast
erClient @ localhost:19998 after 44 attempts
        at alluxio.AbstractClient.connect(AbstractClient.java:269)
        at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:613)
        at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:314)
        at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:415)
        at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:406)
        at alluxio.hadoop.HdfsFileInputStream.<init>(HdfsFileInputStream.java:60)
        at alluxio.hadoop.AbstractFileSystem.open(AbstractFileSystem.java:633)
        at alluxio.hadoop.FileSystem.open(FileSystem.java:41)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
        at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:109)
        at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
        at org.apache.spark.rdd.HadoopRDD$$anon$1.liftedTree1$1(HadoopRDD.scala:257)
        at org.apache.spark.rdd.HadoopRDD$$anon$1.<init>(HadoopRDD.scala:256)
        at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:214)
        at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:94)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
```
It's too long to attach

**Comment by ns1123** [comment]
@XiaochenCui this issue usually indicates some issue from the YARN side. Likely due to impersonation. Can you see if the Alluxio Master logs show any information about failed attempts to impersonate? If so, please attach those logs here. If you're running Spark on YARN with Alluxio, you should have this line (or something similar) in  your alluxio-site.properties.

alluxio.master.security.impersonation.yarn.users=*

For more detail on the format of the property, look at this link:
https://docs.alluxio.io/os/user/stable/en/operation/Security.html#client-side-hadoop-impersonation

**Comment by apc999** [comment]
also please double check if your master is running at address localhost:19998

**Comment by XiaochenCui** [comment]
> also please double check if your master is running at address localhost:19998

The master is sometimes not running on localhost

The master list is server1, server2, server3. so as the worker.
And the spark-shell in running on server1.
The leader is server2 when I do the experiments.

But what's the function of alluxio proxy? I have thought it to be like 'kubelet proxy' to proxy traffix so I can access leader thought the proxy endpoint `localhost:39999`, but it dose not works either.

Btw, the `alluxio.master.rpc.addresses` config is spark works bad.
I set it to `server1, server2, server3` and the current leader is server2.
It always throw errors shows that server1 and server3 refuse connnection, so does it has the ability to find the leader? It it has, how it works and how to config it?

Thanks

**Comment by XiaochenCui** [comment]
problem solved, it's caused by wrong config
