### ISSUE TITLE
Setting `alluxio.master.mount.table.root.ufs` to relative path will crash the master

### ISSUE THREAD

**Issue by ctest-team** [Alluxio/alluxio#10767]
**Alluxio Version:**
2.1.0

**Describe the bug**
The configuration parameter `alluxio.master.mount.table.root.ufs` allows an absolute path but refuses any relative path. Alluxio will fail to start the master with the message, `[ FAILED ] The master @ xxx is not serving requests.` if I set it to any relative path like `underFSStorage` 
I think the reason is that the following method always returns false for any relative path:
```
public static boolean isLocalFilesystem(String uri) {
 return uri.startsWith(AlluxioURI.SEPARATOR)
     || uri.startsWith("file://")
     || AlluxioURI.hasWindowsDrive(uri, false);
}
```

**To Reproduce**
1. Specify the `alluxio.master.mount.table.root.ufs` value in `conf/alluxio-site.properties` as following:
```
alluxio.master.mount.table.root.ufs=underFSStorage
```
2. Run `./bin/alluxio format`
3. Run `./bin/alluxio-start.sh local SudoMount`
4. alluxio reports `[ FAILED ] The master @ xxx is not serving requests.`

**Expected behavior**
Alluxio should start successfully and use ./underFSStorage as the directory for underfs.

**Urgency**
Medium.

**Additional context**
The log message from master
```
2020-01-20 12:35:41,828 WARN  ExtensionFactoryRegistry - No factory implementation supports the path underFSStorage
2020-01-20 12:35:41,876 ERROR AlluxioMaster - Fatal error: Failed to create master process
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start masters
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:129)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.<init>(FaultTolerantAlluxioMasterProcess.java:58)
	at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:401)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Failed to start masters
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:57)
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:127)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No Under File System Factory found for: underFSStorage
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:529)
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:55)
	... 4 more
Caused by: java.lang.IllegalArgumentException: No Under File System Factory found for: underFSStorage
	at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:95)
	at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:128)
	at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:164)
	at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:60)
	at alluxio.master.file.DefaultFileSystemMaster.getRootMountInfo(DefaultFileSystemMaster.java:457)
	at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:415)
	at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:396)
	at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:51)
	at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:28)
	at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**How to solve**
Maybe we can append relative path to the working directory to make it an absolute path.

**Comment by ns1123** [comment]
@ctest-team is your request to assume that an unspecified scheme can be assumed to be the local file system? It's not entirely clear that this is a correct or safe assumption.

Additionally, is the idea that the path would be relative to the alluxio installation directory or is the intention that it would it be relative to where the ./bin/alluxio-start.sh  command was issued? Both of these scenarios seem ambiguous and it would make more sense to just have an absolute path with scheme to avoid confusion. I do think we can do a better job with the error message.

**Comment by marshtompsxd** [comment]
@ns1123 I agree that the relative path seems to be ambiguous here. Only allowing absolute path can avoid confusion. 
And it is great to have a better error message! Users can easily get confused when they saw the error message like `java.lang.IllegalArgumentException: No Under File System Factory found for: underFSStorage` after setting a relative path. It would be much better if we could directly tell the users that only an absolute path is allowed here in the error message.

**Comment by ctest-team** [comment]
@ns1123 I agree that the relative path seems to be ambiguous here. Only allowing absolute path can avoid confusion.
And it is great to have a better error message! Users can easily get confused when they saw the error message like `java.lang.IllegalArgumentException: No Under File System Factory found for: underFSStorage` after setting a relative path. It would be much better if we could directly tell the users that only an absolute path is allowed here in the error message.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
