### ISSUE TITLE
NPE on authentication failure

### ISSUE THREAD

**Issue by bf8086** [Alluxio/alluxio#10824]
**Alluxio Version:**
2.1.2
**Describe the bug**
NPE on authentication failure:

```
java.lang.NullPointerException
        at alluxio.security.authentication.SaslStreamServerDriver.onNext(SaslStreamServerDriver.java:119)
        at alluxio.security.authentication.SaslStreamServerDriver.onNext(SaslStreamServerDriver.java:32)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:686)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1355)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
```
**To Reproduce**
Get an exception thrown at `mAuthenticationServer.createSaslHandler(saslMessage.getAuthenticationScheme());`

**Expected behavior**

**Urgency**
Medium due to bad error message

**Additional context**

**Comment by ggezer** [comment]
This is fixed by https://github.com/Alluxio/alluxio/pull/10783
