### ISSUE TITLE
Failed to read the file in alluxio fuse when enable kernel_cache

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10840]
**Alluxio Version:**
2.1.1

**Describe the bug**

Use alluxio-fuse to read file failed when using `kernel_cache`, but it can work with `direct_io`.

**To Reproduce**

1.  disable direct_io in the source code, and here is branch I used: https://github.com/cheyang/alluxio/commits/branch-2.1-use-pagecache-0204

2. start alluxio-master, worker and fuse, and the fuse option is : --fuse-opts=kernel_cache

```
# Prepare the network
docker network create alluxio_network

mkdir Tools/alluxio-fs
cd Tools/alluxio-fs
mkdir ufs
mkdir shm
mkdir fuse
cd ufs
wget http://kubeflow-hk.oss-cn-hongkong.aliyuncs.com/validation-00127-of-00128

# Launch the Alluxio master
docker run -d  --rm \
    -u=0 \
    -p 19999:19999 \
    -p 19998:19998 \
    --net=alluxio_network \
    --name=alluxio-master \
    --hostname=alluxio-master \
    -e ALLUXIO_JAVA_OPTS="-Dalluxio.master.hostname=alluxio-master -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage" \
    -v /Users/cheyang.cy/Tools/alluxio-fs/ufs:/opt/alluxio/underFSStorage \
    registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.1.1-SNAPSHOT-5bd5d3c master

# Launch the Alluxio worker
docker run -d --rm \
    -p 29999:29999 \
    -p 30000:30000 \
    -p 8000:8000 \
    -u=0 \
    --net=alluxio_network \
    --name=alluxio-worker \
    --hostname=alluxio-worker \
    --ipc=shareable \
    --shm-size=1G \
    -v /Users/cheyang.cy/Tools/alluxio-fs/ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS="-Dalluxio.worker.memory.size=1G  -Dalluxio.master.hostname=alluxio-master  -Dalluxio.worker.hostname=alluxio-worker" \
    registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.1.1-SNAPSHOT-5bd5d3c worker

docker run -d --rm \
    --net=container:alluxio-worker \
    --ipc=container:alluxio-worker \
    -u=0 \
    --mount type=bind,source=/Users/cheyang.cy/Tools/alluxio-fs/fuse,target=/alluxio-fuse \
    --name=alluxio-fuse \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    -v /Users/cheyang.cy/Tools/alluxio-fs/ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS="-Dalluxio.worker.memory.size=1G  -Dalluxio.master.hostname=alluxio-master -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.metadata.cache.max.size=1000000 -Dalluxio.user.direct.memory.io.enabled=true -Dalluxio.fuse.debug.enabled=true  -Dalluxio.fuse.cached.paths.max=1000000 -Dalluxio.user.hostname=alluxio-worker -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000" \
    registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio-fuse:2.1.1-SNAPSHOT-5bd5d3c fuse --fuse-opts=kernel_cache
```

3.Access the alluxio-fuse container, and cat the file

```
docker exec -it alluxio-fuse bash
time cat /alluxio-fuse/validation-00127-of-00128 > /dev/null
cat: /alluxio-fuse/validation-00127-of-00128: Bad message
```

4. From the alluxio-fuse logs, I can see the following errors;

```
2020-02-04 12:25:24,912 INFO  DynamicResourcePool - Resource alluxio.client.file.RetryHandlingFileSystemMasterClient@2cec7270 is garbage collected.
2020-02-04 12:25:42,495 ERROR AlluxioFuseFileSystem - Failed to read file /validation-00127-of-00128
alluxio.exception.status.DeadlineExceededException: Timeout waiting for response after 30000ms. (Zero Copy GrpcDataReader)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:158)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receiveDataMessage(GrpcDataMessageBlockingStream.java:84)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.waitForComplete(GrpcDataMessageBlockingStream.java:115)
	at alluxio.client.block.stream.GrpcDataReader.close(GrpcDataReader.java:171)
	at alluxio.client.block.stream.BlockInStream.closeDataReader(BlockInStream.java:388)
	at alluxio.client.block.stream.BlockInStream.seek(BlockInStream.java:327)
	at alluxio.client.file.FileInStream.seek(FileInStream.java:306)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:583)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
   unique: 92, error: -5 (Input/output error), outsize: 16
   unique: 90, error: -5 (Input/output error), outsize: 16
2020-02-04 12:25:42,526 ERROR AlluxioFuseFileSystem - Failed to read file /validation-00127-of-00128
alluxio.exception.status.DeadlineExceededException: Timeout waiting for response after 30000ms. (Zero Copy GrpcDataReader)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:158)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receiveDataMessage(GrpcDataMessageBlockingStream.java:84)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.waitForComplete(GrpcDataMessageBlockingStream.java:115)
	at alluxio.client.block.stream.GrpcDataReader.close(GrpcDataReader.java:171)
	at alluxio.client.block.stream.BlockInStream.closeDataReader(BlockInStream.java:388)
	at alluxio.client.block.stream.BlockInStream.seek(BlockInStream.java:327)
	at alluxio.client.file.FileInStream.seek(FileInStream.java:306)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:583)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
unique: 96, opcode: READ (15), nodeid: 2, insize: 80, pid: 269

```

But the network looks good

```
docker exec -it alluxio-fuse bash
root@alluxio-worker:/libfuse# telnet alluxio-worker 29999
Trying 172.19.0.3...
Connected to alluxio-worker.
Escape character is '^]'.
```

And the following is master, worker and fuse log:

[alluxio-fuse.log](https://github.com/Alluxio/alluxio/files/4153398/alluxio-fuse.log)
[alluxio-master.log](https://github.com/Alluxio/alluxio/files/4153399/alluxio-master.log)
[alluxio-worker.log](https://github.com/Alluxio/alluxio/files/4153400/alluxio-worker.log)

5. Remove the alluxio-fuse, and create a new one with direct_io

```
docker rm -f alluxio-fuse
alluxio-fuse

docker run -d --rm \
    --net=container:alluxio-worker \
    --ipc=container:alluxio-worker \
    -u=0 \
    --mount type=bind,source=/Users/cheyang.cy/Tools/alluxio-fs/fuse,target=/alluxio-fuse \
    --name=alluxio-fuse \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    -v /Users/cheyang.cy/Tools/alluxio-fs/ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS="-Dalluxio.worker.memory.size=1G  -Dalluxio.master.hostname=alluxio-master -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.metadata.cache.max.size=1000000 -Dalluxio.user.direct.memory.io.enabled=true -Dalluxio.fuse.debug.enabled=true  -Dalluxio.fuse.cached.paths.max=1000000 -Dalluxio.user.hostname=alluxio-worker -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000" \
    registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio-fuse:2.1.1-SNAPSHOT-5bd5d3c fuse --fuse-opts=direct_io
```

6. Repeat the step 3, this can work.

```
time cat /alluxio-fuse/validation-00127-of-00128 > /dev/null

real	0m2.330s
user	0m0.003s
sys	0m0.021s
echo $?
0
```

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
After I loaded the file into alluxio system, the error shown is 

```
2020-02-04 15:41:10,325 ERROR AlluxioFuseFileSystem - Failed to read file /validation-00127-of-00128
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at alluxio.client.block.stream.LocalFileDataReader$Factory.create(LocalFileDataReader.java:162)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:367)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:253)
	at alluxio.client.file.FileInStream.read(FileInStream.java:186)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
2020-02-04 15:41:10,329 ERROR AlluxioFuseFileSystem - Failed to read file /validation-00127-of-00128
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at alluxio.client.block.stream.LocalFileDataReader$Factory.create(LocalFileDataReader.java:162)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:367)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:253)
	at alluxio.client.file.FileInStream.read(FileInStream.java:186)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
2020-02-04 15:41:10,326 ERROR AlluxioFuseFileSystem - Failed to read file /validation-00127-of-00128
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at alluxio.client.block.stream.LocalFileDataReader$Factory.create(LocalFileDataReader.java:162)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:367)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:253)
	at alluxio.client.file.FileInStream.read(FileInStream.java:186)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
2020-02-04 15:41:10,325 ERROR AlluxioFuseFileSystem - Failed to read file /validation-00127-of-00128
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at alluxio.client.block.stream.LocalFileDataReader$Factory.create(LocalFileDataReader.java:162)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:367)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:253)
	at alluxio.client.file.FileInStream.read(FileInStream.java:186)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
   unique: 16, error: -74 (Bad message), outsize: 16
   unique: 20, error: -74 (Bad message), outsize: 16
   unique: 18, error: -74 (Bad message), outsize: 16
unique: 24, opcode: READ (15), nodeid: 2, insize: 80, pid: 257
read[0] 4096 bytes from 524288 flags: 0x8000
   unique: 22, error: -74 (Bad message), outsize: 16
2020-02-04 15:41:10,344 ERROR AlluxioFuseFileSystem - Failed to read file /validation-00127-of-00128
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at alluxio.client.block.stream.LocalFileDataReader$Factory.create(LocalFileDataReader.java:162)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:367)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:253)
	at alluxio.client.file.FileInStream.read(FileInStream.java:186)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
   unique: 24, error: -74 (Bad message), outsize: 16
unique: 26, opcode: FLUSH (25), nodeid: 2, insize: 64, pid: 257
flush[0]
   unique: 26, success, outsize: 16
unique: 28, opcode: RELEASE (18), nodeid: 2, insize: 64, pid: 0
release[0] flags: 0x8000
   unique: 28, success, outsize: 16
```

**Comment by cheyang** [comment]
@LuQQiu , here are the logs with your change on logging, please take a look.

```
ead[0] 131072 bytes from 1572864 flags: 0x8000
2020-02-10 15:14:44,095 INFO  AlluxioFuseFileSystem - read(/validation-00127-of-00128, 131072, 1572864)
2020-02-10 15:14:44,096 INFO  LocalFileDataReader$Factory - Creating LocalFileDataReader with offset 917504 len 50136480
unique: 162, opcode: READ (15), nodeid: 2, insize: 80, pid: 259
read[0] 131072 bytes from 1703936 flags: 0x8000
unique: 164, opcode: READ (15), nodeid: 2, insize: 80, pid: 259
read[0] 4096 bytes from 1310720 flags: 0x8000
2020-02-10 15:14:44,097 INFO  AlluxioFuseFileSystem - read(/validation-00127-of-00128, 131072, 1703936)
2020-02-10 15:14:44,098 INFO  LocalFileDataReader$Factory - Creating LocalFileDataReader with offset 1048576 len 50005408
2020-02-10 15:14:44,098 INFO  LocalFileBlockReader - increase usage count for block reader of path /dev/shm/alluxioworker/16777216
2020-02-10 15:14:44,097 INFO  LocalFileBlockReader - increase usage count for block reader of path /dev/shm/alluxioworker/16777216
```

[alluxio-fuse.log](https://github.com/Alluxio/alluxio/files/4181567/alluxio-fuse.log)
[alluxio-master.log](https://github.com/Alluxio/alluxio/files/4181570/alluxio-master.log)
[alluxio-worker.log](https://github.com/Alluxio/alluxio/files/4181571/alluxio-worker.log)

**Comment by LuQQiu** [comment]
When using direct_io or no fuse mount options, reads are sequential which means that one read will wait for another read to finish before it starts. For example, read(size=131072, offset=131072) will be issued after read(size=131072, offset=0) finished.

However, with kernel_cache, libfuse issues read() concurrently. read(size=131072, offset=0) and read(size=131072, offset=131072) can be issued together.

However, AlluxioFuseFileSystem.read() does not take concurrency into account. Reading the same file with different offset at the same time will have issues because multi-threads are sharing the same FileInStream. LocalFileBlockReader does not support concurrency so far, it expects one thread using it at a time.

**Comment by LuQQiu** [comment]
To fix the issue, we need to support concurrency in AlluxioFuseFileSystem.read()

**Comment by apc999** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/12606 with JNI Fuse
