### ISSUE TITLE
Python Alluxio package does not support Python3

### ISSUE THREAD

**Issue by realknorke** [Alluxio/alluxio#10855]
**Alluxio Version:**
n/a
alluxio pip package is only available in 0.1.1
Python v3.7

**Describe the bug**
It is not possible to install the 'alluxio' Python package using pip because of broken/missing dependencies. Installing the 'alluxio' Python package for Python2 works. However, Python2 is end of lifetime and marked deprecated since 2020-01-01.

**To Reproduce**
`pip install alluxio`

**Expected behavior**
Pip installs all dependencies and then Alluxio support for Python.

**Urgency**
Medium, because **installing Alluxio's Python packages from git works**

**Additional context**
Lets setup the clean Python environment first…
```
[/ram] -> find
.
[knorke@eddie] 2020-02-06 14:26:01
[/ram] -> python3.7 -mvenv venv
python3.7 -mvenv venv  1,54s user 0,13s system 99% cpu 1,689 total
[knorke@eddie] 2020-02-06 14:26:11
[/ram] -> source venv/bin/activate
(venv) [knorke@eddie] 2020-02-06 14:26:46
[/ram] -> pip install -U pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.0.2
pip install -U pip  1,09s user 0,10s system 89% cpu 1,334 total
(venv) [knorke@eddie] 2020-02-06 14:26:52
```
here we go
```
[/ram] -> pip install alluxio
Collecting alluxio
  Using cached alluxio-0.1.1.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /dev/shm/venv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pfqkadp5/alluxio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pfqkadp5/alluxio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-pfqkadp5/alluxio/pip-egg-info
         cwd: /tmp/pip-install-pfqkadp5/alluxio/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pfqkadp5/alluxio/setup.py", line 6, in <module>
        import alluxio
      File "/tmp/pip-install-pfqkadp5/alluxio/alluxio/__init__.py", line 3, in <module>
        from .client import Client
      File "/tmp/pip-install-pfqkadp5/alluxio/alluxio/client.py", line 19, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv) [knorke@eddie] {1} 2020-02-06 14:27:12

[/ram] -> pip install requests
Collecting requests
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting chardet<3.1.0,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<2.9,>=2.5
  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
Installing collected packages: chardet, idna, certifi, urllib3, requests
Successfully installed certifi-2019.11.28 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.8
(venv) [knorke@eddie] 2020-02-06 14:27:27

[/ram] -> pip install alluxio
Collecting alluxio
  Using cached alluxio-0.1.1.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /dev/shm/venv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e1sm84c3/alluxio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e1sm84c3/alluxio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-e1sm84c3/alluxio/pip-egg-info
         cwd: /tmp/pip-install-e1sm84c3/alluxio/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e1sm84c3/alluxio/setup.py", line 6, in <module>
        import alluxio
      File "/tmp/pip-install-e1sm84c3/alluxio/alluxio/__init__.py", line 3, in <module>
        from .client import Client
      File "/tmp/pip-install-e1sm84c3/alluxio/alluxio/client.py", line 22, in <module>
        from . import wire
      File "/tmp/pip-install-e1sm84c3/alluxio/alluxio/wire.py", line 10, in <module>
        from .common import _JsonEncodable, _JsonDecodable, String
      File "/tmp/pip-install-e1sm84c3/alluxio/alluxio/common.py", line 5, in <module>
        from six import reraise
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv) [knorke@eddie] {1} 2020-02-06 14:27:38


[/ram] -> pip install six
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six
Successfully installed six-1.14.0
(venv) [knorke@eddie] 2020-02-06 14:27:51

[/ram] -> pip install alluxio
Collecting alluxio
  Using cached alluxio-0.1.1.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /dev/shm/venv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3x0pdyfe/alluxio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3x0pdyfe/alluxio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3x0pdyfe/alluxio/pip-egg-info
         cwd: /tmp/pip-install-3x0pdyfe/alluxio/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3x0pdyfe/alluxio/setup.py", line 6, in <module>
        import alluxio
      File "/tmp/pip-install-3x0pdyfe/alluxio/alluxio/__init__.py", line 4, in <module>
        import option
    ModuleNotFoundError: No module named 'option'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv) [knorke@eddie] {1} 2020-02-06 14:28:02

[/ram] -> pip install option
Collecting option
  Using cached option-1.0.1-py3-none-any.whl (11 kB)
Installing collected packages: option
Successfully installed option-1.0.1
(venv) [knorke@eddie] 2020-02-06 14:28:15

[/ram] -> pip install alluxio
Collecting alluxio
  Using cached alluxio-0.1.1.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /dev/shm/venv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s4g03c4i/alluxio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s4g03c4i/alluxio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-s4g03c4i/alluxio/pip-egg-info
         cwd: /tmp/pip-install-s4g03c4i/alluxio/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s4g03c4i/alluxio/setup.py", line 6, in <module>
        import alluxio
      File "/tmp/pip-install-s4g03c4i/alluxio/alluxio/__init__.py", line 5, in <module>
        import wire
    ModuleNotFoundError: No module named 'wire'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv) [knorke@eddie] {1} 2020-02-06 14:28:18


[/ram] -> pip install wire   
ERROR: Could not find a version that satisfies the requirement wire (from versions: none)
ERROR: No matching distribution found for wire
(venv) [knorke@eddie] {1} 2020-02-06 14:28:34
```

**Comment by fcncassandra** [comment]
Maybe you can try a local installation, cause there is one line code makes mistake in the  file '__init__' when you setup.
![image](https://user-images.githubusercontent.com/35741990/81038872-0a987600-8eda-11ea-952f-98286ba896bb.png)
![image](https://user-images.githubusercontent.com/35741990/81038891-184dfb80-8eda-11ea-992b-91189ba89e19.png)
You should download the package, and fix the line,  then you need to compress them in a tar.
![image](https://user-images.githubusercontent.com/35741990/81038978-521f0200-8eda-11ea-806c-f9e1ad429bd3.png)
Then you can make it right.
![image](https://user-images.githubusercontent.com/35741990/81039004-6105b480-8eda-11ea-8317-f7198ad44f15.png)

**Comment by apc999** [comment]
fixed by https://github.com/Alluxio/alluxio-py/pull/3
