### ISSUE TITLE
Possible NPE in DefaultMetaMaster

### ISSUE THREAD

**Issue by ZacBlanco** [Alluxio/alluxio#10872]
**Alluxio Version:**
2.2.0-SNAPSHOT

**Describe the bug**

There is a possible NPE that can be triggered in DefaultMetaMaster.java. I've seen it in one of the integration tests. I haven't figured out exactly what triggers it, but here is the stacktrace:

```
java.lang.NullPointerException
	at alluxio.master.meta.DefaultMetaMaster.getServices(DefaultMetaMaster.java:267)
	at alluxio.master.AlluxioMasterProcess.startServingRPCServer(AlluxioMasterProcess.java:324)
	at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:294)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.lambda$gainPrimacy$1(FaultTolerantAlluxioMasterProcess.java:130)
	at java.lang.Thread.run(Thread.java:748)

	at alluxio.ProcessUtils.fatalError(ProcessUtils.java:78)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.lambda$gainPrimacy$1(FaultTolerantAlluxioMasterProcess.java:136)
	at java.lang.Thread.run(Thread.java:748)
```

Offending LoC: https://github.com/Alluxio/alluxio/blob/master/core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java#L266-L267

This was thrown while running the CopyToLocalCommandIntegrationTest

Maven log output:

```
Tests run: 13, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 161.628 sec <<< FAILURE! - in alluxio.client.cli.fs.command.CopyToLocalCommandIntegrationTest
copyToLocalRelativePath(alluxio.client.cli.fs.command.CopyToLocalCommandIntegrationTest)  Time elapsed: 64.798 sec  <<< ERROR!
java.lang.RuntimeException: Timed out waiting for process Alluxio job master @ 44fdfda55b3e:40455 to start

copyToLocalRelativePath(alluxio.client.cli.fs.command.CopyToLocalCommandIntegrationTest)  Time elapsed: 64.799 sec  <<< ERROR!
java.lang.NullPointerException
```

Sample build: https://amplab.cs.berkeley.edu/jenkins/view/Alluxio/job/Alluxio-Pull-Request-Builder/8052

**To Reproduce**
Run the integration tests.

**Expected behavior**
No NPE should be thrown and the test should pass.

**Urgency**
Doesn't seem to affect most normal operations. Could be due to failures or exceptions thrown during a test which triggers the code path that `DefaultMetaMaster#getServices()` is called while it is stopped.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
