### ISSUE TITLE
Alluxio Fuse leads high CPU useage

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#10880]
**Alluxio Version:**
2.1.1

**Describe the bug**
I'm running AI workload on Alluxio, and notice it uses very high cpu. It's about 2000% CPU usage.

![image](https://user-images.githubusercontent.com/3724388/74202968-ffea8e00-4ca8-11ea-8837-297c7110ca3d.png)

And the following is the thread dump raw file:
[77737.log](https://github.com/Alluxio/alluxio/files/4183690/77737.log)

And here is the complete analysis : https://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMjAvMDIvMTEvLS03NzczNy5sb2ctLTAtMzgtMzk=&

![image](https://user-images.githubusercontent.com/3724388/74203565-10036d00-4cab-11ea-87ff-ecc071da9c6c.png)

[ft-report-77737.pdf](https://github.com/Alluxio/alluxio/files/4183721/ft-report-77737.pdf)

Looks like the DirectMemoryIO uses the most CPU. Any suggestions on it?

```
at com.kenai.jffi.Foreign.putByteArray(Native Method)
at com.kenai.jffi.MemoryIO$UnsafeImpl.putByteArray(MemoryIO.java:911)
at jnr.ffi.provider.jffi.DirectMemoryIO.put(DirectMemoryIO.java:127)
at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:595)
at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
at ru.serce.jnrfuse.AbstractFuseFS$$Lambda$56/187472540.read(Unknown Source)
at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by yuzhu** [comment]
addressed through jni-fuse
