### ISSUE TITLE
ttl checker exception

### ISSUE THREAD

**Issue by zx-hub** [Alluxio/alluxio#10903]
**Alluxio Version:**
2.1.0

**Describe the bug**
An alluxio service exception was found, and a large number of InodeTtlChecker Error was found in the log
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
Take one for example
```
2020-02-13 00:01:00,429 INFO  InodeTtlChecker - Path /data/dispatcher/cache/5ffcd7115409400e1c205f1858f2d455 TTL has expired, performing action FREE
2020-02-13 00:01:00,434 ERROR InodeTtlChecker - Exception trying to clean up alluxio.master.file.meta.InodeDirectory@f1 for ttl check
alluxio.exception.UnexpectedAlluxioException: Cannot free file /data/dispatcher/cache/5ffcd7115409400e1c205f1858f2d455/35c0e932-0633-4b1f-abd4-83986b073ea8/0_38 which is not persisted
        at alluxio.master.file.DefaultFileSystemMaster.freeInternal(DefaultFileSystemMaster.java:2280)
        at alluxio.master.file.DefaultFileSystemMaster.free(DefaultFileSystemMaster.java:2247)
        at alluxio.master.file.InodeTtlChecker.heartbeat(InodeTtlChecker.java:89)
        at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```
but in alluxio ui,I found this file is persisted
![image](https://user-images.githubusercontent.com/12888103/74401578-aa56e280-4e5c-11ea-8ba9-3c456d2daba0.png)

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by ZacBlanco** [comment]
hi @zx-hub ,

Is this scenario easily reproducible? Can you please include a set of steps that cause this issue? If it's not reproducible then we'll have a hard time fixing it.

Otherwise, can you run `alluxio fs stat <path>` on the command line for that file? Can you paste the output of that here as well?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
