### ISSUE TITLE
UfsJournal crash with local UFS

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#10915]
**Alluxio Version:**
master

**Describe the bug**
Advancing to a next journal files requires listing files in journal directory. Current `LocalUnderFileSystem.listStatus()` implementation can throw `NoSuchFileException` if journal directory is concurrently being changed. (This change is natural as part of completing a current journal file.) This will cause journal reader to crash.

**To Reproduce**
Run `MultiMasterJournalTest-testCheckpointReplay` test multiple times.

**Expected behavior**
Alluxio should be able to handle this concurrent modification case.

**Additional context**

tests/MultiMasterJournalTest-testCheckpointReplay-65ce1226-8d38-44f5-8e0e-a04b2c545dcf/journal/FileSystemMaster/v1/logs/0x22-0x7fffffffffffffff, start=34, end=9223372036854775807, isCheckpoint=false}
2020-01-31 19:36:22,957 [AsyncJournalWriterThread] INFO  ufs.UfsJournalLogWriter (UfsJournalLogWriter.java:flush) - Rotating log file. size: 198 maxSize: 100
2020-01-31 19:36:22,956 [Thread-129] ERROR ufs.UfsJournalCheckpointThread (UfsJournalCheckpointThread.java:runInternal) - FileSystemMaster: Failed to read or process a journal entry.
java.nio.file.NoSuchFileException: /tmp/alluxio-tests/MultiMasterJournalTest-testCheckpointReplay-65ce1226-8d38-44f5-8e0e-a04b2c545dcf/journal/FileSystemMaster/v1/logs/0x1e-0x7fffffffffffffff
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:218)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:131)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at alluxio.underfs.local.LocalUnderFileSystem.listStatus(LocalUnderFileSystem.java:293)
	at alluxio.underfs.UnderFileSystemWithLogging$31.call(UnderFileSystemWithLogging.java:567)
	at alluxio.underfs.UnderFileSystemWithLogging$31.call(UnderFileSystemWithLogging.java:564)
	at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:948)
	at alluxio.underfs.UnderFileSystemWithLogging.listStatus(UnderFileSystemWithLogging.java:564)
	at alluxio.master.journal.ufs.UfsJournalSnapshot.getSnapshot(UfsJournalSnapshot.java:104)
	at alluxio.master.journal.ufs.UfsJournalReader.updateInputStream(UfsJournalReader.java:221)
	at alluxio.master.journal.ufs.UfsJournalReader.advance(UfsJournalReader.java:263)
	at alluxio.master.journal.ufs.UfsJournalCheckpointThread.runInternal(UfsJournalCheckpointThread.java:182)
	at alluxio.master.journal.ufs.UfsJournalCheckpointThread.run(UfsJournalCheckpointThread.java:163)
2020-01-31 19:36:22,964 [Thread-129] INFO  ufs.UfsJournalReader (UfsJournalReader.java:<init>) - Reading journal file /tmp/alluxio-tests/MultiMasterJournalTest-testCheckpointReplay-65ce1226-8d38-44f5-8e0e-a04b2c545dcf/journal/FileSystemMaster/v1/logs/0x19-0x1e.

**Comment by ZacBlanco** [comment]
I don't know if we can 100% fix this operation. However here are some of my thoughts,

Instead of doing a list - and then iterating over the list to read attributes, we can make use of the `java.nio.Files` API: https://docs.oracle.com/javase/8/docs/api/?java/io/Files.html 

Specifically the `walk(Path start, FileVisitOption... options)` API.

The stream is lazily populated, so we can have minimal time between listing and operating on the file attributes. I think it can reduce the chance of getting a stale listing.

My other thought, is that we could also filter out incomplete journal files on the caller-side - but I'm not sure what other implications that would have. I'm not too familiar with how the UfsJournal operates.

**Comment by yuzhu** [comment]
@ggezer has this been fixed?

**Comment by apc999** [comment]
@ggezer has this been fixed?

**Comment by jja725** [comment]
@jenoudet is this still valid? Think we could close this since this is not our main use case

**Comment by jenoudet** [comment]
I don't think this is relevant anymore.

**Comment by jenoudet** [comment]
I don't think this is relevant anymore.
