### ISSUE TITLE
Embedded  journal node crash

### ISSUE THREAD

**Issue by iAlaska** [Alluxio/alluxio#10925]
**Alluxio Version:**
2.1.1

**Describe the bug**
after load some data into alluxio cluster, and execute a `du -s -h` command. one of  the master node crashed and can't restart normally.
blow is the error log of the crashed master node.
```
2020-02-13 16:47:33,255 ERROR JournalStateMachine - Journal replay error: Failed to apply journal entry to master FileSystemMaster. Entry: sequence_number: 4558132
update_inode {
  id: 18988251742207
  last_modification_time_ms: 1581528044771
  overwrite_modification_time: true
  ufs_fingerprint: "TYPE|FILE UFS|hdfs OWNER|mqq GROUP|hive MODE|420 CONTENT_HASH|(len:5717937,_modtime:1581528044771) "
  last_access_time_ms: 1581528044771
}
java.lang.IllegalStateException: Inode 18988251742207 not found
        at alluxio.master.file.meta.InodeTreePersistentState.applyUpdateInode(InodeTreePersistentState.java:395)
        at alluxio.master.file.meta.InodeTreePersistentState.processJournalEntry(InodeTreePersistentState.java:679)
        at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:31)
        at alluxio.master.journal.JournaledGroup.processJournalEntry(JournaledGroup.java:56)
        at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:31)
        at alluxio.master.journal.raft.JournalStateMachine.applyToMaster(JournalStateMachine.java:184)
        at alluxio.master.journal.raft.JournalStateMachine.applySingleEntry(JournalStateMachine.java:169)
        at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:141)
        at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:131)
        at alluxio.master.journal.raft.JournalStateMachine.applyJournalEntryCommand(JournalStateMachine.java:108)
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.atomix.copycat.server.StateMachine.lambda$wrapVoidMethod$0(StateMachine.java:353)
        at io.atomix.copycat.server.state.ServerStateMachineExecutor.lambda$register$1(ServerStateMachineExecutor.java:244)
        at io.atomix.copycat.server.state.ServerStateMachineExecutor.executeOperation(ServerStateMachineExecutor.java:149)
        at io.atomix.copycat.server.state.ServerStateMachine.executeCommand(ServerStateMachine.java:909)
        at io.atomix.copycat.server.state.ServerStateMachine.lambda$apply$19(ServerStateMachine.java:847)
        at io.atomix.catalyst.concurrent.Runnables.lambda$logFailure$0(Runnables.java:20)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Urgency**
because i only has 3 master node, when this node crashed, my whole cluster is down. the only resolution is reformat masters and restart ?

**Additional context**
this is the dump journal log with readJournal comman.
[edits.txt](https://github.com/Alluxio/alluxio/files/4207709/edits.txt)

**Comment by ZacBlanco** [comment]
Thanks for reporting your issue @iAlaska. While the stacktrace and edit log above are useful it isn't enough to fully identify the issue.

Can you please provide the full log from all of your masters, and your `alluxio-site.properties` with any sensitive information omitted. We will need all of this to fully investigate the cause and subsequent failure

**Comment by iAlaska** [comment]
i am sorry, the log of all masters is cleared now. but the `alluxio-site.properties` is here. hope it will help.

```
# Common properties
alluxio.master.hostname=${hostname}
alluxio.master.rpc.port=19998
alluxio.master.web.port=8080
alluxio.worker.web.port=8080
alluxio.master.mount.table.root.ufs=hdfs://nameservice1/user/hive/warehouse/alluxio/root
alluxio.underfs.hdfs.configuration=/etc/hadoop/conf/core-site.xml:/etc/hadoop/conf/hdfs-site.xml
alluxio.integration.master.resource.cpu=20
alluxio.integration.master.resource.mem=20GB

# HA raft
alluxio.master.embedded.journal.addresses=master1:19200,master2:19200,master3:19200
# Worker properties
alluxio.worker.memory.size=10GB
alluxio.worker.tieredstore.levels=1
alluxio.worker.tieredstore.level0.alias=SSD
alluxio.worker.tieredstore.level0.dirs.path=/data1/alluxio/nvm,/data2/alluxio/nvm,/data3/alluxio/nvm,/data4/alluxio/nvm
alluxio.worker.tieredstore.level0.dirs.quota=3.2TB,3.2TB,3.2TB
alluxio.worker.tieredstore.level0.watermark.high.ratio=0.9
alluxio.worker.tieredstore.level0.watermark.low.ratio=0.7
alluxio.integration.worker.resource.cpu=40
alluxio.integration.worker.resource.mem=50GB
# User properties
# alluxio.user.file.readtype.default=CACHE_PROMOTE
alluxio.user.file.writetype.default=CACHE_THROUGH

# Security
alluxio.master.security.impersonation.yarn.users=*
alluxio.master.security.impersonation.hive.users=*
alluxio.master.security.impersonation.impala.users=*
alluxio.master.security.impersonation.cydw.users=*
```

**Comment by jinhang** [comment]
m

**Comment by shenghui361** [comment]
the same problem:
alluixo 2.4.1

`2021-05-13 19:53:00,316 INFO  UfsJournalReader - Reading journal file hdfs://sfbd-dr/alluxio/journal/FileSystemMaster/v1/logs/0x26cd21a8-0x26ce7a8b.
2021-05-13 19:53:00,826 ERROR UfsJournalCheckpointThread - Journal replay error: FileSystemMaster: Failed to read or process journal entry sequence_number: 651025641
update_inode {
  id: 1971409738224726
  last_modification_time_ms: 1620642598232
  last_access_time_ms: 1620642598232
}
.
java.lang.IllegalStateException: Inode 1971409738224726 not found
    at alluxio.master.file.meta.InodeTreePersistentState.applyUpdateInode(InodeTreePersistentState.java:395)
    at alluxio.master.file.meta.InodeTreePersistentState.processJournalEntry(InodeTreePersistentState.java:689)
    at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:30)
    at alluxio.master.journal.JournaledGroup.processJournalEntry(JournaledGroup.java:55)
    at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:30)
    at alluxio.master.journal.ufs.UfsJournalCheckpointThread.runInternal(UfsJournalCheckpointThread.java:191)
    at alluxio.master.journal.ufs.UfsJournalCheckpointThread.run(UfsJournalCheckpointThread.java:163)`

**Comment by yuzhu** [comment]
please give version 2.7.0 a try, as we have addressed similar issues recently.
