### ISSUE TITLE
MetricsHeartbeatContextTest will fail when a local Alluxio cluster is running

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#11147]
**Alluxio Version:**
2.3.0-SNAPSHOT

**Describe the bug**
```
java.lang.AssertionError: expected null, but was:<java.util.concurrent.Executors$DelegatedScheduledExecutorService@7161d8d1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.junit.Assert.assertNull(Assert.java:747)
	at alluxio.client.metrics.MetricsHeartbeatContextTest.testExecutorInitialized(MetricsHeartbeatContextTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**To Reproduce**

1. Have a local Alluxio cluster running
2. Test alluxio.client.metrics.MetricsHeartbeatContextTest
3. Fail

**Expected behavior**
Unit test should pass regardless of whether local Alluxio process is running

**Urgency**
Low

**Additional context**

**Comment by ZacBlanco** [comment]
Do you mean the testing cluster, or just having an external cluster running?

**Comment by apc999** [comment]
> Do you mean the testing cluster, or just having an external cluster running?

Having a standalone external cluster running (not for testing), the test will fail

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is a strong request.
