### ISSUE TITLE
impala stuck in short-circuit read from Alluxio workers

### ISSUE THREAD

**Issue by iAlaska** [Alluxio/alluxio#11157]
**Alluxio Version:**
2.1.1

**Describe the bug**
When deploying Alluxio workers co-located with impala daemon, the impala query via short-circuit mode stuck until query client got this error:

```
e14400f9b170c551:d7faa5b000000008] Disk I/O error on impala-node-1:22000: Error reading from HDFS file: alluxio://master-1:19998;master-2:19998;master-3:19998/data-path/b149e0234165aa32-5cc4d10b00000024_429986748_data.0.parq
Error(255): Unknown error 255
Root cause: DeadlineExceededException: Timeout waiting for response after 30000ms. (LocalFileDataReader{request=block_id: 120661737472
promote: true
, address=WorkerNetAddress{host=worker-1, rpcPort=29999, dataPort=29999, webPort=8080, domainSocketPath=, tieredIdentity=TieredIdentity(node=worker-1, rack=null)}})
    @           0xb4b5b6
    @          0x144b48e
    @          0x144c163
    @          0x144a1e2
    @          0x14417e0
    @          0x11c622f
    @          0x11c6dd9
    @          0x1840c09
```

the worker error logs is blow:
```
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: 11f5c7e3-5c38-41a2-8f06-20df83a11e7d. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: bf046760-64cb-4e73-a7cf-11b8bfa19844. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: 57f8f269-4629-4943-a3b6-7fb1c3566a33. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: eede2602-4b78-49f9-b32b-c9aad58584af. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: 61749897-1a5b-4b67-ba09-c7f2a69f6695. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: 1be1e40a-b900-4a4b-8de9-b0066318c8dd. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: 350680e4-681e-4d2a-a616-46bbb927f555. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: 95e21d2b-2a7a-4f9a-bb19-f8f9366d2616. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: bec25a34-8be3-4639-ac2d-f8c8d02d4da5. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2020-02-27 15:24:39,469 WARN  SaslStreamServerDriver - Error received for channel: 7bb5ee90-d499-4f1e-8262-5b72f077ddf9. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
```

With DEBUG logging leve, I find that, the short-circuit read mode will leave some block unlocked, the screen-shot below shows that there are some lockId is unlocked:

```
2020-02-28 21:42:05,463 DEBUG TieredBlockStore - unlockBlock: lockId=108287
2020-02-28 21:42:05,463 DEBUG TieredBlockStore - lockBlock: sessionId=7794894760981398034, blockId=132170907648
2020-02-28 21:42:05,463 DEBUG TieredBlockStore - accessBlock: sessionId=7794894760981398034, blockId=132170907648
2020-02-28 21:42:05,463 DEBUG TieredBlockStore - getBlockMeta: sessionId=7794894760981398034, blockId=132170907648, lockId=108288
2020-02-28 21:42:05,465 DEBUG TieredBlockStore - lockBlock: sessionId=6764373477415543394, blockId=129822097408
2020-02-28 21:42:05,465 DEBUG TieredBlockStore - getBlockMeta: sessionId=6764373477415543394, blockId=129822097408, lockId=108289
2020-02-28 21:42:05,465 DEBUG TieredBlockStore - unlockBlock: lockId=108289
2020-02-28 21:42:05,465 DEBUG TieredBlockStore - lockBlock: sessionId=6764373477415543394, blockId=129822097408
2020-02-28 21:42:05,465 DEBUG TieredBlockStore - accessBlock: sessionId=6764373477415543394, blockId=129822097408
2020-02-28 21:42:05,465 DEBUG TieredBlockStore - getBlockMeta: sessionId=6764373477415543394, blockId=129822097408, lockId=108290
2020-02-28 21:42:05,466 DEBUG TieredBlockStore - lockBlock: sessionId=8900634991890876552, blockId=132909105152
2020-02-28 21:42:05,466 DEBUG TieredBlockStore - getBlockMeta: sessionId=8900634991890876552, blockId=132909105152, lockId=108291
2020-02-28 21:42:05,466 DEBUG TieredBlockStore - unlockBlock: lockId=108291
2020-02-28 21:42:05,466 DEBUG TieredBlockStore - lockBlock: sessionId=8900634991890876552, blockId=132909105152
2020-02-28 21:42:05,466 DEBUG TieredBlockStore - accessBlock: sessionId=8900634991890876552, blockId=132909105152
2020-02-28 21:42:05,466 DEBUG TieredBlockStore - getBlockMeta: sessionId=8900634991890876552, blockId=132909105152, lockId=108292
2020-02-28 21:42:05,467 DEBUG TieredBlockStore - lockBlock: sessionId=4314004080064914019, blockId=135677345792
2020-02-28 21:42:05,467 DEBUG TieredBlockStore - getBlockMeta: sessionId=4314004080064914019, blockId=135677345792, lockId=108293
2020-02-28 21:42:05,467 DEBUG TieredBlockStore - unlockBlock: lockId=108293
2020-02-28 21:42:05,467 DEBUG TieredBlockStore - lockBlock: sessionId=4314004080064914019, blockId=135677345792
2020-02-28 21:42:05,467 DEBUG TieredBlockStore - accessBlock: sessionId=4314004080064914019, blockId=135677345792
2020-02-28 21:42:05,467 DEBUG TieredBlockStore - getBlockMeta: sessionId=4314004080064914019, blockId=135677345792, lockId=108294
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - lockBlock: sessionId=1805042918594843400, blockId=132187684864
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - getBlockMeta: sessionId=1805042918594843400, blockId=132187684864, lockId=108295
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - unlockBlock: lockId=108295
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - lockBlock: sessionId=1805042918594843400, blockId=132187684864
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - accessBlock: sessionId=1805042918594843400, blockId=132187684864
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - getBlockMeta: sessionId=1805042918594843400, blockId=132187684864, lockId=108296
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - lockBlock: sessionId=7037402169642128379, blockId=131248160768
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - getBlockMeta: sessionId=7037402169642128379, blockId=131248160768, lockId=108297
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - unlockBlock: lockId=108297
2020-02-28 21:42:05,471 DEBUG TieredBlockStore - lockBlock: sessionId=7037402169642128379, blockId=131248160768
2020-02-28 21:42:05,472 DEBUG TieredBlockStore - accessBlock: sessionId=7037402169642128379, blockId=131248160768
2020-02-28 21:42:05,472 DEBUG TieredBlockStore - getBlockMeta: sessionId=7037402169642128379, blockId=131248160768, lockId=108298
2020-02-28 21:42:05,474 DEBUG TieredBlockStore - lockBlock: sessionId=6270361875206346842, blockId=132204462080
2020-02-28 21:42:05,474 DEBUG TieredBlockStore - getBlockMeta: sessionId=6270361875206346842, blockId=132204462080, lockId=108299
2020-02-28 21:42:05,474 DEBUG TieredBlockStore - unlockBlock: lockId=108299
2020-02-28 21:42:05,474 DEBUG TieredBlockStore - lockBlock: sessionId=6270361875206346842, blockId=132204462080
2020-02-28 21:42:05,474 DEBUG TieredBlockStore - accessBlock: sessionId=6270361875206346842, blockId=132204462080
2020-02-28 21:42:05,474 DEBUG TieredBlockStore - getBlockMeta: sessionId=6270361875206346842, blockId=132204462080, lockId=108300
2020-02-28 21:42:05,475 DEBUG TieredBlockStore - lockBlock: sessionId=6608573645040416111, blockId=134150619136
2020-02-28 21:42:05,475 DEBUG TieredBlockStore - getBlockMeta: sessionId=6608573645040416111, blockId=134150619136, lockId=108301
2020-02-28 21:42:05,475 DEBUG TieredBlockStore - unlockBlock: lockId=108301
2020-02-28 21:42:05,475 DEBUG TieredBlockStore - lockBlock: sessionId=6608573645040416111, blockId=134150619136
2020-02-28 21:42:05,475 DEBUG TieredBlockStore - accessBlock: sessionId=6608573645040416111, blockId=134150619136
2020-02-28 21:42:05,475 DEBUG TieredBlockStore - getBlockMeta: sessionId=6608573645040416111, blockId=134150619136, lockId=108302
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - lockBlock: sessionId=830431431466224508, blockId=135140474880
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - getBlockMeta: sessionId=830431431466224508, blockId=135140474880, lockId=108303
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - unlockBlock: lockId=108303
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - lockBlock: sessionId=830431431466224508, blockId=135140474880
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - accessBlock: sessionId=830431431466224508, blockId=135140474880
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - getBlockMeta: sessionId=830431431466224508, blockId=135140474880, lockId=108304
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - lockBlock: sessionId=3353545106950701733, blockId=130157641728
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - getBlockMeta: sessionId=3353545106950701733, blockId=130157641728, lockId=108305
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - unlockBlock: lockId=108305
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - lockBlock: sessionId=3353545106950701733, blockId=130157641728
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - accessBlock: sessionId=3353545106950701733, blockId=130157641728
2020-02-28 21:42:05,476 DEBUG TieredBlockStore - getBlockMeta: sessionId=3353545106950701733, blockId=130157641728, lockId=108306
2020-02-28 21:42:05,477 DEBUG TieredBlockStore - lockBlock: sessionId=8571161711369667205, blockId=133462753280
2020-02-28 21:42:05,477 DEBUG TieredBlockStore - getBlockMeta: sessionId=8571161711369667205, blockId=133462753280, lockId=108307
2020-02-28 21:42:05,477 DEBUG TieredBlockStore - unlockBlock: lockId=108307
2020-02-28 21:42:05,477 DEBUG TieredBlockStore - lockBlock: sessionId=8571161711369667205, blockId=133462753280
2020-02-28 21:42:05,477 DEBUG TieredBlockStore - accessBlock: sessionId=8571161711369667205, blockId=133462753280
2020-02-28 21:42:05,477 DEBUG TieredBlockStore - getBlockMeta: sessionId=8571161711369667205, blockId=133462753280, lockId=108308
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - lockBlock: sessionId=5438107286264967486, blockId=129268449280
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - getBlockMeta: sessionId=5438107286264967486, blockId=129268449280, lockId=108309
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - unlockBlock: lockId=108309
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - lockBlock: sessionId=5438107286264967486, blockId=129268449280
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - accessBlock: sessionId=5438107286264967486, blockId=129268449280
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - getBlockMeta: sessionId=5438107286264967486, blockId=129268449280, lockId=108310
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - lockBlock: sessionId=4630461672940542999, blockId=135576682496
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - getBlockMeta: sessionId=4630461672940542999, blockId=135576682496, lockId=108311
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - unlockBlock: lockId=108311
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - lockBlock: sessionId=4630461672940542999, blockId=135576682496
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - accessBlock: sessionId=4630461672940542999, blockId=135576682496
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - getBlockMeta: sessionId=4630461672940542999, blockId=135576682496, lockId=108312
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - lockBlock: sessionId=6267635712150113775, blockId=132456120320
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - getBlockMeta: sessionId=6267635712150113775, blockId=132456120320, lockId=108313
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - unlockBlock: lockId=108313
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - lockBlock: sessionId=6267635712150113775, blockId=132456120320
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - accessBlock: sessionId=6267635712150113775, blockId=132456120320
2020-02-28 21:42:05,478 DEBUG TieredBlockStore - getBlockMeta: sessionId=6267635712150113775, blockId=132456120320, lockId=108314
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - lockBlock: sessionId=3091469283856730141, blockId=133529862144
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - getBlockMeta: sessionId=3091469283856730141, blockId=133529862144, lockId=108315
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - unlockBlock: lockId=108315
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - lockBlock: sessionId=2668616315875892044, blockId=133076877312
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - lockBlock: sessionId=3091469283856730141, blockId=133529862144
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - accessBlock: sessionId=3091469283856730141, blockId=133529862144
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - getBlockMeta: sessionId=3091469283856730141, blockId=133529862144, lockId=108317
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - getBlockMeta: sessionId=2668616315875892044, blockId=133076877312, lockId=108316
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - unlockBlock: lockId=108316
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - lockBlock: sessionId=2668616315875892044, blockId=133076877312
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - accessBlock: sessionId=2668616315875892044, blockId=133076877312
2020-02-28 21:42:05,479 DEBUG TieredBlockStore - getBlockMeta: sessionId=2668616315875892044, blockId=133076877312, lockId=108318
2020-02-28 21:42:05,480 DEBUG TieredBlockStore - lockBlock: sessionId=8584071228195598249, blockId=132925882368
2020-02-28 21:42:05,480 DEBUG TieredBlockStore - getBlockMeta: sessionId=8584071228195598249, blockId=132925882368, lockId=108319
2020-02-28 21:42:05,480 DEBUG TieredBlockStore - unlockBlock: lockId=108319
2020-02-28 21:42:05,480 DEBUG TieredBlockStore - lockBlock: sessionId=8584071228195598249, blockId=132925882368
2020-02-28 21:42:05,480 DEBUG TieredBlockStore - accessBlock: sessionId=8584071228195598249, blockId=132925882368
2020-02-28 21:42:05,480 DEBUG TieredBlockStore - getBlockMeta: sessionId=8584071228195598249, blockId=132925882368, lockId=108320
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=4328505845264682018, blockId=136532983808
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=4328505845264682018, blockId=136532983808, lockId=108321
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - unlockBlock: lockId=108321
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=4328505845264682018, blockId=136532983808
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - accessBlock: sessionId=4328505845264682018, blockId=136532983808
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=4328505845264682018, blockId=136532983808, lockId=108322
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=5423910930064213689, blockId=132003135488
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=5423910930064213689, blockId=132003135488, lockId=108323
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - unlockBlock: lockId=108323
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=5423910930064213689, blockId=132003135488
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - accessBlock: sessionId=5423910930064213689, blockId=132003135488
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=5423910930064213689, blockId=132003135488, lockId=108324
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=4640613358677609042, blockId=129704656896
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=4640613358677609042, blockId=129704656896, lockId=108325
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - unlockBlock: lockId=108325
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=4640613358677609042, blockId=129704656896
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - accessBlock: sessionId=4640613358677609042, blockId=129704656896
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=202648087762963574, blockId=132221239296
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=4640613358677609042, blockId=129704656896, lockId=108326
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=202648087762963574, blockId=132221239296, lockId=108327
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - unlockBlock: lockId=108327
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - lockBlock: sessionId=202648087762963574, blockId=132221239296
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - accessBlock: sessionId=202648087762963574, blockId=132221239296
2020-02-28 21:42:05,481 DEBUG TieredBlockStore - getBlockMeta: sessionId=202648087762963574, blockId=132221239296, lockId=108328
2020-02-28 21:42:05,482 DEBUG TieredBlockStore - lockBlock: sessionId=8760234457407806301, blockId=130627403776
2020-02-28 21:42:05,482 DEBUG TieredBlockStore - getBlockMeta: sessionId=8760234457407806301, blockId=130627403776, lockId=108329
2020-02-28 21:42:05,482 DEBUG TieredBlockStore - unlockBlock: lockId=108329
2020-02-28 21:42:05,482 DEBUG TieredBlockStore - lockBlock: sessionId=8760234457407806301, blockId=130627403776
2020-02-28 21:42:05,482 DEBUG TieredBlockStore - accessBlock: sessionId=8760234457407806301, blockId=130627403776
2020-02-28 21:42:05,482 DEBUG TieredBlockStore - getBlockMeta: sessionId=8760234457407806301, blockId=130627403776, lockId=108330
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - lockBlock: sessionId=1195478705163256333, blockId=130426077184
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - getBlockMeta: sessionId=1195478705163256333, blockId=130426077184, lockId=108331
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - unlockBlock: lockId=108331
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - lockBlock: sessionId=1195478705163256333, blockId=130426077184
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - accessBlock: sessionId=1195478705163256333, blockId=130426077184
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - getBlockMeta: sessionId=1195478705163256333, blockId=130426077184, lockId=108332
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - lockBlock: sessionId=4505794339556324373, blockId=134737821696
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - getBlockMeta: sessionId=4505794339556324373, blockId=134737821696, lockId=108333
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - unlockBlock: lockId=108333
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - lockBlock: sessionId=4505794339556324373, blockId=134737821696
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - accessBlock: sessionId=4505794339556324373, blockId=134737821696
2020-02-28 21:42:05,484 DEBUG TieredBlockStore - getBlockMeta: sessionId=4505794339556324373, blockId=134737821696, lockId=108334
```

and after killing all impala daemon, the worker can now unlock those locks:
```
2020-03-13 10:18:29,522 DEBUG grpc-default-executor-3021 ShortCircuitBlockReadHandler:127 - Exception occurred processing read request block_id: 656509239296
promote: true
.
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
        at io.grpc.Status.asRuntimeException(Status.java:521)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272)
        at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
        at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:293)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:741)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-13 10:18:29,952 DEBUG grpc-default-executor-3021 TieredBlockStore:180 - unlockBlock: lockId=906290
```

may be some block lock is keeped until impala client exit?

**To Reproduce**

1. deploy alluxio workers co-located with impala daemon
2. create impala table with location refers to alluxio. eg. 'alluxio://'
3. do some query on alluxio-table
4. if step 3 didn't get stuck immediately, retry serveral times and the query will got stuck.

**Additional context**

After move alluxio workers out of impala cluster, all queries is running very well. but all scanned data is transmitted via network, and can't use short-circuit mode to improve io performance.

there is our `alluxio-site.properties` config file: 
```
# Common properties
alluxio.master.hostname=${hostname}
alluxio.master.rpc.port=19998
alluxio.master.web.port=8080
#alluxio.worker.rpc.port=31498
alluxio.worker.web.port=8080
alluxio.master.mount.table.root.ufs=hdfs://xxx/user/hive/warehouse/alluxio/root
alluxio.underfs.hdfs.configuration=/etc/hadoop/conf/core-site.xml:/etc/hadoop/conf/hdfs-site.xml
alluxio.integration.master.resource.cpu=20
alluxio.integration.master.resource.mem=20GB
# UFS HA
alluxio.zookeeper.enabled=true
alluxio.zookeeper.address=zk1:2181,zk2:2181,zk3:2181
alluxio.zookeeper.session.timeout=120s
alluxio.master.journal.type=UFS
alluxio.master.journal.folder=hdfs://xxx/alluxio/journal/
# Worker properties
alluxio.worker.memory.size=10GB
alluxio.worker.tieredstore.levels=1
alluxio.worker.tieredstore.level0.alias=SSD
alluxio.worker.tieredstore.level0.dirs.path=/data1/alluxio/nvm,/data2/alluxio/nvm,/data3/alluxio/nvm,/data4/alluxio/nvm
alluxio.worker.tieredstore.level0.dirs.quota=3.2TB,3.2TB,3.2TB
alluxio.worker.tieredstore.level0.watermark.high.ratio=0.9
alluxio.worker.tieredstore.level0.watermark.low.ratio=0.7
alluxio.integration.worker.resource.cpu=40
alluxio.integration.worker.resource.mem=50GB
# User properties
alluxio.user.file.writetype.default=CACHE_THROUGH
# Security
alluxio.master.security.impersonation.yarn.users=*
alluxio.master.security.impersonation.hive.users=*
alluxio.master.security.impersonation.impala.users=*
alluxio.master.security.impersonation.cydw.users=*

```

**Comment by iAlaska** [comment]
Hey guys, i dump the thread stack of impalad here, hope will give some help.
and  this issue still exists in `alluxio-2.2.0`.
[impalad_stacks_1.txt](https://github.com/Alluxio/alluxio/files/4338286/impalad_stacks_1.txt)
[impalad_stacks_2.txt](https://github.com/Alluxio/alluxio/files/4338289/impalad_stacks_2.txt)
[impalad_stacks_3.txt](https://github.com/Alluxio/alluxio/files/4338290/impalad_stacks_3.txt)

**Comment by apc999** [comment]
@jiacheliu3 @dbw9580 , do you still see this happen?

**Comment by dbw9580** [comment]
Not if we disable impala file handle cache: set `max_cache_file_handles` to 0. Things could be improved from Impala side, that if an Alluxio URI is spotted, disable file handle cache automatically.

**Comment by MyqueWooMiddo** [comment]
@iAlaska  why do you separate alluxio worker and impalad ? 
Do you find "BytesReadShortCircuit" in query profile when all the tables of query are on alluxio scheme?
