### ISSUE TITLE
AsyncBlockRemover stuck not freeing any blocks

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#11309]
**Alluxio Version:**
2.1.1

**Describe the bug**
This issue is reported by @JySongWithZhangCe 

`alluxio fs free /` freed the root mount. One worker failed to free the space, as illustrated.

![image](https://user-images.githubusercontent.com/14806853/79546912-c7f73100-80c5-11ea-8c50-f9de1a793623.png)

In the worker.log there are a lot of below message
```
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 504054677506 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 502712500226 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 503652024322 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 504591548418 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 503584915458 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 505078087685 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 505010978821 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 504004345861 is being removed. Current queue size is 320.
2020-04-17 14:50:41,485 DEBUG AsyncBlockRemover - 502662168581 is being removed. Current queue size is 320.
```
AsycBlockRemover gets a lot of remove calls but remove is not making any progress. There are around 85K lines of above message, whereas the queue size stays 320.

Whenever a block is successfully removed by AsyncBlockRemover there should be one below line in the debug log. However compared to 85K above log msgs, there are like 2 blocks successfully removed.
```
Block XXX is removed in thread XXX.
```

I did a `jstack` on Alluxio worker and ALL remover threads are waiting on the block lock.
```
"block-removal-service-8" #1097 daemon prio=5 os_prio=0 tid=0x00007f8e0d5be800 nid=0x155c4d waiting on condition [0x00007f8a44ed1000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006b416a280> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.Semaphore.acquireUninterruptibly(Semaphore.java:494)
	at alluxio.worker.block.ClientRWLock$SessionLock.lock(ClientRWLock.java:92)
	at alluxio.worker.block.BlockLockManager.lockBlock(BlockLockManager.java:114)
	at alluxio.worker.block.TieredBlockStore.removeBlockInternal(TieredBlockStore.java:835)
	at alluxio.worker.block.TieredBlockStore.removeBlock(TieredBlockStore.java:351)
	at alluxio.worker.block.TieredBlockStore.removeBlock(TieredBlockStore.java:344)
	at alluxio.worker.block.DefaultBlockWorker.removeBlock(DefaultBlockWorker.java:517)
	at alluxio.worker.block.AsyncBlockRemover$BlockRemover.run(AsyncBlockRemover.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

See attachment for jstack and worker.log.

**To Reproduce**
This only happened once and is not very easily reproduced.

1. Mount HDFS to alluxio.
2. Run Presto queries and use a lot of worker space.
3. Run `alluxio fs free /`. (The `free` command didn't return any error. After the `free` ALL files under Alluxio from `alluxio fs ls -R /` showing 0%.)

**Expected behavior**
AsyncBlockRemover makes progress.

**Urgency**
MEDIUM

**Additional context**
[worker.log](https://github.com/Alluxio/alluxio/files/4491746/worker.log)
[jstack.log](https://github.com/Alluxio/alluxio/files/4491747/jstack.log)

**Comment by jiacheliu3** [comment]
@calvinjia Could you pls take a look at this issue? My suspicion is BlockLockManager is not properly releasing block locks somewhere.

https://github.com/Alluxio/alluxio/blob/55e11be2ca437bc9fd5be719e15098f9fc333bf8/core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java#L245

**Comment by ZacBlanco** [comment]
@jiacheliu3 this could be due to a few reasons.

This issue is possible related to #11258 which I have just opened a PR to fix.

**Comment by jiacheliu3** [comment]
@ZacBlanco The waiting conditions look the same to me. I think they are the same issue.

**Comment by ZacBlanco** [comment]
@JySongWithZhangCe do you have the corresponding `worker.out` available?

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe do you have the corresponding `worker.out` available?
All logs in worker.out looks like below:
Apr 17, 2020 5:58:44 PM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 37
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:591)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:239)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ZacBlanco** [comment]
This issue may be fixed due to amy PR. @JySongWithZhangCe are you able to build and test a tarball off of `master` or `branch-2.2` to see if the issue still persists? We won't be releasing for a while.

If you're able to test and this problem still occurs, we can dig further.

**Comment by JySongWithZhangCe** [comment]
> This issue may be fixed due to my recent PR. @JySongWithZhangCe are you able to build and test a tarball off of `master` or `branch-2.2` to see if the issue still persists? We won't be releasing for a while.
> 
> If you're able to test and this problem still occurs, we can dig further.

sure

**Comment by iAlaska** [comment]
Hello @ZacBlanco  I encountered the same problem on `alluxio-2.3.0`. All `block-removal-service-%d` threads blocked for acquire lock. I dumped the heap blew, **`SessionLock` has 10 more instances than `LockRecord`, while the size of block-removal-service pool is 10**. Is there some case that no release `SessionLocak` instances?
```
 num     #instances         #bytes  class name
----------------------------------------------
...
 91:          1234          39488  alluxio.worker.block.BlockLockManager$LockRecord
 109:          1244          29856  alluxio.worker.block.ClientRWLock$SessionLock
```

**Comment by maobaolong** [comment]
Hi @apc999 I think this issue and #12444 are the urgent issue, shall we take a deep investigation about this issue?

**Comment by LuQQiu** [comment]
Looks like somewhere in our code the locks aren't released well.
We previously has a SessionCleaner which is added by @apc999  which marks each client as a session, when the client doesn't have activities for some period of time, we clean all the locks holding by this client(session). This will help prevent this issue when we haven't figured out where locks are lost.

**Comment by JySongWithZhangCe** [comment]
I'v meet a bug before:
 1.Alluxio Worker had already stop 
 2.Spark Executor was running 
 3.TCP link in Alluxio Worker's host between Alluxio Worker and Alluxio Client created by Spark Executor still there, but no pid it was belong to.
 4.This bug is instable
I guess, if Alluxio Client has been released but TCP link will still exits, this problem can lead the dead lock

**Comment by LuQQiu** [comment]
(ShortCurcit) BlockReaderHandler acquire lock when opening the block, and releasing the block lock when completed. Locks could be leaved unreleased if 
1) read connection has been broken before releasing the lock
2) read connection left unbroken for whatever reason and does not enter the releasing lock process.

**Comment by apc999** [comment]
shall be solved by https://github.com/Alluxio/alluxio/pull/12643
