### ISSUE TITLE
A tool to identify inconsistent disk failures

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#11389]
**Is your feature request related to a problem? Please describe.**
Yeah, when one disk of one of the workers has inconsistent disk failures, client operations are likely to fail. 
For example, in an Alluxio cluster with 5 workers, each worker is configured with 4 SSD. One of the SSD is flaky with error:
```
2020-04-29 18:00:38,584 ERROR AbstractReadHandler - Failed to close the request.
java.nio.file.NoSuchFileException: /ssd1/alluxioworker/.tmp_blocks/101/<block>
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
    at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
    at java.nio.file.Files.move(Files.java:1395)
    at alluxio.util.io.FileUtils.move(FileUtils.java:207)
    at alluxio.worker.block.TieredBlockStore.commitBlockInternal(TieredBlockStore.java:547)
    at alluxio.worker.block.TieredBlockStore.commitBlock(TieredBlockStore.java:269)
    at alluxio.worker.block.DefaultBlockWorker.commitBlock(DefaultBlockWorker.java:327)
    at alluxio.worker.block.DefaultBlockWorker.closeUfsBlock(DefaultBlockWorker.java:605)
    at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.completeRequest(BlockReadHandler.java:96)
    at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.completeRequest(BlockReadHandler.java:70)
    at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:407)
    at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:323)
    at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
2020-04-29 18:00:38,589 WARN  UnderFileSystemBlockReader - Failed to update block writer for UFS block [blockId: <id>, ufsPath: <ufs_path>, offset: 0]: Failed to create block path  /ssd1/alluxioworker/.tmp_blocks/22/<block>
2020-04-29 18:00:38,650 WARN  AbstractReadHandler - Exception occurred while completing read request BlockReadRequest{chunkSize=..., end=...., id=..., openUfsBlockOptions=ufs_path: "<path>"
offset_in_file: ...
block_size:....
maxUfsReadConcurrency: ...
mountId: 1
no_cache: false
, promote=true, sessionId=...., start=0}.: /ssd1/alluxioworker/.tmp_blocks/13/<block>
```

When this happens, all the client operations may be affected. Any operations that go to this SSD will be stuck there. Some operations with a retry mechanism will eventually succeed but take a long time.

After removing this flaky SSD, all client operations work as expected. 

**Describe the solution you'd like**

Solution 1: Better handle this kind of error and do not block client operations. (bigger scope and may be harder to implement
Solution 2: Have a tool to identify this kind of inconsistent disk failures and warn users at the very first beginning when it occurs.

**Comment by jiacheliu3** [comment]
How do you define a "flaky disk"? Maybe a broken disk can be told by `alluxio runTests`? A further question may be, is detecting the flakiness of physical device beyond our boundary?

**Comment by jja725** [comment]
Seems like it's not priority
