### ISSUE TITLE
presto read alluxio  error

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#11406]
**problem description**

i use "alluxio fs load /path"     to  load data from hdfs to alluxio, and it returns ok.

but when i use presto to query the hive table, it shows up the error message like below:
Error reading from alluxio:/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000006_0 at position 1020599375

does it because the ufs file changed? as the hive table is inserted  after  "alluxio fs load /path"  

**detailed logs like below:
alluxio load log**
alluxio fs load /user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000017_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000016_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000015_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000014_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000013_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000012_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000011_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000010_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000019_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000018_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000020_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000006_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000005_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000004_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000003_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000002_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000001_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000000_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000021_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000022_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000023_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000024_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000025_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000009_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000008_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000007_0 already in Alluxio fully
/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc loaded
 
 
 **presto logs:**
2020-05-09T11:18:30.778+0800    ERROR   remote-task-callback-68580      com.facebook.presto.execution.StageStateMachine Stage 20200509_031830_23065_j7y8m.1 failed
com.facebook.presto.spi.PrestoException: Error reading from alluxio:/user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc/000022_0 at position 1020725540
        at com.facebook.presto.hive.orc.HdfsOrcDataSource.readInternal(HdfsOrcDataSource.java:80)
        at com.facebook.presto.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:105)
        at com.facebook.presto.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:96)
        at com.facebook.presto.orc.OrcReader.<init>(OrcReader.java:118)
        at com.facebook.presto.orc.OrcReader.<init>(OrcReader.java:80)
        at com.facebook.presto.hive.orc.OrcBatchPageSourceFactory.createOrcPageSource(OrcBatchPageSourceFactory.java:197)
        at com.facebook.presto.hive.orc.OrcBatchPageSourceFactory.createPageSource(OrcBatchPageSourceFactory.java:122)
        at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:273)
        at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:120)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:51)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:248)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_227_d0b486e____20200509_004508_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at alluxio.hadoop.HdfsFileInputStream.readFully(HdfsFileInputStream.java:147)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)
        at com.facebook.presto.hive.orc.HdfsOrcDataSource.readInternal(HdfsOrcDataSource.java:65)

**Comment by apc999** [comment]
Hi @jiemar  yes it looks to me the file has been updated. Two tips here:
(1) Run `alluxio fs ls -f /user/hive/warehouse/cx_dwd_safe.db/dwd_customer_group_enterprise_base_info_yzt_tyc` to force reload files in the directory.
(2) Run `alluxio fs distributedLoad` instead of `alluxio fs load` for better performance.

**Comment by jiemar** [comment]
hi @apc999 
if i set property  alluxio.user.file.metadata.sync.interval=0    at presto client site properties file,
will i avoid the problem ?
