### ISSUE TITLE
Why alluxio needs to create _$folder$ on OSS

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#11437]
**Alluxio Version:**
2.2.0

**Describe the bug**
I’m using alluxio to access aliyun oss in read only way. So the AK I’m using only has read permission. But I see the following error, it tries to create  _$folder$ :

```
2020-05-15 07:43:50,979 ERROR OSSUnderFileSystem - Failed to create object: _$folder$
com.aliyun.oss.OSSException: You have no right to access this object because of bucket acl.
[ErrorCode]: AccessDenied
[RequestId]: 5EBE4836EA377932322D1E7B
[HostId]: imagenet-shanghai.oss-cn-shanghai-internal.aliyuncs.com
[ResponseError]:
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>You have no right to access this object because of bucket acl.</Message>
  <RequestId>5EBE4836EA377932322D1E7B</RequestId>
  <HostId>imagenet-shanghai.oss-cn-shanghai-internal.aliyuncs.com</HostId>
</Error>

	at com.aliyun.oss.common.utils.ExceptionFactory.createOSSException(ExceptionFactory.java:100)
	at com.aliyun.oss.internal.OSSErrorResponseHandler.handle(OSSErrorResponseHandler.java:70)
	at com.aliyun.oss.common.comm.ServiceClient.handleResponse(ServiceClient.java:257)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:140)
	at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:70)
	at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:83)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:145)
	at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:102)
	at com.aliyun.oss.internal.OSSObjectOperation.writeObjectInternal(OSSObjectOperation.java:1125)
	at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:130)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:491)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:475)
	at alluxio.underfs.oss.OSSUnderFileSystem.createEmptyObject(OSSUnderFileSystem.java:133)
	at alluxio.underfs.ObjectUnderFileSystem.mkdirsInternal(ObjectUnderFileSystem.java:1079)
	at alluxio.underfs.ObjectUnderFileSystem.getObjectListingChunkForPath(ObjectUnderFileSystem.java:945)
	at alluxio.underfs.ObjectUnderFileSystem.listInternal(ObjectUnderFileSystem.java:969)
	at alluxio.underfs.ObjectUnderFileSystem.listStatus(ObjectUnderFileSystem.java:604)
	at alluxio.underfs.UnderFileSystemWithLogging$32.call(UnderFileSystemWithLogging.java:730)
	at alluxio.underfs.UnderFileSystemWithLogging$32.call(UnderFileSystemWithLogging.java:727)
	at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:1187)
	at alluxio.underfs.UnderFileSystemWithLogging.listStatus(UnderFileSystemWithLogging.java:727)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$27.execute(ManagedBlockingUfsForwarder.java:374)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$27.execute(ManagedBlockingUfsForwarder.java:371)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.block(ManagedBlockingUfsForwarder.java:596)
	at alluxio.concurrent.jsr.ForkJoinPool.managedBlock(ForkJoinPool.java:1004)
	at alluxio.concurrent.ForkJoinPoolHelper.safeManagedBlock(ForkJoinPoolHelper.java:41)
	at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.get(ManagedBlockingUfsForwarder.java:582)
	at alluxio.concurrent.ManagedBlockingUfsForwarder.listStatus(ManagedBlockingUfsForwarder.java:376)
	at alluxio.master.file.DefaultFileSystemMaster.loadMetadataInternal(DefaultFileSystemMaster.java:2416)
	at alluxio.master.file.DefaultFileSystemMaster.loadMetadataIfNotExist(DefaultFileSystemMaster.java:2665)
	at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:875)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$listStatus$8(FileSystemMasterClientServiceHandler.java:224)
	at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.listStatus(FileSystemMasterClientServiceHandler.java:222)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2170)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
	at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
	at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1355)
	at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
@cheyang this is b/c the current OSS connector is out of date. We used to use
this suffix to create a zero-byte file to annotate a path is a folder.
This is actually no longer needed in most of the Alluxio Object Store UFSes. 
However OSS implementation was not updated.

As a workaround, you can set `alluxio.underfs.object.store.breadcrumbs.enabled=false` to prevent creating such empty objects.

**Comment by cheyang** [comment]
> @cheyang this is b/c the current OSS adaptor is out of date. We used to use
> this suffix to create a zero-byte file to annotate a path is a folder.
> This is actually no longer needed in most of the Alluxio Object Store UFSes.
> However OSS implementation was not updated.
> 
> As a workaround, you can set `alluxio.underfs.object.store.breadcrumbs.enabled=false` to prevent creating such empty objects.

I'm just wondering the reason to create such zero-byte file.
Is it helpful to improve performance when listing metadata from OSS? Not urgent. Thanks.

**Comment by apc999** [comment]
This was a popular way in AWS S3 and similar object storage to emulate a "real file system" and facilitate applications. The motivation is for performance.

**Comment by living42** [comment]
> @cheyang this is b/c the current OSS adaptor is out of date. We used to use
> this suffix to create a zero-byte file to annotate a path is a folder.
> This is actually no longer needed in most of the Alluxio Object Store UFSes.
> However OSS implementation was not updated.
> 
> As a workaround, you can set `alluxio.underfs.object.store.breadcrumbs.enabled=false` to prevent creating such empty objects.

I'am trying this option, but was'nt able to take effect, i found that `mkdirs` don't honour this option.

**Comment by apc999** [comment]
@living42  thanks for reporting this, we will address this issue shortly.

**Comment by jja725** [comment]
@LuQQiu  is this still valid? otherwise, help me close this please
