### ISSUE TITLE
 io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by phoenixwu0229** [Alluxio/alluxio#11434]
**Alluxio Version:**
2.2.0

**Describe the bug**

I am running deep learning with alluxio fuse. It's failed due to Input/output error. And the error in Alluxio fuse is
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 8587837719, max: 8589934592)

**To Reproduce**

Increase direct memory  from 4G to 8G by setting `-XX:MaxDirectMemorySize=8g`. But still encounter

```
o.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
  at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
  at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 8587837719, max: 8589934592)
  at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:725)
  at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:680)
  at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
  at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
  at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
  at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
  at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
  at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:342)
  at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
  at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
  at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
  at io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:532)
  at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:92)
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
  at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
```

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
it is likely due to 
1 a lot of pending unclosed gRPC connections: in FUSE, connections are only closed when 'release' is called and this can be async, which may keep a lot of gRPC connections around
2 a few buffer leak recently fixed

we will fix this issue in 2.6.2
