### ISSUE TITLE
OutOfDirectMemoryError when reading using AlluxioFuseFileSystem

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#11433]
**Alluxio Version:**
2.2.0

**Describe the bug**
with JVM Opts
```
jvmOptions: " -Xmx4G -Xms4G "
```

```
2020-05-14 07:56:47,877 ERROR AlluxioFuseFileSystem - Failed to read file /d_s_1104/sample/part-r-00339.tfr
alluxio.exception.status.UnknownException: Unknown error (Zero Copy GrpcDataReader)
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:159)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:265)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:246)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:164)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receiveDataMessage(GrpcDataMessageBlockingStream.java:84)
	at alluxio.client.block.stream.GrpcDataReader.readChunkInternal(GrpcDataReader.java:135)
	at alluxio.client.block.stream.GrpcDataReader.lambda$readChunk$0(GrpcDataReader.java:123)
	at alluxio.client.LoggingUtils.callAndLog(LoggingUtils.java:63)
	at alluxio.client.block.stream.GrpcDataReader.readChunk(GrpcDataReader.java:123)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:419)
	at alluxio.client.block.stream.BlockInStream.readInternal(BlockInStream.java:268)
	at alluxio.client.block.stream.BlockInStream.lambda$read$0(BlockInStream.java:255)
	at alluxio.client.LoggingUtils.callAndLog(LoggingUtils.java:63)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:255)
	at alluxio.client.file.AlluxioFileInStream.readInternal(AlluxioFileInStream.java:192)
	at alluxio.client.file.AlluxioFileInStream.lambda$read$1(AlluxioFileInStream.java:145)
	at alluxio.client.LoggingUtils.callAndLog(LoggingUtils.java:63)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:145)
	at alluxio.fuse.AlluxioFuseFileSystem.readInternal(AlluxioFuseFileSystem.java:618)
	at alluxio.fuse.AlluxioFuseFileSystem.lambda$read$7(AlluxioFuseFileSystem.java:586)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:246)
	at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:176)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 4292870423, max: 4294967296)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:725)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:680)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:342)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	at io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:532)
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:92)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more
```

**To Reproduce**

**Expected behavior**

**Urgency**

**Additional context**

**Comment by phoenixwu0229** [comment]
I also encountered this problem

**Comment by apc999** [comment]
duplicate of https://github.com/Alluxio/alluxio/issues/11434
