### ISSUE TITLE
alluxio.shaded.client.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Failed to request 8388608 bytes after 10,000ms to create blockId 50751078420

### ISSUE THREAD

**Issue by jinhang** [Alluxio/alluxio#11502]
**Alluxio Version:**
2.2.1

**Describe the bug**

`space_to_reserve: 8388608
medium_type: ""
pin_on_create: false
, address=WorkerNetAddress{host=*, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=*, rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:143)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:265)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:246)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:164)
	at alluxio.client.block.stream.LocalFileDataWriter.ensureReserved(LocalFileDataWriter.java:193)
	at alluxio.client.block.stream.LocalFileDataWriter.writeChunk(LocalFileDataWriter.java:129)
	at alluxio.client.block.stream.BlockOutStream.updateCurrentChunk(BlockOutStream.java:280)
	at alluxio.client.block.stream.BlockOutStream.write(BlockOutStream.java:159)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:254)
	... 15 more
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Failed to request 8388608 bytes after 10,000ms to create blockId 50751078420
	at alluxio.shaded.client.io.grpc.Status.asRuntimeException(Status.java:533)
	at alluxio.shaded.client.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at alluxio.shaded.client.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:176)
	at alluxio.shaded.client.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at alluxio.shaded.client.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at alluxio.shaded.client.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-06-02 14:39:24,539 INFO mapreduce.Job:  map 91% reduce 0%
2020-06-02 14:39:24,541 INFO mapreduce.Job: Task Id : attempt_1590827250007_0067_m_000059_2, Status : FAILED
Error: java.io.IOException: Failed to cache: Failed to request 8388608 bytes after 10,000ms to create blockId 50700746811 (LocalFileDataWriter{request=block_id: 50700746811
tier: 0
space_to_reserve: 8388608
medium_type: ""
pin_on_create: false
, address=WorkerNetAddress{host=*, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=*, rack=null)}})
	at alluxio.client.file.AlluxioFileOutStream.handleCacheWriteException(AlluxioFileOutStream.java:300)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:263)
	at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:217)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:57)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at org.apache.hadoop.fs.TestDFSIO$WriteMapper.doIO(TestDFSIO.java:438)
	at org.apache.hadoop.fs.TestDFSIO$WriteMapper.doIO(TestDFSIO.java:406)
	at org.apache.hadoop.fs.IOMapperBase.map(IOMapperBase.java:134)
	at org.apache.hadoop.fs.IOMapperBase.map(IOMapperBase.java:37)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:178)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:172)
Caused by: alluxio.exception.status.ResourceExhaustedException: Failed to request 8388608 bytes after 10,000ms to create blockId 50700746811 (LocalFileDataWriter{request=block_id: 50700746811
tier: 0
space_to_reserve: 8388608
medium_type: ""
pin_on_create: false
, address=WorkerNetAddress{host=*, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=*, rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:143)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:265)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:246)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:164)
	at alluxio.client.block.stream.LocalFileDataWriter.ensureReserved(LocalFileDataWriter.java:193)
	at alluxio.client.block.stream.LocalFileDataWriter.writeChunk(LocalFileDataWriter.java:129)
	at alluxio.client.block.stream.BlockOutStream.updateCurrentChunk(BlockOutStream.java:280)
	at alluxio.client.block.stream.BlockOutStream.write(BlockOutStream.java:159)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:254)
	... 15 more
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Failed to request 8388608 bytes after 10,000ms to create blockId 50700746811
	at alluxio.shaded.client.io.grpc.Status.asRuntimeException(Status.java:533)
	at alluxio.shaded.client.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at alluxio.shaded.client.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:176)
	at alluxio.shaded.client.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at alluxio.shaded.client.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at alluxio.shaded.client.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at alluxio.shaded.client.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**To Reproduce**
run testDFSIO case

**Expected behavior**
ok

**Urgency**
not

**Additional context**
others

**Comment by ZacBlanco** [comment]
If you are seeing this exception it is not a bug. This means that the worker is under too much load. You need to increase the number of threads available to the worker, or the number of workers available to serve requests

**Comment by jinhang** [comment]
> If you are seeing this exception it is not a bug. This means that the worker is under too much load. You need to increase the number of threads available to the worker, or the number of workers available to serve requests

then.how can I increase the number of threads available to the worker ?

**Comment by jinhang** [comment]
@ZacBlanco

**Comment by ZacBlanco** [comment]
You can increase the number of available threads by setting `alluxio.worker.network.block.reader.threads.max` for reads and `alluxio.worker.network.block.writer.threads.max` for writes
