### ISSUE TITLE
alluxio-fuse pod status is CrashLoopBackOff

### ISSUE THREAD

**Issue by happy2048** [Alluxio/alluxio#11544]
**Alluxio Version:**
2.3.0-SNAPSHOT
chart verision: 0.6.1

**Describe the bug**
alluxio-fuse pod are CrashLoopBackOff，the log is:

```
umount: /mnt/alluxio-fuse: not mounted
Starting alluxio-fuse on local host.
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_CLIENT_HOSTNAME
	at alluxio.conf.InstancedConfiguration.lookupRecursively(InstancedConfiguration.java:457)
	at alluxio.conf.InstancedConfiguration.lookup(InstancedConfiguration.java:430)
	at alluxio.conf.InstancedConfiguration.isResolvable(InstancedConfiguration.java:168)
	at alluxio.conf.InstancedConfiguration.isSet(InstancedConfiguration.java:177)
	at alluxio.util.network.NetworkAddressUtils.getLocalNodeName(NetworkAddressUtils.java:387)
	at alluxio.network.TieredIdentityFactory.create(TieredIdentityFactory.java:98)
	at alluxio.network.TieredIdentityFactory.localIdentity(TieredIdentityFactory.java:62)
	at alluxio.client.block.AlluxioBlockStore.create(AlluxioBlockStore.java:77)
	at alluxio.client.file.BaseFileSystem.<init>(BaseFileSystem.java:106)
	at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:144)
	at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:117)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:63)
```

**To Reproduce**

The following steps show how to reproduce the bug:

(1) set "fuse.enabled" to be "true" in integration/kubernetes/helm-chart/alluxio/values.yaml.

(2) use helm to deploy:
```
# helm install alluxio integration/kubernetes/helm-chart/alluxio
```
(3) use kubectl to check the statuses of alluxio-fuse pods:
```
# kubectl get po
NAME                                            READY   STATUS      RESTARTS   AGE
alluxio-fuse-4ml8f                              1/1     CrashLoopBackOff     1          46m
alluxio-fuse-hcp9d                              1/1     CrashLoopBackOff     1          46m
alluxio-fuse-p47zw                              1/1     CrashLoopBackOff     1          46m
alluxio-master-0                                2/2     Running     0          52m
alluxio-worker-2j22l                            2/2     Running     0          52m
alluxio-worker-5x6jz                            2/2     Running     0          52m
alluxio-worker-72tkq                            2/2     Running     0          52m
```
as you see,the statuses of alluxio-fuse pods are failed.

(4) chose one alluxio-fuse pod and check its' log:
```
# kubectl logs alluxio-fuse-4ml8f   

umount: /mnt/alluxio-fuse: not mounted
Starting alluxio-fuse on local host.
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_CLIENT_HOSTNAME
	at alluxio.conf.InstancedConfiguration.lookupRecursively(InstancedConfiguration.java:457)
	at alluxio.conf.InstancedConfiguration.lookup(InstancedConfiguration.java:430)
	at alluxio.conf.InstancedConfiguration.isResolvable(InstancedConfiguration.java:168)
	at alluxio.conf.InstancedConfiguration.isSet(InstancedConfiguration.java:177)
	at alluxio.util.network.NetworkAddressUtils.getLocalNodeName(NetworkAddressUtils.java:387)
	at alluxio.network.TieredIdentityFactory.create(TieredIdentityFactory.java:98)
	at alluxio.network.TieredIdentityFactory.localIdentity(TieredIdentityFactory.java:62)
	at alluxio.client.block.AlluxioBlockStore.create(AlluxioBlockStore.java:77)
	at alluxio.client.file.BaseFileSystem.<init>(BaseFileSystem.java:106)
	at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:144)
	at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:117)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:63)
```

(5)  use  'kubectl edit' command to edit the pod startup command to "tail -f /dev/null":

```
# kubectl edit daemonset alluxio-fuse
```
waiting the alluxio-fuse pods to be running.

```
#  kubectl get po
NAME                                            READY   STATUS      RESTARTS   AGE
alluxio-fuse-pl1ax                              1/1     Running     0          57m
alluxio-fuse-w6x9b                              1/1     Running     0          57m
alluxio-fuse-odce4                              1/1     Running     0          57m
alluxio-master-0                                2/2     Running     0          63m
alluxio-worker-2j22l                            2/2     Running     0          63m
alluxio-worker-5x6jz                            2/2     Running     0          63m
alluxio-worker-72tkq                            2/2     Running     0          63m
```
(6) use 'kubectl exec' to enter the pod:
```
# kubectl exec -ti alluxio-fuse-pl1ax bash

```
execute following command in container(alluxio-fuse-pl1ax):

```
#  export ALLUXIO_JAVA_OPTS="$ALLUXIO_JAVA_OPTS  -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME}"

# /entrypoint.sh fuse --fuse-opts=allow_other

umount: /mnt/alluxio-fuse: not mounted
Starting alluxio-fuse on local host.
2020-06-10 12:52:08,180 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.8.15, rack=null)
```
and it is working, why?

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
@ssz1997  is this still valid? otherwise help me close this please

**Comment by ssz1997** [comment]
I believe it's fixed in a later version. Please try using the newest version.
