### ISSUE TITLE
Expected magic number at tail

### ISSUE THREAD

**Issue by amitrohra** [Alluxio/alluxio#11571]
Recently we are facing frequent issue with Alluxio, getting following error for many of the parquet files, I need to unload it from Alluxio then it works fine.

Following is the trace.

**2020-06-16 17:52:40 ERROR Executor:94 - Exception in task 16.0 in stage 6228.0 (TID 426959)
java.lang.RuntimeException: alluxio://hostname:19998/prag_map/3KABBGXB__FCT_DIM_EXTRACT.parquet/TIME_KEY=20200609/part-00008-8bb719b8-5b35-4f3a-830e-e48f97618482.c000.snappy.parquet is not a Parquet file. expected magic number at tail [80, 65, 82, 49] but found [57, 56, 53, 50]**
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:484)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:457)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:413)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.footerFileMetaData$lzycompute$1(ParquetFileFormat.scala:371)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.footerFileMetaData$1(ParquetFileFormat.scala:370)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.apply(ParquetFileFormat.scala:374)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.apply(ParquetFileFormat.scala:352)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:126)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:179)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:103)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.scan_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:624)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-06-16 17:52:40 INFO  FileScanRDD:57 - Reading File path: alluxio://hostname:19998/prag_map/3KABBGXB__FCT_DIM_EXTRACT.parquet/TIME_KEY=20200504/part-00013-03a77580-24ee-43a1-b385-58af71dea6d0.c000.snappy.parquet, range: 0-718359, partition values: [20200504]
2020-06-16 17:52:40 INFO  FileScanRDD:57 - Reading File path: alluxio://hostname:19998/prag_map/3KABBGXB__FCT_DIM_EXTRACT.parquet/TIME_KEY=20200527/part-00014-e1cfc067-7707-46b3-9ec0-16cdc4b3d25e.c000.snappy.parquet, range: 0-837264, partition values: [20200527]
2020-06-16 17:52:40 INFO  FileScanRDD:57 - Reading File path: alluxio://hostname:19998/prag_map/3KABBGXB__FCT_DIM_EXTRACT.parquet/TIME_KEY=20200523/part-00010-682036ed-f092-4f16-8a00-291c7bcf9fc2.c000.snappy.parquet, range: 0-793443, partition values: [20200523]
2020-06-16 17:52:40 INFO  FileScanRDD:57 - Reading File path: alluxio://hostname:19998/prag_map/3KABBGXB__FCT_DIM_EXTRACT.parquet/TIME_KEY=20200515/part-00015-f9533d33-28f2-4758-b62e-76752ba01b94.c000.snappy.parquet, range: 0-700732, partition values: [20200515]
2020-06-16 17:52:40 INFO  CoarseGrainedExecutorBackend:57 - Got assigned task 427117
2020-06-16 17:52:40 INFO  Executor:57 - Running task 60.2 in stage 6228.0 (TID 427117)
2020-06-16 17:52:40 INFO  FileScanRDD:57 - Reading File path: alluxio://hostname:19998/prag_map/3KABBGXB__FCT_DIM_EXTRACT.parquet/TIME_KEY=20200527/part-00011-e1cfc067-7707-46b3-9ec0-16cdc4b3d25e.c000.snappy.parquet, range: 0-831784, partition values: [20200527]
2020-06-16 17:52:40 INFO  FileScanRDD:57 - Reading File path: alluxio://hostname:19998/prag_map/3KABBGXB__FCT_DIM_EXTRACT.parquet/TIME_KEY=20200611/part-00006-d538b0a2-3f75-450f-8b44-a696badcaabd.c000.snappy.parquet, range: 0-843647, partition values: [20200611]
2020-06-16 17:52:40 ERROR Executor:94 - Exception in task 60.2 in stage 6228.0 (TID 427117)
java.io.IOException: can not read FileMetaData: Incorrect type in stream. Expected 10 but got 2
	at org.apache.parquet.format.Util.readFileMetaData(Util.java:195)
	at org.apache.parquet.format.Util.readFileMetaData(Util.java:85)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$3.visit(ParquetMetadataConverter.java:1101)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$3.visit(ParquetMetadataConverter.java:1093)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$SkipMetadataFilter.accept(ParquetMetadataConverter.java:986)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1093)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:492)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:457)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:413)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.footerFileMetaData$lzycompute$1(ParquetFileFormat.scala:371)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.footerFileMetaData$1(ParquetFileFormat.scala:370)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.apply(ParquetFileFormat.scala:374)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$buildReaderWithPartitionValues$1.apply(ParquetFileFormat.scala:352)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:126)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:179)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:103)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.scan_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:624)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: shaded.parquet.org.apache.thrift.TException: Incorrect type in stream. Expected 10 but got 2
	at org.apache.parquet.format.event.TypedConsumer.read(TypedConsumer.java:195)
	at org.apache.parquet.format.event.Consumers$DelegatingFieldConsumer.consumeField(Consumers.java:97)
	at org.apache.parquet.format.event.EventBasedThriftReader.readStructContent(EventBasedThriftReader.java:73)
	at org.apache.parquet.format.event.EventBasedThriftReader.readStruct(EventBasedThriftReader.java:57)
	at org.apache.parquet.format.Util.readFileMetaData(Util.java:192)
	... 31 more

**Comment by ZacBlanco** [comment]
This is likely due to an issue with your metadata sync interval configuration. Are the files used by the spark job being modified in the UFS after the initial job has started?

Usually with issues like this the file metadata is retrieved at some point by a parquet library, then read at a later point using the previous metadadata to guide how far to read. When these types of errors occur, usually its because the data in the file underneath changed while you are executing your job.

To alleviate this you can try the following:

1. All reads and writes should go through Alluxio. This means metadata is always up-to-date
2. Make sure the entire file is cached in Alluxio, and then configure the metadata sync interval to some reasonable value based on your application requirements.

**Comment by amitrohra** [comment]
@ZacBlanco agree to your justification, I have faced this quite often. I have job scheduled daily to load multiple parquet files through Alluxio & this error occur for random files against stored earlier (FYI: Parquets are partitioned).

Also I have tried checking consistency using **'fs checkConsistency'** command & it displays metadata is consistent between UFS & Alluxio, even I have tried to load it but gives same error until  I free it from Alluxio & reload it.

My Alluxio version is 1.6.0, & have tried `alluxio.user.file.metadata.load.type=ALWAYS`, but didn't worked well.

I have planned upgrade to recent version & is in progress, but till that is released for production I need alternative for Alluxio 1.6.0.

**Comment by ZacBlanco** [comment]
There have been many new features and bug fixes since 1.6.0. Many large architectural changes. It's possible there is a bug, but I don't know for sure. My next recommendation is to simply upgrade to 2.2.1 and then if you still experience the issue I can provide further assistance. The 1.6 branch  is almost 3 years old and no longer supported or maintained

**Comment by amitrohra** [comment]
@ZacBlanco Thanks for the support, issue is solved after upgrading Alluxio to 1.8.2.
