### ISSUE TITLE
alluxio-client press alluxio-fuse with thread-num=500 will suspend

### ISSUE THREAD

**Issue by gongbing851217** [Alluxio/alluxio#11681]
**Alluxio Version:**
2.2.1

**Describe the bug**
when i run a press client with threads_num=500 for reading 50w file (filesize=4k) for twice,  alluxio-fuse will block.

**Alluxio-user config**
alluxio.user.file.metadata.load.type=ONCE
alluxio.user.file.passive.cache.enabled=false
alluxio.user.file.readtype.default=CACHE
alluxio.fuse.cached.paths.max=500000
alluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
alluxio.user.block.avoid.eviction.policy.reserved.size.bytes=20GB
alluxio.user.metadata.cache.enabled=TRUE
alluxio.user.metadata.cache.max.size=5000000
alluxio.user.metadata.cache.expiration.time=2000min
alluxio.user.block.remote.read.buffer.size.bytes=8MB
alluxio.user.file.buffer.bytes=64MB
alluxio.user.network.max.inbound.message.size=64MB
alluxio.user.network.reader.buffer.size.messages=16
alluxio.user.block.master.client.pool.size.max=10240
alluxio.user.block.master.client.pool.size.min=0
alluxio.user.worker.list.refresh.interval=2000min
alluxio.user.file.master.client.pool.size.max=1024
alluxio.user.block.worker.client.pool.size=10240
alluxio.user.block.worker.client.pool.gc.threshold=300sec

**Alluxio-master and worker config**
alluxio.master.worker.timeout=10min
alluxio.master.worker.heartbeat.interval=30s
alluxio.master.worker.threads.max=102400
alluxio.master.worker.threads.min=25600
alluxio.master.journal.checkpoint.period.entries=10000000
alluxio.master.journal.folder=/data/alluxio-journal
alluxio.master.journal.log.size.bytes.max=100MB
alluxio.master.lock.pool.high.watermark=5000000
alluxio.master.lock.pool.low.watermark=5000000
alluxio.master.ufs.block.location.cache.capacity=5000000
alluxio.master.ufs.path.cache.capacity=5000000
alluxio.master.ufs.path.cache.threads=256
alluxio.master.ufs.active.sync.event.rate.interval=60000sec
alluxio.master.ufs.active.sync.interval=60000sec
alluxio.master.ufs.path.cache.capacity=500000
alluxio.master.journal.type=NOOP
alluxio.master.ufs.active.sync.poll.timeout=10000sec
alluxio.user.file.metadata.sync.interval=1000000000
alluxio.user.file.passive.cache.enabled=false
alluxio.worker.network.flowcontrol.window=128MB
alluxio.worker.network.keepalive.time=300sec
alluxio.worker.network.max.inbound.message.size=128MB
alluxio.worker.network.netty.worker.threads=1024
alluxio.worker.network.reader.buffer.size=64MB
alluxio.worker.network.reader.max.chunk.size.bytes=64MB
alluxio.worker.network.writer.buffer.size.messages=128
alluxio.worker.tieredstore.block.lock.readers=10000
alluxio.worker.block.master.client.pool.size=1024
alluxio.worker.network.netty.watermark.high=512KB
alluxio.worker.network.netty.watermark.low=256KB
alluxio.worker.network.netty.async.cache.manager.threads.max=512
alluxio.worker.session.timeout=20min
alluxio.worker.network.block.reader.threads.max=10240
alluxio.worker.ufs.instream.cache.max.size=500000
alluxio.worker.ufs.instream.cache.expiration.time=500min
alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.worker.tieredstore.level0.dirs.quota=120GB
alluxio.worker.tieredstore.level0.watermark.high.ratio=0.9
alluxio.worker.tieredstore.level0.watermark.low.ratio=0.7
alluxio.worker.tieredstore.level1.alias=SSD
alluxio.worker.tieredstore.level1.dirs.path=/data/alluxio-ssd
alluxio.worker.tieredstore.level1.dirs.quota=3TB
alluxio.worker.tieredstore.level1.watermark.high.ratio=0.9
alluxio.worker.tieredstore.level1.watermark.low.ratio=0.7

**Fuse.log**
2020-06-29 15:48:01,640 WARN  BaseFileSystem - Failed to submit a task to update access time for /data3/public_data/faceunlock/facerecogn/ms1m-retinaface-t1/train_data/0_5262970/16.jpg: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@718a92a1 rejected from java.util.concurrent.ThreadPoolExecutor@64507ea5[Running, pool size = 1024, active threads = 893, queued tasks = 0, completed tasks = 518010]
2020-06-29 15:48:01,640 WARN  BaseFileSystem - Failed to submit a task to update access time for /data3/public_data/faceunlock/facerecogn/ms1m-retinaface-t1/train_data/0_5262970/32.jpg: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7efacd6e rejected from java.util.concurrent.ThreadPoolExecutor@64507ea5[Running, pool size = 1024, active threads = 894, queued tasks = 0, completed tasks = 518010]
2020-06-29 15:48:01,640 WARN  BaseFileSystem - Failed to submit a task to update access time for /data3/public_data/faceunlock/facerecogn/ms1m-retinaface-t1/train_data/0_5262970/31.jpg: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@78f222b0 rejected from java.util.concurrent.ThreadPoolExecutor@64507ea5[Running, pool size = 1024, active threads = 894, queued tasks = 0, completed tasks = 518010]
2020-06-29 15:48:01,641 WARN  BaseFileSystem - Failed to submit a task to update access time for /data3/public_data/faceunlock/facerecogn/ms1m-retinaface-t1/train_data/0_5262970/49.jpg: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@13b6af79 rejected from java.util.concurrent.ThreadPoolExecutor@64507ea5[Running, pool size = 1024, active threads = 895, queued tasks = 0, completed tasks = 518010]
2020-06-29 15:48:01,641 WARN  BaseFileSystem - Failed to submit a task to update access time for /data3/public_data/faceunlock/facerecogn/ms1m-retinaface-t1/train_data/0_5262970/24.jpg: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7849e001 rejected from java.util.concurrent.ThreadPoolExecutor@64507ea5[Running, pool size = 1024, active threads = 895, queued tasks = 0, completed tasks = 518010]
2020-06-29 15:48:14,528 WARN  InstancedConfiguration - alluxio.user.network.reader.buffer.size.messages is deprecated. Please avoid using this key in the future. 

**jstack alluxio-fuse log**
`
"Thread-518025" #519334 daemon prio=5 os_prio=0 tid=0x00007f1b0c07a000 nid=0xb2aa waiting on condition [0x00007f19653fa000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007f201602ab20> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
        at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:341)
        at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:288)
        at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:520)
        at alluxio.client.file.FileSystemContext.acquireBlockWorkerClient(FileSystemContext.java:502)
        at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:83)
        at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:49)
        at alluxio.client.block.stream.GrpcDataReader$Factory.create(GrpcDataReader.java:203)
        at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:374)
        at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:260)
        at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:186)
        at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
        at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
        at ru.serce.jnrfuse.AbstractFuseFS$$Lambda$55/1782580546.read(Unknown Source)
        at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)

   Locked ownable synchronizers:
        - None

"Thread-518006" #519315 daemon prio=5 os_prio=0 tid=0x00007f1abc0bd000 nid=0xb27c waiting on condition [0x00007f196f40e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007f201602ab20> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
        at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:341)
        at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:288)
        at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:520)
        at alluxio.client.file.FileSystemContext.acquireBlockWorkerClient(FileSystemContext.java:502)
        at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:83)
        at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:49)
        at alluxio.client.block.stream.GrpcDataReader$Factory.create(GrpcDataReader.java:203)
        at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:374)
        at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:260)
        at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:186)
        at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:586)
        at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:134)
        at ru.serce.jnrfuse.AbstractFuseFS$$Lambda$55/1782580546.read(Unknown Source)
        at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)

   Locked ownable synchronizers:
        - None`

**Comment by apc999** [comment]
please try use latest Alluxio FUSE (backed by JNIFuse) after 2.6.1
