### ISSUE TITLE
Can't duplicate copy by alluxio-fuse

### ISSUE THREAD

**Issue by qzwlinux** [Alluxio/alluxio#11694]
**Alluxio Version:**
alluxio-2.2.2

**Describe the bug**
When i want to copy file again,it tell me Operation not support

```
[~]$ time cp test /home/nfs/storage/manage/qizewen/

real	0m8.379s
user	0m0.036s
sys	0m2.156s

[~]$ time cp test /home/nfs/storage/manage/qizewen/
cp: cannot create regular file '/home/nfs/storage/manage/qizewen/test': Operation not supported

real	0m0.071s
user	0m0.000s
sys	0m0.000s
```

alluxio-site.properties
```
#################################################
#              Common properties                #
#################################################
alluxio.home=/opt/alluxio-2.2.2
alluxio.master.hostname=storage
alluxio.master.mount.table.root.ufs=/data/hdd
alluxio.conf.dir=${alluxio.home}/conf
alluxio.logs.dir=${alluxio.work.dir}/logs

#################################################
#             Security properties               #
#################################################
# alluxio.security.authorization.permission.enabled=true
# alluxio.security.authentication.type=SIMPLE



#################################################
#             Master properties                 #
#################################################
alluxio.master.memory.size=90GB
alluxio.master.tieredstore.levels=2

alluxio.master.tieredstore.level0.alias=MEM
alluxio.master.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.master.tieredstore.level0.dirs.quota=90G
alluxio.master.tieredstore.level0.dirs.mediumtype=MEM
alluxio.master.tieredstore.level0.watermark.high.ratio=0.9
alluxio.master.tieredstore.level0.watermark.low.ratio=0.7

alluxio.master.tieredstore.level1.alias=SSD
alluxio.master.tieredstore.level1.dirs.path=/data/ssd1,/data/ssd2,/data/ssd3,/data/ssd4
alluxio.master.tieredstore.level1.dirs.quota=890G
alluxio.master.tieredstore.level0.dirs.mediumtype=SSD,SSD,SSD,SSD
alluxio.master.tieredstore.level1.watermark.high.ratio=0.9
alluxio.master.tieredstore.level1.watermark.low.ratio=0.7

alluxio.master.journal.type=EMBEDDED
alluxio.master.journal.folder=${alluxio.home}/journal
alluxio.master.metastore=ROCKS


#################################################
#             Worker properties                 #
#################################################
alluxio.worker.memory.size=90GB

alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.reserver.enable=true

alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.worker.tieredstore.level0.dirs.quota=90G
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
alluxio.worker.tieredstore.level0.watermark.high.ratio=0.9
alluxio.worker.tieredstore.level0.watermark.low.ratio=0.7

alluxio.worker.tieredstore.level1.alias=SSD
alluxio.worker.tieredstore.level1.dirs.path=/data/ssd1,/data/ssd2,/data/ssd3,/data/ssd4
alluxio.worker.tieredstore.level1.dirs.quota=890G
alluxio.worker.tieredstore.level0.dirs.mediumtype=SSD,SSD,SSD,SSD
alluxio.worker.tieredstore.level1.watermark.high.ratio=0.9
alluxio.worker.tieredstore.level1.watermark.low.ratio=0.7


#################################################
#             User properties                   #
#################################################
alluxio.user.file.readtype.default=CACHE
alluxio.user.file.writetype.default=ASYNC_THROUGH
alluxio.user.file.replication.durable=1
alluxio.user.metadata.cache.enable=true
alluxio.user.file.metadata.sync.interval=0
alluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.LocalFirstAvoidEvictionPolicy
alluxio.user.block.avoid.eviction.policy.reserved.size.bytes=10G
alluxio.user.file.passive.cache.enabled=false

```

fuse.log
```
2020-06-30 01:54:56,665 ERROR ConfigHashSync - Failed to heartbeat to meta master to get configuration hash:
alluxio.exception.status.UnavailableException: Failed to connect to MetaMaster @ storage:19998 after 44 attempts
        at alluxio.AbstractClient.connect(AbstractClient.java:272)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:383)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:347)
        at alluxio.client.meta.RetryHandlingMetaMasterConfigClient.getConfigHash(RetryHandlingMetaMasterConfigClient.java:82)
        at alluxio.client.file.ConfigHashSync.heartbeat(ConfigHashSync.java:82)
        at alluxio.client.file.FileSystemContextReinitializer.lambda$new$0(FileSystemContextReinitializer.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: alluxio.exception.status.UnavailableException: Target Unavailable. GrpcChannelKey{ClientType=MetaMaster, ClientHostname=storage, ServerAddress=GrpcServerAddress{HostName=storage, SocketAddress=storage:19998}, ChannelId=72872878-e1be-43b4-ae75-5d0ef676ee7f}
        at alluxio.grpc.GrpcChannelBuilder.build(GrpcChannelBuilder.java:144)
        at alluxio.AbstractClient.connect(AbstractClient.java:225)
        ... 12 more
Caused by: alluxio.exception.status.UnavailableException: io exception
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:155)
        at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:214)
        at alluxio.exception.status.AlluxioStatusException.fromThrowable(AlluxioStatusException.java:199)
        at alluxio.security.authentication.AuthenticatedChannelClientDriver.waitUntilChannelAuthenticated(AuthenticatedChannelClientDriver.java:187)
        at alluxio.security.authentication.AuthenticatedChannelClientDriver.startAuthenticatedChannel(AuthenticatedChannelClientDriver.java:164)
        at alluxio.security.authentication.ChannelAuthenticator.authenticate(ChannelAuthenticator.java:103)
        at alluxio.grpc.GrpcChannelBuilder.build(GrpcChannelBuilder.java:129)
        ... 13 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        ... 3 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: storage/10.0.80.254:19998
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:660)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:637)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:524)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:473)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)


```

**Comment by apc999** [comment]
@qzwlinux thanks for reporting this issue. I remember we discussed this offline.
I tested on my local desktop filesystem (APFS) and cp overwrite indeed is the default behavior
https://www.computerhope.com/unix/ucp.htm

I will later create a PR to fix this issue.
