### ISSUE TITLE
alluxio worker OOM

### ISSUE THREAD

**Issue by trionesadam** [Alluxio/alluxio#11761]
**Alluxio Version:**
alluxio 2.2.0

**Describe the bug**
we saw too kind of issues as  below:
1)
020-06-15 17:46:14,052 WARN  AbstractReadHandler - Exception occurred while processing read request null: CANCELLED: cancelled before receiving half close
2020-06-15 17:47:41,309 ERROR AbstractReadHandler - Failed to run DataReader.
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 4292870423, max: 4294967296)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:725)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:680)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:342)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:123)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:108)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:70)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:325)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:293)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-06-15 17:47:41,377 ERROR AbstractReadHandler - Failed to run DataReader.

2)
2020-07-03 12:12:29,417 WARN  UnderFileSystemBlockStore - Key (block ID: 1323504238592, session ID 998409497566676670) is not found when releasing the UFS block.
2020-07-03 12:12:35,436 ERROR AbstractReadHandler - Failed to run DataReader.
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at io.netty.util.internal.PlatformDependent.newFixedMpscQueue(PlatformDependent.java:940)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.<init>(PoolThreadCache.java:377)
        at io.netty.buffer.PoolThreadCache$SubPageMemoryRegionCache.<init>(PoolThreadCache.java:344)
        at io.netty.buffer.PoolThreadCache.createSubPageCaches(PoolThreadCache.java:128)
        at io.netty.buffer.PoolThreadCache.<init>(PoolThreadCache.java:75)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:460)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:444)
        at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177)
        at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:337)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:123)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:108)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:70)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:325)
        at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:293)
        at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor$$Lambda$87/805655736.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-07-03 12:12:55,815 WARN  ClientCnxn - Client session timed out, have not heard from server in 30180ms for sessionid 0x10047ac5950fe49
2020-07-03 12:12:55,815 WARN  AbstractReadHandler - Exception occurred while sending data for read request BlockReadRequest{chunkSize=1048576, end=196216481, id=1323504238592, openUfsBlockOp:

after client session time out , master remove the worker. but the worker process also existed. when we read  the table on the alluxio data are less than expected.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by ggezer** [comment]
The worker seems to be under severe memory pressure.
Could you try below steps in order:
- Increase the java heap size
- Increase the java max direct memory allocation
- Reduce `alluxio.worker.network.reader.buffer.size` to 2MB
- Collect GC logs for the worker java process (if nothing works)

**Comment by apc999** [comment]
@ggezer  do you know if 2.3.0 has this issue improved compared to 2.2.0 (he is running), based on your work?

**Comment by ggezer** [comment]
@apc999 2.3 would have improvements only at peak capacity, meaning when the worker storage is full.

**Comment by apc999** [comment]
Possibly fixed by https://github.com/Alluxio/alluxio/pull/13172
Please upgrade to 2.5.0-2 (releasing soon) and let's know if this happens again.
