### ISSUE TITLE
JNIFuse doesn't handle the file not exist correctly

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#11952]
**Alluxio Version:**
/opt/alluxio/bin/alluxio version -r
2.3.1-SNAPSHOT-bbce37af9776842668419f53cd81182fd59aa1b4

**Describe the bug**
Access a directory or file which doesn't exist

```
[root@iZuf68sywkiky95veylv1yZ alluxio-fuse]# docker exec -it 4b bash
root@iZuf68sywkiky95veylv1yZ:/libfuse# /opt/alluxio/bin/alluxio version -r
2.3.1-SNAPSHOT-bbce37af9776842668419f53cd81182fd59aa1b4
root@iZuf68sywkiky95veylv1yZ:/libfuse# exit
exit
[root@iZuf68sywkiky95veylv1yZ alluxio-fuse]# mount |grep alluxio
alluxio-fuse on /alluxio-mnt/default/imagenet/alluxio-fuse type fuse.alluxio-fuse (ro,nosuid,nodev,relatime,user_id=0,group_id=0,max_read=131072)
[root@iZuf68sywkiky95veylv1yZ alluxio-fuse]# cd /alluxio-mnt/default/imagenet/alluxio-fuse
[root@iZuf68sywkiky95veylv1yZ alluxio-fuse]# ls
imagenet
[root@iZuf68sywkiky95veylv1yZ alluxio-fuse]# cd imagenet
[root@iZuf68sywkiky95veylv1yZ imagenet]# cd ..
[root@iZuf68sywkiky95veylv1yZ alluxio-fuse]# cd train
-bash: cd: train: 输入/输出错误
```

And the in fuse log

```
2020-08-09 08:48:43,350 ERROR AlluxioJniFuseFileSystem - Failed to getattr /train:
alluxio.exception.FileDoesNotExistException: Path "/train" does not exist.
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:521)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:258)
	at alluxio.client.file.MetadataCachingBaseFileSystem.getStatus(MetadataCachingBaseFileSystem.java:78)
	at alluxio.client.file.FileSystem.getStatus(FileSystem.java:324)
	at alluxio.fuse.AlluxioJniFuseFileSystem.getattrInternal(AlluxioJniFuseFileSystem.java:211)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$getattr$1(AlluxioJniFuseFileSystem.java:205)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
	at alluxio.fuse.AlluxioJniFuseFileSystem.getattr(AlluxioJniFuseFileSystem.java:204)
	at alluxio.jnifuse.AbstractFuseFileSystem.getattrCallback(AbstractFuseFileSystem.java:159)
2020-08-09 08:48:43,353 ERROR AlluxioJniFuseFileSystem - Failed to getattr /train:
alluxio.exception.FileDoesNotExistException: Path "/train" does not exist.
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:521)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:258)
	at alluxio.client.file.MetadataCachingBaseFileSystem.getStatus(MetadataCachingBaseFileSystem.java:78)
	at alluxio.client.file.FileSystem.getStatus(FileSystem.java:324)
	at alluxio.fuse.AlluxioJniFuseFileSystem.getattrInternal(AlluxioJniFuseFileSystem.java:211)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$getattr$1(AlluxioJniFuseFileSystem.java:205)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
	at alluxio.fuse.AlluxioJniFuseFileSystem.getattr(AlluxioJniFuseFileSystem.java:204)
	at alluxio.jnifuse.AbstractFuseFileSystem.getattrCallback(AbstractFuseFileSystem.java:159)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
Fixed by f34d97ca10634eae587a73bd2f4528cd1efc65a0
