### ISSUE TITLE
fuse pod hang forever after open&read many files without close the files

### ISSUE THREAD

**Issue by chaowangnk1** [Alluxio/alluxio#12136]
**Alluxio Version:**
latest build on master branch

**Describe the bug**
With alluxio deployed on k8s, fuse pod hang forever after open&read many files without close the files. The file operations are from separated ML training job run pods, on alluxio mounted path.
After checking stack traces of java process in fuse pod, I observed thread hang at:
```
"Thread-5" #31 daemon prio=5 os_prio=0 tid=0x00007f29d0001000 nid=0xab9c waiting on condition [0x00007f2a09a99000]
   java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x000000072be23138> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:352)
at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:295)
at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:541)
at alluxio.client.file.FileSystemContext.acquireBlockWorkerClient(FileSystemContext.java:521)
at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:83)
at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:49)
at alluxio.client.block.stream.GrpcDataReader$Factory.create(GrpcDataReader.java:203)
at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:396)
at alluxio.client.block.stream.BlockInStream.readInternal(BlockInStream.java:274)
at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:264)
at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:188)
at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:336)
at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$4(AlluxioJniFuseFileSystem.java:305)
at alluxio.fuse.AlluxioJniFuseFileSystem$$Lambda$83/1203318693.call(Unknown Source)
at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:305)
at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:150)
```

**To Reproduce**
  - Deploy alluxio to a k8s
  - start another pod to open&read files, util the script hang. 
  - fuse pod hang and any following file ops will be blocked.
attached is the py script for file operations.
[walk.txt](https://github.com/Alluxio/alluxio/files/5272056/walk.txt)

**Expected behavior**
The script will fail once hit OS file open limit. And fuse pod should not hang.

**Urgency**
This bug is blocking all imagenet training jobs.

**Additional context**

**Comment by apc999** [comment]
Fixed by #12136
