### ISSUE TITLE
fuse pod hang forever after trying to write a big file (> 64 GiB, with block size = 64MiB)

### ISSUE THREAD

**Issue by chaowangnk1** [Alluxio/alluxio#12137]
**Alluxio Version:**
branch-2.3-fuse

**Describe the bug**
With alluxio deployed on k8s, fuse pod hang forever after trying to write a big file. And all following file operations on the same node will be blocked.

In fuse pod, I observed threads hang at 
```
   java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x000000072be23138> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:352)
at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:295)
at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:541)
at alluxio.client.file.FileSystemContext.acquireBlockWorkerClient(FileSystemContext.java:521)
```

**To Reproduce**
  - Deploy alluxio to k8s, with fuse pods deployed, set block size to 64MiB
  - start a new pod, create a file and write >64 GiB contents to the file, until write operation hangs.

**Expected behavior**
File write can be done successfully.

**Urgency**
This bug is blocking our non-critical perf testing.

**Additional context**

**Comment by ZacBlanco** [comment]
Likely related to the following issue: https://github.com/Alluxio/alluxio/issues/11521

**Comment by apc999** [comment]
Indeed, @ZacBlanco @chaowangnk1 , currently we have by default 1024 blockWorkerClient. When writing more than 64GB with 64MB blocks, it takes 1024 clients. So it will hang as no more block worker clients can be acquired. As a workaround, @chaowangnk1 , you can increase `alluxio.user.block.worker.client.pool.max` property to a value larger.

On our side, at least `acquireBlockWorkerClient` should provide tryLock mode to return false rather than hanging there. @madanadit @calvinjia
