### ISSUE TITLE
Local Alluxio (Short-circuit) Read Metrics not getting captured

### ISSUE THREAD

**Issue by jainanuj07** [Alluxio/alluxio#12229]
**Alluxio Version:**
alluxio-2.4.0-Snapshot

**Describe the bug**
I am unable to see Local Alluxio (Short-circuit) Read Metrics . It is always coming as 0. As per documents i have enabled "alluxio.user.metrics.collection.enabled=true" this setting but after i enabled this setting i am seeing below error in logs :

logs/job_master.log:2020-10-10 10:44:40,520 ERROR metrics.ClientMasterSync (SamplingLogger.java:error) - Failed to get master address during initialization: alluxio.exception.status.UnavailableException: Failed to handshake with master *.*.*.*:19998 to load cluster default configuration values: UNAVAILABLE: io exception

logs/proxy.log:2020-10-08 18:28:54,870 ERROR ClientMasterSync - Failed to get master address during initialization: alluxio.exception.status.UnavailableException: Failed to handshake with master *.*.*.*:19998 to load cluster default configuration values: UNAVAILABLE: Network closed for unknown reason
logs/proxy.log:	at alluxio.client.metrics.ClientMasterSync.loadConf(ClientMasterSync.java:123)
logs/proxy.log:	at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:75)

**To Reproduce**
1. Enable the "alluxio.user.metrics.collection.enabled=true" in alluxio-site.properties.
2. Restart the master. 

**Expected behavior**
As per documents : 
In order to retrieve metrics for short circuit IO, the client metrics collection need to be enabled by setting alluxio.user.metrics.collection.enabled=true in alluxio-site.properties or corresponding application configuration.

After enabling this i should get short circuit metrics on UI.

**Urgency**
Its impacting to analyze the impact of alluxio and we do not able to see how much % of local read we are hitting. 

**Additional context**
Most of the time this problem is happening but sometime randomly i am able to see Short-circuit metrics. So if i restart multiple times my master randomly 1 or 2 times it works.

**Comment by apc999** [comment]
@jainanuj07  your log `Failed to get master address during initialization: alluxio.exception.status.UnavailableException: Failed to handshake with master ...:19998 to load cluster default configuration values: UNAVAILABLE: io exception` shows your jobmaster and proxy server were not able to connect to master. Are you able to 
(1) check your webui and verify your master server is running?
(2) check if your proxy and job master are using the correct master address?

**Comment by jainanuj07** [comment]
WebUI is working fine. Everything is working fine except that I am not able to track short-circuit metrics. As I mentioned sometime randomly it works so not sure what is the issue.

**Comment by apc999** [comment]
> 1 Enable the "alluxio.user.metrics.collection.enabled=true" in alluxio-site.properties.
> 2 Restart the master.

You will also need to restart all your existing applications (which has Alluxio client jar inside). This is because `alluxio.user.metrics.collection.enabled=true` is in fact a client side property telling the client jar to report the metrics to master. Only restarting the master may not be sufficient to let client pick up the latest configuration.

**Comment by jainanuj07** [comment]
1. enabled alluxio.user.metrics.collection.enabled=true
2. Restart all services of Alluxio.
3. restart presto server. 

Still, Local Alluxio (Short-circuit) Read=0. How can I make sure that my short-circuit read is not happening or its reporting issue?

**Comment by LuQQiu** [comment]
@jainanuj07 job_master and proxy will also launch Alluxio clients to connect to Alluxio master. They are just different in the way that they are long-running Alluxio clients instead of short Alluxio client used by Alluxio CLI or compute frameworks. If they are not able to do clientMasterSync with Alluxio master, other short clients are probably not able to sync with Alluxio master and not able to report metrics to the Alluxio master. Can you share the user log and see if any exception in there?

Other useful information that may help us understand and reproduce the issue includes:
1) How many masters inside the cluster?
2) What workflow did you run to trigger the short-circuit read metrics recording?
3) Did you see this issue in older Alluxio?

Also it will be helpful to double-check if the other nodes (including the nodes running the Alluxio clients) are known of the master hostname and are able to connect to the master node

**Comment by jainanuj07** [comment]
**In user Logs i do not see any Error :**

2020-10-15 03:50:03,992 DEBUG MetricsHeartbeatContext - Registered metrics heartbeat with appId: app-3540947044826381834
2020-10-15 03:50:04,239 DEBUG FileSystem$Factory - alluxio.master.cluster.metrics.update.interval=1min (DEFAULT)
2020-10-15 03:50:04,243 DEBUG FileSystem$Factory - alluxio.master.metrics.service.threads=5 (DEFAULT)
2020-10-15 03:50:04,243 DEBUG FileSystem$Factory - alluxio.master.metrics.time.series.interval=5min (DEFAULT)
2020-10-15 03:50:04,246 DEBUG FileSystem$Factory - alluxio.metrics.conf.file=/home/ubuntu/alluxio-master/alluxio/conf/metrics.properties (DEFAULT)
2020-10-15 03:50:04,246 DEBUG FileSystem$Factory - alluxio.metrics.context.shutdown.timeout=1sec (DEFAULT)
2020-10-15 03:50:04,252 DEBUG FileSystem$Factory - alluxio.user.metrics.collection.enabled=true (SITE_PROPERTY (/home/ubuntu/alluxio-master/alluxio/conf/alluxio-site.properties))
2020-10-15 03:50:04,252 DEBUG FileSystem$Factory - alluxio.user.metrics.heartbeat.interval=10sec (DEFAULT)
2020-10-15 03:50:04,303 DEBUG MetricsHeartbeatContext - Registered metrics heartbeat with appId: app-3540947044826381834
2020-10-15 03:50:04,852 DEBUG ConfigurationUtils - Loading property: alluxio.metrics.conf.file (ALL) -> ${alluxio.conf.dir}/metrics.properties
2020-10-15 03:50:04,853 DEBUG ConfigurationUtils - Loading property: alluxio.user.metrics.heartbeat.interval (CLIENT) -> 10sec
2020-10-15 03:50:04,853 DEBUG ConfigurationUtils - Loading property: alluxio.metrics.context.shutdown.timeout (ALL) -> 1sec
2020-10-15 03:50:04,853 DEBUG ConfigurationUtils - Loading property: alluxio.user.metrics.collection.enabled (CLIENT) -> true
2020-10-15 03:50:05,050 DEBUG MetricsHeartbeatContext - De-registered metrics heartbeat with appId: app-3540947044826381834
2020-10-15 03:50:05,117 DEBUG ConfigurationUtils - Loading property: alluxio.metrics.conf.file (ALL) -> ${alluxio.conf.dir}/metrics.properties
2020-10-15 03:50:05,117 DEBUG ConfigurationUtils - Loading property: alluxio.user.metrics.heartbeat.interval (CLIENT) -> 10sec
2020-10-15 03:50:05,117 DEBUG ConfigurationUtils - Loading property: alluxio.metrics.context.shutdown.timeout (ALL) -> 1sec
2020-10-15 03:50:05,117 DEBUG ConfigurationUtils - Loading property: alluxio.user.metrics.collection.enabled (CLIENT) -> true
2020-10-15 03:50:05,126 DEBUG MetricsSystem - Get the client metrics list to report to leading master in 4ms
2020-10-15 03:50:05,126 DEBUG MetricsHeartbeatContext - De-registered metrics heartbeat with appId: app-3540947044826381834
2020-10-15 03:50:05,840 INFO  MetricsHeartbeatContext - Created metrics heartbeat with ID app-1405232900524325950. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
2020-10-15 03:50:05,843 DEBUG MetricsHeartbeatContext - Registered metrics heartbeat with appId: app-1405232900524325950
2020-10-15 03:50:06,086 DEBUG FileSystem$Factory - alluxio.master.cluster.metrics.update.interval=1min (DEFAULT)
2020-10-15 03:50:06,090 DEBUG FileSystem$Factory - alluxio.master.metrics.service.threads=5 (DEFAULT)
2020-10-15 03:50:06,090 DEBUG FileSystem$Factory - alluxio.master.metrics.time.series.interval=5min (DEFAULT)
2020-10-15 03:50:06,093 DEBUG FileSystem$Factory - alluxio.metrics.conf.file=/home/ubuntu/alluxio-master/alluxio/conf/metrics.properties (DEFAULT)
2020-10-15 03:50:06,093 DEBUG FileSystem$Factory - alluxio.metrics.context.shutdown.timeout=1sec (DEFAULT)
2020-10-15 03:50:06,101 DEBUG FileSystem$Factory - alluxio.user.metrics.collection.enabled=true (SITE_PROPERTY (/home/ubuntu/alluxio-master/alluxio/conf/alluxio-site.properties))
2020-10-15 03:50:06,101 DEBUG FileSystem$Factory - alluxio.user.metrics.heartbeat.interval=10sec (DEFAULT)
2020-10-15 03:50:06,148 DEBUG MetricsHeartbeatContext - Registered metrics heartbeat with appId: app-1405232900524325950


1. I am running a single master. Proxy and job_master running on the same machine as alluxio master. 
2. I am running alluxio with 1 master 2 workers and on the same machines, my presto setup is the. So I enabled "alluxio.user.metrics.collection.enabled=true" in alluxio-site.properties. Restart all alluxio services and then restarted presto. 
3. Yes issue persists in 2.3 also.

**Comment by jainanuj07** [comment]
@LuQQiu  anything you have figuredd out

**Comment by LuQQiu** [comment]
have you tried put the alluxio.user.metrics.collection.enabled=true in the core-site.xml that presto catalog points to?

**Comment by jainanuj07** [comment]
i am using alluxio catalog so is it needed and where i have to put this property.

**Comment by LuQQiu** [comment]
@bradyoo Do you know where alluxio client configuration should be put when using alluxio catalog?

**Comment by bradyoo** [comment]
I do not. Nor know for sure that it works (at least based on this issue)

**Comment by yuzhu** [comment]
@jainanuj07 Alluxio catalog service simply returns an alluxio URI.  We still need to enable `alluxio.user.metrics.collection.enabled=true` for presto. Please follow instructions here https://docs.alluxio.io/os/user/stable/en/compute/Presto.html#customize-alluxio-user-properties . I would recommend the first approach by editing `jvm.config`

**Comment by jainanuj07** [comment]
@yuzhu This I have already enabled in my jvm.config of presto 

-Xbootclasspath/a:/home/ubuntu/alluxio-master/alluxio/conf/alluxio-site.properties

**Comment by yuzhu** [comment]
Did you restart presto processes after you edit alluxio configuration?

**Comment by jainanuj07** [comment]
Yup i have started presto all nodes after this.

**Comment by yuzhu** [comment]
just to double check, did you make this change `-Xbootclasspath/a:/home/ubuntu/alluxio-master/alluxio/conf/alluxio-site.properties` on all of your presto nodes?

**Comment by weimy2018** [comment]
Does this issues fix ? I met it again with alluxio-2.6.1 version.

**Comment by jja725** [comment]
I are reconsidering short-circuit read since it complicates the logic a lot.
Will close it for now, feel free to reopen it and contact us if this is a strong request.

**Comment by arcyda** [comment]
> Does this issues fix ? I met it again with alluxio-2.6.1 version.

I also met this issue with alluxio-2.6.1. Have you got any solutions?
