### ISSUE TITLE
MinIO runTest failed but successfully persist data in MinIO

### ISSUE THREAD

**Issue by HelloHorizon** [Alluxio/alluxio#12334]
**Alluxio Version:**
2.4.0

**Describe the bug**
Failed to pass all tests in `runTests` with MinIO as UFS.

for MinIO, I set the configurations as follows:

```
alluxio.master.mount.table.root.ufs=s3://doc/test
alluxio.underfs.s3.endpoint=http://localhost:9000/
alluxio.underfs.s3.disable.dns.buckets=true
alluxio.underfs.s3.inherit.acl=false
aws.accessKeyId=minioadmin
aws.secretKey=minioadmin
```

Then I tried to run `alluxio runTests` , I got the error message as follows:

```
runTest BASIC_NON_BYTE_BUFFER NO_CACHE THROUGH
2020-10-16 12:43:01,135 ERROR RunTestUtils - Exception running test: alluxio.cli.BasicNonByteBufferOperations@d278d2b
alluxio.exception.AlluxioException: Cannot create or load UFS directory s3://doc/test/default_tests_files: java.io.FileNotFoundException: s3://doc/test/default_tests_files.
	at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:104)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:534)
	at alluxio.client.file.BaseFileSystem.createFile(BaseFileSystem.java:148)
	at alluxio.cli.BasicNonByteBufferOperations.createFile(BasicNonByteBufferOperations.java:102)
	at alluxio.cli.BasicNonByteBufferOperations.write(BasicNonByteBufferOperations.java:85)
	at alluxio.cli.BasicNonByteBufferOperations.call(BasicNonByteBufferOperations.java:80)
	at alluxio.cli.BasicNonByteBufferOperations.call(BasicNonByteBufferOperations.java:49)
	at alluxio.cli.RunTestUtils.runExample(RunTestUtils.java:62)
	at alluxio.cli.TestRunner.runTest(TestRunner.java:162)
	at alluxio.cli.TestRunner.runTests(TestRunner.java:132)
	at alluxio.cli.TestRunner.main(TestRunner.java:98)
Caused by: alluxio.exception.status.UnknownException: Cannot create or load UFS directory s3://doc/test/default_tests_files: java.io.FileNotFoundException: s3://doc/test/default_tests_files.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:159)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:214)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:401)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:365)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.createFile(RetryHandlingFileSystemMasterClient.java:145)
	at alluxio.client.file.BaseFileSystem.lambda$createFile$1(BaseFileSystem.java:151)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:519)
	... 9 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Cannot create or load UFS directory s3://doc/test/default_tests_files: java.io.FileNotFoundException: s3://doc/test/default_tests_files.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.createFile(FileSystemMasterClientServiceGrpc.java:1582)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$createFile$2(RetryHandlingFileSystemMasterClient.java:146)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:399)
	... 13 more
Failed the test!
```
But when I checked the MinIO UI, I found the dir is successfully created by Alluxio

```
% mc ls doc/test/default_tests_files 
[2020-10-16 12:48:22 PDT]    80B BASIC_CACHE_ASYNC_THROUGH
[2020-10-16 12:48:22 PDT]    80B BASIC_CACHE_PROMOTE_ASYNC_THROUGH
[2020-10-16 12:48:22 PDT]    84B BASIC_NON_BYTE_BUFFER_CACHE_ASYNC_THROUGH
[2020-10-16 12:48:22 PDT]    84B BASIC_NON_BYTE_BUFFER_CACHE_PROMOTE_ASYNC_THROUGH
[2020-10-16 12:48:22 PDT]    84B BASIC_NON_BYTE_BUFFER_NO_CACHE_ASYNC_THROUGH
[2020-10-16 12:48:22 PDT]    80B BASIC_NO_CACHE_ASYNC_THROUGH
```

And I also tried with run ` bin/alluxio runUfsTests --path s3://doc/test -Daws.accessKeyId=minioadmin -Daws.secretKeyId=minioadmin-Dalluxio.underfs.s3.endpoint=http://localhost:9000/ -Dalluxio.underfs.s3.disable.dns.buckets=true`, I got the error as follows:

```
Running test: renameDirectoryDeepTest...
Related S3 operations: putObject, upload, copyObject, listObjectsV2, getObjectMetadata
Operation renameDirectoryDeepTest failed
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at alluxio.cli.UnderFileSystemContractTest.loadAndRunTests(UnderFileSystemContractTest.java:234)
	at alluxio.cli.UnderFileSystemContractTest.runCommonOperations(UnderFileSystemContractTest.java:185)
	at alluxio.cli.UnderFileSystemContractTest.runCommonOperations(UnderFileSystemContractTest.java:179)
	at alluxio.cli.UnderFileSystemContractTest.run(UnderFileSystemContractTest.java:104)
	at alluxio.cli.UnderFileSystemContractTest.main(UnderFileSystemContractTest.java:338)
Caused by: java.io.IOException: Should failed in UnderFileSystem.isDirectory() check, but succeed
	at alluxio.cli.UnderFileSystemCommonOperations.renameDirectoryDeepTest(UnderFileSystemCommonOperations.java:1063)
	... 9 more
Test class java.lang.reflect.Method.renameDirectoryDeepTest aborted
java.lang.reflect.InvocationTargetException
Failed the test!
```

**To Reproduce**
1. Configure Alluxio with MinIO as UFS.
2. run `bin/alluxio runTests`.

**Expected behavior**
Pass all `runTests` and `runUfsTests` tests.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
