### ISSUE TITLE
Alluxio master failed to start after stopping and restart with backup

### ISSUE THREAD

**Issue by jainanuj07** [Alluxio/alluxio#12356]
**Alluxio Version:**
  alluxio-2.4

**Describe the bug**
 I have to stop alluxio master to change my ufs sync interval. After stooping when I try to start the master is not able to start. 
 I then tried to start it with backup in that case also it fails and not able to start. 

It's giving this error 

java.io.IOException: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
        at alluxio.master.journal.raft.RaftJournalWriter.flush(RaftJournalWriter.java:100)
        at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:295)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:172)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

Starting master @  Logging to /home/ubuntu/alluxio-master/alluxio/logs
--- [ FAILED ] The master  is not serving requests.
--- Printing the log tail for /home/ubuntu/alluxio-master/alluxio/logs/master.log
>>> BEGIN

2020-10-20 17:37:36,950 DEBUG AuthenticatedChannelClientDriver - Authentication established for GrpcChannelKey{ClientType=RaftClient, ClientHostname=ip-172-20-6-164.ap-south-1.compute.internal, ServerAddress=GrpcServerAddress{HostName=172.20.6.164, SocketAddress=172.20.6.164:19200}, ChannelId=541e6eb4-1165-4fb9-b657-092eacf08eca}
2020-10-20 17:37:36,951 DEBUG GrpcMessagingClient - Created a messaging client connection: GrpcMessagingClientConnection{ConnectionOwner=CLIENT, ConnectionId=189, TransportId=GrpcChannelKey{ClientType=RaftClient, ClientHostname=ip-172-20-6-164.ap-south-1.compute.internal, ServerAddress=GrpcServerAddress{HostName=172.20.6.164, SocketAddress=172.20.6.164:19200}, ChannelId=541e6eb4-1165-4fb9-b657-092eacf08eca}}
2020-10-20 17:37:36,951 DEBUG NettyClientHandler - [id: 0xd1a31255, L:/172.20.6.164:44770 - R:172.20.6.164/172.20.6.164:19200] OUTBOUND HEADERS: streamId=381 headers=GrpcHttp2OutboundHeaders[:authority: 172.20.6.164:19200, :path: /alluxio.grpc.messaging.MessagingService/connect, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.28.1, channel-id: 541e6eb4-1165-4fb9-b657-092eacf08eca, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2020-10-20 17:37:36,951 DEBUG ClientConnection - a75ad6e0-6ab3-4452-b81f-29753f5779dc - Setting up connection to 172.20.6.164:19200
2020-10-20 17:37:36,951 DEBUG GrpcMessagingConnection - Submitted request(1) of type: io.atomix.copycat.protocol.ConnectRequest. Connection: GrpcMessagingClientConnection{ConnectionOwner=CLIENT, ConnectionId=189, TransportId=GrpcChannelKey{ClientType=RaftClient, ClientHostname=ip-172-20-6-164.ap-south-1.compute.internal, ServerAddress=GrpcServerAddress{HostName=172.20.6.164, SocketAddress=172.20.6.164:19200}, ChannelId=541e6eb4-1165-4fb9-b657-092eacf08eca}} FireAndForget: false
2020-10-20 17:37:36,951 DEBUG NettyClientHandler - [id: 0xd1a31255, L:/172.20.6.164:44770 - R:172.20.6.164/172.20.6.164:19200] OUTBOUND DATA: streamId=381 padding=0 endStream=false length=4108 bytes=00000010070a0208011a802001fc01002461373561643665302d366162332d343435322d623831662d3239373533663537373964630000000000000000000000...
2020-10-20 17:37:36,951 DEBUG GrpcMessagingServiceClientHandler - Creating a messaging server connection: GrpcMessagingServiceClientHandler{ServerAddress=172.20.6.164:19200, ClientAddress=/172.20.6.164:44770}
2020-10-20 17:37:36,951 DEBUG GrpcMessagingServiceClientHandler - Created a messaging server connection: GrpcMessagingServerConnection{ConnectionOwner=SERVER, ConnectionId=190, TransportId=GrpcMessagingServiceClientHandler{ServerAddress=172.20.6.164:19200, ClientAddress=/172.20.6.164:44770}}
2020-10-20 17:37:36,952 DEBUG GrpcMessagingConnection - Received a new message. Connection: GrpcMessagingServerConnection{ConnectionOwner=SERVER, ConnectionId=190, TransportId=GrpcMessagingServiceClientHandler{ServerAddress=172.20.6.164:19200, ClientAddress=/172.20.6.164:44770}}, RequestHeader: requestId: 1
, ResponseHeader:
2020-10-20 17:37:36,952 DEBUG GrpcMessagingConnection - Handling request(1) of type: io.atomix.copycat.protocol.ConnectRequest. Connection: GrpcMessagingServerConnection{ConnectionOwner=SERVER, ConnectionId=190, TransportId=GrpcMessagingServiceClientHandler{ServerAddress=172.20.6.164:19200, ClientAddress=/172.20.6.164:44770}}
2020-10-20 17:37:36,952 DEBUG GrpcMessagingConnection - Sending response of type: io.atomix.copycat.protocol.ConnectResponse for request(1). Connection: SERVER
2020-10-20 17:37:36,952 DEBUG NettyClientHandler - [id: 0xd1a31255, L:/172.20.6.164:44770 - R:172.20.6.164/172.20.6.164:19200] INBOUND HEADERS: streamId=381 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] padding=0 endStream=false
2020-10-20 17:37:36,952 DEBUG NettyClientHandler - [id: 0xd1a31255, L:/172.20.6.164:44770 - R:172.20.6.164/172.20.6.164:19200] INBOUND DATA: streamId=381 padding=0 endStream=false length=4110 bytes=00000010091204080110001a802001f50101d2010101000c3137322e32302e362e31363400004b0002b5000101d2010101000c3137322e32302e362e31363400...
2020-10-20 17:37:36,952 DEBUG GrpcMessagingConnection - Received a new message. Connection: GrpcMessagingClientConnection{ConnectionOwner=CLIENT, ConnectionId=189, TransportId=GrpcChannelKey{ClientType=RaftClient, ClientHostname=ip-172-20-6-164.ap-south-1.compute.internal, ServerAddress=GrpcServerAddress{HostName=172.20.6.164, SocketAddress=172.20.6.164:19200}, ChannelId=541e6eb4-1165-4fb9-b657-092eacf08eca}}, RequestHeader: , ResponseHeader: requestId: 1
isThrowable: false

2020-10-20 17:37:36,953 DEBUG GrpcMessagingConnection - Received response of type: io.atomix.copycat.protocol.CommandResponse for request(2). Connection: GrpcMessagingClientConnection{ConnectionOwner=CLIENT, ConnectionId=189, TransportId=GrpcChannelKey{ClientType=RaftClient, ClientHostname=ip-172-20-6-164.ap-south-1.compute.internal, ServerAddress=GrpcServerAddress{HostName=172.20.6.164, SocketAddress=172.20.6.164:19200}, ChannelId=541e6eb4-1165-4fb9-b657-092eacf08eca}}
<<< EOF
--- Printing the log tail for /home/ubuntu/alluxio-master/alluxio/logs/master.out
>>> BEGIN
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 377
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:596)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:239)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

<<< EOF

**To Reproduce**
1. Stop the master
2. Try to restart 
3. Try to restart with a journal backup still it will not start. 

**Expected behavior**
 1.  The Master should be able to start with the last checkpoint. If it failed due to some issues at least it should start from 
   backup. 
2. It should give a proper error so that will be able to understand why it's failing to start. 

**Urgency**
All alluxio data is getting loose whenever we restart the master.  
[logs_start.tar.gz](https://github.com/Alluxio/alluxio/files/5410832/logs_start.tar.gz)

**Additional context**
Attaching the master log when I try to restart. 

[logs_start.tar.gz](https://github.com/Alluxio/alluxio/files/5410839/logs_start.tar.gz)
[start with backup master.log](https://github.com/Alluxio/alluxio/files/5410843/master.log)
[start with backup master.out](https://github.com/Alluxio/alluxio/files/5410854/master_out.log)

**Comment by yuzhu** [comment]
@LuQQiu do you have any idea about this issue?

**Comment by LuQQiu** [comment]
@bf8086 FYI

**Comment by jainanuj07** [comment]
any thought around this as I am not able to use backup and every time my master down I have to format it.

**Comment by bf8086** [comment]
@jainanuj07 The logs indicate there are some journal flushing issues. Do you mind sharing your Alluxio cluster site property file?

**Comment by jainanuj07** [comment]
This is my alluxio-site.properties

alluxio.master.mount.table.root.ufs=s3://bounce-alluxio/
alluxio.user.file.metadata.sync.interval=30m
alluxio.worker.network.async.cache.manager.threads.max=10
alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
alluxio.worker.tieredstore.level0.dirs.quota=32GB
alluxio.worker.tieredstore.level1.alias=SSD
alluxio.worker.tieredstore.level1.dirs.path=/alluxio_data
alluxio.worker.tieredstore.level0.dirs.mediumtype=SSD
alluxio.worker.tieredstore.level1.dirs.quota=400GB
alluxio.worker.network.max.inbound.message.size=320MB
alluxio.user.metrics.collection.enabled=true
alluxio.underfs.s3.directory.suffix=_$folder$
alluxio.master.journal.type=EMBEDDED
alluxio.master.daily.backup.enabled=true
alluxio.master.daily.backup.time=18:05
alluxio.user.streaming.data.timeout=90sec

**Comment by LuQQiu** [comment]
@jainanuj07 Thanks for reporting the issue. There are two issues reported in your ticket,
1. Failed to start after stopping
2. Failed to start with backup.

I took a look at the first issue, there is no obvious error exist in the master.log, but master do takes longer than expected to start
```
2020-10-20 17:15:57,450 INFO  RaftJournalSystem - Initializing Raft Journal System
2020-10-20 17:15:57 to 17:16:13 Reading local copycat segment files
2020-10-20 17:16:13,680 INFO  AbstractPrimarySelector - Primary selector transitioning to SECONDARY
2020-10-20 17:16:14,567 INFO  JournalUtils - Reading journal entries
2020-10-20 17:16:15,314 INFO  Database - Adding new table ...
2020-10-20 17:16:14 to 16:59  Adding and Updating database tables
2020-10-20 17:17:03,100 INFO  AbstractPrimarySelector - Primary selector transitioning to PRIMARY
2020-10-20 17:17:03,108 INFO  AlluxioMasterProcess - All masters started
2020-10-20 17:17:08 to 2020-10-20 17:19:31  Database - Updating table ...
2020-10-20 17:19:31,082 INFO  RaftJournalSystem - Performing catchup. Last applied SN: 9920755. Catchup ID: -3286135040307079950
2020-10-20 17:19:32,090 Caught up  RaftJournalSystem - Caught up in 1008ms. Last sequence number from 
2020-10-20 17:19:32,094 INFO  RaftJournalSystem - Shutting down raft journal 
2020-10-20 17:19:32,127 INFO  RaftJournalSystem - Journal shutdown complete
```
The master takes 3.5mins to start which is longer than what `alluxio-start.sh master` tracks, that's why you saw the error log that master is not serving. After master starts, it immediately being killed maybe by `alluxio-stop.sh master`.

@jainanuj07 I noticed that the master takes a lot of time to updating database tables, are you using Alluxio catalog service and have many tables and/or partitions?

Will continue looking into the second issue.

**Comment by LuQQiu** [comment]
For the failed to start from backup, I guess it takes way too long to restore from backup as well, from the logs, i saw
```
.....
2020-10-20 17:37:27,609 INFO  BackupManager - 1854417 entries from backup applied so far...
2020-10-20 17:37:44,696 INFO  AbstractMaster - TableMaster: Stopped secondary master.
2020-10-20 17:37:44,697 INFO  AbstractMaster - MetaMaster: Stopped secondary master.
2020-10-20 17:37:44,697 INFO  AbstractMaster - FileSystemMaster: Stopped secondary master.

start with backup master.log
2020-10-20 17:37:44,700 INFO  RaftJournalSystem - Shutting down raft journal
2020-10-20 17:37:44,703 INFO  RaftJournalWriter - Closing journal writer. Last sequence numbers written/submitted/committed: 1854416/1854416/1854130

2020-10-20 17:37:45,128 ERROR ProcessUtils - Uncaught exception while running Alluxio master @172.20.6.164:19998, stopping it and exiting. Exception "java.lang.RuntimeException: alluxio.exception.status.UnavailableException: Failed to complete request: Cannot flush. Journal writer has been closed", Root Cause "alluxio.exception.JournalClosedException: Cannot flush. Journal writer has been closed"
```

Could be restoring from backup takes unexpected long and then users think the master failed to start and killed it (so that rat journal gets shutting down).

**Comment by LuQQiu** [comment]
The unexpected long time to start a master with journal/backup may come from the heavy usage of catalog service.
FYI @yuzhu @gpang

**Comment by LuQQiu** [comment]
The current version is Alluxio-2.4.0-SNAPSHOT, is the version before merging Ratis back to master branch. so the cluster is running with original Copycat embedded journal.

**Comment by jainanuj07** [comment]
Thanks, @LuQQiu  for looking at the issue.
1. are you using Alluxio catalog service and have many tables and/or partitions?
   yes, I am using an alluxio catalog and I have around 300 tables with each table contains many partitions. 
2. So is this expected behavior if the master is taking a long time to start it will throw an error and get killed ?
3. What is the solution to make this work. Is there any timeout that I can increase?

**Comment by LuQQiu** [comment]
For the second question: If the master is taking a long time to start, the master process will not be killed (as I know), but the `alluxio-start.sh` command will error out since it's not able to check master serving in the given timeout.

I would say try to wait for the master to come up, let the master process running for like 5-10 minutes and see if the master is able to serve requests after that time.

**Comment by jainanuj07** [comment]
@LuQQiu I do not see master process is running so it means it getting killed or not even started

**Comment by LuQQiu** [comment]
For the `logs_start.tar.gz`, looks like master process should be able to come up after an unexpected long time (like 5-10mins), but user kill the process.

For the given `start with backup master.log`, the master does error out with 
```
2020-10-20 17:37:44,700 INFO  RaftJournalSystem - Shutting down raft journal
2020-10-20 17:37:44,703 INFO  RaftJournalWriter - Closing journal writer. Last sequence numbers written/submitted/committed: 1854416/1854416/1854130

2020-10-20 17:37:45,128 ERROR ProcessUtils - Uncaught exception while running Alluxio master @172.20.6.164:19998, stopping it and exiting. Exception "java.lang.RuntimeException: alluxio.exception.status.UnavailableException: Failed to complete request: Cannot flush. Journal writer has been closed", Root Cause "alluxio.exception.JournalClosedException: Cannot flush. Journal writer has been closed"
java.lang.RuntimeException: alluxio.exception.status.UnavailableException: Failed to complete request: Cannot flush. Journal writer has been closed
	at alluxio.master.AlluxioMasterProcess.startMasters(AlluxioMasterProcess.java:219)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.gainPrimacy(FaultTolerantAlluxioMasterProcess.java:127)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.start(FaultTolerantAlluxioMasterProcess.java:90)
	at alluxio.ProcessUtils.run(ProcessUtils.java:36)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)
Caused by: alluxio.exception.status.UnavailableException: Failed to complete request: Cannot flush. Journal writer has been closed
	at alluxio.master.journal.MasterJournalContext.waitForJournalFlush(MasterJournalContext.java:80)
	at alluxio.master.journal.MasterJournalContext.close(MasterJournalContext.java:91)
	at alluxio.master.journal.StateChangeJournalContext.close(StateChangeJournalContext.java:53)
	at alluxio.master.BackupManager.lambda$initFromBackup$8(BackupManager.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: alluxio.exception.JournalClosedException: Cannot flush. Journal writer has been closed
	at alluxio.master.journal.raft.RaftJournalWriter.flush(RaftJournalWriter.java:84)
	at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:295)
	... 1 more
2020-10-20 17:37:54,731 INFO  RaftJournalSystem - Journal shutdown complete
2020-10-20 17:37:54,731 ERROR ProcessUtils - Uncaught exception while stopping Alluxio master @172.20.6.164:19998, simply exiting. Exception "java.lang.IllegalStateException: Journal is not running", Root Cause "java.lang.IllegalStateException: Journal is not running"
java.lang.IllegalStateException: Journal is not running
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at alluxio.master.journal.AbstractJournalSystem.stop(AbstractJournalSystem.java:56)
	at alluxio.master.AlluxioMasterProcess.stop(AlluxioMasterProcess.java:170)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.stop(FaultTolerantAlluxioMasterProcess.java:175)
	at alluxio.ProcessUtils.run(ProcessUtils.java:43)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)
2020-10-20 17:37:54,731 DEBUG NettyClientHandler - [id: 0xd1a31255
```

**Comment by LuQQiu** [comment]
@jainanuj07 Contacted you via Alluxio community slack, please take a look! Thanks

**Comment by apc999** [comment]
@LuQQiu  is issue here related to embedded journal? If yes, we will aim to fix it in the next release

**Comment by LuQQiu** [comment]
@apc999 It's a joint effort from catalog service + restoring from backup (may related to journaling). I think we should get it fix or at least understand what's happening

**Comment by LuQQiu** [comment]
PR #12649 helps Alluxio log the correct Ratis error that helps to debug the related journal issues.

PR #12650 expose Ratis journal size related configuration to Alluxio configuration and enlarge those values to support journaling entries larger than 3MB. Note that this is mainly helping the Ratis journal write path. Ratis journal read path has a hard limit of 30MB per entry.

PR #12658 change from logging a table with all its partitions to logging a table entry and multiple partitions entries based on alluxio.table.journal.partitions.chunk.size (=500 by default, a single entry only contains up to 500 partitions). In the future, Journal restore or restart will not be crashed by large table entries anymore.

PR #12695 helps resolve or prevents unexpected large journal entries coming from other places of Alluxio by flushing journal entries bigger than `MASTER_EMBEDDED_JOURNAL_ENTRY_SIZE_MAX / 3` and log error when journal entries bigger than the `MASTER_EMBEDDED_JOURNAL_ENTRY_SIZE_MAX`.

@jainanuj07 Could you help validate if the above fixes solve the issue? We have done some testing on our side but may not be similar to your actual environment. Thanks!

**Comment by jja725** [comment]
resolved
