### ISSUE TITLE
Result of alluxio metadata calculation is incorrect

### ISSUE THREAD

**Issue by TrafalgarZZZ** [Alluxio/alluxio#12373]
**Alluxio Version:**
What version of Alluxio are you using?
branch-2.3-fuse

**Describe the bug**
After the fix #12315 , we've found two unexpected things happened to us.

~**1. Results of all the alluxio command(e.g. `alluxio fs du -sh /` and `alluxio fs ls -R /`) are doubled.**~ (Resolved)
For example, we mount a UFS(about 143.67GB and 1157 files in total) to Alluxio, and run the following commands:
```
bash-4.4# alluxio fs du -sh /
File Size     In Alluxio       Path
287.34GB      0B (0%)          /
```

```
bash-4.4# alluxio fs ls -R / | wc -l
2314
```
The result is twice as the actual number, while we expect to see the two are same.

**2. When mounting a UFS with large amounts of files(about 92GB and 3.8million files), the result of `alluxio fs du -sh` is incorrect.**

This is the result we got when running `alluxio fs du -sh /` on the UFS mentioned above:
```
File Size     In Alluxio       Path
168.58GB      0B (0%)          /
```
Divide `168.58GB` by 2 due to problem 1, we got `84.29GB` which is still inconsistent with the actual size of our UFS (about 92GB).

We also found that `84.29GB` is exactly the same result we got **before the fix**, this may provide additional info about this problem. 
```
bash-4.4# alluxio fs du -sh /
File Size     In Alluxio       Path
SLF4J: Failed toString() invocation on an object of type [java.util.ArrayList]
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:304)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:276)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:230)
	at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:463)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.listStatus(RetryHandlingFileSystemMasterClient.java:228)
	at alluxio.client.file.BaseFileSystem.lambda$listStatus$9(BaseFileSystem.java:274)
	at alluxio.client.file.BaseFileSystem$$Lambda$71/825249556.call(Unknown Source)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:531)
	at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:270)
	at alluxio.cli.fs.command.DuCommand.runPlainPath(DuCommand.java:94)
	at alluxio.cli.fs.command.AbstractFileSystemCommand.runWildCardCmd(AbstractFileSystemCommand.java:92)
	at alluxio.cli.fs.command.DuCommand.run(DuCommand.java:207)
	at alluxio.cli.AbstractShell.run(AbstractShell.java:137)
	at alluxio.cli.fs.FileSystemShell.main(FileSystemShell.java:66)
84.29GB       0B (0%)          /
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

1. To reproduce problem 1, just launch an Alluxio master and mount any WebUFS to it. Either check the total size of UFS or list all the files in UFS can reproduce it.

2. To reproduce problem 2, launch an Alluxio master and mount an UFS with millions of files. Check the total size of it may reproduce it.

**Expected behavior**
Returned results should be consistent with the actual number.

**Urgency**
Describe the impact and urgency of the bug.
Urgent

**Additional context**
This is an issue related to #12127. 
@apc999

**Comment by TrafalgarZZZ** [comment]
@apc999 Hi, here are some few steps for you to reproduce problem 1:
1. run Docker container with Alluxio Image (branch-2.3-fuse, commit id: 75a8e27) and login 
```
docker exec -it alluxio-master /bin/bash
```
2. set `ALLUXIO_JAVA_OPTS` with some alluxio properties like:
```
export ALLUXIO_JAVA_OPTS=' -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.master.hostname=localhost '
```
3.  start Alluxio Master:
```
/entrypoint.sh master-only
```
4. Create some dir and file
```
alluxio fs mkdir /aaa && alluxio fs touch /aaa/bbb
```
5. list files
```
alluxio fs ls -R /
```
There should be two `/aaa` and `/aaa/bbb` file status in returned results.

**Comment by apc999** [comment]
@TrafalgarZZZ  thanks for the detailed instruction! I have created PR #12423 to fix this with unit tests added

**Comment by TrafalgarZZZ** [comment]
Hi @apc999 Thanks for the fix! The fix did resolve problem 1, but problem 2 seems still unresolved, so would you mind maybe reopen this issue?

**Comment by apc999** [comment]
@TrafalgarZZZ my understanding is that problem 2 you described that the results are doubled has been resolved.
You were reporting the case where the result is no more doubled but just different (with some files missing). Am I correct?

If that's the case, I would suggest creating a new issue documenting the new behavior, but keep this issue closed.

**Comment by TrafalgarZZZ** [comment]
@apc999 yes, just like what you said. I will close this and open a new issue later. Thanks for your help.
