### ISSUE TITLE
The alluxio master is busy when no work load in using rocks db

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#12568]
**Alluxio Version:**
alluxio version -r
2.3.1-SNAPSHOT-2c412267e0e749ced63262d53043cf753cc11927

**Describe the bug**

There is no workload on Alluxio, but Alluxio master is still busy.

![image](https://user-images.githubusercontent.com/3724388/99878872-5840ba00-2c43-11eb-9bfb-75e47c6b60c9.png)

And in the master I can see such logs:

```
020-11-21 12:38:35,463 WARN  SleepingTimer - Master Replication Check last execution took 247774 ms. Longer than the interval 60000
2020-11-21 12:38:48,656 ERROR FileSystemMasterClientServiceHandler - Exit (Error): ListStatus: request: path: "/"
options {
  loadMetadataType: ONCE
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: FREE
  }
  recursive: true
}

java.lang.RuntimeException: Call cancelled by trackers: GRPC_CLIENT_TRACKER
	at alluxio.master.file.RpcContext.throwIfCancelled(RpcContext.java:103)
	at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1060)
	at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:1025)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$listStatus$8(FileSystemMasterClientServiceHandler.java:226)
	at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.listStatus(FileSystemMasterClientServiceHandler.java:224)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2170)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
	at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
	at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1356)
	at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
2020-11-21 12:43:42,443 WARN  SleepingTimer - Master Replication Check last execution took 306980 ms. Longer than the interval 60000
2020-11-21 12:48:57,036 WARN  SleepingTimer - Master Replication Check last execution took 314593 ms. Longer than the interval 60000
2020-11-21 12:53:19,788 WARN  SleepingTimer - Master Replication Check last execution took 262752 ms. Longer than the interval 60000
2020-11-21 12:57:56,989 WARN  SleepingTimer - Master Replication Check last execution took 277201 ms. Longer than the interval 60000
2020-11-21 13:02:10,934 WARN  SleepingTimer - Master Replication Check last execution took 253945 ms. Longer than the interval 60000
2020-11-21 13:07:03,785 WARN  SleepingTimer - Master Replication Check last execution took 292851 ms. Longer than the interval 60000
2020-11-21 13:11:22,990 WARN  SleepingTimer - Master Replication Check last execution took 259204 ms. Longer than the interval 60000
2020-11-21 13:15:34,934 WARN  SleepingTimer - Master Replication Check last execution took 251944 ms. Longer than the interval 60000
2020-11-21 13:19:45,738 WARN  SleepingTimer - Master Replication Check last execution took 250804 ms. Longer than the interval 60000
2020-11-21 13:22:48,657 INFO  ServerConfigurationChecker - All server-side configurations are consistent.
2020-11-21 13:23:57,047 WARN  SleepingTimer - Master Replication Check last execution took 251308 ms. Longer than the interval 60000
2020-11-21 13:28:04,426 WARN  SleepingTimer - Master Replication Check last execution took 247378 ms. Longer than the interval 60000
Sat Nov 21 13:31:38 GMT 2020 com.taobao.arthas.agent.ArthasClassloader@9f12c6e JM.Log:INFO Log root path: /root/logs/
Sat Nov 21 13:31:38 GMT 2020 com.taobao.arthas.agent.ArthasClassloader@9f12c6e JM.Log:INFO Set arthas log path: /root/logs/arthas
2020-11-21 13:32:11,501 WARN  SleepingTimer - Master Replication Check last execution took 247075 ms. Longer than the interval 60000
2020-11-21 13:36:22,278 WARN  SleepingTimer - Master Replication Check last execution took 250776 ms. Longer than the interval 60000
2020-11-21 13:41:11,998 WARN  SleepingTimer - Master Replication Check last execution took 289719 ms. Longer than the interval 60000
2020-11-21 13:45:18,652 WARN  SleepingTimer - Master Replication Check last execution took 246654 ms. Longer than the interval 60000
2020-11-21 13:49:31,671 WARN  SleepingTimer - Master Replication Check last execution took 253019 ms. Longer than the interval 60000
```

And the stack trace is 

```
"Master Replication Check" Id=48 RUNNABLE
    at org.rocksdb.RocksIterator.seek0(Native Method)
    at org.rocksdb.AbstractRocksIterator.seek(AbstractRocksIterator.java:58)
    at alluxio.master.metastore.rocks.RocksBlockStore.getLocations(RocksBlockStore.java:156)
    at alluxio.master.block.DefaultBlockMaster.generateBlockInfo(DefaultBlockMaster.java:1049)
    at alluxio.master.block.DefaultBlockMaster.getBlockInfo(DefaultBlockMaster.java:735)
    at alluxio.master.file.replication.ReplicationChecker.check(ReplicationChecker.java:262)
    at alluxio.master.file.replication.ReplicationChecker.heartbeat(ReplicationChecker.java:142)
    at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

    Number of locked synchronizers = 2
    - java.util.concurrent.locks.ReentrantLock$NonfairSync@52bc527f
    - java.util.concurrent.ThreadPoolExecutor$Worker@67d48005
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
