### ISSUE TITLE
Making the gRPC call that retrieves table partition scalable

### ISSUE THREAD

**Issue by zjiawei3** [Alluxio/alluxio#12595]
**Alluxio Env**
Version: 2.4.0
Master: -Xms96g -Xmx96g, Single master (no secondary, no standby), with embedded Journal server
Worker: 10 worker nodes, each with -Xms4g -Xmx4g
AWS Instance type: i3.4xlarge, 16cores, 120GB mem

**Describe the bug**
I'm exploring Alluxio as a caching layer for our Presto cluster. All our files currently live in S3 and we are running Hive cluster upon those files. I'm using Alluxio Catalog Service solution to sync our Hive databases thru HMS to Alluxio master. It worked for small tables and a small number of partitions, but failed when I tried to query a big table with >20k partitions.

Even if we dont scan those partitions, the issue persists.

query:

`
SELECT
        gdpr_user__secret as gdpr_user__secret,
        device__platform as device_platform,
        substr(timestamp, 1, 19) AS event_date_time,
        client_ip,
        geoip__ip as geo_ip,
        geoip__city_name as geo_ip_city_name,
        geoip__country_name as geo_ip_country_name
    FROM alluxio.events.gdpr_event
    WHERE gdpr_user__secret in ('pii_mask_85e86226-c553-4edc-8cc9-98263894a143')
            AND dt>= '2020-09-25'
`

logs:

`io.prestosql.spi.PrestoException: gRPC message exceeds maximum size 104857600: 115319510
	at io.prestosql.plugin.hive.metastore.alluxio.AlluxioHiveMetastore.getPartitionNamesByParts(AlluxioHiveMetastore.java:382)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.loadPartitionNamesByParts(CachingHiveMetastore.java:681)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:258)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.getPartitionNamesByParts(CachingHiveMetastore.java:676)
	at io.prestosql.plugin.hive.HiveMetastoreClosure.getPartitionNamesByParts(HiveMetastoreClosure.java:195)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.doGetPartitionNames(SemiTransactionalHiveMetastore.java:598)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.getPartitionNamesByParts(SemiTransactionalHiveMetastore.java:576)
	at io.prestosql.plugin.hive.HivePartitionManager.getFilteredPartitionNames(HivePartitionManager.java:338)
	at io.prestosql.plugin.hive.HivePartitionManager.getPartitions(HivePartitionManager.java:156)
	at io.prestosql.plugin.hive.HiveMetadata.applyFilter(HiveMetadata.java:1997)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.applyFilter(ClassLoaderSafeConnectorMetadata.java:690)
	at io.prestosql.metadata.MetadataManager.applyFilter(MetadataManager.java:1229)
	at io.prestosql.sql.planner.iterative.rule.PushPredicateIntoTableScan.pushFilterIntoTableScan(PushPredicateIntoTableScan.java:213)
	at io.prestosql.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:99)
	at io.prestosql.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:69)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:168)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:143)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:108)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:99)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:200)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:189)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:184)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:425)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:413)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:365)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_2a142c0____20201119_055150_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: alluxio.exception.status.ResourceExhaustedException: gRPC message exceeds maximum size 104857600: 115319510
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:143)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:214)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:401)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:365)
	at alluxio.client.table.RetryHandlingTableMasterClient.readTable(RetryHandlingTableMasterClient.java:148)
	at io.prestosql.plugin.hive.metastore.alluxio.AlluxioHiveMetastore.getPartitionNamesByParts(AlluxioHiveMetastore.java:357)
	... 48 more
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 104857600: 115319510
	at alluxio.shaded.client.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at alluxio.shaded.client.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at alluxio.shaded.client.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at alluxio.grpc.table.TableMasterClientServiceGrpc$TableMasterClientServiceBlockingStub.readTable(TableMasterClientServiceGrpc.java:927)
	at alluxio.client.table.RetryHandlingTableMasterClient.lambda$readTable$7(RetryHandlingTableMasterClient.java:148)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:399)
	... 51 more
`

**Comment by gpang** [comment]
We can make that call a streaming rpc. This PR is an example of converting an existing rpc to a streaming rpc: https://github.com/Alluxio/alluxio/pull/8813

Relevant parts of the PR:
- [change the rpc definition to be streaming](https://github.com/Alluxio/alluxio/pull/8813/files#diff-dbdf3988f9f3c1041d468c233a43d169b62028f7b704c6842c30c88d6246f010R500)
- [update server rpc handler to implement streaming](https://github.com/Alluxio/alluxio/pull/8813/files#diff-1ee78a35b1736b84c0e192df8a0d2c38e6535b3e5095da19bfdf8740bd37372bR231-R292)
- [update client side to receive stream results](https://github.com/Alluxio/alluxio/pull/8813/files#diff-f0b3f5c51c2e3e48833beccd832c5a63de3d74b8d195d9da564c99c299f50288R217-R223)

**Comment by zjiawei3** [comment]
@hycsam has confirmed this can be circumvented by changing a config. As we discussed in the sync up , we will close for the current release.
