### ISSUE TITLE
Failed to copy 1TB file through JNI Fuse

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#12591]
**Alluxio Version:**

2.3.1-SNAPSHOT-2c412267e0e749ced63262d53043cf753cc11927

**Describe the bug**
1. The file's size is 1279.90GB 

```
alluxio fs du -sh  /large-test/largefile/image-large.tar.gz

File Size     In Alluxio       Path
1279.90GB     12.80GB (1%)     /large-test/largefile/image-large.tar.gz
```

2. The cache capacity is 1800.00GB , 12 nodes

```
alluxio fsadmin report capacity
Capacity information for all workers:
    Total Capacity: 1800.00GB
        Tier: SSD  Size: 1800.00GB
    Used Capacity: 9.52GB
        Tier: SSD  Size: 9.52GB
    Used Percentage: 0%
    Free Percentage: 100%

Worker Name      Last Heartbeat   Storage       SSD
192.168.5.138    0                capacity      150.00GB
                                  used          1232.00MB (0%)
192.168.5.131    0                capacity      150.00GB
                                  used          192.00MB (0%)
192.168.5.132    0                capacity      150.00GB
                                  used          1584.00MB (1%)
192.168.5.137    0                capacity      150.00GB
                                  used          0B (0%)
192.168.5.129    0                capacity      150.00GB
                                  used          80.00MB (0%)
192.168.5.139    0                capacity      150.00GB
                                  used          1008.00MB (0%)
192.168.5.134    0                capacity      150.00GB
                                  used          1760.00MB (1%)
192.168.5.135    0                capacity      150.00GB
                                  used          288.00MB (0%)
192.168.5.136    0                capacity      150.00GB
                                  used          1120.00MB (0%)
192.168.5.133    0                capacity      150.00GB
                                  used          112.00MB (0%)
192.168.5.130    0                capacity      150.00GB
                                  used          1328.00MB (0%)
192.168.5.128    0                capacity      150.00GB
                                  used          1040.00MB (0%)
```

3.  Try to copy the file

```
 time cp /runtime-mnt/alluxio/default/large/alluxio-fuse/large-test/image-large.tar.gz .
cp: 读取"/runtime-mnt/alluxio/default/large/alluxio-fuse/large-test/image-large.tar.gz" 时出错: 输入/输出错误
cp: 扩展"./image-large.tar.gz" 失败: 输入/输出错误

real    0m22.228s
user    0m0.001s
sys     0m0.004s
```

The logs are in

```
2020-11-29 01:55:28,384 ERROR AlluxioJniFuseFileSystem - Failed to read /large-test/image-large.tar.gz,131072,3670016:
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at alluxio.client.block.stream.SharedGrpcDataReader.readChunk(SharedGrpcDataReader.java:105)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:442)
	at alluxio.client.block.stream.BlockInStream.readInternal(BlockInStream.java:274)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:270)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:190)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:366)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:339)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:339)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:150)
2020-11-29 01:55:50,236 ERROR AlluxioJniFuseFileSystem - Failed to read /large-test/image-large.tar.gz,4096,3670016:
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at alluxio.client.block.stream.SharedGrpcDataReader.readChunk(SharedGrpcDataReader.java:105)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:442)
	at alluxio.client.block.stream.BlockInStream.readInternal(BlockInStream.java:274)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:270)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:190)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:366)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:339)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:339)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:150)
2020-11-29 01:55:50,237 WARN  AlluxioJniFuseFileSystem - read(path=/large-test/image-large.tar.gz,buf=java.nio.DirectByteBuffer[pos=0 lim=4096 cap=4096],size=4096,offset=3670016) returned -5 in 21852 ms (>=1000 ms)
2020-11-29 01:55:50,237 ERROR AlluxioJniFuseFileSystem - Failed to read /large-test/image-large.tar.gz,131072,3932160:
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at alluxio.client.block.stream.SharedGrpcDataReader.readChunk(SharedGrpcDataReader.java:105)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:442)
	at alluxio.client.block.stream.BlockInStream.readInternal(BlockInStream.java:274)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:270)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:190)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:366)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:339)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:339)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:150)
2020-11-29 01:55:50,238 WARN  AlluxioJniFuseFileSystem - read(path=/large-test/image-large.tar.gz,buf=java.nio.DirectByteBuffer[pos=0 lim=131072 cap=131072],size=131072,offset=3932160) returned -5 in 21855 ms (>=1000 ms)
```

[diagnose_fluid_1606625922.tar.gz](https://github.com/Alluxio/alluxio/files/5611681/diagnose_fluid_1606625922.tar.gz)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
