### ISSUE TITLE
No Under File System Factory found for: hdfs://namenode1:8020/

### ISSUE THREAD

**Issue by loovia** [Alluxio/alluxio#12709]
**Alluxio Version:**
version: `alluxio-2.4.1-1`

**Describe the bug**
when I execute `./bin/alluxio-start.sh all Mount`, there was an error from ./logs/master.log:
```
2021-01-11 02:45:51,481 WARN  ExtensionFactoryRegistry - No factory implementation supports the path hdfs://namenode1:8020/
2021-01-11 02:45:51,530 ERROR AlluxioMaster - Fatal error: Failed to create master process
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start masters
        at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:125)
        at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:400)
        at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Failed to start masters
        at alluxio.master.MasterUtils.createMasters(MasterUtils.java:57)
        at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:123)
        ... 2 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No Under File System Factory found for: hdfs://namenode1:8020/
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:592)
        at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:554)
        at alluxio.master.MasterUtils.createMasters(MasterUtils.java:55)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: No Under File System Factory found for: hdfs://namenode1:8020/
        at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:95)
        at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:128)
        at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:167)
        at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:60)
        at alluxio.master.file.DefaultFileSystemMaster.getRootMountInfo(DefaultFileSystemMaster.java:495)
        at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:437)
        at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:418)
        at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:51)
        at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:28)
        at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

2021-01-11 02:46:02,082 INFO  NettyUtils - EPOLL_MODE is available
2021-01-11 02:46:03,354 ERROR MasterHealthCheckClient - Exception thrown in the master process check
java.lang.IllegalStateException: Master process is not running on the host namenode1
        at alluxio.master.MasterHealthCheckClient$ProcessCheckRunnable.run(MasterHealthCheckClient.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

I don't konw how to solve it, and below is my configuration:
```
alluxio.master.hostname=namenode1
alluxio.master.journal.type=UFS
alluxio.master.mount.table.root.ufs=hdfs://namenode1:8020/
alluxio.master.mount.table.root.option.alluxio.underfs.version=3.1
alluxio.underfs.hdfs.configuration=/etc/hadoop/3.1.4.0-315/0/core-site.xml:/etc/hadoop/3.1.4.0-315/0/hdfs-site.xml

alluxio.master.embedded.journal.addresses=namenode1:19200,namenode2:19200,namenode3:19200

alluxio.master.security.impersonation.yarn.users=*
alluxio.master.security.impersonation.hive.users=*
alluxio.master.security.impersonation.impala.users=*
alluxio.master.security.impersonation.cydw.users=*
```

**Comment by gpang** [comment]
@loovia It looks like you are configuring for hdfs 3.1. Does the 3.1 hdfs ufs exist under the `${ALLUXIO_HOME}/lib/` directory?

**Comment by loovia** [comment]
@gpang thank u! I added the 3.1 hdfs ufs to `${ALLUXIO_HOME}/lib/`, But it's another error:
```
[hdfs@namenode1 bin]$ ./alluxio fs mount   --option alluxio.underfs.version=3.1  /mnt/hdfs  hdfs://namenode1:8020/
File /mnt/hdfs creation failed. Component 1(mnt) does not exist
```
I have created the `/mnt/hdfs` directory by hdfs user: 
```
[hdfs@namenode1 bin]$ ll /mnt/
total 0
drwxr-xr-x 2 hdfs hadoop 6 Jan 11 18:32 hdfs
```

**Comment by apc999** [comment]
@loovia  to mount your hdfs path to Alluxio, you need to give an unexisting path.
In your case, can you remove `/mnt/hdfs` before running `fs mount` or use a different dir?

**Comment by loovia** [comment]
@apc999 thanks! 
My alluxio cluster consists of 3 masters and 11 workers. I changed my configuration file `conf/alluxio-site.properties` : 
```
alluxio.master.mount.table.root.ufs=hdfs://namenode1:8020/
alluxio.master.mount.table.root.ufs=hdfs://mycluster
alluxio.master.mount.table.root.option.alluxio.underfs.version=3.1
alluxio.underfs.hdfs.configuration=/etc/hadoop/3.1.4.0-315/0/core-site.xml:/etc/hadoop/3.1.4.0-315/0/hdfs-site.xml

alluxio.master.embedded.journal.addresses=namenode1:19200,namenode2:19200,namenode3:19200

alluxio.master.journal.type=UFS
alluxio.master.journal.folder=hdfs://mycluster/alluxio/alluxio_journal/

# Security
alluxio.master.security.impersonation.yarn.users=*
alluxio.master.security.impersonation.hive.users=*
alluxio.master.security.impersonation.impala.users=*
alluxio.master.security.impersonation.cydw.users=*
```
But when I execute `./bin/alluxio format` by hdfs user, I get an error(hdfs dir`hdfs://mycluster/alluxio/alluxio_journal/BlockMaster` was built):
```
[hdfs@namenode1 bin]$ ./alluxio format
Executing the following command on all worker nodes and logging to /opt/alluxio/alluxio-2.4.1-1/logs/task.log: /opt/alluxio/alluxio-2.4.1-1/bin/alluxio formatWorker
Waiting for tasks to finish...
All tasks finished
Formatting Alluxio Master @ namenode1
2021-01-12 22:08:02,641 INFO  Format - Formatting master journal: hdfs://mycluster/alluxio/alluxio_journal/
2021-01-12 22:08:02,701 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio/alluxio-2.4.1-1/lib
2021-01-12 22:08:02,825 INFO  ExtensionFactoryRegistry - Loading extension jars from /opt/alluxio/alluxio-2.4.1-1/extensions
2021-01-12 22:08:02,856 WARN  ExtensionFactoryRegistry - No factory implementation supports the path hdfs://mycluster/alluxio/alluxio_journal/BlockMaster
2021-01-12 22:08:02,857 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio/alluxio-2.4.1-1/lib
2021-01-12 22:08:02,900 INFO  ExtensionFactoryRegistry - Loading extension jars from /opt/alluxio/alluxio-2.4.1-1/extensions
2021-01-12 22:08:02,918 WARN  ExtensionFactoryRegistry - No factory implementation supports the path hdfs://mycluster/alluxio/alluxio_journal/BlockMaster
2021-01-12 22:08:02,919 ERROR Format - Failed to format
java.lang.IllegalArgumentException: No Under File System Factory found for: hdfs://mycluster/alluxio/alluxio_journal/BlockMaster
        at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:95)
        at alluxio.master.journal.ufs.UfsJournal.<init>(UfsJournal.java:149)
        at alluxio.master.journal.ufs.UfsJournalSystem.createJournal(UfsJournalSystem.java:73)
        at alluxio.master.journal.ufs.UfsJournalSystem.createJournal(UfsJournalSystem.java:47)
        at alluxio.cli.Format.format(Format.java:120)
        at alluxio.cli.Format.main(Format.java:97)
```

**Comment by gpang** [comment]
@gpang Which version is your journal HDFS? Which ever that version is:
- it should be configured with `alluxio.master.journal.ufs.option.alluxio.underfs.version=???`
- that corresponding jar should be in the `lib/` directory

**Comment by loovia** [comment]
@gpang Thanks! But I have another problem with `No Under File System Factory found for`.

I mounted two HDFS(HDP3.1.4 and CDH6.3.2) by mount command.  And that corresponding jar is already in the `lib/` directory.
- HDP3.1.4
```
[hdfs@dc-adh-188 bin]$ ./alluxio fs mount \
  --option alluxio.underfs.version=3.1 \
  /hdfs/hdp3 hdfs://mycluster/
```
- CDH6.3.2
```
[hdfs@dc-adh-188 bin]$ ./alluxio fs mount \
  --option alluxio.underfs.version=3.0 \
  --option alluxio.underfs.hdfs.configuration=/opt/alluxio/alluxio-2.4.1-1/conf/cdh6.3.2/core-site.xml:/opt/alluxio/alluxio-2.4.1-1/conf/cdh6.3.2/hdfs-site.xml \
  /hdfs/cdh632 hdfs://192.168.33.22:8020/
```


And I put same test data to HDFS by `hadoop put hdfs://namenode:port/path`. Now I want to test whether Aluxio can works.

- In HDP3.1.4 it works
```
[hdfs@namenode1 bin]$ hadoop fs -cat alluxio://namenode1:19998,namenode2:19998,namenode3:19998/hdfs/hdp3/group/tools/lineorder/pt=2020010515/lineorder.csv | head
21/01/19 02:34:32 INFO hadoop.AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration {}, uri configuration {alluxio.zookeeper.address=null, alluxio.zookeeper.enabled=false, alluxio.master.rpc.addresses=192.168.33.188:19998,192.168.33.189:19998,192.168.33.190:19998}
21/01/19 02:34:33 INFO hadoop.AbstractFileSystem: Initializing filesystem with connect details 192.168.33.188:19998,192.168.33.189:19998,192.168.33.190:19998
21/01/19 02:34:33 INFO network.TieredIdentityFactory: Initialized tiered identity TieredIdentity(node=dc-adh-188, rack=null)
21/01/19 02:34:35 INFO network.NettyUtils: EPOLL_MODE is available
1,1,73801,465569,8273,"1996-01-02","5-LOW",0,17,2608718,21280402,4,2504369,92072,2,"1996-02-12","TRUCK"
1,2,73801,201928,1630,"1996-01-02","5-LOW",0,36,6587676,21280402,9,5994785,109794,6,"1996-02-28","MAIL"
1,3,73801,191100,709,"1996-01-02","5-LOW",0,8,952880,21280402,10,857592,71466,2,"1996-03-05","REG AIR"
1,4,73801,6395,9421,"1996-01-02","5-LOW",0,28,3643892,21280402,9,3315941,78083,6,"1996-03-30","AIR"
1,5,73801,72080,16246,"1996-01-02","5-LOW",0,24,2524992,21280402,10,2272492,63124,4,"1996-03-14","FOB"
1,6,73801,46904,13672,"1996-01-02","5-LOW",0,32,5922880,21280402,7,5508278,111054,2,"1996-02-07","MAIL"
2,1,156004,318510,10657,"1996-12-01","1-URGENT",0,38,5808300,6098715,0,5808300,91710,5,"1997-01-14","RAIL"
3,1,246628,12891,19585,"1993-10-14","5-LOW",0,45,8117505,23639715,6,7630454,108233,0,"1994-01-04","AIR"
3,2,246628,57107,16666,"1993-10-14","5-LOW",0,49,5214090,23639715,10,4692681,63846,0,"1993-12-20","RAIL"
3,3,246628,385345,14090,"1993-10-14","5-LOW",0,27,3861891,23639715,6,3630177,85819,7,"1993-11-22","SHIP"
```
- In CDH6.3.2, it not works. `No Under File System Factory found for` from the log.
```
[hdfs@namenode1 bin]$ hadoop fs -cat alluxio://namenode1:19998,namenode2:19998,namenode3:19998/hdfs/cdh632/data/hive/warehouse/rp_gene_user_tag_4clickhouse_inc_d/rp_gene_user_tag_4clickhouse_inc_d.txt|head
21/01/19 02:24:46 INFO hadoop.AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration {}, uri configuration {alluxio.zookeeper.address=null, alluxio.zookeeper.enabled=false, alluxio.master.rpc.addresses=namenode1:19998,namenode2:19998,namenode3:19998}
21/01/19 02:24:47 INFO hadoop.AbstractFileSystem: Initializing filesystem with connect details namenode1:19998,namenode2:19998,namenode3:19998
21/01/19 02:24:47 INFO network.TieredIdentityFactory: Initialized tiered identity TieredIdentity(node=dc-adh-188, rack=null)
21/01/19 02:24:49 INFO network.NettyUtils: EPOLL_MODE is available
21/01/19 02:25:00 WARN stream.GrpcBlockingStream: Received error alluxio.shaded.client.io.grpc.StatusRuntimeException: UNAVAILABLE: Failed to read block ID=56321114112 from tiered storage and UFS tier: No Under File System Factory found for: hdfs://192.168.33.22:8020/ for stream (Zero Copy GrpcDataReader)
21/01/19 02:25:00 WARN file.AlluxioFileInStream: Failed to read block 56321114112 of file /hdfs/cdh632/data/hive/warehouse/rp_gene_user_tag_4clickhouse_inc_d/rp_gene_user_tag_4clickhouse_inc_d.txt from worker WorkerNetAddress{host=dc-adh-54, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=dc-adh-54, rack=null)}, will retry: Failed to read block ID=56321114112 from tiered storage and UFS tier: No Under File System Factory found for: hdfs://192.168.33.22:8020/ (Zero Copy GrpcDataReader)
21/01/19 02:25:00 WARN stream.GrpcBlockingStream: Received error alluxio.shaded.client.io.grpc.StatusRuntimeException: UNAVAILABLE: Failed to read block ID=56321114112 from tiered storage and UFS tier: No Under File System Factory found for: hdfs://192.168.33.22:8020/ for stream (Zero Copy GrpcDataReader)
21/01/19 02:25:00 WARN file.AlluxioFileInStream: Failed to read block 56321114112 of file /hdfs/cdh632/data/hive/warehouse/rp_gene_user_tag_4clickhouse_inc_d/rp_gene_user_tag_4clickhouse_inc_d.txt from worker WorkerNetAddress{host=dc-adh-195, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=dc-adh-195, rack=null)}, will retry: Failed to read block ID=56321114112 from tiered storage and UFS tier: No Under File System Factory found for: hdfs://192.168.33.22:8020/ (Zero Copy GrpcDataReader)
```

I don't know what's wrong. The following is `conf/alluxio-site.properties` content:
```
alluxio.underfs.hdfs.configuration=/etc/hadoop/3.1.4.0-315/0/core-site.xml:/etc/hadoop/3.1.4.0-315/0/hdfs-site.xml
alluxio.master.embedded.journal.addresses=192.168.33.188:19200,192.168.33.189:19200,192.168.33.190:19200

alluxio.master.journal.type=UFS
alluxio.master.journal.ufs.option.alluxio.underfs.version=3.1
alluxio.master.journal.folder=hdfs://mycluster/alluxio/alluxio_journal/

alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/dev/shm
```
Please help me to see what's wrong, thank you!

**Comment by leonlee9310** [comment]
@loovia Have  u already solved this problem？

**Comment by loovia** [comment]
@leonlee9310 yeah~

**Comment by isLiuXinxin** [comment]
> @gpang谢谢你！我将3.1 hdfs ufs添加到`${ALLUXIO_HOME}/lib/`，但这是另一个错误：
> 
> ```
> [hdfs@namenode1 bin]$ ./alluxio fs mount   --option alluxio.underfs.version=3.1  /mnt/hdfs  hdfs://namenode1:8020/
> File /mnt/hdfs creation failed. Component 1(mnt) does not exist
> ```
> 
> 我已经`/mnt/hdfs`通过hdfs用户创建了目录：
> 
> ```
> [hdfs@namenode1 bin]$ ll /mnt/
> total 0
> drwxr-xr-x 2 hdfs hadoop 6 Jan 11 18:32 hdfs
> ```



> @gpang谢谢你！我将3.1 hdfs ufs添加到`${ALLUXIO_HOME}/lib/`，但这是另一个错误：
> 
> ```
> [hdfs@namenode1 bin]$ ./alluxio fs mount   --option alluxio.underfs.version=3.1  /mnt/hdfs  hdfs://namenode1:8020/
> File /mnt/hdfs creation failed. Component 1(mnt) does not exist
> ```
> 
> 我已经`/mnt/hdfs`通过hdfs用户创建了目录：
> 
> ```
> [hdfs@namenode1 bin]$ ll /mnt/
> total 0
> drwxr-xr-x 2 hdfs hadoop 6 Jan 11 18:32 hdfs
> ```

Could you tell me where did you get the 3.1 HDFS UFS JAR?

**Comment by loovia** [comment]
@isLiuXinxin `https://docs.alluxio.io/os/user/stable/en/ufs/HDFS.html`搜`Mount HDFS with Specific Versions`

**Comment by isLiuXinxin** [comment]
Could not resolve dependencies for project org.alluxio:alluxio-underfs-hdfs:jar:2.4.0: Failed to collect dependencies at org.alluxio:alluxio-shaded-hadoop:jar:3.1.0 
Could you send an email with alluxio-underfs-hdfs-3.1.0-2.4.x.jar?  isliuxinxin@yeah.net

**Comment by DLUTLiuFengyi** [comment]
我尝试过 `alluxio.master.mount.table.root.option.alluxio.underfs.version=3.2` 和 `alluxio.master.journal.ufs.option.alluxio.underfs.version=3.2` 都不行，用 `alluxio.underfs.version=3.2` 反而成功了...
