### ISSUE TITLE
Automatically create metric directory if metric directory is not created yet

### ISSUE THREAD

**Issue by HelloHorizon** [Alluxio/alluxio#12702]
**Is your feature request related to a problem? Please describe.**
The current metric system requires users to create the metrics directory before starting the Alluxio cluster, otherwise, it will keep poping warning message as follows:
```
2021-01-05 13:43:03,305 WARN  CsvReporter - Error writing to Cluster.BytesReadRemoteThroughput
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:319)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:312)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:228)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:253)
	at com.codahale.metrics.ScheduledReporter.lambda$start$0(ScheduledReporter.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Describe the solution you'd like**
Auto-create metrics directory if it's possible.

**Describe alternatives you've considered**

**Urgency**
Explain why the feature is important

**Additional context**

**Comment by apc999** [comment]
@JySongWithZhangCe  can you take a look at this issue?

**Comment by JySongWithZhangCe** [comment]
> @JySongWithZhangCe can you take a look at this issue?

Sure
