### ISSUE TITLE
Deploy Alluxio on Docker - permission error running alluxio-fuse Docker command

### ISSUE THREAD

**Issue by claesenm** [Alluxio/alluxio#12712]
**Page**
https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html#enable-posix-api-access

**Summary**
The docker run command listed in section 5.4 is not working due to permission errors during the fuse mount.

**Fix**
The permission error can be resolved by adding the `--privileged` flag to the docker run command, e.g.,

```
$ docker run --rm \
    --net=host \
    --name=alluxio-fuse \
    --privileged \
    -v /tmp/mnt:/mnt:rshared \
    -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost" \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    alluxio/alluxio-fuse fuse
```

**Comment by peterwillcn** [comment]
ls: cannot access alluxio-fuse: Permission denied
![Screen Shot 2021-01-26 at 11 36 10 AM](https://user-images.githubusercontent.com/323794/105797533-1f1e2080-5fcb-11eb-8830-bd04b50094f1.png)

```
docker run --rm \
    --net=host \
    --name=alluxio-fuse \
    -v /tmp/fs:/mnt:rshared \
    -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=10.10.10.101" \
    --privileged \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    alluxio/alluxio-fuse fuse
```

**Comment by apc999** [comment]
Confirm. This is what i see:
```
docker run --rm     --net=host     --name=alluxio-fuse     -v ~/tmp/mnt:/mnt:rshared     -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost"   --privileged  --cap-add SYS_ADMIN     --device /dev/fuse     alluxio/alluxio-fuse fuse
mkdir: cannot create directory '/mnt/alluxio-fuse': Permission denied
umount: /mnt/alluxio-fuse: No such file or directory
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes"
2021-02-10 00:32:34,084 INFO  AlluxioFuse - Alluxio version: 2.4.1-2-58173ca23282447ae6f14ecbeea56fab18a22ba2
2021-02-10 00:32:34,484 INFO  NettyUtils - EPOLL_MODE is available
2021-02-10 00:32:34,915 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=ip-172-31-28-19.ec2.internal, rack=null)
2021-02-10 00:32:35,191 INFO  AlluxioFuseFileSystem - Mount AlluxioFuseFileSystem: mountPoint="/mnt/alluxio-fuse", blocking=true, debug=false, fuseOpts="[-obig_writes, -omax_write=131072, -odirect_io]"
fuse: bad mount point `/mnt/alluxio-fuse': No such file or directory
2021-02-10 00:32:35,197 ERROR AlluxioFuse - Failed to mount /mnt/alluxio-fuse
ru.serce.jnrfuse.FuseException: Unable to mount FS
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:281)
	at alluxio.fuse.AlluxioFuseFileSystem.mount(AlluxioFuseFileSystem.java:968)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:139)
Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:277)
	... 2 more
2021-02-10 00:32:35,199 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
2021-02-10 00:32:35,200 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
```

@cheyang , @madanadit, @jiacheliu3  can you take a look here?

**Comment by peterroelants** [comment]
I've been debugging this and there are two issues at play:

- Filesystem permissions to `/tmp/mnt`.
- Docker capability to mount folders.

See: https://github.com/Alluxio/alluxio/issues/12943#issuecomment-786817860

The following should work:
```
mkdir -p /tmp/mnt
docker run --rm \
    --net=host \
    --name=alluxio-fuse \
    -v /tmp/mnt:/mnt:rshared \
    -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost" \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --privileged \
    alluxio/alluxio-fuse fuse
 ```
 
 Alternatively `--privileged` can be replaced with `--security-opt apparmor:unconfined`

**Comment by apc999** [comment]
Thanks @peterroelants  for the investigation! I will create a documentation fix to address this issue.
