### ISSUE TITLE
Unable to create an UnderFileSystem instance for path: hdfs

### ISSUE THREAD

**Issue by loovia** [Alluxio/alluxio#12742]
**Alluxio Version:**
2.4.1-1

**Describe the bug**
mount hdfs fail.

I had build client jar files by running mvn command for the 2.6.0 version. And the 2.6 hdfs ufs exist under the `${ALLUXIO_HOME}/lib/` directory.

Now I mount hdfs to alluxio and return an error. Here is my command:
```
./alluxio fs mount \
  --option alluxio.underfs.version=2.6 \
  --option alluxio.underfs.hdfs.configuration=/opt/alluxio/alluxio-2.4.1-1/conf/cdh5.16.1/core-site.xml:/opt/alluxio/alluxio-2.4.1-1/conf/cdh5.16.1/hdfs-site.xml \
  /hdfs/cdh5 hdfs://namenode:8020/data/alluxio
```
Error log is:
```
java.lang.IllegalArgumentException: Unable to create an UnderFileSystem instance for path: hdfs://namenode:8020/data/alluxio
        at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:122)
        at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:128)
        at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:167)
        at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:60)
        at alluxio.master.file.DefaultFileSystemMaster.prepareForMount(DefaultFileSystemMaster.java:2699)
        at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:2863)
        at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:2824)
        at alluxio.master.file.DefaultFileSystemMaster.mount(DefaultFileSystemMaster.java:2799)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$mount$10(FileSystemMasterClientServiceHandler.java:258)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
        at alluxio.RpcUtils.call(RpcUtils.java:78)
        at alluxio.RpcUtils.call(RpcUtils.java:53)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.mount(FileSystemMasterClientServiceHandler.java:257)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2263)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1356)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
        Suppressed: java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration
                at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<init>(DefaultMetricsSystem.java:38)
                at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<clinit>(DefaultMetricsSystem.java:36)
                at org.apache.hadoop.security.UserGroupInformation$UgiMetrics.create(UserGroupInformation.java:108)
                at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:224)
                at alluxio.underfs.hdfs.HdfsUnderFileSystem.<init>(HdfsUnderFileSystem.java:150)
                at alluxio.underfs.hdfs.HdfsUnderFileSystem.createInstance(HdfsUnderFileSystem.java:108)
                at alluxio.underfs.hdfs.HdfsUnderFileSystemFactory.create(HdfsUnderFileSystemFactory.java:43)
                at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:107)
                ... 30 more
        Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration.Configuration
                at java.lang.ClassLoader.findClass(ClassLoader.java:530)
                at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.findClass(ExtensionsClassLoader.java:41)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.loadClass(ExtensionsClassLoader.java:51)
                at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                ... 38 more
```
I add commons-configuration-1.6.jar to `${ALLUXIO_HOME}/lib/` directory,  still return error.

**Comment by loovia** [comment]
Does anyone help me?

**Comment by loovia** [comment]
I execute command `grep org.apache.commons.configuration.Configuration -r . ` in soure code path, and return nothing. I can't figure out where this package is being used.

**Comment by loovia** [comment]
Does alluxio support hadoop2.6?

**Comment by liupan664021** [comment]
Do you build the Alluxio server with the hadoop version 2.6 ? I think only the client built with the version 2.6 may be not enough. A mount operation will be handled by the master.

**Comment by loovia** [comment]
> Do you build the Alluxio server with the hadoop version 2.6 ?
Yes. Mounted Successfully by use `--option alluxio.underfs.version=2.7` , but my hadoop version is 2.6......

**Comment by apc999** [comment]
@loovia   
By default, Alluxio distribution **does not** come with hadoop 2.6, (but with 2.2, 2.7, 2.8 and 3.2)
You can
(1) build Alluxio hdfs ufs 2.6 (checking my answer at
https://github.com/Alluxio/alluxio/issues/12809)
(2) using prebuild Alluxio hdfs 2.7 or 2.8 (`--option alluxio.underfs.version=2.7` like you did),
this should still be safe as hadoop client 2.7 should be backward-compatible with 2.6.

Feel free to re-open this issue if you have more questions.
