### ISSUE TITLE
Can not find objects after mount ceph s3 bucket to alluxio path

### ISSUE THREAD

**Issue by gtarcoder** [Alluxio/alluxio#12778]
**Alluxio Version:**
What version of Alluxio are you using?
v2.4 stable

**Describe the bug**
I started alluxio on local machine following this guide https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-Locally.html, and I mount a ceph s3 bucket to alluxio path following this guide: https://docs.alluxio.io/ee/user/stable/en/compute/Tensorflow.html , 
```
./bin/alluxio fs mount /training-data/bmlx_train_data s3://mlpipeline-test/ -Dalluxio.underfs.s3.inherit.acl=false    
-Daws.accessKeyId=xxx   -Daws.secretKey=xxx -Dalluxio.underfs.s3.endpoint=http://xxx     
-Dalluxio.underfs.s3.disable.dns.buckets=true   
```
Actually, there are some objects in my bucket, s3://mlpipeline-test and I can access those files via aws cli. But I can not find those files under alluxio path by command ./bin/alluxio fs ls /training-data/bmlx_train_data

So I am wondering what is wrong here.

**Comment by gtarcoder** [comment]
@haoyuan could you please give any suggestion for this issue?

**Comment by gtarcoder** [comment]
and here is the alluxio fs mount  status: 
![image](https://user-images.githubusercontent.com/11898942/106459138-6117fc80-64cc-11eb-991f-77bf3fa186f0.png)

**Comment by apc999** [comment]
@gtarcoder  -1B simply means unavailable in your case. We will create a PR to fix it. @maobaolong , can you get the display fixed (e.g., instead of -1B, showing  unavailable)?

Meanwhile, when you run `./bin/alluxio fs ls /training-data/bmlx_train_data`, can you check your master log (located at `ALLUXIO_ROOT/logs/master.log`) and see if there is any error returned?

**Comment by gtarcoder** [comment]
> @gtarcoder -1B simply means unavailable in your case. We will create a PR to fix it. @maobaolong , can you get the display fixed (e.g., instead of -1B, showing unavailable)?
> 
> Meanwhile, when you run `./bin/alluxio fs ls /training-data/bmlx_train_data`, can you check your master log (located at `ALLUXIO_ROOT/logs/master.log`) and see if there is any error returned?

@apc999  , when I run ./bin/alluxio fs ls /training-data/bmlx_train_data , nothing appended to master.log and master.out.

**Comment by apc999** [comment]
try to run the following command first to enable DEBUG level  logging for RPCs,
```
./bin/alluxio logLevel \
--logName=alluxio.master.file.FileSystemMasterClientServiceHandler \
--target master --level=DEBUG
```

Then run `./bin/alluxio fs ls /training-data/bmlx_train_data` and check master.log again?

**Comment by gtarcoder** [comment]
![image](https://user-images.githubusercontent.com/11898942/106690037-fcfc5200-660b-11eb-865d-e5ed73f5eab6.png)

**Comment by gtarcoder** [comment]
I am wondering if the alluxio will sync meta information after mount ceph s3 automatically? if not, is there a command to sync meta information manually?

**Comment by gtarcoder** [comment]
Here is the output when I try to run `bin/alluxio fs chown xxx:xxx -R /training-data`,
```
2021-02-04 14:32:19,080 INFO  ExtensionFactoryRegistry - Loading core jars from /data1/sunkaicheng/alluxio-2.0.0/lib
2021-02-04 14:32:19,091 INFO  ExtensionFactoryRegistry - Loading extension jars from /data1/sunkaicheng/alluxio-2.0.0/extensions
2021-02-04 14:32:19,461 INFO  MountTable - Mounting s3://mlpipeline-test/ at /training-data
2021-02-04 14:33:04,639 ERROR S3AUnderFileSystem - Failed to create object: /
com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: tx0000000000000089162c7-00601
b9520-88727a-default; S3 Extended Request ID: 88727a-default-default), S3 Extended Request ID: 88727a-default-default
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1738)
        at alluxio.underfs.s3a.S3AUnderFileSystem.createEmptyObject(S3AUnderFileSystem.java:301)
        at alluxio.underfs.ObjectUnderFileSystem.mkdirsInternal(ObjectUnderFileSystem.java:1075)
        at alluxio.underfs.ObjectUnderFileSystem.getObjectListingChunkForPath(ObjectUnderFileSystem.java:943)
        at alluxio.underfs.ObjectUnderFileSystem.listInternal(ObjectUnderFileSystem.java:967)
        at alluxio.underfs.ObjectUnderFileSystem.listStatus(ObjectUnderFileSystem.java:605)
        at alluxio.underfs.UnderFileSystemWithLogging$32.call(UnderFileSystemWithLogging.java:584)
        at alluxio.underfs.UnderFileSystemWithLogging$32.call(UnderFileSystemWithLogging.java:581)
        at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:949)
        at alluxio.underfs.UnderFileSystemWithLogging.listStatus(UnderFileSystemWithLogging.java:581)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$27.execute(ManagedBlockingUfsForwarder.java:374)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$27.execute(ManagedBlockingUfsForwarder.java:371)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.block(ManagedBlockingUfsForwarder.java:596)
        at alluxio.concurrent.jsr.ForkJoinPool.managedBlock(ForkJoinPool.java:1004)
        at alluxio.concurrent.ForkJoinPoolHelper.safeManagedBlock(ForkJoinPoolHelper.java:41)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.get(ManagedBlockingUfsForwarder.java:582)
        at alluxio.concurrent.ManagedBlockingUfsForwarder.listStatus(ManagedBlockingUfsForwarder.java:376)
        at alluxio.master.file.DefaultFileSystemMaster.populateStatusCache(DefaultFileSystemMaster.java:3247)
        at alluxio.master.file.DefaultFileSystemMaster.syncMetadata(DefaultFileSystemMaster.java:3225)
        at alluxio.master.file.DefaultFileSystemMaster.setAttribute(DefaultFileSystemMaster.java:3046)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$setAttribute$16(FileSystemMasterClientServiceHandler.java:389)
...skipping...
        at alluxio.underfs.UnderFileSystemWithLogging.listStatus(UnderFileSystemWithLogging.java:581)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$27.execute(ManagedBlockingUfsForwarder.java:374)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$27.execute(ManagedBlockingUfsForwarder.java:371)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.block(ManagedBlockingUfsForwarder.java:596)
        at alluxio.concurrent.jsr.ForkJoinPool.managedBlock(ForkJoinPool.java:1004)
        at alluxio.concurrent.ForkJoinPoolHelper.safeManagedBlock(ForkJoinPoolHelper.java:41)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.get(ManagedBlockingUfsForwarder.java:582)
        at alluxio.concurrent.ManagedBlockingUfsForwarder.listStatus(ManagedBlockingUfsForwarder.java:376)
        at alluxio.master.file.DefaultFileSystemMaster.populateStatusCache(DefaultFileSystemMaster.java:3247)
        at alluxio.master.file.DefaultFileSystemMaster.syncMetadata(DefaultFileSystemMaster.java:3225)
        at alluxio.master.file.DefaultFileSystemMaster.setAttribute(DefaultFileSystemMaster.java:3046)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$setAttribute$16(FileSystemMasterClientServiceHandler.java:389)
        at alluxio.RpcUtils.call(RpcUtils.java:193)
        at alluxio.RpcUtils.call(RpcUtils.java:166)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.setAttribute(FileSystemMasterClientServiceHandler.java:388)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2122)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:52)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1355)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
```

@apc999  any idea on this error?

**Comment by apc999** [comment]
> I am wondering if the alluxio will sync meta information after mount ceph s3 automatically? if not, is there a command to sync meta information manually? @apc999

sync is triggered based on your policy, check it out https://docs.alluxio.io/os/user/edge/en/core-services/Unified-Namespace.html#relationship-between-alluxio-and-ufs-namespace . By default it is synced on the first time your application reference a UFS (s3 here) address

**Comment by calvinjia** [comment]
@gtarcoder It looks like the signature version doesn't match. Do you know if your Ceph S3 is expecting V2 or V4? You can look into the alluxio property - `alluxio.underfs.s3.signer.algorithm` and

**Comment by gtarcoder** [comment]
> @gtarcoder It looks like the signature version doesn't match. Do you know if your Ceph S3 is expecting V2 or V4? You can look into the alluxio property - `alluxio.underfs.s3.signer.algorithm` and

yes, after I set `alluxio.underfs.s3.signer.algorithm=S3SignerType`,  list object is ok now. But another issue occurs, that is if the file count under the mounted directory is less than 1000, ls command works ok; but if file count is larger than 1000, the ls command will be hanged.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
