### ISSUE TITLE
ERROR AlluxioFuse - Failed to mount /mnt/alluxio-fuse when following documentation

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#12943]
**Alluxio Version:**
alluxio version 2.4.1-2

**Describe the bug**
When trying to [Enable POSIX API access](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html#enable-posix-api-access) I get a `ERROR AlluxioFuse - Failed to mount /mnt/alluxio-fuse` error when running the alluxio-fuse container:
```
umount: /mnt/alluxio-fuse: not mounted
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes"
2021-02-25 19:41:46,173 INFO  AlluxioFuse - Alluxio version: 2.4.1-2-58173ca23282447ae6f14ecbeea56fab18a22ba2
2021-02-25 19:41:46,512 INFO  NettyUtils - EPOLL_MODE is available
2021-02-25 19:41:46,749 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.0.168, rack=null)
2021-02-25 19:41:46,907 INFO  AlluxioFuseFileSystem - Mount AlluxioFuseFileSystem: mountPoint="/mnt/alluxio-fuse", blocking=true, debug=false, fuseOpts="[-obig_writes, -omax_write=131072, -odirect_io]"
fuse: mount failed: Permission denied
2021-02-25 19:41:46,911 ERROR AlluxioFuse - Failed to mount /mnt/alluxio-fuse
ru.serce.jnrfuse.FuseException: Unable to mount FS
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:281)
	at alluxio.fuse.AlluxioFuseFileSystem.mount(AlluxioFuseFileSystem.java:968)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:139)
Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:277)
	... 2 more
2021-02-25 19:41:46,912 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
2021-02-25 19:41:46,912 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
```

**To Reproduce**
Follow the ["Deploy Alluxio on Docker"](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html) tutorial:
```
❯ mkdir -p /tmp/alluxio_ufs
❯ docker run -d --rm \
    --net=host \
    --name=alluxio-master \
    -v /tmp/alluxio_ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS=" \
       -Dalluxio.master.hostname=localhost \
       -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage" \
    alluxio/alluxio master
5575befe47d4c6fa099480b9f50201599fdeea54145e564a158a90fcaa22b5a7
❯ docker run -d --rm \
    --net=host \
    --name=alluxio-worker \
    --shm-size=1G \
    -v /tmp/alluxio_ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS=" \
       -Dalluxio.worker.ramdisk.size=1G \
       -Dalluxio.master.hostname=localhost" \
    alluxio/alluxio worker
68f41d6b28a2feea4220ceb3b20dd9efe5ecf4820b23b3f2098a74a5dbe32e6e
❯ mkdir /tmp/mnt
❯ docker run --rm \
    --net=host \
    --name=alluxio-fuse \
    -v /tmp/mnt:/mnt:rshared \
    -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost" \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    alluxio/alluxio-fuse fuse
umount: /mnt/alluxio-fuse: not mounted
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes"
2021-02-25 19:41:46,173 INFO  AlluxioFuse - Alluxio version: 2.4.1-2-58173ca23282447ae6f14ecbeea56fab18a22ba2
2021-02-25 19:41:46,512 INFO  NettyUtils - EPOLL_MODE is available
2021-02-25 19:41:46,749 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.0.168, rack=null)
2021-02-25 19:41:46,907 INFO  AlluxioFuseFileSystem - Mount AlluxioFuseFileSystem: mountPoint="/mnt/alluxio-fuse", blocking=true, debug=false, fuseOpts="[-obig_writes, -omax_write=131072, -odirect_io]"
fuse: mount failed: Permission denied
2021-02-25 19:41:46,911 ERROR AlluxioFuse - Failed to mount /mnt/alluxio-fuse
ru.serce.jnrfuse.FuseException: Unable to mount FS
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:281)
	at alluxio.fuse.AlluxioFuseFileSystem.mount(AlluxioFuseFileSystem.java:968)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:139)
Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:277)
	... 2 more
2021-02-25 19:41:46,912 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
2021-02-25 19:41:46,912 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
```

**Expected behavior**
`alluxio/alluxio-fuse` works according to documentation without error.

**Urgency**
Relatively high: I cannot get the fuse mount to work in docker.

**Additional context**
Docker images downloaded:
```
REPOSITORY             TAG       IMAGE ID       CREATED       SIZE
alluxio/alluxio-fuse   latest    bdbbdad27def   4 weeks ago   1.75GB
alluxio/alluxio        latest    c1c6c4c8ac1d   4 weeks ago   1.77GB
```

- I [verified the cluster](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html#verify-the-cluster) by running the tests `alluxio runTests` in the worker (they all passed)
- Making sure that `/tmp/mnt` exists with `mkdir -p /tmp/mnt` before running or having the folder not exist does not seem to make a difference and produces the same error.
- `alluxio-fuse` is created in `/tmp/mnt` by the crashing container.
- My system: `Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64`
- Docker version 20.10.3, build 48d30b5
- `fuse.conf` on my host running the containers:
  ```
  ❯ cat /etc/fuse.conf
  # /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)
  
  # Set the maximum number of FUSE mounts allowed to non-root users.
  # The default is 1000.
  #mount_max = 1000
  
  # Allow non-root users to specify the allow_other or allow_root mount options.
  user_allow_other
  ```
- Slack thread with seemingly similar issue: https://alluxio-community.slack.com/archives/CEXGGUBDK/p1610479439491600

**Comment by peterroelants** [comment]
Issue https://github.com/Alluxio/alluxio/issues/12712 seemed related so I tried adding the `--privileged` flag, however I seem to be getting the same error. See logs at [fuse_privileged.log](https://github.com/Alluxio/alluxio/files/6047900/fuse_privileged.log)

**Comment by peterroelants** [comment]
It seems to be both a security and user problem. Adding both `--security-opt apparmor:unconfined` and `--user='root'` to the `run` command seems to fix the problem.

E.g.
```
docker run --rm \
    --net=host \
    --name=alluxio-fuse \
    -v /tmp/mnt:/mnt:rshared \
    -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost" \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --security-opt apparmor:unconfined \
    --user='root' \
    alluxio/alluxio-fuse fuse
```

results in:
```
umount: /mnt/alluxio-fuse: not mounted
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes"
2021-02-26 12:45:30,639 INFO  AlluxioFuse - Alluxio version: 2.4.1-2-58173ca23282447ae6f14ecbeea56fab18a22ba2
2021-02-26 12:45:30,927 INFO  NettyUtils - EPOLL_MODE is available
2021-02-26 12:45:31,192 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.0.168, rack=null)
2021-02-26 12:45:31,356 INFO  AlluxioFuseFileSystem - Mount AlluxioFuseFileSystem: mountPoint="/mnt/alluxio-fuse", blocking=true, debug=false, fuseOpts="[-obig_writes, -omax_write=131072, -odirect_io]"
fuse: max_idle_threads: 10
fuse: max_idle_threads: 10
```

**Comment by peterroelants** [comment]
I've been debugging a bit and have found the following:

#### Permission to create folder

If I just run:
```
docker run --rm \
    --net=host \
    --name=alluxio-fuse \
    -v /tmp/mnt:/mnt:rshared \
    -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost" \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    alluxio/alluxio-fuse fuse
```
Without creating `/tmp/mnt` first I get:
```
mkdir: cannot create directory '/mnt/alluxio-fuse': Permission denied
umount: /mnt/alluxio-fuse: No such file or directory
...
```

We can fix this by either:
- Create the folder to mount locally `mkdir -p /tmp/mnt`, or,
- Running as `root` by adding `--user='root'` to our docker run command

#### Permission to mount

After fixing the previous issue we still see:
```
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes"
2021-02-26 18:13:47,170 INFO  AlluxioFuse - Alluxio version: 2.4.1-2-58173ca23282447ae6f14ecbeea56fab18a22ba2
2021-02-26 18:13:47,456 INFO  NettyUtils - EPOLL_MODE is available
2021-02-26 18:13:47,718 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.0.168, rack=null)
2021-02-26 18:13:47,874 INFO  AlluxioFuseFileSystem - Mount AlluxioFuseFileSystem: mountPoint="/mnt/alluxio-fuse", blocking=true, debug=false, fuseOpts="[-obig_writes, -omax_write=131072, -odirect_io]"
fuse: mount failed: Permission denied
2021-02-26 18:13:47,878 ERROR AlluxioFuse - Failed to mount /mnt/alluxio-fuse
ru.serce.jnrfuse.FuseException: Unable to mount FS
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:281)
	at alluxio.fuse.AlluxioFuseFileSystem.mount(AlluxioFuseFileSystem.java:968)
	at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:139)
Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:277)
	... 2 more
2021-02-26 18:13:47,878 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
2021-02-26 18:13:47,879 INFO  AlluxioFuseFileSystem - Umount AlluxioFuseFileSystem
```

This can be fixed by adding `--security-opt apparmor:unconfined` to the options.

**Comment by peterroelants** [comment]
This works for me:
```
mkdir -p /tmp/mnt
docker run --rm \
    --net=host \
    --name=alluxio-fuse \
    -v /tmp/mnt:/mnt:rshared \
    -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost" \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --security-opt apparmor:unconfined \
    alluxio/alluxio-fuse fuse
```

With output:
```
umount: /mnt/alluxio-fuse: not mounted
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes"
2021-02-26 18:28:30,390 INFO  AlluxioFuse - Alluxio version: 2.4.1-2-58173ca23282447ae6f14ecbeea56fab18a22ba2
2021-02-26 18:28:30,680 INFO  NettyUtils - EPOLL_MODE is available
2021-02-26 18:28:30,922 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=192.168.0.168, rack=null)
2021-02-26 18:28:31,080 INFO  AlluxioFuseFileSystem - Mount AlluxioFuseFileSystem: mountPoint="/mnt/alluxio-fuse", blocking=true, debug=false, fuseOpts="[-obig_writes, -omax_write=131072, -odirect_io]"
fuse: max_idle_threads: 10
fuse: max_idle_threads: 10
```

**Comment by peterroelants** [comment]
Created a PR at: https://github.com/Alluxio/alluxio/pull/13053

**Comment by peterroelants** [comment]
> I've been debugging a bit and have found the following:
> 
> #### Permission to create folder
> If I just run:
> 
> ```
> docker run --rm \
>     --net=host \
>     --name=alluxio-fuse \
>     -v /tmp/mnt:/mnt:rshared \
>     -e "ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=localhost" \
>     --cap-add SYS_ADMIN \
>     --device /dev/fuse \
>     alluxio/alluxio-fuse fuse
> ```
> 
> Without creating `/tmp/mnt` first I get:
> 
> ```
> mkdir: cannot create directory '/mnt/alluxio-fuse': Permission denied
> umount: /mnt/alluxio-fuse: No such file or directory
> ...
> ```

Fix this by https://github.com/Alluxio/alluxio/pull/13074
