### ISSUE TITLE
ERROR: Master exits abnormally when recovering from backup

### ISSUE THREAD

**Issue by smallx** [Alluxio/alluxio#12959]
**Alluxio Version:**
2.2

**Describe the bug**
Backup succeeded. However, master exits abnormally when recovering from this backup file. Other backup files don't have this problem.

**To Reproduce**
It's not yet clear.

**Urgency**
Non urgent.

**Additional context**
Here are some logs:

```
2021-02-24 14:23:59,167 ERROR ProcessUtils - Uncaught exception while running Alluxio master @xxx:19998, stopping it and exiting. Exception "java.lang.RuntimeException: java.io.IOException: java.util.NoSuchElementException: No value present", Root Cause "java.util.NoSuchElementException: No value present"
java.lang.RuntimeException: java.io.IOException: java.util.NoSuchElementException: No value present
        at alluxio.master.AlluxioMasterProcess.startMasters(AlluxioMasterProcess.java:222)
        at alluxio.master.FaultTolerantAlluxioMasterProcess.gainPrimacy(FaultTolerantAlluxioMasterProcess.java:127)
        at alluxio.master.FaultTolerantAlluxioMasterProcess.start(FaultTolerantAlluxioMasterProcess.java:90)
        at alluxio.ProcessUtils.run(ProcessUtils.java:35)
        at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)
Caused by: java.io.IOException: java.util.NoSuchElementException: No value present
        at alluxio.master.BackupManager.safeWaitTasks(BackupManager.java:347)
        at alluxio.master.BackupManager.initFromBackup(BackupManager.java:307)
        at alluxio.master.AlluxioMasterProcess.initFromBackup(AlluxioMasterProcess.java:193)
        at alluxio.master.AlluxioMasterProcess.startMasters(AlluxioMasterProcess.java:209)
        ... 4 more
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at alluxio.master.file.meta.InodeTreePersistentState.updateTimestampsAndChildCount(InodeTreePersistentState.java:679)
        at alluxio.master.file.meta.InodeTreePersistentState.applyCreateInode(InodeTreePersistentState.java:620)
        at alluxio.master.file.meta.InodeTreePersistentState.applyCreateDirectory(InodeTreePersistentState.java:395)
        at alluxio.master.file.meta.InodeTreePersistentState.processJournalEntry(InodeTreePersistentState.java:741)
        at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:31)
        at alluxio.master.journal.JournaledGroup.processJournalEntry(JournaledGroup.java:56)
        at alluxio.master.journal.Journaled.applyAndJournal(Journaled.java:50)
        at alluxio.master.journal.DelegatingJournaled.applyAndJournal(DelegatingJournaled.java:41)
        at alluxio.master.BackupManager.lambda$initFromBackup$46(BackupManager.java:286)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-02-24 14:23:59,168 INFO  AbstractMaster - UdfManagerMaster: Stopped secondary master.
2021-02-24 14:23:59,168 INFO  AbstractMaster - MetaMaster: Stopped secondary master.
2021-02-24 14:23:59,168 INFO  AbstractMaster - FileSystemMaster: Stopped secondary master.
```

```
2021-02-25 23:23:11,364 ERROR BufferedJournalApplier - Journal replay error: Failed to apply journal entry to master FileSystemMaster. Entry: sequence_number: 39843466
inode_file {
  id: 1036653791543295
  parent_id: 1034634133530774
  name: "main_spark.py"
  persistence_state: "PERSISTED"
  pinned: false
  creation_time_ms: 1609294076620
  last_modification_time_ms: 1606461568000
  block_size_bytes: 268435456
  length: 4598
  completed: true
  cacheable: true
  blocks: 1036653774766080
  ttl: -1
  ttlAction: DELETE
  ufs_fingerprint: "TYPE|FILE UFS|hdfs OWNER|xxx GROUP|xxx MODE|511 CONTENT_HASH|(len:4598,_modtime:1606461568000) "
  acl {
    owningUser: "xxx"
    owningGroup: "xxx"
    userActions {
      name: ""
      actions {
        actions: READ
        actions: WRITE
        actions: EXECUTE
      }
    }
    groupActions {
      name: ""
      actions {
        actions: READ
        actions: WRITE
        actions: EXECUTE
      }
    }
    otherActions {
      actions: READ
      actions: WRITE
      actions: EXECUTE
    }
    isDefault: false
    isEmpty: false
  }
  replication_max: -1
  replication_min: 0
  persist_job_id: -1
  temp_ufs_path: ""
  replication_durable: 1
  last_access_time_ms: 1612116239546
}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at alluxio.master.file.meta.InodeTreePersistentState.updateTimestampsAndChildCount(InodeTreePersistentState.java:679)
        at alluxio.master.file.meta.InodeTreePersistentState.applyCreateInode(InodeTreePersistentState.java:620)
        at alluxio.master.file.meta.InodeTreePersistentState.applyCreateFile(InodeTreePersistentState.java:399)
        at alluxio.master.file.meta.InodeTreePersistentState.processJournalEntry(InodeTreePersistentState.java:743)
        at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:31)
        at alluxio.master.journal.JournaledGroup.processJournalEntry(JournaledGroup.java:56)
        at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:31)
        at alluxio.master.journal.raft.BufferedJournalApplier.applyToMaster(BufferedJournalApplier.java:239)
        at alluxio.master.journal.raft.BufferedJournalApplier.processJournalEntry(BufferedJournalApplier.java:110)
        at alluxio.master.journal.raft.JournalStateMachine.applySingleEntry(JournalStateMachine.java:170)
        at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:142)
        at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:132)
        at alluxio.master.journal.raft.JournalStateMachine.applyJournalEntryCommand(JournalStateMachine.java:109)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.atomix.copycat.server.StateMachine.lambda$wrapVoidMethod$0(StateMachine.java:353)
        at io.atomix.copycat.server.state.ServerStateMachineExecutor.lambda$register$1(ServerStateMachineExecutor.java:244)
        at io.atomix.copycat.server.state.ServerStateMachineExecutor.executeOperation(ServerStateMachineExecutor.java:149)
        at io.atomix.copycat.server.state.ServerStateMachine.executeCommand(ServerStateMachine.java:909)
        at io.atomix.copycat.server.state.ServerStateMachine.lambda$apply$19(ServerStateMachine.java:847)
        at io.atomix.catalyst.concurrent.Runnables.lambda$logFailure$0(Runnables.java:20)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by apc999** [comment]
@smallx  is this PR https://github.com/Alluxio/alluxio/pull/12958 supposed to solve this issue?

**Comment by calvinjia** [comment]
@smallx Was there an issue when writing the backup, or do you observe this happening every few backups (ie. the backup write process is creating corrupted backups)?

**Comment by smallx** [comment]
@calvinjia 
Yes, we have some backup files with this problem, others don't.
The cause of the backup file corruption has not been found, but it has been worked around by https://github.com/Alluxio/alluxio/pull/12958.
Now, HA masters can be recovered from backup file normally.

**Comment by smallx** [comment]
> @smallx Was there an issue when writing the backup, or do you observe this happening every few backups (ie. the backup write process is creating corrupted backups)?

@calvinjia 
Yes, we have some backup files with this problem, others don't.
The cause of the backup file corruption has not been found, but it has been worked around by https://github.com/Alluxio/alluxio/pull/12958.
Now, HA masters can be recovered from backup file normally.

**Comment by smallx** [comment]
> @smallx Was there an issue when writing the backup, or do you observe this happening every few backups (ie. the backup write process is creating corrupted backups)?

@calvinjia 
Yes, we have some backup files with this problem, others don't.
The cause of the backup file corruption has not been found, but it has been worked around by https://github.com/Alluxio/alluxio/pull/12958.
Now, HA masters can be recovered from backup file normally.

**Comment by smallx** [comment]
> @smallx is this PR #12958 supposed to solve this issue?

@apc999 Yes. To workaround this problem.
