### ISSUE TITLE
alluxio fuse read data error

### ISSUE THREAD

**Issue by wonderisland** [Alluxio/alluxio#13050]
先通过alluxio fuse mount alluxio的目录， 然后上层通过go read file， alluxio fuse进程显示异常如下
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at alluxio.client.file.AlluxioFileInStream.triggerAsyncCaching(AlluxioFileInStream.java:389)
        at alluxio.client.file.AlluxioFileInStream.closeBlockInStream(AlluxioFileInStream.java:381)
        at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:198)
        at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:336)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:317)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
        at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:317)
        at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:150)
2021-03-12 04:22:39,116 ERROR AlluxioJniFuseFileSystem - Failed to read, path: /data/0.5G_1.txt size: 4096 offset: 536866816

using jnr fuse， also find the error
2021-03-12 08:36:48,521 ERROR AlluxioFuseFileSystem - Failed to read file=/data/0.5G_9.txt, offset=536862720, size=8192
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at alluxio.client.file.AlluxioFileInStream.triggerAsyncCaching(AlluxioFileInStream.java:389)
        at alluxio.client.file.AlluxioFileInStream.closeBlockInStream(AlluxioFileInStream.java:381)
        at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:198)
        at alluxio.fuse.AlluxioFuseFileSystem.readInternal(AlluxioFuseFileSystem.java:624)
        at alluxio.fuse.AlluxioFuseFileSystem.lambda$read$7(AlluxioFuseFileSystem.java:596)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:245)
        at alluxio.fuse.AlluxioFuseFileSystem.read(AlluxioFuseFileSystem.java:596)
        at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$3(AbstractFuseFS.java:135)
        at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$9.invoke(Unknown Source)
unique: 2465256, opcode: FLUSH (25), nodeid: 594, insize: 64, pid: 777281

到文件末尾必现：
tail -n 100  /data/benchmark/data/0.5G_9.txt 
tail: error reading '/data/benchmark/data/0.5G_9.txt': Bad message

**Comment by cheyang** [comment]
Please add commit id？ which branch did you reproduce this issue?

**Comment by xieydd** [comment]
Reprodece env:
branch: origin/release-2.4.1-2
commit id: bfff8c6881e5cb045fd1d84c59acba26078bb4d9
File size 512 Mb

**Comment by apc999** [comment]
@xieydd what is the Alluxio block size you are using?
`bin/alluxio getConf alluxio.user.block.size.bytes.default`

**Comment by apc999** [comment]
can you also run `bin/alluxio fs stat /path/to//data/benchmark/data/0.5G_9.txt`  using Alluxio CLI?
I want to check how many blocks this file has in Alluxio land

**Comment by xieydd** [comment]
@apc999  Log in here:
```
bash-4.4# alluxio fs stat /slice1/data/0.5G_307.txt
/slice1/data/0.5G_307.txt is a file path.
FileInfo{fileId=9881780223, fileIdentifier=null, name=0.5G_307.txt, path=/slice1/data/0.5G_307.txt, ufsPath=cosn://test-1251707795/data/0.5G_307.txt, length=536870912, blockSizeBytes=134217728, creationTimeMs=1615717317953, completed=true, folder=false, pinned=false, pinnedlocation=[], cacheable=true, persisted=true, blockIds=[9865003008, 9865003009, 9865003010, 9865003011], inMemoryPercentage=0, lastModificationTimesMs=1615718295957, ttl=-1, lastAccessTimesMs=1615453514000, ttlAction=FREE, owner=root, group=root, mode=438, persistenceState=PERSISTED, mountPoint=false, replicationMax=1, replicationMin=0, fileBlockInfos=[FileBlockInfo{blockInfo=BlockInfo{id=9865003008, length=134217728, locations=[]}, offset=0, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=9865003009, length=134217728, locations=[]}, offset=134217728, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=9865003010, length=134217728, locations=[]}, offset=268435456, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=9865003011, length=134217728, locations=[]}, offset=402653184, ufsLocations=[]}], mountId=7269158556764111209, inAlluxioPercentage=0, ufsFingerprint=TYPE|FILE UFS|hdfs OWNER|root GROUP|root MODE|438 CONTENT_HASH|(len:536870912,_modtime:1615453514000) , acl=user::rw-,group::rw-,other::rw-, defaultAcl=}
Containing the following blocks:
BlockInfo{id=9865003008, length=134217728, locations=[]}
BlockInfo{id=9865003009, length=134217728, locations=[]}
BlockInfo{id=9865003010, length=134217728, locations=[]}
BlockInfo{id=9865003011, length=134217728, locations=[]}
bash-4.4#
```

I find when i run dataload job in fluid, not all data loading correctly, for example log show 0.5G_307.txt is full loaded, but in master show loader percent is 0;
```
bash-4.4# alluxio fs ls /slice1/data/ | grep /slice1/data/0.5G_307.txt
      536870912       PERSISTED 03-14-2021 10:38:15:957   0% /slice1/data/0.5G_307.txt

# In dataload.log 
/slice1/data/0.5G_307.txt is already fully loaded in Alluxio
```

This is dataload log:  [dataload.log](https://github.com/Alluxio/alluxio/files/6136542/dataload.log)


When i read full loaded data in alluxio via `tail -n 100 ` will be no error, but when i read 0% loaded or other not 100% loaded will cause the error in this issue.

**Comment by xieydd** [comment]
@alluxio-bot reopen the issue. The error is almost same after the patch to version 2.4.1-2

**Comment by apc999** [comment]
@xieydd  can you post the error message again?

**Comment by apc999** [comment]
and I will release 2.5.0-1 and make an another try?

**Comment by xieydd** [comment]
@apc999 This is the fuse pod log, is it helpful. [new-fuse.log](https://github.com/Alluxio/alluxio/files/6186353/new-fuse.log)

**Comment by xieydd** [comment]
> and I will release 2.5.0-1 and make an another try?

2.5.0-1 release will contain the optimization in release-2.4.1-2? If yes, i will make a try : )

**Comment by xieydd** [comment]
@apc999 @cheyang release-2.5.0-1 doesn't have this error.

**Comment by apc999** [comment]
same issue of https://github.com/Alluxio/alluxio/issues/13828
this should be addressed by https://github.com/Alluxio/alluxio/pull/13845
