### ISSUE TITLE
Cannot start worker after shrinking the storage size

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#13071]
**Alluxio Version:**
2.5

**Describe the bug**
If I have a worker that I've been using, then I shrink the tiered storage, I may not be able to start it. The worker scans the tiered storage and finds more than its capacity, and does not know what to do other than crashing. An example of error looks like below:
```
2021-03-11 06:51:34,147 INFO NettyUtils - EPOLL_MODE is available
2021-03-11 06:51:34,445 INFO TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=100.89.9.216, rack=null)
2021-03-11 06:51:34,602 INFO BlockWorkerFactory - Creating alluxio.worker.block.BlockWorker
2021-03-11 06:51:35,706 ERROR AlluxioWorker - Fatal error: Failed to create worker process
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: alluxio.exception.WorkerOutOfSpaceException: blockId 241636068032512 is 134217728 bytes, but only 60148024 bytes available in HDD
at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:181)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:46)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:38)
at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:72)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: alluxio.exception.WorkerOutOfSpaceException: blockId 241636068032512 is 134217728 bytes, but only 60148024 bytes available in HDD
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:592)
at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:554)
at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:122)
... 3 more
Caused by: java.lang.RuntimeException: alluxio.exception.WorkerOutOfSpaceException: blockId 241636068032512 is 134217728 bytes, but only 60148024 bytes available in HDD
at alluxio.worker.block.BlockMetadataManager.<init>(BlockMetadataManager.java:97)
at alluxio.worker.block.BlockMetadataManager.createBlockMetadataManager(BlockMetadataManager.java:114)
at alluxio.worker.block.TieredBlockStore.<init>(TieredBlockStore.java:116)
at alluxio.worker.block.DefaultBlockWorker.<init>(DefaultBlockWorker.java:135)
at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:43)
at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:26)
at alluxio.worker.AlluxioWorkerProcess.lambda$new$0(AlluxioWorkerProcess.java:114)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: alluxio.exception.WorkerOutOfSpaceException: blockId 241636068032512 is 134217728 bytes, but only 60148024 bytes available in HDD
at alluxio.worker.block.meta.StorageDir.addBlockMeta(StorageDir.java:307)
at alluxio.worker.block.meta.StorageDir.initializeMeta(StorageDir.java:153)
at alluxio.worker.block.meta.StorageDir.newStorageDir(StorageDir.java:109)
at alluxio.worker.block.meta.StorageTier.initStorageTier(StorageTier.java:107)
at alluxio.worker.block.meta.StorageTier.newStorageTier(StorageTier.java:200)
at alluxio.worker.block.BlockMetadataManager.<init>(BlockMetadataManager.java:78)
... 10 more
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
The worker should be able to evict or stop, instead of crashing.

**Urgency**
MEDIUM

**Additional context**

**Comment by xieydd** [comment]
I am not shrinking the tiered storage, but i still meet this error in version 2.4.1. @jiacheliu3

**Comment by jiacheliu3** [comment]
> I am not shrinking the tiered storage, but i still meet this error in version 2.4.1. @jiacheliu3
> 
> ```
> 192 2021-03-14 10:23:20,243 ERROR TieredBlockStore - Allocation failure. Options: AllocateOptions{Location=BlockStoreLocation{TierAlias=MEM, DirIndex=0, MediumTy     pe=MEM}, Size=335544320, ForceLocation=true, EvictionAllowed=true, UseReservedSpace=false}. Error:
>  193 alluxio.exception.WorkerOutOfSpaceException: Failed to free 335544320 bytes space at location MEM. Min contiguous requested: 335544320, Min available request     ed: 335544320, Blocks iterated: 0, Blocks removed: 0, Space freed: 0
>  194         at alluxio.worker.block.TieredBlockStore.freeSpaceInternal(TieredBlockStore.java:825)
>  195         at alluxio.worker.block.TieredBlockStore.freeSpace(TieredBlockStore.java:455)
>  196         at alluxio.worker.block.TieredBlockStore.allocateSpace(TieredBlockStore.java:651)
>  197         at alluxio.worker.block.TieredBlockStore.requestSpace(TieredBlockStore.java:318)
>  198         at alluxio.worker.block.DefaultBlockWorker.requestSpace(DefaultBlockWorker.java:483)
>  199         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:132)
>  200         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
>  201         at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
>  202         at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
>  203         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
>  204         at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
>  205         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>  206         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>  207         at java.lang.Thread.run(Thread.java:748)
>  208 2021-03-14 10:23:20,248 ERROR AbstractWriteHandler - Failed to write data for request BlockWriteRequest{id=6945767424, sessionId=2003017542951314771, tier=0,      createUfsBlockOptions=null}
>  209 alluxio.exception.WorkerOutOfSpaceException: Can't reserve more space for block: 6945767424 under session: 2003017542951314771.
>  210         at alluxio.worker.block.TieredBlockStore.requestSpace(TieredBlockStore.java:321)
>  211         at alluxio.worker.block.DefaultBlockWorker.requestSpace(DefaultBlockWorker.java:483)
>  212         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:132)
>  213         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
>  214         at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
>  215         at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
>  216         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
>  217         at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
>  218         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>  219         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>  220         at java.lang.Thread.run(Thread.java:748)
> ```

@xieydd you faced a different issue. The stack traces are different. See https://github.com/Alluxio/alluxio/issues/13086

**Comment by jja725** [comment]
@beinan I think it's still valid? bring this to your attention.
