### ISSUE TITLE
Failed ls a directory with mismatched inode state

### ISSUE THREAD

**Issue by frankobe** [Alluxio/alluxio#13080]
**Alluxio Version:**
2.4.0

**Describe the bug**
`bin/alluxio fs ls/rm/unmount/startSync /mount-hdfs-dir` all be blocked by the following exception

```
java.lang.IllegalStateException: Expected to lock inode part-00655-6d8e1353-1eff-459d-86f9-edc6d76333e4-c000 but locked inode part-00010-a12bf595-b57b-4e5f-bf97-238e4be22a34-c000
        at com.google.common.base.Preconditions.checkState(Preconditions.java:824)
        at alluxio.master.file.meta.SimpleInodeLockList.lockInode(SimpleInodeLockList.java:92)
        at alluxio.master.file.meta.LockedInodePath.traverse(LockedInodePath.java:439)
        at alluxio.master.file.meta.InodeTree.lockInodePath(InodeTree.java:409)
        at alluxio.master.file.meta.InodeTree.lockInodePath(InodeTree.java:391)
        at alluxio.master.file.meta.InodeTree.lockInodePath(InodeTree.java:377)
        at alluxio.master.file.DefaultFileSystemMaster.getFileInfo(DefaultFileSystemMaster.java:853)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$getStatus$94(FileSystemMasterClientServiceHandler.java:207)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
        at alluxio.RpcUtils.call(RpcUtils.java:78)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.getStatus(FileSystemMasterClientServiceHandler.java:204)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2166)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1356)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
```

**To Reproduce**
Unclear right now. Only `bin/alluxio fs mount --shared --readOnly` is performed on the dir

**Expected behavior**

**Urgency**
High as there is any solution except for wiping out the entire Alluxio metastore

**Comment by yuzhu** [comment]
@frankobe could you provide any more detail on how you might have arrived at this state?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
