### ISSUE TITLE
Failed to free space for block

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#13086]
**Alluxio Version:**
2.4.1

**Describe the bug**
Failed to free space for block
```
192 2021-03-14 10:23:20,243 ERROR TieredBlockStore - Allocation failure. Options: AllocateOptions{Location=BlockStoreLocation{TierAlias=MEM, DirIndex=0, MediumType=MEM}, Size=335544320, ForceLocation=true, EvictionAllowed=true, UseReservedSpace=false}. Error:
 193 alluxio.exception.WorkerOutOfSpaceException: Failed to free 335544320 bytes space at location MEM. Min contiguous requested: 335544320, Min available requested: 335544320, Blocks iterated: 0, Blocks removed: 0, Space freed: 0
 194         at alluxio.worker.block.TieredBlockStore.freeSpaceInternal(TieredBlockStore.java:825)
 195         at alluxio.worker.block.TieredBlockStore.freeSpace(TieredBlockStore.java:455)
 196         at alluxio.worker.block.TieredBlockStore.allocateSpace(TieredBlockStore.java:651)
 197         at alluxio.worker.block.TieredBlockStore.requestSpace(TieredBlockStore.java:318)
 198         at alluxio.worker.block.DefaultBlockWorker.requestSpace(DefaultBlockWorker.java:483)
 199         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:132)
 200         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
 201         at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
 202         at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
 203         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
 204         at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
 205         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 206         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 207         at java.lang.Thread.run(Thread.java:748)
 208 2021-03-14 10:23:20,248 ERROR AbstractWriteHandler - Failed to write data for request BlockWriteRequest{id=6945767424, sessionId=2003017542951314771, tier=0,      createUfsBlockOptions=null}
 209 alluxio.exception.WorkerOutOfSpaceException: Can't reserve more space for block: 6945767424 under session: 2003017542951314771.
 210         at alluxio.worker.block.TieredBlockStore.requestSpace(TieredBlockStore.java:321)
 211         at alluxio.worker.block.DefaultBlockWorker.requestSpace(DefaultBlockWorker.java:483)
 212         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:132)
 213         at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
 214         at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
 215         at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
 216         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
 217         at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
 218         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 219         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 220         at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jiacheliu3** [comment]
@xieydd What is your tiered storage configuration like? What do you see in the physical directories?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
