### ISSUE TITLE
listStatus on open file stream will complete the stream unexpectedly

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#13128]
The behavior and root cause are reported by a community user

**Alluxio Version:**
2.5.0

**Describe the bug**
Running `listStatus(file)` when the file stream is not closed will cause the block to be completed unexpectedly, resulting in blocks that have 0 length.

The file will look like below, with block(s) of 0 length.
```
FileInfo{fileId=83886079, fileIdentifier=null, name=test_file_large3, path=/test_file_large3, ufsPath=s3a://autobots-xxx/test_file_large3, length=0, blockSizeBytes=67108864, creationTimeMs=1616765744207, completed=false, folder=false, pinned=false, pinnedlocation=[], cacheable=true, persisted=true, blockIds=[67108864, 67108865], inMemoryPercentage=100, lastModificationTimesMs=1616765744205, ttl=-1, lastAccessTimesMs=1616765744205, ttlAction=DELETE, owner=jiachengliu, group=staff, mode=420, persistenceState=PERSISTED, mountPoint=false, replicationMax=-1, replicationMin=0, fileBlockInfos=[
FileBlockInfo{blockInfo=BlockInfo{id=67108864, length=0, locations=[]}, offset=0, ufsLocations=[]}, FileBlockInfo{blockInfo=BlockInfo{id=67108865, length=0, locations=[]}, offset=67108864, ufsLocations=[]}], 
mountId=1, inAlluxioPercentage=100, ufsFingerprint=, acl=user::rw-,group::r--,other::r--, defaultAcl=, cacheQuota=null, cacheScope=null}
```

Subsequently when closing the `AlluxioFileOutputStream` the following exception is met:
```
alluxio.exception.status.InvalidArgumentException: Block index 0 has a block size smaller than the file block size (67108864)

	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:131)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:407)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.completeFile(RetryHandlingFileSystemMasterClient.java:172)
	at alluxio.client.file.AlluxioFileOutStream.close(AlluxioFileOutStream.java:185)
	at alluxio.cli.CommitTest.testCommit(CommitTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
...
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Block index 0 has a block size smaller than the file block size (67108864)
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.completeFile(FileSystemMasterClientServiceGrpc.java:1685)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$completeFile$4(RetryHandlingFileSystemMasterClient.java:172)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:405)
	... 30 more

```

See below for the test code to easily reproduce the exception above.

**To Reproduce**
First have an Alluxio cluster running.

Then run the test logic below. The easiest way is to just execute as a unit test.
```
@Test
  public void testCommit() throws Exception {
    String path = "/test_file_large3";
    FileSystem fs = FileSystem.Factory.get();
    AlluxioURI a_path = new AlluxioURI(path);

    byte[] content = "0123456789".getBytes(); //10byte
    FileSystemMasterCommonPOptions commonPOptions = FileSystemMasterCommonPOptions.newBuilder().setSyncIntervalMs(-1).build();
    CreateFilePOptions options = CreateFilePOptions.newBuilder().setWriteType(WritePType.CACHE_THROUGH).setCommonOptions(commonPOptions).build();
    FileOutStream out = fs.createFile(a_path, options);

    int max = 65 * 1024 * 1024/content.length; // So there are more than 1 blocks
    long counter = 0;
    for(int i=0; i < max; i++) {
      out.write(content);
      counter += content.length;
      if(counter >= 1 * 1024 * 1024)
        try {
          Thread.sleep(3 * 1000L);
          System.out.println(fs.getStatus(a_path)); // This will cause the block to complete on the master side
          counter = 0;
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
    }
    out.flush();
    out.close(); // Exception thrown here
    System.out.println(fs.getStatus(a_path));
  }
```

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
The issue is related to the rehydration logic https://github.com/Alluxio/alluxio/blob/feb4aa08ea675ef1c49005c2f6c401e07bab80cf/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L931

The evidence is the master log
```
2021-03-26 21:35:47,511 WARN  DefaultFileSystemMaster - BlockInfo missing for file: /test_file_large3. BlockIdsWithMissingInfos: 
2021-03-26 21:38:57,279 WARN  DefaultFileSystemMaster - BlockInfo missing for file: /test_file_large3. BlockIdsWithMissingInfos: 67108864
2021-03-26 21:39:29,240 WARN  DefaultBlockMaster - Rejecting attempt to change block length from 0 to 1048576
2021-03-26 21:39:29,242 WARN  DefaultBlockMaster - Rejecting attempt to change block length from 0 to 67108864
2021-03-26 21:39:29,247 WARN  FileSystemMasterClientServiceHandler - Exit (Error): CompleteFile: request=path: "/test_file_large3"
options {
  ufsLength: 68157440
}
, Error=Block index 0 has a block size smaller than the file block size (67108864)
```

**Solution**
Only rehydrate if the file is completed.

**Comment by jiacheliu3** [comment]
The root cause is, in `DefaultFileSystemMaster#getFileInfoInternal`, it compares the length of `BlockId` and `FileBlockInfo`. If there's a mismatch, it will consider the file has lost some block info for unknown reason and attempts to update the FileInfo. Here it commits the blocks implicitly.

The logic was added in https://github.com/Alluxio/alluxio/commit/256e331ab3bca297fec610aff8edd7a7b5f99cbc where we were trying to make up for using RocksDB incorrectly (and thus have lost BlockInfo mysteriously).

The problem with files we are currently writing is, `getBlockInfoInternal` [here](https://github.com/Alluxio/alluxio/blob/2ad1e1e0b8a59671177a83d712754197be273667/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L920) will return a list with length not matching the blockIds. The logic is like this:

1. The 1st block
When the file has 1 block (<64MB), currently writing
fileInfo.getBlockIds will return 1 block ID
getBlockInfoInternal(path) will return 1 BlockInfo with length=0. This length is always 0 until the whole file is committed.

2. The 2nd block (same for blocks after the 1st)
When the file has 2 blocks, currently still writing
fileInfo.getBlockIds will return 2 block IDs
getBlockInfoInternal(path) will return 1 BlockInfo, both having length=0. The lengths will always be 0 until the whole file is committed.
Here we get a mismatch between the number of BlockId and BlockInfo.
Then [here](https://github.com/Alluxio/alluxio/blob/2ad1e1e0b8a59671177a83d712754197be273667/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L936) we commit the FileInfo with the 2 BlockInfo we just got. Here the 1st BlockInfo is committed with length=0, which is wrong.

**Comment by jiacheliu3** [comment]
One solution is, when we check for rehydration (whether the rehydration should be allowed is another topic), we ignore incomplete files because there will be mismatch in the BlockId size and FileBlockInfo size, because of the order we create them. The PR is https://github.com/Alluxio/alluxio/pull/13131.

There are other alternatives, like we change the order we create `BlockId` and `FileBlockInfo` and make sure they always match so we do not enter the rehydration logic whether or not the file is completed.

**Comment by apc999** [comment]
thanks for the patch to fix this issue @jiacheliu3
