### ISSUE TITLE
Alluxio 2.5.0 Docker image does not include HDFS 3.3 support

### ISSUE THREAD

**Issue by ZhuTopher** [Alluxio/alluxio#13127]
**Alluxio Version:**
What version of Alluxio are you using?
2.5.0 (Docker image `alluxio/alluxio:2.5.0`)

**Describe the bug**
When using HDFS as the UFS the default version is configured to be 3.3
- See `UNDERFS_VERSION` in [PropertyKey.java](https://github.com/Alluxio/alluxio/blob/master/core/common/src/main/java/alluxio/conf/PropertyKey.java#L4753)
- The [Alluxio HDFS Docs](https://docs.alluxio.io/os/user/stable/en/ufs/HDFS.html#supported-hdfs-versions) say Alluxio supports up to 3.3 (and that 3.3 is the default version)

If running the Alluxio image `alluxio/alluxio:2.5.0` configured with HDFS as the UFS (eg: `alluxio.master.mount.table.root.ufs=hdfs://hdfs-k8s/alluxio`) then the `alluxio-master-0` Pod in container `alluxio-master` has the following logs:
```
2021-03-25 21:28:36,800 WARN  ExtensionFactoryRegistry - No factory implementation supports the path hdfs://hdfs-k8s/alluxio
2021-03-25 21:28:36,828 ERROR AlluxioMaster - Fatal error: Failed to create master process
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start masters
    at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:125)
    at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:420)
    at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Failed to start masters
    at alluxio.master.MasterUtils.createMasters(MasterUtils.java:57)
    at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:123)
    ... 2 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No Under File System Factory found for: hdfs://hdfs-k8s/alluxio
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:592)
    at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:554)
    at alluxio.master.MasterUtils.createMasters(MasterUtils.java:55)
    ... 3 more
Caused by: java.lang.IllegalArgumentException: No Under File System Factory found for: hdfs://hdfs-k8s/alluxio
    at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:95)
    at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:132)
    at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:171)
    at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:61)
    at alluxio.master.file.DefaultFileSystemMaster.getRootMountInfo(DefaultFileSystemMaster.java:498)
    at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:440)
    at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:421)
    at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:51)
    at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:28)
    at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

The reason is because the Docker image of Alluxio 2.5.0 does not have the UFS implementation for HDFS 3.3:
```
$ kubectl exec -it alluxio-master-0 -c alluxio-master /bin/bash
bash-4.4$ cd lib
bash-4.4$ ls
alluxio-integration-tools-hms-2.5.0.jar
alluxio-integration-tools-validation-2.5.0.jar
alluxio-table-server-underdb-glue-2.5.0.jar
alluxio-table-server-underdb-hive-2.5.0.jar
alluxio-underfs-adl-2.5.0.jar
alluxio-underfs-cos-2.5.0.jar
alluxio-underfs-gcs-2.5.0.jar
alluxio-underfs-hadoop-2.2-2.5.0.jar
alluxio-underfs-hadoop-2.7-2.5.0.jar
alluxio-underfs-hadoop-2.8-2.5.0.jar
alluxio-underfs-hadoop-2.9-2.5.0.jar
alluxio-underfs-hadoop-3.2-2.5.0.jar
alluxio-underfs-local-2.5.0.jar
alluxio-underfs-oss-2.5.0.jar
alluxio-underfs-s3a-2.5.0.jar
alluxio-underfs-swift-2.5.0.jar
alluxio-underfs-wasb-2.5.0.jar
alluxio-underfs-web-2.5.0.jar
libjnifuse.dylib
libjnifuse.so
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

Deploy Alluxio in k8s using either the Helm chart or manually via Kubectl (see the [Alluxio k8s docs](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html)).

Configure a single-master, local journal Alluxio cluster using HDFS as its UFS. Examine the logs of the `alluxio-master-0` Pod's `alluxio-master` container.

**Expected behavior**

Alluxio should be able to use HDFS 3.3 as its UFS (according to the docs).

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jja725** [comment]
@ssz1997  is this still valid? otherwise help me close this please

**Comment by ssz1997** [comment]
Alluxio dockerfile directly copy Alluxio tarball into the container. It doesn't make sense bare metal alluxio works but docker env doesn't. Plus we don't hear complain from any user. I think it's safe to close the issue.
