### ISSUE TITLE
ERROR AlluxioJniFuseFileSystem - Failed to read when setting alluxio.fuse.shared.caching.reader.enabled=true

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13125]
**Alluxio Version:**
2.5.0-1

**Describe the bug**

When reading a file from Alluxio FUSE which has `alluxio.fuse.shared.caching.reader.enabled=true`: I get the following errors:
```
ERROR AlluxioJniFuseFileSystem - Failed to read, path: /tmpsq57a1g8.bin size: 131072 offset: 0
java.lang.ArrayIndexOutOfBoundsException: Index -25 out of bounds for length 32
	at alluxio.client.block.stream.SharedGrpcDataReader.getLock(SharedGrpcDataReader.java:68)
	at alluxio.client.block.stream.SharedGrpcDataReader.access$000(SharedGrpcDataReader.java:43)
	at alluxio.client.block.stream.SharedGrpcDataReader$Factory.create(SharedGrpcDataReader.java:167)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:427)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:268)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:189)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:374)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:349)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:278)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:349)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)
ERROR AlluxioJniFuseFileSystem - Failed to read, path: /tmpsq57a1g8.bin size: 4096 offset: 0
java.lang.ArrayIndexOutOfBoundsException: Index -25 out of bounds for length 32
	at alluxio.client.block.stream.SharedGrpcDataReader.getLock(SharedGrpcDataReader.java:68)
	at alluxio.client.block.stream.SharedGrpcDataReader.access$000(SharedGrpcDataReader.java:43)
	at alluxio.client.block.stream.SharedGrpcDataReader$Factory.create(SharedGrpcDataReader.java:167)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:427)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:268)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:189)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:374)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:349)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:278)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:349)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)
```

- At the client side reading the file I get a `Errno 5: Input/output error` OS error.
- The file I'm reading is persisted, and after failure reading is 67% in alluxio.
- I don't see anything weird in the Master or Worker logs

**To Reproduce**
In Docker containers:
- Start Alluxio Master and Worker
- Start Alluxio fuse with `alluxio.fuse.jnifuse.enabled=true`, `alluxio.user.file.readtype.default=CACHE`, and `alluxio.fuse.shared.caching.reader.enabled=true`
- Read non-cached 100MB file from Alluxio.

**Expected behavior**
Exception not to happen.

**Urgency**
Alluxio FUSE works with `alluxio.fuse.shared.caching.reader.enabled=false`

**Additional context**
I know the `alluxio.fuse.shared.caching.reader.enabled` flag is experimental, however I thought it would be best to flag the issue.
- Java: JRE 11
- Services run in Docker
- Fuse service settings that might be relevant:
  - alluxio.fuse.jnifuse.enabled=true
  - alluxio.user.file.readtype.default=CACHE
  - alluxio.fuse.shared.caching.reader.enabled=true

**Comment by apc999** [comment]
@LuQQiu  can you take a look at this issue?

**Comment by LuQQiu** [comment]
This issue can be reproduced in linux environment and cannot be reproduce in local mac environment. Taking a look into the cause now. Thanks

**Comment by lilyzhoupeijie** [comment]
this not only occur  in fuse system,when alluxio.fuse.shared.caching.reader.enabled=true is set,the file will never write from allxuio to udfs successfully, all files can not persist to ceph successfully ,the error is alluxio.client.block.stream.SharedGrpcDataReader.getLock(SharedGrpcDataReader.java:68)
alluxio version 2.6.0

**Comment by jja725** [comment]
seems like resolved
