### ISSUE TITLE
java.lang.NoSuchMethodException: alluxio.metrics.sink.PrometheusMetricsServlet.<init>(java.util.Properties, com.codahale.metrics.MetricRegistry)

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#13165]
**Alluxio Version:**
2.3.0

**Describe the bug**
java.lang.NoSuchMethodException: alluxio.metrics.sink.PrometheusMetricsServlet.<init>(java.util.Properties, com.codahale.metrics.MetricRegistry)

when master start

**Comment by LuQQiu** [comment]
@jiemar Thanks for reporting this issue. Can you help describe the details for us to reproduce this issue?
For example, what's the metrics.properties and alluxio-site.properties you used when launching the cluster?

**Comment by apc999** [comment]
@jiemar  ping.

**Comment by kevincai** [comment]
facing the same error

conf/metrics.properties
```
# Enable PrometheusMetricsServlet
sink.prometheus.class=alluxio.metrics.sink.PrometheusMetricsServlet
```

Error Log
```
2021-09-15 21:50:15,781 INFO  MetricsSystem - Starting sinks with config: {sink.prometheus.class=alluxio.metrics.sink.PrometheusMetricsServlet}.
2021-09-15 21:50:15,781 INFO  MetricsSystem - Starting sink alluxio.metrics.sink.PrometheusMetricsServlet.
2021-09-15 21:50:15,782 ERROR MetricsSystem - Sink class alluxio.metrics.sink.PrometheusMetricsServlet cannot be instantiated
java.lang.NoSuchMethodException: alluxio.metrics.sink.PrometheusMetricsServlet.<init>(java.util.Properties, com.codahale.metrics.MetricRegistry)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at alluxio.metrics.MetricsSystem.startSinksFromConfig(MetricsSystem.java:241)
        at alluxio.metrics.MetricsSystem.startSinks(MetricsSystem.java:178)
        at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:283)
        at alluxio.master.FaultTolerantAlluxioMasterProcess.lambda$gainPrimacy$207(FaultTolerantAlluxioMasterProcess.java:148)
        at java.lang.Thread.run(Thread.java:756)
```
