### ISSUE TITLE
alluxio cluster masters hung every few days

### ISSUE THREAD

**Issue by XuankuF** [Alluxio/alluxio#13164]
**Alluxio Version:**
2.4.1-2

**Urgency**
Very urgent, affecting the online works.

**Describe the bug**
three master nodes: node1(leader), node2, node3.  node2 alluxio master and node3 alluxio master hung every few days, and node1(leader) `Journal flush failed`. Finally node1(leader) abnormal exit.
jvm heap:
```
ALLUXIO_MASTER_JAVA_OPTS+="-Xms100g -Xmx100g"
ALLUXIO_SECONDARY_MASTER_JAVA_OPTS+="-Xms100g -Xmx100g"
```

The error logs from node2:
```
java.io.IOException: Failed to rename journal log from hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs/0x1f3065-0x7fffffffffffffff to hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs
/0x1f3065-0x1fdc53
        at alluxio.master.journal.ufs.UfsJournalLogWriter.completeLog(UfsJournalLogWriter.java:349)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.access$300(UfsJournalLogWriter.java:57)
        at alluxio.master.journal.ufs.UfsJournalLogWriter$JournalOutputStream.close(UfsJournalLogWriter.java:479)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.maybeRotateLog(UfsJournalLogWriter.java:282)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.write(UfsJournalLogWriter.java:119)
        at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:286)
        at java.lang.Thread.run(Thread.java:748)
2021-04-01 17:03:23,132 WARN  MasterJournalContext - Journal flush failed. retrying...
java.io.IOException: Failed to rename journal log from hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs/0x1f3065-0x7fffffffffffffff to hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs
/0x1f3065-0x1fdc53
        at alluxio.master.journal.ufs.UfsJournalLogWriter.completeLog(UfsJournalLogWriter.java:349)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.access$300(UfsJournalLogWriter.java:57)
        at alluxio.master.journal.ufs.UfsJournalLogWriter$JournalOutputStream.close(UfsJournalLogWriter.java:479)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.maybeRotateLog(UfsJournalLogWriter.java:282)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.write(UfsJournalLogWriter.java:119)
        at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:286)
        at java.lang.Thread.run(Thread.java:748)
2021-04-01 17:03:23,132 INFO  UfsJournalLogWriter - Completing log hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs/0x1f3065-0x7fffffffffffffff with next sequence number 2088019
2021-04-01 17:03:23,168 WARN  HdfsUnderFileSystem - Unable to rename hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs/0x1f3065-0x7fffffffffffffff to hdfs://Thor/alluxio/alluxio_journal/FileSystem
Master/v1/logs/0x1f3065-0x1fdc53 because source does not exist or is a directory
2021-04-01 17:03:23,205 INFO  AbstractMaster - TableMaster: Stopping primary master.
2021-04-01 17:03:23,205 INFO  UfsJournalLogWriter - Marking hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs/0x1f3065-0x7fffffffffffffff as complete with log entries within [2044005, 2088019).
2021-04-01 17:03:23,205 INFO  UfsJournalLogWriter - Completing log hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs/0x1f3065-0x7fffffffffffffff with next sequence number 2088019
2021-04-01 17:03:23,205 INFO  AbstractMaster - TableMaster: Stopped primary master.
2021-04-01 17:03:23,205 INFO  AbstractMaster - MetaMaster: Stopping primary master.
2021-04-01 17:03:23,205 WARN  HdfsUnderFileSystem - Unable to rename hdfs://Thor/alluxio/alluxio_journal/FileSystemMaster/v1/logs/0x1f3065-0x7fffffffffffffff to hdfs://Thor/alluxio/alluxio_journal/FileSystem
Master/v1/logs/0x1f3065-0x1fdc53 because source does not exist or is a directory
2021-04-01 17:03:23,205 INFO  AbstractMaster - MetaMaster: Stopped primary master.
```

The error logs from node1(leader):
```
2021-04-01 16:58:01,523 WARN  MasterJournalContext - Journal flush failed. retrying...
alluxio.exception.status.AlluxioStatusException
        at alluxio.master.journal.AsyncJournalWriter.flush(AsyncJournalWriter.java:373)
        at alluxio.master.journal.MasterJournalContext.waitForJournalFlush(MasterJournalContext.java:75)
        at alluxio.master.journal.MasterJournalContext.close(MasterJournalContext.java:91)
        at alluxio.master.journal.StateChangeJournalContext.close(StateChangeJournalContext.java:53)
        at alluxio.master.block.DefaultBlockMaster.commitBlock(DefaultBlockMaster.java:715)
        at alluxio.master.block.BlockMasterWorkerServiceHandler.lambda$commitBlock$4(BlockMasterWorkerServiceHandler.java:109)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
        at alluxio.RpcUtils.call(RpcUtils.java:78)
        at alluxio.RpcUtils.call(RpcUtils.java:53)
        at alluxio.master.block.BlockMasterWorkerServiceHandler.commitBlock(BlockMasterWorkerServiceHandler.java:108)
        at alluxio.grpc.BlockMasterWorkerServiceGrpc$MethodHandlers.invoke(BlockMasterWorkerServiceGrpc.java:597)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1356)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:717)
        at alluxio.concurrent.jsr.ForkJoinPool.createWorker(ForkJoinPool.java:1076)
        at alluxio.concurrent.jsr.ForkJoinPool.tryCompensate(ForkJoinPool.java:1326)
        at alluxio.concurrent.jsr.ForkJoinPool.managedBlock(ForkJoinPool.java:1002)
        at alluxio.concurrent.ForkJoinPoolHelper.safeManagedBlock(ForkJoinPoolHelper.java:41)
        at alluxio.master.journal.AsyncJournalWriter$FlushTicket.waitCompleted(AsyncJournalWriter.java:96)
        at alluxio.master.journal.AsyncJournalWriter.flush(AsyncJournalWriter.java:360)
        ... 23 more
2021-04-01 16:58:01,523 ERROR MasterJournalContext - Fatal error: Journal flush failed after 714 attempts
```

**Comment by loovia** [comment]
@apc999 Could you take a look at this issue?

**Comment by BUPTAnderson** [comment]
> @apc999 Could you take a look at this issue?

Is there any error log in hdfs namenode or datanode at the same time ?

**Comment by loovia** [comment]
> Is there any error log in hdfs namenode or datanode at the same time ?
@BUPTAnderson no, hadoop is fine

**Comment by LuQQiu** [comment]
@bf8086 Any thoughts on why Journal write can succeed but journal rename failed with HDFS journal?

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid.
