### ISSUE TITLE
Alluxio Worker down Without cause

### ISSUE THREAD

**Issue by loovia** [Alluxio/alluxio#13230]
**Alluxio Version:**
2.4.1-2

```
2021-04-13 18:09:29,098 WARN  AsyncBlockRemover - Failed to remove block 7991524851713 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-8, error Cannot remove uncommitted blockId 7991524851713
2021-04-13 18:09:30,011 ERROR AbstractWriteHandler - Failed to write data for request BlockWriteRequest{id=9926541836288, sessionId=3105850754760692057, tier=0, createUfsBlockOptions=null}
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
        at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:141)
        at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
        at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
        at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2021-04-13 18:09:30,100 WARN  AsyncBlockRemover - Failed to remove block 7990769876993 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-1, error Cannot remove uncommitted blockId 7990769876993
2021-04-13 18:09:30,100 WARN  AsyncBlockRemover - Failed to remove block 7991289970689 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-0, error Cannot remove uncommitted blockId 7991289970689
2021-04-13 18:09:30,100 WARN  AsyncBlockRemover - Failed to remove block 7991961059329 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-2, error Cannot remove uncommitted blockId 7991961059329
2021-04-13 18:09:30,100 WARN  AsyncBlockRemover - Failed to remove block 7991524851713 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-9, error Cannot remove uncommitted blockId 7991524851713
2021-04-13 18:09:30,100 WARN  AsyncBlockRemover - Failed to remove block 7991994613761 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-4, error Cannot remove uncommitted blockId 7991994613761
2021-04-13 18:09:30,100 WARN  AsyncBlockRemover - Failed to remove block 7990669213698 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-1, error Cannot remove uncommitted blockId 7990669213698
2021-04-13 18:09:30,240 ERROR AbstractWriteHandler - Failed to write data for request BlockWriteRequest{id=9926541836288, sessionId=3105850754760692057, tier=0, createUfsBlockOptions=null}
java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
        at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:1121)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:948)
        at alluxio.worker.block.io.LocalFileBlockWriter.append(LocalFileBlockWriter.java:66)
        at alluxio.worker.block.io.LocalFileBlockWriter.append(LocalFileBlockWriter.java:80)
        at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:141)
        at alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
        at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
        at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2021-04-13 18:09:30,240 WARN  TieredBlockStore - Clean up expired temporary block 9926541836288 from session 3105850754760692057.
2021-04-13 18:09:31,099 WARN  AsyncBlockRemover - Failed to remove block 7991961059329 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-3, error Cannot remove uncommitted blockId 7991961059329
```

**Comment by apc999** [comment]
@loovia  it seems the worker is full from log 
"Failed to write data for request BlockWriteRequest{id=9926541836288, sessionId=3105850754760692057, tier=0, createUfsBlockOptions=null}
java.io.IOException: No space left on device"

Do you mind upload your worker.out and worker.log files here?

**Comment by loovia** [comment]
[worker.log](https://github.com/Alluxio/alluxio/files/6355365/worker.log)
@apc999 
yesterday i changed worker tieredstore to SSD(500G) replaced of MEM(50G) + HDD(150*12) every host, it seems normal now. But there still AsyncBlockRemover log `2021-04-22 11:02:11,369 WARN  AsyncBlockRemover - Failed to remove block 8595236192256 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-8, error BlockMeta not found for blockId 8595236192256`. I don't know what's mean.

worker.out file often print:
```
Apr 22, 2021 11:53:04 AM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 19
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:596)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:239)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by apc999** [comment]
@loovia  

> "But there still AsyncBlockRemover log 2021-04-22 11:02:11,369 WARN AsyncBlockRemover - Failed to remove block 8595236192256 instructed by master. This is best-effort and will be tried later. threadName block-removal-service-8, error BlockMeta not found for blockId 8595236192256. I don't know what's mean."

You can ignore this warning message. It simply means the master instruct the worker to remove a data block and this block is no longer on this worker (can be an expected case)

> "Apr 22, 2021 11:53:04 AM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 19"

This is a known issue https://github.com/Alluxio/alluxio/issues/13138 we are tracking. in short, you can ignore this message too.

**Comment by loovia** [comment]
@apc999 thanks~
