### ISSUE TITLE
GCS complains about Connection reset UnknownHostException: www.googleapis.com

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#13245]
**Alluxio Version:**
Alluxio 2.5

**Describe the bug**
```
2021-04-15 02:09:10,149 ERROR AbstractWriteHandler - Failed to write data for request {.....}
com.google.cloud.storage.StorageException: www.googleapis.com
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:225)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:744)
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:53)
	at com.google.cloud.BaseWriteChannel.flush(BaseWriteChannel.java:112)
	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:139)
	at alluxio.underfs.gcs.v2.GCSV2OutputStream.write(GCSV2OutputStream.java:100)
	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:608)
	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:595)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:142)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:1161)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:49)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:965)
	at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:2097)
	at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:49)
	at alluxio.network.protocol.databuffer.NettyDataBuffer.readBytes(NettyDataBuffer.java:64)
	at alluxio.worker.grpc.UfsFileWriteHandler.writeBuf(UfsFileWriteHandler.java:142)
	at alluxio.worker.grpc.UfsFileWriteHandler.writeBuf(UfsFileWriteHandler.java:50)
	at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:312)
	at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:186)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: www.googleapis.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:108)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:79)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:995)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:721)
	... 27 more
```

```
2021-04-15 03:57:49,196 ERROR AbstractWriteHandler - Failed to write data for request UfsFileWriteRequest{.....
}
com.google.cloud.storage.StorageException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:225)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:744)
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:53)
	at com.google.cloud.BaseWriteChannel.flush(BaseWriteChannel.java:112)
	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:139)
	at alluxio.underfs.gcs.v2.GCSV2OutputStream.write(GCSV2OutputStream.java:100)
	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:608)
	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:588)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:142)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:1161)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:49)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:965)
	at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:2097)
	at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:49)
	at alluxio.network.protocol.databuffer.NettyDataBuffer.readBytes(NettyDataBuffer.java:64)
	at alluxio.worker.grpc.UfsFileWriteHandler.writeBuf(UfsFileWriteHandler.java:142)
	at alluxio.worker.grpc.UfsFileWriteHandler.writeBuf(UfsFileWriteHandler.java:50)
	at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:312)
	at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:186)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
...
```
**To Reproduce**
This occurs occasionally, randomly an not determined

**Expected behavior**
Understand the reason of the reset and can better handle it

**Urgency**
Medium

**Additional context**

**Comment by LuQQiu** [comment]
Could be Memory pressure
https://support.terra.bio/hc/en-us/community/posts/360055563171-Intermittent-StorageExceptions-unknown-host-www-googleapis-com-

**Comment by jja725** [comment]
Will close it for now since gcs is not priority, feel free to reopen it and contact us if this is still valid.
