### ISSUE TITLE
fuse with translation disabled still requires username lookup

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13254]
**Alluxio Version:**
2.5.0-2

**Describe the bug**
I have a FUSE process with user translation turned off by setting `alluxio.fuse.user.group.translation.enabled=false`. This fuse process is running in a Docker container as `alluxio` user, and is sharing the FUSE mount via a bind-mount on the host.
 However when trying to write to the FUSE folder from a different service I get the following error:
 ```
 ExitCodeException exitCode=1: id: ‘1548’: no such user

	at alluxio.shell.ShellCommand.run(ShellCommand.java:71)
	at alluxio.util.ShellUtils.execCommand(ShellUtils.java:238)
	at alluxio.fuse.AlluxioFuseUtils.getUserName(AlluxioFuseUtils.java:108)
	at alluxio.fuse.AlluxioJniFuseFileSystem.setUserGroupIfNeeded(AlluxioJniFuseFileSystem.java:196)
	at alluxio.fuse.AlluxioJniFuseFileSystem.createInternal(AlluxioJniFuseFileSystem.java:232)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$create$0(AlluxioJniFuseFileSystem.java:213)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.create(AlluxioJniFuseFileSystem.java:213)
	at alluxio.jnifuse.AbstractFuseFileSystem.createCallback(AbstractFuseFileSystem.java:253)
```

This seems to imply that the FUSE container still needs to be aware of the user with UID 1548. I was hoping that by turning the translation off all files would be owned by by the `alluxio` user, and the FUSE container would not need to be aware of other users.

**To Reproduce**
- Launch Alluxio FUSE in Docker running as `alluxio` user with UID `1001`. Make sure FUSE is mounted in a bind mount to the host. Make sure that `alluxio` user is the only user on this container.
- From the host with a different user with UID `1548`: Write a file to the FUSE mount.
- Result: above error.

Please note that the exact user name and UID does not matter, what matters is that the FUSE mount is being written to by a user that the FUSE container is not aware of.

**Expected behavior**
- Writing by a different user working out-of-the box when user translation is turned off.

**Urgency**
low,
If I write to the fuse folder with a user that has the same UID it works. The error prevents me to seperate user spaces between services.

**Additional context**

**Comment by apc999** [comment]
@peterroelants  I created a patch #13268 to fix this issue.
