### ISSUE TITLE
Alluxio-Worker-FUSE integration hangs

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13255]
**Alluxio Version:**
2.5.0-2

**Describe the bug**
The [Alluxio Worker-FUSE integration](https://docs.alluxio.io/os/user/edge/en/api/POSIX-API.html#fuse-on-worker-process) hangs after fetching a file from cache.

**To Reproduce**
- Start Alluxio Master
- Start Alluxio Worker with FUSE integration
  - Worker has multi-tiered caching with a tier 0 in MEM and tier 1 on disk.
- On worker container:
  - Load file from S3 (770MB file in this case) `alluxio fs load <alluxio_path>`
  - Read file a few times: `cat ${MOUNT_POINT}/<alluxio_path> > /dev/null`, it usually hangs after 2-4 tries
  
For example, these are some timings I got when running it on my alluxio-worker with FUSE:
```
alluxio@7f23ccee2029:/opt/alluxio$ alluxio fs load <alluxio_path>
<alluxio_path> loaded
alluxio@7f23ccee2029:/opt/alluxio$ date
Tue Apr 20 14:50:23 UTC 2021
alluxio@7f23ccee2029:/opt/alluxio$ date && time cat ${MOUNT_POINT}/<alluxio_path> > /dev/null
Tue Apr 20 14:50:57 UTC 2021

real	0m0.797s
user	0m0.003s
sys	0m0.219s
alluxio@7f23ccee2029:/opt/alluxio$ date && time cat ${MOUNT_POINT}/<alluxio_path> > /dev/null
Tue Apr 20 14:51:03 UTC 2021

real	0m0.497s
user	0m0.004s
sys	0m0.269s
alluxio@7f23ccee2029:/opt/alluxio$ date && time cat ${MOUNT_POINT}/<alluxio_path> > /dev/null
Tue Apr 20 14:51:09 UTC 2021

.... (Hangs here for more than  2 hours now)
```
I added date references to be able to lookup things against the logs. However, I don't notice anything weird in the logs

Note that I can actually read the file two times in less than a second before it hangs the 3rd time. I have been able to replicate this each time I tried it (4 times) after loading the file 2-4 times in a row.

Please find the following logs attached:
- [master.log](https://github.com/Alluxio/alluxio/files/6344709/master.log)
- [job_master.log](https://github.com/Alluxio/alluxio/files/6344712/job_master.log)
- [worker.log](https://github.com/Alluxio/alluxio/files/6344713/worker.log)
- [worker/user_alluxio.log](https://github.com/Alluxio/alluxio/files/6344715/worker-user_alluxio.log)
- [output of `ps -aux` in worker-fuse container](https://github.com/Alluxio/alluxio/files/6344721/worker_ps_aux.log)

**Expected behavior**
Alluxio Worker-FUSE integration to not hang

**Urgency**
High, This makes the Alluxio Worker-FUSE integration unworkable.

**Additional context**
- Services running in custom Docker containers
- Relevant FUSE options:
  ```
  alluxio.fuse.user.group.translation.enabled=false
  alluxio.fuse.jnifuse.enabled=true
  alluxio.user.file.readtype.default=CACHE
  alluxio.user.file.writetype.default=ASYNC_THROUGH
  alluxio.fuse.maxwrite.bytes=131072
  alluxio.fuse.shared.caching.reader.enabled=false
  alluxio.user.metadata.cache.enabled=false
  ```
- Worker: `MAX_IDLE_THREADS: 64`
- fusermount version: 2.9.5 (Patched version)
 - Worker `ALLUXIO_JAVA_OPTS`:
   ```
    -Dalluxio.worker.hostname=alluxio-worker-fuse
    -Dalluxio.worker.fuse.enabled=true
    -Dalluxio.worker.fuse.mount.alluxio.path=${ALLUXIO_UFS_PATH_MOUNTED_IN_FUSE}
    -Dalluxio.worker.fuse.mount.point=/mnt/fuse_parent_volume/${ALLUXIO_FUSE_MNT_DIR_NAME}
    -Dalluxio.worker.fuse.mount.options=entry_timeout=7200,attr_timeout=7200
    -Dalluxio.worker.ramdisk.size=${ALLUXIO_WORKER_RAMDISK_SIZE_GB}G
    -Dalluxio.worker.tieredstore.levels=2
    -Dalluxio.worker.tieredstore.level0.alias=MEM
    -Dalluxio.worker.tieredstore.level0.dirs.path=/mnt/tmpfs
    -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=MEM
    -Dalluxio.worker.tieredstore.level0.dirs.quota=${ALLUXIO_WORKER_RAMDISK_SIZE_GB}G
    -Dalluxio.worker.tieredstore.level1.alias=HDD
    -Dalluxio.worker.tieredstore.level1.dirs.path=/mnt/hdd-cache
    -Dalluxio.worker.tieredstore.level1.dirs.mediumtype=HDD
    -Dalluxio.worker.tieredstore.level1.dirs.quota=${ALLUXIO_WORKER_HDD_SIZE_GB}G
  ```

**Comment by apc999** [comment]
@peterroelants  can you provide jstack of your worker process ? it will be very helpful to identify where it is stucking

**Comment by peterroelants** [comment]
I have been running this with JRE, which does not have jstack afaik.
If I have some time I will try to recreate the issue with JDK and try to get the output from jstack.

**Comment by peterroelants** [comment]
I have been able to [add jstack to my JRE-based container](https://stackoverflow.com/a/66528723/919431).

I have replicated the issue with:
```
❯ docker exec -it -u alluxio alluxio-worker-fuse /bin/bash
alluxio@2713505568b6:/opt/alluxio$ alluxio fs load /<alluxio_path>
/<alluxio_path> loaded
alluxio@2713505568b6:/opt/alluxio$ date
Thu Apr 22 09:30:01 UTC 2021
alluxio@2713505568b6:/opt/alluxio$ date && time cat ${MOUNT_POINT}/<alluxio_path> > /dev/null
Thu Apr 22 09:30:09 UTC 2021

real	0m0.854s
user	0m0.004s
sys	0m0.203s
alluxio@2713505568b6:/opt/alluxio$ date && time cat ${MOUNT_POINT}/<alluxio_path> > /dev/null
Thu Apr 22 09:30:18 UTC 2021

real	0m0.436s
user	0m0.000s
sys	0m0.251s
alluxio@2713505568b6:/opt/alluxio$ date && time cat ${MOUNT_POINT}/<alluxio_path> > /dev/null
Thu Apr 22 09:30:26 UTC 2021

real	0m0.397s
user	0m0.004s
sys	0m0.243s
alluxio@2713505568b6:/opt/alluxio$ date && time cat ${MOUNT_POINT}/<alluxio_path> > /dev/null
Thu Apr 22 09:30:32 UTC 2021

.... (Hangs here)
```

Please find the worker logs and jstack outputs as collected by:
```
docker exec -it -u alluxio alluxio-worker-fuse /bin/bash -c "ps -aux | cat" &> worker-ps-aux.log
docker exec -it -u alluxio alluxio-worker-fuse /bin/bash -c "jstack 25" &> jstack-AlluxioWorker.log
docker exec -it -u alluxio alluxio-worker-fuse /bin/bash -c "jstack 294" &> jstack-AlluxioJobWorker.log
docker exec -it -u alluxio alluxio-worker-fuse /bin/bash -c "cat logs/job_worker.log" &> job_worker.log
docker exec -it -u alluxio alluxio-worker-fuse /bin/bash -c "cat logs/user/user_alluxio.log" &> user_alluxio.log
```
- [worker-ps-aux.log](https://github.com/Alluxio/alluxio/files/6357407/worker-ps-aux.log)
- [worker.log](https://github.com/Alluxio/alluxio/files/6357410/worker.log)
- [jstack-AlluxioWorker.log](https://github.com/Alluxio/alluxio/files/6357412/jstack-AlluxioWorker.log)
- [job_worker.log](https://github.com/Alluxio/alluxio/files/6357414/job_worker.log)
- [jstack-AlluxioJobWorker.log](https://github.com/Alluxio/alluxio/files/6357415/jstack-AlluxioJobWorker.log)
- [user_alluxio.log](https://github.com/Alluxio/alluxio/files/6357418/user_alluxio.log)

**Comment by LuQQiu** [comment]
From jstack-AlluxioWorker.log, 3 threads are blocked waiting for lock `0x0000000732f91ab8`
```
"Thread-3" #122 daemon prio=5 os_prio=0 cpu=435.03ms elapsed=2085.94s tid=0x00007fc940001800 nid=0x294 waiting on condition  [0x00007fc936af5000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x0000000707171ca0> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@11.0.11/Unknown Source)
	at java.util.concurrent.Semaphore.acquireUninterruptibly(java.base@11.0.11/Unknown Source)
	at alluxio.worker.block.ClientRWLock$SessionLock.lock(ClientRWLock.java:92)
	at alluxio.worker.block.BlockLockManager.lockBlockInternal(BlockLockManager.java:134)
	at alluxio.worker.block.BlockLockManager.lockBlock(BlockLockManager.java:100)
	at alluxio.worker.block.TieredBlockStore.lockBlockNoException(TieredBlockStore.java:164)
	at alluxio.worker.block.DefaultBlockWorker.createLocalBlockReader(DefaultBlockWorker.java:471)
	at alluxio.worker.block.DefaultBlockWorker.createBlockReader(DefaultBlockWorker.java:629)
	at alluxio.client.block.stream.BlockWorkerDataReader$Factory.create(BlockWorkerDataReader.java:132)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:481)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:314)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:203)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:389)
	- locked <0x0000000732f91ab8> (a alluxio.client.file.AlluxioFileInStream)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:364)
	at alluxio.fuse.AlluxioJniFuseFileSystem$$Lambda$464/0x000000084067f040.call(Unknown Source)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:364)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)
"Thread-38" #232 daemon prio=5 os_prio=0 cpu=350.69ms elapsed=1932.37s tid=0x00007fca64003800 nid=0x11a0 waiting for monitor entry  [0x00007fc90d6ba000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:381)
	- waiting to lock <0x0000000732f91ab8> (a alluxio.client.file.AlluxioFileInStream)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:364)
	at alluxio.fuse.AlluxioJniFuseFileSystem$$Lambda$464/0x000000084067f040.call(Unknown Source)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:364)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)

"Thread-39" #233 daemon prio=5 os_prio=0 cpu=341.99ms elapsed=1932.37s tid=0x00007fca70008000 nid=0x11a1 waiting for monitor entry  [0x00007fc90ceb9000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:381)
	- waiting to lock <0x0000000732f91ab8> (a alluxio.client.file.AlluxioFileInStream)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:364)
	at alluxio.fuse.AlluxioJniFuseFileSystem$$Lambda$464/0x000000084067f040.call(Unknown Source)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:364)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)

"Thread-40" #234 daemon prio=5 os_prio=0 cpu=231.63ms elapsed=1931.80s tid=0x00007fca80028000 nid=0x11a5 waiting for monitor entry  [0x00007fc90c6b8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:381)
	- waiting to lock <0x0000000732f91ab8> (a alluxio.client.file.AlluxioFileInStream)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:364)
	at alluxio.fuse.AlluxioJniFuseFileSystem$$Lambda$464/0x000000084067f040.call(Unknown Source)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:364)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)

```

**Comment by xinzhang-hello** [comment]
The bug not fixed yet?
