### ISSUE TITLE
Failed to attachdb - Logging NullPointerException

### ISSUE THREAD

**Issue by jasondavindev** [Alluxio/alluxio#13251]
**Alluxio Version:**
Version 2.4.1-2

**Describe the bug**
When I try to attach db on Alluxio, I faced with `NullPointerException`. The part of message error is sent when I trying to attach a glue database. The complete message is the same error but for 5 tables.

```
2021-04-19 11:22:32,270 INFO  GlueDatabase - Glue table events.clicks has 119 partitions.
2021-04-19 11:22:32,305 ERROR Database - Sync thread failed for events.clicks
java.lang.NullPointerException
	at com.google.protobuf.Internal.checkNotNull(Internal.java:64)
	at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:405)
	at alluxio.grpc.table.layout.hive.HiveBucketProperty$Builder.addAllBucketedBy(HiveBucketProperty.java:703)
	at alluxio.table.under.glue.GlueUtils.toProto(GlueUtils.java:320)
	at alluxio.table.under.glue.GlueDatabase.getTable(GlueDatabase.java:399)
	at alluxio.master.table.Database.lambda$sync$1(Database.java:232)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-19 11:22:32,306 INFO  Database - Syncing db events progress: completed 5 of 5 tables (100%)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
Call
```bash
alluxio table attachdb \
    --db events glue null events \
    -o udb-glue.aws.region=us-east-1
    -o udb-glue.aws.catalog.id=MY_CATALOG_ID
```
My aws credentials are set in configuration files.

**Expected behavior**
The alluxio attach db to occur successfully

**Urgency**
Medium. The error is occurring many times for different databases

**Additional context**

**Comment by LuQQiu** [comment]
@HelloHorizon Can you help take a look at this issue?
