### ISSUE TITLE
alluxio.shaded.client.io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by loovia** [Alluxio/alluxio#13300]
**Alluxio Version:**
2.4.1-2

run hivesql `create table tmp_src_table_h_2021042620 as select col from table `
error log:
```
 Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to move source alluxio://master1:19998,master2:19998,master3:19998/Thor/data/hive/warehouse/hive-databases/mid.db/.hive-staging_hive_2021-04-26_21-35-25_478_9151317015944838173-12846/-ext-10002 to destination alluxio://master1:19998,master2:19998,master3:19998/Thor/data/hive/warehouse/hive-databases/mid.db/tmp_src_table_h_2021042620
 	at org.apache.hadoop.hive.ql.metadata.Hive.moveFile(Hive.java:3221)
 	at org.apache.hadoop.hive.ql.exec.MoveTask.moveFileInDfs(MoveTask.java:120)
 	at org.apache.hadoop.hive.ql.exec.MoveTask.moveFile(MoveTask.java:97)
 	... 20 more
 Caused by: java.io.IOException: alluxio.exception.AlluxioException: HTTP/2 error code: PROTOCOL_ERROR
 Received Rst Stream
 	at alluxio.hadoop.AbstractFileSystem.delete(AbstractFileSystem.java:267)
 	at org.apache.hadoop.hive.ql.metadata.Hive.moveFile(Hive.java:3129)
 	... 22 more
 Caused by: alluxio.exception.AlluxioException: HTTP/2 error code: PROTOCOL_ERROR
 Received Rst Stream
 	at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:104)
 	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:549)
 	at alluxio.client.file.BaseFileSystem.delete(BaseFileSystem.java:187)
 	at alluxio.hadoop.AbstractFileSystem.delete(AbstractFileSystem.java:261)
 	... 23 more
 Caused by: alluxio.exception.status.InternalException: HTTP/2 error code: PROTOCOL_ERROR
 Received Rst Stream
 	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:153)
 	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
 	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:401)
 	at alluxio.AbstractClient.retryRPC(AbstractClient.java:365)
 	at alluxio.client.file.RetryHandlingFileSystemMasterClient.delete(RetryHandlingFileSystemMasterClient.java:173)
 	at alluxio.client.file.BaseFileSystem.lambda$delete$3(BaseFileSystem.java:190)
 	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:534)
 	... 25 more
 Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
 Received Rst Stream
 	at alluxio.shaded.client.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
 	at alluxio.shaded.client.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
 	at alluxio.shaded.client.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
 	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.remove(FileSystemMasterClientServiceGrpc.java:1757)
 	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$delete$5(RetryHandlingFileSystemMasterClient.java:173)
 	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:399)
 	... 29 more (state=08S01,code=1)
```

**Comment by loovia** [comment]
@apc999 Please take a look, thank you~

**Comment by apc999** [comment]
@ggezer @bf8086  do you know when GRPC receive `INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
 Received Rst Stream`?

**Comment by ggezer** [comment]
RST_STREAM will be one of the hardest errors to investigate since it's kind of an umbrella bug:
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

This could also give an idea as to where to look for at our side:
https://github.com/grpc/grpc-go/issues/576
