### ISSUE TITLE
FUSE directory remains with .fuse_hidden0000000900000001 file after trying to delete the directory.

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13324]
**Alluxio Version:**
2.5.0-2

**Describe the bug**
To test our system I have some unit tests that read and write to and from Alluxio. As in a typical unit test we try to clean everything up after the run.

However when creating a directory into Alluxio FUSE (with local storage as UFS), writing into it, and cleaning up after running some checks I see the following error in the Alluxio FUSE logs:
```
2021-04-30 07:25:11,463 ERROR AlluxioJniFuseFileSystem - Failed to delete /data/test_upload/testing/2021-04-30__07_24_51_JwRfXqmFEeuqHQJCrBoABA: 
alluxio.exception.DirectoryNotEmptyException: Cannot delete non-empty directory 2021-04-30__07_24_51_JwRfXqmFEeuqHQJCrBoABA because recursive is set to false
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:583)
	at alluxio.client.file.BaseFileSystem.delete(BaseFileSystem.java:189)
	at alluxio.client.file.FileSystem.delete(FileSystem.java:247)
	at alluxio.fuse.AlluxioJniFuseFileSystem.rmInternal(AlluxioJniFuseFileSystem.java:561)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$rmdir$11(AlluxioJniFuseFileSystem.java:548)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.rmdir(AlluxioJniFuseFileSystem.java:548)
	at alluxio.jnifuse.AbstractFuseFileSystem.rmdirCallback(AbstractFuseFileSystem.java:280)
```

And the following remaining file in the folder: `/data/test_upload/testing/2021-04-30__07_24_51_JwRfXqmFEeuqHQJCrBoABA/.fuse_hidden0000000900000001`. This file is not created by me.

Alluxio seemed to have deleted the files I created in the folder, however does not delete the folder itself because of this `.fuse_hidden0000000900000001` file being there. The user deleting the folder has write permissions on this file so it should be able to delete this file (but doesn't).

This `.fuse_hidden0000000900000001` file seems to stay in the directory, even after deleting the directory.

**Additional context 1**
What is weird is this `recursive is set to false`, which I also see in the master logs as:
```
2021-04-30 07:25:11,462 WARN  FileSystemMasterClientServiceHandler - Exit (Error): Remove: request=path: "/data/test_upload/testing/2021-04-30__07_24_51_JwRfXqmFEeuqHQJCrBoABA"
options {
  recursive: false
  alluxioOnly: false
  unchecked: false
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: DELETE
  }
}
, Error=Cannot delete non-empty directory 2021-04-30__07_24_51_JwRfXqmFEeuqHQJCrBoABA because recursive is set to falsey
```

I tried removing the directory at the end of my Python unit tests with both `os.system(f"rm -rf {_local_dir!s}")` and `shutil.rmtree(str(_local_dir))`, which both should recursively remove the directory. But for some reason this recursive delete is not picked up by Alluxio-FUSE.

**Additional context 2**
Using JNI-FUSE via `alluxio.fuse.jnifuse.enabled=true`.

I tried with both `alluxio.user.file.writetype.default=ASYNC_THROUGH` and `alluxio.user.file.writetype.default=CACHE_THROUGH`, with the same result

**logs**

Please find the logs here:
- [worker.log](https://github.com/Alluxio/alluxio/files/6403636/worker.log)
- [master.log](https://github.com/Alluxio/alluxio/files/6403637/master.log)
- [fuse.log](https://github.com/Alluxio/alluxio/files/6403638/fuse.log)

**To Reproduce**
I currently don't have any minimal reproducing code I can share, however I thought it would be best to already report this issue.

**Expected behavior**
FUSE folders being cleaned up correctly after deleting them.

**Urgency**
Medium

**Comment by peterroelants** [comment]
After reading a bit on the internet I found the following two posts that clarify a bit what those `.fuse_hidden****` files are:
- https://askubuntu.com/a/493206
- https://serverfault.com/a/478619

>  It means a file was deleted but there is at least one software which is still using it, so it can't be removed permanently.

It seems that something is still keeping my file open (even after my tests finished)

**Comment by peterroelants** [comment]
This seemed to be an issue with an underlying service that was not releasing the file properly: https://github.com/libvips/pyvips/issues/249
