### ISSUE TITLE
Race condition on alluxio/server/ft/MasterFailoverIntegrationTest.java#failoverJournalFencingTest

### ISSUE THREAD

**Issue by frankobe** [Alluxio/alluxio#13349]
**Alluxio Version:**
2.5.0 latest master branch head

**Describe the bug**
failoverJournalFencingTest fails due to 

**To Reproduce**
Clone the master branch head, run `failoverJournalFencingTest`, it fails due to race condition on rocksdb open

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start masters

	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:125)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.<init>(FaultTolerantAlluxioMasterProcess.java:61)
	at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:415)
	at alluxio.master.LocalAlluxioMaster.start(LocalAlluxioMaster.java:101)
	at alluxio.master.MultiMasterLocalAlluxioCluster.startMasters(MultiMasterLocalAlluxioCluster.java:247)
	at alluxio.master.AbstractLocalAlluxioCluster.restartMasters(AbstractLocalAlluxioCluster.java:106)
	at alluxio.server.ft.MasterFailoverIntegrationTest.failoverJournalFencingTest(MasterFailoverIntegrationTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to start masters
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:57)
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:123)
	... 21 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.rocksdb.RocksDBException: lock hold by current process, acquire time 1620321104 acquiring thread 123145521623040: /var/folders/w4/8ykm85hs099_xqql9j4c9lv00000gp/T/alluxio-tests/MasterFailoverIntegrationTest-failoverJournalFencingTest-9a9a410f-73db-41c0-887d-f1dbd5e536f4/metastore-1/inodes/LOCK: No locks available
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:593)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:555)
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:55)
	... 22 more
Caused by: java.lang.RuntimeException: org.rocksdb.RocksDBException: lock hold by current process, acquire time 1620321104 acquiring thread 123145521623040: /var/folders/w4/8ykm85hs099_xqql9j4c9lv00000gp/T/alluxio-tests/MasterFailoverIntegrationTest-failoverJournalFencingTest-9a9a410f-73db-41c0-887d-f1dbd5e536f4/metastore-1/inodes/LOCK: No locks available
	at alluxio.master.metastore.rocks.RocksStore.<init>(RocksStore.java:84)
	at alluxio.master.metastore.rocks.RocksInodeStore.<init>(RocksInodeStore.java:103)
	at alluxio.master.MasterUtils.lambda$getInodeStoreFactory$4(MasterUtils.java:93)
	at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:444)
	at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:423)
	at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:51)
	at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:28)
	at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: org.rocksdb.RocksDBException: lock hold by current process, acquire time 1620321104 acquiring thread 123145521623040: /var/folders/w4/8ykm85hs099_xqql9j4c9lv00000gp/T/alluxio-tests/MasterFailoverIntegrationTest-failoverJournalFencingTest-9a9a410f-73db-41c0-887d-f1dbd5e536f4/metastore-1/inodes/LOCK: No locks available
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:306)
	at alluxio.master.metastore.rocks.RocksStore.createDb(RocksStore.java:151)
	at alluxio.master.metastore.rocks.RocksStore.resetDb(RocksStore.java:110)
	at alluxio.master.metastore.rocks.RocksStore.<init>(RocksStore.java:82)
	... 11 more
```

**Expected behavior**
The test should pass

**Urgency**
Describe the impact and urgency of the bug.

**Comment by apc999** [comment]
@frankobe  this issue has been fixed by https://github.com/Alluxio/alluxio/pull/13175
We have 2.5.0-3 release including this fix
