### ISSUE TITLE
Journal flush failed. retrying...

### ISSUE THREAD

**Issue by loovia** [Alluxio/alluxio#13421]
**Alluxio Version:**
2.4.1-2

**Describe the bug**
master suddenly hangs up.
error log from master.log and keep printing:
```
2021-05-15 03:24:59,171 WARN  HdfsUnderFileSystem - Unable to rename hdfs://Thor/alluxio/alluxio_journal/BlockMaster/v1/logs/0x0-0x7fffffffffffffff to hdfs://Thor/alluxio/alluxio_journal/BlockMaster/v1/logs/0x0-0x9220d because source does not exist or is a directory
2021-05-15 03:24:59,173 WARN  AsyncJournalWriter - Failed to flush journal entry: Failed to rename journal log from hdfs://Thor/alluxio/alluxio_journal/BlockMaster/v1/logs/0x0-0x7fffffffffffffff to hdfs://Thor/alluxio/alluxio_journal/BlockMaster/v1/logs/0x0-0x9220d
java.io.IOException: Failed to rename journal log from hdfs://Thor/alluxio/alluxio_journal/BlockMaster/v1/logs/0x0-0x7fffffffffffffff to hdfs://Thor/alluxio/alluxio_journal/BlockMaster/v1/logs/0x0-0x9220d
        at alluxio.master.journal.ufs.UfsJournalLogWriter.completeLog(UfsJournalLogWriter.java:349)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.access$300(UfsJournalLogWriter.java:57)
        at alluxio.master.journal.ufs.UfsJournalLogWriter$JournalOutputStream.close(UfsJournalLogWriter.java:479)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.maybeRotateLog(UfsJournalLogWriter.java:282)
        at alluxio.master.journal.ufs.UfsJournalLogWriter.write(UfsJournalLogWriter.java:119)
        at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:286)
        at java.lang.Thread.run(Thread.java:748)
2021-05-15 03:24:59,175 WARN  MasterJournalContext - Journal flush failed. retrying...
```

**Comment by apc999** [comment]
@loovia from the messages, you are not using embedded journal but HDFS as a UFS journal, can you double check your configuration? https://docs.alluxio.io/os/user/stable/en/operation/Journal.html#configuring-embedded-journal

Back to what you see here, it looks to me, when you were flushing the journal, the HDFS was unavailable (possibly temporarily, can you check HDFS logs?). This caused `AsyncJournalWriter` to print a warning and would trigger retries.
At this moment, because the journal is waiting for retrying to flush, all WRITE operations will be blocked until journal is flushed.

In your deployment, do you see the master back to normal or hang there since then?
