### ISSUE TITLE
HeartbeatThread NullPointerException

### ISSUE THREAD

**Issue by shenghui361** [Alluxio/alluxio#13430]
**Alluxio Version:**
2.5.0-3

**Describe the bug**
2021-05-17 16:48:54,268 ERROR HeartbeatThread - Uncaught exception in heartbeat executor, Heartbeat Thread shutting down
java.lang.NullPointerException
        at alluxio.master.metastore.rocks.RocksBlockStore.removeLocation(RocksBlockStore.java:185)
        at alluxio.master.block.DefaultBlockMaster.processWorkerRemovedBlocks(DefaultBlockMaster.java:973)
        at alluxio.master.block.DefaultBlockMaster.processLostWorker(DefaultBlockMaster.java:1139)
        at alluxio.master.block.DefaultBlockMaster.access$400(DefaultBlockMaster.java:119)
        at alluxio.master.block.DefaultBlockMaster$LostWorkerDetectionHeartbeatExecutor.heartbeat(DefaultBlockMaster.java:1103)
        at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by apc999** [comment]
@shenghui361 when you see this issue, are you in the middle of actions like shutting down masters? It will be very helpful for us to know when it happens. Also, can you share your `master.log` ?

@jiacheliu3  FYI

**Comment by apc999** [comment]
Ping @shenghui361  possibly to share your `master.log`?
