### ISSUE TITLE
Attachdb action report error when using Alluxio SDS

### ISSUE THREAD

**Issue by bzheng888** [Alluxio/alluxio#13492]
**Alluxio Version:**
2.5.0-3

**Describe the bug**
Sync errors: 
Table test failed to sync: java.lang.IllegalArgumentException: Can not create a uri with a null path.
Table test failed to sync: java.lang.IllegalArgumentException: Can not create a uri with a null path.
Table test failed to sync: java.lang.IllegalArgumentException: Can not create a uri with a null path.
Table test failed to sync: java.io.IOException: Failed to get table: xxx error: [OMS Internal Error]xxx partition p1 has more than one values. Currently do not support this kind of partition
Table test failed to sync: java.io.IOException: Failed to mount table location. tableName: test hiveUfsLocation: hdfs://xxx/user/xxx/warehouse/test.db/xxx AlluxioLocation: /catalog/test/tables/xxx/hive error: Ufs path hdfs://xxx/user/xxx/warehouse/test.db/xxx does not exist
Table xxx failed to sync: java.io.IOException: Failed to mount table location. tableName: xxx hiveUfsLocation: hdfs://xxx/user/xxx/warehouse/test.db/xxx AlluxioLocation: /catalog/test/tables/xxx/hive error: Ufs path hdfs://xxx/user/xxx/warehouse/test.db/xxx does not exist
Table test failed to sync: java.io.IOException: Failed to get table: test error: [OMS Internal Error]test partition age has more than one values. Currently do not support this kind of partition
Table test failed to sync: java.io.IOException: Failed to get table: test error: [OMS Internal Error]test partition sub_1 has more than one values. Currently do not support this kind of partition
Table test failed to sync: java.lang.IllegalArgumentException: Can not create a uri with a null path.
Table test failed to sync: java.io.IOException: Failed to get table: test error: [OMS Internal Error]test partition sub_par1 has more than one values. Currently do not support this kind of partition

**To Reproduce**
> bin/alluxio table attachdb -o udb-hive.mount.option.{xxx}.alluxio.underfs.version=xxx -o udb-hive.mount.option.{hdfs://xxx}.alluxio.underfs.version=xxx -o udb-hive.mount.option.{hdfs://xxx}.alluxio.underfs.version=xxx hive thrift://xxx:xxx test

**Expected behavior**
attachdb operation succeesfull 

**Urgency**
If we do not give the "--ignore-sync-errors" option the  attachdb action will failed

**Additional context**

**Comment by HelloHorizon** [comment]
@bzheng888 Do you mind providing the corresponding error message in master.log?

**Comment by maobaolong** [comment]
```

2021-05-27 11:22:04,540 ERROR Database - Sync thread failed for test.xxx_listpartition2
java.io.IOException: Failed to get table: xxx_listpartition2 error: [OMS Internal Error]test.xxx_listpartition2 partition sub_par1 has more than one values. Currently do not support this kind of partition
        at alluxio.table.under.hive.HiveDatabase.getTable(HiveDatabase.java:293)
        at alluxio.master.table.Database.lambda$sync$8(Database.java:232)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: MetaException(message:[OMS Internal Error]test.xxx_listpartition2 partition sub_par1 has more than one values. Currently do not support this kind of partition)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_req_result$get_table_req_resultStandardScheme.read(ThriftHiveMetastore.java:55210)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_req_result$get_table_req_resultStandardScheme.read(ThriftHiveMetastore.java:55187)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_req_result.read(ThriftHiveMetastore.java:55118)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_req(ThriftHiveMetastore.java:1567)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_req(ThriftHiveMetastore.java:1554)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1350)
        at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169)
        at com.sun.proxy.$Proxy125.getTable(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at alluxio.table.under.hive.util.CompatibleMetastoreClient.invoke(CompatibleMetastoreClient.java:39)
        at com.sun.proxy.$Proxy125.getTable(Unknown Source)
        at alluxio.table.under.hive.HiveDatabase.getTable(HiveDatabase.java:208)
        ... 5 more

```

@HelloHorizon Thanks for check this issue, this callstack is a clue of this issue.

**Comment by HelloHorizon** [comment]
@maobaolong can I know which version of Hive are you using now?
