### ISSUE TITLE
Met grpc error: Panic! This is a bug! when using presto on alluxio

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13493]
**Alluxio Version:**
2.5.0-3

**Describe the bug**

`select * from test.test` in the presto-cli, will through exception when using alluxio, it can query successfully without using alluxio.

![image](https://user-images.githubusercontent.com/17329931/119785529-da1ae400-bf01-11eb-8b0f-3492e301ef00.png)

![image](https://user-images.githubusercontent.com/17329931/119785609-f3239500-bf01-11eb-9661-0c9b2a247903.png)

Through the webui, we can find the file under the table has been loaded.

![image](https://user-images.githubusercontent.com/17329931/119785805-2403ca00-bf02-11eb-893e-783046084b73.png)

**To Reproduce**

A test table with a single part file in it, just 200+ bytes contents.

`select * from test.test` 

**Expected behavior**

**Urgency**

Urgency, block production business

**Additional context**

No

**Comment by maobaolong** [comment]
```
2021-05-27T15:20:48.775+0800    DEBUG   query-execution-9       com.facebook.presto.execution.QueryStateMachine Query 20210527_072048_00017_n7cbm failed
com.facebook.presto.spi.PrestoException: Received exception from 192.168.1.100:19998. message: Panic! This is a bug!
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:215)
        at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
        at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
        at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
        at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Received exception from 192.168.1.100:19998. message: Panic! This is a bug!
        at alluxio.master.PollingMasterInquireClient.getAddress(PollingMasterInquireClient.java:134)
        at alluxio.master.PollingMasterInquireClient.getPrimaryRpcAddress(PollingMasterInquireClient.java:107)
        at alluxio.AbstractMasterClient.getAddress(AbstractMasterClient.java:63)
        at alluxio.AbstractClient.connect(AbstractClient.java:216)
        at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:533)
        at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:284)
        at alluxio.client.file.FileSystem.listStatus(FileSystem.java:361)
        at alluxio.hadoop.AbstractFileSystem.listStatus(AbstractFileSystem.java:586)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1554)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1597)
        at org.apache.hadoop.fs.FileSystem$4.<init>(FileSystem.java:1760)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1759)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1742)
        at org.apache.hadoop.fs.HadoopExtendedFileSystem.listLocatedStatus(HadoopExtendedFileSystem.java:242)
        at com.facebook.presto.hive.HadoopDirectoryLister.lambda$list$0(HadoopDirectoryLister.java:45)
        at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:126)
        at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:114)
        at com.facebook.presto.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:103)
        at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:96)
        at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:40)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:282)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:105)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:208)
        ... 7 more
Caused by: alluxio.exception.status.InternalException: Panic! This is a bug!
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:153)
        at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
        at alluxio.exception.status.AlluxioStatusException.fromThrowable(AlluxioStatusException.java:208)
        at alluxio.master.PollingMasterInquireClient.pingMetaService(PollingMasterInquireClient.java:157)
        at alluxio.master.PollingMasterInquireClient.getAddress(PollingMasterInquireClient.java:123)
        ... 37 more
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
        at alluxio.grpc.ServiceVersionClientServiceGrpc$ServiceVersionClientServiceBlockingStub.getServiceVersion(ServiceVersionClientServiceGrpc.java:184)
        at alluxio.master.PollingMasterInquireClient.pingMetaService(PollingMasterInquireClient.java:154)
        ... 38 more
Caused by: java.util.concurrent.RejectedExecutionException: event executor terminated
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor.lazyExecute(SingleThreadEventExecutor.java:823)
        at alluxio.shaded.client.io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:263)
        at alluxio.shaded.client.io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:177)
        at alluxio.shaded.client.io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:50)
        at alluxio.shaded.client.io.netty.util.concurrent.AbstractEventExecutorGroup.schedule(AbstractEventExecutorGroup.java:32)
        at alluxio.shaded.client.io.grpc.internal.Rescheduler.reschedule(Rescheduler.java:63)
        at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl.rescheduleIdleTimer(ManagedChannelImpl.java:414)
        at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:372)
        at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:473)
        at alluxio.shaded.client.io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
        at alluxio.shaded.client.io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
        at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:477)
        at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:253)
        at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:210)
        at alluxio.shaded.client.io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
        at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1.start(GrpcChannel.java:165)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.startCall(ClientCalls.java:315)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:287)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)
        ... 40 more
```

This is a call stack from presto server.log

**Comment by maobaolong** [comment]
```

presto> SHOW CREATE TABLE hive.test.test;
                                                            Create Table                                                            
------------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE hive.test.test (                                                                                                      
    x integer,                                                                                                                      
    b integer                                                                                                                       
 )                                                                                                                                  
 WITH (                                                                                                                             
    format = 'ORC',                                                                                                                 
    location = 'alluxio://192.168.1.100:19998,192.168.1.101:19998,192.168.1.102:19998/hive/warehouse/test.db/test', 
    serde = 'org.apache.hadoop.hive.ql.io.orc.OrcSerde'                                                                             
 )                                                                                                                                  
(1 row)

Query 20210527_083237_00068_n7cbm, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```
