### ISSUE TITLE
lock  exception

### ISSUE THREAD

**Issue by shenghui361** [Alluxio/alluxio#13491]
**Alluxio Version:**
2.4.1

**Describe the bug**
MOD-1621884814495 (/tmp/.cache/27af9c1fb3ae41bd194d7b8531305bf0/MOD-1621884814495) and
segment_5000000.gz (/dw/user/hive/warehouse/dm_bdpfsimage.db/cfo_hdfs/_copying_20210527/segment_5000000.gz) are are two unrelated inodes. 

2021-05-27 09:52:45,271 ERROR FileSystemMasterClientServiceHandler - Exit (Error): GetStatus: request=path: "/dw/user/hive/warehouse/dm_bdpfsimage.db/cfo_hdfs/_copying_20210527/segment_5000000.gz"
options {
  loadMetadataType: ONCE
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: DELETE
  }
}

java.lang.IllegalStateException: Expected to lock inode segment_5000000.gz but locked inode MOD-1621884814495
        at com.google.common.base.Preconditions.checkState(Preconditions.java:824)
        at alluxio.master.file.meta.SimpleInodeLockList.lockInode(SimpleInodeLockList.java:92)
        at alluxio.master.file.meta.LockedInodePath.traverse(LockedInodePath.java:439)
        at alluxio.master.file.meta.InodeTree.lockInodePath(InodeTree.java:409)
        at alluxio.master.file.meta.InodeTree.lockInodePath(InodeTree.java:391)
        at alluxio.master.file.meta.InodeTree.lockInodePath(InodeTree.java:377)
        at alluxio.master.file.DefaultFileSystemMaster.getFileInfo(DefaultFileSystemMaster.java:857)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$getStatus$8(FileSystemMasterClientServiceHandler.java:222)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
        at alluxio.RpcUtils.call(RpcUtils.java:78)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.getStatus(FileSystemMasterClientServiceHandler.java:219)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2255)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1356)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by LuQQiu** [comment]
@ggezer @rastogiasr FYI

**Comment by apc999** [comment]
ping @ggezer

**Comment by apc999** [comment]
@shenghui361 we have seen users reporting similar errors before and upgrading to alluxio 2.5 resolves it.
Can you try it?

**Comment by shenghui361** [comment]
@apc999    after upgrading to version 2.5.0-3, it does not appear again.

**Comment by ggezer** [comment]
Thanks for confirmation @shenghui361.
Closing until further repro...
