### ISSUE TITLE
Master failed to start with hadoop dependency changes

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#13490]
**Alluxio Version:**
Master with commit from https://github.com/Alluxio/alluxio/pull/12783

**Describe the bug**
In a sanity check cluster with Alluxio cluster + HDFS as root UFS,
when starting the Alluxio master, error

```
Caused by: java.lang.IllegalArgumentException: Unable to create an UnderFileSystem instance for path: hdfs://SanityMicrobench-masters-1:9000/alluxio_storage
        at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:122)
        at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:132)
        at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:171)
        at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:61)
        at alluxio.master.file.DefaultFileSystemMaster.getRootMountInfo(DefaultFileSystemMaster.java:502)
        at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:444)
        at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:425)
        at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:51)
        at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:28)
        at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration
                at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<init>(DefaultMetricsSystem.java:38)
                at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<clinit>(DefaultMetricsSystem.java:36)
                at org.apache.hadoop.security.UserGroupInformation$UgiMetrics.create(UserGroupInformation.java:121)
                at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:237)
                at alluxio.underfs.hdfs.HdfsUnderFileSystem.<init>(HdfsUnderFileSystem.java:150)
                at alluxio.underfs.hdfs.HdfsUnderFileSystem.createInstance(HdfsUnderFileSystem.java:108)
                at alluxio.underfs.hdfs.HdfsUnderFileSystemFactory.create(HdfsUnderFileSystemFactory.java:43)
                at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:107)
                ... 13 more
        Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration.Configuration
                at java.lang.ClassLoader.findClass(ClassLoader.java:523)
                at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.findClass(ExtensionsClassLoader.java:43)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.loadClass(ExtensionsClassLoader.java:53)
                at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:84)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```
shown and master failed to come up, will create an issue for that
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by maobaolong** [comment]
@LuQQiu Lu, thanks for catching this issue and reverting it for me. Would you please add some reproduce step, and I could fix this bug base on it.

**Comment by LuQQiu** [comment]
@Xenorith can you help provide more details?

**Comment by Xenorith** [comment]
the current description describes most of the details already. i believe this should reproduce when trying to start any alluxio cluster with HDFS configured as its root ufs mount. i used apache hadoop 2.7.2 for HDFS in this cluster. the alluxio configuration in the cluster that failed is:
```
alluxio.home=/tmp/alluxio
alluxio.master.embedded.journal.addresses=SanityMicrobench-masters-1:19200,SanityMicrobench-masters-2:19200
alluxio.master.mount.table.root.option.alluxio.underfs.version=2.7
alluxio.underfs.version=2.7
alluxio.worker.tieredstore.levels=1
alluxio.master.hostname=SanityMicrobench-masters-1
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.master.journal.type=EMBEDDED
alluxio.user.hostname=SanityMicrobench-masters-1
alluxio.underfs.hdfs.configuration=/tmp/hadoop/etc/hadoop/core-site.xml:/tmp/hadoop/etc/hadoop/hdfs-site.xml
alluxio.underfs.hdfs.remote=false
alluxio.worker.tieredstore.level0.dirs.quota=10GB
alluxio.master.mount.table.root.ufs=hdfs://SanityMicrobench-masters-1:9000/alluxio_storage/
```
and alluxio-env.sh contains
```
#!/usr/bin/env bash
ALLUXIO_CLASSPATH=$ALLUXIO_CLASSPATH:/tmp/hadoop/etc/hadoop
ALLUXIO_MASTER_MOUNT_TABLE_ROOT_UFS=${ALLUXIO_MASTER_MOUNT_TABLE_ROOT_UFS:-hdfs://SanityMicrobench-masters-1:9000/alluxio_storage/}
ALLUXIO_JAVA_OPTS+=" -XX:+PreserveFramePointer"
ALLUXIO_RAM_FOLDER=${ALLUXIO_RAM_FOLDER:-/mnt/ramdisk}
ALLUXIO_WORKER_MEMORY_SIZE=${ALLUXIO_WORKER_MEMORY_SIZE:-10GB}
```

note that apache hadoop is installed in `/tmp/hadoop` in this cluster. although this cluster was launched with 2 masters for HA with embedded journal, i don't think HA or embedded journal are necessary given the nature of the error message. i would first try to connect a local alluxio cluster (single master, single worker on a local machine) to an existing HDFS cluster and see if the problem appears when starting the master process.

if your repro attempts fail, i can spend more time creating a better repro that you can launch yourself, maybe through AWS EMR?

**Comment by maobaolong** [comment]
@Xenorith Thanks for the help, I've reproduced this issue, it can works well with `alluxio.underfs.version=3.2` which is the default ufs version, but failed to start for `2.x`. Will take a further look.

**Comment by maobaolong** [comment]
@Xenorith @LuQQiu  I submit a new PR to bring the #15237  back, PTAL.
