### ISSUE TITLE
Master failed to start with kerberosed HDFS RBF

### ISSUE THREAD

**Issue by BUPTAnderson** [Alluxio/alluxio#13507]
**Alluxio Version:**
2.5.0-1 2.6.0-SNAPSHOT

Underfs:
kerberosed HDFS RBF
Underfs Version:
3.2.0

Underfs Setting:
alluxio.master.mount.table.root.ufs=hdfs://router/alluxio-multi-media/underFSStorage
alluxio.master.backup.directory=hdfs://router/alluxio-multi-media/alluxio_backups
alluxio.master.journal.type=UFS
alluxio.master.journal.folder=hdfs://router/alluxio-multi-media/journal/

**Describe the bug**
```
Caused by: java.io.IOException: Couldn't set up IO streams: java.lang.NoClassDefFoundError: alluxio/shaded/hdfs/com/google/re2j/PatternSyntaxException
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:866)
        at org.apache.hadoop.ipc.Client$Connection.access$3700(Client.java:411)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1572)
        at org.apache.hadoop.ipc.Client.call(Client.java:1403)
        ... 33 more
Caused by: java.lang.NoClassDefFoundError: alluxio/shaded/hdfs/com/google/re2j/PatternSyntaxException
        at org.apache.hadoop.security.SaslRpcClient.getServerPrincipal(SaslRpcClient.java:311)
        at org.apache.hadoop.security.SaslRpcClient.createSaslClient(SaslRpcClient.java:234)
        at org.apache.hadoop.security.SaslRpcClient.selectSaslClient(SaslRpcClient.java:160)
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:390)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:617)
        at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:411)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:804)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:800)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:800)
        ... 36 more
Caused by: java.lang.ClassNotFoundException: alluxio.shaded.hdfs.com.google.re2j.PatternSyntaxException
        at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:718)
        at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.findClass(ExtensionsClassLoader.java:43)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.loadClass(ExtensionsClassLoader.java:53)
        at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:84)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 48 more
```

Additional context:
In the class `org.apache.hadoop.security.SaslRpcClient`, method `getServerPrincipal`:
<pre>
if (serverKeyPattern != null && !serverKeyPattern.isEmpty()) {
      Pattern pattern = <strong>GlobPattern</strong>.compile(serverKeyPattern);
      if (!pattern.matcher(serverPrincipal).matches())
        throw new IllegalArgumentException(String.format("Server has invalid Kerberos principal: %s, doesn't match the pattern: %s", new Object[] { serverPrincipal, serverKeyPattern })); 
    } else {
</pre>

and in `org.apache.hadoop.fs.GlobPattern`:
<pre>
package org.apache.hadoop.fs;

<strong>import alluxio.shaded.hdfs.com.google.re2j.Pattern;</strong>
<strong>import alluxio.shaded.hdfs.com.google.re2j.PatternSyntaxException;</strong>
import org.apache.hadoop.classification.InterfaceAudience.Private;
import org.apache.hadoop.classification.InterfaceStability.Evolving;

@Private
@Evolving
public class GlobPattern {
</pre>

**Comment by BUPTAnderson** [comment]
assign @BUPTAnderson
