### ISSUE TITLE
Does not work the front of the ALLUXIO_JAVA_OPTS environment variable.

### ISSUE THREAD

**Issue by kwnam1302** [Alluxio/alluxio#13537]
**Alluxio Version:**

2.4.1

**Describe the bug**

Does not work the front of the `ALLUXIO_JAVA_OPTS` environment variable.

**To Reproduce**

alluxio-env.sh
```
export ALLUXIO_JAVA_OPTS="-Djava.security.krb5.realm=EXAMPLE.COM  -Djava.security.krb5.kdc=dev-kdc-test.com -Dalluxio.site.conf.dir=/alluxio-site"
export ALLUXIO_MASTER_JAVA_OPTS="-Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} -Djava.library.path=/opt/alluxio-2.4.1/conf/::/opt/alluxio-2.4.1/assembly/alluxio-server-2.4.1.jar:/opt/alluxio-2.4.1/lib/alluxio-shaded-hadoop-3.3.0.jar"
```

alluxio-master was failed as below.
the front of `ALLUXIO_JAVA_OPTS` was appended to the end of the `ALLUXIO_MASTER_JAVA_OPTS`.

```
2021-06-02 07:28:00,965 DEBUG FileSystem$Factory - java.library.path=/opt/alluxio-2.4.1/conf/::/opt/alluxio-2.4.1/assembly/alluxio-server-2.4.1.jar:/opt/alluxio-2.4.1/lib/alluxio-shaded-hadoop-3.3.0.jar-Djava.security.krb5.realm=EXAMPLE.COM (SYSTEM_PROPERTY)
2021-06-02 07:28:00,965 DEBUG FileSystem$Factory - java.security.krb5.kdc=dev-kdc-test.com (SYSTEM_PROPERTY)
...
Caused by: java.lang.IllegalArgumentException: Unable to create an UnderFileSystem instance for path: hdfs://test/alluxio
        at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:122)
        at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:128)
        at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:167)
        at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:60)
        at alluxio.master.file.DefaultFileSystemMaster.getRootMountInfo(DefaultFileSystemMaster.java:495)
        at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:437)
        at alluxio.master.file.DefaultFileSystemMaster.<init>(DefaultFileSystemMaster.java:418)
        at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:51)
        at alluxio.master.file.FileSystemMasterFactory.create(FileSystemMasterFactory.java:28)
        at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.IllegalArgumentException: Can't get Kerberos realm
                at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
                at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:318)
                at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:364)
                at alluxio.underfs.hdfs.HdfsUnderFileSystem.<init>(HdfsUnderFileSystem.java:150)
                at alluxio.underfs.hdfs.HdfsUnderFileSystem.createInstance(HdfsUnderFileSystem.java:108)
                at alluxio.underfs.hdfs.HdfsUnderFileSystemFactory.create(HdfsUnderFileSystemFactory.java:43)
                at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:107)
                ... 13 more
```

**Expected behavior**

`ALLUXIO_JAVA_OPTS` is working as expected

**Urgency**

not critical

**Additional context**

Here is `alluxio-config.sh`
```
..
# Master specific parameters based on ALLUXIO_JAVA_OPTS.
ALLUXIO_MASTER_JAVA_OPTS+=${ALLUXIO_JAVA_OPTS}
ALLUXIO_MASTER_JAVA_OPTS+=" -Dalluxio.logger.type=${ALLUXIO_MASTER_LOGGER:-MASTER_LOGGER}"
ALLUXIO_MASTER_JAVA_OPTS+=" -Dalluxio.master.audit.logger.type=${ALLUXIO_MASTER_AUDIT_LOGGER:-MASTER_AUDIT_LOGGER}"
if [[ -n "${ALLUXIO_LOGSERVER_HOSTNAME}" && -n "${ALLUXIO_LOGSERVER_PORT}" ]]; then
    ALLUXIO_MASTER_JAVA_OPTS+=" -Dalluxio.remote.logger.type=REMOTE_MASTER_LOGGER"
fi
```
`ALLUXIO_JAVA_OPTS` will be appended at the end of the `ALLUXIO_MASTER_JAVA_OPTS` without space.

**Comment by apc999** [comment]
@kwnam1302  thanks for reporting this issue! I created a patch #13544 to address it.

**Comment by kwnam1302** [comment]
@apc999 thank you for fixing the issue!
