### ISSUE TITLE
Update start guide documents

### ISSUE THREAD

**Issue by codings-dan** [Alluxio/alluxio#13575]
**Page**
Include the link to the page you are reporting a defect
https://docs.alluxio.io/os/user/stable/en/overview/Getting-Started.html

**Summary**

There is an error when running 
 ./bin/alluxio format locally. 
It is recommended to modify the document according to 
https://github.com/Alluxio/alluxio/issues/9687#issuecomment-520652070

**Comment by apc999** [comment]
@codings-dan , can you post what errors you see?
is it same as #9687 ?

**Comment by apc999** [comment]
ping @codings-dan

**Comment by codings-dan** [comment]
@apc999 When I run the “./bin/alluxio format” command, the error message is similar to #9687, and the log is as follows:


Executing the following command on all worker nodes and logging to /home/bot/桌面/project/alluxio/logs/task.log: /home/bot/桌面/project/alluxio/bin/alluxio formatWorker
[localhost] Connecting as bot...
[2021-06-18 19:51:11][localhost] nohup: 忽略输入
[2021-06-18 19:51:16][localhost] Formatting Alluxio Worker @ localhost
[2021-06-18 19:51:16][localhost] 2021-06-18 19:51:16,640 INFO  Format - Formatting worker data folder: /alluxioworker/
[2021-06-18 19:51:16][localhost] 2021-06-18 19:51:16,641 INFO  Format - Formatting Data path for tier 0:/mnt/ramdisk/alluxioworker
[2021-06-18 19:51:16][localhost] 2021-06-18 19:51:16,643 ERROR Format - Failed to format
[2021-06-18 19:51:16][localhost] java.nio.file.NoSuchFileException: /mnt/ramdisk/alluxioworker
[2021-06-18 19:51:16][localhost] at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[2021-06-18 19:51:16][localhost] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[2021-06-18 19:51:16][localhost] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[2021-06-18 19:51:16][localhost] at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
[2021-06-18 19:51:16][localhost] at java.nio.file.Files.createDirectory(Files.java:674)
[2021-06-18 19:51:16][localhost] at alluxio.cli.Format.formatWorkerDataFolder(Format.java:67)
[2021-06-18 19:51:16][localhost] at alluxio.cli.Format.format(Format.java:138)
[2021-06-18 19:51:16][localhost] at alluxio.cli.Format.main(Format.java:98)
[2021-06-18 19:51:16][localhost] Connection to localhost closed.
Executing the following command on all master nodes and logging to /home/bot/桌面/project/alluxio/logs/task.log: /home/bot/桌面/project/alluxio/bin/alluxio formatJournal
[localhost] Connecting as bot...
[2021-06-18 19:51:18][localhost] nohup: 忽略输入
[2021-06-18 19:51:22][localhost] Formatting Alluxio Master @ localhost
[2021-06-18 19:51:22][localhost] 2021-06-18 19:51:22,390 INFO  Format - Formatting master journal: /home/bot/桌面/project/alluxio/journal/
[2021-06-18 19:51:22][localhost] 2021-06-18 19:51:22,464 INFO  Format - Formatting complete
[2021-06-18 19:51:22][localhost] Connection to localhost closed.
