### ISSUE TITLE
Support create full tier storage path instead of the last child folder

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#13609]
**Alluxio Version:**
Master 9403ae042c8479f5764a86e9494013f56e2940e7

**Describe the bug**
```
$ sudo mkdir /alluxio
$ chmod 777 /alluxio
$ docker run --rm     --net=host     --name=alluxio-worker     -v /alluxio:/alluxio     --cap-add SYS_ADMIN     --device /dev/fuse     --security-opt apparmor:unconfined     -e ALLUXIO_JAVA_OPTS=" \
       -Dalluxio.worker.hostname=ip-172-31-38-117.ec2.internal \
       -Dalluxio.user.hostname=ip-172-31-38-117.ec2.internal \
       -Dalluxio.master.hostname=ip-172-31-47-167.ec2.internal \
>        -Daws.accessKeyId=<> \
>        -Daws.secretKey=<> \
>        -Dalluxio.master.mount.table.root.ufs=s3://<>/ \
>        -Dalluxio.master.journal.type=UFS \
>        -Dalluxio.master.journal.folder=/alluxio/journal \
>        -Dalluxio.worker.tieredstore.levels=1 \
>        -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD \
>        -Dalluxio.worker.tieredstore.level0.alias=SSD \
>        -Dalluxio.worker.tieredstore.level0.dirs.path=/alluxio/alluxio-ssd \
>        -Dalluxio.worker.tieredstore.level0.dirs.quota=300GB \
>        -Dalluxio.worker.fuse.enabled=true \
>        -Dalluxio.worker.fuse.mount.alluxio.path=/ \
>        -Dalluxio.worker.fuse.mount.point=/alluxio/alluxio-fuse \
>        -Dalluxio.worker.fuse.mount.options=allow_other,kernel_cache,max_read=131072,attr_timeout=7200,entry_timeout=7200 \
>        -Dalluxio.user.metadata.cache.enabled=false \
>        -Dalluxio.user.metadata.cache.expiration.time=1h \
>        -Dalluxio.user.metadata.cache.max.size=10000000 \
>        -Dalluxio.user.update.file.accesstime.disabled=true \
>        -Dalluxio.user.file.passive.cache.enabled=false"     luqqiu/alluxio:2.6.0-SNAPSHOT-f2fd707ae6 worker
> Formatting Alluxio Worker @ ip-172-31-38-117.ec2.internal
> 2021-06-08 22:31:50,126 INFO  Format - Formatting worker data folder: /alluxioworker/
> 2021-06-08 22:31:50,127 INFO  Format - Formatting Data path for tier 0:/alluxio/alluxio-ssd/alluxioworker
> 2021-06-08 22:31:50,129 ERROR Format - Failed to format
> java.nio.file.NoSuchFileException: /alluxio/alluxio-ssd/alluxioworker
> at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
> at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
> at java.nio.file.Files.createDirectory(Files.java:674)
> at alluxio.cli.Format.formatWorkerDataFolder(Format.java:67)
> at alluxio.cli.Format.format(Format.java:138)
> at alluxio.cli.Format.main(Format.java:98)
```
When createDirectory of the last child folder failed, can we support creating the full path? 

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by LuQQiu** [comment]
Note that this behavior is not deterministic but frequently appeared
