### ISSUE TITLE
when hive metadata had drop one database,alluxio udb failed,causes alluxio to fail to start

### ISSUE THREAD

**Issue by xinip** [Alluxio/alluxio#13719]
**Alluxio Version:**
2.5.0-1

**Describe the bug**
when hive metadata had drop one database,alluxio udb failed,causes alluxio to fail to start

**To Reproduce**
1.hive create one database: test_db,
2.attachdb the test_db to alluxio udb,
3.detachdb the test_db alluxio udb
4.then restart alluxio.it‘s failed start

**Expected behavior**
should normal start

**Urgency**
very urgent

**Additional context**
ERROR JournalUtils - Journal replay error: Failed to process journal entry attach_db {
  udb_type: "hive"
  udb_connection_uri: "thrift://10.0.0.1:19088"
  udb_db_name: "test_db"
  db_name: "test_db"
}
 from a journal checkpoint
java.lang.IllegalArgumentException: Creating udb failed for database name: test_db
        at alluxio.master.table.Database.create(Database.java:104)
        at alluxio.master.table.AlluxioCatalog.apply(AlluxioCatalog.java:370)
        at alluxio.master.table.AlluxioCatalog.processJournalEntry(AlluxioCatalog.java:402)
        at alluxio.master.journal.JournalUtils.restoreJournalEntryCheckpoint(JournalUtils.java:112)
        at alluxio.master.journal.Journaled.restoreFromCheckpoint(Journaled.java:61)
        at alluxio.master.journal.JournalUtils.restoreFromCheckpoint(JournalUtils.java:157)
        at alluxio.master.journal.JournaledGroup.restoreFromCheckpoint(JournaledGroup.java:80)
        at alluxio.master.journal.DelegatingJournaled.restoreFromCheckpoint(DelegatingJournaled.java:55)
        at alluxio.master.journal.JournalUtils.restoreFromCheckpoint(JournalUtils.java:157)
        at alluxio.master.journal.raft.JournalStateMachine.install(JournalStateMachine.java:502)
        at alluxio.master.journal.raft.JournalStateMachine.loadSnapshot(JournalStateMachine.java:180)
        at alluxio.master.journal.raft.JournalStateMachine.lambda$initialize$1(JournalStateMachine.java:154)
        at org.apache.ratis.util.LifeCycle.startAndTransition(LifeCycle.java:214)
        at alluxio.master.journal.raft.JournalStateMachine.initialize(JournalStateMachine.java:149)
        at org.apache.ratis.server.impl.ServerState.initStatemachine(ServerState.java:160)
        at org.apache.ratis.server.impl.ServerState.<init>(ServerState.java:112)
        at org.apache.ratis.server.impl.RaftServerImpl.<init>(RaftServerImpl.java:122)
        at org.apache.ratis.server.impl.RaftServerProxy.lambda$newRaftServerImpl$2(RaftServerProxy.java:213)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Failed to create UnderDb by factory alluxio.table.under.hive.HiveDatabaseFactory@34ff8919
        at alluxio.table.common.udb.UnderDatabaseRegistry.create(UnderDatabaseRegistry.java:133)
        at alluxio.master.table.Database.create(Database.java:101)
        ... 21 more
Caused by: java.lang.RuntimeException: hive db name 'test_db' does not exist at metastore: thrift://10.0.0.1:19088
        at alluxio.table.under.hive.HiveDatabase.create(HiveDatabase.java:107)
        at alluxio.table.under.hive.HiveDatabaseFactory.create(HiveDatabaseFactory.java:32)
        at alluxio.table.common.udb.UnderDatabaseRegistry.create(UnderDatabaseRegistry.java:129)
        ... 22 more
Caused by: NoSuchObjectException(message:dc_bj_qj)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result$get_database_resultStandardScheme.read(ThriftHiveMetastore.java:27584)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result$get_database_resultStandardScheme.read(ThriftHiveMetastore.java:27561)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_database_result.read(ThriftHiveMetastore.java:27492)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_database(ThriftHiveMetastore.java:782)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_database(ThriftHiveMetastore.java:769)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getDatabase(HiveMetaStoreClient.java:1290)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169)
        at com.sun.proxy.$Proxy16.getDatabase(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at alluxio.table.under.hive.util.CompatibleMetastoreClient.invoke(CompatibleMetastoreClient.java:39)
        at com.sun.proxy.$Proxy16.getDatabase(Unknown Source)
        at alluxio.table.under.hive.HiveDatabase.create(HiveDatabase.java:104)
        ... 24 more

**Comment by maobaolong** [comment]
@HelloHorizon @apc999 Separate SDS from Alluxio Master will never cause Aluxio Master failed to start.
