### ISSUE TITLE
MapReduce On Alluxio-Http2Exception: First received frame was not SETTINGS

### ISSUE THREAD

**Issue by xpleaf** [Alluxio/alluxio#13710]
**Alluxio Version:**
2.6

**Describe the bug**

- **Failed to run MapReduce App on alluxio**

My environment is like this.

Node **leaf** runs hadoop：

```shell
$ jps6992 ResourceManager
24804 NameNode
7108 NodeManager
25124 SecondaryNameNode
21406 Jps
24942 DataNode
```

Node **alluxio01** **allxio02** **alluxio03** runs alluxio:

```shell
alluxio01 $ jps
8417 AlluxioJobMaster
7890 AlluxioMaster
8985 AlluxioProxy
22831 Jps
alluxio02 $ jps
9954 Jps
29749 AlluxioWorker
30278 AlluxioProxy
29982 AlluxioJobWorker
alluxio03 $ jps
28916 AlluxioWorker
9111 Jps
29434 AlluxioProxy
29149 AlluxioJobWorker
```

I built a 3-node Aluxio cluster according to the official documentation.

The four nodes mentioned above are all accessible to each other, and I have turned off the firewall (for research on Aluxio).Then I submit an application using the following command according to the official documentation [《Runing Hadoop MapReduce on Alluxio》](https://docs.alluxio.io/os/user/stable/en/compute/Hadoop-MapReduce.html#example):

```shell
leaf $ yarn jar hadoop-mapreduce-examples-2.7.7.jar wordcount alluxio://alluxio01:19999/wordcount/input.txt alluxio://alluxio01:19999/wordcount/output
```

The following error occurred:

```shell
21/06/28 23:42:44 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/06/28 23:42:44 INFO hadoop.AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration {}, uri configuration {alluxio.zookeeper.address=null, alluxio.zookeeper.enabled=false, alluxio.master.hostname=alluxio01, alluxio.master.rpc.addresses=null, alluxio.master.embedded.journal.addresses=null, alluxio.master.rpc.port=19999}
21/06/28 23:42:45 INFO hadoop.AbstractFileSystem: Initializing filesystem with connect details alluxio01:19999
21/06/28 23:42:45 INFO network.TieredIdentityFactory: Initialized tiered identity TieredIdentity(node=leaf, rack=null)
21/06/28 23:42:45 INFO client.RMProxy: Connecting to ResourceManager at /10.215.129.73:8032
21/06/28 23:42:46 INFO network.NettyUtils: EPOLL_MODE is available
alluxio.exception.status.UnavailableException: Failed to connect to master (alluxio01:19999) after 44 attempts.Please check if Alluxio master is currently running on "alluxio01:19999". Service="FileSystemMasterClient"
        at alluxio.AbstractClient.connect(AbstractClient.java:279)
        at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:573)
        at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:275)
        at alluxio.client.file.FileSystem.getStatus(FileSystem.java:342)
        at alluxio.hadoop.AbstractFileSystem.getFileStatus(AbstractFileSystem.java:359)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1425)
        at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:145)
        at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:266)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:139)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287)
        at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1308)
        at org.apache.hadoop.examples.WordCount.main(WordCount.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:226)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:141)
Caused by: alluxio.exception.status.UnavailableException: Failed to handshake with master alluxio01:19999 to load cluster default configuration values: INTERNAL: http2 exception
        at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:504)
        at alluxio.ClientContext.loadConf(ClientContext.java:135)
        at alluxio.ClientContext.loadConfIfNotLoaded(ClientContext.java:159)
        at alluxio.AbstractClient.beforeConnect(AbstractClient.java:175)
        at alluxio.AbstractClient.connect(AbstractClient.java:224)
        ... 29 more
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: INTERNAL: http2 exception
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at alluxio.grpc.MetaMasterConfigurationServiceGrpc$MetaMasterConfigurationServiceBlockingStub.getConfiguration(MetaMasterConfigurationServiceGrpc.java:371)
        at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:498)
        ... 33 more
Caused by: alluxio.shaded.client.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
        at alluxio.shaded.client.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
        at alluxio.shaded.client.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338)
        at alluxio.shaded.client.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
        at alluxio.shaded.client.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at alluxio.shaded.client.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at alluxio.shaded.client.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at alluxio.shaded.client.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at alluxio.shaded.client.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at alluxio.shaded.client.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at alluxio.shaded.client.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at alluxio.shaded.client.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at alluxio.shaded.client.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at alluxio.shaded.client.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
```

Seems to be the GRPC problem? But then I really did not know which direction to search, I think this is a very simple example.Do I have some JAR conflicts? The version of Hadoop I am using is 2.7.7, and only one node is deployed for demonstration purposes.

I hope you can help to check this problem, thank you very much!

**To Reproduce**
Refer to the above.

**Expected behavior**
Refer to the above.

**Urgency**
Refer to the above.

**Additional context**
Refer to the above.

**Comment by HelloHorizon** [comment]
@xpleaf Thanks for submitting the issue, can I know which version of Hadoop are you using? And is the password ssh enabled in your cluster?

**Comment by xpleaf** [comment]
@HelloHorizon Thank you for your reply. Hopefully the following information will help locate the problem.

- **Login**

I configured a key-free login.

- **Hadoop Version**

```shell
leaf $ hadoop version
Hadoop 2.7.7
Subversion Unknown -r c1aad84bd27cd79c3d1a7dd58202a8c3ee1ed3ac
Compiled by stevel on 2018-07-18T22:47Z
Compiled with protoc 2.5.0
From source with checksum 792e15d20b12c74bd6f19a1fb886490
This command was run using /home/hadoop/app/hadoop_2.7.7/share/hadoop/common/hadoop-common-2.7.7.jar
```

- **Configuration of `core-site.xml`**

```xml
<configuration>
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://10.215.129.73:9000</value>
    <description>hdfs内部通讯访问地址</description>
  </property>
  <property>
    <name>hadoop.tmp.dir</name>
    <value>/home/hadoop/app/hadoop-2.7.7/data/tmp</value>
  </property>
</configuration>
```

Leaf nodes are built on a very simple pseudo-distributed Hadoop cluster, and leaf's ip is 10.215.129.73.

**Comment by xpleaf** [comment]
@HelloHorizon I tried to use Aluxio's local mode (which is how documentation is used) on another machine with Hadoop stand-alone installed, and it also failed, with the same error.

**Comment by xpleaf** [comment]
@HelloHorizon One more piece of information, the operating system version I use is:
```
$ cat /etc/redhat-release 
CentOS release 6.8 (Final)
```

**Comment by xpleaf** [comment]
@HelloHorizon I have verified in three different environments, and the same problem occurred in all of them. At present, as long as you give me a CentOS server, the problem can be 100% repeated.

**Comment by xpleaf** [comment]
@HelloHorizon Hello, I finally solved the problem. First of all, I always had a misunderstanding about Aluxio. I always thought that the port number of 19998 was Worker (I was very surprised why I formed such an impression, and it was so deep that I didn't even doubt that it was a wrong understanding), so my command to submit the task was as follows:

```shell
hadoop jar ~/app/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.7.jar  wordcount -libjars /home/hadoop/jars/alluxio/alluxio-2.6.0-client.jar alluxio://alluxio01:19998/wordcount/input.txt alluxio://alluxio01:19998/wordcount/output
```

But there are still errors, and I still can't recognize the error of alluxio scheme, so I still add the following configuration to `core-site.xml`:

```xml
<property>
  <name>fs.alluxio.impl</name>
  <value>alluxio.hadoop.FileSystem</value>
  <description>The Alluxio FileSystem</description>
</property>
```

Obviously I'm using a 2.x version of Hadoop, and the official documentation says that you don't need to add this configuration for the 2.x version, but in my case it does.



In the end, thanks a lot anyway!

**Comment by xpleaf** [comment]
Here I will post the news after the success:
```
$ hadoop jar ~/app/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.7.jar  wordcount -libjars /home/hadoop/jars/alluxio/alluxio-2.6.0-client.jar alluxio://alluxio01:19998/wordcount/input.txt alluxio://alluxio01:19998/wordcount/output
21/06/30 16:36:17 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/06/30 16:36:18 INFO hadoop.AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration {}, uri configuration {alluxio.zookeeper.address=null, alluxio.zookeeper.enabled=false, alluxio.master.hostname=alluxio01, alluxio.master.rpc.addresses=null, alluxio.master.embedded.journal.addresses=null, alluxio.master.rpc.port=19998}
21/06/30 16:36:18 INFO hadoop.AbstractFileSystem: Initializing filesystem with connect details alluxio01:19998
21/06/30 16:36:18 INFO network.TieredIdentityFactory: Initialized tiered identity TieredIdentity(node=leaf, rack=null)
21/06/30 16:36:18 INFO client.RMProxy: Connecting to ResourceManager at /10.215.129.73:8032
21/06/30 16:36:19 INFO network.NettyUtils: EPOLL_MODE is available
21/06/30 16:36:20 INFO input.FileInputFormat: Total input paths to process : 1
21/06/30 16:36:20 INFO mapreduce.JobSubmitter: number of splits:1
21/06/30 16:36:20 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1625042023205_0002
21/06/30 16:36:20 INFO impl.YarnClientImpl: Submitted application application_1625042023205_0002
21/06/30 16:36:20 INFO mapreduce.Job: The url to track the job: http://leaf:8088/proxy/application_1625042023205_0002/
21/06/30 16:36:20 INFO mapreduce.Job: Running job: job_1625042023205_0002
21/06/30 16:36:25 INFO mapreduce.Job: Job job_1625042023205_0002 running in uber mode : false
21/06/30 16:36:25 INFO mapreduce.Job:  map 0% reduce 0%
21/06/30 16:36:31 INFO mapreduce.Job:  map 100% reduce 0%
21/06/30 16:36:38 INFO mapreduce.Job:  map 100% reduce 100%
21/06/30 16:36:39 INFO mapreduce.Job: Job job_1625042023205_0002 completed successfully
21/06/30 16:36:39 INFO mapreduce.Job: Counters: 54
        File System Counters
                ALLUXIO: Number of bytes read=27040
                ALLUXIO: Number of bytes written=12161
                ALLUXIO: Number of read operations=5
                ALLUXIO: Number of large read operations=0
                ALLUXIO: Number of write operations=2
                FILE: Number of bytes read=16661
                FILE: Number of bytes written=281767
                FILE: Number of read operations=0
                FILE: Number of large read operations=0
                FILE: Number of write operations=0
                HDFS: Number of bytes read=110
                HDFS: Number of bytes written=0
                HDFS: Number of read operations=1
                HDFS: Number of large read operations=0
                HDFS: Number of write operations=0
        Job Counters 
                Launched map tasks=1
                Launched reduce tasks=1
                Rack-local map tasks=1
                Total time spent by all maps in occupied slots (ms)=3081
                Total time spent by all reduces in occupied slots (ms)=3247
                Total time spent by all map tasks (ms)=3081
                Total time spent by all reduce tasks (ms)=3247
                Total vcore-milliseconds taken by all map tasks=3081
                Total vcore-milliseconds taken by all reduce tasks=3247
                Total megabyte-milliseconds taken by all map tasks=3154944
                Total megabyte-milliseconds taken by all reduce tasks=3324928
        Map-Reduce Framework
                Map input records=482
                Map output records=3809
                Map output bytes=41055
                Map output materialized bytes=16661
                Input split bytes=110
                Combine input records=3809
                Combine output records=1140
                Reduce input groups=1140
                Reduce shuffle bytes=16661
                Reduce input records=1140
                Reduce output records=1140
                Spilled Records=2280
                Shuffled Maps =1
                Failed Shuffles=0
                Merged Map outputs=1
                GC time elapsed (ms)=258
                CPU time spent (ms)=6330
                Physical memory (bytes) snapshot=643952640
                Virtual memory (bytes) snapshot=4389224448
                Total committed heap usage (bytes)=397934592
        Shuffle Errors
                BAD_ID=0
                CONNECTION=0
                IO_ERROR=0
                WRONG_LENGTH=0
                WRONG_MAP=0
                WRONG_REDUCE=0
        File Input Format Counters 
                Bytes Read=27040
        File Output Format Counters 
                Bytes Written=12161
```

**Comment by HelloHorizon** [comment]
@xpleaf Glad you solve the issue. Yeah, we use 19999 as web UI port and 19998 to server master RPCs.
