### ISSUE TITLE
Older worker cannot register to newer master

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13747]
**Alluxio Version:**
2.7.0-SNAPSHOT for master
2.5.0-SNAPSHOT for worker

**Describe the bug**

![image](https://user-images.githubusercontent.com/17329931/124563883-0a479200-de73-11eb-8710-ba950332bcd2.png)
```
2021-07-06 15:54:52,309 WARN  ConfigurationUtils - Alluxio CLIENT version (2.5.0-SNAPSHOT) does not match Alluxio cluster version (2.7.0-SNAPSHOT)
2021-07-06 15:54:52,341 ERROR ProcessUtils - Uncaught exception while running Alluxio worker @192.168.1.100:29999, stopping it and exiting. Exception "alluxio.exception.status.UnknownException", Root Cause "io.grpc.StatusRuntimeException: UNKNOWN"
alluxio.exception.status.UnknownException
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:168)
        at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:406)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:371)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:360)
        at alluxio.worker.block.BlockMasterClient.register(BlockMasterClient.java:232)
        at alluxio.worker.block.BlockMasterSync.registerWithMaster(BlockMasterSync.java:109)
        at alluxio.worker.block.BlockMasterSync.<init>(BlockMasterSync.java:96)
        at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:218)
        at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:76)
        at alluxio.Registry.start(Registry.java:131)
        at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:283)
        at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:235)
        at alluxio.ProcessUtils.run(ProcessUtils.java:36)
        at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:80)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
        at alluxio.grpc.BlockMasterWorkerServiceGrpc$BlockMasterWorkerServiceBlockingStub.registerWorker(BlockMasterWorkerServiceGrpc.java:485)
        at alluxio.worker.block.BlockMasterClient.lambda$register$27(BlockMasterClient.java:233)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:404)
        ... 12 more
2021-07-06 15:54:52,344 INFO  GrpcDataServer - Shutting down Alluxio worker gRPC server at 0.0.0.0/0.0.0.0:29999.
```

**To Reproduce**

use the master with 2.7.0-SNAPSHOT and worker with 2.5.0-SNAPSHOT, worker cannot register to master.

**Expected behavior**

worker can works well with newer alluxio master

**Urgency**

Normal

**Additional context**

No

**Comment by apc999** [comment]
@maobaolong  this is expected behavior as the worker and master versions do not match.
Often we upgrade server-side APIs or parameters in newer versions of Alluxio, which may break the RPC

I am closing this ticket as the proposed behavior "worker can work well with newer alluxio master" is actually currently not supported.
