### ISSUE TITLE
Flaky test in RaftJournalTest

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#13746]
**Alluxio Version:**
2.7.0-SNAPSHOT

**Describe the bug**
```
Error: 9.329 [ERROR] Errors:
Error: 9.330 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend
Error: 9.330 [ERROR]   Run 1: RaftJournalTest.gainPrimacyAfterSuspend:350->promoteFollower:404 » Timeout Tim...
Error: 9.330 [ERROR]   Run 2: RaftJournalTest.gainPrimacyAfterSuspend:350->promoteFollower:404 » Timeout Tim...
```

**To Reproduce**

**Expected behavior**
Unrelated change shall not fail these tests

**Urgency**
high. these flaky tests are blocking a lot of PRs

**Additional context**

**Comment by apc999** [comment]
more info https://pipelines.actions.githubusercontent.com/110HvfICxw4TXSOnsd72jk32naeMsNgZF0xPcAxH5PwqdiBHUN/_apis/pipelines/1/runs/25506/signedlogcontent/4?urlExpires=2021-07-10T16%3A46%3A55.4529457Z&urlSigningMethod=HMACV1&urlSignature=t7zS2lro60IekQVYejJGj8LpsU5ZOwRrHYG8%2BalPjdI%3D

```
2021-07-10T06:55:59.3215303Z 06:55:59.310 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend  Time elapsed: 32.288 s  <<< ERROR!
2021-07-10T06:55:59.3358087Z java.util.concurrent.TimeoutException: Timed out waiting for follower becomes leader options: WaitForOptions{interval=20, timeout=30000} last value: false
2021-07-10T06:55:59.3359957Z 	at alluxio.util.CommonUtils.waitForResult(CommonUtils.java:383)
2021-07-10T06:55:59.3361522Z 	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:341)
2021-07-10T06:55:59.3363534Z 	at alluxio.master.journal.raft.RaftJournalTest.promoteFollower(RaftJournalTest.java:404)
2021-07-10T06:55:59.3366513Z 	at alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterSuspend(RaftJournalTest.java:350)
2021-07-10T06:55:59.3369213Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-07-10T06:55:59.3371667Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-07-10T06:55:59.3374570Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-07-10T06:55:59.3376671Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-07-10T06:55:59.3378255Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2021-07-10T06:55:59.3380451Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2021-07-10T06:55:59.3382955Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2021-07-10T06:55:59.3385632Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2021-07-10T06:55:59.3388149Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2021-07-10T06:55:59.3390477Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2021-07-10T06:55:59.3392515Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2021-07-10T06:55:59.3394456Z 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
2021-07-10T06:55:59.3396280Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-07-10T06:55:59.3397951Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2021-07-10T06:55:59.3399721Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2021-07-10T06:55:59.3401785Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2021-07-10T06:55:59.3404108Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2021-07-10T06:55:59.3405909Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2021-07-10T06:55:59.3407220Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2021-07-10T06:55:59.3408752Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2021-07-10T06:55:59.3410350Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2021-07-10T06:55:59.3411809Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2021-07-10T06:55:59.3413136Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-07-10T06:55:59.3414499Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2021-07-10T06:55:59.3416369Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
2021-07-10T06:55:59.3418973Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
2021-07-10T06:55:59.3421831Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
2021-07-10T06:55:59.3424373Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
2021-07-10T06:55:59.3427050Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2021-07-10T06:55:59.3429426Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2021-07-10T06:55:59.3431420Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2021-07-10T06:55:59.3449367Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2021-07-10T06:55:59.3450483Z 
2021-07-10T06:55:59.3452311Z 06:55:59.329 [ERROR] alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterCatchup  Time elapsed: 32.282 s  <<< ERROR!
2021-07-10T06:55:59.3454940Z java.util.concurrent.TimeoutException: Timed out waiting for follower becomes leader options: WaitForOptions{interval=20, timeout=30000} last value: false
2021-07-10T06:55:59.3456804Z 	at alluxio.util.CommonUtils.waitForResult(CommonUtils.java:383)
2021-07-10T06:55:59.3458089Z 	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:341)
2021-07-10T06:55:59.3459950Z 	at alluxio.master.journal.raft.RaftJournalTest.promoteFollower(RaftJournalTest.java:404)
2021-07-10T06:55:59.3462733Z 	at alluxio.master.journal.raft.RaftJournalTest.gainPrimacyAfterCatchup(RaftJournalTest.java:390)
2021-07-10T06:55:59.3465313Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-07-10T06:55:59.3467591Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-07-10T06:55:59.3470282Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-07-10T06:55:59.3473069Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-07-10T06:55:59.3474762Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2021-07-10T06:55:59.3477122Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2021-07-10T06:55:59.3479649Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2021-07-10T06:55:59.3483416Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2021-07-10T06:55:59.3485981Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2021-07-10T06:55:59.3488309Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2021-07-10T06:55:59.3490228Z 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2021-07-10T06:55:59.3492176Z 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
2021-07-10T06:55:59.3493989Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-07-10T06:55:59.3495830Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2021-07-10T06:55:59.3497591Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2021-07-10T06:55:59.3499516Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2021-07-10T06:55:59.3501810Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2021-07-10T06:55:59.3503584Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2021-07-10T06:55:59.3504876Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2021-07-10T06:55:59.3506408Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2021-07-10T06:55:59.3509965Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2021-07-10T06:55:59.3511464Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2021-07-10T06:55:59.3512944Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-07-10T06:55:59.3514325Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2021-07-10T06:55:59.3516187Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
2021-07-10T06:55:59.3518875Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:289)
2021-07-10T06:55:59.3521698Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
2021-07-10T06:55:59.3524255Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
2021-07-10T06:55:59.3526874Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2021-07-10T06:55:59.3529525Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2021-07-10T06:55:59.3531674Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2021-07-10T06:55:59.3534771Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2021-07-10T06:55:59.3535857Z 
```

**Comment by apc999** [comment]
@ggezer  this unit test is really flaky. Can you take a look?
