### ISSUE TITLE
LocalCache met IndexOutOfBoundsException when read file

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13824]
**Alluxio Version:**
Master branch

commit hash 6f8c5d26

**Describe the bug**

# cat /data/wangzhe/mbl/testa12.txt
cat: /data/wangzhe/mbl/testa12.txt: Input/output error

- Fuse.log

```
2021-07-20 14:57:11,033 ERROR AlluxioJniFuseFileSystem - Failed to read, path: /test.sh size: 4096 offset: 0
java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkBounds(Buffer.java:567)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:357)
        at alluxio.client.file.cache.LocalCacheFileInStream.read(LocalCacheFileInStream.java:115)
        at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:377)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:352)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
        at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:352)
        at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)
2021-07-20 14:57:11,037 ERROR AlluxioJniFuseFileSystem - Failed to read, path: /test.sh size: 4096 offset: 0
```

**To Reproduce**

Using the following config to start Alluxio fuse and read the file contents of alluxio fs

```
alluxio.user.client.cache.enabled=true 
alluxio.user.client.cache.dir=/tmp/alluxio_cache 
alluxio.user.client.cache.size=4GB
```

```
cat /data/wangzhe/mbl/testa12.txt
```

**Expected behavior**

Output the file contents

**Urgency**

Urgent

**Additional context**
No

**Comment by maobaolong** [comment]
I guess the issue is broke by #13406 , please take a look @neuyilan

**Comment by neuyilan** [comment]
> I guess the issue is broke by #13406 , please take a look @neuyilan

Thanks for pointing it out, I'll take a look.

**Comment by maobaolong** [comment]
@neuyilan Thanks for the quick response!

**Comment by neuyilan** [comment]
Hi @maobaolong , I did a lot of tests locally according to your steps. There were different file sizes and local cache sizes, but they were not reproduced. However, through the code review, a possible bug is indeed found. I have submitted a pr. if possible, please reproduce your issue based on this PR to see if it has been solved.
Thanks.

https://github.com/Alluxio/alluxio/pull/13849
