### ISSUE TITLE
Journal replay error: NoSuchElementException: No value present

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13842]
**Alluxio Version:**
Master branch

commit hash 6f8c5d2

**Describe the bug**

All masters logs shown like the following and no one become to leader, no any vote related log.

```
2021-07-23 11:33:29,060 WARN  BlockMasterWorkerServiceHandler - Exit (Error): commitBlock: request=workerId: 2278329360490778076
usedBytesOnTier: 200856688
tierAlias: "MEM"
blockId: 152840437760
length: 9650
mediumType: "MEM"
, Error=alluxio.exception.status.NotFoundException: No worker with workerId 2278329360490778076 is found


2021-07-23 11:49:23,237 ERROR BufferedJournalApplier - Journal replay error: Failed to apply journal entry to master FileSystemMaster. Entry: sequence_number: 10767
inode_directory {
  id: 15
  parent_id: 6
  name: "defense"
  persistence_state: "NOT_PERSISTED"
  pinned: false
  creation_time_ms: 1627012141879
  last_modification_time_ms: 1627012141879
  mount_point: false
  direct_children_loaded: false
  ttl: -1
  ttlAction: DELETE
  acl {
    owningUser: "root"
    owningGroup: ""
    userActions {
      name: ""
      actions {
        actions: READ
        actions: WRITE
        actions: EXECUTE
      }
    }
    groupActions {
      name: ""
      actions {
        actions: READ
        actions: EXECUTE
      }
    }
    otherActions {
      actions: READ
      actions: EXECUTE
    }
    isDefault: false
    isEmpty: false
  }
  defaultAcl {
    owningUser: "root"
    owningGroup: ""
    userActions {
      name: ""
      actions {
      }
   }
    groupActions {
      name: ""
      actions {
      }
    }
    otherActions {
    }
    isDefault: true
    isEmpty: true
  }
  path: "/ceph/defense"
  last_access_time_ms: 1627012141879
}

java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at alluxio.master.file.meta.InodeTreePersistentState.updateTimestampsAndChildCount(InodeTreePersistentState.java:631)
        at alluxio.master.file.meta.InodeTreePersistentState.applyCreateInode(InodeTreePersistentState.java:582)
        at alluxio.master.file.meta.InodeTreePersistentState.applyCreateDirectory(InodeTreePersistentState.java:366)
        at alluxio.master.file.meta.InodeTreePersistentState.processJournalEntry(InodeTreePersistentState.java:693)
        at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:30)
        at alluxio.master.journal.JournaledGroup.processJournalEntry(JournaledGroup.java:55)
        at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:30)
        at alluxio.master.journal.raft.BufferedJournalApplier.applyToMaster(BufferedJournalApplier.java:243)
        at alluxio.master.journal.raft.BufferedJournalApplier.processJournalEntry(BufferedJournalApplier.java:110)
        at alluxio.master.journal.raft.JournalStateMachine.applySingleEntry(JournalStateMachine.java:445)
        at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:417)
        at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:407)
        at alluxio.master.journal.raft.JournalStateMachine.applyJournalEntryCommand(JournalStateMachine.java:385)
        at alluxio.master.journal.raft.JournalStateMachine.applyTransaction(JournalStateMachine.java:279)
        at org.apache.ratis.server.impl.RaftServerImpl.applyLogToStateMachine(RaftServerImpl.java:1659)
        at org.apache.ratis.server.impl.StateMachineUpdater.applyLog(StateMachineUpdater.java:234)
        at org.apache.ratis.server.impl.StateMachineUpdater.run(StateMachineUpdater.java:179)
        at java.lang.Thread.run(Thread.java:748)

2021-07-23 11:49:23,251 INFO  AbstractMaster - TableMaster: Stopped secondary master.

```

**To Reproduce**

Switch leader by kill leader master pod while master use emptydir as a journal persistent volume.

**Expected behavior**

Everything running as expected.

**Urgency**
Urgent.

**Additional context**
No

**Comment by kevincai** [comment]
facing the same issue

**Comment by kevincai** [comment]
Add a few more information from my reproduce.

seems like journalLogEntry out of orders

`2021-09-16 11:23:22,979 ERROR BufferedJournalApplier - Journal replay error: Failed to apply journal entry to master FileSystemMaster. Entry: sequence_number: 12
inode_file {
  id: 50331647
  parent_id: 3
  name: "0001.jpg"
  persistence_state: "PERSISTED"
  pinned: false
  creation_time_ms: 1631762602944
  last_modification_time_ms: 1631500774000
  block_size_bytes: 67108864
  length: 203281
  completed: true
  cacheable: true
  blocks: 33554432
  ttl: -1
  ttlAction: DELETE
  ufs_fingerprint: "TYPE|FILE UFS|oss OWNER|_ GROUP|_ MODE|511 CONTENT_HASH|5674403C7735C373D9F76564E16255AE "
`

LogEntry-12, references to parent_id: 3
From Master journal dump, parent_id 3 is in LogEntry-18
`
sequence_number: 12
inode_file {
  id: 50331647
  parent_id: 3
  name: "0001.jpg"
  persistence_state: "PERSISTED"
  pinned: false
  creation_time_ms: 1631762602944
  last_modification_time_ms: 1631500774000
  block_size_bytes: 67108864
  length: 203281
  completed: true
  cacheable: true
  blocks: 33554432
  ttl: -1
  ttlAction: DELETE
  ufs_fingerprint: "TYPE|FILE UFS|oss OWNER|_ GROUP|_ MODE|511 CONTENT_HASH|5674403C7735C373D9F76564E16255AE "
  acl {
    owningUser: "admin"
    owningGroup: "admin"
    userActions {
`

`
sequence_number: 18
inode_directory {
  id: 3
  parent_id: 2
  name: "00"
  persistence_state: "NOT_PERSISTED"
  pinned: false
  creation_time_ms: 1631762602925
  last_modification_time_ms: 1631762602925
  mount_point: false
  direct_children_loaded: false
  ttl: -1
  ttlAction: DELETE
  acl {
    owningUser: "admin"
    owningGroup: "admin"
    userActions {
      name: ""
      actions {
        actions: READ
        actions: WRITE
        actions: EXECUTE
      }
    }
`
