### ISSUE TITLE
Failed to upgrade Alluxio 1.8.2 to Alluxio 2.6.0:  Chunk [TYPE:FILE] is not a valid entry

### ISSUE THREAD

**Issue by xpleaf** [Alluxio/alluxio#13877]
**Alluxio Version:**
2.6.0

**Describe the bug**
When I upgrade Alluxio according to the [official upgrade document](https://docs.alluxio.io/ee/user/stable/en/operation/Upgrade.html), the following exception is reported when I access the file:

```shell
[hadoop@sample alluxio-2.6.0]$ bin/alluxio fs ls /
-rw-r--r--  hadoop         hadoop                      22       PERSISTED 07-30-2021 20:56:42:946   0% /word.txt
-rw-r--r--  hadoop         hadoop                       6       PERSISTED 07-30-2021 19:56:41:040   0% /word2.txt
drwxr-xr-x  hadoop         hadoop                      24       PERSISTED 07-30-2021 19:57:16:919  DIR /default_tests_files
[hadoop@sample alluxio-2.6.0]$ bin/alluxio fs cat /word.txt
Chunk [TYPE:FILE] is not a valid entry
```

View Alluxio logs. The details are as follows:

```shell
2021-07-30 21:07:37,910 ERROR FileSystemMasterClientServiceHandler - Exit (Error): GetStatus: request=path: "/word.txt"
options {
  loadMetadataType: ALWAYS
  commonOptions {
    syncIntervalMs: 30000
    ttl: -1
    ttlAction: DELETE
  }
}

java.lang.IllegalArgumentException: Chunk [TYPE:FILE] is not a valid entry
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
        at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
        at alluxio.underfs.Fingerprint.parse(Fingerprint.java:143)
        at alluxio.master.file.meta.UfsSyncUtils.computeSyncPlan(UfsSyncUtils.java:37)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

In my opinion, this problem is very easy to repeat. In order to ensure that I can upgrade Allxuio 1.8.2 to Allxuio 2.6.0 in the production environment, I built a single node Alluxio to verify the upgrade, which failed. I will briefly describe the steps to repeat this problem.

1. Build an Alluxio 1.8.2 cluster (single node).
2. Use Alluxio 1.8.2 to write and persist the file `word.txt`, and ensure that the file is accessible.
3. Upgrade Alluxio to 2.6 by following the steps provided in the [official document](https://docs.alluxio.io/ee/user/stable/en/operation/Upgrade.html).
4. After the new Alluxio 2.6 cluster starts, try to access file `word.txt`.

In this way, the problem I mentioned above can be repeated, that is, in the new cluster, the file can be seen(`alluxio ls /`), but the exception will be reported when trying to access it(`alluxio fs cat /word.txt`).

**Expected behavior**

After the cluster upgrade, not only will these files be visible (that is, metadata is fine), but the contents of these files should also be accessible.

**Urgency**
Describe the impact and urgency of the bug.

This is a very urgent problem. Recently, due to many reasons, I upgraded Alluxio 1.8.2 to Alluxio 2.6.0 to meet some business needs, and I completely follow the operation of the official documents, I hope to get your help and suggestions, thank you very much!

**Additional context**

For now, just deploy a single node cluster in Alluxio 1.8.2, and then upgrade to Alluxio 2.6.0, and the problem I'm talking about comes up, so replicating it is easy, and I can post my entire procedure if I need to, because I've documented it.

**Comment by beinan** [comment]
@ggezer could you help take a look?

**Comment by apc999** [comment]
@yuzhu  not sure if this is supported, or we have some issues in backwards compatibility?

**Comment by ggezer** [comment]
Has there been any progress on this?

**Comment by yuzhu** [comment]
@apc999 @ggezer I don't think backwards compatibility is maintained as we moved from 1.8 to 2.x. This specific error is because we changed the way we store fingerprint. 

@xpleaf
I would recommend formatting the master in this case. There are many major changes from 1.8 to 2.x.
