### ISSUE TITLE
Master report Maximum lock count exceeded

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#13904]
**Alluxio Version:**

Master branch from commit hash 7b4abe1dd481

**Describe the bug**

Exception in thread "master-rpc-pool-thread-182" java.lang.Error: Maximum lock count exceeded
        at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.fullTryAcquireShared(ReentrantReadWriteLock.java:528)
        at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryAcquireShared(ReentrantReadWriteLock.java:488)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lockInterruptibly(ReentrantReadWriteLock.java:772)
        at alluxio.master.StateLockManager.lockShared(StateLockManager.java:162)
        at alluxio.master.AbstractMaster.createJournalContext(AbstractMaster.java:141)
        at alluxio.master.file.DefaultFileSystemMaster.createRpcContext(DefaultFileSystemMaster.java:4620)
        at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:986)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$listStatus$183(FileSystemMasterClientServiceHandler.java:243)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:113)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.listStatus(FileSystemMasterClientServiceHandler.java:241)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2328)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1356)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)

**To Reproduce**

Not sure

**Expected behavior**

Be healthy

**Urgency**

Urgent

**Additional context**

Alluxio embedded journal HA cannot work.

[master-18119.log](https://github.com/Alluxio/alluxio/files/6952544/master-18119.log)

**Comment by maobaolong** [comment]
I found alluxio master filled by the following log 

```
2021-08-06 15:45:29,827 WARN  LostFileDetector - Failed to run lost file detector: alluxio.exception.status.UnavailableException: Journal has been closed
```

I guess the lost file count was a high value.

![image](https://user-images.githubusercontent.com/17329931/128671552-04553126-05b5-412d-a992-9c2e1d3900ff.png)

**Comment by yuzhu** [comment]
@ggezer is this similar to what we saw before?

**Comment by maobaolong** [comment]
@yuzhu @ggezer Do you need more information?

**Comment by ggezer** [comment]
> @ggezer is this similar to what we saw before?

@yuzhu Earlier leak was on inode locks. This issue seems to happen on state-lock manager. (Not sure if it's a leak or not yet.)
@maobaolong thanks, i'll let you know if we need more info.

**Comment by maobaolong** [comment]
@ggezer thanks for fix this pr. Could you let me know when journal close? Or I want to know how to workaround or avoid to encounter this issue  before patch your fix

**Comment by ggezer** [comment]
It'll be closed on the leader when stepping down. It's actually pretty short between closing the journals and stopping RPC server. However this duration was long enough in your case for RPCs to hit the limit. So It'd be very good to know why this short period was prolonged in your case.

**Comment by ggezer** [comment]
I wonder how many leader switches happen in your case, since RPC servers should have been closed before journal is closed. So I suspect some wild cycling of leader in your cluster. Having all master logs during this period would be nice.

**Comment by maobaolong** [comment]
Our log file is full of the following line
2021-08-06 15:45:44,800 WARN  ReplicationChecker - Failed to check replication level for inode id 38546995937279 : inodeId 38546995937279 does not exist

**Comment by ggezer** [comment]
Reopening for background investigation.

**Comment by ggezer** [comment]
@maobaolong Do you have `alluxio.master.journal.exit.on.demotion` enabled on the master?

**Comment by maobaolong** [comment]
@ggezer No, it kept default `false`

**Comment by ggezer** [comment]
@maobaolong As you hinted at, it looks LostFileDetector is missing appropriate back-offs when master is stepping down. It should back-off when the journal is closed.

Additionally, we'll investigate why `LostFileDetector` was not interrupted during step down.

**Comment by maobaolong** [comment]
@ggezer Thanks for the fixes related to this issue!
