### ISSUE TITLE
Can't format Alluxio when  HDFS as Alluxio’s under storage system That HDFS authenticate by kerberos

### ISSUE THREAD

**Issue by thirdparty-core** [Alluxio/alluxio#13963]
**Alluxio Version:**
2.6.1

**Describe the bug**
HDFS as Alluxio’s under storage system That HDFS authentication by kerberos,and can't format Alluxio.
The host on which I run format does not perform Kinit operation，and I have made the following configuration:
```
alluxio.master.keytab.file=alluxio.keytab
alluxio.master.principal=alluxio@MY_REALM
alluxio.worker.keytab.file=alluxio.keytab
alluxio.worker.principal=alluxio@MY_REALM
```
exception:
```
Caused by: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
	at org.apache.hadoop.security.SaslRpcClient.selectSaslClient(SaslRpcClient.java:179)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:392)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:622)
	at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:413)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:822)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:818)
	... 33 more
```

Now I want to know if alluxio is not certified for HDFS? Or do I lack any configuration?

Looking forward to your answer.

**Comment by HelloHorizon** [comment]
We don't support the Alluxio access Kerberos enabled HDFS cluster.
