### ISSUE TITLE
Data loss when worker crashed

### ISSUE THREAD

**Issue by tomscut** [Alluxio/alluxio#13972]
**Alluxio Version:**
2.6.0

**Describe the bug**
In our test cluster, we used Flink to consume Kafka data and write it to Alluxio. There are three workers, the number of replication is 2, UFS is HDFS, writeType is cache_through. After we stopped two of the workers and waited for Kafka lag to recover, we began to compare the data directly written into HDFS by product cluster, and found that the data was about 5/1000 less. We tested it multiple times, and the results were all biased.

We suspect there is something wrong with BlockOutStream#updateCurrentChunk(), which is not handling any exceptions.

```
  private void updateCurrentChunk(boolean lastChunk) throws IOException {
    // Early return for the most common case.
    (...)
    if (mCurrentChunk.writableBytes() == 0 || lastChunk) {
      try {
        if (mCurrentChunk.readableBytes() > 0) {
          for (DataWriter dataWriter : mDataWriters) {
            mCurrentChunk.retain();
            dataWriter.writeChunk(mCurrentChunk.duplicate());
          }
        } else {
          Preconditions.checkState(lastChunk);
        }
      } finally {
        // If the packet has bytes to read, we increment its refcount explicitly for every packet
        // writer. So we need to release here. If the packet has no bytes to read, then it has
        // to be the last packet. It needs to be released as well.
        mCurrentChunk.release();
        mCurrentChunk = null;
      }
    }
  (...)
  }
```

We added log.
```
  private void updateCurrentChunk(boolean lastChunk) throws IOException {
    (...)
    if (mCurrentChunk.writableBytes() == 0 || lastChunk) {
      try {
        if (mCurrentChunk.readableBytes() > 0) {
          for (DataWriter dataWriter : mDataWriters) {
              mCurrentChunk.retain();
              dataWriter.writeChunk(mCurrentChunk.duplicate());
          }
        } else {
          Preconditions.checkState(lastChunk);
        }
      } catch (Throwable t) {
        throw new IOException("UpdateCurrentChunk failed!", t);
      } finally {
        // If the packet has bytes to read, we increment its refcount explicitly for every packet
        // writer. So we need to release here. If the packet has no bytes to read, then it has
        // to be the last packet. It needs to be released as well.
        mCurrentChunk.release();
        mCurrentChunk = null;
      }
    }
   (...)
  }
```
Log as follows.
```
21/08/23 18:55:51 ERROR stream.BlockOutStream: UpdateCurrentChunk failed!
java.lang.IllegalStateException: DataWriter is closed while writing chunks.
	at alluxio.shaded.client.com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at alluxio.client.block.stream.LocalFileDataWriter.writeChunk(LocalFileDataWriter.java:129)
	at alluxio.client.block.stream.BlockOutStream.updateCurrentChunk(BlockOutStream.java:263)
	at alluxio.client.block.stream.BlockOutStream.write(BlockOutStream.java:142)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:254)
	at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:217)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:57)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:96)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:68)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:129)
	at org.apache.hadoop.fs.shell.CommandWithDestination$TargetFileSystem.writeStreamToFile(CommandWithDestination.java:485)
	at org.apache.hadoop.fs.shell.CommandWithDestination.copyStreamToTarget(CommandWithDestination.java:407)
	at org.apache.hadoop.fs.shell.CommandWithDestination.copyFileToTarget(CommandWithDestination.java:342)
	at org.apache.hadoop.fs.shell.CommandWithDestination.processPath(CommandWithDestination.java:277)
	at org.apache.hadoop.fs.shell.CommandWithDestination.processPath(CommandWithDestination.java:262)
	at org.apache.hadoop.fs.shell.Command.processPathInternal(Command.java:367)
	at org.apache.hadoop.fs.shell.Command.processPaths(Command.java:331)
	at org.apache.hadoop.fs.shell.Command.processPathArgument(Command.java:304)
	at org.apache.hadoop.fs.shell.CommandWithDestination.processPathArgument(CommandWithDestination.java:257)
	at org.apache.hadoop.fs.shell.Command.processArgument(Command.java:286)
	at org.apache.hadoop.fs.shell.Command.processArguments(Command.java:270)
	at org.apache.hadoop.fs.shell.CommandWithDestination.processArguments(CommandWithDestination.java:228)
	at org.apache.hadoop.fs.shell.CopyCommands$Put.processArguments(CopyCommands.java:295)
	at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:120)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:177)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:328)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:391)
```

**Comment by tomscut** [comment]
Hi @yuzhu @maobaolong , have you met similar problems? Please help to confirm whether there is a bug here. Thanks a lot.

**Comment by jiacheliu3** [comment]
Hi @tomscut thanks for the report!

We'd like to further understand the log you added and see. In your log for `updateCurrentChunk()` could you print more information in that log message? For example I recommend printing the `lastChunk` argument, the `mLength` and `mAddress` from the `BlockOutStream` object. Also the `mDataWriters` from the `BlockOutStream` class has information about the `DataWriter` objects. In your stacktrace it seems to be `LocalFileDataWriter` and `LocalFileDataWriter` has additional information about where the write is from, like `CreateLocalBlockRequest` and the `LocalFileBlockWriter`. If you could print those information and share with us, we can then identify how the `DataWriter` is closed unexpectedly.

**Comment by jiacheliu3** [comment]
Also do you observe any pattern between the log message and the data loss? Does one exception correspond to one data loss?

**Comment by apc999** [comment]
@tomscut  can you help provide more information to help jiacheng debug this issue?

**Comment by tomscut** [comment]
Hi @apc999 @jiacheliu3 , sorry for the late reply. I will post a detailed log ASAP.

**Comment by tomscut** [comment]
Hi @jiacheliu3 , we can reproduce the question like this:
1 Add catch to ```updateCurrentChunk()``` and print relevant information we need.
2 Create a large file and upload it to Alluxio using the command line ```alluxio fs copyFromLocal ./10g-file```.
3 Shut down a worker during file uploading. Then we can see the error message. 

![image](https://user-images.githubusercontent.com/55134131/133174915-dd86bcc6-a907-4f52-80a0-66ee179b8297.png)

**Comment by apc999** [comment]
jiacheng is on vacation, I will take a closer look. thanks @tomscut

**Comment by tomscut** [comment]
> jiacheng is on vacation, I will take a closer look. thanks @tomscut

Thank you for your attention to this issue.

**Comment by yuzhu** [comment]
@apc999 @jiacheliu3， do you have any update on this issue?

**Comment by tomscut** [comment]
> @apc999 @jiacheliu3， do you have any update on this issue?

The problem should be resolved by retry. We can pay attention to this issue [#14041](https://github.com/Alluxio/alluxio/issues/14041). And @liubingxing is doing this work, he will submit PR later.

**Comment by jiacheliu3** [comment]
@tomscut Thx for adding the information.

I'm confused why retry will resolve this issue. At least I'm not yet convinced before I can see what the `DataWriter` is. Without that information I think it's hard to reason how this issue can be fixed. Is it possible to add the logging as I suggested?

Also for the stacktrace you pasted, if the exception is not caught here, it will propagate to higher levels. Looks to me the exception is caught somewhere else. `IllegalStateException` is a `RuntimeException` and will propagate to your shell's log.

However, your stacktrace is from a shell command instead of Kafka stream? How are things connected?

**Comment by yuzhu** [comment]
@tomscut @liubingxing any update on this PR?  please tag this issue when PR is submitted, thanks.

**Comment by tomscut** [comment]
> @tomscut @liubingxing any update on this PR? please tag this issue when PR is submitted, thanks.

Ok, @liubingxing will submit relevant PR.
