### ISSUE TITLE
Illegal character in user info at index 10: alluxio://[zk@henghe66:2181;henghe67:2181;henghe68:2181]

### ISSUE THREAD

**Issue by thirdparty-core** [Alluxio/alluxio#14019]
**Alluxio Version:**
What version of Alluxio are you using?
Alluxio-2.6.1

**Describe the bug**
Hive on Spark
Spark：2.4.6
Hive：3.1.2
Hadoop：3.1.3

Hive on Spark is based on Alluxio,when I run a sql like '**select count(*) from person**' in hive cmd, then throw an exeption:
```
Caused by: java.net.URISyntaxException: Illegal character in user info at index 10: alluxio://[zk@henghe66:2181;henghe67:2181;henghe68:2181]/
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.parseServer(URI.java:3204)
	at java.net.URI$Parser.parseAuthority(URI.java:3154)
	at java.net.URI$Parser.parseHierarchical(URI.java:3096)
	at java.net.URI$Parser.parse(URI.java:3052)
	at java.net.URI.<init>(URI.java:673)
	at java.net.URI.<init>(URI.java:774)
	at org.apache.hadoop.fs.AbstractFileSystem.getUri(AbstractFileSystem.java:330)
	at org.apache.hadoop.fs.AbstractFileSystem.<init>(AbstractFileSystem.java:274)
	at org.apache.hadoop.fs.DelegateToFileSystem.<init>(DelegateToFileSystem.java:49)
	at alluxio.hadoop.AlluxioFileSystem.<init>(AlluxioFileSystem.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.fs.AbstractFileSystem.newInstance(AbstractFileSystem.java:135)
	... 25 more

	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41) ~[netty-all-4.1.17.Final.jar:4.1.17.Final]
	at org.apache.hive.spark.client.SparkClientImpl.<init>(SparkClientImpl.java:106) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hive.spark.client.SparkClientFactory.createClient(SparkClientFactory.java:88) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.spark.RemoteHiveSparkClient.createRemoteClient(RemoteHiveSparkClient.java:105) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.spark.RemoteHiveSparkClient.<init>(RemoteHiveSparkClient.java:101) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.spark.HiveSparkClientFactory.createHiveSparkClient(HiveSparkClientFactory.java:76) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.spark.session.SparkSessionImpl.open(SparkSessionImpl.java:87) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.spark.session.SparkSessionManagerImpl.getSession(SparkSessionManagerImpl.java:115) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.spark.SparkUtilities.getSparkSession(SparkUtilities.java:136) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.spark.SparkTask.execute(SparkTask.java:115) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:205) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:97) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2664) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:2335) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:2011) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1709) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1703) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:157) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:218) ~[hive-exec-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:243) ~[hive-cli-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:192) ~[hive-cli-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406) ~[hive-cli-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:847) ~[hive-cli-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:785) ~[hive-cli-3.1.2.jar:3.1.2]
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:687) ~[hive-cli-3.1.2.jar:3.1.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at org.apache.hadoop.util.RunJar.run(RunJar.java:318) ~[hadoop-common-3.1.3.jar:?]
	at org.apache.hadoop.util.RunJar.main(RunJar.java:232) ~[hadoop-common-3.1.3.jar:?]
Caused by: java.lang.RuntimeException: Cancel client 'd0f99f8d-4232-4157-a01c-d0d8ddb4902d'
```
I now want to know which parameter 'alluxio://[zk@henghe66:2181;henghe67:2181;henghe68:2181]/' comes from?
In my configuration, I did not give a configuration in the format like '**zk@[]**'.

How should I avoid such mistakes? Or do I need to configure any parameters?
Looking forward to your reply.
Thank you very much.

**Comment by ZhuTopher** [comment]
I think this issue is probably due to something unrelated to the linked PR #14021, but I or somebody else will look into this after we resolve that PR first.

In the meantime, can you share your Alluxio properties used (environment variables, `conf/alluxio.site.properties`, etc.)  and maybe a description of how all your services are deployed/configured? Thanks!

**Comment by thirdparty-core** [comment]
Hi，Thank you for your reply. 
I first modified my local alluxio source code according to [#14021](https://github.com/Alluxio/alluxio/pull/14021).
Secondly, I added the following configuration in the core-site.xml file of Hadoop:
```xml
  <property>
       <name>fs.alluxio.impl</name>
       <value>alluxio.hadoop.FileSystem</value>
   </property>

   <property>
    <name>alluxio.zookeeper.address.henghe</name>
    <value>henghe66:2181,henghe67:2181,henghe68:2181</value>
  </property>

  <property>
       <name>fs.AbstractFileSystem.alluxio.impl</name>
       <value>alluxio.hadoop.AlluxioFileSystem</value>
   </property>
```
Now my hive on spark based on alluxio can run normally.


I'm not sure if it's because I modified my local alluxio source code according to [#14021](https://github.com/Alluxio/alluxio/pull/14021) so that my hive on spark can run normally.
But I think it is important to add the above configuration in Hadoop's core-site.xml, especially the latter two.

Good luck!

**Comment by apc999** [comment]
thanks @thirdparty-core for reporting back your solution. I see @ZhuTopher are working with you on  #14021.
I will close this issue for now since you can make it work normally with configuration update.
