### ISSUE TITLE
Run stressMasterBench throw exception when create files

### ISSUE THREAD

**Issue by codings-dan** [Alluxio/alluxio#14038]
**Alluxio Version:**
alluxio 2.6.1

**Describe the bug**
Use stressMasterBench to create files ,  an exception is thrown

```
java.io.IOException: alluxio.exception.AlluxioException: Cannot create or load UFS directory /var/alluxio-share-dir/underFSStorage/testbase15: java.io.FileNotFoundException: /var/alluxio-share-dir/underFSStorage/testbase15.
	at alluxio.hadoop.AbstractFileSystem.mkdirs(AbstractFileSystem.java:625)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2355)
	at alluxio.stress.cli.StressMasterBench.prepare(StressMasterBench.java:115)
	at alluxio.stress.cli.Benchmark.run(Benchmark.java:148)
	at alluxio.stress.cli.Benchmark.mainInternal(Benchmark.java:90)
	at alluxio.stress.cli.StressMasterBench.main(StressMasterBench.java:72)
Caused by: alluxio.exception.AlluxioException: Cannot create or load UFS directory /var/alluxio-share-dir/underFSStorage/testbase15: java.io.FileNotFoundException: /var/alluxio-share-dir/underFSStorage/testbase15.
	at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:104)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:589)
	at alluxio.client.file.BaseFileSystem.createDirectory(BaseFileSystem.java:152)
	at alluxio.hadoop.AbstractFileSystem.mkdirs(AbstractFileSystem.java:622)
	... 5 more
Caused by: alluxio.exception.status.UnknownException: Cannot create or load UFS directory /var/alluxio-share-dir/underFSStorage/testbase15: java.io.FileNotFoundException: /var/alluxio-share-dir/underFSStorage/testbase15.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:168)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:407)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.createDirectory(RetryHandlingFileSystemMasterClient.java:154)
	at alluxio.client.file.BaseFileSystem.lambda$createDirectory$1(BaseFileSystem.java:155)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:574)
	... 7 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Cannot create or load UFS directory /var/alluxio-share-dir/underFSStorage/testbase15: java.io.FileNotFoundException: /var/alluxio-share-dir/underFSStorage/testbase15.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.createDirectory(FileSystemMasterClientServiceGrpc.java:1683)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$createDirectory$2(RetryHandlingFileSystemMasterClient.java:155)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:405)
	... 12 more
```

**To Reproduce**
In an alluxio cluster, execute the command:

`bin/alluxio runClass alluxio.stress.cli.StressMasterBench --base alluxio://alluxio-master-1:19998/testbase15 --conf alluxio.user.file.writetype.default=MUST_CACHE --conf alluxio.user.block.master.client.pool.size.max=512 --conf alluxio.user.file.master.client.pool.size.max=512  --operation CreateFile --warmup 0s --threads 128 --stop-count 100 --target-throughput 10000 --cluster `

**Expected behavior**
Work normally, no longer throw exceptions

**Urgency**
No

**Comment by codings-dan** [comment]
It can also be reproduced using 15 workers, the command is as follows
`bin/alluxio runClass alluxio.stress.cli.StressMasterBench --base alluxio://alluxio-master-1:19998/testbase15 --conf alluxio.user.file.writetype.default=MUST_CACHE --conf alluxio.user.block.master.client.pool.size.max=512 --conf alluxio.user.file.master.client.pool.size.max=512  --operation CreateFile --warmup 0s --threads 128 --stop-count 100 --target-throughput 10000 --cluster --cluster-limit 15 `

**Comment by yuzhu** [comment]
@codings-dan are you using local file system as the UFS?    /var/alluxio-share-dir/underFSStorage/testbase15 do you have permission assigned to the user running the master process?

**Comment by apc999** [comment]
it looks like the ufs is set to local fs? if this is the case, please make sure the ufs is shared across alluxio, or  it will cause issues when you are running this benchmark in a cluster. Can you confirm, @codings-dan ?

**Comment by yuzhu** [comment]
@codings-dan are you still seeing this issue? and can you confirm that you are using a local fs?

**Comment by codings-dan** [comment]
@yuzhu Sorry, this issue has not been tracked recently. I checked again, I am using a local fs. If I manually create the corresponding folder first, and then run StressBench, this exception will not appear again.

**Comment by yuzhu** [comment]
in general, a local fs that is not shared between workers is not a good ufs choice, because worker2 won't see worker1's writes. the exceptions you saw were expected in that case.
