### ISSUE TITLE
Alluxio local cache should propagate InterruptedException to the caller

### ISSUE THREAD

**Issue by beinan** [Alluxio/alluxio#14078]
**Alluxio Version:**
2.5.0-3 (earlier or later version might also have the same issue)

**Describe the bug**
The InterruptedException should be propagated to the caller.  (Or we could call Thread.currentThread().interrupt();)

We're seeing the error log from presto
```
alluxio.client.file.cache.LocalCacheManager	Failed to add page PageId{FileId=4288d79acd4eaf4292a2d00b8e5c6bbc, PageIndex=84} to pageStore
java.io.IOException: java.lang.InterruptedException
	at alluxio.client.file.cache.TimeBoundPageStore.put(TimeBoundPageStore.java:68)
	at alluxio.client.file.cache.LocalCacheManager.putAttempt(LocalCacheManager.java:361)
	at 

```

We should not wrap the interrupted exception into an IOException
**To Reproduce**
Cancel a running presto query when it's reading from the local cache.

**Expected behavior**
We should know the source of the interrupted exception

If the running thread is cancelled (interrupted) by the caller, we should propagate it to the caller (e.g. presto)

If it's interrupted by a timer in alluxio code (e.g. TimeBoundPageStore/SimpleTimeLimiter), I think we should catch and handle it in our code.

**Urgency**
Normal

**Additional context**

**Comment by beinan** [comment]
Fixed in https://github.com/Alluxio/alluxio/pull/15028
