### ISSUE TITLE
alluxio ha Failed to determine address for FileSystemMasterClient after 1 attempts

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14098]
**Alluxio Version:**
2.6.1

**Describe the bug**
alluxio.exception.status.UnavailableException: Failed to determine address for FileSystemMasterClient after 1 attempts
at alluxio.AbstractClient.connect(AbstractClient.java:267)
at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:573)
at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:290)
at com.zhipin.arsenal.dataset.clear.util.AlluxioUtil.getFileStatus(AlluxioUtil.java:89)
at com.zhipin.arsenal.dataset.clear.task.DatasetExpiredFileDeleteTask.deleteExpiredFile(DatasetExpiredFileDeleteTask.java:46)
at com.zhipin.arsenal.dataset.clear.task.DatasetExpiredFileDeleteTask.main(DatasetExpiredFileDeleteTask.java:86)

**Comment by apc999** [comment]
@lilyzhoupeijie  this happens when the address an Alluxio client see is null

https://github.com/Alluxio/alluxio/blob/master/core/common/src/main/java/alluxio/AbstractClient.java#L261-L265

**Comment by ggezer** [comment]
`after 1 attempts` implies that we didn't retry. 
In the logs, I see `CancelledException` as root cause. It's thrown when the target is stepping down and was not properly handled before https://github.com/Alluxio/alluxio/pull/14114

**Comment by LuQQiu** [comment]
master-ha111-master-0-alluxio-master.log
```
2021-09-17 13:36:01,688 INFO  RaftServer - master-ha111-master-0_20329: start RPC server
2021-09-17 13:36:01,723 INFO  GrpcService - master-ha111-master-0_20329: GrpcService started, listening on 20329
2021-09-17 13:36:06,800 INFO  RaftServer$Division - master-ha111-master-0_20329@group-ABB3109A44C1: change Leader from null to master-ha111-master-2_20329 at term 7 for appendEntries, leader elected after 8220ms
2021-09-17 13:37:24,531 WARN  GrpcUtil - Timed out gracefully shutting down connection: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=41, target=master-ha111-master-2:20329}}. 
2021-09-17 13:37:30,117 WARN  RaftJournalSystem - Exception occurred while joining quorum: java.util.concurrent.CompletionException: org.apache.ratis.protocol.exceptions.AlreadyClosedException: SlidingWindow$Client:client-684F92525F5F->RAFT is closed.
// Start to have the failed to determine address exception
```
master-ha111-master-1-alluxio-master.log
```
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_CLIENT_HOSTNAME
	at alluxio.conf.InstancedConfiguration.lookupRecursively(InstancedConfiguration.java:458)
	at alluxio.conf.InstancedConfiguration.lookup(InstancedConfiguration.java:431)
	at alluxio.conf.InstancedConfiguration.isResolvable(InstancedConfiguration.java:171)
	at alluxio.conf.InstancedConfiguration.isSet(InstancedConfiguration.java:180)
	at alluxio.conf.AlluxioConfiguration.getOrDefault(AlluxioConfiguration.java:64)
	at alluxio.cli.GetConf.getConfImpl(GetConf.java:190)
	at alluxio.cli.GetConf.getConf(GetConf.java:147)
	at alluxio.cli.GetConf.main(GetConf.java:274)
2021-09-17 10:42:41,690 INFO  RaftServer - master-ha111-master-1_20329: start RPC server
2021-09-17 10:42:41,724 INFO  GrpcService - master-ha111-master-1_20329: GrpcService started, listening on 20329
2021-09-17 10:42:43,438 INFO  RaftServer$Division - master-ha111-master-1_20329@group-ABB3109A44C1: change Leader from null to master-ha111-master-2_20329 at term 7 for appendEntries, leader elected after 5174ms
2021-09-17 10:43:53,472 WARN  GrpcUtil - Timed out gracefully shutting down connection: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=43, target=master-ha111-master-2:20329}}. 
2021-09-17 10:44:03,809 WARN  RaftJournalSystem - Exception occurred while joining quorum: java.util.concurrent.CompletionException: org.apache.ratis.protocol.exceptions.AlreadyClosedException: 
// Start to have the failed to determine address exception
```
master-ha111-master-2-alluxio-master.log
```
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_CLIENT_HOSTNAME
	at alluxio.conf.InstancedConfiguration.lookupRecursively(InstancedConfiguration.java:458)
	at alluxio.conf.InstancedConfiguration.lookup(InstancedConfiguration.java:431)
	at alluxio.conf.InstancedConfiguration.isResolvable(InstancedConfiguration.java:171)
	at alluxio.conf.InstancedConfiguration.isSet(InstancedConfiguration.java:180)
	at alluxio.conf.AlluxioConfiguration.getOrDefault(AlluxioConfiguration.java:64)
	at alluxio.cli.GetConf.getConfImpl(GetConf.java:190)
	at alluxio.cli.GetConf.getConf(GetConf.java:147)
	at alluxio.cli.GetConf.main(GetConf.java:274)
2021-09-17 10:42:25,963 INFO  RaftServer - master-ha111-master-2_20329: start RPC server
2021-09-17 10:42:25,998 INFO  GrpcService - master-ha111-master-2_20329: GrpcService started, listening on 20329
2021-09-17 10:42:42,806 INFO  AbstractPrimarySelector - Primary selector transitioning to PRIMARY
2021-09-17 10:42:43,429 INFO  SegmentedRaftLogWorker - master-ha111-master-2_20329@group-ABB3109A44C1-SegmentedRaftLogWorker: created new log segment /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_inprogress_1921558
2021-09-17 10:42:43,630 ERROR PollingMasterInquireClient - Error while connecting to master-ha111-master-1:20309. {}
alluxio.exception.status.CancelledException: Thread interrupted
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:129)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
	at alluxio.exception.status.AlluxioStatusException.fromThrowable(AlluxioStatusException.java:208)
	at alluxio.master.PollingMasterInquireClient.pingMetaService(PollingMasterInquireClient.java:158)
	at alluxio.master.PollingMasterInquireClient.getAddress(PollingMasterInquireClient.java:123)
	at alluxio.master.PollingMasterInquireClient.getPrimaryRpcAddress(PollingMasterInquireClient.java:107)
	at alluxio.AbstractMasterClient.getAddress(AbstractMasterClient.java:63)
	at alluxio.AbstractClient.connect(AbstractClient.java:220)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:410)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:379)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:368)
	at alluxio.master.meta.RetryHandlingMetaMasterMasterClient.getId(RetryHandlingMetaMasterMasterClient.java:81)
	at alluxio.master.meta.MetaMasterSync.setIdAndRegister(MetaMasterSync.java:115)
	at alluxio.master.meta.MetaMasterSync.heartbeat(MetaMasterSync.java:71)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: CANCELLED: Thread interrupted
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.ServiceVersionClientServiceGrpc$ServiceVersionClientServiceBlockingStub.getServiceVersion(ServiceVersionClientServiceGrpc.java:171)
	at alluxio.master.PollingMasterInquireClient.pingMetaService(PollingMasterInquireClient.java:155)
	... 16 more
Caused by: java.lang.InterruptedException
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.throwIfInterrupted(ClientCalls.java:749)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:725)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
	... 18 more
2021-09-17 10:42:43,632 WARN  RetryHandlingMetaMasterMasterClient - GetId(address=master-ha111-master-2:20309) exits with exception [alluxio.exception.status.UnavailableException: Failed to determine address for MetaMasterMaster after 1 attempts] in 17040 ms (>=1000ms)
2021-09-17 10:42:43,632 ERROR MetaMasterSync - Failed to receive leader master heartbeat command.
alluxio.exception.status.UnavailableException: Failed to determine address for MetaMasterMaster after 1 attempts
	at alluxio.AbstractClient.connect(AbstractClient.java:267)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:410)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:379)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:368)
	at alluxio.master.meta.RetryHandlingMetaMasterMasterClient.getId(RetryHandlingMetaMasterMasterClient.java:81)
	at alluxio.master.meta.MetaMasterSync.setIdAndRegister(MetaMasterSync.java:115)
	at alluxio.master.meta.MetaMasterSync.heartbeat(MetaMasterSync.java:71)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-09-17 10:42:43,633 INFO  AbstractMaster - MetaMaster: Stopped secondary master.
2021-09-17 10:42:43,633 INFO  AbstractMaster - FileSystemMaster: Stopped secondary master.
2021-09-17 10:42:43,633 INFO  AbstractMaster - BlockMaster: Stopped secondary master.
2021-09-17 10:42:43,633 INFO  AbstractMaster - MetricsMaster: Stopped secondary master.
2021-09-17 10:42:43,633 INFO  FaultTolerantAlluxioMasterProcess - Secondary stopped
2021-09-17 10:43:03,500 INFO  FollowerInfo - master-ha111-master-2_20329@group-ABB3109A44C1->master-ha111-master-0_20329: nextIndex: updateUnconditionally 1921560 -> 1921558
2021-09-17 10:43:05,172 WARN  GrpcUtil - Timed out gracefully shutting down connection: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=44, target=master-ha111-master-2:20329}}. 
2021-09-17 10:43:29,075 WARN  GrpcUtil - Timed out gracefully shutting down connection: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=61, target=master-ha111-master-2:20329}}. 
2021-09-17 10:43:43,525 WARN  RaftJournalSystem - Exception occurred while joining quorum: java.util.concurrent.CompletionException: org.apache.ratis.protocol.exceptions.AlreadyClosedException: SlidingWindow$Client:client-CADBADFAA5EB->RAFT is closed.
2021-09-17 10:48:31,860 ERROR ClientMasterSync - Failed to get master address during initialization
alluxio.exception.status.UnavailableException: Failed to determine primary master rpc address after polling each of [master-ha111-master-0:20309, master-ha111-master-1:20309, master-ha111-master-2:20309] 114 times
```
Master 2 failed to become the leading master and no leading master in the Alluxio servers

**Comment by spasalkar-uptycs** [comment]
@apc999  We are seeing this while writing data from trino (461) to alluxio. This is making alluxio functionality useless as files gets written on UFS & no entry in metastore, so when application again try it it fails with path already exists

```
2025-05-19T13:05:33.240Z	WARN	transaction-finishing-65	io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore	Rolling back due to metastore commit failure: java.io.IOException: Got exception: alluxio.exception.status.UnavailableException Failed to determine address for FileSystemMasterClient after 7 attempts
2025-05-19T13:05:33.250Z	WARN	transaction-finishing-65	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.5)
2025-05-19T13:05:33.265Z	WARN	transaction-finishing-65	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.5)
2025-05-19T13:05:33.286Z	WARN	transaction-finishing-65	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.5)
2025-05-19T13:05:33.301Z	WARN	transaction-finishing-65	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.5)
2025-05-19T13:05:33.310Z	WARN	transaction-finishing-65	io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore	Not deleting non-empty directory: alluxio:/transit/data/abc/test/day=20250519/batch=1747659600
2025-05-19T13:05:33.310Z	WARN	transaction-finishing-65	io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore	Error deleting directory alluxio:/transit/data/abc/test/day=20250519/batch=1747659600 for temporary directory commit abort. Some eligible items cannot be deleted: [alluxio:/transit/data/abc/test/day=20250519/batch=1747659600/].
```
