### ISSUE TITLE
slaver ERROR SnapshotUploader,Cause the master raft log to be extremely large

### ISSUE THREAD

**Issue by xinip** [Alluxio/alluxio#14102]
**Alluxio Version:**
2.5.0-1

**Describe the bug**
slaver ERROR SnapshotUploader,Cause the master raft log to be extremely large

**To Reproduce**
I do not kown how to reproduce

**Expected behavior**
If an error occurs, you should retry uploading the snapshot until the upload is successful

**Urgency**
High

**Additional context**
Slaver log:
```
2021-09-15 14:07:04,624 INFO  RaftLog - alluxio-slaver_19200@group-ABB3109A44C1-SegmentedRaftLog: purgeIndex: updateToMax old=599952, new=699924, updated? true
2021-09-15 14:07:22,327 INFO  SnapshotReplicationManager - Sending stream request to alluxio-master:19998 for snapshot (t:1, i:699999)
2021-09-15 14:07:22,328 ERROR SnapshotUploader - Error sending snapshot /data/alluxio/journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/sm/snapshot.1_699999 at 0
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Channel: 688b90d4-1223-4eea-8163-0529031cb9b7 is not authenticated for call: alluxio.grpc.meta.RaftJournalService/UploadSnapshot
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:172)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Master log:
```
2021-09-15 14:07:00,043 WARN  SnapshotReplicationManager - Failed to request snapshot info from followers: alluxio.exception.status.UnavailableException: No recent snapshot found from followers
2021-09-15 14:07:00,057 WARN  SnapshotReplicationManager - Failed to request snapshot info from followers: alluxio.exception.status.UnavailableException: No recent snapshot found from followers
2021-09-15 14:07:00,073 WARN  SnapshotReplicationManager - Failed to request snapshot info from followers: alluxio.exception.status.UnavailableException: No recent snapshot found from followers
2021-09-15 14:07:22,338 INFO  SnapshotReplicationManager - Request snapshot data from follower alluxio-slaver_19200
2021-09-15 14:07:22,340 INFO  SnapshotReplicationManager - Received upload snapshot request from follower /172.24.150.113:60740
```

**Comment by yuzhu** [comment]
@ggezer PTAL

**Comment by ggezer** [comment]
Couldn't reproduce this. There have been attempts to harden snapshot uploads/downloads and the code seems solid for handling this case. Please feel free to open if you see this again after trying out a newer release.

**Comment by uniqueZt** [comment]
i also encouter the problem，have we any progress here？

**Comment by yuzhu** [comment]
@uniqueZt could you add some more detailed steps to reproduce this? thanks.  we will reopen the issue when that is received.
