### ISSUE TITLE
JOB_MASTER journal quorum info breaks

### ISSUE THREAD

**Issue by kevincai** [Alluxio/alluxio#14211]
**Alluxio Version:**

Alluxio v2.6.2

**Describe the bug**

`./bin/alluxio fsadmin journal quorum info -domain JOB_MASTER` command doesn't work anymore.

**To Reproduce**

Following admin command fails
```
$ ./bin/alluxio fsadmin journal quorum info -domain JOB_MASTER
Failed to connect to master (11.149.82.118:20001) after 8 attempts.Please check if Alluxio master is currently running on "11.149.82.118:20001". Service="JournalMaster"
```
with following error logs
```
2021-10-08 21:57:40,377 INFO  Reflections - Reflections took 279 ms to scan 1 urls, producing 69 keys and 375 values 
2021-10-08 21:57:40,667 INFO  NettyUtils - EPOLL_MODE is available
2021-10-08 21:57:45,566 ERROR AbstractShell - Error running journal quorum info -domain JOB_MASTER
alluxio.exception.status.UnavailableException: Failed to connect to master (11.149.82.118:20001) after 8 attempts.Please check if Alluxio master is currently running on "11.149.82.118:20001". Service="JournalMaster"
        at alluxio.AbstractClient.connect(AbstractClient.java:279)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:403)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.client.journal.RetryHandlingJournalMasterClient.getQuorumInfo(RetryHandlingJournalMasterClient.java:69)
        at alluxio.cli.fsadmin.journal.QuorumInfoCommand.run(QuorumInfoCommand.java:76)
        at alluxio.cli.AbstractShell.run(AbstractShell.java:137)
        at alluxio.cli.fsadmin.FileSystemAdminShell.main(FileSystemAdminShell.java:71)
Caused by: alluxio.exception.status.UnavailableException: Failed to handshake with master 11.149.82.118:20001 to load cluster default configuration values: UNIMPLEMENTED: Method not found: alluxio.grpc.meta.MetaMasterConfigurationService/GetConfiguration
        at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:504)
        at alluxio.ClientContext.loadConf(ClientContext.java:135)
        at alluxio.ClientContext.loadConfIfNotLoaded(ClientContext.java:159)
        at alluxio.AbstractClient.beforeConnect(AbstractClient.java:176)
        at alluxio.AbstractClient.connect(AbstractClient.java:224)
        ... 7 more
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: alluxio.grpc.meta.MetaMasterConfigurationService/GetConfiguration
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at alluxio.grpc.MetaMasterConfigurationServiceGrpc$MetaMasterConfigurationServiceBlockingStub.getConfiguration(MetaMasterConfigurationServiceGrpc.java:424)
        at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:498)
        ... 11 more
```

**Expected behavior**

should be function similar to `-domain MASTER`

`./bin/alluxio fsadmin journal quorum info -domain MASTER`

**Urgency**

Break job-master replacement by command line managing (add/remove) quorum member.

**Additional context**

This bug is probably introduced by commit #13893

 Build with commit `601272157bf8558c2e9bf0315ba10a3815e585b6` reverted, the command works fine.

Need a revisit on commit 601272157bf8558c2e9bf0315ba10a3815e585b6 code change.

**Comment by kevincai** [comment]
all nodes are v2.6.2, I run the command on the same node where MASTER leader runs.
```
$ ./bin/alluxio version
2.6.2
```

With default log configuration, job master server side log doesn't verbose any logline.

**Comment by yuzhu** [comment]
@kevincai do you mind joining our community slack https://alluxio.io/slack so we can discuss about this issue more interactively? I feel there is a lot of overhead in tagging each other on github...

**Comment by yyongycy** [comment]
If you are convenient, please help double check that. The original change is trying to divide the client into two categories:
1. Know only Master
2. Know both Master and JobMaster
The rest semantic is same.

**Comment by yyongycy** [comment]
In reality, it does talk to the two. I am preferring to keep a simple fix. The client side is quite complex, a lot of clients are there. At the same time, we need make sure the convention following the current one.
