### ISSUE TITLE
WORKER_NETWORK_ASYNC_CACHE_MANAGER_THREADS_MAX is invalid in some k8s containers

### ISSUE THREAD

**Issue by ssz1997** [Alluxio/alluxio#14243]
**Alluxio Version:**
2.6.2

**Describe the bug**
The property key [`WORKER_NETWORK_ASYNC_CACHE_MANAGER_THREADS_MAX`](https://github.com/Alluxio/alluxio/blob/71165a5da66df06425265247f32d631c34692489/core/common/src/main/java/alluxio/conf/PropertyKey.java#L3141-L3149), used at [`GrpcExecutors.java`](https://github.com/Alluxio/alluxio/blob/71165a5da66df06425265247f32d631c34692489/core/common/src/main/java/alluxio/conf/PropertyKey.java#L3141-L3149), is set by `2 * Runtime.getRuntime().availableProcessors()`. In some environments this function always returns `1`, for example, in Fluid.
However, we also require the minimum thread to be at least 4 [here](https://github.com/Alluxio/alluxio/blame/master/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java#L38), so this check would fail. While launching worker, it returns:

2021-10-12 17:50:25,490 ERROR AlluxioWorker - Fatal error: Failed to create worker process
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:162)
	at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:46)
	at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:38)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:72)
Caused by: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:593)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:555)
	at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:113)
	... 3 more
Caused by: java.lang.ExceptionInInitializerError
	at alluxio.worker.block.DefaultBlockWorker.<init>(DefaultBlockWorker.java:185)
	at alluxio.worker.block.DefaultBlockWorker.<init>(DefaultBlockWorker.java:152)
	at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:43)
	at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:26)
	at alluxio.worker.AlluxioWorkerProcess.lambda$new$0(AlluxioWorkerProcess.java:105)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
	at alluxio.worker.grpc.GrpcExecutors.<clinit>(GrpcExecutors.java:46)
	... 9 more

**Additional context**
Some related links: 
https://stackoverflow.com/questions/57003259/runtime-getruntime-availableprocessors-is-always-returning-1-on-container-op?rq=1
https://community.neo4j.com/t/configuring-cpu-and-memory-usage-on-kubernetes/6386/2

**Comment by Xenorith** [comment]
not sure about `-XX:ActiveProcessorCount` flag if using java 8. according to https://stackoverflow.com/questions/59882464/does-javas-activeprocessorcount-limit-the-number-of-cpus-the-jvm-can-use
there's a comment, this flag was introduced in java 10: https://www.oracle.com/java/technologies/javase/10-relnote-issues.html

**Comment by ssz1997** [comment]
> not sure about `-XX:ActiveProcessorCount` flag if using java 8. according to https://stackoverflow.com/questions/59882464/does-javas-activeprocessorcount-limit-the-number-of-cpus-the-jvm-can-use there's a comment, this flag was introduced in java 10: https://www.oracle.com/java/technologies/javase/10-relnote-issues.html

Works in my case though. https://stackoverflow.com/questions/59882464/does-javas-activeprocessorcount-limit-the-number-of-cpus-the-jvm-can-use there's also a comment saying "This also worked on the latest version of Java 8, specifically OpenJDK 1.8.0_242-b08."
