### ISSUE TITLE
Alluxio docker image have StackOverflowError error

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14275]
**Alluxio Version:**
Alluxio 2.6.2

**Describe the bug**
When using alluxio 2.6.2 docker image and run a high concurrency machine learning script, the Alluxio will error out
```
2021-10-12 23:51:51,493 INFO  UnderFileSystem$Factory - Failed to create UnderFileSystem by factory alluxio.underfs.s3a.S3AUnderFileSystemFactory@390c5ead: {}
java.lang.StackOverflowError
	at java.io.InputStream.<init>(InputStream.java:45)
	at java.util.zip.ZipFile$ZipFileInputStream.<init>(ZipFile.java:711)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:375)
	at java.util.jar.JarFile.getInputStream(JarFile.java:452)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:987)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader.java:73)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader.java:73)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader.java:73)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:441)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at com.amazonaws.util.Base64.<clinit>(Base64.java:52)
	at alluxio.underfs.s3a.S3AUnderFileSystem.<clinit>(S3AUnderFileSystem.java:119)
	at alluxio.underfs.s3a.S3AUnderFileSystemFactory.create(S3AUnderFileSystemFactory.java:43)
	at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:107)
	at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:132)
	at alluxio.underfs.AbstractUfsManager.lambda$addMount$0(AbstractUfsManager.java:171)
	at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:61)
	at alluxio.worker.block.UnderFileSystemBlockReader.<init>(UnderFileSystemBlockReader.java:140)
	at alluxio.worker.block.UnderFileSystemBlockReader.create(UnderFileSystemBlockReader.java:113)
	at alluxio.worker.block.UnderFileSystemBlockStore.getBlockReader(UnderFileSystemBlockStore.java:244)
	at alluxio.worker.block.DefaultBlockWorker.createUfsBlockReader(DefaultBlockWorker.java:513)
	at alluxio.worker.block.DefaultBlockWorker.createBlockReader(DefaultBlockWorker.java:669)
	at alluxio.client.block.stream.BlockWorkerDataReader$Factory.create(BlockWorkerDataReader.java:132)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:482)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:317)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:185)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:387)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$5(AlluxioJniFuseFileSystem.java:362)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
	at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:362)
	at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)

```
Interesting that when changing to `alluxio-dev` docker image, nothing happens and everything works fine
**To Reproduce**
Launch a cluster similar to  https://github.com/Alluxio/alluxio/issues/14028
and run
```
arena --loglevel info submit pytorch \
  --name=test-job \
  --gpus=0 \
  --workers=4 \
  --cpu 10 \
  --memory 32G \
  --selector alluxio-master=false \
  --image=nvcr.io/nvidia/pytorch:21.05-py3 \
  --data-dir=/s3/ \
  --sync-mode=git \
  --sync-source=https://github.com/LuQQiu/DALI.git \
  "python /root/code/DALI/docs/examples/use_cases/pytorch/resnet50/main.py \
  --process 8 \
  --batch-size 256 \
  --print-freq 1000 \
  /s3/s3-fuse/dali"

arena --loglevel info submit pytorch \
  --name=test-job \
  --gpus=0 \
  --workers=4 \
  --cpu 10 \
  --memory 32G \
  --selector alluxio-master=false \
  --image=nvcr.io/nvidia/pytorch:21.05-py3 \
  --data-dir=/alluxio/ \
  --sync-mode=git \
  --sync-source=https://github.com/LuQQiu/DALI.git \
  "python /root/code/DALI/docs/examples/use_cases/pytorch/resnet50/main.py \
  --process 8 \
  --batch-size 256 \
  --print-freq 1000 \
  /alluxio/alluxio-mountpoint/alluxio-fuse/dali"
```
then go to the alluxio worker log, will find the error

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
Looks like related to #14596
