### ISSUE TITLE
alluxio apply journal entry bug

### ISSUE THREAD

**Issue by gjhkael** [Alluxio/alluxio#14285]
**Alluxio Version:**
Our alluxio cluster version is 2.6.1,  and use "Raft-based Embedded Journal" to build HA cluster with three master nodes.

**Master conf**
```shell
alluxio.table.enabled=false

#mount table
alluxio.underfs.hdfs.configuration=/mnt/storage00/alluxio-2.6.1-SNAPSHOT/conf/core-site.xml:/mnt/storage00/alluxio-2.6.1-SNAPSHOT/conf/hdfs-site.xml
alluxio.master.mount.table.root.ufs=hdfs://namenode-ns2/
alluxio.master.mount.table.root.option.alluxio.underfs.version=3.2

#aluxio ha
alluxio.master.hostname=alluxio-master-01
alluxio.master.embedded.journal.addresses=alluxio-master-01:19200,alluxio-master-02:19200,alluxio-master-03:19200

#hdfs security
alluxio.master.keytab.file=
alluxio.master.principal=
alluxio.master.security.impersonation.root.users=*
alluxio.security.authorization.permission.supergroup=alluxio

#audit log
alluxio.master.audit.logging.enabled=true

#worker dir
alluxio.work.dir=/mnt/storage00/alluxio
```
**Describe the bug**
We have a service that implement the MetaStoreEventListener, when have new partition added, then we use distributed load command to load file from hdfs to alluxio.  For metastore event send out before hive drop .hive_staging path, So Distributed load command may load files belongs to .hive-staging, but when alluxio read from hdfs, the file may delete by hive. Then the exception appear.

The job master's log is below:
```shell
2021-10-20 20:12:25,508 INFO  plan.PlanCoordinator (PlanCoordinator.java:start) - Starting job Id=1634719516120 Config=LoadConfig{FilePath=/xxx/xxx.db/xxx/log_date=20211020/log_hour=19/.hive-staging_hive_2021-10-20_20-08-30_050_253489674686919575-1/-ext-10001/000050_0, Replication=1}
```
The coordinator master's log is below:
```shell
2021-10-20 20:12:26,221 WARN  InodeSyncStream - Failed to sync metadata on root path InodeSyncStream{rootPath=LockingScheme{path=/xxx/xxx.db/xxx/log_date=20211020/log_hour=19/.hive-staging_hive_2021-10-20_20-08-30_050_253489674686919575-1/-ext-10001/000005_0, desiredLockPattern=READ, shouldSync=false}, descendantType=NONE, commonOptions=syncIntervalMs: -1
ttl: -1
ttlAction: DELETE
, forceSync=true, isGetFileInfo=true}: alluxio.exception.FileDoesNotExistException: Path "/xxx/xxx.db/xxx/log_date=20211020/log_hour=19/.hive-staging_hive_2021-10-20_20-08-30_050_253489674686919575-1/-ext-10001/000005_0" does not exist.

2021-10-20 20:12:56,057 WARN  AsyncJournalWriter - Failed to flush journal entry: Timed out after waiting 30000 milliseconds for journal entries to be processed
java.io.IOException: Timed out after waiting 30000 milliseconds for journal entries to be processed
    at alluxio.master.journal.raft.RaftJournalWriter.flush(RaftJournalWriter.java:135)
    at alluxio.master.journal.AsyncJournalWriter.doFlush(AsyncJournalWriter.java:303)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at alluxio.master.journal.raft.RaftJournalWriter.flush(RaftJournalWriter.java:124)
    ... 2 more
```
The standby master's log is below:
```shell
2021-10-20 20:12:25,730 ERROR BufferedJournalApplier - Journal replay error: Failed to apply journal entry to master FileSystemMaster. Entry: sequence_number: 2743163
inode_file {
  id: 14843474083839
  parent_id: 14797504512318
  name: "000000_0"
  persistence_state: "PERSISTED"
  pinned: false
  creation_time_ms: 1634731945709
  last_modification_time_ms: 1634731934707
  block_size_bytes: 536870912
  length: 461399611
  completed: true
  cacheable: true
  blocks: 14843457306624
  ttl: -1
  ttlAction: DELETE
  ufs_fingerprint: "TYPE|FILE UFS|hdfs OWNER|liulvhao GROUP|hadoop MODE|488 CONTENT_HASH|(len:461399611,_modtime:1634731934707) "
  acl {
    owningUser: "liulvhao"
    owningGroup: "hadoop"
    userActions {
      name: ""
      actions {
        actions: READ
        actions: WRITE
        actions: EXECUTE
      }
    }
    groupActions {
      name: ""
      actions {
        actions: READ
        actions: EXECUTE
      }
    }
    otherActions {
    }
    isDefault: false
      isEmpty: false
  }
  replication_max: -1
  replication_min: 0
  persist_job_id: -1
  temp_ufs_path: ""
  replication_durable: 1
  last_access_time_ms: 1634731934707
}

java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at alluxio.master.file.meta.InodeTreePersistentState.updateTimestampsAndChildCount(InodeTreePersistentState.java:631)
    at alluxio.master.file.meta.InodeTreePersistentState.applyCreateInode(InodeTreePersistentState.java:582)
    at alluxio.master.file.meta.InodeTreePersistentState.applyCreateFile(InodeTreePersistentState.java:370)
    at alluxio.master.file.meta.InodeTreePersistentState.processJournalEntry(InodeTreePersistentState.java:695)
    at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:30)
    at alluxio.master.journal.JournaledGroup.processJournalEntry(JournaledGroup.java:55)
    at alluxio.master.journal.DelegatingJournaled.processJournalEntry(DelegatingJournaled.java:30)
    at alluxio.master.journal.raft.BufferedJournalApplier.applyToMaster(BufferedJournalApplier.java:243)
    at alluxio.master.journal.raft.BufferedJournalApplier.processJournalEntry(BufferedJournalApplier.java:110)
    at alluxio.master.journal.raft.JournalStateMachine.applySingleEntry(JournalStateMachine.java:446)
    at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:418)
    at alluxio.master.journal.raft.JournalStateMachine.applyEntry(JournalStateMachine.java:408)
    at alluxio.master.journal.raft.JournalStateMachine.applyJournalEntryCommand(JournalStateMachine.java:386)
    at alluxio.master.journal.raft.JournalStateMachine.applyTransaction(JournalStateMachine.java:280)
    at org.apache.ratis.server.impl.RaftServerImpl.applyLogToStateMachine(RaftServerImpl.java:1394)
    at org.apache.ratis.server.impl.StateMachineUpdater.applyLog(StateMachineUpdater.java:230)
    at org.apache.ratis.server.impl.StateMachineUpdater.run(StateMachineUpdater.java:171)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by jenoudet** [comment]
@gjhkael do you have the logs from all the masters when this event happened? Did this failure cause the whole cluster to fail or was it able to recover from this and proceed?

**Comment by yuzhu** [comment]
@gjhkael please take a look at PR https://github.com/Alluxio/alluxio/pull/14307  and the related issue #14306. I believe that is the root cause here. Basically we were caching some journal entries, which causes race conditions to occur when two simultaneous creations were happening.   I would suggest you try it with that patch applied, or wait a couple of days for our newest release, which will include this patch.
