### ISSUE TITLE
Failed to build webui under WSL

### ISSUE THREAD

**Issue by qian0817** [Alluxio/alluxio#14461]
**Alluxio Version:**
master branch

**Describe the bug**
When I try to build webui under WSL, npm throw a Segmentation fault.

**To Reproduce**
run `mvn -T 4C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Dlicense.skip` under WSL.

**Expected behavior**
build successfully.

**Urgency**
middle.

**Are you planning to fix it**
plan to fix.

**Additional context**
logs
```
[INFO] Running 'npm ci' in /home/qianlei/IdeaProjects/alluxio/webui
[ERROR] added 661 packages in 3.014s
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:exec (Install npm dependencies for packages) @ alluxio-webui ---
lerna notice cli v3.13.0
lerna info ci enabled
lerna ERR! Error: Command failed: npm --version
lerna ERR! Segmentation fault
lerna ERR!
lerna ERR!
lerna ERR!     at makeError (/home/qianlei/IdeaProjects/alluxio/webui/node_modules/execa/index.js:174:9)
lerna ERR!     at Function.module.exports.sync (/home/qianlei/IdeaProjects/alluxio/webui/node_modules/execa/index.js:338:15)
lerna ERR!     at Object.execSync (/home/qianlei/IdeaProjects/alluxio/webui/node_modules/@lerna/child-process/index.js:22:16)
lerna ERR!     at getNpmVersion (/home/qianlei/IdeaProjects/alluxio/webui/node_modules/@lerna/has-npm-version/lib/has-npm-version.js:24:23)
lerna ERR!     at hasNpmVersion (/home/qianlei/IdeaProjects/alluxio/webui/node_modules/@lerna/has-npm-version/lib/has-npm-version.js:10:25)
lerna ERR!     at BootstrapCommand.initialize (/home/qianlei/IdeaProjects/alluxio/webui/node_modules/@lerna/bootstrap/index.js:110:51)
lerna ERR! lerna Command failed: npm --version
lerna ERR! lerna Segmentation fault
lerna ERR! lerna
lerna ERR! lerna
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.626 s (Wall Clock)
[INFO] Finished at: 2021-11-07T21:43:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (Install npm dependencies for packages) on project alluxio-webui: Command execution failed.: Process exited with an error: 139 (Exit value: 139) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by apc999** [comment]
I don't think WSL is supported currently by Alluxio.

**Comment by qian0817** [comment]
I am currently trying to develop alluxio under WSL and have not encountered any incompatibilities other than this.

**Comment by beinan** [comment]
Hi @qian0817, are you still seeing this error?  I got the exactly same issue on wsl2.  
I think the cmds below might help
```
sudo apt --auto-remove purge npm
sudo apt --auto-remove purge nodejs
```
after doing so, you might see some failure on node-sass, then do a mvn clean install or delete the node-modules manually would help.
```
[INFO] Alluxio UI 2.8.0-SNAPSHOT .......................... SUCCESS [01:20 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:32 min
[INFO] Finished at: 2022-01-21T16:07:52-08:00
[INFO] ------------------------------------------------------------------------
```


Some other hints of building alluxio on wsl2 in case other wsl users might see this issue also.
1. put alluxio project on wsl's file system rather than /c/mnt/something,  it would highly spead up the building process
2. select the jdk on wsl in IDEA (either java 11 or java 8 is ok)
