### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14475]
**Alluxio Version:**
 2.6.1

**Describe the bug**
master process show the following error,sometimes it occurs in the begining,sometimes after the master process runs  for 
some days.
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.CompletableFuture$ThreadPerTaskExecutor.execute(CompletableFuture.java:405)
	at java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1654)
	at java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:1856)
	at alluxio.master.journal.raft.JournalStateMachine.notifyTermIndexUpdated(JournalStateMachine.java:299)
	at org.apache.ratis.server.impl.RaftServerImpl.applyLogToStateMachine(RaftServerImpl.java:1637)
	at org.apache.ratis.server.impl.StateMachineUpdater.applyLog(StateMachineUpdater.java:234)
	at org.apache.ratis.server.impl.StateMachineUpdater.run(StateMachineUpdater.java:179)
	at java.lang.Thread.run(Thread.java:748)

I have checked the following:

1)root@test-hhd-5-master-1:/opt/alluxio-2.6.1# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1028023
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

2)
root@test-hhd-5-master-1:/opt/alluxio-2.6.1# sysctl -a|grep vm.max_map_count
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
vm.max_map_count = 262144
root@test-hhd-5-master-1:/opt/alluxio-2.6.1# sysctl -a|grep kernel.thread
kernel.threads-max = 2056047
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
root@test-hhd-5-master-1:/opt/alluxio-2.6.1# sysctl -a|grep kernel.thread_max
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
root@test-hhd-5-master-1:/opt/alluxio-2.6.1# sysctl -a|grep kernel.pid_max
kernel.pid_max = 65536
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"

3)java 
-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/jmx/master.hprof -Xmx19g -Xms19g -XX:MetaspaceSize=256M alluxio.master.AlluxioMaster

the pod request memory is 50Gi

Firstly,I think it may be because the machine is too busy,so I turn master to a quite new machine without ohter process,it also happens.
And this sometimes occur in the begining of the master.

**To Reproduce**
we don't find how to reproduce,but it happens every day.

**Urgency**
very urgent,this affects our online service.

**Comment by LuQQiu** [comment]
added java options
```
-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/jmx/master.hprof -Xmx19g -Xms19g -XX:MetaspaceSize=256M alluxio.master.AlluxioMaster
```
no heap dump happens when the error 
```
java.lang.OutOfMemoryError: unable to create new native thread
```

**Comment by LuQQiu** [comment]
hyphothesis - container has extra limitations on those resources

**Comment by LuQQiu** [comment]
cat /proc/PID/limits

**Comment by LuQQiu** [comment]
Can be related to HA mode - throw by Ratis

**Comment by yuzhu** [comment]
root cause is `at alluxio.master.journal.raft.JournalStateMachine.notifyTermIndexUpdated(JournalStateMachine.java:299)
` 
This uses a common Pool which will create a thread for each submission, causing resourceExhaustion. 
We should use a custom ForkJoinPool here for this.

**Comment by yuzhu** [comment]
suspicion is that Java incorrectly sets parallellism for the common pool to 1 due to containerized environment., which means create as many thread as needed.  https://dzone.com/articles/be-aware-of-forkjoinpoolcommonpool

**Comment by LuQQiu** [comment]
https://github.com/Alluxio/alluxio/pull/14575 PR to alleviate memory pressure from Worker process’s GrpcServer
