### ISSUE TITLE
Presto create table command has timeout issue when enable Alluxio local cache.

### ISSUE THREAD

**Issue by FeiZou** [Alluxio/alluxio#14524]
**Alluxio Version:**
The current Presto version we are using is 0.247, so the corresponding Alluxio version is 2.4.1

**Describe the bug**
When we running `create table shcema_name.table1 as select * from table2` command, we are getting a timeout error:
`om.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1189)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1135)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:2018)
	at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1969)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.rename(PrestoS3FileSystem.java:452)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.rename(PrestoS3FileSystem.java:447)
	at org.apache.hadoop.fs.HadoopExtendedFileSystem.rename(HadoopExtendedFileSystem.java:192)
	at com.facebook.presto.cache.CachingFileSystem.rename(CachingFileSystem.java:209)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.renameDirectory(SemiTransactionalHiveMetastore.java:1934)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.access$2800(SemiTransactionalHiveMetastore.java:101)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.prepareAddTable(SemiTransactionalHiveMetastore.java:1139)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.access$300(SemiTransactionalHiveMetastore.java:1073)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:964)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:908)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:3322)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:221)
	at com.facebook.presto.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:677)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1311)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	... 32 more`
We only see this issue happening when we enable local cache.

**To Reproduce**
Try to create a hive managed table like above. But we also notice that in some case running create table query like above won't through the timeout error. It's happened for some certain tables only without a pattern. 

**Expected behavior**
We are using following setting up on hive.properties file which will help resolve the timeout issue, but we don't know what the root issue is.
`hive.s3.connect-timeout=30s
hive.s3.socket-timeout=30s`
We expect the query should pass through with default timeout setup.

**Urgency**
Urgent

**Are you planning to fix it**
No, since we are not yet locating where the root cause is.

**Comment by beinan** [comment]
@FeiZou sorry for the delay, I'm still working on this one.  Just let me know if you found something, thanks!

**Comment by beinan** [comment]
I'm using running the query as below, the result looks good
```
presto:default> create table hive.default.tpcds_customer2 with (format='PARQUET', partitioned_by = ARRAY['c_birth_month']) as SELECT c_customer_sk, c_customer_id, c_first_name,c_birth_day,c_birth_month FROM tpcds.sf100.customer;
CREATE TABLE: 2000000 rows

Query 20211202_073010_00003_j9sta, FINISHED, 2 nodes
http://localhost:8080/ui/query.html?20211202_073010_00003_j9sta
Splits: 26 total, 26 done (100.00%)
CPU Time: 20.8s total, 96.2K rows/s,     0B/s, 53% active
Per Node: 0.4 parallelism, 41.6K rows/s,     0B/s
Parallelism: 0.9
Peak User Memory: 0B
Peak Total Memory: 69.8MB
Peak Task Total Memory: 37.5MB
S0-driverCountPerTask: sum=1 count=1 min=1 max=1
S0-taskElapsedTimeNanos: sum=0:16 count=1 min=0:16 max=0:16
S1-driverCountPerTask: sum=17 count=1 min=17 max=17
S1-taskElapsedTimeNanos: sum=0:16 count=1 min=0:16 max=0:16
S2-driverCountPerTask: sum=8 count=1 min=8 max=8
S2-taskElapsedTimeNanos: sum=0:06 count=1 min=0:06 max=0:06
fragmentPlanTimeNanos: sum=1ms count=1 min=1ms max=1ms
getLayoutTimeNanos: sum=0ms count=2 min=0ms max=0ms
getMaterializedViewTimeNanos: sum=0ms count=1 min=0ms max=0ms
getSplitsTimeNanos: sum=0ms count=1 min=0ms max=0ms
getTableHandleTimeNanos: sum=0ms count=1 min=0ms max=0ms
getTableMetadataTimeNanos: sum=0ms count=1 min=0ms max=0ms
getViewTimeNanos: sum=0ms count=1 min=0ms max=0ms
logicalPlannerTimeNanos: sum=19ms count=1 min=19ms max=19ms
0:24 [2M rows, 0B] [83.1K rows/s, 0B/s]
```

My hive.propertes

```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://hive-metastore:9083
hive.config.resources=/docker/volumes/conf/presto/etc/hive-default-fs-site.xml
hive.allow-add-column=true
hive.allow-drop-column=true
hive.allow-rename-column=true
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.metastore-cache-ttl=0s
hive.fs.cache.max-size=10
hive.max-partitions-per-scan=100
hive.collect-column-statistics-on-write=true

hive.node-selection-strategy=SOFT_AFFINITY

hive.s3.aws-access-key=xxxxxxx
hive.s3.aws-secret-key=xxxxxxxx

#cache.enabled=true
#cache.type=ALLUXIO
#cache.base-directory=file:///tmp/alluxio
#cache.alluxio.max-cache-size=100MB
```

**Comment by FeiZou** [comment]
Hey @beinan , sorry for the late reply. As I just checked, the dataset which failed in the error has 400 million rows so it's fairly large dataset.

**Comment by beinan** [comment]
s3's renaming is really painful, that's why we have iceberg.   anyway I will try your data size, though I still don't think it's related with our local cache.
