### ISSUE TITLE
OSS ufs cannot be read: java.lang.StackOverflowError  at java.security.AccessController.doPrivileged(Native Method) 

### ISSUE THREAD

**Issue by sighingnow** [Alluxio/alluxio#14596]
**Alluxio Version:**

2.7.0

**Describe the bug**

Reading (`cat`) files from alluxio-fuse (ufs is oss) causing `StackOverflowError`, but accessing (`ls`) doesn't. The stack trace is

```
2021-11-30 03:56:20,485 ERROR AlluxioJniFuseFileSystem - Failed to read, path: /ogbn-papers100M/ogb_extract.py size: 4096 offset: 0                                                                                                                                                                                 [109/1036]
java.lang.StackOverflowError
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader.java:73)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader.java:73)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader.java:73)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader.java:73)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at com.aliyun.oss.common.utils.BinaryUtil.toBase64String(BinaryUtil.java:33)
        at com.aliyun.oss.common.auth.HmacSHA1Signature.computeSignature(HmacSHA1Signature.java:58)
        at com.aliyun.oss.internal.SignUtils.buildSignature(SignUtils.java:228)
        at com.aliyun.oss.internal.OSSRequestSigner.sign(OSSRequestSigner.java:58)
        at com.aliyun.oss.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:90)
        at com.aliyun.oss.common.comm.ServiceClient.sendRequest(ServiceClient.java:70)
        at com.aliyun.oss.internal.OSSOperation.send(OSSOperation.java:83)
        at com.aliyun.oss.internal.OSSOperation.doOperation(OSSOperation.java:145)
        at com.aliyun.oss.internal.OSSObjectOperation.getObjectMetadata(OSSObjectOperation.java:496)
        at com.aliyun.oss.OSSClient.getObjectMetadata(OSSClient.java:599)
        at com.aliyun.oss.OSSClient.getObjectMetadata(OSSClient.java:589)
        at alluxio.underfs.oss.OSSInputStream.<init>(OSSInputStream.java:88)
        at alluxio.underfs.oss.OSSUnderFileSystem.openObject(OSSUnderFileSystem.java:286)
        at alluxio.underfs.ObjectUnderFileSystem.openExistingFile(ObjectUnderFileSystem.java:659)
        at alluxio.underfs.UnderFileSystemWithLogging$39.call(UnderFileSystemWithLogging.java:903)
        at alluxio.underfs.UnderFileSystemWithLogging$39.call(UnderFileSystemWithLogging.java:900)
        at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:1213)
        at alluxio.underfs.UnderFileSystemWithLogging.openExistingFile(UnderFileSystemWithLogging.java:900)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$34.execute(ManagedBlockingUfsForwarder.java:445)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$34.execute(ManagedBlockingUfsForwarder.java:442)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.block(ManagedBlockingUfsForwarder.java:607)
        at alluxio.concurrent.jsr.ForkJoinPool.managedBlock(ForkJoinPool.java:1014)
        at alluxio.concurrent.ForkJoinPoolHelper.safeManagedBlock(ForkJoinPoolHelper.java:41)
        at alluxio.concurrent.ManagedBlockingUfsForwarder$ManagedBlockingUfsMethod.get(ManagedBlockingUfsForwarder.java:593)
        at alluxio.concurrent.ManagedBlockingUfsForwarder.openExistingFile(ManagedBlockingUfsForwarder.java:447)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by jiacheliu3** [comment]
Seems there's a loop in class loading.

**Comment by sighingnow** [comment]
More information about this issue: if we load the target file first using `./bin/alluxio fs load ...`, then the `cat` via fuse succeed.

But I guess it is just a workaround, and there's indeed something in the implementation itself? Looks like the ufs operations fail inside the fuse callback?

**Comment by ssz1997** [comment]
@LuQQiu FYI

**Comment by LuQQiu** [comment]
https://github.com/Alluxio/alluxio/issues/14275
