### ISSUE TITLE
Deploy alluxio on docker and worker process throw exception

### ISSUE THREAD

**Issue by bzheng888** [Alluxio/alluxio#14618]
**Alluxio Version:**
Master version 2.7
Worker version 2.6

**Describe the bug**
Deploy Alluxio on Docker, when start worker container.
master will show error log:

```
BlockMasterWorkerServiceHandler - Worker 6947780794923580178 does not have a lease or the lease has expired. The worker should acquire a new lease and retry to register.
worker will throw exception:
alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.UnavailableException: Worker 6947780794923580178 does not have a lease or the lease has expired. The worker should acquire a new lease and retry to register.
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:424)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:373)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:362)
        at alluxio.worker.block.BlockMasterClient.register(BlockMasterClient.java:255)
        at alluxio.worker.block.BlockMasterSync.registerWithMaster(BlockMasterSync.java:109)
        at alluxio.worker.block.BlockMasterSync.<init>(BlockMasterSync.java:96)
        at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:250)
        at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:97)
        at alluxio.Registry.start(Registry.java:130)
        at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:282)
        at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:229)
        at alluxio.ProcessUtils.run(ProcessUtils.java:37)
        at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:80)
Caused by: alluxio.exception.status.UnavailableException: Worker 6947780794923580178 does not have a lease or the lease has expired. The worker should acquire a new lease and retry to register.
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:155)
        at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:223)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:409)
        ... 12 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Worker 6947780794923580178 does not have a lease or the lease has expired. The worker should acquire a new lease and retry to register.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at alluxio.grpc.BlockMasterWorkerServiceGrpc$BlockMasterWorkerServiceBlockingStub.registerWorker(BlockMasterWorkerServiceGrpc.java:472)
        at alluxio.worker.block.BlockMasterClient.lambda$register$6(BlockMasterClient.java:256)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:407)
        ... 12 more
```

**To Reproduce**
```
docker run -d  --rm -p 8080:19999 -p 19998:19998 -p 19200:19200 -p 20001:20001 --net=alluxio_network --name=alluxio-master  -e ALLUXIO_JAVA_OPTS="-Dalluxio.master.hostname=xxx.xxx.xxx.xxx -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage -Dalluxio.master.worker.register.lease.enabled=false" -v /alluxio/ufs:/opt/alluxio/underFSStorage alluxio/alluxio master
```

```
docker run  --rm -p 29999:29999 -p 80:30000 --net=host --name=alluxio-worker  --shm-size=1G -v /alluxio/ufs:/opt/alluxio/underFSStorage  -e ALLUXIO_JAVA_OPTS="-Dalluxio.master.worker.register.lease.enabled=false -Dalluxio.master.hostname=xxx.xxx.xxx.xxx  -Dalluxio.worker.memory.size=1G" 7a worker
```

**Expected behavior**
worker and master process running success.

**Urgency**
Urgency

**Are you planning to fix it**
No

**Additional context**
No

**Comment by bzheng888** [comment]
Hi, @jiacheliu3, can you take a look at the problem?

**Comment by jiacheliu3** [comment]
The issue is because the master is 2.7 and worker is 2.6. In 2.7 the master defaults to have `alluxio.master.worker.register.lease.enabled=true` and expects the worker to request a lease. 
https://docs.alluxio.io/os/user/stable/en/operation/Scalability-Tuning.html#worker-register-lease

The 2.6 worker will be able to register if the master does not expect a lease. That is done by setting `alluxio.master.worker.register.lease.enabled=false` by updating the config file or dynamically with https://github.com/Alluxio/alluxio/pull/14669
