### ISSUE TITLE
workerFuse stressbench write Input/output error

### ISSUE THREAD

**Issue by ssz1997** [Alluxio/alluxio#14620]
**Alluxio Version:**
Current master branch

**Describe the bug**
Fuse stress bench with workerFuse writing data errors out. 
Not tuning MaxDirectMemorySize, all threads fail. Logs from `worker.out`:
```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 4278190359, max: 4294967296)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:621)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:204)
        at io.netty.buffer.PoolArena.tcacheAllocateNormal(PoolArena.java:188)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:138)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:128)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:378)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
        at alluxio.client.block.stream.BlockOutStream.allocateBuffer(BlockOutStream.java:294)
        at alluxio.client.block.stream.BlockOutStream.updateCurrentChunk(BlockOutStream.java:252)
        at alluxio.client.block.stream.BlockOutStream.write(BlockOutStream.java:141)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:271)
        at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:229)
        at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:438)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$6(AlluxioJniFuseFileSystem.java:413)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:278)
        at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:413)
        at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:316)
```
With following java options in `alluxio-env.sh`: `ALLUXIO_WORKER_JAVA_OPTS+=" -Xmx24G -Xms24G -XX:MaxDirectMemorySize=18g" `, only some threads report failure, and no logs in `worker.out`.

**To Reproduce**
Using ec2 instance r5.2xlarge which has 64GB memory.
Using the following properties in `alluxio-site.properties`:
```
alluxio.master.hostname=localhost
alluxio.master.mount.table.root.ufs=s3://xxxxx
aws.accessKeyId=xxxxxxxxx
aws.secretKey=xxxxxxxxxxxxxxx

alluxio.worker.ramdisk.size=15GB
alluxio.worker.fuse.enabled=true
alluxio.worker.fuse.mount.alluxio.path=/fuseTest
alluxio.worker.fuse.mount.point=/home/centos/fuseTest

# User properties
alluxio.user.file.writetype.default=MUST_CACHE
alluxio.user.block.size.bytes.default=200k
alluxio.client.cache.async.write.enabled=false
alluxio.user.file.passive.cache.enabled=false
```
Run Fuse stress bench with: 
```
bin/alluxio runClass alluxio.stress.cli.fuse.FuseIOBench --local-path /home/centos/fuseTest --operation Write --threads 32 --num-dirs 100 --num-files-per-dir 1000 --file-size 100k
```

**Comment by LuQQiu** [comment]
may be related to https://github.com/Alluxio/alluxio/issues/9345
the bigger topic is how to reduce or control the direct memory usage in Alluxio Fuse or even Alluxio worker

**Comment by ssz1997** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/14637
