### ISSUE TITLE
Can not submit yarn task via logical domain when enable historyserver

### ISSUE THREAD

**Issue by qian0817** [Alluxio/alluxio#14648]
**Alluxio Version:**
2.7.0

**Describe the bug**
Can not submit yarn task via logical domain when enable historyserver.

**To Reproduce**
Use logical address and enable historyserver. then submit a yarn task.

**Expected behavior**
Can submit yarn task successfully.

**Urgency**
High

**Additional context**
exception stack 
```
org.apache.hadoop.fs.InvalidPathException: Invalid path name Wrong FS: alluxio://ebj@logical/tmp/hadoop-yarn/staging/root/.staging/job_1639060727248_0001, expected: alluxio://ebj@logical/
        at org.apache.hadoop.fs.AbstractFileSystem.checkPath(AbstractFileSystem.java:400)
        at org.apache.hadoop.fs.AbstractFileSystem.resolvePath(AbstractFileSystem.java:487)
        at org.apache.hadoop.mapred.YARNRunner.setupLocalResources(YARNRunner.java:394)
        at org.apache.hadoop.mapred.YARNRunner.createApplicationSubmissionContext(YARNRunner.java:573)
        at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:325)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:251)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1567)
        at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:576)
        at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:571)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:571)
        at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:562)
        at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:873)
        at org.apache.hadoop.fs.TestDFSIO.runIOTest(TestDFSIO.java:476)
        at org.apache.hadoop.fs.TestDFSIO.writeTest(TestDFSIO.java:455)
        at org.apache.hadoop.fs.TestDFSIO.run(TestDFSIO.java:872)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
        at org.apache.hadoop.fs.TestDFSIO.main(TestDFSIO.java:743)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.test.MapredTestDriver.run(MapredTestDriver.java:139)
        at org.apache.hadoop.test.MapredTestDriver.main(MapredTestDriver.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
```

**Comment by ZhuTopher** [comment]
As an aside, I'm not really clear how this stacktrace led to #14649.

[Your explanation in the PR](https://github.com/Alluxio/alluxio/pull/14649#issuecomment-991508203) said it's because of the mismatching port assigned to the URI resulting in it matching with two separate filesystem implementations?

Maybe someone more familiar with this could confirm if that makes sense with the error message here?
```
org.apache.hadoop.fs.InvalidPathException: Invalid path name Wrong FS: alluxio://ebj@logical/tmp/hadoop-yarn/staging/root/.staging/job_1639060727248_0001, expected: alluxio://ebj@logical/
```

**Comment by qian0817** [comment]
The latest hadoop code may be misleading, see previous versions of Hadoop code
![image](https://user-images.githubusercontent.com/45898769/146406235-05c63463-8f2a-4923-97db-0d551a8105f5.png)

**Comment by jenoudet** [comment]
The same output can also be observed when using the [Hadoop Synthetic Load Generator](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/SLGUserGuide.html).
`core-site.xml`:
```
<configuration>
  <property>
    <name>alluxio.master.nameservices.hadoop-alluxio-cluster</name>
    <value>master0</value>
  </property>
  <property>
    <name>alluxio.master.rpc.address.hadoop-alluxio-cluster.master0</name>
    <value>AWS_EC2_HOSTNAME:19998</value>
  </property>
  <property>
    <name>fs.AbstractFileSystem.alluxio.impl</name>
    <value>alluxio.hadoop.AlluxioFileSystem</value>
  </property>
  <property>
    <name>fs.alluxio.impl</name>
    <value>alluxio.hadoop.FileSystem</value>
  </property>
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://HadoopIOCluster-client-0:9000</value>
  </property>
  <property>
    <name>hadoop.tmp.dir</name>
    <value>/opt/hadoop/tmpdir</value>
  </property>
</configuration>
```

output:
```
$ /opt/hadoop/bin/yarn jar /opt/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-3.3.1-tests.jar NNdataGenerator -libjars /opt/hadoop/alluxio-2.9.0-SNAPSHOT-client.jar -root alluxio://ebj@hadoop-alluxio-cluster/test -inDir /opt/hadoop
WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
INFO hadoop.AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration {alluxio.master.nameservices.hadoop-alluxio-cluster=master0, alluxio.master.rpc.address.hadoop-alluxio-cluster.master0=AWS_EC2_HOSTNAME:19998}, uri configuration {alluxio.zookeeper.address=null, alluxio.zookeeper.enabled=false, alluxio.master.rpc.addresses=AWS_EC2_HOSTNAME:19998}
INFO hadoop.AbstractFileSystem: Initializing filesystem with connect details HadoopIOCluster-master-0:19998
INFO metrics.MetricsSystem: Starting sinks with config: {}.
INFO metrics.MetricsHeartbeatContext: Created metrics heartbeat with ID app-2418282793439493718. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
INFO network.TieredIdentityFactory: Initialized tiered identity TieredIdentity(node=HadoopIOCluster-client-0, rack=null)
org.apache.hadoop.fs.InvalidPathException: Invalid path name Wrong FS: alluxio://ebj@hadoop-alluxio-cluster/test/dir0/dir0/dir0/dir0 and port=19998, expected: alluxio://ebj@hadoop-alluxio-cluster/ with port=-1
   at org.apache.hadoop.fs.AbstractFileSystem.checkPath(AbstractFileSystem.java:410)
   at org.apache.hadoop.fs.DelegateToFileSystem.mkdir(DelegateToFileSystem.java:184)
   at org.apache.hadoop.fs.FileContext$4.next(FileContext.java:809)
   at org.apache.hadoop.fs.FileContext$4.next(FileContext.java:805)
   at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90)
   at org.apache.hadoop.fs.FileContext.mkdir(FileContext.java:812)
   at org.apache.hadoop.fs.loadGenerator.DataGenerator.genDirStructure(DataGenerator.java:116)
   at org.apache.hadoop.fs.loadGenerator.DataGenerator.run(DataGenerator.java:77)
   at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
   at org.apache.hadoop.fs.loadGenerator.DataGenerator.main(DataGenerator.java:160)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
   at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
   at org.apache.hadoop.test.MapredTestDriver.run(MapredTestDriver.java:139)
   at org.apache.hadoop.test.MapredTestDriver.main(MapredTestDriver.java:147)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
   at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
```
