### ISSUE TITLE
Multi threads accessing LocalFileDataReader problem

### ISSUE THREAD

**Issue by Myasuka** [Alluxio/alluxio#14645]
**Alluxio Version:**
alluxio-2.6.0 with CACHE_THROUGH write type.

**Describe the bug**
We could have several threads reading same file (one is for normal data access, another is for background compaction)
The excpetion stack:
~~~java
Caused by: java.lang.IllegalStateException
	at alluxio.shaded.client.com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at alluxio.client.block.stream.LocalFileDataReader$Factory.create(LocalFileDataReader.java:163)
	at alluxio.client.block.stream.BlockInStream.positionedRead(BlockInStream.java:350)
	at alluxio.client.file.AlluxioFileInStream.positionedReadInternal(AlluxioFileInStream.java:277)
	at alluxio.client.file.AlluxioFileInStream.positionedRead(AlluxioFileInStream.java:247)
	at alluxio.hadoop.HdfsFileInputStream.read(HdfsFileInputStream.java:139)
	at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:89)
~~~

The code looks like:
~~~ java
    public DataReader create(long offset, long len) throws IOException {
      if (mReader == null) {
        mReader = new LocalFileBlockReader(mPath);
      }
      Preconditions.checkState(mReader.getUsageCount() == 0);
      mReader.increaseUsageCount();
      return new LocalFileDataReader(mReader, offset, len, mLocalReaderChunkSize);
    }
~~~
It seems that the LocalFileDataReader does not support concurrent access. However could I avoid or walk around this limitation? Is there something wrong I used for alluxio?

**Expected behavior**
I think alluxio should support multi readers on files.

**Urgency**
Blocker for our usage on alluxio.

**Are you planning to fix it**
Currently no idea. 

**Additional context**

**Comment by apc999** [comment]
Thanks for reporting this issue @Myasuka 
Having concurrent data access on `FSDataInputStream` which is backed by `AlluxioFileInStream` is not supported currently. Inside `AlluxioFileInStream`, there is shared state and concurrent access may trigger race condition.

To test the concurrent throughput, you can create multiple `FSDataInputStream`, one for each thread to read the file
