### ISSUE TITLE
cannot delete file using ceph 

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14684]
**Alluxio Version:**
alluxio 2.8.0

**Describe the bug**

when delete empty dir,we found the following error.

  Failed to delete /test-hhd-5/quxiyang/20210816 (UFS dir not in sync. Sync UFS, or delete with unchecked flag.) from the under file system
  2021-11-22 06:56:31,838 ERROR AbstractShell - Error running rm -R /test-hhd-5/quxiyang/20210816
  java.io.IOException: Failed to delete /test-hhd-5/quxiyang/20210816 (UFS dir not in sync. Sync UFS, or delete with unchecked flag.) from the under file system
  at alluxio.cli.fs.command.AbstractFileSystemCommand.runWildCardCmd(AbstractFileSystemCommand.java:104)
  at alluxio.cli.fs.command.RmCommand.run(RmCommand.java:111)
  at alluxio.cli.AbstractShell.run(AbstractShell.java:137)
  at alluxio.cli.fs.FileSystemShell.main(FileSystemShell.java:66)

**To Reproduce**
write some files to an empty directory,and delete the files under the directory,then try to delete the directory.

**Expected behavior**
when using ceph as under filesystem,an empty direcoty will never persist to ceph,so when the diretory is empty,it should be deleted immediately

**Are you planning to fix it**
Already finish repairing this problem,and the code has been tested and brought online to the production environment

**Comment by JiamingMai** [comment]
In response to `write some files to an empty directory,and delete the files under the directory, then try to delete the directory.` you mentioned above, are you deleting files through Alluxio? Or delete files directly from UFS?
