### ISSUE TITLE
Python script failed because of random write includes

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14708]
**Alluxio Version:**
Alluxio 2.7.0

**Describe the bug**
```
import h5py
import numpy as np

with h5py.File("/tmp/test/animals_12101333.h5", 'w') as f:
    f.create_dataset('animals_included',data=np.array(["dogs".encode(),"cats".encode()]))
    dogs_group = f.create_group("dogs")
    f.create_dataset('cats',data = np.array(np.random.randn(5,64,64,3)))
    dogs_group.create_dataset("husky",data=np.random.randn(64,64,3))
    dogs_group.create_dataset("shiba",data=np.random.randn(64,64,3))

    f.close()

import h5py
with h5py.File("/tmp/test/animals_12101333.h5", 'w') as f:
    for key in f.keys():
        print(f[key], key)
```

the operation failed

**To Reproduce**
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
pip install h5py
pip install numpy
run the script against Alluxio Fuse mount point failed

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
Open the fuse debug logging by setting log4j.properties
```
log4j.rootLogger=DEBUG, ${alluxio.logger.type}, ${alluxio.remote.logger.type}
```
Enable Fuse operation level debug logging of fuse.out by setting
```
alluxio.fuse.debug.enabled=true
```
[fuse.log](https://github.com/Alluxio/alluxio/files/7740305/fuse.log)
[fuse.out.log](https://github.com/Alluxio/alluxio/files/7740306/fuse.out.log)

**Comment by LuQQiu** [comment]
The first write will succeed but the following write will fail because of it includes file overwrite.
The triggered operation is
```
open flags: 0x8002 /animals_12101333.h5
truncate /animals_12101333.h5 0
write[2] 96 bytes to 0 flags: 0x8002
truncate /animals_12101333.h5 800
   unique: 60, error: -95 (Operation not supported), outsize: 16
write[2] 800 bytes to 0 flags: 0x8002
write[2] 96 bytes to 0 flags: 0x8002
flush[2]
release[2] flags: 0x8002
```

**Comment by LuQQiu** [comment]
The script read is 
```
import h5py
with h5py.File("/tmp/test/animals_12101333.h5", 'r') as f:
    for key in f.keys():
        print(f[key], key)
```
The problem is the written `/tmp/test/animals_12101333.h5` has a different size between Alluxio Fuse and the local filesystem.
the one written to local filesystem can be read but the one written to Alluxio Fuse is smaller and cannot be read successfully

**Comment by LuQQiu** [comment]
```
[ec2-user@ProcessLocalRead-worker-0 ~]$ python3 testfile
Traceback (most recent call last):
  File "testfile", line 14, in <module>
    with h5py.File("/mnt/alluxio-standalone-fuse-write/animals_12101333.h5", 'r') as f:
  File "/home/ec2-user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)
```
Error message is `OSError: Unable to open file (bad object header version number)`
In Fuse.out
```

create flags: 0x8242 /animals_12101333.h5 0100664 umask=0002
   create[4] flags: 0x8242 /animals_12101333.h5
getattr /animals_12101333.h5
   NODEID: 4
   unique: 50, success, outsize: 160
unique: 51, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 51, success, outsize: 24
unique: 52, opcode: WRITE (16), nodeid: 4, insize: 176, pid: 12902
write[4] 96 bytes to 0 flags: 0x8002
   write[4] 96 bytes to 0
   unique: 52, success, outsize: 24
unique: 53, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 53, success, outsize: 24
unique: 54, opcode: WRITE (16), nodeid: 4, insize: 88, pid: 12902
write[4] 8 bytes to 2048 flags: 0x8002
   write[4] 8 bytes to 2048
   unique: 54, success, outsize: 24
unique: 55, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 55, success, outsize: 24
unique: 56, opcode: WRITE (16), nodeid: 4, insize: 129104, pid: 12902
write[4] 129024 bytes to 6144 flags: 0x8002
   write[4] 129024 bytes to 6144
   unique: 56, success, outsize: 24
unique: 57, opcode: WRITE (16), nodeid: 4, insize: 131152, pid: 12902
write[4] 131072 bytes to 135168 flags: 0x8002
   write[4] 131072 bytes to 135168
   unique: 57, success, outsize: 24
unique: 58, opcode: WRITE (16), nodeid: 4, insize: 131152, pid: 12902
write[4] 131072 bytes to 266240 flags: 0x8002
   write[4] 131072 bytes to 266240
   unique: 58, success, outsize: 24
unique: 59, opcode: WRITE (16), nodeid: 4, insize: 100432, pid: 12902
write[4] 100352 bytes to 397312 flags: 0x8002
   write[4] 100352 bytes to 397312
   unique: 59, success, outsize: 24
unique: 60, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 60, success, outsize: 24
unique: 61, opcode: WRITE (16), nodeid: 4, insize: 98384, pid: 12902
write[4] 98304 bytes to 497664 flags: 0x8002
   write[4] 98304 bytes to 497664
   unique: 61, success, outsize: 24
unique: 62, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 62, success, outsize: 24
unique: 63, opcode: WRITE (16), nodeid: 4, insize: 98384, pid: 12902
write[4] 98304 bytes to 595968 flags: 0x8002
   write[4] 98304 bytes to 595968
   unique: 63, success, outsize: 24
unique: 64, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 64, success, outsize: 24
unique: 65, opcode: WRITE (16), nodeid: 4, insize: 1968, pid: 12902
write[4] 1888 bytes to 96 flags: 0x8002
   write[4] 1888 bytes to 96
   unique: 65, success, outsize: 24
unique: 66, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 66, success, outsize: 24
unique: 67, opcode: WRITE (16), nodeid: 4, insize: 1344, pid: 12902
write[4] 1264 bytes to 4096 flags: 0x8002
   write[4] 1264 bytes to 4096
   unique: 67, success, outsize: 24
unique: 68, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 68, success, outsize: 24
unique: 69, opcode: WRITE (16), nodeid: 4, insize: 176, pid: 12902
write[4] 96 bytes to 0 flags: 0x8002
   write[4] 96 bytes to 0
   unique: 69, success, outsize: 24
unique: 70, opcode: GETXATTR (22), nodeid: 4, insize: 68, pid: 12902
getxattr /animals_12101333.h5 security.capability 0
   unique: 70, success, outsize: 24
unique: 71, opcode: WRITE (16), nodeid: 4, insize: 176, pid: 12902
write[4] 96 bytes to 0 flags: 0x8002
   write[4] 96 bytes to 0
   unique: 71, success, outsize: 24
unique: 72, opcode: FLUSH (25), nodeid: 4, insize: 64, pid: 12902
flush[4]
   unique: 72, success, outsize: 16
unique: 73, opcode: RELEASE (18), nodeid: 4, insize: 64, pid: 0
release[4] flags: 0x8002
unique: 74, opcode: OPEN (14), nodeid: 4, insize: 48, pid: 12902
open flags: 0x8000 /animals_12101333.h5
   unique: 73, success, outsize: 16
   open[5] flags: 0x8000 /animals_12101333.h5
   unique: 74, success, outsize: 32
unique: 75, opcode: GETATTR (3), nodeid: 4, insize: 56, pid: 12902
getattr /animals_12101333.h5
   unique: 75, success, outsize: 120
unique: 76, opcode: READ (15), nodeid: 4, insize: 80, pid: 12902
read[5] 16384 bytes from 0 flags: 0x8000
   read[5] 16384 bytes from 0
   unique: 76, success, outsize: 16400
unique: 77, opcode: FLUSH (25), nodeid: 4, insize: 64, pid: 12902
flush[5]
   unique: 77, success, outsize: 16
unique: 78, opcode: RELEASE (18), nodeid: 4, insize: 64, pid: 0
release[5] flags: 0x8000
   unique: 78, success, outsize: 16
```
`getxattr /animals_12101333.h5 security.capability 0`
getxattr is called and this function is not implemented by Alluxio yet.

**Comment by LuQQiu** [comment]
@maobaolong @yyongycy PTAL, i am not that familiar with extended attributes and wondering whether Alluxio can support setxattr, getxattr, removexattr, and listxattr?

**Comment by LuQQiu** [comment]
@sg-c FYI

**Comment by LuQQiu** [comment]
This python script contains random write which is not supported by Alluxio yet
<google-sheets-html-origin><style type="text/css"></style>

size=96,offset=0
--
size=8,offset=2048
size=129024,offset=6144
size=131072,offset=135168
size=131072,offset=266240
size=100352,offset=397312
size=98304,offset=497664
size=98304,offset=595968
size=1888,offset=96
size=1264,offset=4096
size=96,offset=0
size=96,offset=0

[fuse.log](https://github.com/Alluxio/allu
[fuse.out.log](https://github.com/Alluxio/alluxio/files/7765634/fuse.out.log)
xio/files/7765632/fuse.log)

**Comment by LuQQiu** [comment]
@sg-c This is one of the known Alluxio limitations (design), that Alluxio doesn't support random write.
It's not the AlluxioFuse limitation. I took a look the source code, it's unlikely to support random write in the near future unless Alluxio infra has huge modification.

**Comment by yyongycy** [comment]
> @maobaolong @yyongycy PTAL, i am not that familiar with extended attributes and wondering whether Alluxio can support setxattr, getxattr, removexattr, and listxattr?

xattr is not a must-to-have apies. It can be ignored.

**Comment by LuQQiu** [comment]
@yyongycy Thanks! The error of this python script is caused by random write and is not caused by xattrs

**Comment by maobaolong** [comment]
@LuQQiu We can implement it with two mode, ignored mode or redirect the request to alluxio master.

**Comment by LuQQiu** [comment]
@maobaolong are you talking about the xattr? how alluxio master handles the request?

**Comment by LuQQiu** [comment]
Close issue because random write is not support by Alluxio
