### ISSUE TITLE
Fuse Mv should not error out when destination file exsit

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14752]
**Alluxio Version:**
Master

**Describe the bug**
In Alluxio Fuse mount point
```
[ec2-user@ProcessLocalRead-worker-0 alluxio-standalone-fuse-read]$ cat b.file
bbbb
[ec2-user@ProcessLocalRead-worker-0 alluxio-standalone-fuse-read]$ cat c.file
cccc
[ec2-user@ProcessLocalRead-worker-0 alluxio-standalone-fuse-read]$ mv b.file c.file
mv: cannot move ‘b.file’ to ‘c.file’: Input/output error
```
From Fuse.log
```
2021-12-27 19:57:07,232 ERROR AlluxioJniFuseFileSystem - Failed to rename /b.file to /c.file:
alluxio.exception.FileAlreadyExistsException: Cannot rename because destination already exists. src: /b.file dst: /c.file
        at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:577)
        at alluxio.client.file.BaseFileSystem.rename(BaseFileSystem.java:412)
        at alluxio.client.file.MetadataCachingBaseFileSystem.rename(MetadataCachingBaseFileSystem.java:119)
        at alluxio.client.file.FileSystem.rename(FileSystem.java:567)
        at alluxio.fuse.AlluxioJniFuseFileSystem.renameInternal(AlluxioJniFuseFileSystem.java:647)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$rename$12(AlluxioJniFuseFileSystem.java:633)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:318)
        at alluxio.fuse.AlluxioJniFuseFileSystem.rename(AlluxioJniFuseFileSystem.java:633)
        at alluxio.jnifuse.AbstractFuseFileSystem.renameCallback(AbstractFuseFileSystem.java:271)
2021-12-27 19:57:07,232 DEBUG AlluxioJniFuseFileSystem - Exit (-5): Fuse.Rename(oldPath=/b.file,newPath=/c.file,) in 6 ms
```

In Linux
```
[ec2-user@ProcessLocalRead-worker-0 ~]$  echo "cccc" > c.file
[ec2-user@ProcessLocalRead-worker-0 ~]$ echo "bbbb" > b.file
[ec2-user@ProcessLocalRead-worker-0 ~]$ mv b.file c.file
[ec2-user@ProcessLocalRead-worker-0 ~]$ ls
c.file
```
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
Expect Fuse perform as the linux system

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
See if mac has same behavior as linux

**Comment by LuQQiu** [comment]
https://libfuse.github.io/doxygen/structfuse__operations.html

Rename int(* fuse_operations::rename)(const char *, const char *, unsigned int flags)
Rename a file

flags may be RENAME_EXCHANGE or RENAME_NOREPLACE. If RENAME_NOREPLACE is specified, the filesystem must not overwrite newname if it exists and return an error instead. If RENAME_EXCHANGE is specified, the filesystem must atomically exchange the two files, i.e. both must exist and neither may be deleted.

our Alluxio JNI Fuse implementation does not have flags
```
RenameOperation::RenameOperation(JniFuseFileSystem *fs) {
  this->fs = fs;
  JNIEnv *env = this->fs->getEnv();
  this->obj = this->fs->getFSObj();
  this->clazz = env->GetObjectClass(this->fs->getFSObj());
  this->signature = "(Ljava/lang/String;Ljava/lang/String;)I";
  this->methodID = env->GetMethodID(this->clazz, "renameCallback", signature);
}

int RenameOperation::call(const char *oldPath, const char *newPath) {
  JNIEnv *env = this->fs->getEnv();
  jstring jspath = env->NewStringUTF(oldPath);
  jstring jspathNew = env->NewStringUTF(newPath);

   int ret = env->CallIntMethod(this->obj, this->methodID, jspath, jspathNew);

  env->DeleteLocalRef(jspath);
  env->DeleteLocalRef(jspathNew);

  return ret;
}
```

**Comment by LuQQiu** [comment]
In libfuse/include/fuse.h master
```
	/** Rename a file
	 *
	 * *flags* may be `RENAME_EXCHANGE` or `RENAME_NOREPLACE`. If
	 * RENAME_NOREPLACE is specified, the filesystem must not
	 * overwrite *newname* if it exists and return an error
	 * instead. If `RENAME_EXCHANGE` is specified, the filesystem
	 * must atomically exchange the two files, i.e. both must
	 * exist and neither may be deleted.
	 */
	int (*rename) (const char *, const char *, unsigned int flags);
```
In libfuse/include/fuse.h 2.9.5
```
	/** Rename a file */
	int (*rename) (const char *, const char *);
```

**Comment by LuQQiu** [comment]
https://github.com/Alluxio/alluxio/issues/12758 can be a reason for upgrading libfuse to 3.x

**Comment by LuQQiu** [comment]
![Screen Shot 2022-07-07 at 12 36 50 PM](https://user-images.githubusercontent.com/25273483/177857776-ba8088ea-5157-4b30-955b-4da7411e35bf.png)
