### ISSUE TITLE
Support rename while writing

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14854]
**Alluxio Version:**
Master

**Describe the bug**
Workflow:
- Fuse.create(oldPath) or Fuse.open(oldPath) for write/overwrite
- Fuse.write(oldPath)
- Fuse.rename(oldPath, newPath)
- Fuse.release(newPath)

**To Reproduce**
Filebench with composite workload
```
define fileset name=testF1,path={{.f.DataPath}}/filebench/composite,entries={{.f.NumFiles}},filesize={{.f.FileSize}},prealloc=50,dirwidth=20
define fileset name=testF2,path={{.f.DataPath}}/filebench/composite,entries={{.f.NumFiles}},filesize={{.f.FileSize}},prealloc=50,dirwidth=20
define process name=filewrite,instances={{.writeProcesses}} {
	thread name=filewritethread,instances={{.writeThreads}} {
		flowop deletefile name=deleteWriteOp,filesetname=testF1,fd=1
		flowop createfile name=createWriteOp,filesetname=testF1,fd=1
		flowop writewholefile name=writeOp,filesetname=testF1,iosize={{.wlt.WriteBufferSize}},fd=1
		flowop closefile name=closeWriteOp,filesetname=testF1,fd=1
	}
}
define process name=fileread,instances={{.readProcesses}} {
	thread name=filereadthread,instances={{.readThreads}} {
		flowop openfile name=openReadOp,filesetname=testF2,fd=1
		flowop readwholefile name=readOp,filesetname=testF2,iosize={{.wlt.ReadSize}},fd=1
		flowop closefile name=closeReadOp,fd=1
	}
}
	
run {{.f.RuntimeSeconds}}`
```
Detailed logs
```
2022-01-16 08:42:08,981 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Create(path=/filebench/composite/testF1/00000010/00000029,mode=100664)

2022-01-16 08:42:08,996 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Write(path=/filebench/composite/testF1/00000010/00000029,buf=java.nio.DirectByteBuffer[pos=0 lim=131072 cap=131072],size=131072,offset=0)

2022-01-16 08:42:09,025 DEBUG AlluxioJniFuseFileSystem - Exit (0): Fuse.Rename(oldPath=/filebench/composite/testF1/00000010/00000029,newPath=/filebench/composite/testF1/00000010/.fuse_hidden0000040e00000046,) i

2022-01-16 08:42:09,026 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Release(path=/filebench/composite/testF1/00000010/.fuse_hidden0000040e00000046)

2022-01-16 08:42:09,050 DEBUG FileSystemMasterClient - Exit (ERROR): CompleteFile
Failed closing /filebench/composite/testF1/00000010/.fuse_hidden0000040e00000046
alluxio.exception.status.NotFoundException: Path "/filebench/composite/testF1/00000010/00000029" does not exist.

2022-01-16 08:42:09,050 ERROR AlluxioJniFuseFileSystem - Failed closing /filebench/composite/testF1/00000010/.fuse_hidden0000040e00000046
alluxio.exception.status.NotFoundException: Path "/filebench/composite/testF1/00000010/00000029" does not exist.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:136)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:224)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:408)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.completeFile(RetryHandlingFileSystemMasterClient.java:171)
	at alluxio.client.file.AlluxioFileOutStream.close(AlluxioFileOutStream.java:202)
	at alluxio.fuse.CreateFileEntry.close(CreateFileEntry.java:89)
	at alluxio.fuse.AlluxioJniFuseFileSystem.releaseInternal(AlluxioJniFuseFileSystem.java:590)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$release$8(AlluxioJniFuseFileSystem.java:570)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:279)
	at alluxio.fuse.AlluxioJniFuseFileSystem.release(AlluxioJniFuseFileSystem.java:570)
	at alluxio.jnifuse.AbstractFuseFileSystem.releaseCallback(AbstractFuseFileSystem.java:226)
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Path "/filebench/composite/testF1/00000010/00000029" does not exist.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.completeFile(FileSystemMasterClientServiceGrpc.java:1672)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$completeFile$4(RetryHandlingFileSystemMasterClient.java:171)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:406)
	... 10 more
```

**Expected behavior**
No error thrown
**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
```
  @Test
  public void renameWhileWriting() throws Exception {
    String testFile = "/renameWritingTestFile";
    String newTestFile = "/newRenameWritingTestFile";
    int fileLen = 128;
    try (CloseableFuseFileInfo info = new CloseableFuseFileInfo()) {
      FuseFileInfo fuseFileInfo = info.getFuseFileInfo();
      fuseFileInfo.flags.set(OpenFlags.O_WRONLY.intValue());
      Assert.assertEquals(0, mFuseFileSystem.create(testFile, 777, fuseFileInfo));
      ByteBuffer buffer = BufferUtils.getIncreasingByteBuffer(fileLen / 2);
      try {
        Assert.assertEquals(fileLen / 2, mFuseFileSystem.write(testFile, buffer, fileLen / 2, 0, fuseFileInfo));
        // https://github.com/Alluxio/alluxio/issues/14854
        Assert.assertEquals(0, mFuseFileSystem.rename(testFile, newTestFile));
      } finally {
        // Failed here
        Assert.assertEquals(0, mFuseFileSystem.release(newTestFile, fuseFileInfo));
      }
    }
  }
```
Test case to add when supporting this functionality

**Comment by LuQQiu** [comment]
Verified that alluxio CLI doesn't support rename while writing.
In one shell, copy from from local
```
bin/alluxio fs copyFromLocal ~/downloads/a.zip /a.zip
```
While copying, in another shell, try to rename
```
bin/alluxio fs mv /a.zip /b.zip
```
Then rename returns successfully `Renamed /a.zip to /b.zip`
and copyFromLocal error out with `Failed to cache: Path "/a.zip" does not exist.`

**Comment by yyongycy** [comment]
can we try to return EBUSY if the file is not completed? 
https://man7.org/linux/man-pages/man2/rename.2.html


       EBUSY  The rename fails because oldpath or newpath is a directory
              that is in use by some process (perhaps as current working
              directory, or as root directory, or because it was open
              for reading) or is in use by the system (for example as a
              mount point), while the system considers this an error.
              (Note that there is no requirement to return EBUSY in such
              cases—there is nothing wrong with doing the rename anyway—
              but it is allowed to return EBUSY if the system cannot
              otherwise handle such situations.)
