### ISSUE TITLE
install alluxio fuse error

### ISSUE THREAD

**Issue by wukong1992** [Alluxio/alluxio#14888]
**Alluxio Version:**
2.7.2

**Describe the bug**
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_HUB_AGENT_RPC_HOSTNAME
	at alluxio.conf.InstancedConfiguration.lookupRecursively(InstancedConfiguration.java:454)
	at alluxio.conf.InstancedConfiguration.lookup(InstancedConfiguration.java:427)
	at alluxio.conf.InstancedConfiguration.isResolvable(InstancedConfiguration.java:170)
	at alluxio.conf.InstancedConfiguration.isSet(InstancedConfiguration.java:179)
	at alluxio.conf.AlluxioConfiguration.getOrDefault(AlluxioConfiguration.java:64)
	at alluxio.cli.GetConf.getConfImpl(GetConf.java:190)
	at alluxio.cli.GetConf.getConf(GetConf.java:147)
	at alluxio.cli.GetConf.main(GetConf.java:274)
umount: can't unmount /mnt/alluxio-fuse: Invalid argument
Starting AlluxioFuse process: mounting alluxio path "/" to local mount point "/mnt/alluxio-fuse" with options="big_writes,allow_other"
2022-01-21 09:31:58,490 INFO  AlluxioFuse - Alluxio version: 2.7.2-0703ba35241e96f8405614dc20e7c7db09167abb
2022-01-21 09:31:58,779 INFO  MetricsSystem - Starting sinks with config: {}.
2022-01-21 09:31:58,785 INFO  MetricsHeartbeatContext - Created metrics heartbeat with ID app-2263885892254298669. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
2022-01-21 09:31:58,885 INFO  NettyUtils - EPOLL_MODE is available
2022-01-21 09:31:59,210 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=10.38.213.112, rack=null)
2022-01-21 09:31:59,217 INFO  NativeLibraryLoader - Loaded lib by jar from path /tmp/libjnifuse1030091537740859028.so.
2022-01-21 09:31:59,375 INFO  Reflections - Reflections took 115 ms to scan 1 urls, producing 58 keys and 194 values 
2022-01-21 09:31:59,391 INFO  AlluxioFuse - Mounting AlluxioJniFuseFileSystem: mount point="/mnt/alluxio-fuse", OPTIONS="[-obig_writes, -oallow_other, -omax_write=131072]"
2022-01-21 09:31:59,391 INFO  AbstractFuseFileSystem - Mounting /mnt/alluxio-fuse: blocking=true, debug=false, fuseOpts="[-obig_writes, -oallow_other, -omax_write=131072]"
fuse: max_idle_threads: 64
fuse: max_idle_threads: 64
2022-01-21 09:32:01,224 ERROR AbstractFuseFileSystem - Failed to statfs /: 
java.lang.UnsupportedOperationException: statfs
	at alluxio.jnifuse.FuseFileSystem.statfs(FuseFileSystem.java:77)
	at alluxio.jnifuse.AbstractFuseFileSystem.statfsCallback(AbstractFuseFileSystem.java:289)

I use kubernetes env

**Comment by apc999** [comment]
@wukong1992 what command did you run? it looks like `statfs` in our FUSE Stub is not supported currently. Curious to see how you triggered this call

**Comment by maobaolong** [comment]
@apc999 we support statfs now, will contribute it these day

**Comment by apc999** [comment]
addressed by "Support statfs for jnifuse #14900"
