### ISSUE TITLE
Not able to create file using JAVA client

### ISSUE THREAD

**Issue by akshaychougule5607** [Alluxio/alluxio#14882]
**Alluxio Version:**
alluxio:2.7.2

**Describe the bug**
Deployed alluxio singlemaster-localjournal through Kubernetes (kubectl) by enabling short-circuit (Use uuid (default)) option.

We are able to create buckets/objects through REST API by enabling the proxy service on port 39999 (eg. curl -i -X PUT http://localhost:39999/api/v1/s3/testbucket)

We need to create bucket without enabling proxy so while creating buckets/objects using alluxio java client (single master and worker on the same node) getting below error - 

[metrics-master-heartbeat-0] ERROR alluxio.client.metrics.ClientMasterSync - Failed to get master address during initialization
alluxio.exception.status.UnavailableException: Failed to handshake with master ip-XXXXXX.us-west-2.compute.internal:19998 to load cluster default configuration values: UNAVAILABLE: io exception
        at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:521)
        at alluxio.ClientContext.loadConf(ClientContext.java:134)
        at alluxio.client.metrics.ClientMasterSync.loadConf(ClientMasterSync.java:122)
        at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:74)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at alluxio.shaded.client.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)

We are using the below java sample to create new file(filename: JavaDemo.java) - 

import alluxio.AlluxioURI;
import alluxio.client.file.FileInStream;
import alluxio.client.file.FileOutStream;
import alluxio.client.file.FileSystem;
import alluxio.conf.AlluxioConfiguration;
import alluxio.conf.InstancedConfiguration;
import alluxio.grpc.CreateFilePOptions;
import alluxio.grpc.WritePType;
import alluxio.util.ConfigurationUtils;

public class JavaDemo {
        public static void main (String args[]) throws Exception {

FileSystem fs = FileSystem.Factory.get();
AlluxioURI path = new AlluxioURI("/testbucket");
// Create a file and get its output stream
 FileOutStream out = fs.createFile(path);
// Write data
out.write("Creating File".getBytes());
// Close and complete file
out.close();
}
}

**To Reproduce**
javac -cp alluxio-shaded-client-2.7.2.jar:slf4j-api-1.7.32.jar:slf4j-simple-1.7.32.jar:. JavaDemo.java

java -cp alluxio-shaded-client-2.7.2.jar:slf4j-api-1.7.32.jar:slf4j-simple-1.7.32.jar:. JavaDemo

**Expected behavior**
need to create new file using java client

**Urgency**
High

**Additional context**
Using openebs-hostpath as storageclass engine

**Comment by apc999** [comment]
@akshaychougule5607  do you have an Alluxio master running at host ip-XXXXXX.us-west-2.compute.internal and port 19998? it looks the client failed to connect to the master

**Comment by akshaychougule5607** [comment]
Its resolved now as Alluxio master is running at this host but port (3XXXX) was different so used conf.set(PropertyKey.MASTER_RPC_PORT, "3XXXX"); in java client.

**Comment by apc999** [comment]
thanks for the update. good to hear it works
