### ISSUE TITLE
mount alluxio error

### ISSUE THREAD

**Issue by wukong1992** [Alluxio/alluxio#14986]
**Alluxio Version:**
2.7.3

**Describe the bug**
I install alluxio with k8s, and use alluxio with posix api, mount the alluixo fs.

2022-02-10 03:03:29,631 WARN  FileSystemMasterClientServiceHandler - Exit (Error): GetNewBlockIdForFile: request=path: "/tmpXgWbWY"
options {
}
, Error=alluxio.exception.FileDoesNotExistException: Path "/tmpXgWbWY" does not exist.
2022-02-10 03:04:24,610 WARN  InodeSyncStream - Failed to sync metadata on root path InodeSyncStream{rootPath=LockingScheme{path=/tmpTpVAVT, desiredLockPattern=READ, shouldSync=false}, descendantType=NONE, commonOptions=syncIntervalMs: -1
ttl: -1
ttlAction: DELETE
, forceSync=true, isGetFileInfo=true}: alluxio.exception.FileDoesNotExistException: Path "/tmpTpVAVT" does not exist.
2022-02-10 03:04:24,622 WARN  DefaultFileSystemMaster - File /tmpTpVAVT is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,628 WARN  InodeSyncStream - Failed to sync metadata on root path InodeSyncStream{rootPath=LockingScheme{path=/.fuse_hidden0000000a00000009, desiredLockPattern=READ, shouldSync=false}, descendantType=NONE, commonOptions=syncIntervalMs: -1
ttl: -1
ttlAction: DELETE
, forceSync=true, isGetFileInfo=true}: alluxio.exception.FileDoesNotExistException: Path "/.fuse_hidden0000000a00000009" does not exist.
2022-02-10 03:04:24,632 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,633 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,655 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,677 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,699 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,721 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,742 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,764 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,786 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,808 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,830 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,852 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,874 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,896 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,918 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,939 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,961 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:24,983 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:25,005 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:25,027 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:25,048 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.
2022-02-10 03:04:25,070 WARN  DefaultFileSystemMaster - File /.fuse_hidden0000000a00000009 is not yet completed. getStatus will see incomplete metadata.

alluxio.exception.status.NotFoundException: Path "/tmpDBR207" does not exist.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:136)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:224)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:408)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.getNewBlockIdForFile(RetryHandlingFileSystemMasterClient.java:217)
	at alluxio.client.file.AlluxioFileOutStream.getNextBlockId(AlluxioFileOutStream.java:309)
	at alluxio.client.file.AlluxioFileOutStream.getNextBlock(AlluxioFileOutStream.java:301)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:267)
	at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:229)
	at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:605)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$6(AlluxioJniFuseFileSystem.java:522)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:279)
	at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:522)
	at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:316)
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Path "/tmpDBR207" does not exist.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.getNewBlockIdForFile(FileSystemMasterClientServiceGrpc.java:1749)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$getNewBlockIdForFile$11(RetryHandlingFileSystemMasterClient.java:218)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:406)
	... 12 more
2022-02-10 03:14:29,680 ERROR AlluxioJniFuseFileSystem - IOException while writing to /.fuse_hidden0000000300000002.
java.io.IOException: Failed to cache: Path "/tmpDBR207" does not exist.
	at alluxio.client.file.AlluxioFileOutStream.handleCacheWriteException(AlluxioFileOutStream.java:317)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:280)
	at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:229)
	at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:605)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$6(AlluxioJniFuseFileSystem.java:522)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:279)
	at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:522)
	at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:316)
Caused by: alluxio.exception.status.NotFoundException: Path "/tmpDBR207" does not exist.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:136)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:224)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:408)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.getNewBlockIdForFile(RetryHandlingFileSystemMasterClient.java:217)
	at alluxio.client.file.AlluxioFileOutStream.getNextBlockId(AlluxioFileOutStream.java:309)
	at alluxio.client.file.AlluxioFileOutStream.getNextBlock(AlluxioFileOutStream.java:301)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:267)
	... 6 more
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Path "/tmpDBR207" does not exist.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.getNewBlockIdForFile(FileSystemMasterClientServiceGrpc.java:1749)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$getNewBlockIdForFile$11(RetryHandlingFileSystemMasterClient.java:218)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:406)
	... 12 more

**Comment by wukong1992** [comment]
> Hey @wukong1992 , do you mind to fill the details of your issue? It's hard to know what happens there without any useful context. And we have a question list that you can find when you create the bug issue. Thx

I install alluxio by doc [https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html](url) . The under fs use local filesystem. And I use posix client api, install fuse component by the autogenerated yaml. But when everything is done. I saw the log above.
