### ISSUE TITLE
Umounting alluxio fuse can't work correctly

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#15007]
**Alluxio Version:**
What version of Alluxio are you using?
2.7.2

**Describe the bug**

1. Run `umount alluxio_fuse-mount`, for example `umount /runtime-mnt/alluxio/default/serverless-data/alluxio-fuse`
2. From the fuse log:

```
alluxio-fuse on /runtime-mnt/alluxio/default/serverless-data/alluxio-fuse type fuse.alluxio-fuse (ro,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=131072)
succeed in checking mount point /runtime-mnt/alluxio/default/serverless-data
2022-02-16 03:38:30,823 INFO  AbstractFuseFileSystem - Umounting /runtime-mnt/alluxio/default/serverless-data/alluxio-fuse
2022-02-16 03:38:30,825 ERROR AbstractFuseFileSystem - Failed to umount /runtime-mnt/alluxio/default/serverless-data/alluxio-fuse
alluxio.jnifuse.FuseException: Unable to umount FS with exit code 1
	at alluxio.jnifuse.AbstractFuseFileSystem.umountInternal(AbstractFuseFileSystem.java:165)
	at alluxio.jnifuse.AbstractFuseFileSystem.umount(AbstractFuseFileSystem.java:121)
	at alluxio.fuse.AlluxioJniFuseFileSystem.umount(AlluxioJniFuseFileSystem.java:843)
	at alluxio.jnifuse.AbstractFuseFileSystem.lambda$mount$0(AbstractFuseFileSystem.java:88)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-3" alluxio.jnifuse.FuseException: Unable to umount FS with exit code 1
	at alluxio.jnifuse.AbstractFuseFileSystem.umountInternal(AbstractFuseFileSystem.java:165)
	at alluxio.jnifuse.AbstractFuseFileSystem.umount(AbstractFuseFileSystem.java:121)
	at alluxio.fuse.AlluxioJniFuseFileSystem.umount(AlluxioJniFuseFileSystem.java:843)
	at alluxio.jnifuse.AbstractFuseFileSystem.lambda$mount$0(AbstractFuseFileSystem.java:88)
	at java.lang.Thread.run(Thread.java:748)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f436a5fc106, pid=1, tid=0x00007f436bbe2700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x8f4106]  Monitor::ILock(Thread*)+0xf6
#
# Core dump written. Default location: /opt/alluxio-release-2.7.2-SNAPSHOT/core or core.1
#
# An error report file with more information is saved as:
# /opt/alluxio-release-2.7.2-SNAPSHOT/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk
#

[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]


[error occurred during error reporting , id 0xb]

[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

I expect the alluxio fuse process can exit 0.

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
may related to https://github.com/Alluxio/alluxio/issues/15015

**Comment by LuQQiu** [comment]
Close this issue since it may relates to #15015, feel free to reopen it when needed
