### ISSUE TITLE
Alluxio Fuse exits with transport not connected

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#15017]
**Alluxio Version:**
Alluxio Fuse: 2.8.0-SNAPSHOT-3eabe2925d4ef0c6e6e2e3c2a6b7f94b575bcddc
Alluxio servers: 2.7.2

**Describe the bug**
40 Fuse training nodes launches to read data from Alluxio.
Most of the training nodes succeed, but a small amount of training nodes failed to read data from Alluxio.
Fuse pod is likely crash with error `transport not connected`.

[alluxio-fuse-2.log](https://github.com/Alluxio/alluxio/files/8091251/alluxio-fuse-2.log)
```
2022-02-16 11:52:57,166 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Readdir(path=/hdfstest-global,buf=139587108868208)
2022-02-16 11:54:35,259 WARN  FileSystemMasterClient - ListStatus(path=/hdfstest-global,options=loadMetadataType: ONCE
commonOptions {
  syncIntervalMs: -1
  ttl: -1
  ttlAction: FREE
}
loadMetadataOnly: false
) exits with exception [alluxio.exception.status.UnavailableException: Failed after 1 attempts: alluxio.exception.status.UnavailableException: Keepalive failed. The connection is likely gone] in 98088 ms (>=1000ms)
2022-02-16 11:54:35,260 ERROR AlluxioJniFuseFileSystem - Failed to readdir /hdfstest-global: 
alluxio.exception.status.UnavailableException: Failed after 1 attempts: alluxio.exception.status.UnavailableException: Keepalive failed. The connection is likely gone
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:423)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.iterateStatus(RetryHandlingFileSystemMasterClient.java:253)
	at alluxio.client.file.BaseFileSystem.lambda$iterateStatus$11(BaseFileSystem.java:299)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:566)
	at alluxio.client.file.BaseFileSystem.iterateStatus(BaseFileSystem.java:295)
	at alluxio.client.file.MetadataCachingBaseFileSystem.iterateStatus(MetadataCachingBaseFileSystem.java:164)
	at alluxio.client.file.FileSystem.iterateStatus(FileSystem.java:373)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readdirInternal(AlluxioJniFuseFileSystem.java:342)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$readdir$2(AlluxioJniFuseFileSystem.java:330)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:305)
	at alluxio.fuse.AlluxioJniFuseFileSystem.readdir(AlluxioJniFuseFileSystem.java:330)
	at alluxio.jnifuse.AbstractFuseFileSystem.readdirCallback(AbstractFuseFileSystem.java:199)
Caused by: alluxio.exception.status.UnavailableException: Keepalive failed. The connection is likely gone
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:156)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:224)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:408)
	... 12 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:648)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$iterateStatus$16(RetryHandlingFileSystemMasterClient.java:264)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:406)
	... 12 more
2022-02-16 11:54:35,264 DEBUG AlluxioJniFuseFileSystem - Exit (-5): Fuse.Readdir(path=/hdfstest-global,buf=139587108868208) in 98098 ms
2022-02-16 11:54:35,264 WARN  AlluxioJniFuseFileSystem - Fuse.Readdir(path=/hdfstest-global,buf=139587108868208) returned -5 in 98098 ms (>=10000 ms)
   unique: 346, error: -5 (Input/output error), outsize: 16
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
This problem is likely because version mismatch.
Change Fuse version to 2.7.2, and this issue haven't occurred again

**Comment by LuQQiu** [comment]
Next steps: Add Alluxio logs to get more information about this type of error.
Instead of letting Fuse exit without any information, we need to get more info.

**Comment by LuQQiu** [comment]
read 90/100 and then crash

**Comment by LuQQiu** [comment]
[alluxio-fuse-17-warm.log](https://github.com/Alluxio/alluxio/files/8106732/alluxio-fuse-17-warm.log)
[alluxio-fuse-35-cold.log
[alluxio-fuse-9-cold.log](https://github.com/Alluxio/alluxio/files/8106734/alluxio-fuse-9-cold.log)
](https://github.com/Alluxio/alluxio/files/8106733/alluxio-fuse-35-cold.log)

**Comment by LuQQiu** [comment]
Log only occur for < 1min, but application succeed runs for 7 to 1h, majority of data read, random place occur problem.

**Comment by LuQQiu** [comment]
https://github.com/Alluxio/alluxio/pull/15038

**Comment by LuQQiu** [comment]
Alluxio Fuse process launched and logs normally -> logs disappear after 1 second but Alluxio Fuse process is still serving requests (application can still read normally) -> Fuse mount point transport not connected after reading more than 60% of data.
@Nizifan, can you help check the following information
- /var/log/message -> may tell us whether this process is killed by the operating system
- when logs disappeared but Fuse process is running as normal, can you help take a jstack of the Fuse process?

@yyongycy any other information is helpful? or any thoughts about why the above behavior will happen?

**Comment by Nizifan** [comment]
@LuQQiu according to my former experiment,  the log does not disappear when the fuse is still serving.
But when it hit transport not connected, the log just disappeared.

I may try to save the log in fuse process when crash is detected.
