### ISSUE TITLE
Read from caching data much slower than read from UFS directly

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#15026]
**Alluxio Version:**
2.7.2

**Describe the bug**

Alluxio cluster is launched with 1 master and 8 workers. 40 training nodes are launched to read data from 40 co-located Fuse pods. Each Fuse pod reads 1/40 of the total data. 
Data amount is 2TB total, about 70MB each, about 30k files. Each Fuse pod reads 50GB data.

Clean the whole cache during 15:00

the first round cold read from Alluxio is very fast, on average takes 15 minutes  (consistent)
the second round warm read from Alluxio, the speed drops, on average is 50% of the cold read speed, takes 40 minutes (not consistent)

Bytes read UFS = increase(Cluster_BytesReadUfsAll{fluid_runtime=~"$fluid_runtime",namespace=~"$namespace"}[2m])
Bytes Read Cache = increase(Cluster_BytesReadRemote{fluid_runtime=~"$fluid_runtime",namespace=~"$namespace"}[2m]) - increase(Cluster_BytesReadUfsAll{fluid_runtime=~"$fluid_runtime",namespace=~"$namespace"}[2m])

![image (5)](https://user-images.githubusercontent.com/25273483/154766431-1ba1114d-ec8e-4ccc-96f3-dd337eddd432.png)
![image (6)](https://user-images.githubusercontent.com/25273483/154766439-0734b281-faf2-4c81-a9c7-c8ff2067e136.png)

![image (7)](https://user-images.githubusercontent.com/25273483/154766440-21e5206a-2062-47d2-87e7-67d761cdbe4e.png)

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
Try to scale down the problem:
Fuse with 1 master, 1 worker, and 5 Fuse pods (scaled down from 8 worker and 40 Fuse pods). The load is same for this worker and each Fuse pod. Each Fuse pod still reads about 50GB data. worker to Fuse pods ratio is similar.
But with this setup, reading from cache is faster than reading from UFS, which is the expected behavior

**Comment by LuQQiu** [comment]
Rerunning the test with 1 master, 8 worker, and 40 Fuse pods.
Master - really low CPU usage (below 10%), no much network
Worker - medium level CPU usage (about 10 - 30%), many disk read, network read and send
Fuse - a low CPU usage (3-30%), some write to disk?, receive a lot of data through network

**Comment by LuQQiu** [comment]
@Nizifan 
Compare `Cluster_BytesReadUfsAll` and `Cluster_BytesReadRemote` is not apple to apple comparison.
They are at different levels in the code base.

BlockReadHandler (BytesReadRemote recorded at this level)
  -> getDataBuffer
          -> UFSBlockReader(BytesReadUfs recorded at this level)

BytesReadRemote includes more logics (locking, executor execute)
and BytesReadUfs is simply getting data from ufs block.

Better to compare the performance from the client-side directly. (e.g. what's the actual read performance differences between cold read and warm read on application level)

But the differences between BytesReadRemote and BytesReadUfs do provide some information about the delay of acquire locks or executor threads

**Comment by LuQQiu** [comment]
[jstack-worker.txt](https://github.com/Alluxio/alluxio/files/8127689/jstack-worker.txt)
[jstack-master.txt](https://git
[jstack-fuse.txt](https://github.com/Alluxio/alluxio/files/8127691/jstack-fuse.txt)
hub.com/Alluxio/alluxio/files/8127690/jstack-master.txt)
Get the jstack when running read from alluxio cache.

From worker jstack: there are only one BlockReader thread, only one file is currently reading from this worker.
```
BlockDataReaderExecutor-1046

stackTrace:
java.lang.Thread.State: RUNNABLE
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:192)
at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
- locked <0x00007efa2115d2c8> (a java.lang.Object)
at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
at alluxio.worker.block.io.LocalFileBlockReader.transferTo(LocalFileBlockReader.java:105)
at alluxio.worker.block.io.DelegatingBlockReader.transferTo(DelegatingBlockReader.java:64)
at alluxio.worker.grpc.BlockReadHandler$DataReader.getDataBuffer(BlockReadHandler.java:518)
at alluxio.worker.grpc.BlockReadHandler$DataReader.runInternal(BlockReadHandler.java:405)
at alluxio.worker.grpc.BlockReadHandler$DataReader.run(BlockReadHandler.java:367)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:125)
at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor$$Lambda$338/1544229824.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Locked ownable synchronizers:
- <0x00007efa0f52b288> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

From the fuse jstack,
There are 17 libfuse reading threads ("Thread-<number>"). thread 6 and 13, thread 7 and 12, thread 8 and 10 are reading the same files.
So libfuse probably is reading 3 to 14 files from this fuse.

There are only two `grpc-default-executor` threads, these two threads are waiting for data to arrive.

**Comment by LuQQiu** [comment]
Why this worker has only one BlockReader thread (only serving one file read request)
- we are not taking jstack in the middle of the read from cache workflow? (@Nizifan can you help validate it, or take multiple worker jstacks from multiple workers)
- The worker cache is unbalanced, some workers have more data cached locally while some workers have less. So the load for each worker is different 
- Not enough load from Fuse? 
   - From this Fuse, it is reading at least 3 files and up to 14 files
   - could it be some Fuse read from some workers stuck (worker bad healthy?)?

**Comment by LuQQiu** [comment]
@Nizifan Some suggestions for investigating this issue
1. After read from Ufs, check if the worker cached size is balanced. whether each of the worker cached 1/8 of the total data size?
2. During the read from UFS, and read from Alluxio cache (for comparison)
(1) take multiple worker `jstack` in the middle of the read process,  if the worker cache is balanced, choose random two workers. If it's unbalanced, choose the one with most cache and the one with least cache
(2) For the fuse process, jstack may not be enough since many threads are just `Running` states which doesn't give much information. Thread profiling with `async_profiler` or `visualVM` (may be hard to use in K8S env) is helpful. Can you help take the read from UFS thread profiling and read from cache thread profiling using `async_profiler`?

**Comment by LuQQiu** [comment]
For more information about thread profiling with async-profiler
https://github.com/jvm-profiling-tools/async-profiler
Profiling the CPU time
```
cd async-profiler && \
./profiler.sh -e cpu -d <profiling duration> -f cpu.html `jps | grep AlluxioFuse | awk '{print $1}'`
```
The command launches after your program running, after the reading from UFS/Cache starts,
the time duration is better to be able to cover most of the test time, e.g. 15min for read from ufs, 30min for read from cache.

Profiling the wall-clock may also be helpful
```
cd async-profiler && \
./profiler.sh -e wall -t -d <profiling duration> -f cpu.html `jps | grep AlluxioFuse | awk '{print $1}'`
```
Better to have two profiling results for comparison (normal -> read from ufs, to debug one read from cache)

**Comment by Nizifan** [comment]
[
[fuse-jstack-ufs-3.txt](https://github.com/Alluxio/alluxio/files/8168166/fuse-jstack-ufs-3.txt)
jstack-worker-ufs3.txt](https://github.com/Alluxio/alluxio/files/8168161/jstack-worker-ufs3.txt)
[jstack-worker-ufs2.txt](https://github.com/Alluxio/alluxio/files/8168162/jstack-worker-ufs2.txt)
[jstack-worker-ufs1.txt](https://github.com
[fuse-jstack-ufs-1.txt](https://github.c
[fuse-jstack-ufs-2.txt](https://github.com/Alluxio/alluxio/files/8168165/fuse-jstack-ufs-2.txt)
om/Alluxio/alluxio/files/8168164/fuse-jstack-ufs-1.txt)
/Alluxio/alluxio/files/8168163/jstack-worker-ufs1.txt)

**Comment by LuQQiu** [comment]
[fuse-jstack-cache-3.txt](https://github.com/Alluxio/alluxio/files/8168361/fuse-jstack-cache-3.txt)
[fuse-jstack-cache-2.txt](https://github.com/Alluxio/alluxio/files/8168363/fuse-jstack-cache-2.txt)
[fuse-jstack-cache-1.txt](https://github.com/Alluxio/alluxio/files/8168364/fuse-jstack-cache-1.txt)
[jstack-worker-cache3.txt](https://github.com/Alluxio/alluxio/files/8168365/jstack-worker-cache3.txt)
[jstack-worker-cache2.txt](https://github.com/Alluxio/alluxio/files/8168366/jstack-worker-cache2.txt)
[jstack-worker-cache1.txt](https://github.com/Alluxio/alluxio/files/8168367/jstack-worker-cache1.txt)

**Comment by LuQQiu** [comment]
jstack-worker-cache1: 30 BlockDataReaderExecutor thread
one of the BlockDataReaderExecutor blocks other six BlockDataReaderExecutor
```
BlockDataReaderExecutor-9833
BlockDataReaderExecutor-9833
Stack Trace is:
java.lang.Thread.State: RUNNABLE
at java.lang.Object.notify(Native Method)
at org.apache.hadoop.ipc.Client$Connection.addCall(Client.java:524)
- locked <0x00007efb14348d10> (a org.apache.hadoop.ipc.Client$Connection)
at org.apache.hadoop.ipc.Client$Connection.access$3700(Client.java:413)
at org.apache.hadoop.ipc.Client.getConnection(Client.java:1623)
at org.apache.hadoop.ipc.Client.call(Client.java:1452)
at org.apache.hadoop.ipc.Client.call(Client.java:1405)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:234)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:119)
at com.sun.proxy.$Proxy54.getBlockLocations(Unknown Source)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
- locked <0x00007ef9e556bbd8> (a org.apache.hadoop.io.retry.RetryInvocationHandler$Call)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
at com.sun.proxy.$Proxy55.getBlockLocations(Unknown Source)
at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:892)
at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:881)
at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:870)
at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1038)
at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:333)
at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329)
at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:346)
at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:945)
at alluxio.underfs.hdfs.HdfsUnderFileSystem.open(HdfsUnderFileSystem.java:613)
at alluxio.underfs.ConsistentUnderFileSystem.openExistingFile(ConsistentUnderFileSystem.java:91)
at alluxio.underfs.UnderFileSystemWithLogging$39.call(UnderFileSystemWithLogging.java:902)
at alluxio.underfs.UnderFileSystemWithLogging$39.call(UnderFileSystemWithLogging.java:899)
at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:1212)
at alluxio.underfs.UnderFileSystemWithLogging.openExistingFile(UnderFileSystemWithLogging.java:899)
at alluxio.worker.block.UfsInputStreamCache.lambda$acquire$2(UfsInputStreamCache.java:220)
at alluxio.worker.block.UfsInputStreamCache$$Lambda$359/127623111.call(Unknown Source)
at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
- locked <0x00007ef9e5568250> (a com.google.common.cache.LocalCache$StrongAccessEntry)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
at alluxio.worker.block.UfsInputStreamCache.acquire(UfsInputStreamCache.java:218)
at alluxio.worker.block.UnderFileSystemBlockReader.updateUnderFileSystemInputStream(UnderFileSystemBlockReader.java:343)
at alluxio.worker.block.UnderFileSystemBlockReader.init(UnderFileSystemBlockReader.java:163)
at alluxio.worker.block.UnderFileSystemBlockReader.create(UnderFileSystemBlockReader.java:115)
at alluxio.worker.block.UnderFileSystemBlockStore.getBlockReader(UnderFileSystemBlockStore.java:243)
at alluxio.worker.block.DefaultBlockWorker.createUfsBlockReader(DefaultBlockWorker.java:526)
at alluxio.worker.block.DefaultBlockWorker.createBlockReader(DefaultBlockWorker.java:682)
at alluxio.worker.grpc.BlockReadHandler$DataReader.openBlock(BlockReadHandler.java:566)
at alluxio.worker.grpc.BlockReadHandler$DataReader.getDataBuffer(BlockReadHandler.java:511)
at alluxio.worker.grpc.BlockReadHandler$DataReader.runInternal(BlockReadHandler.java:405)
at alluxio.worker.grpc.BlockReadHandler$DataReader.run(BlockReadHandler.java:367)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:125)
at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor$$Lambda$338/1544229824.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Locked ownable synchronizers:
- <0x00007efb143431f0> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```
Those be blocked
```
BlockDataReaderExecutor-9830
BlockDataReaderExecutor-9830
Stack Trace is:
java.lang.Thread.State: BLOCKED (on object monitor)
at org.apache.hadoop.ipc.Client$Connection.addCall(Client.java:521)
- waiting to lock <0x00007efb14348d10> (a org.apache.hadoop.ipc.Client$Connection)
at org.apache.hadoop.ipc.Client$Connection.access$3700(Client.java:413)
at org.apache.hadoop.ipc.Client.getConnection(Client.java:1623)
at org.apache.hadoop.ipc.Client.call(Client.java:1452)
at org.apache.hadoop.ipc.Client.call(Client.java:1405)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:234)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:119)
at com.sun.proxy.$Proxy54.getBlockLocations(Unknown Source)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
- locked <0x00007ef9e5aa34a0> (a org.apache.hadoop.io.retry.RetryInvocationHandler$Call)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
at com.sun.proxy.$Proxy55.getBlockLocations(Unknown Source)
at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:892)
at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:881)
at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:870)
at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1038)
at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:333)
at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329)
at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:346)
at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:945)
at alluxio.underfs.hdfs.HdfsUnderFileSystem.open(HdfsUnderFileSystem.java:613)
at alluxio.underfs.ConsistentUnderFileSystem.openExistingFile(ConsistentUnderFileSystem.java:91)
at alluxio.underfs.UnderFileSystemWithLogging$39.call(UnderFileSystemWithLogging.java:902)
at alluxio.underfs.UnderFileSystemWithLogging$39.call(UnderFileSystemWithLogging.java:899)
at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:1212)
at alluxio.underfs.UnderFileSystemWithLogging.openExistingFile(UnderFileSystemWithLogging.java:899)
at alluxio.worker.block.UfsInputStreamCache.lambda$acquire$2(UfsInputStreamCache.java:220)
at alluxio.worker.block.UfsInputStreamCache$$Lambda$359/127623111.call(Unknown Source)
at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
- locked <0x00007ef9e5a9fc68> (a com.google.common.cache.LocalCache$StrongAccessEntry)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
at alluxio.worker.block.UfsInputStreamCache.acquire(UfsInputStreamCache.java:218)
at alluxio.worker.block.UnderFileSystemBlockReader.updateUnderFileSystemInputStream(UnderFileSystemBlockReader.java:343)
at alluxio.worker.block.UnderFileSystemBlockReader.init(UnderFileSystemBlockReader.java:163)
at alluxio.worker.block.UnderFileSystemBlockReader.create(UnderFileSystemBlockReader.java:115)
at alluxio.worker.block.UnderFileSystemBlockStore.getBlockReader(UnderFileSystemBlockStore.java:243)
at alluxio.worker.block.DefaultBlockWorker.createUfsBlockReader(DefaultBlockWorker.java:526)
at alluxio.worker.block.DefaultBlockWorker.createBlockReader(DefaultBlockWorker.java:682)
at alluxio.worker.grpc.BlockReadHandler$DataReader.openBlock(BlockReadHandler.java:566)
at alluxio.worker.grpc.BlockReadHandler$DataReader.getDataBuffer(BlockReadHandler.java:511)
at alluxio.worker.grpc.BlockReadHandler$DataReader.runInternal(BlockReadHandler.java:405)
at alluxio.worker.grpc.BlockReadHandler$DataReader.run(BlockReadHandler.java:367)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:125)
at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor$$Lambda$338/1544229824.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Locked ownable synchronizers:
- <0x00007efb14343c38> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```
12 block-worker-executor

**Comment by LuQQiu** [comment]
jstack-worker-ufs1
6 block data reader executor, 4 blocked, 2 running
ufs2, total 7, 3 waiting, 4 reading
ufs3, total 7, 1 waiting, 6 reading

**Comment by LuQQiu** [comment]
From the jstack, could not find obvious information.
Based on your previous feedback, maybe some of the workers/fuse read fast but some are relatively slow?

**Comment by LuQQiu** [comment]
Tested in Alluxio 
Dataset
10K130MB files, total 1.3TB
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-60901f41-7fff-9bfc-6c73-6579d556f7f7"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Concurrency</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Node | Training_Process/Node | Data_Loading_Process/Training_Process | Total concurrency
-- | -- | -- | --
8 | 5 | 8 | 320

</div><br /></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-71428f90-7fff-de5c-deb9-6d6aca7394ce"><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Alluxio read performance</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">:</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Batch size: 8</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

  | Data in Alluxio | Fuse metadata cached | Kernel cached | Average batch read time (second) | Node throughput | Cluster throughput | Cluster throughput (GB/2min)
-- | -- | -- | -- | -- | -- | -- | --
1 | No | No | No | 33.56 | 1.22 file/s159.4MB/s | 9.76 file/s 1.27 GB/s | 152
2 | Yes | No | No | 23.27 | 1.72 file/s223.4MB/s | 13.76 file/s1.785 GB/s | 214
3 | Yes | No | Yes | 22.12 | 1.8 file/s235 MB/s | 14.46 file/s1.88 GB/s | 225
4 | Yes | Yes | No | 23.35 | 1.7 file/s 222.7 MB/s | 13.7 file/s1.781 GB/s | 214
6 | Yes | Yes | Yes | 16.12 | 2.98 files/s387.3 MB/s | 23.8 files/s3.1 GB/s | 370

</div><br /></b>

The performance of read from cache doesn't show obvious bugs/problems.
According to @Nizifan, their HDFS UFS can reach memory speed under low pressure.
The setup is with SSD Alluxio worker storage, can because read from SSD is slower than read from HDFS directly.
It will be helpful to direct test the throughput of local SSD vs HDFS without Alluxio involved

**Comment by LuQQiu** [comment]
Consider closing this issue for now, @Nizifan if you have future performance requirements or new discoveries, feel free to reopen this issue, thanks!
