### ISSUE TITLE
Allocate extra large memory when generating LostFileCount metric

### ISSUE THREAD

**Issue by kevincai** [Alluxio/alluxio#15042]
**Alluxio Version:**
Alluxio v2.7.0

**Describe the bug**
```
==WARNING==  allocating large array--thread_id[0x00007f0841068000]--thread_name[qtp1109038953-122571]--array_size[1073741848 bytes]--array_length[134217728 elememts]
"qtp1109038953-122571" #122571 prio=5 os_prio=0 cpu=17212.95ms elapsed=614.96s tid=0x00007f0841068000 nid=480536 runnable  [0x00007f080eef5000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap.resize(java.base@11.0.11.11-AJDK/HashMap.java:700)
        at java.util.HashMap.putVal(java.base@11.0.11.11-AJDK/HashMap.java:659)
        at java.util.HashMap.put(java.base@11.0.11.11-AJDK/HashMap.java:608)
        at java.util.HashSet.add(java.base@11.0.11.11-AJDK/HashSet.java:220)
        at alluxio.master.file.DefaultFileSystemMaster.getLostFiles(DefaultFileSystemMaster.java:2774)
        at alluxio.master.file.LostFileDetector.lambda$new$175(LostFileDetector.java:48)
        at alluxio.master.file.LostFileDetector$$Lambda$1174/0x00007f08111b8c70.getValue(Unknown Source)
        at alluxio.metrics.MetricsSystem$1.loadValue(MetricsSystem.java:622)
        at com.codahale.metrics.CachedGauge.getValue(CachedGauge.java:53)
        at io.prometheus.client.dropwizard.DropwizardExports.fromGauge(DropwizardExports.java:62)
        at io.prometheus.client.dropwizard.DropwizardExports.collect(DropwizardExports.java:132)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
        at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:48)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
```

**To Reproduce**

1. Cache million of files into workers
2. Take down workers, so master will mark the workers as LOST, and mark all the blocks on the workers as lost blocks
3. access master metrics REST interface: /metrics/prometheus/, the error will be printed in master log.

**Expected behavior**
A better way to get the number of lost files for metrics collection.

**Urgency**
NA

**Are you planning to fix it**
YES

**Additional context**
NA

**Comment by kevincai** [comment]
The cost to get accurate number of Files are high. A workaround is to get an approximate number of counts for the metrics collection.

1. Every time MasterLostFileDetector heartbeat will update the number of lost files
2. Metric sink only read the static counter from MasterLostFileDetector heartbeat.

so the metric will be updated the same frequency as master LostFileDetector heartbeat.

Long term solution:
* should consider turn the LOST files from PERSISTENT state to NOT_PERSISTENT state as if the cache were evicted if the file is from UFS.

@yuzhu any suggestion about the fix?

**Comment by yuzhu** [comment]
@kevincai I did not get a chance to look at this yet.  is this still an issue? did it require a config fix or code change?
