### ISSUE TITLE
New master join cluster and become the leader, the alluxio cluster is not working

### ISSUE THREAD

**Issue by ccy00808** [Alluxio/alluxio#15048]
**Alluxio Version:**
ALL

**Describe the bug**
Note: ratis can automatically add new nodes to the group.
1.  When the master node is replaced and becomes the leader， follower and worker not worker， because they are not able to identify the new leader。
2. The master address is statically set in conf，After ratis elects the leader successfully, the "alluxio.master.embedded.journal.addresses" in the cluster conf will not be updated
3. Because follower and worker are not able to identity leader, The following exception will be reported periodically:

2022-01-14 10:19:42,151 WARN  RetryHandlingMetaMasterMasterClient - GetId(address=xxxxx:19998) exits with exception [alluxio.exception.status.UnavailableException: Failed to determine address for MetaMasterMaster after 1 attempts] in 120001 ms (>=10000ms)
2022-01-14 10:19:42,151 ERROR MetaMasterSync - Failed to receive leader master heartbeat command.alluxio.exception.status.UnavailableException: Failed to determine address for MetaMasterMaster after 1 attempts        at alluxio.AbstractClient.connect(AbstractClient.java:264)        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:405)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:373)        at alluxio.AbstractClient.retryRPC(AbstractClient.java:362)        at alluxio.master.meta.RetryHandlingMetaMasterMasterClient.getId(RetryHandlingMetaMasterMasterClient.java:81)        at alluxio.master.meta.MetaMasterSync.setIdAndRegister(MetaMasterSync.java:115)        at alluxio.master.meta.MetaMasterSync.heartbeat(MetaMasterSync.java:71)
        at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:119)        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:979)
2022-01-14 10:19:42,152 WARN  SleepingTimer - Meta Master Sync last execution took 120002 ms. Longer than the interval 120000

**To Reproduce**
1. alluxio master was replaced
2. new master become the leader

**Expected behavior**
Workers and followers can identify the leader normally, and alluxio can provide services normally

**Urgency**
NA

**Are you planning to fix it**
YES

**Additional context**
NA

**Comment by HelloHorizon** [comment]
@jenoudet @tcrain can you take a look?

**Comment by HelloHorizon** [comment]
ping @jenoudet

**Comment by ccy00808** [comment]
@jenoudet ,We have some machines that are often offline, and new machines are online at the same time. The newly online machine "alluxio.job.master.embedded.journal.addresses" sets the latest node set, and the old master cannot be recognized after being elected as the new leader.  so the cluster does not work. The impact of no change in cluster machines is controllable, but it has a greater impact on scenarios where machines are frequently replaced.

Currently, we plan to add a synchronization mechanism to update master, worker , jobworker, jobmaster, proxy's "alluxio.job.master.embedded.journal.addresses" according to raftgroup changes
2. worker

**Comment by jenoudet** [comment]
The mismatch comes from the fact that we currently do not support dynamic configuration propagation for Alluxio master addresses. Ratis can and does take into account new masters, but this configuration change current is not propagated to Alluxio. If you want this feature you will have to implement dynamic configuration propagation.

**Comment by jenoudet** [comment]
My suggestion would be to look at the `MasterInquireClient`. Currently, an Embedded Journal deployment uses the `PollingMasterInquireClient` to poll masters to see if they are the leader. A new `RaftInquireClient` could be created using a `RaftClient` to poll the quorum for the leader information.

**Comment by ssz1997** [comment]
@ccy00808 I would suggest instead of putting the static ip address in the configuration, put in the hostname. In kubernetes although the IP of the master pod changes, the hostname doesn't. Other pods should be able to find the new pod with the hostname.

**Comment by ssz1997** [comment]
@ccy00808 Any updates on this issue? Are you still encountering the problem?

**Comment by ssz1997** [comment]
Offline synced. It's not a problem any more.
