### ISSUE TITLE
Worker cannot re-register successfully with 15million files

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#15156]
**Alluxio Version:**
TBD

**Describe the bug**
Dataset: 15millions of 100KB files = 1.5TB
Alluxio cluster: 1 master + 3 workers
Replica: 1

Every time when the master restarts, one or two out of three workers will fail to register with the master.
The failed worker will keep restarting and keep failing to register with the master.

The master can serve requests of the other successfully registered worker.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by LuQQiu** [comment]
Important logs
```
2022-03-17 11:54:11,204 ERROR ProcessUtils - Uncaught exception while running Alluxio worker @10.70.29.34:20020, stopping it and exiting. Exception “alluxio.exception.status.DeadlineExceededException: No response from master for more than 60000ms during the stream!“, Root Cause “alluxio.exception.status.DeadlineExceededException: No response from master for more than 60000ms during the stream!”
alluxio.exception.status.DeadlineExceededException: No response from master for more than 60000ms during the stream!
	at alluxio.worker.block.RegisterStreamer.registerInternal(RegisterStreamer.java:206)
	at alluxio.worker.block.RegisterStreamer.registerWithMaster(RegisterStreamer.java:185)
	at alluxio.worker.block.BlockMasterClient.lambda$registerWithStream$8(BlockMasterClient.java:341)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:406)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
	at alluxio.worker.block.BlockMasterClient.registerWithStream(BlockMasterClient.java:333)
	at alluxio.worker.block.BlockMasterSync.registerWithMaster(BlockMasterSync.java:162)
	at alluxio.worker.block.BlockMasterSync.<init>(BlockMasterSync.java:113)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:249)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:96)
	at alluxio.Registry.start(Registry.java:129)
	at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:281)
	at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:228)
	at alluxio.ProcessUtils.run(ProcessUtils.java:37)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:79)





[9:02](https://alluxio-community.slack.com/archives/C02KBE9RE4B/p1647489740053819)
2022-03-17 11:51:48,040 WARN RegisterStreamObserver - Exit(stream) (Error): registerWorkerStart: WorkerId=8845064499903993866, Error=java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed
2022-03-17 11:51:48,040 ERROR RegisterStreamObserver - Failed to process the RegisterWorkerPRequest in the stream:
java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:359)
	at alluxio.RpcUtils.streamingRPCAndLog(RpcUtils.java:183)
	at alluxio.master.block.RegisterStreamObserver.onNext(RegisterStreamObserver.java:69)
```
@nizifan can you help provide the detailed logs, the master & worker logs covering the restart process

and can you set the debug log of class `alluxio.master.block.RegisterStreamObserver` and get the new logs. https://docs.alluxio.io/os/user/stable/en/operation/User-CLI.html#loglevel

**Comment by LuQQiu** [comment]
@jiacheliu3 FYI

**Comment by kevincai** [comment]
FYI. Had not successfully register worker with 4 million block when we were upgrading from v2.6.2 to v2.7.0, and hence disabled the stream registration. 

Haven't got a chance to look into details about streaming registration yet.

**Comment by Nizifan** [comment]
Core stack trace:
2022-03-17 19:59:50,367 WARN  RegisterStreamObserver - Exit(stream) (Error): registerWorkerStart: WorkerId=460157959576971576, Error=java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed
2022-03-17 19:59:50,367 ERROR RegisterStreamObserver - Failed to process the RegisterWorkerPRequest in the stream: 
java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:359)
	at alluxio.RpcUtils.streamingRPCAndLog(RpcUtils.java:183)
	at alluxio.master.block.RegisterStreamObserver.onNext(RegisterStreamObserver.java:69)
	at alluxio.master.block.RegisterStreamObserver.onNext(RegisterStreamObserver.java:36)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:765)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Mar 17, 2022 7:59:50 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@42fbe475
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202)
2022-03-17 19:59:50,367 ERROR RegisterStreamObserver - Received error from the worker side during the streaming register call: CANCELLED: client cancelled
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374)
	at alluxio.master.block.RegisterStreamObserver$1.exceptionCaught(RegisterStreamObserver.java:112)
	at alluxio.RpcUtils.streamingRPCAndLog(RpcUtils.java:194)
	at alluxio.master.block.RegisterStreamObserver.onNext(RegisterStreamObserver.java:69)
	at alluxio.master.block.RegisterStreamObserver.onNext(RegisterStreamObserver.java:36)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:255)
	at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:765)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Nizifan** [comment]
[pipelineworker.txt](https://github.com/Alluxio/alluxio/files/8284519/pipelineworker.txt)
[Uploading pipelinemasterlog.txt…]()

**Comment by Nizifan** [comment]
Full log:
[pipelineworker.txt](https://github.com/Alluxio/alluxio/files/8284538/pipelineworker.txt)
[pipelinemasterlog.txt](https://github.com/Alluxio/alluxio/files/8284541/pipelinemasterlog.txt)

For @jiacheliu3 to take a look

**Comment by Nizifan** [comment]
Update:
After set alluxio.master.worker.register.stream.response.timeout to 10 minutes, the worker get registered correctly, we shall considering using some continue token when register can no succeed

**Comment by LuQQiu** [comment]
@Nizifan have you tracked how long it takes for all three workers to register themselves successfully?

**Comment by LuQQiu** [comment]
@beinan can your new approach for storing a large amount of small files in worker solve this issue as well?
do we still need to register all blocks to master when restarting worker?

**Comment by LuQQiu** [comment]
> FYI. Had not successfully registered workers with 4 million blocks when upgrading from v2.6.2 to v2.7.0, and hence disabled the stream registration.
> 
> Haven't got a chance to look into details about streaming registration yet.

Hi @kevincai , have you tried setting alluxio.master.worker.register.stream.response.timeout to 10 minutes?

**Comment by Nizifan** [comment]
> @Nizifan Can you help track how long it takes for all three workers to register themselves successfully?
> After we have the numbers @beinan and our team will consider how to improve the register wait time.
> When workers restart, it needs to scan all the blocks on disk, report to master, and master needs to process all those blocks.
> The whole process for millions of million may take long


worker 1:  45:15 - 46:49 - around 94s
2022-03-17 20:45:15,029 INFO  RegisterStreamer - Worker 1510918500665379928 - All requests have been sent. Completing the client side.
2022-03-17 20:45:15,029 INFO  RegisterStreamer - Worker 1510918500665379928 - Waiting on the master side to complete
2022-03-17 20:45:15,038 INFO  RegisterStreamer - 1510918500665379928 - Complete message received from the server. Closing stream
2022-03-17 20:45:15,038 INFO  RegisterStreamer - Worker 1510918500665379928 - Finished registration with a stream
2022-03-17 20:46:49,007 WARN  BlockMasterClient - Heartbeat(workerId=1510918500665379928) returned commandType: Register
2022-03-17 20:46:49,021 INFO  BlockMasterSync - Acquiring a RegisterLease from the master before registering
2022-03-17 20:46:49,028 INFO  BlockMapIterator - Worker register stream batchSize=1000000
2022-03-17 20:46:49,030 INFO  RegisterStreamer - Worker 5444409660821532537 - All requests have been sent. Completing the client side.
2022-03-17 20:46:49,030 INFO  RegisterStreamer - Worker 5444409660821532537 - Waiting on the master side to complete
2022-03-17 20:46:49,055 INFO  RegisterStreamer - 5444409660821532537 - Complete message received from the server. Closing stream
2022-03-17 20:46:49,056 INFO  RegisterStreamer - Worker 5444409660821532537 - Finished registration with a stream

worker 2: 45:14 ~ 46:50 96s
2022-03-17 20:45:14,402 WARN  BlockMasterClient - Heartbeat(workerId=4202614116266097825) returned commandType: Register
2022-03-17 20:45:14,421 INFO  BlockMasterSync - Acquiring a RegisterLease from the master before registering
2022-03-17 20:45:14,430 INFO  BlockMapIterator - Worker register stream batchSize=1000000
2022-03-17 20:45:14,432 INFO  RegisterStreamer - Worker 1942030634004047008 - All requests have been sent. Completing the client side.
2022-03-17 20:45:14,432 INFO  RegisterStreamer - Worker 1942030634004047008 - Waiting on the master side to complete
2022-03-17 20:45:14,457 INFO  RegisterStreamer - 1942030634004047008 - Complete message received from the server. Closing stream
2022-03-17 20:45:14,457 INFO  RegisterStreamer - Worker 1942030634004047008 - Finished registration with a stream
2022-03-17 20:46:50,172 WARN  BlockMasterClient - Heartbeat(workerId=1942030634004047008) returned commandType: Register
2022-03-17 20:46:50,179 INFO  BlockMasterSync - Acquiring a RegisterLease from the master before registering
2022-03-17 20:46:50,182 INFO  BlockMapIterator - Worker register stream batchSize=1000000
2022-03-17 20:46:50,185 INFO  RegisterStreamer - Worker 6165307090372298239 - All requests have been sent. Completing the client side.
2022-03-17 20:46:50,185 INFO  RegisterStreamer - Worker 6165307090372298239 - Waiting on the master side to complete
2022-03-17 20:46:50,190 INFO  RegisterStreamer - 6165307090372298239 - Complete message received from the server. Closing stream
2022-03-17 20:46:50,190 INFO  RegisterStreamer - Worker 6165307090372298239 - Finished registration with a stream

worker 3: 45:15 ~ 46:49
2022-03-17 20:45:15,417 WARN  BlockMasterClient - Heartbeat(workerId=8053804533264619731) returned commandType: Register
2022-03-17 20:45:15,431 INFO  BlockMasterSync - Acquiring a RegisterLease from the master before registering
2022-03-17 20:45:15,440 INFO  BlockMapIterator - Worker register stream batchSize=1000000
2022-03-17 20:45:15,442 INFO  RegisterStreamer - Worker 5300169006694238443 - All requests have been sent. Completing the client side.
2022-03-17 20:45:15,442 INFO  RegisterStreamer - Worker 5300169006694238443 - Waiting on the master side to complete
2022-03-17 20:45:15,451 INFO  RegisterStreamer - 5300169006694238443 - Complete message received from the server. Closing stream
2022-03-17 20:45:15,452 INFO  RegisterStreamer - Worker 5300169006694238443 - Finished registration with a stream
2022-03-17 20:46:49,309 WARN  BlockMasterClient - Heartbeat(workerId=5300169006694238443) returned commandType: Register
2022-03-17 20:46:49,313 INFO  BlockMasterSync - Acquiring a RegisterLease from the master before registering
2022-03-17 20:46:49,316 INFO  BlockMapIterator - Worker register stream batchSize=1000000
2022-03-17 20:46:49,318 INFO  RegisterStreamer - Worker 6755984117028260338 - All requests have been sent. Completing the client side.
2022-03-17 20:46:49,318 INFO  RegisterStreamer - Worker 6755984117028260338 - Waiting on the master side to complete
2022-03-17 20:46:49,322 INFO  RegisterStreamer - 6755984117028260338 - Complete message received from the server. Closing stream
2022-03-17 20:46:49,322 INFO  RegisterStreamer - Worker 6755984117028260338 - Finished registration with a stream

**Comment by LuQQiu** [comment]
@Nizifan From the logs, the registration time is not too long (we previously worried that it may take more than 10 minutes), 1 min `alluxio.master.worker.register.stream.response.timeout` may be too short and is at the borderline. 

@jiacheliu3 looks like the problem can be resolved by enlarging `alluxio.master.worker.register.stream.response.timeout` and the actual registration time is not too long. This problem can be considered as resolved. One remaining question is that whether we consider enlarging the default value for `alluxio.master.worker.register.stream.response.timeout`?
