### ISSUE TITLE
Bug: Alluxio worker can not start if the given disk have file with the same block id

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#15171]
**Alluxio Version:**
2.7.2

**Describe the bug**
User create an 5 workers * 400 Gi Alluxio worker 16 hours ago(current time is 3/18 14:49), and I find 2 of them keep in "CrashLoop" State. The name of this  cluster have been used before and deleted before this instance get created.

Look into the log, find corresponding log show block Id have mismatching.
 blockId 227212527665152 is 160044 bytes, but only 89514 bytes available in SSD

Log into corresponding node, finding the block is created 2 days ago:

root@jssz-main-cv-train-04:~ # ls -lh /data/docker/alluxio/ai/xg-audf3/ai/xg-audf3/alluxioworker/227212527665152
-rwxrwxrwx 1 root root 157K Mar 16 17:09 /data/docker/alluxio/ai/xg-audf3/ai/xg-audf3/alluxioworker/227212527665152
root@jssz-main-cv-train-04:~ # touch a.txt
root@jssz-main-cv-train-04:~ # ls -lh a.txt 
-rw-r--r-- 1 root root 0 Mar 18 14:50 a.txt

So the issue is, if the former worker have create block with that block id but not cleaned them up, the later one can not start on this machine.

Detailed log:
2022-03-18 14:35:02,447 ERROR AlluxioWorker - Fatal error: Failed to create worker process
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: alluxio.exception.WorkerOutOfSpaceException: blockId 227212527665152 is 160044 bytes, but only 89514 bytes available in SSD
	at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:161)
	at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:45)
	at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:37)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:71)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: alluxio.exception.WorkerOutOfSpaceException: blockId 227212527665152 is 160044 bytes, but only 89514 bytes available in SSD
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:594)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:556)
	at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:112)
	... 3 more
Caused by: java.lang.RuntimeException: alluxio.exception.WorkerOutOfSpaceException: blockId 227212527665152 is 160044 bytes, but only 89514 bytes available in SSD
	at alluxio.worker.block.BlockMetadataManager.<init>(BlockMetadataManager.java:123)
	at alluxio.worker.block.BlockMetadataManager.createBlockMetadataManager(BlockMetadataManager.java:140)
	at alluxio.worker.block.TieredBlockStore.<init>(TieredBlockStore.java:122)
	at alluxio.worker.block.DefaultBlockWorker.<init>(DefaultBlockWorker.java:161)
	at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:43)
	at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:26)
	at alluxio.worker.AlluxioWorkerProcess.lambda$new$0(AlluxioWorkerProcess.java:104)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: alluxio.exception.WorkerOutOfSpaceException: blockId 227212527665152 is 160044 bytes, but only 89514 bytes available in SSD
	at alluxio.worker.block.meta.DefaultStorageDir.addBlockMeta(DefaultStorageDir.java:248)
	at alluxio.worker.block.meta.DefaultStorageDir.initializeMeta(DefaultStorageDir.java:156)
	at alluxio.worker.block.meta.DefaultStorageDir.newStorageDir(DefaultStorageDir.java:109)
	at alluxio.worker.block.meta.DefaultStorageTier.initStorageTier(DefaultStorageTier.java:107)
	at alluxio.worker.block.meta.DefaultStorageTier.newStorageTier(DefaultStorageTier.java:197)
	at alluxio.worker.block.BlockMetadataManager.<init>(BlockMetadataManager.java:87)
	... 10 more

**Comment by Nizifan** [comment]
After clean corresponding old directory, the worker work as normal.

**Comment by ssz1997** [comment]
Relates to #15172

**Comment by LuQQiu** [comment]
After discussed with @beinan , there are two approaches for this PR
-  make sure the disk is fully cleaned
- - @ssz1997 can you help take a look to improve the disk clearance
- make sure old blocks are not used for new cluster/worker
- - can add the functionality to https://github.com/Alluxio/alluxio/pull/14258
- - when block_size change, delete/clean the block. persist block_size to worker. Same block id but if with different sizes, then delete/clean this block

**Comment by LuQQiu** [comment]
Update information here
- Make sure the disk is fully cleaned
- - In a plain install, ideally, `bin/alluxio formatWorker` is run before `bin/alluxio-start.sh worker`, basically `entrypoint.sh worker`. After `bin/alluxio-stop.sh worker`, run `bin/alluxio formatWorker` again to clean up worker storage.
- - `bin/alluxio fs free` cleans up the master metadata, but didn't synchronously cleanup the worker storage
- - When Alluxio worker is running, it should have the mechanism of cleaning up the orphaned blocks. @beinan suggesting a new way of putting worker blocks `{timestamp-master-format}/{timestamp-worker-format}/block_files`. Only the `block_files` under the latest `{timestamp-master-format}/{timestamp-worker-format}` can be cleaned up, all the old ones can be cleared and will be cleared by Alluxio worker asynchronously.

- Make sure we only use new blocks instead of old blocks with the same block id
- - `{timestamp-master-format}/{timestamp-worker-format}` can also help us avoid this situation
