### ISSUE TITLE
StressMasterBench report exception in ListDir operation

### ISSUE THREAD

**Issue by lucaspeng12138** [Alluxio/alluxio#15181]
**Alluxio Version:**
master branch [68fcda9](https://github.com/Alluxio/alluxio/commit/68fcda9dd2ca2181eb897e10ca02fa5bc3a3099f)

**Describe the bug**
StressMasterBench report exception as follow:
`2022-03-21 13:40:52,888 ERROR FileSystemMasterClientServiceHandler - Exit (Error): ListStatus: request=path: "/stress_master/files/11.175.135.23-1647594832272/fixed"
options {
  loadMetadataType: ONCE
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: DELETE
  }
  loadMetadataOnly: false
}

java.lang.RuntimeException: Call cancelled by trackers: GRPC_CLIENT_TRACKER
        at alluxio.master.file.RpcContext.throwIfCancelled(RpcContext.java:108)
        at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1132)
        at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1163)
        at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:1089)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$listStatus$9(FileSystemMasterClientServiceHandler.java:246)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:121)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.listStatus(FileSystemMasterClientServiceHandler.java:244)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2400)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
        at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
        at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1356)
        at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)`

**To Reproduce**
Step1. Run CreateFile in StressMasterBench
`bin/alluxio runClass alluxio.stress.cli.StressMasterBench \
--cluster \
--operation CreateFile \
--base alluxio://${alluxio_host}:19998/${master_test_path}/ \
--target-throughput 1000000 \
--create-file-size 1kb \
--warmup 1m \
--duration 3m \
--fixed-count 10000 \
--stop-count 10000`
Step2. Run ListDir in StressMasterBench
`bin/alluxio runClass alluxio.stress.cli.StressMasterBench \
--cluster \
--operation ListDir \
--base alluxio://${alluxio_host}:19998/${master_test_path}/ \
--target-throughput 1000000 \
--warmup 1m \
--duration 3m \
--fixed-count 10000`

could you please help me @HelloHorizon

**Comment by jenoudet** [comment]
Hello @lucaspeng12138, thank you for your patience. Is this still an issue for you?
