### ISSUE TITLE
When a worker node is blocked, the all alluxio cluster cannot provide services for presto queries.

### ISSUE THREAD

**Issue by xinip** [Alluxio/alluxio#15212]
**Alluxio Version:**
2.5.0-1

**Describe the bug**
When a worker node is blocked, the all alluxio cluster cannot provide services for presto queries.
when openMs long time.many half close.

**To Reproduce**
when query many big data.

**Expected behavior**

**Urgency**
High

**Are you planning to fix it**

**Additional context**
2022-03-27 11:20:30,760 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ssd/alluxioworker/5194830053377 bytes: 1048576 openMs: 299901 transferMs: 5 durationMs: 299906
2022-03-27 11:25:38,421 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ram/alluxioworker/786582994944 bytes: 1048576 openMs: 291017 transferMs: 1 durationMs: 291018
2022-03-27 11:30:38,435 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ssd/alluxioworker/4690792153088 bytes: 1048576 openMs: 598047 transferMs: 2 durationMs: 598049
2022-03-27 11:52:40,588 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 5196407111680
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-03-27 11:54:55,591 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 5195115266048
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-03-27 11:54:55,591 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 4687419932672
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-03-27 11:56:25,593 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 5195098488832
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close

2022-03-27 12:17:33,277 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 19610954891264
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-03-27 12:17:33,280 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ssd/alluxioworker/5206104342529 bytes: 1048576 openMs: 3112319 transferMs: 3 durationMs: 3112322
2022-03-27 12:17:33,280 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 15760617373696
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-03-27 12:17:33,282 WARN  BlockReadHandler - Exception occurred while sending data for read request BlockReadRequest{chunkSize=1048576, end=134217728, id=5206104342529, openUfsBlockOptions=ufs_path: "hdfs://masters/hive/warehouse/xxx.db/yyy_table/dt=2020-03-01/000000_0"
offset_in_file: 134217728
block_size: 134217728
maxUfsReadConcurrency: 2147483647
mountId: 1
no_cache: false
, promote=false, sessionId=7243546879341406138, start=0, positionShort=false}.: io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
2022-03-27 12:17:33,282 WARN  UnderFileSystemBlockStore - Key (block ID: 5206104342529, session ID 7243546879341406138) is not found when cleaning up the UFS block.
2022-03-27 12:17:33,282 WARN  UnderFileSystemBlockStore - Key (block ID: 5206104342529, session ID 7243546879341406138) is not found when releasing the UFS block.
2022-03-27 12:18:10,633 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 14730043326464
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-03-27 12:18:10,633 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 13841219977216
promote: false

**Comment by HelloHorizon** [comment]
@beinan can you take a look?

**Comment by beinan** [comment]
Hello @xinip , many thanks for reporting this bug to us!  Can I have more context about this bug?
1. are you using colocated deployment (deploy presto worker and alluxio worker on the same machine) and enabled short-circuit?
2. How did you know an alluxio node is blocked? "the all alluxio cluster cannot provide services for presto queries." do you mean all the presto query failed?  does "alluxio fs ls /" work for you?

**Comment by xinip** [comment]
Hello @beinan 
1.alluxio.user.file.short.circuit.enabled=true
2.when alluxio  cannot provide services,all presto query blocked , I had not "alluxio fs ls /"

**Comment by xinip** [comment]
2022-04-01 20:25:08,832 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ssd/alluxioworker/5189662670848 bytes: 1048576 openMs: 299948 transferMs: 3 durationMs: 299951
2022-04-01 20:27:17,592 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ssd/alluxioworker/5203134775296 bytes: 1048576 openMs: 28749 transferMs: 3 durationMs: 28752
2022-04-01 20:33:55,586 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 824214290433
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-04-01 20:34:40,593 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 5204124631040
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-04-01 20:35:25,593 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 824331730945
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-04-01 20:37:55,585 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 824382062592
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-04-01 21:21:07,229 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ssd/alluxioworker/5190501531648 bytes: 1048576 openMs: 298977 transferMs: 3 durationMs: 298980
2022-04-01 21:26:10,728 WARN  BlockReadHandler - Getting buffer for remote read took longer than 10000 ms. reader: alluxio.worker.block.io.StoreBlockReader location: /home/presto/alluxiodata/data/ssd/alluxioworker/14793947742208 bytes: 1048576 openMs: 299997 transferMs: 3 durationMs: 300000
2022-04-01 21:33:55,584 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 5196541329408
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-04-01 21:34:40,585 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 5203487096832
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-04-01 21:35:25,586 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 5203487096833
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
2022-04-01 21:35:25,586 WARN  ShortCircuitBlockReadHandler - Exception occurred processing read request block_id: 15211935301632
promote: false
.: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close

**Comment by xinip** [comment]
com.facebook.presto.spi.PrestoException: Timeout waiting for response after 300000ms. clientClosed: false clientCancelled: false serverClosed: false (LocalFileDataReader{request=block_id: 19545758629888
promote: false
, address=WorkerNetAddress{host=datanode106, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=datanode106, rack=null)}})
	at com.facebook.presto.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:231)
	at com.facebook.presto.hive.HiveRecordCursor.advanceNextPosition(HiveRecordCursor.java:175)
	at com.facebook.presto.$gen.CursorProcessor_20220401_132648_445579.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processColumnSource(ScanFilterAndProjectOperator.java:252)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:244)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:418)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:301)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:722)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:294)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_248_1_$_git_commit_id_abbrev_____20220218_185330_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: alluxio.exception.status.DeadlineExceededException: Timeout waiting for response after 300000ms. clientClosed: false clientCancelled: false serverClosed: false (LocalFileDataReader{request=block_id: 19545758629888
promote: false
, address=WorkerNetAddress{host=datanode106, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=datanode106, rack=null)}})
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:187)
	at alluxio.client.block.stream.LocalFileDataReader$Factory.<init>(LocalFileDataReader.java:149)
	at alluxio.client.block.stream.BlockInStream.createLocalBlockInStream(BlockInStream.java:158)
	at alluxio.client.block.stream.BlockInStream.create(BlockInStream.java:127)
	at alluxio.client.block.AlluxioBlockStore.getInStream(AlluxioBlockStore.java:217)
	at alluxio.client.file.AlluxioFileInStream.updateStream(AlluxioFileInStream.java:363)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:188)
	at alluxio.hadoop.HdfsFileInputStream.read(HdfsFileInputStream.java:126)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at org.apache.hadoop.mapreduce.lib.input.UncompressedSplitLineReader.fillBuffer(UncompressedSplitLineReader.java:62)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:238)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:193)
	at org.apache.hadoop.mapreduce.lib.input.UncompressedSplitLineReader.readLine(UncompressedSplitLineReader.java:94)
	at org.apache.hadoop.mapred.LineRecordReader.skipUtfByteOrderMark(LineRecordReader.java:208)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:246)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:48)
	at com.facebook.presto.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:213)
	... 15 more

**Comment by beinan** [comment]
Thank you @xinip ! this is very helpful!

two possibilities
1. the alluxio worker's jvm is paused (probably full gc or some other system pause).  Have you enabled the GC log of alluxio workers? what's the jvm setting of your alluxio workers?  
2. The disk is paused somehow, we have seen this on both solid or mechanical hard drives.  This PR might help https://github.com/Alluxio/alluxio/pull/15166. do you mind to give it a shot?  thanks!

**Comment by xinip** [comment]
> Thank you @xinip ! this is very helpful!
> 
> two possibilities
> 
> 1. the alluxio worker's jvm is paused (probably full gc or some other system pause).  Have you enabled the GC log of alluxio workers? what's the jvm setting of your alluxio workers?
> 2. The disk is paused somehow, we have seen this on both solid or mechanical hard drives.  This PR might help [Add timeout logic to local block reading/writing #15166](https://github.com/Alluxio/alluxio/pull/15166). do you mind to give it a shot?  thanks!

**Comment by beinan** [comment]
@xinip any update? have you checked the GC logs?

**Comment by xinip** [comment]
Hello @beinan 
1.jvm gc is normal,memory is enough
2.maybe i should try to update to the next alluxio latest version, i can try

**Comment by xinip** [comment]
> @xinip any update? have you checked the GC logs?

jvm gc is normal,memory is enough

**Comment by beinan** [comment]
Thank you @xinip for the updates! Just let us know if the latest version of alluxio works or not.  I think this commit would be included in 2.7.4, it's already on maven repo but I didn't got a chance to send out the release note.
