### ISSUE TITLE
ClientMasterSync - Failed to get master address during initialization

### ISSUE THREAD

**Issue by allenhaozi** [Alluxio/alluxio#15463]
```
Exception in thread "main" java.lang.RuntimeException: Invalid property key ALLUXIO_CLIENT_HOSTNAME
	at alluxio.conf.InstancedConfiguration.lookupRecursively(InstancedConfiguration.java:454)
	at alluxio.conf.InstancedConfiguration.lookup(InstancedConfiguration.java:427)
	at alluxio.conf.InstancedConfiguration.isResolvable(InstancedConfiguration.java:170)
	at alluxio.conf.InstancedConfiguration.isSet(InstancedConfiguration.java:179)
	at alluxio.conf.AlluxioConfiguration.getOrDefault(AlluxioConfiguration.java:64)
	at alluxio.cli.GetConf.getConfImpl(GetConf.java:190)
	at alluxio.cli.GetConf.getConf(GetConf.java:147)
	at alluxio.cli.GetConf.main(GetConf.java:274)
2022-04-26 14:45:29,624 INFO  MetricsMasterFactory - Creating alluxio.master.metrics.MetricsMaster 
2022-04-26 14:45:29,725 INFO  TableMasterFactory - Creating alluxio.master.table.TableMaster 
2022-04-26 14:45:29,724 INFO  MetaMasterFactory - Creating alluxio.master.meta.MetaMaster 
2022-04-26 14:45:29,524 INFO  FileSystemMasterFactory - Creating alluxio.master.file.FileSystemMaster 
2022-04-26 14:45:29,721 INFO  BlockMasterFactory - Creating alluxio.master.block.BlockMaster 
2022-04-26 14:45:39,088 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-release-2.7.2-SNAPSHOT/lib
2022-04-26 14:45:47,290 INFO  ExtensionFactoryRegistry - Loading extension jars from /opt/alluxio-release-2.7.2-SNAPSHOT/extensions
2022-04-26 14:45:52,988 INFO  MetricsSystem - Starting sinks with config: {}.
2022-04-26 14:45:53,089 INFO  MetricsHeartbeatContext - Created metrics heartbeat with ID app-2401050102813511990. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
2022-04-26 14:45:56,088 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=10.244.0.14, rack=null)
2022-04-26 14:45:56,287 INFO  UnderDatabaseRegistry - Loading udb jars from /opt/alluxio-release-2.7.2-SNAPSHOT/lib
2022-04-26 14:45:58,992 INFO  UnderDatabaseRegistry - Registered UDBs: hive,glue
2022-04-26 14:45:59,090 INFO  LayoutRegistry - Registered Table Layouts: hive
2022-04-26 14:46:11,755 INFO  RocksStore - Opened rocks database under path /opt/alluxio-release-2.7.2-SNAPSHOT/metastore/blocks
2022-04-26 14:46:21,557 INFO  NettyUtils - EPOLL_MODE is available
2022-04-26 14:46:23,153 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-release-2.7.2-SNAPSHOT/lib
2022-04-26 14:46:43,420 INFO  ExtensionFactoryRegistry - Loading extension jars from /opt/alluxio-release-2.7.2-SNAPSHOT/extensions
2022-04-26 14:47:56,650 ERROR ClientMasterSync - Failed to get master address during initialization
alluxio.exception.status.UnavailableException: Failed to handshake with master 10.244.0.14:20196 to load cluster default configuration values: UNAVAILABLE: io exception
	at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:521)
	at alluxio.ClientContext.loadConf(ClientContext.java:134)
	at alluxio.client.metrics.ClientMasterSync.loadConf(ClientMasterSync.java:122)
	at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.MetaMasterConfigurationServiceGrpc$MetaMasterConfigurationServiceBlockingStub.getConfiguration(MetaMasterConfigurationServiceGrpc.java:424)
	at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:515)
	... 10 more

```

**Comment by HelloHorizon** [comment]
@allenhaozi do you have more context about this issue?

**Comment by allenhaozi** [comment]
hi @HelloHorizon , This is my local MAC env, I increased the resource quota and it work

**Comment by itlab1024** [comment]
@allenhaozi how to resove the iisue plz?
