### ISSUE TITLE
v2.8.0 Failed to find any Kerberos tgt

### ISSUE THREAD

**Issue by takersk** [Alluxio/alluxio#15568]
Alluxio Version:
2.8.0

Describe the bug
1. worker logs
`alluxio-worker-thh2j alluxio-job-worker 2022-05-17 02:15:22,047 ERROR UserGroupInformation - PriviledgedActionException as:[test]@[test.com] (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]`

Kerberos ticket expires 24h, and renew is executed according to this cycle, but tickets are not being reissued in some nodes.

**An issue occurs in 1 or 2 nodes out of 25 workers.
v2.7.1 had no problems, only problem with v2.8.0**

2. I've set up kinit as a separate script, but it's the same. >>> unnecessary option

```
bash-5.0$ klist -a
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: hadoop-cdp-write@KAKAO.HADOOP

Valid starting     Expires            Service principal
05/17/22 02:34:22  05/18/22 02:34:22  krbtgt/KAKAO.HADOOP@KAKAO.HADOOP
        renew until 05/24/22 02:34:22
        Addresses: (none)
```

3. namenode connection exception
```
java.io.IOException: Failed on local exception: java.io.IOException: Couldn't setup connection for [user] to [namenode]:8020; Host Details : local host is: [worker]; destination host is: [namenode]:8020; 
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:764)
        at org.apache.hadoop.ipc.Client.call(Client.java:1351)
        at org.apache.hadoop.ipc.Client.call(Client.java:1300)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
        at com.sun.proxy.$Proxy77.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:651)
        at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:186)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy78.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1679)
        at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1106)
        at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1102)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1102)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1397)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem.exists(HdfsUnderFileSystem.java:337)
        at alluxio.underfs.UnderFileSystemWithLogging$15.call(UnderFileSystemWithLogging.java:365)
        at alluxio.underfs.UnderFileSystemWithLogging$15.call(UnderFileSystemWithLogging.java:362)
        at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:1237)
        at alluxio.underfs.UnderFileSystemWithLogging.exists(UnderFileSystemWithLogging.java:362)
        at alluxio.job.plan.persist.PersistDefinition.runTask(PersistDefinition.java:114)
        at alluxio.job.plan.persist.PersistDefinition.runTask(PersistDefinition.java:57)
        at alluxio.worker.job.task.TaskExecutor.run(TaskExecutor.java:88)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Couldn't setup connection for [user] to [namenode]:8020
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:612)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:583)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:667)
        at org.apache.hadoop.ipc.Client$Connection.access$2600(Client.java:314)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1399)
        at org.apache.hadoop.ipc.Client.call(Client.java:1318)
        ... 29 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:404)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:494)
        at org.apache.hadoop.ipc.Client$Connection.access$1700(Client.java:314)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:659)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:655)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:654)
        ... 32 more
```

**v2.7.1 had no problems, only problem with v2.8.0**
**v2.7.1 had no problems, only problem with v2.8.0**
**v2.7.1 had no problems, only problem with v2.8.0**

To Reproduce
See above

Expected behavior
I want it to be retained when reissuing a kerberos ticket.

Urgency
Describe the impact and urgency of the bug.

Are you planning to fix it
No.

Additional context
...

**Comment by takersk** [comment]
alluxio-site.properties

alluxio.master.mount.table.root.ufs: "hdfs://[path]"
alluxio.master.mount.table.root.option.alluxio.underfs.hdfs.configuration: "/secrets/hdfsConfig/core-site.xml:/secrets/hdfsConfig/hdfs-site.xml"

alluxio.master.keytab.file: "[keytab]"
alluxio.master.principal: "[user]@[domain]"
alluxio.worker.keytab.file: "[keytab]"
alluxio.worker.principal: "[user]@[domain]"
alluxio.security.underfs.hdfs.kerberos.client.keytab.file: "[keytab]"
alluxio.security.underfs.hdfs.kerberos.client.principal: "[user]@[domain]"

**Comment by takersk** [comment]
Modify the "ufs.hadoop.version" information in the v2.8.0 project source code to "2.6.0-cdh5.14.2" to match the hadoop version we are using, 

I applied build>package (alluxio-underfs-hdfs-2.6.0-cdh5.14.2 -2.8.0.jar) and there was no problem.
