### ISSUE TITLE
High concurrency Fuse read stuck

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#15643]
**Alluxio Version:**
2.9.0-SNAPSHOT

**Describe the bug**
The read applications generate 64 threads, each thread creates a file in Alluxio and keeps doing sequential read operations with different buffer sizes against the file through Alluxio POSIX API.

After the test run for more than 20 minutes, the read application stuck.
55 threads out of 64 are blocked at reading from AlluxioFuse
```
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(FileInputStream.java:233)
at alluxio.SequentialReadTest.sequentialReadSingleFile(SequentialReadTest.java:49)
```
9 remaining threads are blocked at writing to AlluxioFuse
```
at sun.nio.fs.UnixCopyFile.transfer(Native Method)
at java.nio.file.Files.copy(Files.java:1274)
at alluxio.ReadMain.prepareDataset(ReadMain.java:289)
```
From the Fuse jstack, all threads are blocked waiting to `acquireBlockWorkerClientInternal`. Note that the max value of block worker client is 1024 which should be sufficient.
```
- parking to wait for <0x00007f198e4fb0b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:549)
at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:183)
- locked <0x00007f1f8542b4b0> (a alluxio.client.file.AlluxioFileInStream)
```
```
at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:549)
at alluxio.client.block.stream.LocalFileDataWriter.create(LocalFileDataWriter.java:78)
at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:576)
```
**To Reproduce**
Code: https://github.com/LuQQiu/LuTemp/tree/master/src/main/java/alluxio
Launch the Alluxio cluster and Fuse
<img width="711" alt="Screen Shot 2022-05-27 at 10 57 56 AM" src="https://user-images.githubusercontent.com/25273483/170765384-56d6e4f6-ac30-4b9b-a09a-9728d703b5f1.png">

Run the test program with
```
java -Xmx16G -Xms16G -XX:MaxDirectMemorySize=16g  -cp target/LuTemp-1.0-SNAPSHOT-jar-with-dependencies.jar alluxio.ReadMain -l /local2 -f /mnt/alluxio-fuse -t 64 -i 1 -d 60 -s > testDiff.log
```
The application will stuck after 20min
**Expected behavior**
The application should not stuck

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**
there are 127 RPC threads and 128 Streaming threads in Fuse process.

**Comment by yyongycy** [comment]
Is the native read stuck? Or just slow?

at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(FileInputStream.java:233)
at alluxio.SequentialReadTest.sequentialReadSingleFile(SequentialReadTest.java:49)

**Comment by LuQQiu** [comment]
It's a stuck for more than 1h

**Comment by LuQQiu** [comment]
From the 
 jmap -histo <Fuse process> in the middle
```
 155:          3981         541416  alluxio.client.file.AlluxioFileInStream
 198:          3811         365856  alluxio.client.block.stream.BlockInStream
  217:          3811         304880  alluxio.client.block.stream.LocalFileDataReader$Factory
 254:          3807         213192  alluxio.client.block.stream.LocalFileDataReader
 388:           160          12800  alluxio.client.block.stream.DefaultBlockWorkerClient
```

**Comment by yyongycy** [comment]
Do we have any jstack?

**Comment by LuQQiu** [comment]
The previous jstack
[readMain.csv](https://github.com/Alluxio/alluxio/files/8855544/readMain.csv)
T
[worker.csv](https://github.com/Alluxio/alluxio/files/8855545/worker.csv)
[fuse.csv](https://github.com/Alluxio/alluxio/files/8855536/fuse.csv)
[master.csv](https://github.com/Alluxio/alluxio/files/8855541/master.csv)
but in my latest testing that runs for more than 12 hours, the sequential read didn't fail and didn't stuck....

**Comment by yyongycy** [comment]
I saw 42 gc thread in readMain.csv, is the system overloaded?  That is possible to hang the system.

**Comment by LuQQiu** [comment]
Cannot reproduce... consider closing the issue

**Comment by LuQQiu** [comment]
> I saw 42 gc thread in readMain.csv, is the system overloaded? That is possible to hang the system.

that's possible but not able to verify now
