### ISSUE TITLE
Alluxio Master failed to start

### ISSUE THREAD

**Issue by githubjianli** [Alluxio/alluxio#15677]
**Alluxio Version:**
What version of Alluxio are you using?
2.7.4
**Describe the bug**
Alluxio master keep stopping while reading entries from journal.
BTW, We are running in single node master, no HA enabled.
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
There is not exactly step to reproduce the issue, but we were facing the similar issue few times. Alluxio went offline suddenly,  then when we are trying to restart master service, keep getting below error :
2022-05-30 18:34:05,043 INFO  LogSegment - Successfully read 3096 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20580907-20584002
2022-05-30 18:34:05,092 INFO  LogSegment - Successfully read 4128 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20584003-20588130
2022-05-30 18:34:05,143 INFO  LogSegment - Successfully read 5026 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20588131-20593156
2022-05-30 18:34:05,200 INFO  LogSegment - Successfully read 4220 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20593157-20597376
2022-05-30 18:34:05,256 INFO  LogSegment - Successfully read 5152 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20597377-20602528
2022-05-30 18:34:05,318 INFO  LogSegment - Successfully read 3152 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20602529-20605680
2022-05-30 18:34:05,373 INFO  LogSegment - Successfully read 2820 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20605681-20608500
2022-05-30 18:34:05,429 INFO  LogSegment - Successfully read 3884 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20608501-20612384
2022-05-30 18:34:05,517 INFO  LogSegment - Successfully read 20304 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20612385-20632688
2022-05-30 18:34:05,599 INFO  LogSegment - Successfully read 21794 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20632689-20654482
2022-05-30 18:34:05,622 INFO  FaultTolerantAlluxioMasterProcess - Stopping...
2022-05-30 18:34:05,622 INFO  AlluxioMasterProcess - Stopping...
2022-05-30 18:34:05,679 INFO  LogSegment - Successfully read 21144 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20654483-20675626
2022-05-30 18:34:05,751 INFO  LogSegment - Successfully read 20204 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20675627-20695830
2022-05-30 18:34:05,828 INFO  LogSegment - Successfully read 20332 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20695831-20716162
2022-05-30 18:34:05,902 INFO  LogSegment - Successfully read 19722 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20716163-20735884
2022-05-30 18:34:05,974 INFO  LogSegment - Successfully read 19634 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20735885-20755518
2022-05-30 18:34:06,049 INFO  LogSegment - Successfully read 19584 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20755519-20775102
2022-05-30 18:34:06,119 INFO  LogSegment - Successfully read 5800 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20775103-20780902
2022-05-30 18:34:06,177 INFO  LogSegment - Successfully read 4316 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20780903-20785218
2022-05-30 18:34:06,237 INFO  LogSegment - Successfully read 5348 entries from segment file /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/log_20785219-20790566
**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.
This is not urgent, but we were facing it few times in different envs(test/prod), and we were able to recover the service by either reinstall the whole cluster or format the cluster.

It's annoying and very costly bcs we will need to reload data from s3 over and over again.
 
**Are you planning to fix it**
Please indicate if you are already working on a PR. 
N/A
**Additional context**
N/A

**Comment by yuzhu** [comment]
@githubjianli if you have encountered any exceptions during the journal replay, please post them here.

**Comment by githubjianli** [comment]
2022-05-30 18:42:37,716 INFO  RaftServerConfigKeys - raft.server.log.statemachine.data.sync.timeout = 10s (default)
2022-05-30 18:42:37,716 INFO  RaftServerConfigKeys - raft.server.log.statemachine.data.sync.timeout.retry = -1 (default)
2022-05-30 18:42:37,717 INFO  RaftServerConfigKeys - raft.server.log.write.buffer.size = 64KB (=65536) (default)
2022-05-30 18:42:37,717 INFO  RaftServerConfigKeys - raft.server.log.statemachine.data.caching.enabled = false (default)
2022-05-30 18:42:37,723 ERROR ProcessUtils - Uncaught exception while running Alluxio master @10.19.17.100:19998, stopping it and exiting. Exception "java.io.IOException: Failed to bootstrap raft cluster with addresses [10.19.17.100:19200]: java.nio.file
.NoSuchFileException: /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current", Root Cause "java.io.IOException: Failed to bootstrap raft cluster with addresses [10.19.17.100:19200]: java.nio.file.NoSuchFileException: /journal/raft/02511d47-d67c-49a3-
9011-abb3109a44c1/current"
java.io.IOException: Failed to bootstrap raft cluster with addresses [10.19.17.100:19200]: java.nio.file.NoSuchFileException: /journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current
        at alluxio.master.journal.raft.RaftJournalSystem.startInternal(RaftJournalSystem.java:786)
        at alluxio.master.journal.AbstractJournalSystem.start(AbstractJournalSystem.java:51)
        at alluxio.master.FaultTolerantAlluxioMasterProcess.start(FaultTolerantAlluxioMasterProcess.java:78)
        at alluxio.ProcessUtils.run(ProcessUtils.java:37)
        at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)
2022-05-30 18:42:37,724 INFO  FaultTolerantAlluxioMasterProcess - Stopping...
2022-05-30 18:42:37,724 INFO  AlluxioMasterProcess - Stopping...
2022-05-30 18:42:37,724 ERROR ProcessUtils - Uncaught exception while stopping Alluxio master @10.19.17.100:19998, simply exiting. Exception "java.lang.IllegalStateException: Journal is not running", Root Cause "java.lang.IllegalStateException: Journal i
s not running"
java.lang.IllegalStateException: Journal is not running
        at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
        at alluxio.master.journal.AbstractJournalSystem.stop(AbstractJournalSystem.java:57)
        at alluxio.master.AlluxioMasterProcess.stop(AlluxioMasterProcess.java:166)
        at alluxio.master.FaultTolerantAlluxioMasterProcess.stop(FaultTolerantAlluxioMasterProcess.java:219)
        at alluxio.ProcessUtils.run(ProcessUtils.java:44)
        at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)
2022-05-30 18:42:37,724 INFO  FaultTolerantAlluxioMasterProcess - Stopping...
2022-05-30 18:42:37,724 INFO  AlluxioMasterProcess - Stopping...
2022-05-30 18:42:37,724 ERROR ProcessUtils - Failed to stop process
java.lang.IllegalStateException: Journal is not running
        at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
        at alluxio.master.journal.AbstractJournalSystem.stop(AbstractJournalSystem.java:57)
        at alluxio.master.AlluxioMasterProcess.stop(AlluxioMasterProcess.java:166)
        at alluxio.master.FaultTolerantAlluxioMasterProcess.stop(FaultTolerantAlluxioMasterProcess.java:219)
        at alluxio.ProcessUtils.lambda$stopProcessOnShutdown$0(ProcessUtils.java:98)
        at java.lang.Thread.run(Thread.java:748)
2022-05-30 18:44:09,657 INFO  FileSystemMasterFactory - Creating alluxio.master.file.FileSystemMaster
2022-05-30 18:44:09,657 INFO  MetaMasterFactory - Creating alluxio.master.meta.MetaMaster
2022-05-30 18:44:09,657 INFO  MetricsMasterFactory - Creating alluxio.master.metrics.MetricsMaster
2022-05-30 18:44:09,657 INFO  TableMasterFactory - Creating alluxio.master.table.TableMaster
2022-05-30 18:44:09,657 INFO  BlockMasterFactory - Creating alluxio.master.block.BlockMaster

**Comment by yuzhu** [comment]
might be related to https://github.com/Alluxio/alluxio/pull/14318

**Comment by yuzhu** [comment]
@tcrain does your recent fix on rocks handle help here?

**Comment by yuzhu** [comment]
@githubjianli have you tried a newer version than 2.7.4? The exception you posted is during the shutdown sequence and not the startup sequence. Was there any exception during the startup sequence?
