### ISSUE TITLE
[ERROR][hive.ql.metadata.Hive][load-dynamic-partitions-0] - Exception when loading partition with parameters  

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#15689]
Symptom After Alluxio is mounted to the Hive table, the exception occurs when data is being written.Some tables do not, but this table does, when both duplicate and new partitions are written and dynamic partitioning is enabled.How does this need to be fixed?Why does hive-staging_hiVE_2022-06-08_06-53-46_217_3256132660226127253 need to be synchronized?This is a temporary file. How do I avoid writing this file to alluxio?

```
06-08 06:54:51 [ERROR][hive.ql.metadata.Hive][load-dynamic-partitions-0] - Exception when loading partition with parameters  partPath=alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000/dt=2022-06-06,  table=yysdk_dm_core_live_biz_di,  partSpec={dt=2022-06-06},  replace=true,  listBucketingEnabled=false,  isAcid=false,  hasFollowingStatsTask=false
org.apache.hadoop.hive.ql.metadata.HiveException: Unable to move source alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000/dt=2022-06-06 to destination alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/dt=2022-06-06
	at org.apache.hadoop.hive.ql.metadata.Hive.moveFile(Hive.java:3228)
	at org.apache.hadoop.hive.ql.metadata.Hive.replaceFiles(Hive.java:3485)
	at org.apache.hadoop.hive.ql.metadata.Hive.loadPartition(Hive.java:1657)
	at org.apache.hadoop.hive.ql.metadata.Hive$3.call(Hive.java:1929)
	at org.apache.hadoop.hive.ql.metadata.Hive$3.call(Hive.java:1920)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: alluxio.exception.DirectoryNotEmptyException: Failed to delete /alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/dt=2022-06-06 (UFS dir not in sync. Sync UFS, or delete with unchecked flag.) from the under file system
	at alluxio.hadoop.AbstractFileSystem.delete(AbstractFileSystem.java:267)
	at org.apache.hadoop.hive.ql.metadata.Hive.moveFile(Hive.java:3136)
	... 8 more
Caused by: alluxio.exception.DirectoryNotEmptyException: Failed to delete /alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/dt=2022-06-06 (UFS dir not in sync. Sync UFS, or delete with unchecked flag.) from the under file system
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:582)
	at alluxio.client.file.BaseFileSystem.delete(BaseFileSystem.java:188)
	at alluxio.hadoop.AbstractFileSystem.delete(AbstractFileSystem.java:261)
	... 9 more
06-08 06:54:51 [INFO][com.hiido.server.service.impl.SparkSqlJob][Driver] - user dw_yuanbingze throw Exception
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 2 in table yysdk_dm_core_live_biz_di with loadPath=alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:111)
	at org.apache.spark.sql.hive.HiveExternalCatalog.loadDynamicPartitions(HiveExternalCatalog.scala:933)
	at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.loadDynamicPartitions(ExternalCatalogWithListener.scala:189)
	at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.processInsert(InsertIntoHiveTable.scala:268)
	at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.run(InsertIntoHiveTable.scala:106)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:482)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:81)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:482)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:456)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
	at com.hiido.server.service.impl.SparkSqlJob.executing(SparkSqlJob.java:78)
	at com.hiido.server.service.impl.SparkSqlJob.main(SparkSqlJob.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 2 in table yysdk_dm_core_live_biz_di with loadPath=alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000
	at org.apache.hadoop.hive.ql.metadata.Hive.loadDynamicPartitions(Hive.java:1970)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.sql.hive.client.Shim_v2_1.loadDynamicPartitions(HiveShim.scala:1299)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$loadDynamicPartitions$1(HiveClientImpl.scala:930)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:309)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:240)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:239)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:289)
	at org.apache.spark.sql.hive.client.HiveClientImpl.loadDynamicPartitions(HiveClientImpl.scala:921)
	at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$loadDynamicPartitions$1(HiveExternalCatalog.scala:953)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:102)
	... 41 more
Caused by: java.util.concurrent.ExecutionException: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to move source alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000/dt=2022-06-06 to destination alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/dt=2022-06-06
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.hadoop.hive.ql.metadata.Hive.loadDynamicPartitions(Hive.java:1961)
	... 56 more
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to move source alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000/dt=2022-06-06 to destination alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/dt=2022-06-06
	at org.apache.hadoop.hive.ql.metadata.Hive.moveFile(Hive.java:3228)
	at org.apache.hadoop.hive.ql.metadata.Hive.replaceFiles(Hive.java:3485)
	at org.apache.hadoop.hive.ql.metadata.Hive.loadPartition(Hive.java:1657)
	at org.apache.hadoop.hive.ql.metadata.Hive$3.call(Hive.java:1929)
	at org.apache.hadoop.hive.ql.metadata.Hive$3.call(Hive.java:1920)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: alluxio.exception.DirectoryNotEmptyException: Failed to delete /alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/dt=2022-06-06 (UFS dir not in sync. Sync UFS, or delete with unchecked flag.) from the under file system
	at alluxio.hadoop.AbstractFileSystem.delete(AbstractFileSystem.java:267)
	at org.apache.hadoop.hive.ql.metadata.Hive.moveFile(Hive.java:3136)
	... 8 more
Caused by: alluxio.exception.DirectoryNotEmptyException: Failed to delete /alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/dt=2022-06-06 (UFS dir not in sync. Sync UFS, or delete with unchecked flag.) from the under file system
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:582)
	at alluxio.client.file.BaseFileSystem.delete(BaseFileSystem.java:188)
	at alluxio.hadoop.AbstractFileSystem.delete(AbstractFileSystem.java:261)
	... 9 more
06-08 06:54:51 [ERROR][org.apache.spark.deploy.yarn.ApplicationMaster][Driver] - User class threw exception: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 2 in table yysdk_dm_core_live_biz_di with loadPath=alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000; line -1 pos -1
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 2 in table yysdk_dm_core_live_biz_di with loadPath=alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000; line -1 pos -1
	at com.hiido.server.service.impl.SparkSqlJob.executing(SparkSqlJob.java:143)
	at com.hiido.server.service.impl.SparkSqlJob.main(SparkSqlJob.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)
06-08 06:54:51 [INFO][org.apache.spark.deploy.yarn.ApplicationMaster][Driver] - Final app status: FAILED, exitCode: 15, (reason: User class threw exception: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 2 in table yysdk_dm_core_live_biz_di with loadPath=alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000; line -1 pos -1
	at com.hiido.server.service.impl.SparkSqlJob.executing(SparkSqlJob.java:143)
	at com.hiido.server.service.impl.SparkSqlJob.main(SparkSqlJob.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)
)
06-08 06:54:51 [INFO][org.apache.spark.SparkContext][shutdown-hook-0] - Invoking stop() from shutdown hook
06-08 06:54:51 [INFO][org.apache.spark.ui.SparkUI][shutdown-hook-0] - Stopped Spark web UI at http://fs-hiido-dn-12-10-31.hiido.host.yydevops.com:23553
06-08 06:54:51 [INFO][org.apache.spark.scheduler.cluster.YarnClusterSchedulerBackend][shutdown-hook-0] - Shutting down all executors
06-08 06:54:51 [INFO][org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnDriverEndpoint][dispatcher-CoarseGrainedScheduler] - Asking each executor to shut down
06-08 06:54:51 [INFO][org.apache.spark.MapOutputTrackerMasterEndpoint][dispatcher-event-loop-2] - MapOutputTrackerMasterEndpoint stopped!
06-08 06:54:51 [INFO][org.apache.spark.storage.memory.MemoryStore][shutdown-hook-0] - MemoryStore cleared
06-08 06:54:51 [INFO][org.apache.spark.storage.BlockManager][shutdown-hook-0] - BlockManager stopped
06-08 06:54:51 [INFO][org.apache.spark.storage.BlockManagerMaster][shutdown-hook-0] - BlockManagerMaster stopped
06-08 06:54:51 [INFO][org.apache.spark.scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint][dispatcher-event-loop-0] - OutputCommitCoordinator stopped!
06-08 06:54:51 [INFO][org.apache.spark.SparkContext][shutdown-hook-0] - Successfully stopped SparkContext
06-08 06:54:51 [INFO][org.apache.spark.deploy.yarn.ApplicationMaster][shutdown-hook-0] - Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 2 in table yysdk_dm_core_live_biz_di with loadPath=alluxio://fs-alluxio-master01.hiido.host.yydevops.com:19998,fs-alluxio-master02.hiido.host.yydevops.com:19998,fs-alluxio-master03.hiido.host.yydevops.com:19998/alluxio_mnt/yycluster02/hive_warehouse/yysdk.db/yysdk_dm_core_live_biz_di/.hive-staging_hive_2022-06-08_06-53-46_217_3256132660226127253-1/-ext-10000; line -1 pos -1
	at com.hiido.server.service.impl.SparkSqlJob.executing(SparkSqlJob.java:143)
	at com.hiido.server.service.impl.SparkSqlJob.main(SparkSqlJob.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)
)
06-08 06:54:51 [INFO][org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl][shutdown-hook-0] - Waiting for application to be successfully unregistered.
```
After removing the Alluxio mount, the job returned to normal, so this is an Alluxio bug

**Comment by liangrui1988** [comment]
alluxio.user.file.delete.unchecked  =true
Solved the problem

**Comment by liangrui1988** [comment]
alluxio.user.file.delete.unchecked =true
Solved the problem
