### ISSUE TITLE
Unable to write to a read-only file when creating it

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#15808]
**Alluxio Version:**
2.7.1

**Describe the bug**

For the local file system, it is ok to write content to a read-only permission file while creating it. But it encountered "Permission denied" in alluxio.

**To Reproduce**

Test code

```
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

int main() {
    int fd = open("./test-write", O_RDWR|O_CREAT|O_EXCL, 0400);
    write(fd, "test", 4);
    close(fd);
    printf("Finished\n");
    return 0;
}
```

The code works well under a local file system path

```
> cat /tmp/test-write
test
> ll /tmp/test-write
-r--------  1 test_user  wheel  4 30 Jun 22:42 /tmp/test-write
```

The code encountered the following exception while running under a alluxio-fuse path with a non-super user

```
2022-07-01 14:29:32,421 Thread-18 WARN  AlluxioFileOutStream - Failed to write into AlluxioStore, canceling write attempt.
alluxio.exception.status.PermissionDeniedException: Permission denied: user=test_user, access=-w-, path=/projects/sidecar/test-write: failed at test-write, inode owner=test_user, inode group=test_user
, inode mode=r--------
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:140)
        at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:224)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:408)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.client.file.RetryHandlingFileSystemMasterClient.getNewBlockIdForFile(RetryHandlingFileSystemMasterClient.java:217)
        at alluxio.client.file.AlluxioFileOutStream.getNextBlockId(AlluxioFileOutStream.java:309)
        at alluxio.client.file.AlluxioFileOutStream.getNextBlock(AlluxioFileOutStream.java:301)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:267)
        at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:229)
        at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:636)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$6(AlluxioJniFuseFileSystem.java:554)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:332)
        at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:554)
        at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:333)
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied: user=test_user, access=-w-, path=/projects/sidecar/test-write: failed at test-write, inode owner=test_user, inode group=test_user, inode mode=r--------
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.getNewBlockIdForFile(FileSystemMasterClientServiceGrpc.java:1749)
        at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$getNewBlockIdForFile$11(RetryHandlingFileSystemMasterClient.java:218)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:406)
        ... 12 more
```

**Expected behavior**

**Urgency**
Normal

**Are you planning to fix it**
Yes

**Additional context**
No

**Comment by yyongycy** [comment]
why should you write to a read-only file?

**Comment by secfree** [comment]
> why should you write to a read-only file?

We need to execute "git clone" in an aluxio-fuse mounted path, and "git clone" creates some files under ".git/objects" with read-only permission.

**Comment by LuQQiu** [comment]
Strange that my workload has no obvious problem

**Comment by LuQQiu** [comment]
git clone https://github.com/Alluxio/alluxio

**Comment by secfree** [comment]
> Strange that my workload has no obvious problem, pjdfstest added test case

@LuQQiu can you check if you are using a privileged user in your system? 
https://github.com/Alluxio/alluxio/blob/master/core/server/master/src/main/java/alluxio/master/file/DefaultPermissionChecker.java#L294

**Comment by LuQQiu** [comment]
EXT4 requires
