### ISSUE TITLE
NPE at DefaultStorageTierAssoc.getOrdinal when using paged block store

### ISSUE THREAD

**Issue by dbw9580** [Alluxio/alluxio#15930]
**Alluxio Version:**
What version of Alluxio are you using?
current master

**Describe the bug**

When using the paged block store, block master cannot find a tier in the global tier list. This causes a NPE.

```
2022-07-21 09:25:28,311 ERROR FileSystemMasterClientServiceHandler - Exit (Error): ListStatus: request=path: "/"
options {
  loadMetadataType: ONCE
  commonOptions {
    syncIntervalMs: -1
    ttl: -1
    ttlAction: DELETE
  }
  recursive: true
  loadMetadataOnly: false
}

java.lang.NullPointerException
 at alluxio.DefaultStorageTierAssoc.getOrdinal(DefaultStorageTierAssoc.java:99)
 at alluxio.master.file.DefaultFileSystemMaster.isInTopStorageTier(DefaultFileSystemMaster.java:2401)
 at alluxio.master.file.DefaultFileSystemMaster.getFileInMemoryPercentageInternal(DefaultFileSystemMaster.java:2351)
 at alluxio.master.file.DefaultFileSystemMaster.getFileInfoInternal(DefaultFileSystemMaster.java:965)
 at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1213)
 at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1201)
 at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1201)
 at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:1124)
 at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$listStatus$10(FileSystemMasterClientServiceHandler.java:255)
 at alluxio.RpcUtils.callAndReturn(RpcUtils.java:123)
 at alluxio.master.file.FileSystemMasterClientServiceHandler.listStatus(FileSystemMasterClientServiceHandler.java:253)

<snip>
```

**To Reproduce**
Use paged block store and do a `ls` on a file.

**Additional context**

Current tier of paged block store is `DefaultTier`, but `alluxio.master.block.DefaultBlockMaster#MASTER_STORAGE_TIER_ASSOC` expects it to be one of `MEM` `SSD` `HDD`.

**Comment by dbw9580** [comment]
@beinan FYI.
