### ISSUE TITLE
Out of bound exception when reading fron paged block store

### ISSUE THREAD

**Issue by dbw9580** [Alluxio/alluxio#15995]
**Alluxio Version:**
current master

**Describe the bug**

ArrayIndexOutOfBoundsException when doing random reads from a paged block.

```
2022-08-02 06:35:49,058 DEBUG BlockReadHandler - Exception occurred while reading data for read request BlockReadRequest{chunkSize=1048576, end=14830815, id=16777216, openUfsBlockOptions=ufs_path: “hdfs://BlockStorePerfPage-master-0:9000/alluxio_ufs/stress-worker-bench-base/data0”
offset_in_file: 0
block_size: 20971520
maxUfsReadConcurrency: 2147483647
mountId: 1
no_cache: false
, promote=false, sessionId=1871510110820781136, start=14789855, positionShort=true}. session 1871510110820781136
java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at alluxio.worker.page.PagedBlockReader.read(PagedBlockReader.java:107)
        at alluxio.worker.grpc.BlockReadHandler$DataReader.getDataBuffer(BlockReadHandler.java:528)
        at alluxio.worker.grpc.BlockReadHandler$DataReader.runInternal(BlockReadHandler.java:407)
        at alluxio.worker.grpc.BlockReadHandler$DataReader.run(BlockReadHandler.java:369)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:144)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by dbw9580** [comment]
@beinan FYI. Not sure if it's related 3d205d8119c4de95971e49a153a2427ebf01ae11

**Comment by bobbai00** [comment]
The reproduce method is:
1. set `alluxio.worker.network.reader.buffer.pooled` as `false`;
2. use `PAGE` as the block store.
3. client calls ` public int read(long position, byte[] buffer, int offset, int length)`

**Comment by beinan** [comment]
The change of https://github.com/Alluxio/alluxio/commit/3d205d8119c4de95971e49a153a2427ebf01ae11 is on the write path, so I guess it won't be related.

**Comment by bobbai00** [comment]
By running several clusters, we find that:
| alluxio.worker.network.reader.buffer.pooled | write mode | error? |
| ------------------- | ------------------ | -------------- |
| `true` | sequential read | No |
| `false` | sequential read | No |
| `true` | random read | No |
| `false` | random read | Yes |
