### ISSUE TITLE
Read alluxio files get "input/output error" 

### ISSUE THREAD

**Issue by flyhighzy** [Alluxio/alluxio#16045]
**Alluxio Version:**
2.7.2-0703ba35241e96f8405614dc20e7c7db09167abb

**Describe the bug**
process get multiple input/output error when reading files in alluxio when caching files at about 61million level:
![image](https://user-images.githubusercontent.com/1246062/184311014-9dee3547-efef-4129-b081-495dbdf17c6e.png)

abount between 2022-08-12 07:19 ~ 2022-08-12 08:32, reading process got input/output error and finally fail, here is the alluxio master's log and job-master.log:

master's log around the event time:
```
2022-08-12 06:02:15,653 WARN  SleepingTimer - Master Replication Check last execution took 1240639 ms. Longer than the interval 60000
2022-08-12 06:23:49,550 WARN  SleepingTimer - Master Replication Check last execution took 1293897 ms. Longer than the interval 60000
2022-08-12 06:43:52,917 WARN  SleepingTimer - Master Replication Check last execution took 1203367 ms. Longer than the interval 60000
2022-08-12 07:03:25,188 WARN  SleepingTimer - Master Replication Check last execution took 1172270 ms. Longer than the interval 60000
2022-08-12 07:24:19,460 WARN  SleepingTimer - Master Replication Check last execution took 1254272 ms. Longer than the interval 60000
2022-08-12 07:44:51,052 WARN  SleepingTimer - Master Replication Check last execution took 1231592 ms. Longer than the interval 60000
2022-08-12 08:04:13,591 WARN  SleepingTimer - Master Replication Check last execution took 1162539 ms. Longer than the interval 60000
2022-08-12 08:24:48,230 WARN  SleepingTimer - Master Replication Check last execution took 1234639 ms. Longer than the interval 60000
2022-08-12 08:44:38,284 WARN  SleepingTimer - Master Replication Check last execution took 1190054 ms. Longer than the interval 60000
2022-08-12 09:05:19,559 WARN  SleepingTimer - Master Replication Check last execution took 1241275 ms. Longer than the interval 60000
2022-08-12 09:27:00,113 WARN  SleepingTimer - Master Replication Check last execution took 1300554 ms. Longer than the interval 60000
```

job-master's log around the event time are all like this:
```
2022-08-12 07:54:18,436 INFO  PlanCoordinator - Starting job Id=1660216842782 Config=EvictConfig{blockId=439232883589120, replicas=1}
2022-08-12 07:54:18,493 INFO  PlanCoordinator - Starting job Id=1660216842783 Config=EvictConfig{blockId=474489733251072, replicas=1}
2022-08-12 07:54:18,620 INFO  PlanCoordinator - Starting job Id=1660216842784 Config=EvictConfig{blockId=360271117811712, replicas=1}
2022-08-12 07:54:18,857 INFO  PlanCoordinator - Starting job Id=1660216842785 Config=EvictConfig{blockId=510085885329408, replicas=1}
2022-08-12 07:54:19,033 INFO  PlanCoordinator - Starting job Id=1660216842786 Config=EvictConfig{blockId=543268265787392, replicas=1}
2022-08-12 07:54:19,054 INFO  PlanCoordinator - Starting job Id=1660216842787 Config=EvictConfig{blockId=446526140710912, replicas=1}
2022-08-12 07:54:19,074 INFO  PlanCoordinator - Starting job Id=1660216842788 Config=EvictConfig{blockId=428963751002112, replicas=1}
2022-08-12 07:54:19,089 INFO  PlanCoordinator - Starting job Id=1660216842789 Config=EvictConfig{blockId=464164766089216, replicas=1}
2022-08-12 07:54:19,213 INFO  PlanCoordinator - Starting job Id=1660216842790 Config=EvictConfig{blockId=481890364555264, replicas=1}
2022-08-12 07:54:19,345 INFO  PlanCoordinator - Starting job Id=1660216842791 Config=EvictConfig{blockId=429260103745536, replicas=1}
2022-08-12 07:54:19,385 INFO  PlanCoordinator - Starting job Id=1660216842792 Config=EvictConfig{blockId=394114923233280, replicas=1}
2022-08-12 07:54:19,497 INFO  PlanCoordinator - Starting job Id=1660216842793 Config=EvictConfig{blockId=561371821375488, replicas=1}
2022-08-12 07:54:19,535 INFO  PlanCoordinator - Starting job Id=1660216842794 Config=EvictConfig{blockId=359107181674496, replicas=1}
2022-08-12 07:54:19,770 INFO  PlanCoordinator - Starting job Id=1660216842795 Config=EvictConfig{blockId=412149759344640, replicas=1}
2022-08-12 07:54:19,871 INFO  PlanCoordinator - Starting job Id=1660216842796 Config=EvictConfig{blockId=315505881645056, replicas=1}
2022-08-12 07:54:20,063 INFO  PlanCoordinator - Starting job Id=1660216842797 Config=EvictConfig{blockId=313521606754304, replicas=1}
2022-08-12 07:54:20,283 INFO  PlanCoordinator - Starting job Id=1660216842798 Config=EvictConfig{blockId=392933807226880, replicas=1}
2022-08-12 07:54:20,351 INFO  PlanCoordinator - Starting job Id=1660216842799 Config=EvictConfig{blockId=375411145965568, replicas=1}
2022-08-12 07:54:20,361 INFO  PlanCoordinator - Starting job Id=1660216842800 Config=EvictConfig{blockId=507358581096448, replicas=1}
2022-08-12 07:54:20,414 INFO  PlanCoordinator - Starting job Id=1660216842801 Config=EvictConfig{blockId=401867204984832, replicas=1}
2022-08-12 07:54:20,435 INFO  PlanCoordinator - Starting job Id=1660216842802 Config=EvictConfig{blockId=375492750344192, replicas=1}
2022-08-12 07:54:20,445 INFO  PlanCoordinator - Starting job Id=1660216842803 Config=EvictConfig{blockId=489865984606208, replicas=1}
2022-08-12 07:54:20,504 INFO  PlanCoordinator - Starting job Id=1660216842804 Config=EvictConfig{blockId=401957399298048, replicas=1}
2022-08-12 07:54:20,588 INFO  PlanCoordinator - Starting job Id=1660216842805 Config=EvictConfig{blockId=560383978897408, replicas=1}
2022-08-12 07:54:20,666 INFO  PlanCoordinator - Starting job Id=1660216842806 Config=EvictConfig{blockId=454918372589568, replicas=1}
2022-08-12 07:54:20,726 INFO  PlanCoordinator - Starting job Id=1660216842807 Config=EvictConfig{blockId=560538597720064, replicas=1}
2022-08-12 07:54:20,898 INFO  PlanCoordinator - Starting job Id=1660216842808 Config=EvictConfig{blockId=358415691939840, replicas=1}
2022-08-12 07:54:21,062 INFO  PlanCoordinator - Starting job Id=1660216842809 Config=EvictConfig{blockId=312417800159232, replicas=1}
2022-08-12 07:54:21,138 INFO  PlanCoordinator - Starting job Id=1660216842810 Config=EvictConfig{blockId=418055205158912, replicas=1}
2022-08-12 07:54:21,192 INFO  PlanCoordinator - Starting job Id=1660216842811 Config=EvictConfig{blockId=470894845624320, replicas=1}
2022-08-12 07:54:21,346 INFO  PlanCoordinator - Starting job Id=1660216842812 Config=EvictConfig{blockId=391898720108544, replicas=1}
2022-08-12 07:54:21,350 INFO  PlanCoordinator - Starting job Id=1660216842813 Config=EvictConfig{blockId=471079529218048, replicas=1}
2022-08-12 07:54:21,554 INFO  PlanCoordinator - Starting job Id=1660216842814 Config=EvictConfig{blockId=392130648342528, replicas=1}
2022-08-12 07:54:21,893 INFO  PlanCoordinator - Starting job Id=1660216842815 Config=EvictConfig{blockId=454085148934144, replicas=1}
2022-08-12 07:54:21,966 INFO  PlanCoordinator - Starting job Id=1660216842816 Config=EvictConfig{blockId=443180361187328, replicas=1}
2022-08-12 07:54:22,083 INFO  PlanCoordinator - Starting job Id=1660216842817 Config=EvictConfig{blockId=548856420892672, replicas=1}
2022-08-12 07:54:22,137 INFO  PlanCoordinator - Starting job Id=1660216842818 Config=EvictConfig{blockId=531324095954944, replicas=1}
2022-08-12 07:54:22,171 INFO  PlanCoordinator - Starting job Id=1660216842819 Config=EvictConfig{blockId=355434984636416, replicas=1}
2022-08-12 07:54:22,305 INFO  PlanCoordinator - Starting job Id=1660216842820 Config=EvictConfig{blockId=522717652582400, replicas=1}
2022-08-12 07:54:22,423 INFO  PlanCoordinator - Starting job Id=1660216842821 Config=EvictConfig{blockId=549247262916608, replicas=1}
2022-08-12 07:54:22,723 INFO  PlanCoordinator - Starting job Id=1660216842822 Config=EvictConfig{blockId=320882509611008, replicas=1}
2022-08-12 07:54:23,394 INFO  PlanCoordinator - Starting job Id=1660216842823 Config=EvictConfig{blockId=503587599810560, replicas=1}
2022-08-12 07:54:23,729 INFO  PlanCoordinator - Starting job Id=1660216842824 Config=EvictConfig{blockId=310442115203072, replicas=1}
2022-08-12 07:54:23,939 INFO  PlanCoordinator - Starting job Id=1660216842825 Config=EvictConfig{blockId=451417974243328, replicas=1}
2022-08-12 07:54:24,036 INFO  PlanCoordinator - Starting job Id=1660216842826 Config=EvictConfig{blockId=486666233970688, replicas=1}
2022-08-12 07:54:24,343 INFO  PlanCoordinator - Starting job Id=1660216842827 Config=EvictConfig{blockId=310996165984256, replicas=1}
2022-08-12 07:54:24,429 INFO  PlanCoordinator - Starting job Id=1660216842828 Config=EvictConfig{blockId=328669151100928, replicas=1}
2022-08-12 07:54:24,720 INFO  PlanCoordinator - Starting job Id=1660216842829 Config=EvictConfig{blockId=537903851634688, replicas=1}
2022-08-12 07:54:24,742 INFO  PlanCoordinator - Starting job Id=1660216842830 Config=EvictConfig{blockId=467566245969920, replicas=1}
2022-08-12 07:54:24,858 INFO  PlanCoordinator - Starting job Id=1660216842831 Config=EvictConfig{blockId=309351193509888, replicas=1}
2022-08-12 07:54:24,942 INFO  PlanCoordinator - Starting job Id=1660216842832 Config=EvictConfig{blockId=406201229639680, replicas=1}
2022-08-12 07:54:25,110 INFO  PlanCoordinator - Starting job Id=1660216842833 Config=EvictConfig{blockId=529537389559808, replicas=1}
2022-08-12 07:54:25,321 INFO  PlanCoordinator - Starting job Id=1660216842834 Config=EvictConfig{blockId=406622136434688, replicas=1}
2022-08-12 07:54:25,383 INFO  PlanCoordinator - Starting job Id=1660216842835 Config=EvictConfig{blockId=503450160857088, replicas=1}
2022-08-12 07:54:25,612 INFO  PlanCoordinator - Starting job Id=1660216842836 Config=EvictConfig{blockId=351964651061248, replicas=1}
2022-08-12 07:54:25,679 INFO  PlanCoordinator - Starting job Id=1660216842837 Config=EvictConfig{blockId=387230090657792, replicas=1}
2022-08-12 07:54:25,683 INFO  PlanCoordinator - Starting job Id=1660216842838 Config=EvictConfig{blockId=360837919277056, replicas=1}
2022-08-12 07:54:25,794 INFO  PlanCoordinator - Starting job Id=1660216842839 Config=EvictConfig{blockId=360958178361344, replicas=1}
2022-08-12 07:54:26,027 INFO  PlanCoordinator - Starting job Id=1660216842840 Config=EvictConfig{blockId=545948728033280, replicas=1}
2022-08-12 07:54:26,095 INFO  PlanCoordinator - Starting job Id=1660216842841 Config=EvictConfig{blockId=546013152542720, replicas=1}
2022-08-12 07:54:26,257 INFO  PlanCoordinator - Starting job Id=1660216842842 Config=EvictConfig{blockId=519805664755712, replicas=1}
2022-08-12 07:54:26,427 INFO  PlanCoordinator - Starting job Id=1660216842843 Config=EvictConfig{blockId=484810808098816, replicas=1}
2022-08-12 07:54:26,442 INFO  PlanCoordinator - Starting job Id=1660216842844 Config=EvictConfig{blockId=335296688291840, replicas=1}
2022-08-12 07:54:26,873 INFO  PlanCoordinator - Starting job Id=1660216842845 Config=EvictConfig{blockId=535889511972864, replicas=1}
2022-08-12 07:54:27,066 INFO  PlanCoordinator - Starting job Id=1660216842846 Config=EvictConfig{blockId=465736589901824, replicas=1}
2022-08-12 07:54:27,228 INFO  PlanCoordinator - Starting job Id=1660216842847 Config=EvictConfig{blockId=360361177907200, replicas=1}
2022-08-12 07:54:27,254 INFO  PlanCoordinator - Starting job Id=1660216842848 Config=EvictConfig{blockId=483530907844608, replicas=1}
2022-08-12 07:54:27,620 INFO  PlanCoordinator - Starting job Id=1660216842849 Config=EvictConfig{blockId=420172758253568, replicas=1}
2022-08-12 07:54:27,632 INFO  PlanCoordinator - Starting job Id=1660216842850 Config=EvictConfig{blockId=428976501686272, replicas=1}
2022-08-12 07:54:27,687 INFO  PlanCoordinator - Starting job Id=1660216842851 Config=EvictConfig{blockId=420237182763008, replicas=1}
2022-08-12 07:54:27,691 INFO  PlanCoordinator - Starting job Id=1660216842852 Config=EvictConfig{blockId=446641970610176, replicas=1}
2022-08-12 07:54:27,723 INFO  PlanCoordinator - Starting job Id=1660216842853 Config=EvictConfig{blockId=437880103108608, replicas=1}
2022-08-12 07:54:27,893 INFO  PlanCoordinator - Starting job Id=1660216842854 Config=EvictConfig{blockId=429272854429696, replicas=1}
2022-08-12 07:54:27,981 INFO  PlanCoordinator - Starting job Id=1660216842855 Config=EvictConfig{blockId=517323173658624, replicas=1}
2022-08-12 07:54:28,011 INFO  PlanCoordinator - Starting job Id=1660216842856 Config=EvictConfig{blockId=323845902827520, replicas=1}
2022-08-12 07:54:28,020 INFO  PlanCoordinator - Starting job Id=1660216842857 Config=EvictConfig{blockId=517366123331584, replicas=1}
2022-08-12 07:54:28,029 INFO  PlanCoordinator - Starting job Id=1660216842858 Config=EvictConfig{blockId=455803270070272, replicas=1}
2022-08-12 07:54:28,199 INFO  PlanCoordinator - Starting job Id=1660216842859 Config=EvictConfig{blockId=350436448010240, replicas=1}
2022-08-12 07:54:28,210 INFO  PlanCoordinator - Starting job Id=1660216842860 Config=EvictConfig{blockId=456013723467776, replicas=1}
2022-08-12 07:54:28,343 INFO  PlanCoordinator - Starting job Id=1660216842861 Config=EvictConfig{blockId=359399105232896, replicas=1}
2022-08-12 07:54:28,382 INFO  PlanCoordinator - Starting job Id=1660216842862 Config=EvictConfig{blockId=447406474788864, replicas=1}
2022-08-12 07:54:28,794 INFO  PlanCoordinator - Starting job Id=1660216842863 Config=EvictConfig{blockId=428065968619520, replicas=1}
2022-08-12 07:54:29,147 INFO  PlanCoordinator - Starting job Id=1660216842864 Config=EvictConfig{blockId=534025496166400, replicas=1}
2022-08-12 07:54:29,223 INFO  PlanCoordinator - Starting job Id=1660216842865 Config=EvictConfig{blockId=402155102011392, replicas=1}
2022-08-12 07:54:29,237 INFO  PlanCoordinator - Starting job Id=1660216842866 Config=EvictConfig{blockId=542911917719552, replicas=1}

```

**To Reproduce**
set alluxio to cache remote boss directory with about 60million files, use pytorch dataloader(multi process) to read files for training, after some hours, job with failed with input/output error, or sometimes hanging there reading with no response.

**Expected behavior**
No input/output error happend

**Urgency**
we can't use alluxio to increase training speed for large datasets, and job always fail which cannot finish even one epoch.

**Comment by LuQQiu** [comment]
@flyhighzy when there is input/output error, which means the Fuse return code is `-Errorcodes.EIO` but the actual failure is usually shown in the corresponding fuse.log 
For more information, please take a look at https://docs.alluxio.io/os/user/stable/en/api/POSIX-API.html#inputoutput-error-and-fuse-logs
can you share the corresponding fuse.log?

**Comment by flyhighzy** [comment]
here is the fuse log for another input/output error case, they are all like those below:

```
2022-08-12 19:04:17,440 ERROR AbstractFuseFileSystem - Failed to statfs /:
java.lang.UnsupportedOperationException: statfs
        at alluxio.jnifuse.FuseFileSystem.statfs(FuseFileSystem.java:77)
        at alluxio.jnifuse.AbstractFuseFileSystem.statfsCallback(AbstractFuseFileSystem.java:289)
2022-08-12 19:04:23,472 ERROR AbstractFuseFileSystem - Failed to statfs /:
java.lang.UnsupportedOperationException: statfs
        at alluxio.jnifuse.FuseFileSystem.statfs(FuseFileSystem.java:77)
        at alluxio.jnifuse.AbstractFuseFileSystem.statfsCallback(AbstractFuseFileSystem.java:289)
2022-08-12 19:04:45,236 ERROR AbstractFuseFileSystem - Failed to statfs /:
java.lang.UnsupportedOperationException: statfs
        at alluxio.jnifuse.FuseFileSystem.statfs(FuseFileSystem.java:77)
        at alluxio.jnifuse.AbstractFuseFileSystem.statfsCallback(AbstractFuseFileSystem.java:289)
2022-08-12 19:05:02,597 ERROR AbstractFuseFileSystem - Failed to statfs /:
java.lang.UnsupportedOperationException: statfs
        at alluxio.jnifuse.FuseFileSystem.statfs(FuseFileSystem.java:77)
        at alluxio.jnifuse.AbstractFuseFileSystem.statfsCallback(AbstractFuseFileSystem.java:289)
2022-08-12 19:05:02,662 ERROR AbstractFuseFileSystem - Failed to statfs /:
java.lang.UnsupportedOperationException: statfs
        at alluxio.jnifuse.FuseFileSystem.statfs(FuseFileSystem.java:77)
        at alluxio.jnifuse.AbstractFuseFileSystem.statfsCallback(AbstractFuseFileSystem.java:289)
```

**Comment by flyhighzy** [comment]
another case occured, here is some log maybe helpful:

alluxio-master:
```
2022-08-14 03:50:11,601 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,603 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,623 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,644 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,665 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,685 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,706 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,726 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
2022-08-14 03:50:11,747 WARN  DefaultFileSystemMaster - File /video_pose/aic/tiktok_human_body/annotations/v0200f300000bs4r0nogmnq8ifdprt70_0000.json is not yet completed. getStatus will see incomplete metadata.
```

**Comment by flyhighzy** [comment]
here I get more detail fuse log now:

```
alluxio.exception.FileIncompleteException: Cannot read from /video_pose/aic/bili_dance/annotations/BV1QW411q7yB_output_0054.json because it is incomplete. Wait for the file to be marked as complete by the writing thread or application.
        at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:398)
        at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:386)
        at alluxio.client.file.FileSystem.openFile(FileSystem.java:503)
        at alluxio.fuse.AlluxioJniFuseFileSystem.openInternal(AlluxioJniFuseFileSystem.java:362)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$open$4(AlluxioJniFuseFileSystem.java:338)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:318)
        at alluxio.fuse.AlluxioJniFuseFileSystem.open(AlluxioJniFuseFileSystem.java:338)
        at alluxio.jnifuse.AbstractFuseFileSystem.openCallback(AbstractFuseFileSystem.java:171)
2022-08-15 04:31:50,140 WARN  AlluxioJniFuseFileSystem - Fuse.open(path=/video_pose/aic/bili_dance/annotations/BV1QW411q7yB_output_0054.json,flags=0x8000) returned -5 in 5006 ms (>=1000 ms)
```

Is this also related to [issue 16023](https://github.com/Alluxio/alluxio/issues/16023) ? Data inconsistent cause this problem?

**Comment by LuQQiu** [comment]
@flyhighzy can you try 2.8.1 and see if the same problem occurs?
In 2.8.1, we implements the statfs, refactor the Fuse read/write logics to take better care of the open in complete file related logics.
