### ISSUE TITLE
AlluxioFuse encountered a lot of "StatusRuntimeException: UNKNOWN for stream (Zero Copy GrpcDataReader)" warnings

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#16094]
**Alluxio Version:**
- 2.7.1

**Describe the bug**
When the size of direct memory is not enough, the AlluxioFuse process encountered a lot of the following warnings which reduced the performance a lot

```
2022-08-24 18:15:37,608 WARN  GrpcBlockingStream - Received error io.grpc.StatusRuntimeException: UNKNOWN for stream (Zero Copy GrpcDataReader)
2022-08-24 18:15:37,609 WARN  AlluxioFileInStream - Failed to read block 112099367845891 of file /projects/.../part-00324-8a41beba-4e77-4214-b47a-398ab94677d6-c000.tfrecord from worker WorkerNetAddress{host=worker12-xx, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=worker12-xx, rack=null)}. This worker will be skipped for future read operations, will retry: alluxio.exception.status.UnknownException: Unknown error (Zero Copy GrpcDataReader)
```

Log the stack of the warning "StatusRuntimeException: UNKNOWN for stream (Zero Copy GrpcDataReader)" and got

```
2022-08-22 20:03:48,541 WARN  GrpcBlockingStream - Received error io.grpc.StatusRuntimeException: UNKNOWN for stream (Zero Copy GrpcDataReader)
io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:172)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 132120855, max: 134217728)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:621)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:204)
        at io.netty.buffer.PoolArena.tcacheAllocateNormal(PoolArena.java:188)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:138)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:128)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:378)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
        at io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:532)
        at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:97)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:274)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 1 more
```

**To Reproduce**
1. Set a small value for `MaxDirectMemorySize`

```
export ALLUXIO_FUSE_JAVA_OPTS="-XX:MaxDirectMemorySize=128m"
```

2. mount

```
integration/fuse/bin/alluxio-fuse mount {local_path} {alluxio_path}
```

3. Put 30 100MB files to one alluxio path to read

4. Use 10 threads/processes to keep reading files from the path 

**Expected behavior**
1. Do not add the worker to blacklist if the exception is caused at client side
2. Provide a way to avoid OutOfDirectMemoryError when having limited direct memory

**Urgency**
Normal

**Are you planning to fix it**
Yes

**Comment by secfree** [comment]
The version we are using has backported the patch: https://github.com/Alluxio/alluxio/pull/14637

**Comment by secfree** [comment]
According to my investigation, there is no direct memory leak. The OutOfDirectMemoryError is caused by the direct memory chunk pool managed by netty.  It does "destroyChunk" immediately when "releaseChunk".
