### ISSUE TITLE
job master occur dead lock when job worker heartbeat timeout

### ISSUE THREAD

**Issue by wubiaoi** [Alluxio/alluxio#16121]
**Alluxio Version:**
2.7.3

**Describe the bug**

Found one Java-level deadlock:
=============================
"grpc-default-executor-37":
  waiting to lock monitor 0x00007fd2642078d8 (object 0x00007fda462f7ba8, a alluxio.master.job.plan.PlanCoordinator),
  which is held by "grpc-default-executor-4"
"grpc-default-executor-4":
  waiting to lock monitor 0x00007fd388006168 (object 0x00007fda475d2748, a alluxio.job.plan.meta.PlanInfo),
  which is held by "Job Master Lost Worker Detection"
"Job Master Lost Worker Detection":
  waiting to lock monitor 0x00007fd2642078d8 (object 0x00007fda462f7ba8, a alluxio.master.job.plan.PlanCoordinator),
  which is held by "grpc-default-executor-4"

`"grpc-default-executor-4":
        at alluxio.job.plan.meta.PlanInfo.setStatus(PlanInfo.java:192)
        - waiting to lock <0x00007fda475d2748> (a alluxio.job.plan.meta.PlanInfo)
        at alluxio.master.job.plan.PlanCoordinator.setJobAsFailed(PlanCoordinator.java:215)
        - locked <0x00007fda462f7ba8> (a alluxio.master.job.plan.PlanCoordinator)
        at alluxio.master.job.plan.PlanCoordinator.updateStatus(PlanCoordinator.java:280)
        - locked <0x00007fda462f7ba8> (a alluxio.master.job.plan.PlanCoordinator)
        at alluxio.master.job.plan.PlanCoordinator.updateTasks(PlanCoordinator.java:187)
        - locked <0x00007fda462f7ba8> (a alluxio.master.job.plan.PlanCoordinator)
        at alluxio.master.job.JobMaster.workerHeartbeat(JobMaster.java:552)
        at alluxio.master.job.JobMasterWorkerServiceHandler.lambda$heartbeat$0(JobMasterWorkerServiceHandler.java:67)
        at alluxio.master.job.JobMasterWorkerServiceHandler$$Lambda$800/6433229.call(Unknown Source)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:122)
        at alluxio.RpcUtils.call(RpcUtils.java:83)
        at alluxio.RpcUtils.call(RpcUtils.java:58)
        at alluxio.master.job.JobMasterWorkerServiceHandler.heartbeat(JobMasterWorkerServiceHandler.java:56)
        at alluxio.grpc.JobMasterWorkerServiceGrpc$MethodHandlers.invoke(JobMasterWorkerServiceGrpc.java:325)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"Job Master Lost Worker Detection":
        at alluxio.master.job.plan.PlanCoordinator.updateStatus(PlanCoordinator.java:270)
        - waiting to lock <0x00007fda462f7ba8> (a alluxio.master.job.plan.PlanCoordinator)
        at alluxio.master.job.plan.PlanCoordinator.failTasksForWorker(PlanCoordinator.java:252)
        - locked <0x00007fda475d2748> (a alluxio.job.plan.meta.PlanInfo)
        at alluxio.master.job.JobMaster$LostWorkerDetectionHeartbeatExecutor.heartbeat(JobMaster.java:624)
        at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:118)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by wushiming540** [comment]
hi， we meet the same issue, how do you solve the problem？

**Comment by wubiaoi** [comment]
> hi， we meet the same issue, how do you solve the problem？

I solved it with the following modifications, but I can't guarantee that there are no problems elsewhere.
[jobserver_deadlock.patch](https://github.com/Alluxio/alluxio/files/13172129/jobserver_deadlock.patch)
