### ISSUE TITLE
org.apache.ratis.thirdparty.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 10735321367, max: 10737418240)

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#16167]
**Alluxio Version:**
2.7.2

**Describe the bug**
After the master node is abnormal, and has not been transferred to other nodes, I have a total of 3 masters, which shows that it is a major bug, causing all services of Alluxio to be unavailable?

```
  2022-09-08 04:05:54,202 INFO  FollowerInfo - fs-alluxio-master03.xx_19200@group-ABB3109A44C1->fs-alluxio-master02.xx_19200: nextIndex: updateUnconditionally 43451958 -> 43451888
2022-09-08 04:05:54,212 ERROR LogAppenderDaemon - fs-alluxio-master03.xx_19200@group-ABB3109A44C1->fs-alluxio-master02.xx_19200-GrpcLogAppender-LogAppenderDaemon failed
org.apache.ratis.thirdparty.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 10735321367, max: 10737418240)
        at org.apache.ratis.thirdparty.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754)
        at org.apache.ratis.thirdparty.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709)
        at org.apache.ratis.thirdparty.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:755)
        at org.apache.ratis.thirdparty.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:731)
        at org.apache.ratis.thirdparty.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:247)
        at org.apache.ratis.thirdparty.io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
        at org.apache.ratis.thirdparty.io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
        at org.apache.ratis.thirdparty.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
        at org.apache.ratis.thirdparty.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at org.apache.ratis.thirdparty.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:123)
        at org.apache.ratis.thirdparty.io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:51)
        at org.apache.ratis.thirdparty.io.grpc.internal.MessageFramer.writeRaw(MessageFramer.java:287)
        at org.apache.ratis.thirdparty.io.grpc.internal.MessageFramer.access$400(MessageFramer.java:43)
        at org.apache.ratis.thirdparty.io.grpc.internal.MessageFramer$OutputStreamAdapter.write(MessageFramer.java:377)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:3005)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:3013)
        at org.apache.ratis.thirdparty.com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1392)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2801)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2775)
        at org.apache.ratis.proto.RaftProtos$StateMachineLogEntryProto.writeTo(RaftProtos.java:6910)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2855)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2824)
        at org.apache.ratis.proto.RaftProtos$LogEntryProto.writeTo(RaftProtos.java:8544)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2855)
        at org.apache.ratis.thirdparty.com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2824)
        at org.apache.ratis.proto.RaftProtos$AppendEntriesRequestProto.writeTo(RaftProtos.java:16769)
        at org.apache.ratis.thirdparty.com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:83)
        at org.apache.ratis.thirdparty.io.grpc.protobuf.lite.ProtoInputStream.drainTo(ProtoInputStream.java:52)
        at org.apache.ratis.thirdparty.io.grpc.internal.MessageFramer.writeToOutputStream(MessageFramer.java:269)
        at org.apache.ratis.thirdparty.io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:230)
        at org.apache.ratis.thirdparty.io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:168)
        at org.apache.ratis.thirdparty.io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:141)
        at org.apache.ratis.thirdparty.io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
        at org.apache.ratis.thirdparty.io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
        at org.apache.ratis.thirdparty.io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:579)
        at org.apache.ratis.thirdparty.io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:563)
        at org.apache.ratis.thirdparty.io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:364)
        at org.apache.ratis.grpc.server.GrpcLogAppender.sendRequest(GrpcLogAppender.java:234)
        at org.apache.ratis.grpc.server.GrpcLogAppender.appendLog(GrpcLogAppender.java:225)
        at org.apache.ratis.grpc.server.GrpcLogAppender.run(GrpcLogAppender.java:145)
        at org.apache.ratis.server.leader.LogAppenderDaemon.run(LogAppenderDaemon.java:77)
        at java.lang.Thread.run(Thread.java:748)
		



2022-09-08 11:08:39,867 ERROR ConfigHashSync - Failed to heartbeat to meta master to get configuration hash:
alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.hiido.host.yydev
ops.com:19998". Service="MetaMaster"
        at alluxio.AbstractClient.connect(AbstractClient.java:279)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:404)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.client.meta.RetryHandlingMetaMasterConfigClient.getConfigHash(RetryHandlingMetaMasterConfigClient.java:89)
        at alluxio.client.file.ConfigHashSync.heartbeat(ConfigHashSync.java:81)
        at alluxio.client.file.FileSystemContextReinitializer.lambda$new$0(FileSystemContextReinitializer.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-09-08 11:08:49,888 WARN  RetryHandlingMetaMasterMasterClient - Heartbeat(masterId=5723233685622813509) exits with exception [alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.xx:19998". Service="MetaMasterMaster"] in 120002 ms (>=10000ms)
2022-09-08 11:08:49,888 ERROR MetaMasterSync - Failed to receive leader master heartbeat command.
alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.xx:19998". Service="MetaMasterMaster"
        at alluxio.AbstractClient.connect(AbstractClient.java:279)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:404)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.master.meta.RetryHandlingMetaMasterMasterClient.heartbeat(RetryHandlingMetaMasterMasterClient.java:93)
        at alluxio.master.meta.MetaMasterSync.heartbeat(MetaMasterSync.java:72)
        at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:118)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
		
		
		
		job
		
		
		
		2022-09-08 04:08:44,072 ERROR file.ConfigHashSync (ConfigHashSync.java:heartbeat) - Failed to heartbeat to meta master to get configuration hash:
alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.xx:19998". Service="MetaMaster"
        at alluxio.AbstractClient.connect(AbstractClient.java:279)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:404)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.client.meta.RetryHandlingMetaMasterConfigClient.getConfigHash(RetryHandlingMetaMasterConfigClient.java:89)
        at alluxio.client.file.ConfigHashSync.heartbeat(ConfigHashSync.java:81)
        at alluxio.client.file.FileSystemContextReinitializer.lambda$new$0(FileSystemContextReinitializer.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-09-08 04:10:44,100 WARN  meta.MetaMasterConfigClient (AbstractClient.java:retryRPC) - GetConfigHash() exits with exception [alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.xx:19998". Service="MetaMaster"] in 120028 ms (>=10000ms)
2022-09-08 04:10:44,101 ERROR file.ConfigHashSync (ConfigHashSync.java:heartbeat) - Failed to heartbeat to meta master to get configuration hash:
alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.xx:19998". Service="MetaMaster"
        at alluxio.AbstractClient.connect(AbstractClient.java:279)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:404)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.client.meta.RetryHandlingMetaMasterConfigClient.getConfigHash(RetryHandlingMetaMasterConfigClient.java:89)
        at alluxio.client.file.ConfigHashSync.heartbeat(ConfigHashSync.java:81)
        at alluxio.client.file.FileSystemContextReinitializer.lambda$new$0(FileSystemContextReinitializer.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-09-08 04:12:44,144 WARN  meta.MetaMasterConfigClient (AbstractClient.java:retryRPC) - GetConfigHash() exits with exception [alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.xx:19998". Service="MetaMaster"] in 120043 ms (>=10000ms)
2022-09-08 04:12:44,144 ERROR file.ConfigHashSync (ConfigHashSync.java:heartbeat) - Failed to heartbeat to meta master to get configuration hash:
alluxio.exception.status.UnavailableException: Failed to connect to master (fs-alluxio-master03.xx:19998) after 1 attempts.Please check if Alluxio master is currently running on "fs-alluxio-master03.xx:19998". Service="MetaMaster"
        at alluxio.AbstractClient.connect(AbstractClient.java:279)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:404)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
        at alluxio.client.meta.RetryHandlingMetaMasterConfigClient.getConfigHash(RetryHandlingMetaMasterConfigClient.java:89)
        at alluxio.client.file.ConfigHashSync.heartbeat(ConfigHashSync.java:81)
        at alluxio.client.file.FileSystemContextReinitializer.lambda$new$0(FileSystemContextReinitializer.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
```

**Comment by jenoudet** [comment]
When a master suffers from an out-of-memory error, it is sometimes best to restart the affected master. It will naturally rejoin the cluster and help perform normal operations.
Have you tried restarting the affected master?

**Comment by HelloHorizon** [comment]
Thank you for report @liangrui1988! I will like to get more information before we dive deeper. Do you mind sharing the deployment of the cluster, which is the primary master and which is the follower master?

And what are the xmx and director memory configurations from your side, with your node configurations(total memory)?

And to understand the urgency of the issue, I would also want to know if this issue will stop the leadership transfer or not.

**Comment by liangrui1988** [comment]
> Thank you for report @liangrui1988! I will like to get more information before we dive deeper. Do you mind sharing the deployment of the cluster, which is the primary master and which is the follower master?
> 
> And what are the xmx and director memory configurations from your side, with your node configurations(total memory)?
> 
> And to understand the urgency of the issue, I would also want to know if this issue will stop the leadership transfer or not.



It was something like this,
master01
cat /etc/alluxio/conf$ cat /data10/journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/raft-meta
```
#
#Wed Sep 14 14:16:28 CST 2022
votedFor=fs-alluxio-master03.hiido.host.yydevops.com_19200
term=14
```


master02
cat /etc/alluxio/conf$ cat /data10/journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/raft-meta
```
#
#Wed Sep 14 14:16:28 CST 2022
votedFor=fs-alluxio-master01.hiido.host.yydevops.com_19200
term=15
```

master03  ==>leader

cat /etc/alluxio/conf$ cat /data10/journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/raft-meta

```
#
#Wed Sep 14 14:16:28 CST 2022
votedFor=fs-alluxio-master03.hiido.host.yydevops.com_19200
term=14
```


I have done manual primary/secondary switchover and restart operations during this period, but I do not know the cause of this.It was not until I deleted all the Master services and compared the configuration that I found the reason.
So why doesn't this configuration file force synchronization?

**Comment by jenoudet** [comment]
I'm not sure I understand how the information you have provided about the leader election relates to the OutOfMemory error described above. The `raft-meta` file is not a configuration file. It is an internal state-keeping file generated by Ratis. During an election, it is reasonable to assume that some masters may vote for different candidates: in your case, 2 / 3 voted for master3, so it was elected as leader.
As @HelloHorizon has asked, could you provide the `-Xmx` and `-XX:MaxDirectMemorySize` configurations from your side, as well as the total memory available on the machine on which you are running Alluxio?
And does the OOM error prevent future leaders from being elected? The example you gave seems to suggest that the failover did happen and that a new leader was elected.

**Comment by liangrui1988** [comment]
> 

ALLUXIO_JAVA_OPTS+="-XX:MaxDirectMemorySize=10g"

master02
cat /etc/alluxio/conf$ cat /data10/journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current/raft-meta

#
#Wed Sep 14 14:16:28 CST 2022
votedFor=fs-alluxio-master01.hiido.host.yydevops.com_19200
term=15

This is an incorrect configuration, and there is an obvious log thrown, and the metadata cannot be synchronized. It is clear that this problem causes the accumulation of metadata, which cannot be synchronized, resulting in memory overflow.The specific cause of this did not continue to check

Normally the configuration of the three masters should be the same,
