### ISSUE TITLE
"FuseException: Unable to mount FS, return code = 3" when using libfuse3

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#16344]
**Alluxio Version:**
2.7.1 + Most alluxio-fuse related PRs after 2.7.1

**Describe the bug**
I encountered the following exception after setting `alluxio.fuse.jnifuse.libfuse.version=3`.

```
2022-10-18 15:33:31,264 main INFO  AlluxioFuse - Mounting AlluxioJniFuseFileSystem: mount point="/mnt/s3_zhaoqun", OPTIONS="[-obig_writes, -oallow_other, -odefault_permissions]"
2022-10-18 15:33:31,265 main INFO  AbstractFuseFileSystem - Mounting /mnt/s3_zhaoqun: blocking=true, debug=false, fuseOpts="[-obig_writes, -oallow_other, -odefault_permissions]"
2022-10-18 15:33:31,266 main ERROR AlluxioFuse - Failed to mount alluxio path /s3/zhaoqun to mount point /mnt/s3_zhaoqun
alluxio.jnifuse.FuseException: Unable to mount FS
        at alluxio.jnifuse.AbstractFuseFileSystem.mount(AbstractFuseFileSystem.java:112)
        at alluxio.fuse.AlluxioFuse.launchFuse(AlluxioFuse.java:137)
        at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:89)
Caused by: alluxio.jnifuse.FuseException: Unable to mount FS, return code = 3
        at alluxio.jnifuse.AbstractFuseFileSystem.mount(AbstractFuseFileSystem.java:108)
        ... 2 more
2022-10-18 15:33:31,378 main ERROR AlluxioFuse - Failed to launch FUSE
java.io.IOException: Failed to mount Alluxio file system
        at alluxio.fuse.AlluxioFuse.launchFuse(AlluxioFuse.java:174)
        at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:89)
Caused by: java.io.IOException: Failed to mount alluxio path /s3/zhaoqun to mount point /mnt/s3_zhaoqun
        at alluxio.fuse.AlluxioFuse.launchFuse(AlluxioFuse.java:151)
        ... 1 more
Caused by: alluxio.jnifuse.FuseException: Unable to mount FS
        at alluxio.jnifuse.AbstractFuseFileSystem.mount(AbstractFuseFileSystem.java:112)
        at alluxio.fuse.AlluxioFuse.launchFuse(AlluxioFuse.java:137)
        ... 1 more
Caused by: alluxio.jnifuse.FuseException: Unable to mount FS, return code = 3
        at alluxio.jnifuse.AbstractFuseFileSystem.mount(AbstractFuseFileSystem.java:108)
        ... 2 more
```

In fuse.log, there is

```
ERROR ../../src/main/native/libjnifuse/jnifuse_helper.cc:34 Validate standard errors can be logged as expected
fuse: unknown option(s): `-o big_writes'
INFO ../../src/main/native/libjnifuse/jnifuse_onload.cc:25 Loaded libjnifuse
INFO ../../src/main/native/libjnifuse/jnifuse_helper.cc:33 Start initializing JNIFuse
INFO ../../src/main/native/libjnifuse/jnifuse_helper.cc:88 JNIFuse initialized
```

**To Reproduce**
Set `alluxio.fuse.jnifuse.libfuse.version=3` and do alluxio-fuse mount.

**Expected behavior**
The mount operation should succeed.

**Urgency**
Not urgent

**Are you planning to fix it**
Yes

**Additional context**
No

**Comment by secfree** [comment]
Just found @LuQQiu fixed this issue 17 hours ago in #16307, I will just close this.
