### ISSUE TITLE
Client deadlock

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#16399]
**Alluxio Version:**
master branch

**Describe the bug**

Client DeadLock

```
"config-hash-master-heartbeat-0" #46 daemon prio=5 os_prio=0 cpu=55.36ms elapsed=65198.70s tid=0x00007f4b505ef000 nid=0x184 waiting for monitor entry [0x00007f4b0ea7b000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at alluxio.client.file.FileSystemContext.closeContext(FileSystemContext.java:315)
	- waiting to lock <0x000000022523e438> (a alluxio.client.file.FileSystemContext)
	at alluxio.client.file.FileSystemContext.reinit(FileSystemContext.java:413)
	at alluxio.client.file.ConfigHashSync.heartbeat(ConfigHashSync.java:94)
	- locked <0x000000022c0c1ba8> (a alluxio.client.file.ConfigHashSync)
	at alluxio.client.file.FileSystemContextReinitializer.lambda$new$0(FileSystemContextReinitializer.java:69)
	at alluxio.client.file.FileSystemContextReinitializer$$Lambda$102/1487715041.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
。。。


"PLCExecute_Thread-41" #706 prio=5 os_prio=0 cpu=1662.74ms elapsed=65142.74s tid=0x00007f4b51028800 nid=0x41f waiting on condition [0x00007f4aec365000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000022c998f38> (a alluxio.concurrent.CountingLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at alluxio.concurrent.CountingLatch.inc(CountingLatch.java:108)
	at alluxio.client.file.FileSystemContextReinitializer$ReinitBlockerResource.<init>(FileSystemContextReinitializer.java:104)
	at alluxio.client.file.FileSystemContextReinitializer.block(FileSystemContextReinitializer.java:155)
	at alluxio.client.file.FileSystemContext.blockReinit(FileSystemContext.java:370)
	at alluxio.client.file.FileSystemContext.acquireBlockMasterClientResource(FileSystemContext.java:497)
	at alluxio.client.file.FileSystemContext.getAllWorkers(FileSystemContext.java:677)
	at alluxio.client.file.FileSystemContext.getCachedWorkers(FileSystemContext.java:656)
	- locked <0x000000022523e438> (a alluxio.client.file.FileSystemContext)
	at alluxio.client.file.BaseFileSystem.getHostWorkerMap(BaseFileSystem.java:252)
	at alluxio.client.file.BaseFileSystem.getBlockLocations(BaseFileSystem.java:242)
	at alluxio.hadoop.AbstractFileSystem.getFileBlockLocations(AbstractFileSystem.java:299)
	at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:2146)
	at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:2128)
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:280)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**

Urgency

**Are you planning to fix it**

Not sure

**Additional context**

"config-hash-master-heartbeat-0" called mReinitializer.allow(), called mLatch.await() indirect, locked LockA，
then, it call FileSystemContext.closeContext, need acquire FileSystemContext object monitor, LockB.

"PLCExecute_Thread-41"  locked FileSystemContext object monitor LockB, then call FileSystemContext.getCachedWorkers, it call  CountingLatch.inc indirectly, need acquire LockA

LockA LockB are dead locked.

**Comment by maobaolong** [comment]
This seems have been resolved by recent PR.
