### ISSUE TITLE
Repeated get ACL from UFS

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#16473]
**Summary**

In InodeSyncStream, when an inode does not exist, it will first be loaded from UFS then sync-ed.
https://github.com/Alluxio/alluxio/blob/140497bfdd0632d863fd14a4027863667c685105/core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java#L726
```
  private void syncInodeMetadata(LockedInodePath inodePath, RpcContext rpcContext)
      throws InvalidPathException, AccessControlException, IOException, FileDoesNotExistException,
      FileAlreadyCompletedException, InvalidFileSizeException, BlockInfoException,
      InterruptedException {
    if (!inodePath.fullPathExists()) {
      loadMetadataForPath(inodePath, rpcContext);
      // skip the load metadata step in the sync if it has been just loaded
      syncExistingInodeMetadata(inodePath, rpcContext, true);
    } else {
      syncExistingInodeMetadata(inodePath, rpcContext, false);
    }
  }
```

First the loadFileMetadataInternal() will ask for ACL
```
at alluxio.master.file.InodeSyncStream.loadFileMetadataInternal(InodeSyncStream.java:1187)
at alluxio.master.file.InodeSyncStream.loadMetadata(InodeSyncStream.java:1020)
at alluxio.master.file.InodeSyncStream.loadMetadata(InodeSyncStream.java:1056)
at alluxio.master.file.InodeSyncStream.loadMetadataForPath(InodeSyncStream.java:991)
at alluxio.master.file.InodeSyncStream.syncInodeMetadata(InodeSyncStream.java:726)
at alluxio.master.file.InodeSyncStream.syncInternal(InodeSyncStream.java:474)
at alluxio.master.file.InodeSyncStream.sync(InodeSyncStream.java:404)
```
https://github.com/Alluxio/alluxio/blob/140497bfdd0632d863fd14a4027863667c685105/core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java#L1177

Then immediately a syncExistingInodeMetadata() will ask for the ACL again.
```
at alluxio.master.file.InodeSyncStream.syncExistingInodeMetadata(InodeSyncStream.java:831)
at alluxio.master.file.InodeSyncStream.syncInodeMetadata(InodeSyncStream.java:728)
at alluxio.master.file.InodeSyncStream.syncInternal(InodeSyncStream.java:474)
at alluxio.master.file.InodeSyncStream.sync(InodeSyncStream.java:404)
```
https://github.com/Alluxio/alluxio/blob/140497bfdd0632d863fd14a4027863667c685105/core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java#L827

**Urgency**
Explain why it is important to address the tech debt

**Comment by jiacheliu3** [comment]
@tcrain Could you take a look at this? Also @kuszz is this on the same thread for your PR https://github.com/Alluxio/alluxio/pull/16445#pullrequestreview-1169924283 ?
