### ISSUE TITLE
alluxio-fuse created a file but did not trigger completeFile

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#16598]
**Alluxio Version:**
2.7.1 (We have backported most alluxio-fuse related PRs after this version)

**Describe the bug**

Read the file failed from an alluxio-fuse mount path

```
$ head test.ipynb
head: cannot open test.ipynb’ for reading: Input/output error
```

fuse.log has the following content

```
2022-11-29 15:13:02,526 WARN  BaseFileSystem - File /.../test.ipynb is not yet completed. getStatus will see incomplete metadata.
2022-11-29 15:13:02,550 WARN  BaseFileSystem - File /.../test.ipynb is not yet completed. getStatus will see incomplete metadata.
...
2022-11-29 15:13:04,061 ERROR AlluxioFuseUtils - Failed to Fuse.Open(path=/.../test.ipynb,flags=0x8000) with unexpected throwable:
java.lang.UnsupportedOperationException: Failed to create fuse file stream for /.../test.ipynb: file is being written
        at alluxio.fuse.file.FuseFileStream$Factory.create(FuseFileStream.java:114)
        at alluxio.fuse.AlluxioJniFuseFileSystem.createOrOpenInternal(AlluxioJniFuseFileSystem.java:212)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$open$1(AlluxioJniFuseFileSystem.java:202)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:507)
        at alluxio.fuse.AlluxioJniFuseFileSystem.open(AlluxioJniFuseFileSystem.java:201)
        at alluxio.jnifuse.AbstractFuseFileSystem.openCallback(AbstractFuseFileSystem.java:188)
```

"lsof |grep test.ipynb" shows that there is no program opening this file.

master_audit.log has "createFile" and "getNewBlockIdForFile", but it does not have "completeFile"

```
2022-11-29 11:31:16,094 succeeded=true cmd=createFile src=/.../test.ipynb dst=null
2022-11-29 11:31:16,122 succeeded=true cmd=getNewBlockIdForFile src=/.../test.ipynb dst=null
```

**To Reproduce**
Not clear yet

**Expected behavior**
Read operation should succeed.

**Urgency**
Normal(as we just encountered this once by now)

**Are you planning to fix it**
Yes

**Comment by yyongycy** [comment]
@LuQQiu  any idea about this failure?

**Comment by yyongycy** [comment]
had you searched the whole log to see if there are other exception or error?

**Comment by secfree** [comment]
> had you searched the whole log to see if there are other exception or error?

Yes, I checked all WARN/ERROR lines but no other finding.

**Comment by LuQQiu** [comment]
@secfree is it possible to share me your branch and the commits you backported? trying to understand what's the FUSE implementation

**Comment by LuQQiu** [comment]
Have some hyphothesis of what's happening:
1. Write thread loss before calling the release. So that the FUSE write stream has not been closed.
- can check through metrics `Fuse.ReadWriteFileCount`
- memory profiling
2. Some operations will expect the file can be read write concurrently and issue read operation before write finishing
but still better to look at the exact code and see what's the hypothesis and which has higher possibilities

**Comment by secfree** [comment]
@LuQQiu thank you for help and suggestions. 
As the company policy, I cannot share the code of my branch. 
For the issue, it only happened once by now. We have made some tests but cannot reproduce the issue. So we choose to leave it and will check more if encounter it again.

**Comment by shaoxuefeng** [comment]
I meet the same error in Alluxio Version 2.8.1.
I deploy Alluxio in Kubernetes, and create a PVC using Alluxio Fuse.  It's fine to write or read a finle with Alluxio PVC. However,  It will falied when I  execute 'git clone'  opertation with 'Input/output error'.
I had looked the Alluxio Fuse log, It have the same error log.

**Comment by LuQQiu** [comment]
@LuQQiu assigned myself to check the git clone operation of 2.8.1

**Comment by LuQQiu** [comment]
```
2023-01-05 02:07:24,652 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Create(path=/test/libfuse/.git/objects/pack/tmp_pack_AHbwvQ,mode=100444,flags=0x80c2)
2023-01-05 02:07:24,678 DEBUG AlluxioJniFuseFileSystem - Exit (0): Fuse.Create(path=/test/libfuse/.git/objects/pack/tmp_pack_AHbwvQ,mode=100444,flags=0x80c2) in 26 ms

write to fd=56

2023-01-05 02:07:33,395 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Open(path=/test/libfuse/.git/objects/pack/tmp_pack_AHbwvQ,flags=0x8000)
2023-01-05 02:07:53,396 ERROR AlluxioJniFuseFileSystem - Failed to create stream /test/libfuse/.git/objects/pack/tmp_pack_AHbwvQ: deadline exceed
alluxio.exception.runtime.DeadlineExceededRuntimeException: Failed to acquire lock for path s3://alluxio-test-fuse/alluxio/test/libfuse/.git/objects/pack/tmp_pack_AHbwvQ after 20000 ms (LockMode: READ, lock reference count = 0)
        at alluxio.fuse.lock.FuseReadWriteLockManager.tryLock(FuseReadWriteLockManager.java:65)
        at alluxio.fuse.file.FuseFileInStream.create(FuseFileInStream.java:63)
        at alluxio.fuse.file.FuseFileStream$Factory.create(FuseFileStream.java:106)
        at alluxio.fuse.AlluxioJniFuseFileSystem.createOrOpenInternal(AlluxioJniFuseFileSystem.java:179)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$open$1(AlluxioJniFuseFileSystem.java:168)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:642)
        at alluxio.fuse.AlluxioJniFuseFileSystem.open(AlluxioJniFuseFileSystem.java:167)
        at alluxio.jnifuse.AbstractFuseFileSystem.openCallback(AbstractFuseFileSystem.java:185)
2023-01-05 02:07:53,399 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Release(path=/test/libfuse/.git/objects/pack/tmp_pack_AHbwvQ,fd=56)
```

**Comment by LuQQiu** [comment]
Turn the issue into a feature request https://github.com/Alluxio/alluxio/issues/16714

**Comment by LuQQiu** [comment]
Turn the issue into a feature request https://github.com/Alluxio/alluxio/issues/16714
