### ISSUE TITLE
why I deploy the alluxio using helm to kubernetes meet this:

### ISSUE THREAD

**Issue by andyzheung** [Alluxio/alluxio#16646]
I use the offical helm:

but master and worker also have error:
kubectl logs -n alluxio alluxio-master-0 alluxio-job-master

alluxio.exception.status.UnavailableException: Failed to handshake with master 192.168.59.220:19998 to load cluster default configuration values: UNAVAILABLE: io exception
        at alluxio.conf.Configuration.loadConfiguration(Configuration.java:448)
        at alluxio.ClientContext.loadConf(ClientContext.java:120)
        at alluxio.client.metrics.ClientMasterSync.loadConf(ClientMasterSync.java:122)
        at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)

kubectl logs -n alluxio alluxio-worker-vph2h alluxio-job-worker

2022-12-15 08:13:18,974 WARN  RetryUtils - Failed to load cluster default configuration with master (attempt 8): alluxio.exception.status.UnavailableException: Failed to handshake with master alluxio-master-0:19998 to load cluster default configuration values: UNAVAILABLE: Unable to resolve host alluxio-master-0
Dec 15, 2022 8:13:24 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<17>: (alluxio-master-0:19998)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host alluxio-master-0, cause=java.lang.RuntimeException: java.net.UnknownHostException: alluxio-master-0
        at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
        at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: alluxio-master-0
        at java.net.InetAddress.getAllByName0(InetAddress.java:1282)
        at java.net.InetAddress.getAllByName(InetAddress.java:1194)
        at java.net.InetAddress.getAllByName(InetAddress.java:1128)
        at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
        at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
        ... 5 more
}

**Comment by ssz1997** [comment]
@andyzheung Thanks for reporting. I think job master and worker have two different problems.

For job master, I think this is because the master service is not ready yet at the container creation time but it should be fine later. To confirm, can you check the output of `kubectl get pods` and if master pod's READY is `2/2`? `2/2` means job master started without problem (even with some initial error logs).

For worker, I would suggest following this doc: https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/ to see whether some setup of your k8s doesn't work.

**Comment by andyzheung** [comment]
> @andyzheung Thanks for reporting. I think job master and worker have two different problems.
> 
> For job master, I think this is because the master service is not ready yet at the container creation time but it should be fine later. To confirm, can you check the output of `kubectl get pods` and if master pod's READY is `2/2`? `2/2` means job master started without problem (even with some initial error logs).
===>the first question is master is ready for 2/2

> For worker, I would suggest following this doc: https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/ to see whether some setup of your k8s doesn't work.
==>I deploy a demo nginx, and exec nginx can nslookup the master by the command:
nslookup alluxio-master-0

**Comment by ssz1997** [comment]
@andyzheung 
Does worker also show `2/2`?

**Comment by andyzheung** [comment]
> @andyzheung Does worker also show `2/2`?
No, worker can't run... because the error I mentioned above.

**Comment by ssz1997** [comment]
@andyzheung If job master is able to find master without problem, workers should be able to find master too. It is normal for workers to report this error and restart while waiting for master to be ready. There might be something else wrong with worker. Can you send the full worker log?
