### ISSUE TITLE
Support ipv6 on Alluxio HA

### ISSUE THREAD

**Issue by kuszz** [Alluxio/alluxio#16707]
**Is your feature request related to a problem? Please describe.**
Now we get a exception in formatJournal when use ipv6 in alluxio.master.embedded.journal.addresses.
2023-01-03 19:25:01,272 ERROR Format - Failed to format
java.lang.IllegalArgumentException: Failed to parse host:port: 2402:...:b831:19200
        at alluxio.util.ConfigurationUtils.parseInetSocketAddresses(ConfigurationUtils.java:160)
        at alluxio.util.ConfigurationUtils.getMasterEmbeddedJournalAddresses(ConfigurationUtils.java:76)
        at alluxio.util.ConfigurationUtils.getEmbeddedJournalAddresses(ConfigurationUtils.java:63)
        at alluxio.master.journal.raft.RaftJournalSystem.<init>(RaftJournalSystem.java:253)
        at alluxio.master.journal.JournalSystem$Builder.build(JournalSystem.java:294)
        at alluxio.cli.Format.format(Format.java:117)
        at alluxio.cli.Format.main(Format.java:95)
Caused by: java.io.IOException: Invalid InetSocketAddress 2402:...:b831:19200
        at alluxio.util.network.NetworkAddressUtils.parseInetSocketAddress(NetworkAddressUtils.java:666)
        at alluxio.util.ConfigurationUtils.parseInetSocketAddresses(ConfigurationUtils.java:158)
        ... 6 more 

**Describe the solution you'd like**
support ipv6 on Alluxio HA

**Comment by LuQQiu** [comment]
@kuszz are you planning to resolve the issue?

**Comment by kuszz** [comment]
> @kuszz are you planning to resolve the issue?

Sorry, I don't know whether there are other codes don't support ipv6

**Comment by jiacheliu3** [comment]
@HelloHorizon Do you think supporting ipv6 is a valid feature request?

**Comment by jiacheliu3** [comment]
@kuszz Could you please explain more on:
1. What is the scale of this cluster? How many Alluxio nodes are there? Is it on K8s?
2. Is Alluxio running on embedded journal or UFS journal?
3. What are the UFS?
If we are to add support on ipv6, we will need to test internally. And if you can help with providing some basic info on the cluster, we can test on that setup and make sure things run correctly in that one.

**Comment by kuszz** [comment]
> @kuszz Could you please explain more on:
> 
> 1. What is the scale of this cluster? How many Alluxio nodes are there? Is it on K8s?
> 2. Is Alluxio running on embedded journal or UFS journal?
> 3. What are the UFS?
>    If we are to add support on ipv6, we will need to test internally. And if you can help with providing some basic info on the cluster, we can test on that setup and make sure things run correctly in that one.

1. No, it‘s not on k8s.
2. embedded journal
3. cos，hdfs，csp
