### ISSUE TITLE
When raft HA is enabled, the primary master cannot be elected at startup

### ISSUE THREAD

**Issue by xuanlang** [Alluxio/alluxio#16725]
**Alluxio Version:**
2.8.2, 2.9.0

**Describe the bug**
This problem occurs in both bare metal and virtual machine clusters, and the probability of successful startup is low.

master.log:
```
2023-01-05 20:22:37,881 INFO  RaftServer - cache02v.*.*.*.net_19200: start RPC server
2023-01-05 20:22:37,934 INFO  GrpcService - cache02v.*.*.*.net_19200: GrpcService started, listening on 19200
2023-01-05 20:22:37,937 INFO  RaftJournalSystem - Started Raft Journal System in 243ms
2023-01-05 20:22:37,937 INFO  JvmPauseMonitor - JvmPauseMonitor-cache02v.*.*.*.net_19200: Started
2023-01-05 20:22:38,178 INFO  AlluxioMasterProcess - Starting all masters as: follower.
2023-01-05 20:22:38,188 INFO  MetricsSystem - Reset all metrics in the metrics system in 3ms
2023-01-05 20:22:38,188 INFO  MetricsStore - Cleared the metrics store and metrics system in 3 ms
2023-01-05 20:22:38,201 INFO  DefaultMetaMaster - Standby master with address cache02v.*.*.*.net:19998 starts sending heartbeat to leader master.
2023-01-05 20:22:38,247 INFO  BackupTracker - Resetting backup tracker.
2023-01-05 20:22:38,255 INFO  BackupWorkerRole - Creating backup-worker role.
2023-01-05 20:22:38,256 INFO  AlluxioMasterProcess - All masters started.
2023-01-05 20:22:38,274 INFO  AlluxioMasterProcess - Waiting for journals to catch up.
2023-01-05 20:22:38,274 INFO  AlluxioMasterProcess - Starting leader selector.
2023-01-05 20:22:38,275 INFO  AlluxioMasterProcess - Waiting for journals to catch up.
2023-01-05 20:22:38,275 INFO  AlluxioMasterProcess - Started in stand-by mode.
2023-01-05 20:22:38,358 INFO  NettyUtils - EPOLL_MODE is available
2023-01-05 20:22:53,484 INFO  FollowerState - cache02v.*.*.*.net_19200@group-ABB3109A44C1-FollowerState: change to CANDIDATE, lastRpcElapsedTime:15647085211ns, electionTimeout:15645ms
2023-01-05 20:22:53,484 INFO  RoleInfo - cache02v.*.*.*.net_19200: shutdown cache02v.*.*.*.net_19200@group-ABB3109A44C1-FollowerState
2023-01-05 20:22:53,484 INFO  RaftServer$Division - cache02v.*.*.*.net_19200@group-ABB3109A44C1: changes role from  FOLLOWER to CANDIDATE at term 0 for changeToCandidate
2023-01-05 20:22:53,488 INFO  RaftServerConfigKeys - raft.server.leaderelection.pre-vote = true (default)
2023-01-05 20:22:53,488 INFO  RoleInfo - cache02v.*.*.*.net_19200: start cache02v.*.*.*.net_19200@group-ABB3109A44C1-LeaderElection1
2023-01-05 20:22:53,490 INFO  LeaderElection - cache02v.*.*.*.net_19200@group-ABB3109A44C1-LeaderElection1 PRE_VOTE round 0: submit vote requests at term 0 for -1: [cache04v.*.*.*.net_19200|rpc:cache04v.*.*.*.net:19200|priority:0, cache02v.*.*.*.net_19200|rpc:cache02v.*.*.*.net:19200|priority:0, cache01v.*.*.*.net_19200|rpc:cache01v.*.*.*.net:19200|priority:0], old=null
2023-01-05 20:22:53,510 ERROR LeaderElection - cache02v.*.*.*.net_19200@group-ABB3109A44C1-LeaderElection1: Failed, state=RUNNING
java.lang.IllegalStateException
        at org.apache.ratis.util.Preconditions.assertTrue(Preconditions.java:33)
        at org.apache.ratis.server.impl.RaftConfigurationImpl.hasMajority(RaftConfigurationImpl.java:229)
        at org.apache.ratis.server.impl.LeaderElection.waitForResults(LeaderElection.java:420)
        at org.apache.ratis.server.impl.LeaderElection.submitRequestAndWaitResult(LeaderElection.java:287)
        at org.apache.ratis.server.impl.LeaderElection.askForVotes(LeaderElection.java:311)
        at org.apache.ratis.server.impl.LeaderElection.run(LeaderElection.java:237)
        at java.lang.Thread.run(Thread.java:748)
2023-01-05 20:22:54,222 INFO  NettyUtils - EPOLL_MODE is available
```

 **launcher log:**
```
Waiting for tasks to finish...
All tasks finished
Starting to monitor all remote services.
--- [ OK ] The master service @ cache02v.*.*.*.net is in a healthy state.
--- [ OK ] The master service @ cache01v.*.*.*.net is in a healthy state.
--- [ OK ] The master service @ cache04v.*.*.*.net is in a healthy state.
--- [ OK ] The job_master service @ cache01v.*.*.*.net is in a healthy state.
--- [ OK ] The job_master service @ cache04v.*.*.*.net is in a healthy state.
--- [ OK ] The job_master service @ cache02v.*.*.*.net is in a healthy state.
--- [ FAILED ] The worker @ cache04v.*.*.*.net is not serving requests.
--- Printing the log tail for /home/software/alluxio-2.9.0/logs/worker.log.
>>> BEGIN
2023-01-06 10:47:10,318 INFO  NettyUtils - EPOLL_MODE is available
2023-01-06 10:47:57,347 INFO  NettyUtils - EPOLL_MODE is available
<<< EOF
--- Printing the log tail for /home/software/alluxio-2.9.0/logs/worker.out
    --- EMPTY ---
--- [ FAILED ] The job_worker @ cache04v.*.*.*.net is not serving requests.
--- Printing the log tail for /home/work/software/alluxio-2.9.0/logs/job_worker.log
>>> BEGIN
2023-01-06 10:47:13,928 INFO  network.NettyUtils (NettyUtils.java:checkNettyEpollAvailable) - EPOLL_MODE is available
2023-01-06 10:48:58,796 INFO  network.NettyUtils (NettyUtils.java:checkNettyEpollAvailable) - EPOLL_MODE is available
2023-01-06 10:49:13,802 WARN  retry.RetryUtils (RetryUtils.java:retry) - Failed to load cluster default configuration with master (attempt 1): alluxio.exception.status.UnavailableException: Failed to determine primary master rpc address after polling each of [cache02v.*.*.*.net:19998, cache01v.*.*.*.net:19998, cache04v.*.*.*.net:19998] 44 times
<<< EOF
--- Printing the log tail for /home/software/alluxio-2.9.0/logs/job_worker.out
    --- EMPTY ---
--- [ OK ] The proxy service @ cache01v.*.*.*.net is in a healthy state.
--- [ OK ] The proxy service @ cache04v.*.*.*.net is in a healthy state.
--- [ OK ] The proxy service @ cache02v.*.*.*.net is in a healthy state.
```
```
[test@cache02v alluxio-2.9.0]$ ./bin/alluxio fs masterInfo
Failed to find leader master
All masters: [cache02v.*.*.*.net:19998, cache01v.*.*.*.net:19998, cache04v.*.*.*.net:19998]
```

**To Reproduce**
```
alluxio.master.hostname=cache02v.*.*.*.net  
alluxio.master.journal.type=EMBEDDED
alluxio.master.embedded.journal.addresses=cache02v.*.*.*.net:19200,cache01v.*.*.*.net:19200,cache04v.*.*.*.net:19200
alluxio.master.rpc.addresses=cache02v.*.*.*.net:19998,cache01v.*.*.*.net:19998,cache04v.*.*.*.net:19998
alluxio.master.mount.table.root.ufs=hdfs://**
alluxio.underfs.hdfs.configuration=**
```
**Expected behavior**

**Urgency**
This bug is not particularly urgent

**Are you planning to fix it**
I'm trying to fix it

**Additional context**

**Comment by LuQQiu** [comment]
@jenoudet did we update ratis version recently? do u think it's a ratis bug or Alluxio side misuse?

**Comment by LuQQiu** [comment]
https://github.com/Alluxio/alluxio/commit/1e95ed69ab9bec895b3bbfe4a2841238cbedc824

**Comment by LuQQiu** [comment]
@xuanlang if possible, could you help try the latest master and see if the error persists?
and it's possible to share the master log of all three masters, or better if debug log is available, it will be helpful for us to understand the event sequence (what's the state of all three masters at a given time)

**Comment by jenoudet** [comment]
> @jenoudet did we update ratis version recently? do u think it's a ratis bug or Alluxio side misuse?

We recently upgraded Ratis to version 2.4.1 in 2.9. Since this issue is also present in Alluxio 2.8.2, it does not indicate that it is specific to this recent Ratis upgrade.

**Comment by xuanlang** [comment]
@LuQQiu @jenoudet The problem has been solved, the reason is that all masers are configured with the same `alluxio.master.hostname` parameter.

**Comment by jenoudet** [comment]
Awesome, glad this is resolved.
