### ISSUE TITLE
spark-operator write data into alluxio, occurs error

### ISSUE THREAD

**Issue by lingchuanzhou** [Alluxio/alluxio#16862]
this is my conf:
-Dalluxio.master.hostname=alluxio-master-0 -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal -Dalluxio.security.stale.channel.purge.interval=365d -Dalluxio.security.authentication.type=NOSASL -Dalluxio.security.authorization.permission.enabled=false -Dalluxio.master.jvm.monitor.enabled=true -Dalluxio.master.journal.flush.timeout=30min -Dalluxio.master.journal.flush.batch.time=60s -Dalluxio.user.short.circuit.enabled=true -Dalluxio.worker.data.server.domain.socket.address=/opt/domain -Dalluxio.worker.data.server.domain.socket.as.uuid=true -Dalluxio.worker.tieredstore.levels=2 -Dalluxio.worker.tieredstore.level1.alias=HDD -Dalluxio.worker.tieredstore.level1.dirs.mediumtype=HDD -Dalluxio.worker.tieredstore.level1.dirs.path=/mnt/data -Dalluxio.worker.tieredstore.level1.dirs.quota=500Gi -Dalluxio.worker.tieredstore.level1.watermark.high.ratio=0.95 -Dalluxio.worker.tieredstore.level1.watermark.low.ratio=0.7 -Dalluxio.worker.network.async.cache.manager.threads.max=256 -Dalluxio.worker.network.block.reader.threads.max=12288 -Dalluxio.worker.network.async.cache.manager.queue.max=1024 -Dalluxio.job.worker.threadpool.size=48 -Dalluxio.worker.jvm.monitor.enabled=true -Dalluxio.user.metrics.collection.enabled=true -Dalluxio.user.streaming.data.timeout=120s -Dalluxio.user.streaming.writer.close.timeout=300s -Dalluxio.user.file.writetype.default=MUST_CACHE -Dalluxio.master.metadata.sync.executor.pool.size=12

and when spark write parquet to disk, occurs this error:
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1761)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:163)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Job aborted.
        at org.apache.spark.sql.errors.QueryExecutionErrors$.jobAbortedError(QueryExecutionErrors.scala:496)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:251)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:186)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:128)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:848)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:382)
        at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:355)
        at org.apache.spark.sql.DataFrame

**Comment by lingchuanzhou** [comment]
Caused by: alluxio.shaded.client.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Connection refused: /opt/domain/d6deced6-5f88-4adf-9281-e07ec52ea058
Caused by: java.net.ConnectException: connect(..) failed: Connection refused
        at alluxio.shaded.client.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
        at alluxio.shaded.client.io.netty.channel.unix.Socket.connect(Socket.java:239)
        at alluxio.shaded.client.io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:735)
        at alluxio.shaded.client.io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:720)
        at alluxio.shaded.client.io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)
        at alluxio.shaded.client.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:562)
        at alluxio.shaded.client.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
        at alluxio.shaded.client.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
        at alluxio.shaded.client.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:155)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
        at alluxio.shaded.client.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:538)
        at alluxio.shaded.client.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at alluxio.shaded.client.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at alluxio.shaded.client.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at alluxio.shaded.client.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Unknown Source)

23/02/09 20:12:23 ERROR TaskSetManager: Task 1140 in stage 4.0 failed 4 times; aborting job
23/02/09 20:12:23 INFO TaskSchedulerImpl: Cancelling stage 4
23/02/09 20:12:23 INFO TaskSchedulerImpl: Killing all running tasks in stage 4: Stage cancelled
23/02/09 20:12:23 INFO TaskSchedulerImpl: Stage 4 was cancelled
23/02/09 20:12:23 INFO DAGScheduler: ResultStage 4 (save at TmpSparkParquetApp.java:65) failed in 235.175 s due to Job aborted due to stage failure: Task 1140 in stage 4.0 failed 4 times, most recent failure: Lost task 1140.3 in stage 4.0 (TID 18664) (10.42.208.102 executor 5): alluxio.exception.status.UnavailableException: io exception (GrpcDataWriter{request=type: UFS_FILE

**Comment by LuQQiu** [comment]
@lingchuanzhou is the Alluxio cluster running?
or the Spark job cannot connected to the running cluster?
What's your Spark configuration to connect to master?

**Comment by ssz1997** [comment]
This seems the same as https://github.com/Alluxio/alluxio/issues/16903 so I'm closing this issue as well. Feel free to reopen or raise new issues if you have more problems. Thank you for your contribution.
