### ISSUE TITLE
java code can not access k8s-alluxio cluster

### ISSUE THREAD

**Issue by yiwei00000** [Alluxio/alluxio#16939]
Hi:
    I deployed alluxio cluster by k8s helm. The cluster is running and i can access by browser, all nodes are normal. But when i access by java code on my mac os, i can read files which in alluxio cluster. How can i config my mac , then i can run java code to access alluxio cluster.

    my java code:
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/7892927/220883190-fa200d74-9153-48ec-9af4-40fdaaf07a79.png">
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/7892927/220883276-26d001a9-c07a-4fcf-9e9a-57c832e9dd59.png">

error info:

Exception in thread "main" java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=xxx, SocketAddress=10.244.2.147/10.244.2.147:29999}
	at alluxio.client.block.stream.BlockWorkerClient$Factory.create(BlockWorkerClient.java:62)
	at alluxio.client.block.stream.BlockWorkerClientPool.createNewResource(BlockWorkerClientPool.java:72)
	at alluxio.client.block.stream.BlockWorkerClientPool.createNewResource(BlockWorkerClientPool.java:35)
	at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:328)
	at alluxio.resource.DynamicResourcePool.acquire(DynamicResourcePool.java:297)
	at alluxio.client.file.FileSystemContext.acquireBlockWorkerClientInternal(FileSystemContext.java:549)
	at alluxio.client.file.FileSystemContext.acquireBlockWorkerClient(FileSystemContext.java:529)
	at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:92)
	at alluxio.client.block.stream.GrpcDataReader.<init>(GrpcDataReader.java:54)
	at alluxio.client.block.stream.GrpcDataReader$Factory.create(GrpcDataReader.java:240)
	at alluxio.client.block.stream.BlockInStream.readChunk(BlockInStream.java:482)
	at alluxio.client.block.stream.BlockInStream.read(BlockInStream.java:317)
	at alluxio.client.file.AlluxioFileInStream.read(AlluxioFileInStream.java:185)
	at alluxio.client.file.FileInStream.read(FileInStream.java:53)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:178)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
	at com.jdt.alluxio.AlluxioJ.readFile(AlluxioJ.java:72)
	at com.jdt.alluxio.AlluxioJ.main(AlluxioJ.java:37)
Caused by: alluxio.exception.status.UnavailableException: Failed to connect to remote server GrpcServerAddress{HostName=xxx, SocketAddress=10.244.2.147/10.244.2.147:29999}. GrpcChannelKey{ClientType=DefaultBlockWorkerClient-Stream, ClientHostname=10.253.58.168, ServerAddress=GrpcServerAddress{HostName=xxx SocketAddress=10.244.2.147/10.244.2.147:29999}, ChannelId=8529c162-c9a4-4894-b8da-0c08b1139f3b}
	at alluxio.grpc.GrpcChannelBuilder.build(GrpcChannelBuilder.java:146)
	at alluxio.client.block.stream.DefaultBlockWorkerClient.<init>(DefaultBlockWorkerClient.java:105)
	at alluxio.client.block.stream.BlockWorkerClient$Factory.create(BlockWorkerClient.java:59)
	... 22 more
Caused by: alluxio.exception.status.UnavailableException: Waited 30000 milliseconds (plus 2 milliseconds, 917494 nanoseconds delay) for com.google.common.util.concurrent.SettableFuture@6b410923[status=PENDING]
	at alluxio.security.authentication.AuthenticatedChannelClientDriver.waitUntilChannelAuthenticated(AuthenticatedChannelClientDriver.java:194)
	at alluxio.security.authentication.AuthenticatedChannelClientDriver.startAuthenticatedChannel(AuthenticatedChannelClientDriver.java:164)
	at alluxio.security.authentication.ChannelAuthenticator.authenticate(ChannelAuthenticator.java:103)
	at alluxio.grpc.GrpcChannelBuilder.build(GrpcChannelBuilder.java:129)
	... 24 more
Caused by: java.util.concurrent.TimeoutException: Waited 30000 milliseconds (plus 2 milliseconds, 917494 nanoseconds delay) for com.google.common.util.concurrent.SettableFuture@6b410923[status=PENDING]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:506)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:109)
	at alluxio.security.authentication.AuthenticatedChannelClientDriver.waitUntilChannelAuthenticated(AuthenticatedChannelClientDriver.java:181)
	... 27 more

**Comment by dbw9580** [comment]
Hi @yiwei00000 The client which is your Java program running on your Mac is having trouble reaching a worker at `10.244.2.147:29999`. Can you check if the worker is reachable from your Mac? Are your network and firewall, etc. properly configured?
