### ISSUE TITLE
Can not use alluxio fuse special command

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17029]
**Alluxio Version:**
2.9.0

**Describe the bug**
set `alluxio.fuse.special.command.enabled=true`, and `ls -l /path/to/mountpoint/.alluxiocli.metadatacache.dropAll`.

I got an exception:
```
2023-03-07 22:25:37,222 ERROR AlluxioJniFuseFileSystem - Failed to getattr /.alluxiocli.metadatacache.dropAll
java.lang.ClassCastException: alluxio.client.file.cache.LocalCacheFileSystem cannot be cast to alluxio.client.file.MetadataCachingFileSystem
	at alluxio.cli.command.metadatacache.AbstractMetadataCacheSubCommand.run(AbstractMetadataCacheSubCommand.java:46)
	at alluxio.cli.FuseShell.runCommand(FuseShell.java:100)
	at alluxio.fuse.AlluxioJniFuseFileSystem.getattrInternal(AlluxioJniFuseFileSystem.java:200)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$getattr$2(AlluxioJniFuseFileSystem.java:185)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:518)
	at alluxio.fuse.AlluxioJniFuseFileSystem.getattr(AlluxioJniFuseFileSystem.java:184)
	at alluxio.jnifuse.AbstractFuseFileSystem.getattrCallback(AbstractFuseFileSystem.java:205)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by apc999** [comment]
@maobaolong  @LuQQiu can you take a look here? 

`alluxio.fuse.special.command.enabled` is an experimental flag created by @maobaolong and other folks from Tencent.

**Comment by humengyu2012** [comment]
If we enable client cache, the filesystem actually is `LocalCacheFileSystem` instead of `MetadataCachingFileSystem`, maybe we should add a judgment logic.

**Comment by humengyu2012** [comment]
Can I propose a PR to fix this problem?

**Comment by elega** [comment]
sure i asked @LuQQiu to take a look

**Comment by humengyu2012** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/17035.
