### ISSUE TITLE
Failed to determine primary master rpc address

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17041]
**Alluxio Version:**

master/worker/proxy 2.9.0
fuse 2.9.1

**Describe the bug**
Our fuse process sometimes restarts:
```
我们的 fuse 报这个错，可能的原因有人了解过么
23-03-09 02:14:27,256 INFO  NativeLibraryLoader - Loaded libjnifuse with libfuse version 2.
2023-03-09 02:14:27,273 INFO  LocalCacheManager - PageStore (/data1/alluxio-fuse/LOCAL) restored with 265 pages (3756416333 bytes), discarded 0 pages (com.codahale.metrics.Counter@7aff4e23 bytes)
2023-03-09 02:14:27,273 INFO  LocalCacheManager - Cache is in READ_WRITE.
2023-03-09 02:14:27,388 INFO  Reflections - Reflections took 108 ms to scan 1 urls, producing 64 keys and 220 values
2023-03-09 02:14:27,410 INFO  LaunchUserGroupAuthPolicy - Initialized Fuse auth policy with launch user (id:1000) and group (id:1000)
2023-03-09 02:14:27,412 INFO  AlluxioFuse - Mounting AlluxioJniFuseFileSystem: mount point="/mnt/alluxio", OPTIONS="allow_other,big_writes"
2023-03-09 02:14:27,412 INFO  AbstractFuseFileSystem - Mounting /mnt/alluxio: blocking=true, debug=false, fuseOpts="allow_other,big_writes"
ERROR ../../src/main/native/libjnifuse/jnifuse_helper.cc:34 Validate standard errors can be logged as expected
fuse: max_idle_threads: 64
fuse: max_idle_threads: 64
fuse: max_idle_threads: 64
2023-03-09 02:14:36,757 ERROR ClientMasterSync - Failed to get master address during initialization
alluxio.exception.status.UnavailableException: Failed to determine primary master rpc address after polling each of [alluxio-master01:19998, alluxio-master02:19998, alluxio-master03:19998] 4 times
 at alluxio.master.PollingMasterInquireClient.getPrimaryRpcAddress(PollingMasterInquireClient.java:114)
 at alluxio.client.metrics.ClientMasterSync.loadConf(ClientMasterSync.java:121)
 at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:74)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:750)
fuse: max_idle_threads: 64
fuse: max_idle_threads: 64
fuse: max_idle_threads: 64
2023-03-09 02:15:21,248 INFO  FuseSignalHandler - Receive signal name TERM, number 15, system exiting
2023-03-09 02:15:21,248 INFO  AbstractFuseFileSystem - Umounting /mnt/alluxio
2023-03-09 02:15:21,250 INFO  AbstractFuseFileSystem - Unmounting Fuse through shutdown hook
2023-03-09 02:15:21,750 WARN  MetricsHeartbeatContext - Failed to heartbeat to the metrics master before exit
INFO ../../src/main/native/libjnifuse/jnifuse_onload.cc:25 Loaded libjnifuse
INFO ../../src/main/native/libjnifuse/jnifuse_helper.cc:33 Start initializing JNIFuse
```

The alluxio-site.properties of fuse is:
```
alluxio.master.embedded.journal.addresses=xxxxx
​
alluxio.fuse.web.enabled=true
alluxio.fuse.special.command.enabled=true
​
alluxio.user.client.cache.enabled=true
alluxio.user.client.cache.dirs=/data1/alluxio-fuse
alluxio.user.client.cache.size=4TB
alluxio.user.client.cache.page.size=16MB
​
alluxio.user.metadata.cache.enabled=true
alluxio.user.metadata.cache.expiration.time=2h
alluxio.user.metadata.cache.max.size=2000000
```
The alluxio-site.properties of proxy is:
```
alluxio.user.file.metadata.sync.interval=0
alluxio.user.block.read.retry.max.duration=1min
```

and the log of master like this:
```
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10434 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10435 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10436 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10437 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10438 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10439 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10440 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10441 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10442 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10443 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10444 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10445 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10446 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10447 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10448 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10449 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10450 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10451 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10452 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10453 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10454 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10455 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10456 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10457 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10458 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10459 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10460 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10461 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10462 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10463 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10464 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10465 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10466 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10467 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10468 entries, over the limit of 10000
2023-03-09 02:38:49,176 WARN  FileSystemMergeJournalContext - MergeJournalContext has 10469 entries, over the limit of 10000
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by Kai-Zhang** [comment]
Could you provide more logs of the master at the error time point? And is this a temporary error or does the client keep failing?
@elega FYI

**Comment by humengyu2012** [comment]
Matser log:
```
1687095 2023-03-09 06:32:50,338 WARN  CommonUtils - got exception trying to get groups for user ici_feed: ExitCodeException exitCode=1: id: ‘ici_feed’: no such user
1687096 id: ‘ici_feed’: no such user
1687097
1687098 2023-03-09 06:33:21,009 INFO  DefaultFileSystemMaster - The interval of Master Replication Check updated to 60000
1687099 2023-03-09 06:33:21,009 INFO  MetricsHeartbeatContext - Created metrics heartbeat with ID app-8088437392379863529. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id p        roperty
1687100 2023-03-09 06:34:21,010 INFO  DefaultFileSystemMaster - The interval of Master Replication Check updated to 60000
1687101 2023-03-09 06:34:21,010 INFO  MetricsHeartbeatContext - Created metrics heartbeat with ID app-8879488952222678944. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id p        roperty
1687102 2023-03-09 06:34:51,643 WARN  SystemMonitor - System transition status is ESCALATE, status is STRESSED, related Server aggregate indicators:ServerIndicator{directMemUsed=3930731589, heapMax=274877906944, heapUsed=660248620080, cpu        Load=0.19340841730883224, pitTotalJVMPauseTimeMS=0, totalJVMPauseTimeMS=21, rpcQueueSize=0, pitTimeMS=1677487549276}, pit indicators:ServerIndicator{directMemUsed=1310243863, heapMax=274877906944, heapUsed=224512058384, cpuLoad=0.        06446947243627742, pitTotalJVMPauseTimeMS=19908, totalJVMPauseTimeMS=6, rpcQueueSize=0, pitTimeMS=1678314891642}
1687103 2023-03-09 06:34:54,642 WARN  SystemMonitor - System transition status is UNCHANGED, status is STRESSED, related Server aggregate indicators:ServerIndicator{directMemUsed=3930731589, heapMax=274877906944, heapUsed=673469066288, cp        uLoad=0.19340841730883224, pitTotalJVMPauseTimeMS=0, totalJVMPauseTimeMS=22, rpcQueueSize=0, pitTimeMS=1677487549276}, pit indicators:ServerIndicator{directMemUsed=1310243863, heapMax=274877906944, heapUsed=228974797840, cpuLoad=0        .06446947243627742, pitTotalJVMPauseTimeMS=19916, totalJVMPauseTimeMS=8, rpcQueueSize=0, pitTimeMS=1678314894642}
1687104 2023-03-09 06:34:57,642 WARN  SystemMonitor - System transition status is UNCHANGED, status is STRESSED, related Server aggregate indicators:ServerIndicator{directMemUsed=3930731589, heapMax=274877906944, heapUsed=683602504752, cp        uLoad=0.19340841730883224, pitTotalJVMPauseTimeMS=0, totalJVMPauseTimeMS=14, rpcQueueSize=0, pitTimeMS=1677487549276}, pit indicators:ServerIndicator{directMemUsed=1310243863, heapMax=274877906944, heapUsed=230115648528, cpuLoad=0        .06446947243627742, pitTotalJVMPauseTimeMS=19916, totalJVMPauseTimeMS=0, rpcQueueSize=0, pitTimeMS=1678314897642}
1687105 2023-03-09 06:34:57,642 WARN  SystemMonitor - The delta filesystem indicators FileSystemIndicator{Master.DeletePathOps=0, Master.PathsDeleted=0, Master.MetadataSyncPathsFail=0, Master.CreateFileOps=0, Master.ListingCacheHits=393,         Master.MetadataSyncSkipped=0, Master.UfsStatusCacheSize=-2951, Master.CreateDirectoryOps=0, Master.FileBlockInfosGot=0, Master.MetadataSyncPrefetchFail=0, Master.FilesCompleted=536, Master.RenamePathOps=0, Master.MetadataSyncSucce        ss=3675, Master.MetadataSyncActivePaths=0, Master.FilesCreated=536, Master.PathsRenamed=0, Master.FilesPersisted=0, Master.CompletedOperationRetryCount=0, Master.ListingCacheEvictions=0, Master.MetadataSyncTimeMs=56000, Master.Set        AclOps=0, Master.PathsMounted=0, Master.FreeFileOps=0, Master.PathsUnmounted=0, Master.CompleteFileOps=0, Master.NewBlocksGot=0, Master.GetNewBlockOps=0, Master.ListingCacheMisses=0, Master.FileInfosGot=6634, Master.GetFileInfoOps        =3262, Master.GetFileBlockInfoOps=0, Master.UnmountOps=0, Master.MetadataSyncPrefetchPaths=9573, Master.getConfigHashInProgress=0, Master.MetadataSyncPathsSuccess=6626, Master.FilesFreed=0, Master.MetadataSyncNoChange=6622, Master        .SetAttributeOps=0, Master.getConfigurationInProgress=0, Master.MetadataSyncPendingPaths=0, Master.DirectoriesCreated=1, Master.ListingCacheLoadTimes=0, Master.MetadataSyncPrefetchSuccess=6753, Master.MountOps=0, Master.UfsStatusC        acheChildrenSize=0, Master.MetadataSyncPrefetchOpsCount=6376, Master.registerWorkerStartInProgress=0, Master.MetadataSyncPrefetchCancel=0, Master.MetadataSyncPathsCancel=0, Master.MetadataSyncPrefetchRetries=0, Master.MetadataSync        Fail=0, Master.MetadataSyncOpsCount=3262}
1687106 2023-03-09 06:35:00,642 WARN  SystemMonitor - System transition status is UNCHANGED, status is STRESSED, related Server aggregate indicators:ServerIndicator{directMemUsed=3930731589, heapMax=274877906944, heapUsed=689843629104, cp        uLoad=0.1454397368160077, pitTotalJVMPauseTimeMS=0, totalJVMPauseTimeMS=8, rpcQueueSize=0, pitTimeMS=1677487549276}, pit indicators:ServerIndicator{directMemUsed=1310243863, heapMax=274877906944, heapUsed=230753182736, cpuLoad=0.0        16500791943452872, pitTotalJVMPauseTimeMS=19916, totalJVMPauseTimeMS=0, rpcQueueSize=0, pitTimeMS=1678314900642}
1687107 2023-03-09 06:35:00,643 WARN  SystemMonitor - The delta filesystem indicators FileSystemIndicator{Master.DeletePathOps=0, Master.PathsDeleted=96, Master.MetadataSyncPathsFail=0, Master.CreateFileOps=0, Master.ListingCacheHits=479,         Master.MetadataSyncSkipped=0, Master.UfsStatusCacheSize=-777, Master.CreateDirectoryOps=0, Master.FileBlockInfosGot=0, Master.MetadataSyncPrefetchFail=0, Master.FilesCompleted=58, Master.RenamePathOps=0, Master.MetadataSyncSucces        s=1042, Master.MetadataSyncActivePaths=0, Master.FilesCreated=58, Master.PathsRenamed=0, Master.FilesPersisted=0, Master.CompletedOperationRetryCount=0, Master.ListingCacheEvictions=0, Master.MetadataSyncTimeMs=6260, Master.SetAcl        Ops=0, Master.PathsMounted=0, Master.FreeFileOps=0, Master.PathsUnmounted=0, Master.CompleteFileOps=0, Master.NewBlocksGot=0, Master.GetNewBlockOps=0, Master.ListingCacheMisses=0, Master.FileInfosGot=1819, Master.GetFileInfoOps=10        41, Master.GetFileBlockInfoOps=0, Master.UnmountOps=0, Master.MetadataSyncPrefetchPaths=2616, Master.getConfigHashInProgress=0, Master.MetadataSyncPathsSuccess=1839, Master.FilesFreed=0, Master.MetadataSyncNoChange=1819, Master.Se        tAttributeOps=0, Master.getConfigurationInProgress=0, Master.MetadataSyncPendingPaths=0, Master.DirectoriesCreated=38, Master.ListingCacheLoadTimes=0, Master.MetadataSyncPrefetchSuccess=1986, Master.MountOps=0, Master.UfsStatusCac        heChildrenSize=0, Master.MetadataSyncPrefetchOpsCount=1985, Master.registerWorkerStartInProgress=0, Master.MetadataSyncPrefetchCancel=0, Master.MetadataSyncPathsCancel=0, Master.MetadataSyncPrefetchRetries=0, Master.MetadataSyncFa        il=0, Master.MetadataSyncOpsCount=1041}
1687108 2023-03-09 06:35:03,642 WARN  SystemMonitor - System transition status is UNCHANGED, status is STRESSED, related Server aggregate indicators:ServerIndicator{directMemUsed=3930731589, heapMax=274877906944, heapUsed=692125330480, cp        uLoad=0.09747105632318315, pitTotalJVMPauseTimeMS=0, totalJVMPauseTimeMS=0, rpcQueueSize=0, pitTimeMS=1677487549276}, pit indicators:ServerIndicator{directMemUsed=1310243863, heapMax=274877906944, heapUsed=231256499216, cpuLoad=0.        016500791943452872, pitTotalJVMPauseTimeMS=19916, totalJVMPauseTimeMS=0, rpcQueueSize=0, pitTimeMS=1678314903642}
1687109 2023-03-09 06:35:03,642 WARN  SystemMonitor - The delta filesystem indicators FileSystemIndicator{Master.DeletePathOps=0, Master.PathsDeleted=85, Master.MetadataSyncPathsFail=0, Master.CreateFileOps=0, Master.ListingCacheHits=374,         Master.MetadataSyncSkipped=0, Master.UfsStatusCacheSize=-613, Master.CreateDirectoryOps=0, Master.FileBlockInfosGot=0, Master.MetadataSyncPrefetchFail=0, Master.FilesCompleted=51, Master.RenamePathOps=0, Master.MetadataSyncSucces        s=857, Master.MetadataSyncActivePaths=0, Master.FilesCreated=51, Master.PathsRenamed=0, Master.FilesPersisted=0, Master.CompletedOperationRetryCount=0, Master.ListingCacheEvictions=0, Master.MetadataSyncTimeMs=7071, Master.SetAclO        ps=0, Master.PathsMounted=0, Master.FreeFileOps=0, Master.PathsUnmounted=0, Master.CompleteFileOps=0, Master.NewBlocksGot=0, Master.GetNewBlockOps=0, Master.ListingCacheMisses=0, Master.FileInfosGot=1469, Master.GetFileInfoOps=857        , Master.GetFileBlockInfoOps=0, Master.UnmountOps=0, Master.MetadataSyncPrefetchPaths=2101, Master.getConfigHashInProgress=0, Master.MetadataSyncPathsSuccess=1487, Master.FilesFreed=0, Master.MetadataSyncNoChange=1471, Master.SetA        ttributeOps=0, Master.getConfigurationInProgress=0, Master.MetadataSyncPendingPaths=0, Master.DirectoriesCreated=34, Master.ListingCacheLoadTimes=0, Master.MetadataSyncPrefetchSuccess=1601, Master.MountOps=0, Master.UfsStatusCache        ChildrenSize=0, Master.MetadataSyncPrefetchOpsCount=1602, Master.registerWorkerStartInProgress=0, Master.MetadataSyncPrefetchCancel=0, Master.MetadataSyncPathsCancel=0, Master.MetadataSyncPrefetchRetries=0, Master.MetadataSyncFail        =0, Master.MetadataSyncOpsCount=857}
```

**Comment by humengyu2012** [comment]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/45056332/224205011-b8ac63c5-5307-4cae-9ff6-747ddc26a425.png">
