### ISSUE TITLE
FileSystemContext.acquireClosableClientResource encountered NullPointerException

### ISSUE THREAD

**Issue by secfree** [Alluxio/alluxio#17080]
**Alluxio Version:**
2.7.1

**Describe the bug**
A spark application encountered the NullPointerException while reading from Alluxio. As the log shows below

```
23/03/13 11:42:20 INFO AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration ...
23/03/13 11:42:20 INFO AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration ...
23/03/13 11:42:20 INFO AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration ...
23/03/13 11:42:20 INFO AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration ...
23/03/13 11:42:20 INFO AbstractFileSystem: Initializing filesystem with connect details ip-...
23/03/13 11:42:20 INFO AbstractFileSystem: Initializing filesystem with connect details ip-...
23/03/13 11:42:20 INFO AbstractFileSystem: Initializing filesystem with connect details ip-...
23/03/13 11:42:20 INFO AbstractFileSystem: Initializing filesystem with connect details ip-...
23/03/13 11:42:20 INFO MetricsHeartbeatContext: Created metrics heartbeat with ID app-7110688343508577278. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
23/03/13 11:42:20 INFO TieredIdentityFactory: Initialized tiered identity TieredIdentity(node=..., rack=null)
23/03/13 11:42:20 ERROR Executor: Exception in task 29.0 in stage 0.0 (TID 29)
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:375)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.readParquetFootersInParallel(ParquetFileFormat.scala:450)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1(ParquetFileFormat.scala:496)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$mergeSchemasInParallel$1$adapted(ParquetFileFormat.scala:490)
	at org.apache.spark.sql.execution.datasources.SchemaMergeUtils$.$anonfun$mergeSchemasInParallel$2(SchemaMergeUtils.scala:75)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1509)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Could not read footer for file: FileStatus{path=hdfs://...; isDirectory=false; ...}
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:463)
	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:372)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at alluxio.client.file.FileSystemContext.acquireClosableClientResource(FileSystemContext.java:505)
	at alluxio.client.file.FileSystemContext.acquireMasterClientResource(FileSystemContext.java:460)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:570)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:274)
	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:381)
	at alluxio.client.file.FileSystem.openFile(FileSystem.java:497)
	at alluxio.hadoop.HdfsFileInputStream.<init>(HdfsFileInputStream.java:62)
	at alluxio.hadoop.AbstractFileSystem.open(AbstractFileSystem.java:650)
	at org.apache.hadoop.hdfs.ForwardDistributedFileSystem.open(ForwardDistributedFileSystem.java:346)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
	at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:65)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:498)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:476)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.$anonfun$readParquetFootersInParallel$1(ParquetFileFormat.scala:457)
	... 13 more
```

**To Reproduce**
Have not found a way to reproduce it.

**Expected behavior**
No NPE.

**Urgency**
Urgent

**Comment by Kai-Zhang** [comment]
Could you give some details on the configuration or logging from alluxio side? Are there any exceptions in the logs of alluxio master/worker?

**Comment by secfree** [comment]
Found the issue is caused by HDFS side, so I will just close this

Below are the details
1. Spark uses `org.apache.hadoop.fs.FileSystem.get` to get FileSystem instances to access HDFS and Alluxio.
2. In one of our datacenters, if a job access `hdfs://A/`, it will be forwarded to `alluxio://B/`.
3. `org.apache.hadoop.fs.FileSystem.get` caches the FileSystem instance by default, so the chain is `Spark -> FileSystem.get(cache hdfs) -> ForwardDistributedFileSystem -> FileSystem.get(cache alluxio)`
4. If there is parallelism at the driver side(eg. execute `paths.par.map {p => spark.read.parquet(p).count}` in spark-shell), the driver may create multiple FileSystem instances at the same time, and `FileSystem$Cache.getInternal` will close duplicate ones(https://github.com/apache/hadoop/blob/branch-3.3/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3716).
5. When the parallelism is 3, 3 alluxio filesystem instances will be created but only 1 will be left in cache. Then 3 hdfs filesystem instances will point to the left 1 alluxio filesystem instance. As they all point to the same alluxio filesystem instance, closing any of them will make the alluxio filesystem instance closed. So NPE is triggered.
6. One solution is to disable the cache for alluxio by setting `spark.hadoop.fs.alluxio.impl.disable.cache=true`. 
7. Another solution is to check whether filesystem instances point to the same one before closing at https://github.com/apache/hadoop/blob/branch-3.3/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3716
