### ISSUE TITLE
Failed to upload files to the mount point of the ufs cluster configured by parameters

### ISSUE THREAD

**Issue by Haoning-Sun** [Alluxio/alluxio#17158]
**Alluxio Version:**
2.7.1

**Describe the bug**
Mount a ufs path using option `alluxio.underfs.hdfs.configuration`. The mount was successful, but the file upload failed.

**To Reproduce**

1. Mount a ufs path using option `alluxio.underfs.hdfs.configuration`.
2. There is no configuration file on the worker node.
3. Use `copyFromLocal` upload a file and it will be failed.
4. Add configuration files for worker and re-upload the file, it still fails.

**Expected behavior**
After adding the configuration files to the worker, the file can be re-uploaded without restarting the worker node.

**Are you planning to fix it**
yes. 

**Additional context**
Error log:
```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: java.net.UnknownHostException: XX
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem.getFs(HdfsUnderFileSystem.java:831)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem.createDirect(HdfsUnderFileSystem.java:287)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem.create(HdfsUnderFileSystem.java:279)
        at alluxio.underfs.ConsistentUnderFileSystem.createNonexistingFile(ConsistentUnderFileSystem.java:46)
        at alluxio.underfs.UnderFileSystemWithLogging$8.call(UnderFileSystemWithLogging.java:224)
        at alluxio.underfs.UnderFileSystemWithLogging$8.call(UnderFileSystemWithLogging.java:221)
        at alluxio.underfs.UnderFileSystemWithLogging.call(UnderFileSystemWithLogging.java:1213)
        at alluxio.underfs.UnderFileSystemWithLogging.createNonexistingFile(UnderFileSystemWithLogging.java:221)
        at alluxio.worker.grpc.UfsFileWriteHandler.createUfsFile(UfsFileWriteHandler.java:166)
        at alluxio.worker.grpc.UfsFileWriteHandler.writeBuf(UfsFileWriteHandler.java:139)
        at alluxio.worker.grpc.UfsFileWriteHandler.writeBuf(UfsFileWriteHandler.java:49)
        at alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:281)
        at alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:179)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:159)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: XX
        at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:444)
        at org.apache.hadoop.hdfs.NameNodeProxiesClient.createProxyWithClientProtocol(NameNodeProxiesClient.java:142)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:375)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:309)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:168)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3269)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:472)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem$1.load(HdfsUnderFileSystem.java:186)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem$1.load(HdfsUnderFileSystem.java:172)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 21 more
Caused by: java.net.UnknownHostException: XX
        ... 35 more
```

**Comment by ChunxuTang** [comment]
Hi @Haoning-Sun, thanks for your suggestion! We'll review your PR soon.
