### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

### ISSUE THREAD

**Issue by shipoyewu** [Alluxio/alluxio#17169]
**Alluxio Version:**
What version of Alluxio are you using?
2.8.0

**Describe the bug**
When I use Spark to write a large amount of data (2T) to Alluxio, I frequently encounter the problem of 'Network closed for unknown reason.
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

Reading data larger than 2T from Hive and writing it into Alluxio with writeType set to MUST_CACHE, partitioned into 20 segments. After a period of time (around 20 minutes), this problem occurred."
**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.
Task failed.
**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**
3/03/30 12:15:10 WARN GrpcBlockingStream: Received error io.grpc.StatusRuntimeException: CANCELLED: Request is cancelled by user. for stream (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 17976568840192
tier: 0
medium_type: ""
pin_on_create: false
space_to_reserve: 67108864
, address=WorkerNetAddress{host=[*****], containerHost=[*****], rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/f5d5ead0-b069-4946-950f-e33f8ed7e5fe, tieredIdentity=TieredIdentity(node=[*****], rack=null)}})
23/03/30 12:15:10 WARN GrpcBlockingStream: Received error io.grpc.StatusRuntimeException: CANCELLED: Request is cancelled by user. for stream (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 17976568840193
tier: 0
medium_type: ""
pin_on_create: false
space_to_reserve: 67108864
, address=WorkerNetAddress{host=[*****], containerHost=[*****], rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/7c6834d1-85fc-4811-a640-cdbc6d5a0eeb, tieredIdentity=TieredIdentity(node=[*****], rack=null)}})
23/03/30 12:15:10 WARN GrpcBlockingStream: Received error io.grpc.StatusRuntimeException: CANCELLED: Request is cancelled by user. for stream (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 17976568840195
tier: 0
medium_type: ""
pin_on_create: false
space_to_reserve: 67108864
, address=WorkerNetAddress{host=[*****], containerHost=[*****], rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/a571d7c6-b0d8-4058-b90e-4b428084c3c7, tieredIdentity=TieredIdentity(node=[*****], rack=null)}})
23/03/30 12:15:10 WARN GrpcBlockingStream: Received error io.grpc.StatusRuntimeException: CANCELLED: Request is cancelled by user. for stream (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 17976568840194
tier: 0
medium_type: ""
pin_on_create: false
space_to_reserve: 67108864
, address=WorkerNetAddress{host=[*****], containerHost=[*****], rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/f64fb74c-b382-48a0-9c20-434d82096e03, tieredIdentity=TieredIdentity(node=[*****], rack=null)}})
23/03/30 12:15:10 WARN AuthenticationUserUtils: Impersonation ignored. Invalid configuration: root
23/03/30 12:15:10 WARN Utils: Suppressing exception in catch: Network closed for unknown reason (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 17976568840196
tier: 0
medium_type: ""
pin_on_create: false
space_to_reserve: 67108864
, address=WorkerNetAddress{host=[*****], containerHost=[*****], rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/34c9899e-6d4d-4c75-861d-31cad8b0ccf8, tieredIdentity=TieredIdentity(node=[*****], rack=null)}})
alluxio.exception.status.UnavailableException: Network closed for unknown reason (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 17976568840196
tier: 0
medium_type: ""
pin_on_create: false
space_to_reserve: 67108864
, address=WorkerNetAddress{host=[*****], containerHost=[*****], rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/34c9899e-6d4d-4c75-861d-31cad8b0ccf8, tieredIdentity=TieredIdentity(node=[*****], rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:156)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:317)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:298)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:208)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receive(GrpcDataMessageBlockingStream.java:61)
	at alluxio.client.block.stream.GrpcBlockingStream.waitForComplete(GrpcBlockingStream.java:258)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.waitForComplete(GrpcDataMessageBlockingStream.java:110)
	at alluxio.client.block.stream.GrpcDataWriter.close(GrpcDataWriter.java:260)
	at com.tuhu.shaded.com.google.common.io.Closer.close(Closer.java:216)
	at alluxio.client.block.stream.BlockOutStream.close(BlockOutStream.java:228)
	at alluxio.client.block.stream.BlockOutStream.cancel(BlockOutStream.java:214)
	at alluxio.client.file.AlluxioFileOutStream.close(AlluxioFileOutStream.java:174)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.spark.sql.execution.datasources.text.TextOutputWriter.close(TextFileFormat.scala:162)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:57)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.abort(FileFormatDataWriter.scala:83)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$1.apply$mcV$sp(FileFormatWriter.scala:250)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1403)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:248)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:172)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 3 more
23/03/30 12:15:10 ERROR Executor: Exception in task 11.0 in stage 7.0 (TID 92708)
org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:257)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to cache: Failed to connect to block worker (GrpcServerAddress{HostName=[*****], SocketAddress=[*****]/[*****]:29999})
	at alluxio.client.file.AlluxioFileOutStream.handleCacheWriteException(AlluxioFileOutStream.java:317)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:280)
	at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:234)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:58)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at org.apache.spark.unsafe.types.UTF8String.writeTo(UTF8String.java:214)
	at org.apache.spark.sql.execution.datasources.text.TextOutputWriter.write(TextFileFormat.scala:156)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.write(FileFormatDataWriter.scala:137)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:245)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:242)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:248)
	... 10 more
	Suppressed: alluxio.exception.status.UnavailableException: Network closed for unknown reason (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 17976568840196
tier: 0

**Comment by ChunxuTang** [comment]
Thanks for raising the question. Looks like it's related to gRPC. We'll take a closer look at the issue.
Meanwhile, would you mind sharing a bit more about the deployment? How did you deploy the Alluxio cluster and what is the scale?

**Comment by shipoyewu** [comment]
您好，您的邮件我已收到!祝：工作商祺!

**Comment by maobaolong** [comment]
@shipoyewu Thanks for share your issue here, would you like to paste the worker side related log? From this log, we can know that there are something wrong between client and worker.

**Comment by shipoyewu** [comment]
Thank you all for taking the time to pay attention to this issue. However, I have found the root cause of the problem. It is because the Spark memory was overloaded, which led to the connection problem of the client. We solved this problem by modifying the Spark parameters.

**Comment by ChunxuTang** [comment]
Thanks for the clarification!
