### ISSUE TITLE
Can not use s3 proxy when `alluxio.master.mount.table.root.readonly=true`

### ISSUE THREAD

**Issue by humengyu2012** [Alluxio/alluxio#17160]
**Alluxio Version:**
2.9.3

**Describe the bug**
If alluxio mount root is read-only, we can not use S3 proxy, because we don't have permission to create `/.alluxio_s3_api_metadata/uploads`.

```
2023-03-29 12:28:29,029 ERROR S3Handler - Exception during create s3handler:alluxio.exception.AccessControlException: A write operation on /.alluxio_s3_api_metadata/uploads under a readonly mount point / is not allowed
	at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:89)
	at alluxio.client.file.BaseFileSystem.wrapAndThrowAlluxioStatusException(BaseFileSystem.java:649)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:626)
	at alluxio.client.file.BaseFileSystem.createDirectory(BaseFileSystem.java:159)
	at alluxio.proxy.s3.S3Handler.init(S3Handler.java:242)
	at alluxio.proxy.s3.S3Handler.createHandler(S3Handler.java:147)
	at alluxio.proxy.s3.S3RequestServlet.service(S3RequestServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at alluxio.web.CORSFilter.doFilter(CORSFilter.java:54)
	at alluxio.web.HttpFilter.doFilter(HttpFilter.java:48)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)
Caused by: alluxio.exception.status.PermissionDeniedException: A write operation on /.alluxio_s3_api_metadata/uploads under a readonly mount point / is not allowed
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:145)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:215)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:486)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:450)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:439)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.createDirectory(RetryHandlingFileSystemMasterClient.java:171)
	at alluxio.client.file.BaseFileSystem.lambda$createDirectory$1(BaseFileSystem.java:162)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:624)
	... 40 more
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: A write operation on /.alluxio_s3_api_metadata/uploads under a readonly mount point / is not allowed
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.createDirectory(FileSystemMasterClientServiceGrpc.java:2040)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$createDirectory$2(RetryHandlingFileSystemMasterClient.java:172)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:484)
	... 45 more

```

**Expected behavior**
Allowed read API.

**Urgency**
This causes errors on almost all requests.

**Are you planning to fix it**
yes.

**Comment by humengyu2012** [comment]
https://github.com/Alluxio/alluxio/pull/17155

**Comment by humengyu2012** [comment]
alluxio-site.properties:
```
alluxio.user.file.writetype.default=CACHE_THROUGH
alluxio.master.mount.table.root.readonly=true
```

**Comment by lucyge2022** [comment]
Thanks much for this issue, it should be treated info holder only on alluxio, without landing any info on underlying UFS. If Multipart Upload feature is not used, and is blocked on this folder, get rid of the creation of the Initiation of the S3 API metadata directories (in S3Handler.init() in V2 or S3RestServiceHandler constructor in V1 ) should unblock Thanks
