### ISSUE TITLE
 Failed to set channel option 'alluxio.shaded.client.io.netty.channel.epoll.EpollChannelOption'

### ISSUE THREAD

**Issue by xuanlang** [Alluxio/alluxio#17233]
**Alluxio Version:**
2.8.0, 2.8.2, 2.9.0

**Describe the bug**
When executing Hadoop -ls, -put, jar and other commands, alluxio will keep printing netty warning information

**To Reproduce**
`-bash-4.2$ ./bin/hadoop fs -ls alluxio://ebj@my-alluxio-cluster/home/test/demo

23/04/12 10:30:51 INFO hadoop.AbstractFileSystem: Creating Alluxio configuration from Hadoop configuration {alluxio.master.rpc.address.my-alluxio-cluster.master2=m1.*.*.*.*:19998, alluxio.master.nameservices.my-alluxio-cluster=master1,master2,master3, alluxio.master.rpc.address.my-alluxio-cluster.master1=m2.*.*.*.*:19998, alluxio.master.rpc.address.my-alluxio-cluster.master3=m3.*.*.*.*:19998, alluxio.master.rpc.addresses=m2.*.*.*.*:19998,m1.*.*.*.*:19998,m3.*.*.*.*:19998}, uri configuration {alluxio.zookeeper.address=null, alluxio.zookeeper.enabled=false, alluxio.master.rpc.addresses=m2.*.*.*.*:19998,m1.*.*.*.*:19998,m3.*.*.*.*:19998}
23/04/12 10:30:51 INFO hadoop.AbstractFileSystem: Initializing filesystem with connect details m2.*.*.*.*:19998,m1.*.*.*.*:19998,m3.*.*.*.*:19998
23/04/12 10:30:51 INFO metrics.MetricsSystem: Starting sinks with config: {}.
23/04/12 10:30:51 INFO metrics.MetricsHeartbeatContext: Created metrics heartbeat with ID app-2525338048594741580. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
23/04/12 10:30:51 INFO network.TieredIdentityFactory: Initialized tiered identity TieredIdentity(node=*.*.*.*, rack=null)
23/04/12 10:30:52 INFO network.NettyUtils: EPOLL_MODE is available
23/04/12 10:30:52 WARN bootstrap.Bootstrap: Failed to set channel option 'alluxio.shaded.client.io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT' with value '30000' for channel '[id: 0x2a5f6a1f]'
alluxio.shaded.client.io.netty.channel.ChannelException: setsockopt() failed: Protocol not available
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(Native Method)
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(LinuxSocket.java:203)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setTcpUserTimeout(EpollSocketChannelConfig.java:481)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setOption(EpollSocketChannelConfig.java:157)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:451)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:443)
	at alluxio.shaded.client.io.netty.bootstrap.Bootstrap.init(Bootstrap.java:265)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:311)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at alluxio.shaded.client.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:258)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:258)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:200)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1827)
	at alluxio.shaded.client.io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/04/12 10:30:52 WARN bootstrap.Bootstrap: Failed to set channel option 'alluxio.shaded.client.io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT' with value '30000' for channel '[id: 0x272087dd]'
alluxio.shaded.client.io.netty.channel.ChannelException: setsockopt() failed: Protocol not available
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(Native Method)
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(LinuxSocket.java:203)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setTcpUserTimeout(EpollSocketChannelConfig.java:481)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setOption(EpollSocketChannelConfig.java:157)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:451)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:443)
	at alluxio.shaded.client.io.netty.bootstrap.Bootstrap.init(Bootstrap.java:265)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:311)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at alluxio.shaded.client.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:258)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:258)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:200)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1827)
	at alluxio.shaded.client.io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/04/12 10:30:52 WARN bootstrap.Bootstrap: Failed to set channel option 'alluxio.shaded.client.io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT' with value '30000' for channel '[id: 0x5d5b1761]'
alluxio.shaded.client.io.netty.channel.ChannelException: setsockopt() failed: Protocol not available
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(Native Method)
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(LinuxSocket.java:203)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setTcpUserTimeout(EpollSocketChannelConfig.java:481)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setOption(EpollSocketChannelConfig.java:157)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:451)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:443)
	at alluxio.shaded.client.io.netty.bootstrap.Bootstrap.init(Bootstrap.java:265)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:311)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at alluxio.shaded.client.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:258)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:258)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:200)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1827)
	at alluxio.shaded.client.io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/04/12 10:30:52 WARN bootstrap.Bootstrap: Failed to set channel option 'alluxio.shaded.client.io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT' with value '30000' for channel '[id: 0xea668a46]'
alluxio.shaded.client.io.netty.channel.ChannelException: setsockopt() failed: Protocol not available
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(Native Method)
	at alluxio.shaded.client.io.netty.channel.epoll.LinuxSocket.setTcpUserTimeout(LinuxSocket.java:203)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setTcpUserTimeout(EpollSocketChannelConfig.java:481)
	at alluxio.shaded.client.io.netty.channel.epoll.EpollSocketChannelConfig.setOption(EpollSocketChannelConfig.java:157)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:451)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:443)
	at alluxio.shaded.client.io.netty.bootstrap.Bootstrap.init(Bootstrap.java:265)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:311)
	at alluxio.shaded.client.io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at alluxio.shaded.client.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:258)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:33)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:258)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:65)
	at alluxio.shaded.client.io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:200)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at alluxio.shaded.client.io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1827)
	at alluxio.shaded.client.io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Expected behavior**

**Urgency**
more urgent

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by xuanlang** [comment]
yes, operation succeeded

**Comment by huanghua78** [comment]
OK. Thank you for reporting this issue.
We may lower this log level from warning to info.
