### ISSUE TITLE
OSS will occur premature end of Content-Length delimited message body error when reading a file

### ISSUE THREAD

**Issue by qian0817** [Alluxio/alluxio#17235]
**Alluxio Version:**
2.7.3

**Describe the bug**
OSS will occur a premature end of Content-Length delimited message body error when reading a file. Although the request will be retried when the file is read, it will cause performance degradation and increase the possibility of request failure.
In the OSS implementation of `MultiRangeObjectInputStream`, if the `mStream` is not used for a long time, it will cause read failures.

**To Reproduce**
```java
public static void main(String[] args) throws IOException, AlluxioException,
    InterruptedException {
  FileSystem fs = FileSystem.Factory.get(new Subject(),
      new InstancedConfiguration(new AlluxioProperties()));
  FileInStream stream = fs.openFile(new AlluxioURI("/xxx"));
  // Simulate some time-consuming operations.
  for (int i = 0; i < 10; i++) {
    stream.read();
    Thread.sleep(20 * 1000);
  }
  stream.read(new byte[Constants.MB * 128]);
  fs.close();
}
```
The following warning message will appear on the client.
```
2023-04-12 15:33:04,662 WARN  GrpcBlockingStream - Received error on stream (Zero Copy GrpcDataReader)
io.grpc.StatusRuntimeException: UNKNOWN: Premature end of Content-Length delimited message body (expected: 67,108,864; received: 28,705,134)
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:172)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2023-04-12 15:33:04,670 WARN  AlluxioFileInStream - Failed to read block 16777216 of file /xxx from worker WorkerNetAddress{host=127.0.0.1, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=127.0.0.1, rack=null)}. This worker will be skipped for future read operations, will retry: alluxio.exception.status.UnknownException: Premature end of Content-Length delimited message body (expected: 67,108,864; received: 28,705,134) (Zero Copy GrpcDataReader).
```

**Expected behavior**
This error does not occur.

**Urgency**

**Are you planning to fix it**

**Additional context**
https://help.aliyun.com/document_detail/32024.html?spm=a2c4g.31978.0.i7#section-d8e-j13-ckf

**Comment by huanghua78** [comment]
@JiamingMai , do you think this is a valid use case and we need to fix such issue ?
This issue is caused by inactive InputStream for a long time.

**Comment by qian0817** [comment]
We found more than 50 logs in a Spark task log, and although the task did not fail, I think the behavior is not as expected and may cause the task to fail.
I currently have no solution to this problem.
@huanghua78 @JiamingMai
