### ISSUE TITLE
setOwner/setMode is not supported to object storage UFS via Alluxio

### ISSUE THREAD

**Issue by lingchuanzhou** [Alluxio/alluxio#17265]
**Alluxio Version:**
**2.9.1**

**Describe the bug**
**I use spark sql extract data, but the last stage has occurs a bug:**

`2023-04-17 12:47:44,801 INFO  DefaultFileSystemMaster - Updating inode 'part-04964-6edb2d01-ff70-4004-94d2-eba20787be6b-c000' mode bits from rw-r--r-- to rwxrwxrwx
2023-04-17 12:47:44,801 WARN  DefaultFileSystemMaster - setOwner/setMode is not supported to object storage UFS via Alluxio. UFS: s3://alluxiotest/s3b/testspark/test_spark10_1/part-04964-6edb2d01-ff70-4004-94d2-eba20787be6b-c000. This has no effect on the underlying object.
2023-04-17 12:48:09,456 WARN  UnderFileSystemWithLogging - RenameRenamableFile(src=s3://alluxiotest/s3b/testspark/test_spark10_1/.hive-staging_hive_2023-04-17_19-21-49_378_1196559485505624773-1/-ext-10000/part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000, dst=s3://alluxiotest/s3b/testspark/test_spark10_1/part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000) returned OK in 48403 ms (>=10000 ms)
2023-04-17 12:48:09,461 INFO  DefaultFileSystemMaster - Updating inode 'part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000' mode bits from rw-r--r-- to rwxrwxrwx
2023-04-17 12:48:09,461 WARN  DefaultFileSystemMaster - setOwner/setMode is not supported to object storage UFS via Alluxio. UFS: s3://alluxiotest/s3b/testspark/test_spark10_1/part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000. This has no effect on the underlying object.
2023-04-17 12:48:24,581 WARN  UnderFileSystemWithLogging - DeleteExistingDirectory(path=s3://alluxiotest/s3b/testspark/test_spark10_1/.hive-staging_hive_2023-04-17_19-21-49_378_1196559485505624773-1, options=DeleteOptions{recursive=true}) returned OK in 14645 ms (>=10000 ms)

23/04/17 20:10:27 INFO TaskSetManager: task 20752.1 in stage 0.0 (TID 20792) failed, but the task will not be re-executed (either because the task failed with a shuffle data fetch failure, so the previous stage needs to be re-run, or because a different copy of the task has already succeeded).
23/04/17 20:10:28 WARN TaskSetManager: Lost task 20424.1 in stage 0.0 (TID 20770) (10.244.94.197 executor 7): TaskCommitDenied (Driver denied task commit) for job: 0, partition: 20424, attemptNumber: 1

23/04/17 20:11:24 INFO TaskSetManager: task 20424.6 in stage 0.0 (TID 20811) failed, but the task will not be re-executed (either because the task failed with a shuffle data fetch failure, so the previous stage needs to be re-run, or because a different copy of the task has already succeeded).
23/04/17 20:11:24 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
23/04/17 20:11:25 INFO FileFormatWriter: Write Job 016386b2-7e83-400c-9079-5b3115a71569 committed. Elapsed time: 944 ms.
23/04/17 20:11:25 INFO FileFormatWriter: Finished processing stats for write job 016386b2-7e83-400c-9079-5b3115a71569.
23/04/17 20:11:25 WARN RetryingMetaStoreClient: MetaStoreClient lost connection. Attempting to reconnect (1 of 1) after 1s. getTable
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table(ThriftHiveMetastore.java:1514)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table(ThriftHiveMetastore.java:1500)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1346)
        at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.getTable(SessionHiveMetaStoreClient.java:127)
        at jdk.internal.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:173)
        at com.sun.proxy.$Proxy32.getTable(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2327)
        at com.sun.proxy.$Proxy32.getTable(Unknown Source)
        at org.apache.hadoop.hive.ql.metadata.Hive.getTable(Hive.java:1281)
        at org.apache.spark.sql.hive.client.HiveClientImpl.getRawTableOption(HiveClientImpl.scala:404)
        at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$tableExists$1(HiveClientImpl.scala:418)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:305)
        at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:236)
        at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:235)
        at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:285)
        at org.apache.spark.sql.hive.client.HiveClientImpl.tableExists(HiveClientImpl.scala:418)
        at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$tableExists$1(HiveExternalCatalog.scala:864)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:102)
        at org.apache.spark.sql.hive.HiveExternalCatalog.tableExists(HiveExternalCatalog.scala:864)
        at org.apache.spark.sql.catalyst.catalog.ExternalCatalog.requireTableExists(ExternalCatalog.scala:47)
        at org.apache.spark.sql.catalyst.catalog.ExternalCatalog.requireTableExists$(ExternalCatalog.scala:46)
        at org.apache.spark.sql.hive.HiveExternalCatalog.requireTableExists(HiveExternalCatalog.scala:56)
        at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$loadTable$1(HiveExternalCatalog.scala:888)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:102)
        at org.apache.spark.sql.hive.HiveExternalCatalog.loadTable(HiveExternalCatalog.scala:887)
        at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.loadTable(ExternalCatalogWithListener.scala:167)
        at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.processInsert(InsertIntoHiveTable.scala:348)
        at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.run(InsertIntoHiveTable.scala:106)
        at org.apache.spark.sql.hive.execution.CreateHiveTableAsSelectBase.run(CreateHiveTableAsSelectCommand.scala:76)
        at org.apache.spark.sql.hive.execution.CreateHiveTableAsSelectBase.run$(CreateHiveTableAsSelectCommand.scala:41)
        at org.apache.spark.sql.hive.execution.CreateHiveTableAsSelectCommand.run(CreateHiveTableAsSelectCommand.scala:113)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        at com.sangfor.aip.app.SparkSqlOnHive.main(SparkSqlOnHive.java:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:165)
        at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:163)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Unknown Source)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:163)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/java.io.BufferedInputStream.fill(Unknown Source)
        at java.base/java.io.BufferedInputStream.read1(Unknown Source)
        at java.base/java.io.BufferedInputStream.read(Unknown Source)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        ... 93 more
23/04/17 20:11:26 INFO metastore: Closed a connection to metastore, current connections: 1
23/04/17 20:11:26 INFO metastore: Trying to connect to metastore with URI thrift://10.72.1.100:31083
23/04/17 20:11:26 INFO metastore: Opened a connection to metastore, current connections: 2
23/04/17 20:11:26 WARN ShellBasedUnixGroupsMapping: got exception trying to get groups for user admin: id: ‘admin’: no such user
id: ‘admin’: no such user

23/04/17 20:11:26 INFO metastore: Connected to metastore.
23/04/17 20:11:26 INFO FileUtils: Creating directory if it doesn't exist: alluxio://alluxio-master-0.alluxio:19998,alluxio-master-1.alluxio:19998,alluxio-master-2.alluxio:19998/testspark/test_spark10_1
23/04/17 20:11:26 INFO SessionState: Could not get hdfsEncryptionShim, it is only applicable to hdfs filesystem.
23/04/17 20:11:26 INFO SessionState: Could not get hdfsEncryptionShim, it is only applicable to hdfs filesystem.
23/04/17 20:11:38 WARN FileSystemMasterClient: Rename(src=/testspark/test_spark10_1/.hive-staging_hive_2023-04-17_19-21-49_378_1196559485505624773-1/-ext-10000/part-00004-6edb2d01-ff70-4004-94d2-eba20787be6b-c000,dst=/testspark/test_spark10_1/part-00004-6edb2d01-ff70-4004-94d2-eba20787be6b-c000,options=commonOptions {
  syncIntervalMs: -1
  ttl: -1
  ttlAction: DELETE
  operationId {
    mostSignificantBits: 1383106037916254646
    leastSignificantBits: -8060908434265153628
  }
}
persist: false
) returned  in 10912 ms (>=10000 ms)
`
**and next, the follow error log doesn't stop, it report again and again, I have to kill the spark job: **
`23/04/17 20:11:45 WARN FileSystemMasterClient: Rename(src=/testspark/test_spark10_1/.hive-staging_hive_2023-04-17_19-21-49_378_1196559485505624773-1/-ext-10000/part-00026-6edb2d01-ff70-4004-94d2-eba20787be6b-c000,dst=/testspark/test_spark10_1/part-00026-6edb2d01-ff70-4004-94d2-eba20787be6b-c000,options=commonOptions`

and the alluxio reports error again and again: 
`2023-04-17 12:47:44,801 INFO  DefaultFileSystemMaster - Updating inode 'part-04964-6edb2d01-ff70-4004-94d2-eba20787be6b-c000' mode bits from rw-r--r-- to rwxrwxrwx
2023-04-17 12:47:44,801 WARN  DefaultFileSystemMaster - setOwner/setMode is not supported to object storage UFS via Alluxio. UFS: s3://alluxiotest/s3b/testspark/test_spark10_1/part-04964-6edb2d01-ff70-4004-94d2-eba20787be6b-c000. This has no effect on the underlying object.
2023-04-17 12:48:09,456 WARN  UnderFileSystemWithLogging - RenameRenamableFile(src=s3://alluxiotest/s3b/testspark/test_spark10_1/.hive-staging_hive_2023-04-17_19-21-49_378_1196559485505624773-1/-ext-10000/part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000, dst=s3://alluxiotest/s3b/testspark/test_spark10_1/part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000) returned OK in 48403 ms (>=10000 ms)
2023-04-17 12:48:09,461 INFO  DefaultFileSystemMaster - Updating inode 'part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000' mode bits from rw-r--r-- to rwxrwxrwx
2023-04-17 12:48:09,461 WARN  DefaultFileSystemMaster - setOwner/setMode is not supported to object storage UFS via Alluxio. UFS: s3://alluxiotest/s3b/testspark/test_spark10_1/part-04948-6edb2d01-ff70-4004-94d2-eba20787be6b-c000. This has no effect on the underlying object.`

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
I don't konw

**Are you planning to fix it**
no, I need help

**Additional context**
I don't konw

**Comment by huanghua78** [comment]
Thank you @lingchuanzhou for reporting this issue.
Alluxio engineers will verify and investigate this issue.

**Comment by huanghua78** [comment]
@jiacheliu3 Can you please take a look at this issue?

**Comment by lingchuanzhou** [comment]
> 

thank you very much!

**Comment by lingchuanzhou** [comment]
`23/04/17 22:17:43 INFO SessionState: Could not get hdfsEncryptionShim, it is only applicable to hdfs filesystem.
23/04/17 22:17:43 INFO SessionState: Could not get hdfsEncryptionShim, it is only applicable to hdfs filesystem.
`
attention the above error log， it's api bug?

**Comment by lingchuanzhou** [comment]
@huanghua78 how about the progress? there is nobody sovle? it's really very hurry. thanks~!

**Comment by huanghua78** [comment]
> @huanghua78 how about the progress? there is nobody sovle? it's really very hurry. thanks~! @jiacheliu3

Alluxio Engineers are investigating this issue.

**Comment by yyongycy** [comment]
alluxio is printing the warning, that is expected. Is that rename or setOwner triggered by the spark job? Could you please enable the debug log and see if the spark job continuously calls alluxio?

**Comment by lingchuanzhou** [comment]
the debug option does'nt work! I have enable it 'true'.
