### ISSUE TITLE
Failed to start job worker

### ISSUE THREAD

**Issue by jffree** [Alluxio/alluxio#17344]
**Alluxio Version:**
2.9.3

**Describe the bug**
Failed to start job worker
```
2023-04-27 21:22:48,564 ERROR [main](ProcessUtils.java:76) - Uncaught exception while running Alluxio job worker, stopping it and exiting. Exception "alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc
▽
.job.JobMasterWorkerService/RegisterJobWorker.", Root Cause "io.grpc.StatusRuntimeException: UNAUTHENTICATED: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker."
alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:500)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:450)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:439)
	at alluxio.worker.job.RetryHandlingJobMasterClient.registerWorker(RetryHandlingJobMasterClient.java:75)
	at alluxio.worker.JobWorkerIdRegistry.registerWorker(JobWorkerIdRegistry.java:49)
	at alluxio.worker.JobWorker.start(JobWorker.java:97)
	at alluxio.worker.AlluxioJobWorkerProcess.startWorkers(AlluxioJobWorkerProcess.java:236)

▽
	at alluxio.worker.AlluxioJobWorkerProcess.start(AlluxioJobWorkerProcess.java:163)
	at alluxio.ProcessUtils.run(ProcessUtils.java:69)
	at alluxio.worker.AlluxioJobWorker.main(AlluxioJobWorker.java:85)
Caused by: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:147)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:215)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:486)
	... 9 more
Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at alluxio.grpc.JobMasterWorkerServiceGrpc$JobMasterWorkerServiceBlockingStub.registerJobWorker(JobMasterWorkerServiceGrpc.java:256)
	at alluxio.worker.job.RetryHandlingJobMasterClient.lambda$registerWorker$0(RetryHandlingJobMasterClient.java:75)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:484)
	... 9 more
````

* config info
```
alluxio.master.rpc.addresses=172.21.139.130:19998,172.21.139.171:19998,172.21.139.172:19998
alluxio.job.master.rpc.addresses=172.21.139.130:20001,172.21.139.171:20001,172.21.139.172:20001
# Common properties
alluxio.network.ip.address.used=true

# Security properties
alluxio.security.authentication.type=NOSASL
alluxio.security.authorization.permission.enabled=false

# Job Worker properties
alluxio.worker.hostname=172.21.139.194
alluxio.job.worker.web.port=10002
```

**Comment by LuQQiu** [comment]
@jja725 did you see similar exception before?
UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.

@jffree can you try alluxio.security.authentication.type=SIMPLE?

**Comment by jffree** [comment]
@LuQQiu 
more debug log:
```
023-04-27 22:36:15,688 DEBUG [alluxio-client-netty-event-loop-RPC-9](AbstractInternalLogger.java:214) - [id: 0x4354f4dd, L:/172.21.139.194:46418 - R:172.21.139.172/172.21.139.172:20001] OUTBOUND RST_STREAM: streamId=3 errorCode=8
2023-04-27 22:36:15,689 DEBUG [main](AbstractClient.java:326) - Disconnecting from the JobMasterWorker @ GrpcServerAddress{HostName=172.21.139.172, SocketAddress=172.21.139.172:20001}
2023-04-27 22:36:15,689 DEBUG [main](GrpcChannelPool.java:138) - Releasing connection for: GrpcChannelKey{NetworkGroup=RPC, ServerAddress=GrpcServerAddress{HostName=172.21.139.172, SocketAddress=172.21.139.172:20001}, GroupIndex=0, ChannelId=439397a8-69ed-4510-8387-3a70485dc2af}. Ref-count: 1
2023-04-27 22:36:15,689 DEBUG [main](GrpcChannelPool.java:141) - Shutting down connection after: GrpcChannelKey{NetworkGroup=RPC, ServerAddress=GrpcServerAddress{HostName=172.21.139.172, SocketAddress=172.21.139.172:20001}, GroupIndex=0, ChannelId=439397a8-69ed-4510-8387-3a70485dc2af}
2023-04-27 22:36:15,689 DEBUG [alluxio-client-netty-event-loop-RPC-9](AbstractInternalLogger.java:214) - [id: 0x4354f4dd, L:/172.21.139.194:46418 - R:172.21.139.172/172.21.139.172:20001] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
2023-04-27 22:36:15,689 DEBUG [main](GrpcChannelPool.java:304) - Releasing event-loop for: GrpcChannelKey{NetworkGroup=RPC, ServerAddress=GrpcServerAddress{HostName=172.21.139.172, SocketAddress=172.21.139.172:20001}, GroupIndex=0, ChannelId=439397a8-69ed-4510-8387-3a70485dc2af}. Ref-count: 2
2023-04-27 22:36:15,690 DEBUG [main](AbstractClient.java:465) - Exit (ERROR): RegisterWorker(address=WorkerNetAddress{host=172.21.139.194, containerHost=, rpcPort=30001, dataPort=30002, webPort=10002, domainSocketPath=, tieredIdentity=null}) in 120017 ms: alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
2023-04-27 22:36:15,690 WARN  [main](AbstractClient.java:468) - RegisterWorker(address=WorkerNetAddress{host=172.21.139.194, containerHost=, rpcPort=30001, dataPort=30002, webPort=10002, domainSocketPath=, tieredIdentity=null}) exits with exception [alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.] in 120017 ms (>=10000ms)
2023-04-27 22:36:15,691 ERROR [main](ProcessUtils.java:76) - Uncaught exception while running Alluxio job worker, stopping it and exiting. Exception "alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.", Root Cause "io.grpc.StatusRuntimeException: UNAUTHENTICATED: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker."
alluxio.exception.status.UnavailableException: Failed after 44 attempts: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
    at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:500)
    at alluxio.AbstractClient.retryRPC(AbstractClient.java:450)
    at alluxio.AbstractClient.retryRPC(AbstractClient.java:439)
    at alluxio.worker.job.RetryHandlingJobMasterClient.registerWorker(RetryHandlingJobMasterClient.java:75)
    at alluxio.worker.JobWorkerIdRegistry.registerWorker(JobWorkerIdRegistry.java:49)
    at alluxio.worker.JobWorker.start(JobWorker.java:97)
    at alluxio.worker.AlluxioJobWorkerProcess.startWorkers(AlluxioJobWorkerProcess.java:236)
    at alluxio.worker.AlluxioJobWorkerProcess.start(AlluxioJobWorkerProcess.java:163)
    at alluxio.ProcessUtils.run(ProcessUtils.java:69)
    at alluxio.worker.AlluxioJobWorker.main(AlluxioJobWorker.java:85)
Caused by: alluxio.exception.status.UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
    at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:147)
    at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:215)
    at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:486)
    ... 9 more
Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
    at alluxio.grpc.JobMasterWorkerServiceGrpc$JobMasterWorkerServiceBlockingStub.registerJobWorker(JobMasterWorkerServiceGrpc.java:256)
    at alluxio.worker.job.RetryHandlingJobMasterClient.lambda$registerWorker$0(RetryHandlingJobMasterClient.java:75)
    at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:484)
    ... 9 more
2023-04-27 22:36:15,691 INFO  [main](AlluxioJobWorkerProcess.java:216) - Stopping RPC server on Alluxio job worker @ 172.21.139.194:30001
```

**Comment by jffree** [comment]
> @jja725 did you see similar exception before? UnauthenticatedException: Channel Id is missing for call: alluxio.grpc.job.JobMasterWorkerService/RegisterJobWorker.
> 
> @jffree can you try alluxio.security.authentication.type=SIMPLE?

Keep same configuration `alluxio.security.authentication.type=NOSASL`  in job_master and job_worker is ok!
Thank you! @LuQQiu
