### ISSUE TITLE
Alluxio master throw error and exit when run alluxio unmount

### ISSUE THREAD

**Issue by tiandongtao** [Alluxio/alluxio#17389]
**Alluxio Version:**
2.9.0

**Describe the bug**
When run the command bin/alluxio unmount  /xxx  Alluxio master throw error:
```
2023-05-05 17:23:04,214 INFO  ActiveSyncManager - Stop sync for mount id 8861111814001451601
2023-05-05 17:23:04,214 INFO  MountTable - Unmounting /xxx
2023-05-05 17:23:04,268 INFO  ActiveSyncManager - SyncPoint stopped /xxx
2023-05-05 17:23:04,277 ERROR ActiveSyncManager - Fatal error: Failed to apply syncpoint_path: "/xxx"
mount_id: 1

java.lang.RuntimeException: mountId for the syncPoint /xxx not found in the filterMap
        at alluxio.master.file.activesync.ActiveSyncManager.apply(ActiveSyncManager.java:502)
        at alluxio.master.file.activesync.ActiveSyncManager.applyAndJournal(ActiveSyncManager.java:296)
        at alluxio.master.file.activesync.ActiveSyncManager.stopSyncAndJournal(ActiveSyncManager.java:381)
        at alluxio.master.file.DefaultFileSystemMaster.deleteInternal(DefaultFileSystemMaster.java:2246)
        at alluxio.master.file.DefaultFileSystemMaster.unmountInternal(DefaultFileSystemMaster.java:3450)
        at alluxio.master.file.DefaultFileSystemMaster.unmount(DefaultFileSystemMaster.java:3413)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$unmount$23(FileSystemMasterClientServiceHandler.java:419)
        at alluxio.RpcUtils.callAndReturn(RpcUtils.java:125)
        at alluxio.RpcUtils.call(RpcUtils.java:86)
        at alluxio.RpcUtils.call(RpcUtils.java:61)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.unmount(FileSystemMasterClientServiceHandler.java:418)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2610)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:57)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2023-05-05 17:23:04,277 INFO  AlluxioMasterProcess - Stopping...
2023-05-05 17:23:04,286 INFO  BackupLeaderRole - Closing backup-leader role

```

**Additional context**
Alluxio master and worker use default config

**Comment by JiamingMai** [comment]
Which Under File System are you using?

**Comment by tiandongtao** [comment]
> Which Under File System are you using?

hdfs

**Comment by fuzhengjia** [comment]
We will look into this active sync issue.
