### ISSUE TITLE
Spark stores data to minio through alloxio and reports an error

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [Alluxio/alluxio#17576]
**Alluxio Version:**
2.9.3

**Describe the bug**
Spark stores data to minio through alloxio and reports an error.

**To Reproduce**
Build a Spark environment based on k8s and use HMS for metadata services. Create a table and see an error in the Spark UI when writing data.

**Expected behavior**
Write data without errors.

**Urgency**
The impact is currently unknown and the data is being verified.

**Are you planning to fix it**
I don't know how to fix it.

**Additional context**
[error.log](https://github.com/Alluxio/alluxio/files/11686119/error.log)

**Comment by LoseYSelf** [comment]
may be you can set WriteType as THROUGH

**Comment by jiacheliu3** [comment]
your exception looks as follows, I don't think I can tell what the reason is. The client cannot talk to the worker, maybe the network between client and worker is simply not working.

```
Caused by: alluxio.exception.status.UnavailableException: Network closed for unknown reason (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 692009828352
tier: 0
medium_type: ""
pin_on_create: true
space_to_reserve: 67108864
, address=WorkerNetAddress{host=XX.XXX.XXX.XXX, containerHost=172.22.75.12, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/1debe8aa-3933-4a52-bc6d-22a57e01e0e2, tieredIdentity=TieredIdentity(node=10.0.104.217, rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:156)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:317)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:298)
	at alluxio.client.block.stream.GrpcBlockingStream.send(GrpcBlockingStream.java:105)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.sendDataMessage(GrpcDataMessageBlockingStream.java:104)
	at alluxio.client.block.stream.GrpcDataWriter.writeChunk(GrpcDataWriter.java:199)
	at alluxio.client.block.stream.BlockOutStream.updateCurrentChunk(BlockOutStream.java:262)
	at alluxio.client.block.stream.BlockOutStream.write(BlockOutStream.java:141)
	at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:271)
	... 29 more
```

Please double check the worker network addr `address=WorkerNetAddress{host=10.0.104.217, containerHost=172.22.75.12, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=/opt/domain/1debe8aa-3933-4a52-bc6d-22a57e01e0e2, tieredIdentity=TieredIdentity(node=10.0.104.217, rack=null)}})`. Can your client talk to this address? Did the worker pod simply die?
