### ISSUE TITLE
deploy CSI  read and write error with mountInPod false

### ISSUE THREAD

**Issue by syang1997** [Alluxio/alluxio#17739]
**Alluxio Version:**
2.9.3

**Describe the bug**
I deployed alluxio as helm in K8s and there was a problem verifying to csi. When I am running in the configuration of mountInPod:false.
You can view the file path in pod but read and write the file incorrectly. The same configuration can be written correctly with mountInPod:true.

chart config.yaml

```
user: 0
group: 0
fsGroup: 0
properties:
  alluxio.security.login.username: alluxio
  alluxio.master.mount.table.root.ufs: "s3a://dev"
  alluxio.underfs.s3.endpoint: http://xxx:9000/
  alluxio.master.mount.table.root.option.s3a.accessKeyId: "xxx"
  alluxio.master.mount.table.root.option.s3a.secretKey: "xxx"
shortCircuit:
  enabled: false
csi:
  mountInPod: false
  enabled: true
  clientEnabled: true
```
It's the same problem if it's not in the user:0 way.

test pod yaml 

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: alluxio-pvc
  volumes:
    - name: alluxio-pvc
      persistentVolumeClaim:
        claimName: alluxio-pvc
```

test shell

```
/data/test2 # 
/data/test2 # ls
/data/test2 # echo 333 > test.txt
sh: write error: I/O error
/data/test2 # 
/data/test2 # 
/data/test2 # ls
test.txt
/data/test2 # cat test.txt 
cat: read error: File descriptor in bad state
/data/test2 #
```

csi-nodeserver fuse log

```
2023-07-06 03:07:00,951 INFO  [main](AlluxioFuse.java:156) - Alluxio version: 2.9.3-44b59ac84b0bcef9b268a81481d08da96dc27d58
2023-07-06 03:07:01,183 INFO  [main](AlluxioFuse.java:322) - Set fuse mount point options as direct_io,allow_other,entry_timeout=36000,attr_timeout=36000,max_readahead=0 from command line input
2023-07-06 03:07:01,191 INFO  [main](FuseOptions.java:83) - Added fuse mount option big_writes to enlarge single write request size
2023-07-06 03:07:01,272 INFO  [main](MetricsSystem.java:265) - Starting sinks with config: {}.
2023-07-06 03:07:01,279 INFO  [main](MetricsHeartbeatContext.java:169) - Created metrics heartbeat with ID app-5099297118374418685. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
2023-07-06 03:07:01,391 INFO  [main](NettyUtils.java:146) - EPOLL_MODE is available
2023-07-06 03:07:01,739 WARN  [main](InstancedConfiguration.java:381) - alluxio.user.ufs.block.read.location.policy.cache.size is deprecated. Please avoid using this key in the future. CapacityBaseRandomPolicy no longer caches block locations. To make sure a block is always assigned to the same worker, use DeterministicHashPolicy.
2023-07-06 03:07:01,739 WARN  [main](InstancedConfiguration.java:381) - alluxio.user.ufs.block.read.location.policy.cache.expiration.time is deprecated. Please avoid using this key in the future. CapacityBaseRandomPolicy no longer caches block locations. To make sure a block is always assigned to the same worker, use DeterministicHashPolicy.
2023-07-06 03:07:01,751 INFO  [main](TieredIdentityFactory.java:62) - Initialized tiered identity TieredIdentity(node=10.202.4.135, rack=null)
2023-07-06 03:07:01,757 INFO  [main](NativeLibraryLoader.java:232) - Loaded lib by jar from path /tmp/libjnifuse6616908211779542306.so.
2023-07-06 03:07:01,757 INFO  [main](NativeLibraryLoader.java:145) - Loaded libjnifuse with libfuse version 2.
2023-07-06 03:07:01,899 INFO  [main](Reflections.java:239) - Reflections took 108 ms to scan 1 urls, producing 65 keys and 223 values 
2023-07-06 03:07:01,926 INFO  [main](LaunchUserGroupAuthPolicy.java:93) - Initialized Fuse auth policy with launch user (id:0) and group (id:0)
2023-07-06 03:07:01,928 INFO  [main](AlluxioFuse.java:232) - Mounting AlluxioJniFuseFileSystem: mount point="/var/lib/kubelet/pods/1e02309b-3772-4193-821c-005246aca324/volumes/kubernetes.io~csi/alluxio-a8768861-4d7b-4819-97fc-1a8904f4a38a/mount", OPTIONS="max_readahead=0,entry_timeout=36000,direct_io,allow_other,big_writes,attr_timeout=36000"
2023-07-06 03:07:01,929 INFO  [main](AbstractFuseFileSystem.java:75) - Mounting /var/lib/kubelet/pods/1e02309b-3772-4193-821c-005246aca324/volumes/kubernetes.io~csi/alluxio-a8768861-4d7b-4819-97fc-1a8904f4a38a/mount: blocking=true, debug=false, fuseOpts="max_readahead=0,entry_timeout=36000,direct_io,allow_other,big_writes,attr_timeout=36000"
2023-07-06 03:07:11,294 WARN  [metrics-master-heartbeat-0](InstancedConfiguration.java:381) - alluxio.user.ufs.block.read.location.policy.cache.size is deprecated. Please avoid using this key in the future. CapacityBaseRandomPolicy no longer caches block locations. To make sure a block is always assigned to the same worker, use DeterministicHashPolicy.
2023-07-06 03:07:11,296 WARN  [metrics-master-heartbeat-0](InstancedConfiguration.java:381) - alluxio.user.ufs.block.read.location.policy.cache.expiration.time is deprecated. Please avoid using this key in the future. CapacityBaseRandomPolicy no longer caches block locations. To make sure a block is always assigned to the same worker, use DeterministicHashPolicy.
2023-07-06 03:07:39,887 ERROR [Thread-4](AlluxioJniFuseFileSystem.java:247) - File /test2/test.txt is not completed, cannot get accurate file length
2023-07-06 03:07:44,900 ERROR [Thread-5](AlluxioJniFuseFileSystem.java:247) - File /test2/test2.txt is not completed, cannot get accurate file length
2023-07-06 03:07:49,912 ERROR [Thread-6](AlluxioJniFuseFileSystem.java:247) - File /test2/test3.txt is not completed, cannot get accurate file length
2023-07-06 03:08:22,477 WARN  [Thread-5](AlluxioFileOutStream.java:322) - Failed to write into AlluxioStore, canceling write attempt.
alluxio.exception.runtime.NotFoundRuntimeException: wrong path when creating RandomAccessFile
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:56)
        at alluxio.client.block.stream.LocalFileDataWriter.create(LocalFileDataWriter.java:105)
        at alluxio.client.block.stream.DataWriter$Factory.create(DataWriter.java:87)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:288)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:332)
        at alluxio.client.file.AlluxioFileOutStream.getNextBlock(AlluxioFileOutStream.java:309)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:275)
        at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:237)
        at alluxio.fuse.file.FuseFileOutStream.write(FuseFileOutStream.java:162)
        at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:331)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$8(AlluxioJniFuseFileSystem.java:318)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:642)
        at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:318)
        at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:340)
Caused by: java.io.FileNotFoundException: /dev/shm/alluxioworker/.tmp_blocks/125/4e9185c1d410b87d-352673857536 (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:54)
        ... 13 more
2023-07-06 03:08:22,484 ERROR [Thread-5](AlluxioFuseUtils.java:664) - Failed to Fuse.Write(path=/test2/test.txt,fd=0,size=4,offset=0) with unexpected throwable: 
alluxio.exception.runtime.UnknownRuntimeException: Failed to cache: wrong path when creating RandomAccessFile
        at alluxio.exception.runtime.AlluxioRuntimeException.from(AlluxioRuntimeException.java:192)
        at alluxio.fuse.file.FuseFileOutStream.write(FuseFileOutStream.java:164)
        at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:331)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$8(AlluxioJniFuseFileSystem.java:318)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:642)
        at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:318)
        at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:340)
Caused by: java.io.IOException: Failed to cache: wrong path when creating RandomAccessFile
        at alluxio.client.file.AlluxioFileOutStream.handleCacheWriteException(AlluxioFileOutStream.java:325)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:288)
        at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:237)
        at alluxio.fuse.file.FuseFileOutStream.write(FuseFileOutStream.java:162)
        ... 5 more
Caused by: alluxio.exception.runtime.NotFoundRuntimeException: wrong path when creating RandomAccessFile
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:56)
        at alluxio.client.block.stream.LocalFileDataWriter.create(LocalFileDataWriter.java:105)
        at alluxio.client.block.stream.DataWriter$Factory.create(DataWriter.java:87)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:288)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:332)
        at alluxio.client.file.AlluxioFileOutStream.getNextBlock(AlluxioFileOutStream.java:309)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:275)
        ... 7 more
Caused by: java.io.FileNotFoundException: /dev/shm/alluxioworker/.tmp_blocks/125/4e9185c1d410b87d-352673857536 (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:54)
        ... 13 more
2023-07-06 03:08:30,401 ERROR [Thread-5](AlluxioJniFuseFileSystem.java:247) - File /test2/test.txt is not completed, cannot get accurate file length
2023-07-06 03:08:40,008 ERROR [Thread-4](AlluxioJniFuseFileSystem.java:193) - Failed to create stream /test2/test.txt: operation does not supported
alluxio.exception.runtime.UnimplementedRuntimeException: Failed to create fuse file in stream for /test2/test.txt: file is being written
        at alluxio.fuse.file.FuseFileInStream.create(FuseFileInStream.java:70)
        at alluxio.fuse.file.FuseFileStream$Factory.create(FuseFileStream.java:106)
        at alluxio.fuse.AlluxioJniFuseFileSystem.createOrOpenInternal(AlluxioJniFuseFileSystem.java:176)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$open$1(AlluxioJniFuseFileSystem.java:165)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:642)
        at alluxio.fuse.AlluxioJniFuseFileSystem.open(AlluxioJniFuseFileSystem.java:164)
        at alluxio.jnifuse.AbstractFuseFileSystem.openCallback(AbstractFuseFileSystem.java:185)
2023-07-06 03:08:40,009 ERROR [Thread-5](AlluxioJniFuseFileSystem.java:304) - Failed to read /test2/test.txt: Cannot find fd 0
2023-07-06 03:08:40,009 ERROR [Thread-6](AlluxioJniFuseFileSystem.java:304) - Failed to read /test2/test.txt: Cannot find fd 0
2023-07-06 03:08:40,009 ERROR [Thread-4](AlluxioJniFuseFileSystem.java:352) - Failed to flush /test2/test.txt: Cannot find fd 0
```

**To Reproduce**

**Expected behavior**
pvc file can read and write normally

**Comment by syang1997** [comment]
In addition, both fuse and mountInPod:true can be used independently to read and write data. This shows that the master and worker of alluxio are normal, and so is S3.

**Comment by syang1997** [comment]
I found this message in the log.
Caused by: java.io.FileNotFoundException: /dev/shm/alluxioworker/.tmp_blocks/125/4e9185c1d410b87d-352673857536 (No such file or directory)

I went to the corresponding worker container found that the file path looks like `/dev/shm/alluxioworker/.tmp_blocks/125`
That is to say, the last path is missing.

**Comment by ssz1997** [comment]
@syang1997 Running AlluxioFuse in its own pod is strictly better than running Alluxio inside the nodeserver container. They do the same thing and the lifecycle are separated. Is there a particular reason you want to make sure running AlluxioFuse in nodeserver container works? If not I would suggest just set the value to true.

**Comment by syang1997** [comment]
> @syang1997 Running AlluxioFuse in its own pod is strictly better than running Alluxio inside the nodeserver container. They do the same thing and the lifecycle are separated. Is there a particular reason you want to make sure running AlluxioFuse in nodeserver container works? If not I would suggest just set the value to true.

Both modes want to be used together, using mountInPod:false  sc with less read and write requirements, which can reduce the use of resources. Use mountInPod:true sc with high reading and writing requirements, so as to have an independent lifecycle.

**Comment by syang1997** [comment]
@ssz1997 I uninstalled alluxio. The bucket (minio) of ufs has been deleted. Then the bucket and alluxio are rebuilt. There is still a mistake.

```
2023-07-12 03:02:01,261 ERROR [Thread-5](AlluxioJniFuseFileSystem.java:285) - Failed to readdir /
alluxio.exception.InvalidPathException: 400 Bad Request:Bad Request
        at alluxio.client.file.BaseFileSystem.wrapAndThrowAlluxioStatusException(BaseFileSystem.java:640)
        at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:626)
        at alluxio.client.file.BaseFileSystem.iterateStatus(BaseFileSystem.java:303)
        at alluxio.client.file.FileSystem.iterateStatus(FileSystem.java:415)
        at alluxio.fuse.AlluxioJniFuseFileSystem.readdirInternal(AlluxioJniFuseFileSystem.java:281)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$readdir$5(AlluxioJniFuseFileSystem.java:265)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:642)
        at alluxio.fuse.AlluxioJniFuseFileSystem.readdir(AlluxioJniFuseFileSystem.java:265)
        at alluxio.jnifuse.AbstractFuseFileSystem.readdirCallback(AbstractFuseFileSystem.java:213)
2023-07-12 03:02:16,362 WARN  [Thread-4](AlluxioFileOutStream.java:322) - Failed to write into AlluxioStore, canceling write attempt.
alluxio.exception.runtime.NotFoundRuntimeException: wrong path when creating RandomAccessFile
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:56)
        at alluxio.client.block.stream.LocalFileDataWriter.create(LocalFileDataWriter.java:105)
        at alluxio.client.block.stream.DataWriter$Factory.create(DataWriter.java:87)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:288)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:332)
        at alluxio.client.file.AlluxioFileOutStream.getNextBlock(AlluxioFileOutStream.java:309)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:275)
        at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:237)
        at alluxio.fuse.file.FuseFileOutStream.write(FuseFileOutStream.java:162)
        at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:331)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$8(AlluxioJniFuseFileSystem.java:318)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:642)
        at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:318)
        at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:340)
Caused by: java.io.FileNotFoundException: /dev/shm/alluxioworker/.tmp_blocks/989/87c4fa818359bdd-16777216 (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:54)
        ... 13 more
2023-07-12 03:02:16,369 ERROR [Thread-4](AlluxioFuseUtils.java:664) - Failed to Fuse.Write(path=/test.txt,fd=0,size=4,offset=0) with unexpected throwable: 
alluxio.exception.runtime.UnknownRuntimeException: Failed to cache: wrong path when creating RandomAccessFile
        at alluxio.exception.runtime.AlluxioRuntimeException.from(AlluxioRuntimeException.java:192)
        at alluxio.fuse.file.FuseFileOutStream.write(FuseFileOutStream.java:164)
        at alluxio.fuse.AlluxioJniFuseFileSystem.writeInternal(AlluxioJniFuseFileSystem.java:331)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$write$8(AlluxioJniFuseFileSystem.java:318)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:642)
        at alluxio.fuse.AlluxioJniFuseFileSystem.write(AlluxioJniFuseFileSystem.java:318)
        at alluxio.jnifuse.AbstractFuseFileSystem.writeCallback(AbstractFuseFileSystem.java:340)
Caused by: java.io.IOException: Failed to cache: wrong path when creating RandomAccessFile
        at alluxio.client.file.AlluxioFileOutStream.handleCacheWriteException(AlluxioFileOutStream.java:325)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:288)
        at alluxio.client.file.AlluxioFileOutStream.write(AlluxioFileOutStream.java:237)
        at alluxio.fuse.file.FuseFileOutStream.write(FuseFileOutStream.java:162)
        ... 5 more
Caused by: alluxio.exception.runtime.NotFoundRuntimeException: wrong path when creating RandomAccessFile
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:56)
        at alluxio.client.block.stream.LocalFileDataWriter.create(LocalFileDataWriter.java:105)
        at alluxio.client.block.stream.DataWriter$Factory.create(DataWriter.java:87)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:288)
        at alluxio.client.block.BlockStoreClient.getOutStream(BlockStoreClient.java:332)
        at alluxio.client.file.AlluxioFileOutStream.getNextBlock(AlluxioFileOutStream.java:309)
        at alluxio.client.file.AlluxioFileOutStream.writeInternal(AlluxioFileOutStream.java:275)
        ... 7 more
Caused by: java.io.FileNotFoundException: /dev/shm/alluxioworker/.tmp_blocks/989/87c4fa818359bdd-16777216 (No such file or directory)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
        at alluxio.worker.block.io.LocalFileBlockWriter.<init>(LocalFileBlockWriter.java:54)
        ... 13 more
2023-07-12 03:09:01,408 WARN  [BlockWorkerClientPoolGcThreads-0](GrpcChannelPool.java:251) - Timed out gracefully shutting down connection: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=9, target=ip-10-202-4-239.us-west-2.compute.internal:29999}}. 
2023-07-12 03:09:01,410 WARN  [grpc-default-executor-4](GrpcBlockingStream.java:333) - Received error on stream (LocalFileDataWriter{request=block_id: 16777216
tier: 0
space_to_reserve: 67108864
medium_type: ""
pin_on_create: true
, address=WorkerNetAddress{host=10.202.4.135, containerHost=10.202.4.239, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=10.202.4.135, rack=null)}})
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at alluxio.grpc.GrpcChannel$1$1$1.onClose(GrpcChannel.java:160)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by ssz1997** [comment]
@syang1997 Thanks. The setup happens to trigger alluxio shortCircuit, which is actually not applicable. Recommend set `.shortCircuit.enabled` in your helm chart configuration file to `false`.

**Comment by syang1997** [comment]
> Thanks. The setup happens to trigger alluxio shortCircuit, which is actually not applicable. Recommend set `.shortCircuit.enabled` in your helm chart configuration file to `false`.

This is shown in the issue configuration. I didn't open the shortCircuit.
```yaml
user: 0
group: 0
fsGroup: 0
properties:
  alluxio.security.login.username: alluxio
  alluxio.master.mount.table.root.ufs: "s3a://dev"
  alluxio.underfs.s3.endpoint: http://xxx:9000/
  alluxio.master.mount.table.root.option.s3a.accessKeyId: "xxx"
  alluxio.master.mount.table.root.option.s3a.secretKey: "xxx"
shortCircuit:
  enabled: false
csi:
  mountInPod: false
  enabled: true
  clientEnabled: true
```
