### ISSUE TITLE
alluxio integration with flink throw error

### ISSUE THREAD

**Issue by qingyuan18** [Alluxio/alluxio#17754]
**Alluxio Version:**
2.7.3

**Describe the bug**
allluxio integrated with flink throws error when using flink sql write into alluxio backend table
Caused by: java.lang.IllegalArgumentException: cannot find a NameResolver for ip-172-31-19-175.ap-southeast-1.compute.internal:19998
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:763) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:772) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:652) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.shaded.client.io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:615) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.shaded.client.io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.grpc.GrpcConnectionPool.createManagedChannel(GrpcConnectionPool.java:191) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.grpc.GrpcConnectionPool.lambda$acquireConnection$0(GrpcConnectionPool.java:129) ~[alluxio-2.7.3-client.jar:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853) ~[?:1.8.0_372]
	at alluxio.grpc.GrpcConnectionPool.acquireConnection(GrpcConnectionPool.java:101) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.grpc.GrpcChannelBuilder.build(GrpcChannelBuilder.java:121) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.util.ConfigurationUtils.loadConfiguration(ConfigurationUtils.java:512) ~[alluxio-2.7.3-client.jar:?]
	at alluxio.ClientContext.loadConf(ClientContext.java:134) ~[alluxio-2.7.3-client.jar:?]

**To Reproduce**
1: write alluxio client jar into hadoop classpath: 
sudo ln -s "${ALLUXIO_HOME}/client/alluxio-client.jar" /usr/lib/hadoop/lib/alluxio-client.jar

2: add alluxio config into flink's  yaml property
env.java.opts: -Djava.io.tmpdir=/mnt/tmp -Dalluxio.master.web.port=29999 -Dalluxio.user.file.writetype.default=CACHE_THROUGH
 -Dalluxio.master.hostname=ip-172-31-19-175.ap-southeast-1.compute.internal
 -Dalluxio.master.mount.table.root.ufs=s3://salunchbucket/data/alluxio/
 -Dalluxio.master.security.impersonation.hive.users=*
 -Dalluxio.master.security.impersonation.presto.users=*
 -Dalluxio.master.security.impersonation.trino.users=*
 -Dalluxio.master.security.impersonation.hadoop.users=*
 -Dalluxio.master.security.impersonation.yarn.users=*  

3: run flink sql to write into alluxio table 
	CREATE TABLE logevent_sink_test(`timestamp` STRING,

	`system` string,

	actor string,

	action STRING

	) PARTITIONED BY (`system`) WITH (

	'connector' = 'hudi',

	'path' = 'alluxio:///1000/flink-hudi/logevent_sink_test/',

	'table.type' = 'MERGE_ON_READ', 
       .....

**Expected behavior**
write into alluxio cache and also sync to backend storage(s3) 

**Urgency**
sev3 -- impacted by customer's project

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by ChunxuTang** [comment]
Thanks for raising this issue.
@beinan Would you mind taking a look at this issue?

**Comment by beinan** [comment]
Looks like it's a network issue, is ip-172-31-19-175.ap-southeast-1.compute.internal reachable from you client?  or is it possible to try to connect with the ip of the master?  @qingyuan18

**Comment by qingyuan18** [comment]
hello @beinan 
Thanks for your support!   
the network is fine , we can telnet/ping the private dns from our client or the master/worker nodes , otherwise the alluxio cluster will fail when the alluxio worker trying to connect with the master

I saw the execption refers to the "cannot find a NameResolver" , does alluxio has any changes for the gRPC lib when shade reloaction during the maven packaging , or is there anything I missed for the alluxio+flink configuration?

also is there. any best practice for flink + alluxio integration？ I just follow the official alluxio website steps

**Comment by qingyuan18** [comment]
problem solved 
change into alluxio 2.9.3 version, the flink write alluxio path table works fine
