### ISSUE TITLE
Load data throws unknown exception in master

### ISSUE THREAD

**Issue by Haoning-Sun** [Alluxio/alluxio#18074]
**Alluxio Version:**
2.9.3

**Describe the bug**
use `fs loadmeta` and `fs load` to warmup alluxio cache;
loadmeta can be successfully completed but load data run failed;
```
Progress for loading path '/':
	Settings:	bandwidth: unlimited	verify: false
	Job State: RUNNING
	Files Processed: 10889213
	Bytes Loaded: 353.86GB
	Throughput: 244.67MB/s
	Block load failure rate: 0.20%
	Files Failed: 0
```
master error log
```
WARN  [scheduler](LoadJob.java:598) - exception when trying to get load response.
io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at alluxio.grpc.GrpcChannel$1$1$1.onClose(GrpcChannel.java:160)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Additional context**

- ufs fileCount: 10889213, fileSize 859.66 GB
- /cover contains 800,000 folders, each folder has about 10~20 pictures

**Comment by yyongycy** [comment]
Do you have more log of the client side and the related worker?

**Comment by jja725** [comment]
#18042 seems very similar dataset

**Comment by Haoning-Sun** [comment]
The UNKNOWN exception is caused by OutOfMemory during direct memory allocation:
1. The buffer created by allocating memory is pooled, the buffer is put into a treemap, and each time memory is requested the treemap calls ceilingEntry to find the smallest buffer that is greater than or equal to the desired value;
2. If load a large number of small files to create a large number of small buffer, resulting in large files encountered when the small buffer can not be reused, resulting in a waste of resources; if the existing buffer are not enough to meet the demand, then go to apply for new memory may be thrown OutOfMemory error;
3. Multiple tasks apply for buffers of similar size, the result set from the treemap may be the same, if these buffers are occupied, even if there is a larger free buffer can not be used to apply for new memory, then there may be thrown OutOfMemory error.

**Comment by jja725** [comment]
> The UNKNOWN exception is caused by OutOfMemory during direct memory allocation:
> 
> 1. The buffer created by allocating memory is pooled, the buffer is put into a treemap, and each time memory is requested the treemap calls ceilingEntry to find the smallest buffer that is greater than or equal to the desired value;
> 2. If load a large number of small files to create a large number of small buffer, resulting in large files encountered when the small buffer can not be reused, resulting in a waste of resources; if the existing buffer are not enough to meet the demand, then go to apply for new memory may be thrown OutOfMemory error;
> 3. Multiple tasks apply for buffers of similar size, the result set from the treemap may be the same, if these buffers are occupied, even if there is a larger free buffer can not be used to apply for new memory, then there may be thrown OutOfMemory error.

Thanks for the explanation, could you elaborate more about the third point? Why there is a larger free buffer can not be used

**Comment by Haoning-Sun** [comment]
> > The UNKNOWN exception is caused by OutOfMemory during direct memory allocation:
> > 
> > 1. The buffer created by allocating memory is pooled, the buffer is put into a treemap, and each time memory is requested the treemap calls ceilingEntry to find the smallest buffer that is greater than or equal to the desired value;
> > 2. If load a large number of small files to create a large number of small buffer, resulting in large files encountered when the small buffer can not be reused, resulting in a waste of resources; if the existing buffer are not enough to meet the demand, then go to apply for new memory may be thrown OutOfMemory error;
> > 3. Multiple tasks apply for buffers of similar size, the result set from the treemap may be the same, if these buffers are occupied, even if there is a larger free buffer can not be used to apply for new memory, then there may be thrown OutOfMemory error.
> 
> Thanks for the explanation, seems like there's a lot of things we can improve for the buffer pool

I was going to improve this part too, but added the method to free buffer in order to solve the user's problem first.

**Comment by zhangty123321** [comment]
This one tries to use distributedLoad and in the case of a large number of files,unkown This exception can be resolved by attempting to restart the jobMaster
