### ISSUE TITLE
StatusRuntimeException: UNKNOWN   occurs  when  writting  data to Alluxio

### ISSUE THREAD

**Issue by 820678105** [Alluxio/alluxio#18102]
**Alluxio Version:**
What version of Alluxio are you using?
2.9.1
**Describe the bug**
when  using  spark or flink  to write file to  alluxio ,  UnknownException  occurs very frequently.
here is the log:

23/09/04 15:29:12 WARN TaskSetManager: Lost task 41.0 in stage 0.0 (TID 41) (10.244.85.129 executor 6): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:655)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:358)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$22(FileFormatWriter.scala:266)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: alluxio.exception.status.UnknownException: /data/alluxio/alluxioworker/.tmp_blocks/351 (GrpcDataWriter{request=type: ALLUXIO_BLOCK
id: 207270977732608
tier: 0
medium_type: ""
pin_on_create: true
space_to_reserve: 67108864
, address=WorkerNetAddress{host=10.72.1.107, containerHost=10.244.8.167, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=10.72.1.107, rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:174)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:303)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:284)
	at alluxio.client.block.stream.GrpcBlockingStream.send(GrpcBlockingStream.java:105)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.sendDataMessage(GrpcDataMessageBlockingStream.java:103)
	at alluxio.client.block.stream.GrpcDataWriter.writeChunk(GrpcDataWriter.java:190)
	at alluxio.client.block.stream.BlockOutStream.updateCurrentChunk(BlockOutStream.java:255)
	at alluxio.client.block.stream.BlockOutStream.close(BlockOutStream.java:216)
	at alluxio.client.file.AlluxioFileOutStream.close(AlluxioFileOutStream.java:186)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.parquet.hadoop.util.HadoopPositionOutputStream.close(HadoopPositionOutputStream.java:64)
	at org.apache.parquet.hadoop.ParquetFileWriter.end(ParquetFileWriter.java:1106)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:132)
	at org.apache.parquet.hadoop.ParquetRecordWriter.close(ParquetRecordWriter.java:164)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.close(ParquetOutputWriter.scala:41)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseCurrentWriter(FileFormatDataWriter.scala:64)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.releaseResources(FileFormatDataWriter.scala:75)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.commit(FileFormatDataWriter.scala:105)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:342)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1538)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:348)
	... 9 more
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: UNKNOWN: /data/alluxio/alluxioworker/.tmp_blocks/351
	at alluxio.shaded.client.io.grpc.Status.asRuntimeException(Status.java:535)
	at alluxio.shaded.client.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at alluxio.shaded.client.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at alluxio.shaded.client.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 3 more

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

**Comment by jja725** [comment]
Hi, thanks for raising the issue. Could you provide more alluxio logs so we can better root cause the problem?

**Comment by 820678105** [comment]
> Hi, thanks for raising the issue. Could you provide more alluxio logs so we can better root cause the problem?

the  Alluxio worker log as follows:
-------------------------------------------------------------------------------------------------------------
2023-09-06 01:46:11,565 WARN  AbstractWriteHandler - Exception occurred while processing write request command {
  type: ALLUXIO_BLOCK
  id: 215950334885888
  tier: 0
  medium_type: ""
  pin_on_create: true
  space_to_reserve: 67108864
}
.: alluxio.exception.runtime.UnknownRuntimeException: /data/alluxio/alluxioworker/.tmp_blocks/648
Sep 06, 2023 1:46:11 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable alluxio.worker.grpc.AbstractWriteHandler$$Lambda$228/1518934067@70af41c5
java.lang.NullPointerException
        at alluxio.worker.grpc.AbstractWriteHandler.replyError(AbstractWriteHandler.java:427)
        at alluxio.worker.grpc.AbstractWriteHandler.abort(AbstractWriteHandler.java:333)
        at alluxio.worker.grpc.AbstractWriteHandler.lambda$write$0(AbstractWriteHandler.java:149)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:159)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
--------------------------------------------------------------------------------
