### ISSUE TITLE
flink integretion with alluxio  occurs UNAUTHENTICATED exception per 3days 

### ISSUE THREAD

**Issue by xiaohu-liu** [Alluxio/alluxio#18332]
**Alluxio Version:**
2.9.3

**Describe the bug**
Use flink to write kafka data to the hive table. A task restart will occur every three days, causing a report Caused by: alluxio.exception.status.UnauthenticatedException: Channel: 78b62c86-6e51-4778-8bf4-1abb891f0612 is not authenticated for call: alluxio.grpc.block.BlockWorker/WriteBlock, causing some files to be in the complete=false state. The investigation found that the default value of the `alluxio.security.stale.channel.purge.interval` configuration in the configuration is 3 days. The analyst because of three Day triggers the channel mapping relationship in memory to be cleaned

**To Reproduce**
use flink kafka connector to read kafka topic and sink data to hive table in stream mode

**Expected behavior**
Caused by: alluxio.exception.status.UnauthenticatedException: Channel: 78b62c86-6e51-4778-8bf4-1abb891f0612 is not authenticated for call: alluxio.grpc.block.BlockWorker/WriteBlock (GrpcDataWriter{request=type: UFS_FILE
id: -1
tier: 0
create_ufs_file_options {
  ufs_path: "jfs://jfs-test/tmp/data/ods/xxxxx/table1/dt=2023-10-25/.part-cba745ab-a69f-40a5-a4d6-2feed8e01aa2-6-2702.inprogress.a2466996-a53e-4fd8-bd10-79419469a3b3"
  owner: "flink"
  group: "flink"
  mode: 438
  mount_id: 6796318440949522880
  acl {
    owningUser: "flink"
    owningGroup: "flink"
    userActions {
      name: ""
      actions {
        actions: READ
        actions: WRITE
      }
    }
    groupActions {
      name: ""
      actions {
        actions: READ
        actions: WRITE
      }
    }
    otherActions {
      actions: READ
      actions: WRITE
    }
    isDefault: false
    isEmpty: false
  }
}
medium_type: ""
pin_on_create: false
space_to_reserve: 67108864
, address=WorkerNetAddress{host=alluxio-05, containerHost=, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=alluxio-05, rack=null)}})
    at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:147)
    at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:310)
    at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:291)
    at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:209)
    at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receive(GrpcDataMessageBlockingStream.java:61)
    at alluxio.client.block.stream.GrpcBlockingStream.waitForComplete(GrpcBlockingStream.java:258)
    at alluxio.client.block.stream.GrpcDataMessageBlockingStream.waitForComplete(GrpcDataMessageBlockingStream.java:110)
    at alluxio.client.block.stream.GrpcDataWriter.close(GrpcDataWriter.java:264)
    at alluxio.shaded.client.com.google.common.io.Closer.close(Closer.java:218)
    at alluxio.client.block.stream.BlockOutStream.close(BlockOutStream.java:221)
    at alluxio.client.block.stream.UnderFileSystemFileOutStream.close(UnderFileSystemFileOutStream.java:70)
    at alluxio.client.file.AlluxioFileOutStream.close(AlluxioFileOutStream.java:171)
    at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
    at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
    at parquet.hadoop.ParquetFileWriter.end(ParquetFileWriter.java:400)
    at parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:117)
    at parquet.hadoop.ParquetRecordWriter.close(ParquetRecordWriter.java:112)
    at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.close(ParquetRecordWriterWrapper.java:102)
    at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.close(ParquetRecordWriterWrapper.java:119)
    at org.apache.flink.connectors.hive.write.HiveBulkWriterFactory$1.finish(HiveBulkWriterFactory.java:79)
    at org.apache.flink.formats.hadoop.bulk.HadoopPathBasedPartFileWriter.closeForCommit(HadoopPathBasedPartFileWriter.java:71)
    at org.apache.flink.streaming.api.functions.sink.filesystem.Bucket.closePartFile(Bucket.java:263)
    at org.apache.flink.streaming.api.functions.sink.filesystem.Bucket.prepareBucketForCheckpointing(Bucket.java:305)
    at org.apache.flink.streaming.api.functions.sink.filesystem.Bucket.onReceptionOfCheckpoint(Bucket.java:277)
    at org.apache.flink.streaming.api.functions.sink.filesystem.Buckets.snapshotActiveBuckets(Buckets.java:270)
    at org.apache.flink.streaming.api.functions.sink.filesystem.Buckets.snapshotState(Buckets.java:261)
    at org.apache.flink.streaming.api.functions.sink.filesystem.StreamingFileSinkHelper.snapshotState(StreamingFileSinkHelper.java:87)
    at org.apache.flink.connector.file.table.stream.AbstractStreamingWriter.snapshotState(AbstractStreamingWriter.java:129)
    at org.apache.flink.connector.file.table.stream.StreamingFileWriter.snapshotState(StreamingFileWriter.java:103)
    at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:222)
    ... 24 more
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: UNAUTHENTICATED: Channel: 78b62c86-6e51-4778-8bf4-1abb891f0612 is not authenticated for call: alluxio.grpc.block.BlockWorker/WriteBlock
    at alluxio.shaded.client.io.grpc.Status.asRuntimeException(Status.java:535)
    at alluxio.shaded.client.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
    at alluxio.shaded.client.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at alluxio.shaded.client.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at alluxio.shaded.client.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at alluxio.grpc.GrpcChannel$1$1$1.onClose(GrpcChannel.java:160)
    at alluxio.shaded.client.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at alluxio.shaded.client.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at alluxio.shaded.client.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
    at alluxio.shaded.client.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
    at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
    at alluxio.shaded.client.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
    at alluxio.shaded.client.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at alluxio.shaded.client.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    ... 1 more

**Urgency**
The real-time flink streaming job restarts, and the checkpoint fails, causing some files to be in the umcomplete state.

**Are you planning to fix it**
no

**Additional context**
none

**Comment by xiaohu-liu** [comment]
Inactive channels are cleared every three days. What is the default value of 3 days based on?

**Comment by xiaohu-liu** [comment]
The following code only compares time, not date. This is the crux of the problem. why not LocalDateTime?

private void cleanupStaleClients() {
        LocalTime cleanupTime = LocalTime.now();
        LOG.debug("Starting cleanup authentication registry at {}", cleanupTime);
        // Get a list of stale clients under read lock.
        List<UUID> staleChannels = new ArrayList<>();
        for (Map.Entry<UUID, AuthenticatedChannelInfo> clientEntry : mChannels.entrySet()) {
            LocalTime lat = clientEntry.getValue().getLastAccessTime();
            if (lat.plusSeconds(mCleanupIntervalMs / 1000).isBefore(cleanupTime)) {
                staleChannels.add(clientEntry.getKey());
            }
        }
        // Unregister stale clients.
        LOG.debug("Found {} stale channels for cleanup.", staleChannels.size());
        for (UUID clientId : staleChannels) {
            mChannels.remove(clientId).getSaslServerDriver().close();
        }
        LOG.debug("Finished state channel cleanup at {}", LocalTime.now());
    }
