### ISSUE TITLE
Kubernetes deployment error: Could not initialize class alluxio.conf.PropertyKey 

### ISSUE THREAD

**Issue by sadatnfs** [Alluxio/alluxio#18585]
**Alluxio Version:** 
2.9.3 and master branch

**Describe the bug**
Master process doesn't start with this error:
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class alluxio.conf.PropertyKey
        at alluxio.ProcessUtils.fatalError(ProcessUtils.java:116)
        at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:47)

**To Reproduce**
Deploy master stateful set YAML on Kubernetes, or even deploy the Helm chart

I suspect there's some configuration or environment variable I'll need to set for my pods. Any help would be appreciated

**Comment by jasondrogba** [comment]
I guess you did not set properties in values.yaml
```
# Site properties for all Alluxio components
properties:
```

**Comment by sadatnfs** [comment]
I only set the ufs properties. Do you know which ones I gotta set for kubernetes?

**Comment by jasondrogba** [comment]
How did you deploy the cluster? Did you obtain the Alluxio Docker image from official, or did you compile and build it yourself?

**Comment by sadatnfs** [comment]
@jasondrogba i compiled Alluxio myself with Maven calls, because the existing binaries have CVEs that we can't use with work. And then put it in our Docker image

**Comment by jasondrogba** [comment]
@sadatnfs It could be an issue generated by your compilation of Alluxio. Have you deployed and used it on a physical machine after compiling?
Because the error you reported doesn't seem to be caused by Docker, and it's rarely encountered, I suspect it might be a problem with your Maven compilation.
