### ISSUE TITLE
It's tough to run alluxio by docker

### ISSUE THREAD

**Issue by sunzhaoyang** [Alluxio/alluxio#18599]
### First try

Simply  execute command following the [document](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html#prerequisites) 

```
$ docker run -d --rm \
    --net=host \
    --name=alluxio-master \
    -v /tmp/alluxio_ufs:/opt/alluxio/underFSStorage \
    -e ALLUXIO_JAVA_OPTS=" \
       -Dalluxio.master.hostname=localhost \
       -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage" \
    alluxio/alluxio master
```

The container couldn't start because 

```
$sudo docker logs 3d288b4b88a9
2024-05-07 03:34:51,138 ERROR [main](ProcessUtils.java:119) - Fatal error: Failed to create master process
java.lang.RuntimeException: Journal RaftJournalSystem{JournalPath=/opt/alluxio-309/journal, Address=localhost:19200, State=STANDBY, Cluster=[localhost:19200], RaftGroup=null} has not been formatted!
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:116)
	at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:495)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:47)

2024-05-07 03:34:51,141 INFO  [main](ProcessUtils.java:161) - Logging metrics and jstack on MASTER exit...
2024-05-07 03:34:51,336 INFO  [main](ProcessUtils.java:230) - Dumped metrics of current process in 194ms to alluxio-master-exit-metrics-20240507-033451.json
2024-05-07 03:34:51,359 INFO  [main](ProcessUtils.java:247) - Dumped jstack of current process in 22ms to alluxio-master-exit-stacks-20240507-033451.txt
```

### Second  try

I changed version from latest to 295😀, the master start succeed. And then

![image](https://github.com/Alluxio/alluxio/assets/2182116/57c4c528-d6e9-4706-b2ab-6af46f9364ec)

Run tests as the document said 

```
$ docker exec -it alluxio-worker /bin/bash
$ cd /opt/alluxio
$ ./bin/alluxio runTests
```

Got lots of error messages 

```
2024-05-07 07:48:22,997 ERROR [main](RunTestUtils.java:64) - Exception running test: alluxio.cli.BasicOperations@160c3ec1
alluxio.exception.AlluxioException: Cannot create or load UFS directory /opt/alluxio/underFSStorage/default_tests_files: java.io.FileNotFoundException: /opt/alluxio/underFSStorage/default_tests_files.
	at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:110)
	at alluxio.client.file.BaseFileSystem.wrapAndThrowAlluxioStatusException(BaseFileSystem.java:661)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:638)
	at alluxio.client.file.BaseFileSystem.createFile(BaseFileSystem.java:174)
	at alluxio.cli.BasicOperations.writeFile(BasicOperations.java:96)
	at alluxio.cli.BasicOperations.call(BasicOperations.java:84)
	at alluxio.cli.BasicOperations.call(BasicOperations.java:43)
	at alluxio.cli.RunTestUtils.runExample(RunTestUtils.java:62)
	at alluxio.cli.TestRunner.runTest(TestRunner.java:234)
	at alluxio.cli.TestRunner.runTests(TestRunner.java:153)
	at alluxio.cli.TestRunner.main(TestRunner.java:115)
Caused by: alluxio.exception.status.UnknownException: Cannot create or load UFS directory /opt/alluxio/underFSStorage/default_tests_files: java.io.FileNotFoundException: /opt/alluxio/underFSStorage/default_tests_files.
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:174)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:241)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:493)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:457)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:446)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.createFile(RetryHandlingFileSystemMasterClient.java:180)
	at alluxio.client.file.BaseFileSystem.lambda$createFile$2(BaseFileSystem.java:177)
	at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:636)
	... 8 more

```

**Comment by sunzhaoyang** [comment]
successed with 2.9.3
