### ISSUE TITLE
Cannot truncate /Makefile to 0

### ISSUE THREAD

**Issue by airlsyn** [Alluxio/alluxio#18684]
**Alluxio Version:**
v2.9.4

**Describe the bug**
cannot copy file with `shutil.copy` if file exists.

The fuse log is:
```
2024-09-04 14:23:34,931 WARN  BaseFileSystem - File /Makefile is not yet completed. getStatus will see incomplete metadata.
2024-09-04 14:23:34,932 WARN  BaseFileSystem - File /Makefile is not yet completed. getStatus will see incomplete metadata.
2024-09-04 14:23:35,080 WARN  BaseFileSystem - File /Makefile is not yet completed. getStatus will see incomplete metadata.
2024-09-04 14:23:35,084 WARN  BaseFileSystem - File /Makefile is not yet completed. getStatus will see incomplete metadata.
2024-09-04 14:23:40,472 ERROR AlluxioJniFuseFileSystem - Cannot truncate /Makefile to 0. The file is not opened for overwrite

```

**To Reproduce**
````
>>> shutil.copy("Makefile", "/mnt/alluxio-data/")
'/mnt/alluxio-data/Makefile'
>>>
>>>
>>> shutil.copy("Makefile", "/mnt/alluxio-data/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miniconda3/envs/py38/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "miniconda3/envs/py38/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 95] Operation not supported: '/mnt/alluxio-data/Makefile'
>>>
```

**Expected behavior**
no except and correctly copied.

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**
Add any other context about the problem here.

**Comment by YichuanSun** [comment]
The Alluxio 2.x fuse has many known bugs, we don't recommand to use fuse in 2.x. We have a high performance and stable fuse in Alluxio 3.x if you are interested.

**Comment by YichuanSun** [comment]
the free trial https://www.alluxio.io/download/

**Comment by ericxsun** [comment]
> the free trial https://www.alluxio.io/download/

But there isn’t a version 3.x available for the Community Edition.

<img width="850" alt="image" src="https://github.com/user-attachments/assets/87fd0b4e-1c70-4fbd-91b8-7a9b50e90afe">

**Comment by YichuanSun** [comment]
Oh, yes. Alluxio 3.x is an enterprise edition. So I called it "free trial".

**Comment by ericxsun** [comment]
> Oh, yes. Alluxio 3.x is an enterprise edition. So I called it "free trial".

Okay, I'll try it.

Is it possible to release the Alluxio 3.x Community Edition?

**Comment by YichuanSun** [comment]
> > Oh, yes. Alluxio 3.x is an enterprise edition. So I called it "free trial".
> 
> Okay, I'll try it.
> 
> Is it possible to release the Alluxio 3.x Community Edition?

Sorry, currently we don't have the plan.

**Comment by ericxsun** [comment]
> > > Oh, yes. Alluxio 3.x is an enterprise edition. So I called it "free trial".
> > 
> > 
> > Okay, I'll try it.
> > Is it possible to release the Alluxio 3.x Community Edition?
> 
> Sorry, currently we don't have the plan.

Thanks.
