### ISSUE TITLE
java端连接2.9.5 版本alluxio时连接不上 。。。。。。但是同样的代码用2.6.0maven依赖就可以使用，用2.9.5就不行Failed to connect the java terminal to alluxio 2.9.5...... But the same code will work with 2.6.0maven dependencies, but not with 2.9.5

### ISSUE THREAD

**Issue by CAIBAIQIANG** [Alluxio/alluxio#18700]
<img width="1344" alt="Snipaste_2024-10-14_17-28-00" src="https://github.com/user-attachments/assets/27b1339a-653b-4649-999b-ce4b661fdfd0">
<img width="1140" alt="Snipaste_2024-10-14_17-29-31" src="https://github.com/user-attachments/assets/6b868d8b-5e6c-4b23-9d99-6e29e6080316">
17:26:58.527 [main] INFO alluxio.metrics.MetricsSystem -- Starting sinks with config: {}.
17:26:58.536 [main] INFO alluxio.client.metrics.MetricsHeartbeatContext -- Created metrics heartbeat with ID app-2587856813211447794. This ID will be used for identifying info from the client. It can be set manually through the alluxio.user.app.id property
17:26:58.591 [main] INFO alluxio.network.TieredIdentityFactory -- Initialized tiered identity TieredIdentity(node=192.168.12.115, rack=null)
17:26:58.695 [main] INFO alluxio.util.network.NettyUtils -- EPOLL is not available, will use NIO
17:27:08.572 [metrics-master-heartbeat-0] ERROR alluxio.client.metrics.ClientMasterSync -- Failed to get master address during initialization
alluxio.exception.status.UnavailableException: Failed to handshake with master localhost/<unresolved>:19998 to load cluster default configuration values: UNKNOWN
	at alluxio.conf.Configuration.loadConfiguration(Configuration.java:458)
	at alluxio.ClientContext.loadConf(ClientContext.java:123)
	at alluxio.client.metrics.ClientMasterSync.loadConf(ClientMasterSync.java:122)
	at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:74)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at alluxio.grpc.MetaMasterConfigurationServiceGrpc$MetaMasterConfigurationServiceBlockingStub.getConfiguration(MetaMasterConfigurationServiceGrpc.java:405)
	at alluxio.conf.Configuration.loadConfiguration(Configuration.java:452)
	... 10 common frames omitted
Caused by: java.lang.UnsupportedOperationException: null
	at io.grpc.netty.AbstractHttp2Headers.iterator(AbstractHttp2Headers.java:500)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:423)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:350)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:54)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:475)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:483)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:247)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:164)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:186)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:391)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:451)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 common frames omitted

**Comment by CAIBAIQIANG** [comment]
依赖引错了 csdn害人不浅
