### ISSUE TITLE
[alluxio.logger.type] - java.net.BindException: Address already in use: connect

### ISSUE THREAD

**Issue by Leoin** [Alluxio/alluxio#2972]
2016-04-01 13:49:15,625 ERROR [alluxio.logger.type] - java.net.SocketException: No buffer space available (maximum connections reached?): connect
alluxio.org.apache.thrift.transport.TTransportException: java.net.SocketException: No buffer space available (maximum connections reached?): connect
	at alluxio.org.apache.thrift.transport.TSocket.open(TSocket.java:226)
	at alluxio.org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
	at alluxio.client.block.BlockWorkerClient.connectOperation(BlockWorkerClient.java:210)
	at alluxio.client.block.BlockWorkerClient.connect(BlockWorkerClient.java:304)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:291)
	at alluxio.client.block.BlockWorkerClient.sessionHeartbeat(BlockWorkerClient.java:408)
	at alluxio.client.block.BlockWorkerClient.periodicHeartbeat(BlockWorkerClient.java:424)
	at alluxio.client.block.BlockWorkerClientHeartbeatExecutor.heartbeat(BlockWorkerClientHeartbeatExecutor.java:34)
	at alluxio.client.block.BlockWorkerClient.beforeDisconnect(BlockWorkerClient.java:169)
	at alluxio.AbstractClient.disconnect(AbstractClient.java:197)
	at alluxio.AbstractClient.close(AbstractClient.java:221)
	at alluxio.client.block.BlockStoreContext.releaseWorkerClient(BlockStoreContext.java:249)
	at alluxio.client.block.AlluxioBlockStore.promote(AlluxioBlockStore.java:253)
	at alluxio.client.file.FileInStream.updateBlockInStream(FileInStream.java:384)
	at alluxio.client.file.FileInStream.checkAndAdvanceBlockInStream(FileInStream.java:236)
	at alluxio.client.file.FileInStream.read(FileInStream.java:161)
	at org.apache.avro.io.BinaryDecoder$InputStreamByteSource.readRaw(BinaryDecoder.java:824)
	at org.apache.avro.io.BinaryDecoder.doReadBytes(BinaryDecoder.java:349)
	at org.apache.avro.io.BinaryDecoder.readFixed(BinaryDecoder.java:302)
	at org.apache.avro.io.Decoder.readFixed(Decoder.java:150)
	at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:100)
	at org.apache.avro.file.DataFileStream.<init>(DataFileStream.java:84)
	at alluxio.Test.testRead(Test.java:47)
	at alluxio.Test.main(Test.java:35)
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:73)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:157)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
	at java.net.Socket.connect(Socket.java:579)
	at alluxio.org.apache.thrift.transport.TSocket.open(TSocket.java:221)
	... 23 more

**Comment by yupeng9** [comment]
@Leoin can you send the questions to the mailing list https://groups.google.com/forum/?fromgroups#!forum/alluxio-users ? Thanks.
