### ISSUE TITLE
spark write parquet file occured :java.lang.NoSuchFieldError: mProtocol

### ISSUE THREAD

**Issue by Humbinal** [Alluxio/alluxio#3411]
When I use the `dataframe.write.mode(SaveMode.Append).parquet(parquetPath)` to write parquet file an error occured:
java.lang.NoSuchFieldError: mProtocol
	at alluxio.client.file.FileSystemMasterClient.afterConnect(FileSystemMasterClient.java:79)
	at alluxio.AbstractClient.connect(AbstractClient.java:171)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:291)
	at alluxio.client.file.FileSystemMasterClient.getUfsAddress(FileSystemMasterClient.java:255)
	at alluxio.hadoop.AbstractFileSystem.getUfsAddress(AbstractFileSystem.java:598)
	at alluxio.hadoop.AbstractFileSystem.initialize(AbstractFileSystem.java:440)
	at alluxio.hadoop.FileSystem.initialize(FileSystem.java:25)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2397)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:89)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2431)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2413)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:368)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:179)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:137)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:304)

**Comment by haoyuan** [comment]
Please post your question here: https://groups.google.com/forum/?fromgroups#!forum/alluxio-users

If you can't access the above link, please post your question here: http://alluxio-users.85194.x6.nabble.com/
