### ISSUE TITLE
build alluxio

### ISSUE THREAD

**Issue by lklong** [Alluxio/alluxio#4410]
hi ,
 i buid alluxio with cmd "mvn -Dhadoop.version=2.7.1 clean package  -Pspark -Pyarn -Pflink -Phadoop-2.7 -DskipTests" ,and all successed.
but when i access http://localhost:19999/home,ｉgot an error trace like below
**_please give me some advice,thanks very much!_**
**_how should i resovle this problem???????????_**
Caused by:
java.lang.NoSuchMethodError: javax.el.ExpressionFactory.newInstance()Ljavax/el/ExpressionFactory;
	at org.apache.jasper.compiler.JspUtil.getExpressionFactory(JspUtil.java:1189)
	at org.apache.jasper.compiler.JspUtil.validateExpressions(JspUtil.java:651)
	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:760)
	at org.apache.jasper.compiler.Node$ELExpression.accept(Node.java:947)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2297)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2347)
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2353)
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:499)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2297)
	at org.apache.jasper.compiler.Validator.validate(Validator.java:1890)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:223)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:451)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:625)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
	at alluxio.web.WebInterfaceGeneralServlet.doGet(WebInterfaceGeneralServlet.java:126)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by haoyuan** [comment]
Please post questions at our user mailing list: https://groups.google.com/forum/?fromgroups#!forum/alluxio-users or its mirror: http://alluxio-users.85194.x6.nabble.com/

**Comment by lklong** [comment]
ok
thanks very much!
