### ISSUE TITLE
DataFrame write table success, but has NullPointerException end of spark log

### ISSUE THREAD

**Issue by sss008800** [Alluxio/alluxio#5607]
Spark on Yarn, and hdfs is under storage of alluxio.
Have configured spark, hive and hdfs.
application is read a table, and write a table. as,

> import org.apache.spark.sql.hive.HiveContext
> val resDF = hiveContext.sql("select * from u_user")
> resDF.write.mode("append").saveAsTable("user_2")

**spark submit this application, then print WARN log end of console. Job has successful and finashed.** 

`WARN util.ShutdownHookManager: ShutdownHook 'ClientFinalizer' failed, java.lang.NullPointerException
java.lang.NullPointerException
	at alluxio.client.file.FileSystemContext.acquireMasterClient(FileSystemContext.java:185)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:230)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:224)
	at alluxio.hadoop.AbstractFileSystem.getFileStatus(AbstractFileSystem.java:313)
	at alluxio.hadoop.FileSystem.getFileStatus(FileSystem.java:25)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1417)
	at org.apache.hadoop.fs.FileSystem.processDeleteOnExit(FileSystem.java:1400)
	at org.apache.hadoop.fs.FileSystem.close(FileSystem.java:2158)
	at alluxio.hadoop.AbstractFileSystem.close(AbstractFileSystem.java:133)
	at alluxio.hadoop.FileSystem.close(FileSystem.java:25)
	at org.apache.hadoop.fs.FileSystem$Cache.closeAll(FileSystem.java:2912)
	at org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer.run(FileSystem.java:2929)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)`

**Comment by yupeng9** [comment]
Hi @sss008800 

Thanks for checking out Alluxio. Please post the question to the [user mailing list](https://groups.google.com/forum/?fromgroups#!forum/alluxio-users). If you cannot access Google, you can use this [mirror](http://alluxio-users.85194.x6.nabble.com/).
