### ISSUE TITLE
The worker can not be started in version 1.5.0

### ISSUE THREAD

**Issue by JinsYin** [Alluxio/alluxio#5664]
I am running alluxio `1.5.0` on local machine according to [the official tutorial](http://www.alluxio.org/docs/1.5/en/Running-Alluxio-Locally.html), but the `worker`  can not be started. It works after I changed to `1.4.0` version.

```
$ netstat -tpln | grep java
tcp        0      0 0.0.0.0:19998           0.0.0.0:*               LISTEN      9325/java       
tcp        0      0 0.0.0.0:39999           0.0.0.0:*               LISTEN      9479/java       
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      9325/java   
```

```
$ cat logs/master.log
2017-06-21 09:54:10,292 INFO  BlockMasterFactory - Creating alluxio.master.block.BlockMaster 
2017-06-21 09:54:10,292 INFO  FileSystemMasterFactory - Creating alluxio.master.file.FileSystemMaster 
2017-06-21 09:54:10,363 INFO  ProcessUtils - Starting Alluxio master @localhost/127.0.0.1:19998.
2017-06-21 09:54:10,364 INFO  AbstractMaster - BlockMaster: Starting primary master.
2017-06-21 09:54:10,404 INFO  UfsJournalLogWriter - Created current log file: UfsJournalFile{location=/opt/alluxio-1.5.0-hadoop-2.7/journal/BlockMaster/v1/logs/0x0-0x7fffffffffffffff, start=0, end=9223372036854775807, isCheckpoint=false}
2017-06-21 09:54:10,440 INFO  MountTable - Mounting /tmp/underfs at /
2017-06-21 09:54:10,441 INFO  AbstractMaster - FileSystemMaster: Starting primary master.
2017-06-21 09:54:10,443 INFO  UfsJournalLogWriter - Created current log file: UfsJournalFile{location=/opt/alluxio-1.5.0-hadoop-2.7/journal/FileSystemMaster/v1/logs/0x0-0x7fffffffffffffff, start=0, end=9223372036854775807, isCheckpoint=false}
2017-06-21 09:54:10,447 INFO  MetricsSystem - Starting sinks with config: {}.
2017-06-21 09:54:10,453 INFO  log - Logging initialized @627ms
2017-06-21 09:54:10,536 INFO  Server - jetty-9.2.z-SNAPSHOT
2017-06-21 09:54:10,551 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@7671cb68{/metrics/json,null,AVAILABLE}
2017-06-21 09:54:16,872 INFO  ContextHandler - Started o.e.j.w.WebAppContext@fac80{/,file:/opt/alluxio-1.5.0-hadoop-2.7/core/server/common/src/main/webapp/,AVAILABLE}{/opt/alluxio-1.5.0-hadoop-2.7/core/server/common/src/main/webapp}
2017-06-21 09:54:16,877 INFO  ServerConnector - Started ServerConnector@596df867{HTTP/1.1}{0.0.0.0:19999}
2017-06-21 09:54:16,878 INFO  Server - Started @7051ms
2017-06-21 09:54:16,878 INFO  WebServer - Alluxio Master Web service started @ /0.0.0.0:19999
2017-06-21 09:54:16,878 INFO  AlluxioMasterProcess - Alluxio master @localhost/127.0.0.1:19998 version 1.5.0 started @ localhost/127.0.0.1:19998 
```

```
$ cat logs/worker.log
2017-06-21 09:54:16,198 INFO  BlockWorkerFactory - Creating alluxio.worker.block.BlockWorker 
2017-06-21 09:54:16,198 INFO  FileSystemWorkerFactory - Creating alluxio.worker.file.FileSystemWorker 
2017-06-21 09:54:16,238 INFO  FileUtils - Folder /mnt/ramdisk/alluxioworker was created!
```

```bash
$ cat logs/worker.out
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Timed out waiting for server alluxio.worker.block.BlockWorker to be created
	at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:148)
	at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:35)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:54)
Caused by: java.lang.RuntimeException: Timed out waiting for server alluxio.worker.block.BlockWorker to be created
	at alluxio.util.CommonUtils.waitFor(CommonUtils.java:257)
	at alluxio.Registry.get(Registry.java:83)
	at alluxio.Registry.get(Registry.java:69)
	at alluxio.worker.file.FileSystemWorkerFactory.create(FileSystemWorkerFactory.java:44)
	at alluxio.worker.file.FileSystemWorkerFactory.create(FileSystemWorkerFactory.java:27)
	at alluxio.worker.AlluxioWorkerProcess$1.call(AlluxioWorkerProcess.java:113)
	at alluxio.worker.AlluxioWorkerProcess$1.call(AlluxioWorkerProcess.java:109)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yupeng9** [comment]
Hi @JinsYin 

Thanks for checking out 1.5.0. Please post the question to the [user mailing list](https://groups.google.com/forum/?fromgroups#!forum/alluxio-users). If you cannot access Google, you can use this [mirror](http://alluxio-users.85194.x6.nabble.com/).
