### ISSUE TITLE
read a sequencefile encounter exception not a sequencefile

### ISSUE THREAD

**Issue by luyizhizaio** [Alluxio/alluxio#7163]
Hello
recently，i encounter an following exception. I want to read sequencefile stored in HDFS through alluxio.  
some can load successfully,but some can not. 

java.io.IOException: /mcloud/data/datacenter/roaringbitmap/month/standard/label/init/part-r-00175 not a SequenceFile
        at org.apache.hadoop.io.SequenceFile$Reader.init(SequenceFile.java:1850) ~[alluxio-underfs-hdfs-1.6.1.jar:?]
        at org.apache.hadoop.io.SequenceFile$Reader.initialize(SequenceFile.java:1810) ~[alluxio-underfs-hdfs-1.6.1.jar:?]
        at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1759) ~[alluxio-underfs-hdfs-1.6.1.jar:?]
        at com.talkingdata.mc.importer.utils.ImportUtils.readerOf(ImportUtils.java:509) ~[classes]
        at com.talkingdata.mc.importer.utils.ImportUtils.access$100(ImportUtils.java:35) ~[classes]
        at com.talkingdata.mc.importer.utils.ImportUtils$12.run(ImportUtils.java:410) [classes]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_80]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

**Comment by aaudiber** [comment]
@luyizhizaio We don't use github issues to track questions or bugs. Please redirect this to the alluxio mailing list or JIRA - see https://github.com/Alluxio/alluxio/issues/329
