### ISSUE TITLE
alluxio-1.8.1 on hdfs3.0 + spark2.3.1 on yarn error

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#8169]
## versions
	spark version: 2.3.1
	alluxio version: 1.8.1
	hdfs version: 3.0.0
	java version: 1.8.0_181
## describe
	run: sparkSession.read.parquet("alluxio://masterhost:19998/table").show(1)
	error: alluxio-1.8.1-client treat spark client's ip as alluxio's master ip
### spark log shows:
	WARN AbstractClient: Failed to handshake (1) with MetricsMasterClient @ clienthost/ip:19998: Failed to handshake with master clienthost/ip:19998 to load cluster default configuration values
	ERROR ClientMasterSync: Failed to heartbeat to the metrics master:
	alluxio.exception.status.UnavailableException: Failed to connect to MetricsMasterClient @ clienthost/ip:19998 after 1 attempts
		at alluxio.AbstractClient.connect(AbstractClient.java:322)
		at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:84)
		at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:63)
		at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:74)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor 

### alluxio proxy log shows:

	INFO  AbstractClient - Alluxio client (version 1.8.1) is trying to connect with MetricsMasterClient @ masterhost:19998
	INFO  AbstractClient - Client registered with MetricsMasterClient @ masterhost:19998
	ERROR ClientMasterSync - Failed to heartbeat to the metrics master:
	alluxio.exception.status.UnavailableException
			at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:91)
			at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:63)
			at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:74)
			at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
			at java.util.concurrent.FutureTask.run(FutureTask.java:266)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
			at java.lang.Thread.run(Thread.java:748)
	Caused by: org.apache.thrift.transport.TTransportException
			at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
			at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
			at org.apache.thrift.transport.TSaslTransport.readLength(TSaslTransport.java:376)
			at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:453)
			at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:435)
			at org.apache.thrift.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)
			at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
			at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
			at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
			at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
			at org.apache.thrift.protocol.TProtocolDecorator.readMessageBegin(TProtocolDecorator.java:135)
			at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
			at alluxio.thrift.MetricsMasterClientService$Client.recv_metricsHeartbeat(MetricsMasterClientService.java:102)
			at alluxio.thrift.MetricsMasterClientService$Client.metricsHeartbeat(MetricsMasterClientService.java:87)
			at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:86)
			... 7 more
### by the way alluxio.user.metrics.collection.enabled=false

**Comment by JySongWithZhangCe** [comment]
alluxio-1.8.1 on hdfs3.0 + spark2.3.1 on yarn error

**Comment by apc999** [comment]
It seems the Alluxio client in Spark does not successfully recognize the the master host ip.
As a workaround, you can manually pass the Alluxio master host to Spark by passing this "alluxio.master.hostname=masterhost" to Spark (see how to achieve this
https://www.alluxio.org/docs/1.8/en/compute/Spark.html#advanced-setup)

**Comment by JySongWithZhangCe** [comment]
solve this by setting spark.driver.extraJavaOptions -Dalluxio.master.hostname=masterhost in spark-defaults.conf
thx :)

**Comment by apc999** [comment]
glad to know! thanks for reporting this issue
