### ISSUE TITLE
Integrate with spark-sql/hive error

### ISSUE THREAD

**Issue by zjfplayer** [Alluxio/alluxio#8215]

**Comment by zjfplayer** [comment]
When I insert tens of millions of data, I get an error:

> Caused by: java.io.IOException: Could not read footer for file FileStatus{path=a2181,test3:2181/user/hive/warehouse/t_tag_base/_common_metadata; isDirectory=fal0; blocksize=0; modification_time=0; access_time=0; owner=; group=; permission=r
        at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.
        at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: alluxio.exception.status.NotFoundException: Block 36,171,677,696 is ud UFS.
        at alluxio.client.block.AlluxioBlockStore.getInStream(AlluxioBlockStore.
        at alluxio.client.file.FileInStream.updateStream(FileInStream.java:309)
        at alluxio.client.file.FileInStream.read(FileInStream.java:125)
        at alluxio.hadoop.HdfsFileInputStream.read(HdfsFileInputStream.java:100)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.apache.parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.ja
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileRea
        at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.
        ... 5 more

Then I checked the alluxio file system：

> [root@test2 ~]# alluxio fs ls alluxio://zk@test1:2181,test2:2181,test3:2181/user/hive/warehouse/t_tag_base/_common_metadata
-rw-r--r--  root           root                      1753            LOST 12-20-2018 21:53:23:615   0% /user/hive/warehouse/t_tag_base/_common_metadata

**Comment by zjfplayer** [comment]
![image](https://user-images.githubusercontent.com/4350825/50323356-3cdb4a80-0514-11e9-817a-14c5d4598a2a.png)

**Comment by zjfplayer** [comment]
I repackage alluxio with the following command:

> mvn install -Phadoop-2 -Dhadoop.version=hadoop.version=2.6.0-cdh5.14.2 -DskipTests
mvn package -Phadoop-2 -Dhadoop.version=hadoop.version=2.6.0-cdh5.14.2 -DskipTests

And the result is all success

**Comment by apc999** [comment]
@zjfplayer just to double check , this issue has been solved by rebuilding alluxio with `hadoop.version=2.6.0-cdh5.14.2`, right? In that case, I will close the issue

**Comment by zjfplayer** [comment]
> @zjfplayer just to double check , this issue has been solved by rebuilding alluxio with `hadoop.version=2.6.0-cdh5.14.2`, right? In that case, I will close the issue

This problem still exists, I feel that the reason is that the database file generated by hive is not persistent.Then I restarted alluxio and I got an error.

**Comment by zjfplayer** [comment]
Why integration with hive/spark does not automatically persist data files?

**Comment by zjfplayer** [comment]
> @zjfplayer just to double check , this issue has been solved by rebuilding alluxio with `hadoop.version=2.6.0-cdh5.14.2`, right? In that case, I will close the issue

https://groups.google.com/forum/#!topic/alluxio-users/mtMEoxeTFos
This solved the problem for me.
