### ISSUE TITLE
Inconsistent Zookeeper configuration;  Exception using with hive

### ISSUE THREAD

**Issue by jiaxiaodong** [Alluxio/alluxio#8241]
**Alluxio Version:** <enter version here, e.g. 1.8.0>

**Describe the bug**
Configurate with the start guide in cluster with 5 servers. 2 for masters and 3 for workers. And the alluxio could be worked but can't use with hive.
Fistly, I write the server of zk in wrong order. For example on server1 set alluxio.zookeeper.address=zk2,zk1,zk3 and alluxio.zookeeper.address=zk1,zk2,zk3 on the others. So there was a Server Configuration Check: FAILED on that. I fix it but it still appears when using hive.
Here is  log of the hive command. 'alluxio://xxx:19998/testcsv' is a file copyFromLocal and could read on web UI.
hive> create table tagsinm ( userId INT,movieId INT,tag string,trec string)ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' LOCATION 'alluxio://xxx:19998/testcsv';
FAILED: SemanticException java.lang.IllegalStateException: Inconsistent Zookeeper configuration; alluxio.zookeeper.address should be set if and only if alluxio.zookeeper.enabled is true
hive> Exception in thread "Thread-8" java.lang.IllegalStateException: Inconsistent Zookeeper configuration; alluxio.zookeeper.address should be set if and only if alluxio.zookeeper.enabled is true
	at alluxio.core.client.runtime.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at alluxio.conf.InstancedConfiguration.checkZkConfiguration(InstancedConfiguration.java:405)
	at alluxio.conf.InstancedConfiguration.validate(InstancedConfiguration.java:280)
	at alluxio.Configuration.validate(Configuration.java:375)
	at alluxio.AbstractClient.doHandshake(AbstractClient.java:249)
	at alluxio.AbstractClient.connect(AbstractClient.java:297)
	at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:84)
	at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:63)
	at alluxio.client.file.FileSystemContext$MetricsMasterSyncShutDownHook.run(FileSystemContext.java:437)
Exception in thread "Thread-9" java.lang.IllegalStateException: Inconsistent Zookeeper configuration; alluxio.zookeeper.address should be set if and only if alluxio.zookeeper.enabled is true
	at alluxio.core.client.runtime.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at alluxio.conf.InstancedConfiguration.checkZkConfiguration(InstancedConfiguration.java:405)
	at alluxio.conf.InstancedConfiguration.validate(InstancedConfiguration.java:280)
	at alluxio.Configuration.validate(Configuration.java:375)
	at alluxio.AbstractClient.doHandshake(AbstractClient.java:249)
	at alluxio.AbstractClient.connect(AbstractClient.java:297)
	at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:84)
	at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:63)
	at alluxio.client.file.FileSystemContext$MetricsMasterSyncShutDownHook.run(FileSystemContext.java:437)

**Comment by gpang** [comment]
@jiaxiaodong Thanks for the issue. In your description, could you provide the Alluxio version?

**Comment by jiaxiaodong** [comment]
1.8.0 @gpang

**Comment by aaudiber** [comment]
@jiaxiaodong 

If you already set zookeeper configuration in your client properties, you can use a URI like `alluxio:///testcsv`.

You can also use a URI like `alluxio://zk@zk1,zk2,zk3/testcsv` to specify the zookeeper information within the URI itself

**Comment by apc999** [comment]
@jiaxiaodong  does setting URL like `alluxio:///testcsv` working for you?
