### ISSUE TITLE
questions about user premissions, using with hive and hdfs

### ISSUE THREAD

**Issue by jiaxiaodong** [Alluxio/alluxio#8245]
Alluxio 1.8.0 with hadoop 2.7
I depoly alluxio on a Cluster. And run by the user root. So I need to make some dir on hdfs manually, and operations from hive have some AccessControlException. Still can't work now.
I want to confirm what dir or user permission should I use when I want to running hive on alluxio.

For example of me,  there are user hive and hdp responsible for two components. And I run alluxio under root. So I make dir of /alluxio on hdfs, and chown to root. Then I run the hive client under root, there still has some error. Please show me in detail, what dir and user premission should I set.

And there is still some error in different sitution. If there has some wrong, please help me. thank you very much.

**1.I set the config as below**
`alluxio.master.hostname=alluxiomaster.com
alluxio.underfs.address=hdfs://tpresto/

alluxio.worker.memory.size=1GB
alluxio.worker.tieredstore.levels=1
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
`
and the log in hive shows as below.
`2019-01-09 22:14:03,061 INFO  [pool-5-thread-1]: alluxio.AbstractClient (AbstractClient.java:doConnect(257)) - Alluxio client (version 1.8.0) is trying to connect with FileSystemMasterClient @ alluxiomaster.com/172.21.3.1:19998
2019-01-09 22:14:03,063 WARN  [pool-5-thread-1]: alluxio.AbstractClient (AbstractClient.java:connect(308)) - Failed to connect (15) with FileSystemMasterClient @ alluxiomaster.com/172.21.3.1:19998: Peer indicated failure: Plain 
authentication failed: User hive is not configured for any impersonation. impersonationUser: root
2019-01-09 22:14:04,444 INFO  [Master Metrics Sync]: alluxio.AbstractClient (AbstractClient.java:doConnect(257)) - Alluxio client (version 1.8.0) is trying to connect with MetricsMasterClient @ alluxiomaster.com/172.21.3.1:19998
2019-01-09 22:14:04,446 WARN  [Master Metrics Sync]: alluxio.AbstractClient (AbstractClient.java:connect(308)) - Failed to connect (1) with MetricsMasterClient @ alluxiomaster.com/172.21.3.1:19998: Peer indicated failure: Plain 
authentication failed: User hive is not configured for any impersonation. impersonationUser: root
2019-01-09 22:14:04,447 ERROR [Master Metrics Sync]: metrics.ClientMasterSync (ClientMasterSync.java:heartbeat(66)) - Failed to heartbeat to the metrics master: {}
alluxio.exception.status.UnavailableException: Failed to connect to MetricsMasterClient @ alluxiomaster.com/172.21.3.1:19998 after 1 attempts
        at alluxio.AbstractClient.connect(AbstractClient.java:325)
        at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:84)
        at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:63)
        at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`
**2. I set some security parameters below**
alluxio.security.authentication.type=NOSASL
alluxio.security.authorization.permission.enabled=false
alluxio.security.authorization.permission.supergroup=hdfs
alluxio.security.login.username=hive
And the hive could use alluxio client connect to the  FileSystemMasterClient. But when I operate tables on the alluxio, such as alter the table on alluxio there will have some error log.

 `2019-01-09 23:26:52,971 INFO  [pool-5-thread-8]: alluxio.AbstractClient (AbstractClient.java:doConnect(257)) - Alluxio client (version 1.8.0) is trying to connect with FileSystemMasterClient @ alluxiomaster.com/172.21.3.1:19998
2019-01-09 23:26:52,971 INFO  [Master Metrics Sync]: alluxio.AbstractClient (AbstractClient.java:doConnect(257)) - Alluxio client (version 1.8.0) is trying to connect with MetricsMasterClient @ alluxiomaster.com/172.21.3.1:19998
2019-01-09 23:26:52,971 INFO  [Master Metrics Sync]: alluxio.AbstractClient (AbstractClient.java:doConnect(264)) - Client registered with MetricsMasterClient @ alluxiomaster.com/172.21.3.1:19998
2019-01-09 23:26:52,971 INFO  [pool-5-thread-8]: alluxio.AbstractClient (AbstractClient.java:doConnect(264)) - Client registered with FileSystemMasterClient @ alluxiomaster.com/172.21.3.1:19998
2019-01-09 23:26:52,976 ERROR [pool-5-thread-8]: metastore.RetryingHMSHandler (RetryingHMSHandler.java:invokeInternal(199)) - MetaException(message:java.security.AccessControlException: Permission denied: user=root, path="alluxio://alluxiomaster.com:19998/alluxio/testtag":::drwxr-xr-x)
	at org.apache.hadoop.hive.ql.security.authorization.AuthorizationPreEventListener.metaException(AuthorizationPreEventListener.java:411)
	at org.apache.hadoop.hive.ql.security.authorization.AuthorizationPreEventListener.authorizeDropTable(AuthorizationPreEventListener.java:288)
	at org.apache.hadoop.hive.ql.security.authorization.AuthorizationPreEventListener.onEvent(AuthorizationPreEventListener.java:143)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.firePreEvent(HiveMetaStore.java:2131)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.drop_table_core(HiveMetaStore.java:1627)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.drop_table_with_environment_context(HiveMetaStore.java:1846)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:147)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:105)
	at com.sun.proxy.$Proxy11.drop_table_with_environment_context(Unknown Source)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$drop_table_with_environment_context.getResult(ThriftHiveMetastore.java:9455)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$drop_table_with_environment_context.getResult(ThriftHiveMetastore.java:9439)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.hadoop.hive.metastore.TUGIBasedProcessor$1.run(TUGIBasedProcessor.java:110)
	at org.apache.hadoop.hive.metastore.TUGIBasedProcessor$1.run(TUGIBasedProcessor.java:106)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866)
	at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:118)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.security.AccessControlException: Permission denied: user=root, path="alluxio://alluxiomaster.com:19998/alluxio/testtag":::drwxr-xr-x
	at org.apache.hadoop.hive.ql.security.authorization.StorageBasedAuthorizationProvider.checkDeletePermission(StorageBasedAuthorizationProvider.java:259)
	at org.apache.hadoop.hive.ql.security.authorization.StorageBasedAuthorizationProvider.authorize(StorageBasedAuthorizationProvider.java:187)
	at org.apache.hadoop.hive.ql.security.authorization.AuthorizationPreEventListener.authorizeDropTable(AuthorizationPreEventListener.java:281)
	... 24 more
Caused by: java.security.AccessControlException: Permission denied: user=root, path="alluxio://alluxiomaster.com:19998/alluxio/testtag":::drwxr-xr-x
	at org.apache.hadoop.hive.shims.Hadoop23Shims.wrapAccessException(Hadoop23Shims.java:1039)
	at org.apache.hadoop.hive.shims.Hadoop23Shims.checkFileAccess(Hadoop23Shims.java:1023)
	at org.apache.hadoop.hive.common.FileUtils.checkFileAccessWithImpersonation(FileUtils.java:381)
	at org.apache.hadoop.hive.common.FileUtils.checkDeletePermission(FileUtils.java:724)
	at org.apache.hadoop.hive.ql.security.authorization.StorageBasedAuthorizationProvider.checkDeletePermission(StorageBasedAuthorizationProvider.java:257)
	... 26 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.shims.Hadoop23Shims.checkFileAccess(Hadoop23Shims.java:1020)
	... 29 more
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=root, path="alluxio://alluxiomaster.com:19998/alluxio/testtag":::drwxr-xr-x
	at org.apache.hadoop.fs.FileSystem.checkAccessPermissions(FileSystem.java:2245)
	at org.apache.hadoop.fs.FileSystem.access(FileSystem.java:2214)
	... 33 more

2019-01-09 23:26:54,077 INFO  [Master Metrics Sync]: heartbeat.HeartbeatThread (HeartbeatThread.java:run(77)) - Hearbeat Master Metrics Sync is interrupted.
`

**Comment by aaudiber** [comment]
Hi @jiaxiaodong,

For questions like this, you can get better help by posting on the [Alluxio users mailing list](https://groups.google.com/forum/#!forum/alluxio-users). Github issues is for reporting bugs and requesting features.
