### ISSUE TITLE
ERROR ClientMasterSync - Failed to heartbeat to the metrics master

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#8423]
**Alluxio Version:** <enter version here, e.g. 1.8.1>
1.8.1

**Describe the bug**
ERROR ClientMasterSync - Failed to heartbeat to the metrics master

**To Reproduce**
./alluxio-start local SudoMount
./alluxio runTests

2019-02-19 17:52:56,997 ERROR ClientMasterSync - Failed to heartbeat to the metrics master:
alluxio.exception.status.UnavailableException: java.net.SocketException: Broken pipe (Write failed)
	at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:91)
	at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:63)
	at alluxio.heartbeat.HeartbeatThread.run(HeartbeatThread.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)
	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:147)
	at org.apache.thrift.transport.TSaslTransport.flush(TSaslTransport.java:500)
	at org.apache.thrift.transport.TSaslClientTransport.flush(TSaslClientTransport.java:37)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at alluxio.thrift.MetricsMasterClientService$Client.send_metricsHeartbeat(MetricsMasterClientService.java:96)
	at alluxio.thrift.MetricsMasterClientService$Client.metricsHeartbeat(MetricsMasterClientService.java:86)
	at alluxio.client.metrics.MetricsMasterClient.heartbeat(MetricsMasterClient.java:86)
	... 7 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
	... 14 more

**Comment by aaudiber** [comment]
The metrics reporting probably isn't the root cause of the issue, but I agree that it's way too loud. It would be better if it left out the stack trace and gave a warn-level log that metrics won't be recorded.

My guess is that the real root cause is that the master failed to come up - see `logs/master.log` and `logs/master.out` to see if there are any errors.
