### ISSUE TITLE
`LocalAlluxioCluster` can not work in an external application

### ISSUE THREAD

**Issue by murong00** [Alluxio/alluxio#8564]
**Alluxio Version:** <1.8.1>

**Describe the bug**
When trying to make a unit test via `LocalAlluxioCluster` in an external app as below:
```
    @Test
    public void openTest() throws Exception {
        String alluxioDir = "/test";

        // Setup and start the local alluxio cluster
        LocalAlluxioCluster cluster = new LocalAlluxioCluster();
        cluster.initConfiguration();
        Configuration.set(PropertyKey.USER_FILE_WRITE_TYPE_DEFAULT, WriteType.MUST_CACHE);
        cluster.start();

        FileSystem client = cluster.getClient();
        AlluxioURI alluxioURI = new AlluxioURI(alluxioDir);
        Assert.assertTrue(!client.exists(alluxioURI));
    }
```
It failed with the following:
```
14:39:11.450 [MasterThread-26757919:org.eclipse.jetty.webapp.WebInfConfiguration@492] WARN  org.eclipse.jetty.webapp.WebInfConfiguration - Web application not found /test_jar/../core/server/common/src/main/webapp
14:39:11.451 [MasterThread-26757919:org.eclipse.jetty.webapp.WebAppContext@514] WARN  org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@2ed96728{/,null,UNAVAILABLE}{/test_jar/../core/server/common/src/main/webapp}
java.io.FileNotFoundException: /test_jar/../core/server/common/src/main/webapp
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:493) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:468) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:504) [jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.start(Server.java:416) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStart(Server.java:383) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at alluxio.web.WebServer.start(WebServer.java:184) [alluxio-core-server-common-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.startServingWebServer(AlluxioMasterProcess.java:336) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:308) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:296) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.start(AlluxioMasterProcess.java:229) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.LocalAlluxioMaster$2.run(LocalAlluxioMaster.java:103) [alluxio-minicluster-1.8.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]	
```
then we create the above dir `core/server/common/src/main/webapp`, the following error occured:
```
ava.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:407) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1340) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) [jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.start(Server.java:416) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStart(Server.java:383) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at alluxio.web.WebServer.start(WebServer.java:184) [alluxio-core-server-common-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.startServingWebServer(AlluxioMasterProcess.java:336) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:308) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:296) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.AlluxioMasterProcess.start(AlluxioMasterProcess.java:229) [alluxio-core-server-master-1.8.1.jar:?]
	at alluxio.master.LocalAlluxioMaster$2.run(LocalAlluxioMaster.java:103) [alluxio-minicluster-1.8.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/servlet/BaseHolder$Source
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.newListenerInstance(StandardDescriptorProcessor.java:2013) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1957) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	... 37 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.servlet.BaseHolder$Source
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.newListenerInstance(StandardDescriptorProcessor.java:2013) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1957) ~[jetty-webapp-9.2.16.v20160414.jar:9.2.16.v20160414]
	... 37 more
```
however, the expected jar `jetty-servlet-9.4.12.v20180830.jar` are available in the classpath.

Is there any workaround to deal with this? Any advise or guidance would be greatly appreciated!

**Comment by murong00** [comment]
In my application case, the following reasons lead above error:
1.The web path `core/server/common/src/main/webapp` doesn't exist
2.`jetty.version` version mismatch, i.e. jar conflicts, which may lead missing class or method
3.lack some `jetty-*` jars
4.`com.google.guava` version mismatch, i.e. jar conflicts, which may lead missing class or method

**Comment by murong00** [comment]
Compare to `2.0.0-preview`, I found the version of `jetty-*` are all `9.2.16.v20160414`, but some version in `1.8.1` may have `9.4.12.v20180830`, you can use `mvn dependency:tree` to check the dependencies. What's more, the dependency version  of `com.google.guava` is `15.0`, when you use a higher version it may lead jar conflicts. Finally, you need create the missing web path `core/server/common/src/main/webapp` in the current classpath.

**Comment by murong00** [comment]
Here is my `pom` dependencies, hope this can help you:
```
        <properties>
           <jetty.version>9.2.16.v20160414</jetty.version>
        </properties>

        <!-- alluxio guava dependency need lower version -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>15.0</version>
        </dependency>

        <!-- jersey dependencies for alluxio local cluster test -->
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-http</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-security</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-jsp</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-webapp</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-xml</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>${jetty.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.bundles.repackaged</groupId>
            <artifactId>jersey-guava</artifactId>
            <version>2.22</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.27</version>
            <scope>test</scope>
        </dependency>
```

**Comment by apc999** [comment]
@murong00 Thanks so much for providing such comprehensive solution to this issue. @calvinjia , can we aim to improve useability of `LocalAlluxioCluster` in 2.0 GA so external depending applications can run unit tests on it?

**Comment by apc999** [comment]
This is a feature request to enable external applications to run unit tests against Alluxio
