### ISSUE TITLE
alluxio-1.8.1 on hdfs2.7 + spark2.3.0 on yarn error

### ISSUE THREAD

**Issue by JySongWithZhangCe** [Alluxio/alluxio#8589]
**Alluxio Version:** <enter version here, e.g. 1.8.1>
1.8.1
**Describe the bug**
Spark Client report:
java.lang.IllegalStateException: Inconsistent Zookeeper configuration; alluxio.zookeeper.address should be set if and only if alluxio.zookeeper.enabled is true

when alluxio.zookeeper.address already set and able to view on alluxio ui

**To Reproduce**
java.lang.IllegalStateException: Inconsistent Zookeeper configuration; alluxio.zookeeper.address should be set if and only if alluxio.zookeeper.enabled is true
  at alluxio.core.client.runtime.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
  at alluxio.conf.InstancedConfiguration.checkZkConfiguration(InstancedConfiguration.java:408)
  at alluxio.conf.InstancedConfiguration.validate(InstancedConfiguration.java:283)
  at alluxio.Configuration.validate(Configuration.java:375)
  at alluxio.AbstractClient.doHandshake(AbstractClient.java:245)
  at alluxio.AbstractClient.connect(AbstractClient.java:294)
  at alluxio.hadoop.AbstractFileSystem.initializeInternal(AbstractFileSystem.java:520)
  at alluxio.hadoop.AbstractFileSystem.initialize(AbstractFileSystem.java:483)
  at alluxio.hadoop.FileSystem.initialize(FileSystem.java:27)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2796)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:99)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2830)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2812)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:390)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:258)
  at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:229)
  at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
  at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:200)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
  at org.apache.spark.rdd.RDD.count(RDD.scala:1162)
  ... 49 elided

**Comment by aaudiber** [comment]
@JySongWithZhangCe the client needs to set both `alluxio.zookeeper.enabled=true` and `alluxio.zookeeper.address=<address>`. The error indicates that only one of the two is set. Can you double-check that you've set them both on the spark client side?

**Comment by JySongWithZhangCe** [comment]
I have set them both on the Alluxio, not on spark client side.
alluxio-1.8.1 on hdfs3.0 + spark2.3.1 and alluxio-1.7.0 on hdfs2.7 + spark2.3.1 on yarn do well in this way.
I will try your plan.
thx :)

**Comment by aaudiber** [comment]
@JySongWithZhangCe were you able to get it to work?

**Comment by apc999** [comment]
Close this issue as I think we know what's happen here in configuration and the error message is expected. We can always reopen this issue if @JySongWithZhangCe has other input

**Comment by JySongWithZhangCe** [comment]
set both "zookeeper url" and "enable=true" in spark client side is work.

sorry for response too late.

I think this way is not convenient and stable.

Users don't need to set "zookeeper url" and "enable=true" while using Alluxio1.7.0 and Alluxio1.8.1 + hdfs3.0(custom compilation).

We are looking for a good way to help users transfer their applications from alluxio1.7.0 to Alluxio1.8.1 without change anything.

I'd appreciate some good suggestion

thx:)

**Comment by aaudiber** [comment]
@JySongWithZhangCe 

Alluxio has always had the same requirement of setting both the `alluxio.zookeeper.address` and `alluxio.zookeeper.enabled` properties. The change in 1.8 is whether alluxio respects setting an explicit hostname in the uri.

Before 1.8, if you set zookeeper configuration, then use a uri like `alluxio://host1:19999/foo`, the "host1:19999" will be *ignored*, and the zookeeper configuration will be used. In 1.8, we use "host1:19999". To use configuration-based master connection info, you can use a uri like `alluxio:///foo`.

We made this change because it was very confusing to many users that `alluxio://host1:19999/foo` would not connect to `host1:19999` if zookeeper configuration was set.

Can you ask your users to change their alluxio uris to use an empty authority like `alluxio:///` instead of `alluxio://host1:19999`?

**Comment by JySongWithZhangCe** [comment]
I will~ this is the perfect answer~
Thx :）
