### ISSUE TITLE
while Worker register to Master, Both Master and Worker NPE if it named the tier alias name other than the MEM SSD HDD

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#8997]
**Alluxio Version:**
What version of Alluxio are you using?
Alluxio-2.0.0-SNAPSHOT, in fact, i build it from master branch in 5/5/2019

**Describe the bug**
while Worker register to Master, Both Master and Worker NPE if it named the tier alias name other than the MEM SSD HDD

**To Reproduce**

1. start master.

2. using the alluxio.properties to start worker
alluxio.worker.tieredstore.levels=1
alluxio.worker.tieredstore.level0.alias=NAMEFOO
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk/alluxio/alluxio-blockpool
alluxio.worker.tieredstore.level0.dirs.quota=200GB

**Expected behavior**
watching the master.log and worker.log, NPE will occurred in both of them.

**Urgency**
NORMAL.

**Additional context**

- master.log.

```
java.lang.NullPointerException
    at alluxio.StorageTierAssoc.getOrdinal(StorageTierAssoc.java:101)
    at alluxio.master.block.meta.MasterWorkerInfo.register(MasterWorkerInfo.java:114)
    at alluxio.master.block.DefaultBlockMaster.workerRegister(DefaultBlockMaster.java:831)
    at alluxio.master.block.BlockMasterWorkerServiceHandler.lambda$registerWorker$93(BlockMasterWorkerServiceHandler.java:137)
    at alluxio.RpcUtils.call(RpcUtils.java:193)
    at alluxio.RpcUtils.call(RpcUtils.java:166)
    at alluxio.master.block.BlockMasterWorkerServiceHandler.registerWorker(BlockMasterWorkerServiceHandler.java:135)
    at alluxio.grpc.BlockMasterWorkerServiceGrpc$MethodHandlers.invoke(BlockMasterWorkerServiceGrpc.java:605)
    at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
    at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
    at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
    at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
    at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
    at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
    at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
    at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1355)
    at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
```

- worker.log

```
2019-05-06 20:57:03,495 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master BJLFRZ-10k-214-99.hadoop.jd.local/172.21.214.99:19998
2019-05-06 20:57:03,500 INFO  ConfigurationUtils - Alluxio client (version 2.0.0-SNAPSHOT) is trying to load cluster level configurations
2019-05-06 20:57:03,522 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
2019-05-06 20:57:03,533 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=BJLFRZ-10k-214-70.hadoop.jd.local, rack=null)
2019-05-06 20:57:03,691 INFO  BlockWorkerFactory - Creating alluxio.worker.block.BlockWorker
2019-05-06 20:57:03,691 INFO  FileSystemWorkerFactory - Creating alluxio.worker.file.FileSystemWorker
2019-05-06 20:57:03,800 INFO  log - Logging initialized @1160ms
2019-05-06 20:57:03,957 INFO  NettyUtils - EPOLL_MODE is available
2019-05-06 20:57:04,077 INFO  GrpcDataServer - Server started, listening on /0.0.0.0:29999
2019-05-06 20:57:04,078 INFO  ProcessUtils - Starting Alluxio worker.
2019-05-06 20:57:04,079 INFO  MetricsSystem - Starting sinks with config: {}.
2019-05-06 20:57:04,314 ERROR ProcessUtils - Uncaught exception while running Alluxio worker, stopping it and exiting.
alluxio.exception.status.InternalException
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:148)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:209)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:374)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:334)
	at alluxio.worker.block.BlockMasterClient.register(BlockMasterClient.java:198)
	at alluxio.worker.block.BlockMasterSync.registerWithMaster(BlockMasterSync.java:108)
	at alluxio.worker.block.BlockMasterSync.<init>(BlockMasterSync.java:95)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:213)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:76)
	at alluxio.Registry.start(Registry.java:132)
	at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:283)
	at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:235)
	at alluxio.ProcessUtils.run(ProcessUtils.java:35)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:69)
Caused by: io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at alluxio.grpc.BlockMasterWorkerServiceGrpc$BlockMasterWorkerServiceBlockingStub.registerWorker(BlockMasterWorkerServiceGrpc.java:477)
	at alluxio.worker.block.BlockMasterClient.lambda$register$13(BlockMasterClient.java:199)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:372)
	... 11 more
2019-05-06 20:57:04,342 INFO  GrpcDataServer - Shutting down RPC Server at 0.0.0.0/0.0.0.0:29999.
2019-05-06 20:57:08,805 ERROR ProcessUtils - Uncaught exception while stopping Alluxio worker, simply exiting.
java.lang.NullPointerException
	at alluxio.worker.block.DefaultBlockWorker.stop(DefaultBlockWorker.java:262)
	at alluxio.Registry.stop(Registry.java:149)
	at alluxio.worker.AlluxioWorkerProcess.stopWorkers(AlluxioWorkerProcess.java:287)
	at alluxio.worker.AlluxioWorkerProcess.stop(AlluxioWorkerProcess.java:274)
	at alluxio.ProcessUtils.run(ProcessUtils.java:41)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:69)
```

**Comment by ZacBlanco** [comment]
@apc999 can we close this now?

**Comment by apc999** [comment]
Close this issue due to this fix  https://github.com/Alluxio/alluxio/pull/9090
