### ISSUE TITLE
NoClassDefFoundError while mount the hadoop-2.7 version ufs

### ISSUE THREAD

**Issue by maobaolong** [Alluxio/alluxio#8998]
**Alluxio Version:**
2.0.0-SNAPSHOT, in fact, i build it in 5/5/2019

**Describe the bug**
NoClassDefFoundError while mount the hadoop-2.7 version ufs.

After look the lib/*.jar, i find the `org.apache.commons.collections.map.UnmodifiableMap` in hadoop `alluxio-underfs-hadoop-2.2-2.0.0-SNAPSHOT.jar`, but cannot find it in `alluxio-underfs-hadoop-2.7-2.0.0-SNAPSHOT.jar`

**To Reproduce**
```bash
/software/servers/alluxio-2.0.0/bin/alluxio fs mount --option alluxio.underfs.hdfs.configuration=/software/servers/alluxio-2.0.0/hadoop-conf/clusterA/hadoop/hdfs-site.xml --option alluxio.underfs.version=2.7 /tmp/app-logs/ hdfs://ns19/tmp/app-logs/
```

**Expected behavior**

mount failed with null output. IllegalArgumentException occurred in master.log and caused by NoClassDefFoundError

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

- master.log

```
java.lang.IllegalArgumentException: Unable to create an UnderFileSystem instance for path: hdfs://ns19/tmp/app-logs
	at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:134)
	at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:76)
	at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:128)
	at alluxio.underfs.AbstractUfsManager.lambda$addMount$9(AbstractUfsManager.java:164)
	at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:60)
	at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:2653)
	at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:2617)
	at alluxio.master.file.DefaultFileSystemMaster.mount(DefaultFileSystemMaster.java:2593)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$mount$48(FileSystemMasterClientServiceHandler.java:301)
	at alluxio.RpcUtils.call(RpcUtils.java:193)
	at alluxio.RpcUtils.call(RpcUtils.java:166)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.mount(FileSystemMasterClientServiceHandler.java:300)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2016)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:52)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at alluxio.concurrent.jsr.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1378)
	at alluxio.concurrent.jsr.ForkJoinTask.doExec(ForkJoinTask.java:609)
	at alluxio.concurrent.jsr.ForkJoinPool.runWorker(ForkJoinPool.java:1355)
	at alluxio.concurrent.jsr.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:131)
	Suppressed: java.lang.NoClassDefFoundError: org/apache/commons/collections/map/UnmodifiableMap
		at org.apache.hadoop.conf.Configuration$DeprecationContext.<init>(Configuration.java:409)
		at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:448)
		at alluxio.underfs.hdfs.HdfsUnderFileSystem.createConfiguration(HdfsUnderFileSystem.java:208)
		at alluxio.underfs.hdfs.HdfsUnderFileSystem.createInstance(HdfsUnderFileSystem.java:108)
		at alluxio.underfs.hdfs.HdfsUnderFileSystemFactory.create(HdfsUnderFileSystemFactory.java:44)
		at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:118)
		... 29 more
	Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.map.UnmodifiableMap
		at java.lang.ClassLoader.findClass(ClassLoader.java:530)
		at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.findClass(ExtensionsClassLoader.java:41)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.loadClass(ExtensionsClassLoader.java:51)
		at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 35 more
```

**Comment by apc999** [comment]
you need to build hadoop 2.7 UFS. We will provide documentation on how to make this UFS available under `lib/` directory. See documentation at https://docs.alluxio.io/os/user/edge/en/ufs/HDFS.html#mount-hdfs-with-specific-versions

**Comment by maobaolong** [comment]
Thank you, i will try.

**Comment by maobaolong** [comment]
@apc999  I have tried, but the problem still have. And it is the same in version Alluxio-1.8.2-SNAPSHOT

**Comment by maobaolong** [comment]
the 1.8.2 error callstack

```
2019-05-13 18:39:29,401 ERROR MasterUfsManager - Unable to create an UnderFileSystem instance for path: hdfs://ns1003/tmp/app-logs
2019-05-13 18:39:29,401 ERROR FileSystemMasterClientServiceHandler - Exit (Error): Mount: alluxioPath=/tmp/app-logs, ufsPath=hdfs://ns1003/tmp/app-logs, options=MountTOptions(readOnly:true, properties:{alluxio.underfs.hdfs.configuration=/software/servers/alluxio-2.0.0/hadoop-conf/hope/hdfs-site.xml, alluxio.underfs.version=2.2}, shared:false, commonOptions:FileSystemMasterCommonTOptions(syncIntervalMs:-1))
java.lang.IllegalArgumentException: Unable to create an UnderFileSystem instance for path: hdfs://ns1003/tmp/app-logs
    at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:117)
    at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:127)
    at alluxio.underfs.AbstractUfsManager.access$000(AbstractUfsManager.java:35)
    at alluxio.underfs.AbstractUfsManager$1.get(AbstractUfsManager.java:155)
    at alluxio.underfs.AbstractUfsManager$1.get(AbstractUfsManager.java:152)
    at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:53)
    at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:3009)
    at alluxio.master.file.DefaultFileSystemMaster.mountAndJournal(DefaultFileSystemMaster.java:2941)
    at alluxio.master.file.DefaultFileSystemMaster.mount(DefaultFileSystemMaster.java:2911)
    at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$mount$10(FileSystemMasterClientServiceHandler.java:234)
    at alluxio.RpcUtils.call(RpcUtils.java:217)
    at alluxio.RpcUtils.call(RpcUtils.java:189)
    at alluxio.master.file.FileSystemMasterClientServiceHandler.mount(FileSystemMasterClientServiceHandler.java:233)
    at alluxio.thrift.FileSystemMasterClientService$Processor$mount.getResult(FileSystemMasterClientService.java:1737)
    at alluxio.thrift.FileSystemMasterClientService$Processor$mount.getResult(FileSystemMasterClientService.java:1721)
    at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
    at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
    at alluxio.master.file.FileSystemMasterClientServiceProcessor.process(FileSystemMasterClientServiceProcessor.java:78)
    at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:123)
    at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    Suppressed: java.lang.NoClassDefFoundError: org/apache/commons/collections/map/UnmodifiableMap
        at org.apache.hadoop.conf.Configuration$DeprecationContext.<init>(Configuration.java:409)
        at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:448)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem.createConfiguration(HdfsUnderFileSystem.java:145)
        at alluxio.underfs.hdfs.HdfsUnderFileSystem.createInstance(HdfsUnderFileSystem.java:89)
        at alluxio.underfs.hdfs.HdfsUnderFileSystemFactory.create(HdfsUnderFileSystemFactory.java:40)
        at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:102)
        ... 22 more
    Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.map.UnmodifiableMap
        at java.lang.ClassLoader.findClass(ClassLoader.java:530)
        at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.findClass(ExtensionsClassLoader.java:41)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at alluxio.extensions.ExtensionsClassLoader$DefaultClassLoader.loadClass(ExtensionsClassLoader.java:51)
        at alluxio.extensions.ExtensionsClassLoader.loadClass(ExtensionsClassLoader.java:82)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 28 more
```

**Comment by maobaolong** [comment]
BTW. i find two problem

- common.go

```
var hadoopDistributions = map[string]version{
	"hadoop-1.0": parseVersion("1.0.4"),
	"hadoop-1.2": parseVersion("1.2.1"),
	"hadoop-2.2": parseVersion("2.2.0"),
	"hadoop-2.3": parseVersion("2.3.0"),
	"hadoop-2.4": parseVersion("2.4.1"),
	"hadoop-2.5": parseVersion("2.5.2"),
	"hadoop-2.6": parseVersion("2.6.5"),
	"hadoop-2.7": parseVersion("2.7.3"),
	"hadoop-2.8": parseVersion("2.8.0"),
	"hadoop-2.9": parseVersion("2.9.0"),
	// This distribution type is built with 2.2.0, but doesn't include the hadoop version in the name.
	"default": parseVersion("2.2.0"),
}
```

in fact we need a 2.7.1 as "hadoop-2.7", because we are maintain a hadoop-2.7.1 version, and we modified it, so before we build alluxio, we need to install our hadoop-2.7.1 into the repo, actually, we need alluxio use our hadoop-2.7.1 to build its package.

Shortly, we need to specify the Hadoop-version in the tarball command.


- Another problem

i really cannot find the UnmodifiableMap.class in Alluxio CLASSPATH.
