### ISSUE TITLE
Building Alluxio from source, cannot open alluxio web with 19999 port

### ISSUE THREAD

**Issue by geweixuan** [Alluxio/alluxio#9005]
**Alluxio Version:**
What version of Alluxio are you using?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
![issue](https://user-images.githubusercontent.com/36925694/57278414-f5c3af80-70d8-11e9-9523-9bc01e6a0c2c.png)

**Comment by ZacBlanco** [comment]
Hi @geweixuan! We'll need some more information to debug your issue. Everything works fine on my end.

- What command did you use to build alluxio?
- Which branch are you building from?
- and also, if possible, what is the date you attempted to build?
- Are there any useful messages in `logs/master.log`?

**Comment by geweixuan** [comment]
2019-05-08 10:58:11,885 WARN  WebAppContext - Failed startup of context o.e.j.w.WebAppContext@7c6908d7{/,null,null}{/opt/FileServer/alluxio-1.8.1/core/server/common/src/main/webapp}
java.io.FileNotFoundException: /opt/FileServer/alluxio-1.8.1/core/server/common/src/main/webapp
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:493)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:468)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:504)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at alluxio.web.WebServer.start(WebServer.java:184)
	at alluxio.master.AlluxioMasterProcess.startServingWebServer(AlluxioMasterProcess.java:336)
	at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:308)
	at alluxio.master.AlluxioMasterProcess.startServing(AlluxioMasterProcess.java:296)
	at alluxio.master.AlluxioMasterProcess.start(AlluxioMasterProcess.java:229)
	at alluxio.ProcessUtils.run(ProcessUtils.java:32)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)

**Comment by ZacBlanco** [comment]
It looks like your installation of Alluxio doesn't include the necessary files at `/opt/FileServer/alluxio-1.8.1/core/server/common/src/main/webapp`.

What process did you follow to build and install Alluxio? If you follow the steps here to build (https://docs.alluxio.io/os/user/stable/en/contributor/Building-Alluxio-From-Source.html) and run `./bin/alluxio-start.sh local` then your web UI should appear.

Otherwise, if you need a tarball that can be installed elsewhere, you can run 
```
./dev/scripts/generate-tarballs single
```
which should generate a tarball you can put install under `/opt`

**Comment by geweixuan** [comment]
How to  include the necessary files at /opt/FileServer/alluxio-1.8.1/core/server/common/src/main/webapp.
I'm follow the steps of (https://docs.alluxio.io/os/user/stable/en/contributor/Building-Alluxio-From-Source.html)
alluxio version 1.8.1, doesn't have web UI

**Comment by ZacBlanco** [comment]
The following commands will check out v1.8.1 build, and then start it from the repository

```bash
git clone https://github.com/Alluxio/alluxio.git
cd alluxio
git checkout v1.8.1
mvn -T 2C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Dlicense.skip
./bin/alluxio-start-.sh local SudoMount
```

**Comment by apc999** [comment]
@geweixuan, does @ZacBlanco's instruction help here?

**Comment by calvinjia** [comment]
@geweixuan Closing this due to inactivity, please reopen if you still have this issue.
