### ISSUE TITLE
alluxio.exception.status.UnknownException in fuse 

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9020]
**Alluxio Version:**

v2.0.0

**Describe the bug**

I deployed the alluxio fuse in kubernetes by using [alluxio-fuse.yaml.template](https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/alluxio-fuse.yaml.template). The docker image is `alluxio/alluxio-fuse:2.0.0-SNAPSHOT`

But I see the error in logs:

```
2019-05-07 23:37:10,141 WARN  ChannelAuthenticator - Channel authentication failed. ChannelId: b80400fc-4d75-47d5-8b00-9bbbd795584e, AuthType: SIMPLE, Target: alluxio-master:19998, Error: alluxio.exception.status.UnknownException
2019-05-07 23:37:10,141 WARN  AbstractClient - Failed to connect (41) with FileSystemMasterClient @ alluxio-master/192.168.0.111:19998: Channel authentication failed. ChannelId: b80400fc-4d75-47d5-8b00-9bbbd795584e, AuthType: SIMPLE, Target: alluxio-master:19998, Error: alluxio.exception.status.UnknownException
```

And I tried to access the mounted directory, it's hang:

```
[root@iZhp3i15msyqpeqtzv9h0yZ ~]# cd /al^C
[root@iZhp3i15msyqpeqtzv9h0yZ ~]# ls -lt / | grep all
^C^C^C^C^C
``` 

The master looks good:

```
# /opt/alluxio/bin/alluxio fsadmin report
Alluxio cluster summary:
    Master Address: alluxio-master/192.168.0.111:19998
    Web Port: 19999
    Rpc Port: 19998
    Started: 05-07-2019 23:19:34:498
    Uptime: 0 day(s), 0 hour(s), 27 minute(s), and 59 second(s)
    Version: 2.0.0-preview
    Safe Mode: false
    Zookeeper Enabled: false
    Live Workers: 4
    Lost Workers: 0
    Total Capacity: 2000.00GB
        Tier: ssd  Size: 2000.00GB
    Used Capacity: 0B
        Tier: ssd  Size: 0B
    Free Capacity: 2000.00GB
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
I'm also able to see the error:

```
2019-05-08 23:30:49,200 ERROR AlluxioFuseFileSystem - Failed to get info of /
alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ alluxio-master/192.168.0.111:19998 after 44 attempts
	at alluxio.AbstractClient.connect(AbstractClient.java:267)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:370)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:352)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.getStatus(RetryHandlingFileSystemMasterClient.java:174)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:366)
	at alluxio.client.file.BaseFileSystem.getStatus(BaseFileSystem.java:355)
	at alluxio.fuse.AlluxioFuseFileSystem.getattr(AlluxioFuseFileSystem.java:316)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$1(AbstractFuseFS.java:95)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$0.invoke(Unknown Source)
Caused by: alluxio.exception.status.UnknownException: Channel authentication failed. ChannelId: 8cce0a1d-337e-4b69-bccb-83311cbdc732, AuthType: SIMPLE, Target: alluxio-master:19998, Error: alluxio.exception.status.UnknownException
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
	at alluxio.security.authentication.ChannelAuthenticator$AuthenticatedManagedChannel.authenticate(ChannelAuthenticator.java:168)
	at alluxio.security.authentication.ChannelAuthenticator$AuthenticatedManagedChannel.<init>(ChannelAuthenticator.java:135)
	at alluxio.security.authentication.ChannelAuthenticator.authenticate(ChannelAuthenticator.java:122)
	at alluxio.grpc.GrpcChannelBuilder.build(GrpcChannelBuilder.java:222)
	at alluxio.AbstractClient.connect(AbstractClient.java:233)
	... 8 more
Caused by: alluxio.exception.status.UnknownException
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:209)
	at alluxio.security.authentication.SaslStreamClientDriver.start(SaslStreamClientDriver.java:122)
	at alluxio.security.authentication.ChannelAuthenticator$AuthenticatedManagedChannel.authenticate(ChannelAuthenticator.java:158)
	... 12 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:530)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cheyang** [comment]
This is the deployment yaml I am using, and the logs in fuse side:
[kubernetes.zip](https://github.com/Alluxio/alluxio/files/3159654/kubernetes.zip)

[logs.tar.zip](https://github.com/Alluxio/alluxio/files/3159656/logs.tar.zip)

**Comment by cheyang** [comment]
I'm wondering why it reports `Channel authentication failed`

```
2019-05-08 02:28:25,196 WARN  ChannelAuthenticator - Channel authentication failed. ChannelId: 5229becf-a664-4dc1-8969-ad7641529ea1, AuthType: SIMPLE, Target: alluxio-master:19998, Error: alluxio.exception.status.UnknownException
2019-05-08 02:28:25,196 WARN  AbstractClient - Failed to connect (11) with FileSystemMasterClient @ alluxio-master/192.168.0.111:19998: Channel authentication failed. ChannelId: 5229becf-a664-4dc1-8969-ad7641529ea1, AuthType: SIMPLE, Target: alluxio-master:19998, Error: alluxio.exception.status.UnknownException
2019-05-08 02:28:25,299 INFO  AbstractClient - Alluxio client (version 2.0.0-SNAPSHOT) is trying to connect with FileSystemMasterClient @ alluxio-master/192.168.0.111:19998
2019-05-08 02:28:25,300 WARN  ChannelAuthenticator - Channel authentication failed. ChannelId: 25d735fa-398a-4672-b9a8-94c32f784d40, AuthType: SIMPLE, Target: alluxio-master:19998, Error: alluxio.exception.status.UnknownException
2019-05-08 02:28:25,300 WARN  AbstractClient - Failed to connect (26) with FileSystemMasterClient @ alluxio-master/192.168.0.111:19998: Channel authentication failed. ChannelId: 25d735fa-398a-4672-b9a8-94c32f784d40, AuthType: SIMPLE, Target: alluxio-master:19998, Error: alluxio.exception.status.UnknownException
2019-05-08 02:28:25,426 INFO  AbstractClient - Alluxio client (version 2.0.0-SNAPSHOT) is trying to connect with FileSystemMasterClient @ alluxio-master/192.168.0.111:19998
```

**Comment by madanadit** [comment]
might be because of version mismatch. to be verified.
