### ISSUE TITLE
Failed to read directory from alluxio fuse

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9063]
**Alluxio Version:**
2.0.0-snapshot, and underlayer backend is aliyun OSS.

**Describe the bug**

1. copy the files from  mount point of alluxio fuse, and use ctrl+c to stop

```
time cp -r /alluxio-fuse/training-data/images /var/lib/test
^C
```

2. then access the mount point again

```
# ls -ltr
ls: reading directory .: Bad message
total 0
```

Checking the logs

```
2019-05-12 00:44:44,044 ERROR AlluxioFuseFileSystem - Failed to read directory /training-data/images
alluxio.exception.AlluxioException
	at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:99)
	at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:401)
	at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:383)
	at alluxio.fuse.AlluxioFuseFileSystem.readdir(AlluxioFuseFileSystem.java:538)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$10(AbstractFuseFS.java:171)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$13.invoke(Unknown Source)
Caused by: alluxio.exception.status.InternalException
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:148)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:209)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:374)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:352)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.listStatus(RetryHandlingFileSystemMasterClient.java:215)
	at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:395)
	... 4 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.listStatus(FileSystemMasterClientServiceGrpc.java:1547)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$listStatus$12(RetryHandlingFileSystemMasterClient.java:217)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:372)
	... 7 more
2019-05-12 00:45:11,033 ERROR AlluxioFuseFileSystem - Failed to read directory /training-data/images
alluxio.exception.AlluxioException
	at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:99)
	at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:401)
	at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:383)
	at alluxio.fuse.AlluxioFuseFileSystem.readdir(AlluxioFuseFileSystem.java:538)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$10(AbstractFuseFS.java:171)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$13.invoke(Unknown Source)
Caused by: alluxio.exception.status.InternalException
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:148)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:209)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:374)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:352)
	at alluxio.client.file.RetryHandlingFileSystemMasterClient.listStatus(RetryHandlingFileSystemMasterClient.java:215)
	at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:395)
	... 4 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
```
2019-05-12 01:42:00,079 ERROR FileSystemMasterClientServiceHandler - Exit (Error): ListStatus: path=/training-data/images, options=loadMetada
commonOptions {
  syncIntervalMs: -1
  ttl: -1
  ttlAction: DELETE
}

java.lang.NullPointerException
        at alluxio.StorageTierAssoc.getOrdinal(StorageTierAssoc.java:101)
        at alluxio.master.file.DefaultFileSystemMaster.isInTopStorageTier(DefaultFileSystemMaster.java:1931)
        at alluxio.master.file.DefaultFileSystemMaster.getInMemoryPercentage(DefaultFileSystemMaster.java:1892)
        at alluxio.master.file.DefaultFileSystemMaster.getFileInfoInternal(DefaultFileSystemMaster.java:901)
        at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1062)
        at alluxio.master.file.DefaultFileSystemMaster.listStatusInternal(DefaultFileSystemMaster.java:1055)
        at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:999)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$listStatus$8(FileSystemMasterClientServiceHandler.java:233)
        at alluxio.RpcUtils.call(RpcUtils.java:191)
        at alluxio.RpcUtils.call(RpcUtils.java:164)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.listStatus(FileSystemMasterClientServiceHandler.java:231)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2025)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:52)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
- master.log 585/664 88%
```

**Comment by cheyang** [comment]
So my question is :
1. How to recover it?
2.Can we do something to enhance robustness of the system?

**Comment by cheyang** [comment]
I'm able to see the error:
```
Inconsistent Files on Startup (run fs checkConsistency for details)
```

But when I try to recover it

```
# /opt/alluxio/bin/alluxio fs checkConsistency -r /training-data
/training-data has: 1154 inconsistent files.
repairing path: /training-data/images/train-00000-of-01024
A write operation on /training-data/images/train-00000-of-01024 under a readonly mount point /training-data/images is not allowed
```

**Comment by bf8086** [comment]
From the exception call stack the storage tier information on master is incorrect. @yuzhu can you take a look to see what might have gone wrong?

**Comment by madanadit** [comment]
@yuzhu what is the status of this issue? thx

**Comment by yuzhu** [comment]
@madanadit I haven't gotten around to it yet. Plan to take a look later today or early next week.

**Comment by madanadit** [comment]
@cheyang 
- please run `./bin/alluxio validateConf` to validate the conf
- please use the alias as `SSD` (all caps instead of lower case) and let us know if you still see the issue
thx

**Comment by apc999** [comment]
I submitted a fix 
https://github.com/Alluxio/alluxio/pull/9090 which will validate the tier alias to be known or fail the conf check. Close this Issue.
