### ISSUE TITLE
setfacl/getfacl with "default ACL" to a file makes alluxio-master exit with UnsupportedOperationException

### ISSUE THREAD

**Issue by chentao** [Alluxio/alluxio#9116]
**Alluxio Version:**
2.0-preview and 2.0 master branch

**Describe the bug**
setfacl to a file(not a directory) with the command:
     `alluxio fs setfacl  -m default:user:tchen:rwx /tmp/tchen/file1`

master.log produce logs below then the master process died unexpectly:
```
2019-05-17 10:02:44,609 ERROR InodeTreePersistentState - Fatal error: Failed to apply id: 33571209215
op_time_ms: 1558058564599
action: MODIFY
entries {
  type: NAMED_USER
  subject: "tchen"
  actions: READ
  actions: WRITE
  actions: EXECUTE
  isDefault: true
}

java.lang.UnsupportedOperationException: getDefaultACL: File does not have default ACL
	at alluxio.master.file.meta.MutableInodeFile.getDefaultACL(MutableInodeFile.java:124)
	at alluxio.master.file.meta.MutableInode.setAcl(MutableInode.java:405)
	at alluxio.master.file.meta.InodeTreePersistentState.applySetAcl(InodeTreePersistentState.java:348)
	at alluxio.master.file.meta.InodeTreePersistentState.applyAndJournal(InodeTreePersistentState.java:215)
	at alluxio.master.file.meta.InodeTree.setAcl(InodeTree.java:302)
	at alluxio.master.file.DefaultFileSystemMaster.setAclSingleInode(DefaultFileSystemMaster.java:2996)
	at alluxio.master.file.DefaultFileSystemMaster.setAclRecursive(DefaultFileSystemMaster.java:3017)
	at alluxio.master.file.DefaultFileSystemMaster.setAclInternal(DefaultFileSystemMaster.java:2947)
	at alluxio.master.file.DefaultFileSystemMaster.setAcl(DefaultFileSystemMaster.java:2906)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$setAcl$20(FileSystemMasterClientServiceHandler.java:385)
	at alluxio.RpcUtils.call(RpcUtils.java:191)
	at alluxio.RpcUtils.call(RpcUtils.java:164)
	at alluxio.master.file.FileSystemMasterClientServiceHandler.setAcl(FileSystemMasterClientServiceHandler.java:384)
	at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2045)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:52)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2019-05-17 10:02:44,611 INFO  AbstractMaster - MetaMaster: Stopping primary master.
2019-05-17 10:02:44,612 INFO  AbstractMaster - MetaMaster: Stopped primary master.
2019-05-17 10:02:44,612 INFO  AbstractMaster - FileSystemMaster: Stopping primary master.
2019-05-17 10:02:44,613 INFO  AbstractMaster - FileSystemMaster: Stopped primary master.
2019-05-17 10:02:44,613 INFO  AbstractMaster - BlockMaster: Stopping primary master.
2019-05-17 10:02:44,613 INFO  AbstractMaster - BlockMaster: Stopped primary master.
2019-05-17 10:02:44,613 INFO  AbstractMaster - MetricsMaster: Stopping primary master.
2019-05-17 10:02:44,613 INFO  AbstractMaster - MetricsMaster: Stopped primary master.
```

setfacl/getfacl to a directory is OK

**To Reproduce**
see "Describe the bug"

**Expected behavior**
if the UnsupportedOperationException get caught at the execution of the command and print out some information to user would be better

**Urgency**
please resolve it at Alluxio 2.0 GA

**Additional context**
deployment: 1 master, 1 worker with a 6 nodes HDFS cluster

alluxio-site.properties:
```
alluxio.master.hostname=host123
alluxio.underfs.address=hdfs://ns1/
alluxio.worker.memory.size=32GB
alluxio.underfs.hdfs.configuration=/etc/hadoop/conf.cloudera.hdfs/core-site.xml:/etc/hadoop/conf.cloudera.hdfs/hdfs-site.xml
```

**Comment by bf8086** [comment]
@yuzhu Can you take a look at this issue?

**Comment by bf8086** [comment]
@chentao We have made a fix to the issue, @chentao can you download latest RC3 and see if the issue is resolved for you?

**Comment by calvinjia** [comment]
@chentao Closing this due to inactivity, please reopen if you still have this issue.
