### ISSUE TITLE
FUSE mount fails after 60mins of inactivity.

### ISSUE THREAD

**Issue by mingfang** [Alluxio/alluxio#9150]
I've experience this problem and it was also discussed here https://github.com/Alluxio/alluxio/issues/9089

Setting `alluxio.security.stale.channel.purge.interval=365d` works around the problem.

**Comment by mingfang** [comment]
Actually I'm still having problems even after changing the stale interval to 365d.

Here are the errors on the master and worker logs
```
alluxio-master-5f7cbf88c9-5c4bm alluxio May 28, 2019 2:55:49 PM io.grpc.internal.SerializingExecutor run
alluxio-master-5f7cbf88c9-5c4bm alluxio SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@4878421a
alluxio-master-5f7cbf88c9-5c4bm alluxio java.lang.IllegalStateException: call already closed
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:172)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector.authenticateCall(AuthenticatedUserInjector.java:98)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector.access$000(AuthenticatedUserInjector.java:34)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:66)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at java.lang.Thread.run(Thread.java:748)
alluxio-master-5f7cbf88c9-5c4bm alluxio 
alluxio-master-5f7cbf88c9-5c4bm alluxio May 28, 2019 2:55:50 PM io.grpc.internal.SerializingExecutor run
alluxio-master-5f7cbf88c9-5c4bm alluxio SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@60c68c4c
alluxio-master-5f7cbf88c9-5c4bm alluxio java.lang.IllegalStateException: call already closed
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:172)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector.authenticateCall(AuthenticatedUserInjector.java:98)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector.access$000(AuthenticatedUserInjector.java:34)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:66)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
alluxio-master-5f7cbf88c9-5c4bm alluxio 	at java.lang.Thread.run(Thread.java:748)
alluxio-master-5f7cbf88c9-5c4bm alluxio 
alluxio-worker-r5rsb alluxio May 28, 2019 2:55:50 PM io.grpc.internal.SerializingExecutor run
alluxio-worker-r5rsb alluxio SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7133e041
alluxio-worker-r5rsb alluxio java.lang.IllegalStateException: call already closed
alluxio-worker-r5rsb alluxio 	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
alluxio-worker-r5rsb alluxio 	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:172)
alluxio-worker-r5rsb alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector.authenticateCall(AuthenticatedUserInjector.java:98)
alluxio-worker-r5rsb alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector.access$000(AuthenticatedUserInjector.java:34)
alluxio-worker-r5rsb alluxio 	at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:66)
alluxio-worker-r5rsb alluxio 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
alluxio-worker-r5rsb alluxio 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
alluxio-worker-r5rsb alluxio 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
alluxio-worker-r5rsb alluxio 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
alluxio-worker-r5rsb alluxio 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
alluxio-worker-r5rsb alluxio 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
alluxio-worker-r5rsb alluxio 	at java.lang.Thread.run(Thread.java:748)
alluxio-worker-r5rsb alluxio 
alluxio-worker-r5rsb alluxio May 28, 2019 2:55:50 PM io.grpc.netty.NettyServerHandler onStreamError
alluxio-worker-r5rsb alluxio WARNING: Stream Error
alluxio-worker-r5rsb alluxio io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 7
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:531)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:183)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:421)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
alluxio-worker-r5rsb alluxio 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
alluxio-worker-r5rsb alluxio 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
alluxio-worker-r5rsb alluxio 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
alluxio-worker-r5rsb alluxio 	at java.lang.Thread.run(Thread.java:748)
a
```

**Comment by bf8086** [comment]
@ggezer Will the new callstack fixed by https://github.com/Alluxio/alluxio/pull/9149?

**Comment by ggezer** [comment]
@mingfang What is the scenario that is causing these? Also, are you seeing any user level read/write errors during when these traces are dumped?

**Comment by mingfang** [comment]
My test case is pretty low tech. 
1. I bring up the entire alluxio cluster.
2. connect a FUSE client.
3. Do a `ls` or `head *` to make sure the mount works
4. Leave everything idle for an hour
5. Then repeat step 3 to see the problem.

**Comment by mingfang** [comment]
Btw this problem was when using 2.0.0-SNAPSHOT here https://hub.docker.com/r/alluxio/alluxio/tags
I'm trying to recreate the problem using 2.0.0-RC1 now.

**Comment by ggezer** [comment]
Just to clarify, does step 5 fails in shell?

**Comment by mingfang** [comment]
Yes, in shell. ls works but head fails.

I'm unable to recreate the issue using 2.0.0-RC1 so I'm going to close this for now.
@ggezer Thanks for looking.

**Comment by ggezer** [comment]
If `ls` works but `head` doesn't, it's possible that the property was not set for workers. I suggest double checking that worker also has that property set.
