### ISSUE TITLE
Failed to deploy alluxio 2.0 snapshot in kubernetes

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9331]
**Alluxio Version:**
docker image: 2.0.0-SNAPSHOT/52655300b53a

**Describe the bug**

I'm trying to deploy latest alluxio version in kubernetes. But it's failed, and master reported
```
2019-06-19 00:52:55,091 ERROR ProcessUtils - Uncaught exception while running Alluxio master @alluxio-master:19998, stopping it and exiting.
java.io.IOException: Failed to bootstrap raft cluster with addresses [alluxio-master:19200]: java.nio.channels.UnresolvedAddressException
	at alluxio.master.journal.raft.RaftJournalSystem.startInternal(RaftJournalSystem.java:490)
	at alluxio.master.journal.AbstractJournalSystem.start(AbstractJournalSystem.java:50)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.start(FaultTolerantAlluxioMasterProcess.java:72)
	at alluxio.ProcessUtils.run(ProcessUtils.java:35)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)
Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:218)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:191)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
```

I suspect somewhere should configure to address 0.0.0.0.

**To Reproduce**
I will attach the yaml to upload.

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
The yaml I'm using to deploy here:
[master-format.txt](https://github.com/Alluxio/alluxio/files/3303989/master-format.txt)
[worker-format.txt](https://github.com/Alluxio/alluxio/files/3303992/worker-format.txt)
[alluxio.txt](https://github.com/Alluxio/alluxio/files/3303993/alluxio.txt)

**Comment by cheyang** [comment]
The interesting thing is that I'm able to set environment variables successfully, but looks like it's not consumed by alluxio master.

```
bash-4.4# /opt/alluxio/bin/alluxio  getConf | grep master| grep jou| grep type

alluxio.master.journal.type=EMBEDDED
bash-4.4#
bash-4.4# env | grep MASTER
ALLUXIO_MASTER_JOURNAL_FOLDER=/journal
ALLUXIO_MASTER_JOURNAL_TYPE=UFS
ALLUXIO_MASTER_PORT=19998
ALLUXIO_MASTER_WEB_PORT=19999
ALLUXIO_MASTER_HOSTNAME=alluxio-master
```

**Comment by cheyang** [comment]
The master can start successfully. but the workers are still not able to start. I can see the environment variables `ALLUXIO_JAVA_OPT` are set successfully, but the alluxio worker seems not able to load it.

```
bash-4.4# env | grep -i master
ALLUXIO_JAVA_OPT=-Dalluxio.master.hostname=alluxio-master -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal -Dalluxio.worker.data.server.domain.socket.address=/opt/domain -Dalluxio.worker.data.server.domain.socket.as.uuid=true -Dalluxio.master.port=19998 -Dalluxio.master.web.port=19999 -Dalluxio.worker.port=29998 -Dalluxio.worker.data.port=29999 -Dalluxio.worker.web.port=29996 -Dalluxio.worker.memory.size=16GB -Dalluxio.security.stale.channel.purge.interval=365d -Dalluxio.worker.tieredstore.level0.alias=SSD -Dalluxio.worker.tieredstore.level0.dirs.path=/var/lib/docker/alluxio -Dalluxio.worker.tieredstore.level0.dirs.quota=500GB -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.9 -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7
bash-4.4# /entrypoint.sh worker-only
Formatting Alluxio Worker @ iZhp3i15msyqpeqtzv9h0wZ
2019-06-19 11:57:31,405 INFO  Format - Formatting worker data folder: /alluxioworker/
2019-06-19 11:57:31,406 INFO  Format - Formatting Data path for tier 0:/dev/shm/alluxioworker
2019-06-19 11:57:31,491 INFO  Format - Formatting complete
2019-06-19 11:57:32,416 ERROR AlluxioWorker - Fatal error: Cannot run Alluxio worker; Unable to determine master address. Please modify alluxio-site.properties to either set alluxio.master.hostname, configure zookeeper with alluxio.zookeeper.enabled=true and alluxio.zookeeper.address=[comma-separated zookeeper master addresses], or utilize internal HA by setting alluxio.master.embedded.journal.addresses=[comma-separated alluxio master addresses]
```

**Comment by cheyang** [comment]
Thanks @mingfang,  I'm able to get it work now.

**Comment by JackieJ** [comment]
Hi @cheyang ,

I am getting the same deployment error on kubernetes. How did you work it around? Thanks.
