### ISSUE TITLE
NoSuchMethodError when use filesystem api

### ISSUE THREAD

**Issue by Chopinxb** [Alluxio/alluxio#9403]
**Alluxio Version:**
Alluxio-2.0

**Describe the bug**

when we use this filesytem api to access alluxio cluster
```
  val conf: InstancedConfiguration = new InstancedConfiguration(ConfigurationUtils.defaults())
  System.out.println(masterAddress.getHost() + ' ' + masterAddress.getPort())
  conf.set(PropertyKey.MASTER_HOSTNAME, masterAddress.getHost())
  conf.set(PropertyKey.MASTER_RPC_PORT, Integer.toString(masterAddress.getPort()))
  val fs = FileSystem.Factory.create(conf)
```
we will meet exception below:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Hex.encodeHexString([B)Ljava/lang/String;
	at alluxio.conf.Hash.compute(Hash.java:59)
	at alluxio.conf.Hash.get(Hash.java:73)
	at alluxio.conf.AlluxioProperties.hash(AlluxioProperties.java:271)
	at alluxio.conf.InstancedConfiguration.hash(InstancedConfiguration.java:421)
	at alluxio.ClientContext.<init>(ClientContext.java:99)
	at alluxio.ClientContext.create(ClientContext.java:61)
	at alluxio.client.file.FileSystemContext.create(FileSystemContext.java:166)
	at alluxio.client.file.FileSystemContext.create(FileSystemContext.java:155)
	at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:117)
	at AlluxioUtil.<init>(AlluxioUtil.scala:22)
```
this is because in maven repo dependencies:

alluxio-core-client-fs:2.0.0 -->  alluxio-core-common:2.0.0 --> commons.httpclient:3.1 --> 
commons-codec:1.2

while in commons-codec:1.2,  Hex do not have  encodeHexString function.
in alluxio source code , we find that commons-codec's version is 1.10  in pom.xml

**Comment by Binyang2014** [comment]
Seems PR https://github.com/Alluxio/alluxio/pull/10201 revert this change. For 2.2.0 version, it still has such issue.

**Comment by Admasnd** [comment]
2.2.1 also has this issue. Explicitly added the latest version of common-codecs (1.14) to my project dependencies, however, resolves the issue.

**Comment by yuzhu** [comment]
Thanks for reporting, will take a look
