### ISSUE TITLE
Load data failed due to java.net.UnknownHostException

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9409]
**Alluxio Version:**
2.0.0

**Describe the bug**

Using `/opt/alluxio/bin/alluxio fs -Dalluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.DeterministicHashPolicy  load /training-data/images/` to load data from the under storage system to alluxio system, it's failed and report

```
WARNING: [io.grpc.internal.ManagedChannelImpl-235] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host iZhp3bku0ru8vuxq08lorxZ, cause=java.lang.RuntimeException: java.net.UnknownHostException: iZhp3bku0ru8vuxq08lorxZ
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:399)
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:269)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: iZhp3bku0ru8vuxq08lorxZ
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:624)
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:367)
	... 5 more
```

**To Reproduce**
1. Deploy the alluxio cluster successfully, and check the status. It looks good.

```
# /opt/alluxio/bin/alluxio fsadmin report
Alluxio cluster summary:
    Master Address: alluxio-master:19998
    Web Port: 19999
    Rpc Port: 19998
    Started: 06-30-2019 09:38:27:895
    Uptime: 2 day(s), 16 hour(s), 33 minute(s), and 45 second(s)
    Version: 2.0.0
    Safe Mode: false
    Zookeeper Enabled: false
    Live Workers: 4
    Lost Workers: 0
    Total Capacity: 2400.00GB
        Tier: MEM  Size: 400.00GB
        Tier: SSD  Size: 2000.00GB
    Used Capacity: 9.90GB
        Tier: MEM  Size: 9.90GB
        Tier: SSD  Size: 0B
    Free Capacity: 2390.10GB
```
2. And check the capacity, the worker is already registered.
```
/opt/alluxio/bin/alluxio fsadmin report capacity
Capacity information for all workers:
    Total Capacity: 2400.00GB
        Tier: MEM  Size: 400.00GB
        Tier: SSD  Size: 2000.00GB
    Used Capacity: 9.90GB
        Tier: MEM  Size: 9.90GB
        Tier: SSD  Size: 0B
    Used Percentage: 0%
    Free Percentage: 100%

Worker Name                  Last Heartbeat   Storage       Total            MEM           SSD
iZhp3bku0ru8vuxq08loruZ      0                capacity      600.00GB         100.00GB      500.00GB
                                              used          0B (0%)          0B            0B
iZhp3bku0ru8vuxq08lorvZ      0                capacity      600.00GB         100.00GB      500.00GB
                                              used          0B (0%)          0B            0B
iZhp3bku0ru8vuxq08lorxZ      0                capacity      600.00GB         100.00GB      500.00GB
                                              used          0B (0%)          0B            0B
iZhp3bku0ru8vuxq08lorwZ      0                capacity      600.00GB         100.00GB      500.00GB
                                              used          9.90GB (1%)      9.90GB        0B
```

3. And run load data

```
# /opt/alluxio/bin/alluxio fs -Dalluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.DeterministicHashPolicy  load /training-data/images/
Jul 03, 2019 12:14:37 AM io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl onError
WARNING: [io.grpc.internal.ManagedChannelImpl-137] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host iZhp3bku0ru8vuxq08loruZ, cause=java.lang.RuntimeException: java.net.UnknownHostException: iZhp3bku0ru8vuxq08loruZ
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:399)
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:269)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: iZhp3bku0ru8vuxq08loruZ
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:624)
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:367)
	... 5 more
}
```

**Expected behavior**
I think the worker is already registered into the alluxio master, it's no need to use DNS to discover it.  Can you enhance it? Thanks.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by madanadit** [comment]
Hi yang, i notice that the worker hostname is not set to physical host IP in your template. I believe you are using an older version of the template, this was updated just before the 2.0 release

for the worker container set:
``` 
          - name: ALLUXIO_WORKER_JAVA_OPTS
            value: " -Dalluxio.worker.hostname=$(ALLUXIO_WORKER_HOSTNAME) "
```
i see its only set for the job worker container (same pod as worker)

**Comment by cheyang** [comment]
I think we need also add `alluxio.job.worker.hostname` to job worker.

```
- name: ALLUXIO_JOB_WORKER_JAVA_OPTS
   value: " -Dalluxio.job.worker.hostname=$(ALLUXIO_WORKER_HOSTNAME) "
```


because from the logging I see
```
2019-07-10 23:35:48,623 WARN  JobCoordinator - Failed to select executor. Failed to find enough block workers to replicate to. Needed 4 but only found 0. Available workers without the block: []. The following workers could not be used because they have no local job workers: [192.168.0.120, 192.168.0.119, 192.168.0.118, 192.168.0.117])
2019-07-10 23:35:48,645 INFO  JobCoordinator - Starting job LoadConfig{FilePath=/training-data/images/train-00550-of-01024, Replication=4}
2019-07-10 23:35:48,646 WARN  LoadDefinition - Worker on host 192.168.0.120 has no local job worker
2019-07-10 23:35:48,646 WARN  LoadDefinition - Worker on host 192.168.0.119 has no local job worker
2019-07-10 23:35:48,646 WARN  LoadDefinition - Worker on host 192.168.0.118 has no local job worker
2019-07-10 23:35:48,646 WARN  LoadDefinition - Worker on host 192.168.0.117 has no local job worker
2019-07-10 23:35:48,647 WARN  JobCoordinator - Failed to select executor. Failed to find enough block workers to replicate to. Needed 4 but only found 0. Available workers without the block: []. The following workers could not be used because they have no local job workers: [192.168.0.120, 192.168.0.119, 192.168.0.118, 192.168.0.117])
```

**Comment by madanadit** [comment]
The job worker hostname should default to the worker hostname property.  Just make sure the spacing and quotation marks in the value are exactly as I pasted above. Let me know if this issue persists. Thx

**Comment by cheyang** [comment]
But after I added the configuration above, it looks still not be able to recognize the worker and job worker in the same node.

```
2019-07-11 00:09:15,192 WARN  JobCoordinator - Failed to select executor. Failed to find enough block workers to replicate to. Needed 4 but only found 0. Available workers without the block: []. The following workers could not be used because they have no local job workers: [192.168.0.118, 192.168.0.120, 192.168.0.117, 192.168.0.120, 192.168.0.119, 192.168.0.119, 192.168.0.118, 192.168.0.117])
2019-07-11 00:09:15,213 INFO  JobCoordinator - Starting job LoadConfig{FilePath=/training-data/images/train-00550-of-01024, Replication=4}
2019-07-11 00:09:15,214 WARN  LoadDefinition - Worker on host 192.168.0.118 has no local job worker
2019-07-11 00:09:15,215 WARN  LoadDefinition - Worker on host 192.168.0.120 has no local job worker
2019-07-11 00:09:15,215 WARN  LoadDefinition - Worker on host 192.168.0.117 has no local job worker
2019-07-11 00:09:15,215 WARN  LoadDefinition - Worker on host 192.168.0.120 has no local job worker
2019-07-11 00:09:15,215 WARN  LoadDefinition - Worker on host 192.168.0.119 has no local job worker
2019-07-11 00:09:15,215 WARN  LoadDefinition - Worker on host 192.168.0.119 has no local job worker
2019-07-11 00:09:15,215 WARN  LoadDefinition - Worker on host 192.168.0.118 has no local job worker
2019-07-11 00:09:15,215 WARN  LoadDefinition - Worker on host 192.168.0.117 has no local job worker
2019-07-11 00:09:15,216 WARN  JobCoordinator - Failed to select executor. Failed to find enough block workers to replicate to. Needed 4 but only found 0. Available workers without the block: []. The following workers could not be used because they have no local job workers: [192.168.0.118, 192.168.0.120, 192.168.0.117, 192.168.0.120, 192.168.0.119, 192.168.0.119, 192.168.0.118, 192.168.0.117])
```

**Comment by cheyang** [comment]
> The job worker hostname should default to the worker hostname property. Just make sure the spacing and quotation marks in the value are exactly as I pasted above. Let me know if this issue persists. Thx

The issue still persists. Here is the command line of job worker, I'm able to see `-Dalluxio.job.worker.hostname=192.168.0.117`

```
/usr/bin/java -cp /opt/alluxio-2.0.0/conf/::/opt/alluxio-2.0.0/assembly/alluxio-server-2.0.0.jar -Dalluxio.job.worker.hostname=192.168.0.117 -Dalluxio.master.hostname=alluxio-master -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal -Dalluxio.worker.data.server.domain.socket.address=/opt/domain -Dalluxio.worker.data.server.domain.socket.as.uuid=true -Dalluxio.master.port=19998 -Dalluxio.master.web.port=19999 -Dalluxio.worker.port=29998 -Dalluxio.worker.data.port=29999 -Dalluxio.worker.web.port=29996 -Dalluxio.worker.memory.size=16GB -Dalluxio.security.stale.channel.purge.interval=365d -Dalluxio.worker.tieredstore.level1.alias=SSD -Dalluxio.worker.tieredstore.level1.dirs.path=/var/lib/docker/alluxio -Dalluxio.worker.tieredstore.level1.dirs.quota=500GB -Dalluxio.worker.tieredstore.level1.watermark.high.ratio=0.9 -Dalluxio.worker.tieredstore.level1.watermark.low.ratio=0.7 -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.9 -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7 -Dalluxio.worker.tieredstore.level0.dirs.quota=100GB -Dalluxio.worker.tieredstore.levels=2 -Dalluxio.master.jvm.monitor.enabled=true -Dalluxio.home=/opt/alluxio-2.0.0 -Dalluxio.conf.dir=/opt/alluxio-2.0.0/conf -Dalluxio.logs.dir=/opt/alluxio-2.0.0/logs -Dalluxio.user.logs.dir=/opt/alluxio-2.0.0/logs/user -Dalluxio.worker.tieredstore.level0.alias=MEM -Dalluxio.worker.tieredstore.level0.dirs.path=/dev/shm -Dlog4j.configuration=file:/opt/alluxio-2.0.0/conf/log4j.properties -Dorg.apache.jasper.compiler.disablejsr199=true -Djava.net.preferIPv4Stack=true -Dalluxio.logger.type=Console,JOB_WORKER_LOGGER alluxio.worker.AlluxioJobWorker
```

**Comment by apc999** [comment]
@cheyang  is the original `UnknownHostException` issue still showing up or fixed after the update on worker hostname?

**Comment by cheyang** [comment]
> @cheyang is the original `UnknownHostException` issue still showing up or fixed after the update on worker hostname?
I didn't see `UnknownHostException` error. But the load is still failed.

**Comment by madanadit** [comment]
@cheyang can you share logs from the job master pod and one of the job worker pods? i want to see if job worker registration succeeded

**Comment by madanadit** [comment]
```
kubectl logs -f alluxio-master-0 -c alluxio-job-master
kubectl logs -f alluxio-worker-<id> -c alluxio-job-worker
```

**Comment by cheyang** [comment]
I've uploaded the logging file:
[alluxio-job.zip](https://github.com/Alluxio/alluxio/files/3384490/alluxio-job.zip)

**Comment by madanadit** [comment]
I see that job workers are not picking up the hostname property. in job master, the workers registers with virtual ip

```
2019-06-30 09:55:24,538 INFO  JobMaster - registerWorker(): WorkerNetAddress: WorkerNetAddress{host=iZhp3bku0ru8vuxq08lorvZ, rpcPort=30001, dataPort=30002, webPort=30003, domainSocketPath=, tieredIdentity=TieredIdentity(node=iZhp3bku0ru8vuxq08lorvZ)} id: 1561887510075```

**Comment by madanadit** [comment]
@cheyang can you update the job worker JAVA_OPTS from what you had before to
```
- name: ALLUXIO_JOB_WORKER_JAVA_OPTS
   value: " -Dalluxio.worker.hostname=$(ALLUXIO_WORKER_HOSTNAME) "
```

seems like the job worker ignores `alluxio.job.worker.hostname` and uses `alluxio..worker.hostname` instead. 

i'll fix the k8s spec to use `ALLUXIO_JOB_WORKER_JAVA_OPTS` and the job worker code to respect `alluxio.job.worker.hostname`. thx again!

**Comment by cheyang** [comment]
Yeah! It can work now!

**Comment by apc999** [comment]
Great! Close this issue now
