### ISSUE TITLE
Failed to access the data inside alluxio

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9525]
**Alluxio Version:**
v2.0.0

**Describe the bug**
Running TensorFlow on alluxio fuse
1. Find the error in the tensorflow logs ()
```
2019-07-22T11:46:47.961284015Z I0722 11:46:47.960094 140585133606656 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, /data/imagenet/train-00479-of-01024; Input/output error
2019-07-22T11:46:47.961307309Z 	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
2019-07-22T11:46:47.961311255Z 	 [[{{node RemoteCall}}]]
2019-07-22T11:46:47.961314544Z 	 [[node input_processing/IteratorGetNext (defined at /perseus-demo/tensorflow-demo/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2697) ]]
2019-07-22T11:46:47.96131827Z 	 [[{{node cluster_56_1/merge_oidx_273}}]]
2019-07-22T11:46:48.239054392Z I0722 11:46:48.238798 140550806185728 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, /data/imagenet/train-00491-of-01024; Input/output error
2019-07-22T11:46:48.23907186Z 	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
```

2. Go to machine(192.168.0.117), and check the fuse log:

```
019-07-22 11:46:51,961 ERROR AlluxioFuseFileSystem - Failed closing /training-data/images/train-00044-of-01024 [in]
alluxio.exception.status.UnknownException: Unknown error (GrpcDataReader{request=block_id: 17532190720
offset: 0
length: 146401853
promote: true
chunk_size: 1048576
open_ufs_block_options {
  ufs_path: "oss://imagenet-huabei5/images/train-00044-of-01024"
  offset_in_file: 0
  block_size: 146401853
  maxUfsReadConcurrency: 2147483647
  mountId: 7278165762072039447
  no_cache: false
}
, address=WorkerNetAddress{host=192.168.0.117, rpcPort=29998, dataPort=29998, webPort=29996, domainSocketPath=/opt/domain/905527c6-7391-47ef-a600-ee935a962cf6, tieredIdentity=TieredIdentity(node=192.168.0.117, rack=null)}})
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
	at alluxio.client.block.stream.GrpcBlockingStream.toAlluxioStatusException(GrpcBlockingStream.java:261)
	at alluxio.client.block.stream.GrpcBlockingStream.checkError(GrpcBlockingStream.java:242)
	at alluxio.client.block.stream.GrpcBlockingStream.receive(GrpcBlockingStream.java:162)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.receiveDataMessage(GrpcDataMessageBlockingStream.java:84)
	at alluxio.client.block.stream.GrpcDataMessageBlockingStream.waitForComplete(GrpcDataMessageBlockingStream.java:115)
	at alluxio.client.block.stream.GrpcDataReader.close(GrpcDataReader.java:162)
	at alluxio.client.block.stream.BlockInStream.closeDataReader(BlockInStream.java:388)
	at alluxio.client.block.stream.BlockInStream.close(BlockInStream.java:348)
	at alluxio.client.file.FileInStream.closeBlockInStream(FileInStream.java:336)
	at alluxio.client.file.FileInStream.close(FileInStream.java:218)
	at alluxio.fuse.OpenFileEntry.close(OpenFileEntry.java:130)
	at alluxio.fuse.AlluxioFuseFileSystem.release(AlluxioFuseFileSystem.java:581)
	at ru.serce.jnrfuse.AbstractFuseFS.lambda$init$7(AbstractFuseFS.java:146)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$12.invoke(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:530)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at alluxio.grpc.GrpcChannel$ChannelResponseTracker$1$1.onClose(GrpcChannel.java:151)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:694)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 4278190359, max: 4294967296)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:652)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:606)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:89)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	... 1 more
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by cheyang** [comment]
And I notice the fuse configuration: -XX:MaxDirectMemorySize=4g，I think maybe I can change it to fix. But I have 2 questions:

1. Is it something leak? Why it requires so many memory.
2.How can I update the the XX:MaxDirectMemorySize of the fuse?

```
ps -ef|grep MaxDirectMemorySize
root      2809  2753  0 20:17 pts/3    00:00:00 grep --color=auto MaxDirectMemorySize
root     30920 30645  0 Jul12 ?        00:18:55 /usr/bin/java -cp :/opt/alluxio/integration/fuse/bin/../alluxio-fuse-2.0.0.jar -server -Xms1G -Xmx1G -XX:MaxDirectMemorySize=4g -Dalluxio.master.hostname=alluxio-master -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal -Dalluxio.worker.data.server.domain.socket.address=/opt/domain -Dalluxio.worker.data.server.domain.socket.as.uuid=true -Dalluxio.master.port=19998 -Dalluxio.master.web.port=19999 -Dalluxio.worker.port=29998 -Dalluxio.worker.data.port=29999 -Dalluxio.worker.web.port=29996 -Dalluxio.worker.memory.size=16GB -Dalluxio.security.stale.channel.purge.interval=365d -Dallux
```

**Comment by ns1123** [comment]
Hi Cheyang,

Please see the answers below:

1. I will try to get back to you on this, but depending on the number of clients that are concurrently accessing FUSE, 4G may not be enough.
2. For the value of XX:MaxDirectMemorySize, when you update the value in set_java_opts(), does the new value not reflect in the process option? What is the new value you specify?

Thanks,
Nakkul

**Comment by cheyang** [comment]
> Hi Cheyang,
> 
> Please see the answers below:
> 
> 1. I will try to get back to you on this, but depending on the number of clients that are concurrently accessing FUSE, 4G may not be enough.

I only have 4 clients. 

> 2. For the value of XX:MaxDirectMemorySize, when you update the value in set_java_opts(), does the new value not reflect in the process option? What is the new value you specify?

Since I'm using Kubernetes, I don't have chance to set. @madanadit
> 
> Thanks,
> Nakkul

**Comment by cheyang** [comment]
Here is the worker logs:

[alluxio-worker.log](https://github.com/Alluxio/alluxio/files/3420380/alluxio-worker.log)

**Comment by apc999** [comment]
Two issues here:
- Make direct MEM size configurable
- Check if there is direct MEM leak

**Comment by apc999** [comment]
@madanadit  is this issue related to your fix recently?

**Comment by madanadit** [comment]
it could be. @cheyang could you reproduce this with the 2.1.0-SNAPSHOT image? I recently fixed an alluxio client memory leak for another issue you had reported earlier

**Comment by cheyang** [comment]
May I know which PR fixed this issue? @madanadit

**Comment by cheyang** [comment]
I'm able to reproduce it with build: 2.1.0-SNAPSHOT-4614f177781cd4275ea0e0c41162e4e022311a5a


[diagnose_alluxio_1570701411.tar.gz](https://github.com/Alluxio/alluxio/files/3711828/diagnose_alluxio_1570701411.tar.gz)

If you need more info, please contact me in slack. Thanks.

**Comment by madanadit** [comment]
@cheyang I was hoping its the same issue as https://github.com/Alluxio/alluxio/pull/10001. But if you can still reproduce, it looks like its not. thx

**Comment by cheyang** [comment]
Could you take a look at it now?

**Comment by ggezer** [comment]
@cheyang Are you still having this problem?

**Comment by cheyang** [comment]
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory

I still have such issues. For now I have to set direct memory to 16GB which is not a good choice.

**Comment by rastogiasr** [comment]
@LuQQiu  - can you take a look when you have some time.

**Comment by dengweisysu** [comment]
I have the similar problem in 2.6.0 version.
<img width="1297" alt="wecom-temp-e847a40ca62acb0ef993e700e9b7c13d" src="https://user-images.githubusercontent.com/18375623/134630195-11777857-64cf-4086-9002-80fe9f68cf14.png">

and read side is blocked until timeout.
