### ISSUE TITLE
startSync failed

### ISSUE THREAD

**Issue by sunny19930321** [Alluxio/alluxio#9648]
ALLUXIO ENVIRONMENT:
(1) ALLUXIO 2.0.0
(2) HADOOP-2.8.2(HDFS)
(3) JAVA 1.8
bin/alluxio fs startSync /syncdir

 ActiveSyncManager - Fatal error: Failed to apply syncpoint_path: "/syncdir"
Does anybody know why？

**Comment by sunny19930321** [comment]
java.lang.RuntimeException: mountId for the syncPoint /user/liyang28 not found in the filterMap
        at alluxio.master.file.activesync.ActiveSyncManager.apply(ActiveSyncManager.java:427)
        at alluxio.master.file.activesync.ActiveSyncManager.applyAndJournal(ActiveSyncManager.java:256)
        at alluxio.master.file.DefaultFileSystemMaster.startSyncAndJournal(DefaultFileSystemMaster.java:3734)
        at alluxio.master.file.DefaultFileSystemMaster.startSync(DefaultFileSystemMaster.java:3757)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.lambda$startSync$17(FileSystemMasterClientServiceHandler.java:400)
        at alluxio.RpcUtils.call(RpcUtils.java:193)
        at alluxio.RpcUtils.call(RpcUtils.java:166)
        at alluxio.master.file.FileSystemMasterClientServiceHandler.startSync(FileSystemMasterClientServiceHandler.java:399)
        at alluxio.grpc.FileSystemMasterClientServiceGrpc$MethodHandlers.invoke(FileSystemMasterClientServiceGrpc.java:2126)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.ClientIpAddressInjector$1.onHalfClose(ClientIpAddressInjector.java:52)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at alluxio.security.authentication.AuthenticatedUserInjector$1.onHalfClose(AuthenticatedUserInjector.java:67)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

**Comment by ZacBlanco** [comment]
Hi @sunny19930321 

We please ask that you fill out the standard template when submitting issues.

Could you also share your `alluxio-site.properties` configuration?

**Comment by sunny19930321** [comment]
> Hi @sunny19930321
> 
> We please ask that you fill out the standard template when submitting issues.
> 
> Could you also share your `alluxio-site.properties` configuration?

**Comment by sunny19930321** [comment]
> Hi @sunny19930321
> 
> We please ask that you fill out the standard template when submitting issues.
> 
> Could you also share your `alluxio-site.properties` configuration?

Yes, I did not submit the question according to the template. Now I submit the following question again

**Comment by bf8086** [comment]
@yuzhu has this been resolved or do you need more information?

**Comment by yuzhu** [comment]
@bf8086  this has not been resolved, but hopefully with better logging we will know more should this problem occur in the future.

**Comment by gpang** [comment]
@sunny19930321 Does this issue still exist on version 2.1.x? There might be additional logging information in the newer version to help with the investigation. Thanks!
