### ISSUE TITLE
alluxio format reports error in getting started guide

### ISSUE THREAD

**Issue by niyue** [Alluxio/alluxio#9687]
**Alluxio Version:**
2.0.0

**Describe the bug**
It is probably a bug for documentation. In the getting started page (https://docs.alluxio.io/os/user/stable/en/Getting-Started.html), it asks users to run `./bin/alluxio format`, however, an error was reported like below in `alluxio-2.0.0/logs/task.log`:
```
86 [2019-08-09 05:51:25][localhost] 2019-08-09 05:51:25,858 INFO  Format - Formatting master journal: /Users/ss/dev/tools/alluxio-2.0.0/        journal/^M
  87 [2019-08-09 05:51:26][localhost] 2019-08-09 05:51:26,140 INFO  Format - Formatting complete^M
  88 [2019-08-09 05:51:26][localhost] Connection to localhost closed.^M
  89 Executing the following command on all worker nodes and logging to /Users/ss/dev/tools/alluxio-2.0.0/logs/task.log: /Users/ss/dev/tools/     alluxio-2.0.0/bin/alluxio formatWorker
  90 [localhost] Connecting as ss...
  91 [2019-08-09 05:54:35][localhost] Formatting Alluxio Worker @ ssmbp^M
  92 [2019-08-09 05:54:36][localhost] 2019-08-09 05:54:36,221 INFO  Format - Formatting worker data folder: /alluxioworker/^M
  93 [2019-08-09 05:54:36][localhost] 2019-08-09 05:54:36,222 INFO  Format - Formatting Data path for tier 0:/Volumes/ramdisk/alluxioworker^M
  94 [2019-08-09 05:54:36][localhost] 2019-08-09 05:54:36,239 ERROR Format - Failed to format^M
  95 [2019-08-09 05:54:36][localhost] java.nio.file.NoSuchFileException: /Volumes/ramdisk/alluxioworker^M
  96 [2019-08-09 05:54:36][localhost] at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)^M
  97 [2019-08-09 05:54:36][localhost] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)^M
  98 [2019-08-09 05:54:36][localhost] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)^M
  99 [2019-08-09 05:54:36][localhost] at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)^M
 100 [2019-08-09 05:54:36][localhost] at java.nio.file.Files.createDirectory(Files.java:674)^M
 101 [2019-08-09 05:54:36][localhost] at alluxio.cli.Format.formatWorkerDataFolder(Format.java:66)^M
 102 [2019-08-09 05:54:36][localhost] at alluxio.cli.Format.format(Format.java:136)^M
 103 [2019-08-09 05:54:36][localhost] at alluxio.cli.Format.main(Format.java:97)^M
 104 [2019-08-09 05:54:36][localhost] Connection to localhost closed.^M
 105 Executing the following command on all master nodes and logging to /Users/ss/dev/tools/alluxio-2.0.0/logs/task.log: /Users/ss/dev/tools/     alluxio-2.0.0/bin/alluxio formatJournal
```

**To Reproduce**
1) macOS 10.14.5
2) first time Alluxio user 
3) follow the quick start guide (https://docs.alluxio.io/os/user/stable/en/Getting-Started.html) but skip the AWS bonus section
4) the above error will be reported in alluxio-2.0.0/logs/task.log

**Expected behavior**
The getting started guide can be finished without any error

**Urgency**
High, since it affects first time user experience on macOS

**Additional context**
Currently it can be avoided by skipping the `./bin/alluxio format` step completely and do the next step `./bin/alluxio-start.sh local SudoMount` directly. And the `./bin/alluxio format` seems to work after that.

**Comment by apc999** [comment]
@niyue  `./bin/alluxio format` is not actually required if one runs `./bin/alluxio-start.sh local SudoMount`. I will update the documentation.

**Comment by apc999** [comment]
I plan to fix this issue together with https://github.com/Alluxio/alluxio/issues/9712
