### ISSUE TITLE
Failed to use RocksDB in Kubernetes

### ISSUE THREAD

**Issue by cheyang** [Alluxio/alluxio#9761]
**Alluxio Version:**

2.1.0-SNAPSHOT

**Describe the bug**

Change `HEAP` to `ROCKSDB` in the Kubernetes cluster. I'm able to see the erros:

```
2019-08-21 12:07:57,238 ERROR AlluxioMaster - Fatal error: Failed to create master process
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start masters
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:121)
	at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:389)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Failed to start masters
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:57)
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:119)
	... 2 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni8198214604534869932.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/librocksdbjni8198214604534869932.so)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:529)
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:55)
	... 3 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni8198214604534869932.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/librocksdbjni8198214604534869932.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at alluxio.master.metastore.rocks.RocksBlockStore.<init>(RocksBlockStore.java:68)
	at alluxio.master.MasterUtils.lambda$getBlockStoreFactory$1(MasterUtils.java:72)
	at alluxio.master.block.DefaultBlockMaster.<init>(DefaultBlockMaster.java:252)
	at alluxio.master.block.DefaultBlockMaster.<init>(DefaultBlockMaster.java:235)
	at alluxio.master.block.BlockMasterFactory.create(BlockMasterFactory.java:51)
	at alluxio.master.block.BlockMasterFactory.create(BlockMasterFactory.java:28)
	at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by rastogiasr** [comment]
Please provide details on how to reproduce and give details on your K8s environment.

**Comment by cheyang** [comment]
Follow the guide https://github.com/Alluxio/alluxio/tree/master/integration/kubernetes, the only change is 

```
cat << EOF > config.yaml
properties:
   alluxio.master.metastore: ROCKS
   alluxio.master.metastore.dir: /opt/alluxio/metastore
EOF

helm install -f config.yaml alluxio-repo/alluxio --version 2.1.0-SNAPSHOT
```

**Comment by madanadit** [comment]
Related PR: https://github.com/Alluxio/alluxio/pull/8515/files

**Comment by cheyang** [comment]
I'm trying to run with docker, still no luck.

```
docker run -d --user root   -p 19999:19999   --net=alluxio_nw   --name=alluxio-master   --hostname=alluxio-master   -e ALLUXIO_JAVA_OPTS="-Dalluxio.master.hostname=alluxio-master -Dalluxio.master.metastore=ROCKS "   -v journal:/opt/alluxio/journal   -v ufs:/opt/alluxio/underFSStorage   alluxio/alluxio:2.1.0-SNAPSHOT master
```

The error is 

```
019-08-22 11:46:23,070 ERROR AlluxioMaster - Fatal error: Failed to create master process
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start masters
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:121)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.<init>(FaultTolerantAlluxioMasterProcess.java:58)
	at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:387)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Failed to start masters
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:57)
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:119)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni7409597473179416834.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/librocksdbjni7409597473179416834.so)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:529)
	at alluxio.master.MasterUtils.createMasters(MasterUtils.java:55)
	... 4 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni7409597473179416834.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/librocksdbjni7409597473179416834.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at alluxio.master.metastore.rocks.RocksBlockStore.<init>(RocksBlockStore.java:68)
	at alluxio.master.MasterUtils.lambda$getBlockStoreFactory$1(MasterUtils.java:72)
	at alluxio.master.block.DefaultBlockMaster.<init>(DefaultBlockMaster.java:252)
	at alluxio.master.block.DefaultBlockMaster.<init>(DefaultBlockMaster.java:235)
	at alluxio.master.block.BlockMasterFactory.create(BlockMasterFactory.java:51)
	at alluxio.master.block.BlockMasterFactory.create(BlockMasterFactory.java:28)
	at alluxio.master.MasterUtils.lambda$createMasters$0(MasterUtils.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cheyang** [comment]
And I find that adding `export LD_LIBRARY_PATH=/lib64:$LD_LIBRARY_PATH` can fix this issue.

I think it's better fix this in Dockerfile.
