### ISSUE TITLE
Alluxio 1.8.1 with Yarn Integration

### ISSUE THREAD

**Issue by venukolluri** [Alluxio/alluxio#9766]
Hello Team,

We are trying to run alluxio in yarn mode in EMR cluster with 10 worker nodes. with alluxio.integration.yarn.workers.per.host.max property set 1 to ensure one alluxio worker per EMR worker node, but intermittently alluxio fails with below error
2019-08-21 21:18:23,363 ERROR ApplicationMaster - Error running Application Master
java.lang.RuntimeException: Failed to allocate 10 worker containers
	at alluxio.yarn.ContainerAllocator.allocateContainers(ContainerAllocator.java:124)
	at alluxio.yarn.ApplicationMaster.requestAndLaunchContainers(ApplicationMaster.java:335)
	at alluxio.yarn.ApplicationMaster.runApplicationMaster(ApplicationMaster.java:232)
	at alluxio.yarn.ApplicationMaster.main(ApplicationMaster.java:211)

in yarn logs I see its trying to use one yarn worker to start all 10 alluxio workers which doesn't has memory for 10 alluxio workers.

how do ensure one alluxio worker per yarn worker?

Thanks,
Venu

**Comment by gpang** [comment]
The recommendation is to run Alluxio outside of yarn, and have yarn applications just interact with Alluxio.
