### ISSUE TITLE
Zeppelin integration with Alluxio 2.0

### ISSUE THREAD

**Issue by mohanpothula** [Alluxio/alluxio#9774]
**Alluxio Version:**
What version of Alluxio are you using?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by mohanpothula** [comment]
Hi 
I am trying Zeeplin with Alluxio integration ,when running spark intractive queries getting class not found exception though add alluxio class jar in zeppelin class path as below
<img width="1071" alt="Screenshot 2019-08-15 at 3 33 49 PM" src="https://user-images.githubusercontent.com/17589088/63520299-11878000-c527-11e9-8b32-d84f0f08cb1f.png">

**Comment by mohanpothula** [comment]
I am using Alluxio 2.0 storage along with aws s3 bukcet.I have started Master slave Aluxio cluster and able to run the jobs using spark 2.x,However having issue when run spark interactive queries using Alluxio storage and it throwing the error below though set class path in Zeppelin env

Java.lang.RuntimeException: java.lang.ClassNotFoundException: Class alluxio.hadoop.FileSystem not found
  at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2596)
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3269)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
  at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:709)
 
**Steps taken**
Add the entries below in Zeppelin env

spark.driver.extraClassPath /App/Alluxio/alluxio-2.0.0/client/alluxio-2.0.0-client.jar
spark.driver.extraLibraryPath /usr/hdp/current/hadoop-client/lib/native:/usr/hdp/current/hadoop- 
spark.executor.extraClassPath /App/Alluxio/alluxio-2.0.0/client/alluxio-2.0.0-client.jar

**Versions**

Alluxio 2.0
ZooKeeper   3.4.6
Zeppelin Notebook 0.8.0
Saprk 2.3.2
HDP-3.1.0.0

Would appreciate if any advise on the issue above

**Comment by apc999** [comment]
hi @mohanpothula , here is an explanation why "Class alluxio.hadoop.FileSystem not found" is thrown, see  https://www.alluxio.io/blog/developer-tip-why-did-my-job-fail-with-error-message-class-alluxiohadoopfilesystem-not-found/

In addition, you can take a look at this and see if it helos

https://docs.alluxio.io/os/user/stable/en/compute/Spark.html#class-alluxiohadoopfilesystem-not-found-issues-with-sparksql-and-hive-metastore

Plus, how is Spark launched by Zeppelin? Is it running in standalone mode or by some other scheduler like YARN? For later, you may also need to inform YARN, see https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Yarn.html#configure-yarnapplicationclasspath

**Comment by bf8086** [comment]
Closing this issue due to inactivity. Please reopen it if you need more help.
