### ISSUE TITLE
Can I disable MEM? Just SSD in worker.

### ISSUE THREAD

**Issue by BobLiu20** [Alluxio/alluxio#9968]
**Alluxio Version:**
2.0.1

**Describe the bug**
I can't disable MEM

**To Reproduce**
Start master:
```
docker run -d --net=host \
             -v /data/alluxio_ufs:/underStorage \
             -e ALLUXIO_MASTER_HOSTNAME=10.68.71.145 \
             -e ALLUXIO_MASTER_MOUNT_TABLE_ROOT_UFS=/underStorage \
             -e ALLUXIO_JAVA_OPTS="-Dalluxio.master.tieredstore.global.level0.alias=SSD -Dalluxio.master.tieredstore.global.levels=1 -Dalluxio.master.tieredstore.global.mediumtype=SSD" \
             alluxio/alluxio:2.0.1 master
```
I had set levels = 1 and mediumtype = SSD in opts. But I got error:   
```
formatMaster is deprecated - use formatMasters instead
Formatting Alluxio Master @ localhost
Exception in thread "main" java.lang.IllegalStateException: Alias "MEM" on tier 0 on worker (configured by alluxio.worker.tieredstore.level0.alias) is not found in global tiered storage setting: SSD
        at com.google.common.base.Preconditions.checkState(Preconditions.java:862)
        at alluxio.conf.InstancedConfiguration.checkTieredStorage(InstancedConfiguration.java:597)
        at alluxio.conf.InstancedConfiguration.validate(InstancedConfiguration.java:411)
        at alluxio.util.ConfigurationUtils.reloadProperties(ConfigurationUtils.java:443)
        at alluxio.util.ConfigurationUtils.defaults(ConfigurationUtils.java:396)
        at alluxio.cli.Format.main(Format.java:85)
```

**Comment by ns1123** [comment]
Hi Bob,

I think this issue is seen due to the master conflicting with the default worker properties that are set on the worker such as `alluxio.worker.memory.size` and `alluxio.worker.tieredstore.global.level0.alias`. Can you double check to see if the worker settings conflict with the master global settings?

Thanks,
Nakkul

**Comment by BobLiu20** [comment]
@ns1123  Hi, I still not to start worker or any setting for worker. I am trying to run master with this config and encounter this error.
Thanks.

**Comment by ns1123** [comment]
@BobLiu20 Looking at the code, the default value for 'alluxio.worker.tieredstore.level0.alias=MEM'. The reasoning for this was to allow users to begin using Alluxio without having to explicitly set some of the properties. In your case, I would recommend setting this property on all the worker nodes to be 'alluxio.worker.tieredstore.level0.alias=SSD'. Please let me know if that resolves your problem.

**Comment by BobLiu20** [comment]
@ns1123  I had added ```alluxio.worker.tieredstore.level0.alias=SSD``` to ALLUXIO_JAVA_OPTS. See below:
```
docker run -d --net=host \
             -v /data/alluxio_ufs:/underStorage \
             -e ALLUXIO_MASTER_HOSTNAME=10.68.71.145 \
             -e ALLUXIO_MASTER_MOUNT_TABLE_ROOT_UFS=/underStorage \
             -e ALLUXIO_JAVA_OPTS="-Dalluxio.master.tieredstore.global.level0.alias=SSD -Dalluxio.master.tieredstore.global.levels=1 -Dalluxio.master.tieredstore.global.mediumtype=SSD -Dalluxio.worker.tieredstore.level0.alias=SSD" \
             alluxio/alluxio:2.0.1 master
```
But error still appear:
```
formatMaster is deprecated - use formatMasters instead
Formatting Alluxio Master @ localhost
Exception in thread "main" java.lang.IllegalStateException: Alias "MEM" on tier 0 on worker (configured by alluxio.worker.tieredstore.level0.alias) is not found in global tiered storage setting: SSD
        at com.google.common.base.Preconditions.checkState(Preconditions.java:862)
        at alluxio.conf.InstancedConfiguration.checkTieredStorage(InstancedConfiguration.java:597)
        at alluxio.conf.InstancedConfiguration.validate(InstancedConfiguration.java:411)
        at alluxio.util.ConfigurationUtils.reloadProperties(ConfigurationUtils.java:443)
        at alluxio.util.ConfigurationUtils.defaults(ConfigurationUtils.java:396)
        at alluxio.cli.Format.main(Format.java:85)
```

**Comment by ns1123** [comment]
@BobLiu20 I see you have added the alias to the master container. Can you add it to the worker containers as well and retry?

**Comment by BobLiu20** [comment]
@ns1123  Unfortunately. Still error

**Comment by BobLiu20** [comment]
@ns1123 
master config:
```
docker run -d --net=host \
             -v /data/alluxio_ufs:/underStorage \
             -e ALLUXIO_MASTER_HOSTNAME=10.68.71.145 \
             -e ALLUXIO_MASTER_MOUNT_TABLE_ROOT_UFS=/underStorage \
             alluxio/alluxio:2.0.1 master
```
worker config：
```
docker run --net=host \
             -h=10.68.71.146 \
             -v /data/alluxio_ufs:/underStorage \
             -v /data/alluxio_worker:/alluxio_worker \
             -e ALLUXIO_MASTER_HOSTNAME=10.68.71.145 \
             -e ALLUXIO_JAVA_OPTS="-Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.alias=SSD -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD -Dalluxio.worker.tieredstore.level0.dirs.path=/alluxio_worker -Dalluxio.worker.tieredstore.level0.dirs.quota=200GB" \
             alluxio/alluxio:2.0.1 worker
```

worker error message:
```
Formatting Alluxio Worker @ 10.68.71.146
2019-09-26 14:18:58,877 INFO  Format - Formatting worker data folder: /alluxioworker/
2019-09-26 14:18:58,878 INFO  Format - Formatting Data path for tier 0:/dev/shm/alluxioworker
2019-09-26 14:18:58,897 INFO  Format - Formatting complete
2019-09-26 14:19:00,079 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master 10.68.71.145:19998
2019-09-26 14:19:00,080 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master 10.68.71.145:19998
2019-09-26 14:19:00,087 INFO  ConfigurationUtils - Alluxio client (version 2.0.1) is trying to load cluster level configurations
2019-09-26 14:19:00,087 INFO  ConfigurationUtils - Alluxio client (version 2.0.1) is trying to load cluster level configurations
2019-09-26 14:19:00,103 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
2019-09-26 14:19:00,103 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
2019-09-26 14:19:00,116 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=10.68.71.146, rack=null)
2019-09-26 14:19:00,302 INFO  NettyUtils - EPOLL_MODE is available
2019-09-26 14:19:00,310 INFO  BlockWorkerFactory - Creating alluxio.worker.block.BlockWorker
2019-09-26 14:19:00,310 INFO  FileSystemWorkerFactory - Creating alluxio.worker.file.FileSystemWorker
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: tmpfs is smaller than the con$
igured size: tmpfs size: 64.00MB, configured size: 200.00GB
        at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:168)
        at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:46)
        at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:38)
        at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:69)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured
 size: 200.00GB
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:529)
        at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:118)
        ... 3 more
Caused by: java.lang.IllegalStateException: tmpfs is smaller than the configured size: tmpfs size: 64.00MB, configured size: 200.00GB
        at alluxio.worker.block.meta.StorageTier.checkEnoughMemSpace(StorageTier.java:167)
        at alluxio.worker.block.meta.StorageTier.initStorageTier(StorageTier.java:120)
        at alluxio.worker.block.meta.StorageTier.newStorageTier(StorageTier.java:190)
        at alluxio.worker.block.BlockMetadataManager.<init>(BlockMetadataManager.java:68)
        at alluxio.worker.block.BlockMetadataManager.createBlockMetadataManager(BlockMetadataManager.java:83)
        at alluxio.worker.block.TieredBlockStore.<init>(TieredBlockStore.java:126)
        at alluxio.worker.block.DefaultBlockWorker.<init>(DefaultBlockWorker.java:134)
        at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:43)
        at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:26)
        at alluxio.worker.AlluxioWorkerProcess.lambda$new$0(AlluxioWorkerProcess.java:110)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-09-26 14:19:00,366 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=10.68.71.146, rack=null)
2019-09-26 14:19:00,366 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master 10.68.71.145:19998
2019-09-26 14:19:00,367 INFO  ConfigurationUtils - Alluxio client (version 2.0.1) is trying to load path level configurations
2019-09-26 14:19:00,450 INFO  log - Logging initialized @1430ms
2019-09-26 14:19:00,483 INFO  ConfigurationUtils - Alluxio client has loaded path level configurations
2019-09-26 14:19:00,535 INFO  ProcessUtils - Starting Alluxio job worker.
2019-09-26 14:19:00,538 INFO  Server - jetty-9.2.z-SNAPSHOT
2019-09-26 14:19:00,565 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@14fa86ae{/metrics/json,null,AVAILABLE}
2019-09-26 14:19:00,611 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master 10.68.71.145:19998
2019-09-26 14:19:00,612 INFO  ConfigurationUtils - Alluxio client (version 2.0.1) is trying to load cluster level configurations
2019-09-26 14:19:00,615 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
```

**Comment by ns1123** [comment]
@BobLiu20 not to worry, this is the final step. The mounted tmpfs you have in /alluxio_worker is not matching the size you specified in the `-Dalluxio.worker.tieredstore.level0.dirs.quota=200GB`. Can you try starting the Alluxio Workers with the SudoMount option? If not, you may need to check the worker container to see if the /alluxio_worker directory has the required space and potentially remount.

**Comment by bf8086** [comment]
Closing this issue as it is no longer active. Please reopen the issue if you need more help.

**Comment by xumingming** [comment]
I encountered the same issue: https://alluxio-community.slack.com/archives/CEXGGUBDK/p1594719543176100 Can you give more guidance?
